### ISSUE TITLE
OWLAPI parser ignoring catalog-v001.xml and failing to follow redirect when loading imported ontologies

### ISSUE THREAD

**Issue by rpgoldman** [owlcs/owlapi#1011]
I have had this issue when using OWLAPI indirectly through both Protege and HermiT.  I have an ontology whose IRI is `https://www.dropbox.com/s/s1e2dzw64m01f9n/container-ontology.ttl`.  When OWLAPI tries to load it *as an imported ontology* from another ontology, I get this error message (among others):

```
Parser: TurtleOntologyParser
uk.ac.manchester.cs.owl.owlapi.turtle.parser.ParseException: Encountered "" at line 1, column 1.
Was expecting one of:

--------------------------------------------------------------------------------
```

Looking at other error messages, it's clear that this is because OWLAPI is trying to parse the response page for a 301 (permanently relocated) status code.  For example:

```
Parser: ManchesterOWLSyntaxOntologyParser
Encountered '<!DOCTYPE html><html class="maestro dig-Theme--VIS" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml"><head><script nonce="OXfqsdi8Bj21N993tQ/3">' at line 1 column 1.  Expected either 'Ontology:' or 'Prefix:' (Line 1)
```

I think there are two issues here:

1. OWLAPI is not following the relocation link and loading the actual file.
2. OWLAPI is ignoring the `catalog-v001.html` file in the current working directory:

  ```
  $ fgrep https://www.dropbox.com/s/s1e2dzw64m01f9n/container-ontology.ttl catalog-v001.xml
    <uri id="Imports Wizard Entry" name="https://www.dropbox.com/s/s1e2dzw64m01f9n/container-ontology.ttl" uri="container-ontology.ttl"/>
  ```

The catalog file is as follows:

[catalog-v001.xml.txt](https://github.com/owlcs/owlapi/files/6994022/catalog-v001.xml.txt)

I am not a Java programmer, so I am not able to diagnose this much further myself. But if you could point me at some action I could take to test this and report back, I would be delighted to try.  For example, if there is some direct way to invoke OWLAPI instead of going through Protege or HermiT, that would obviously be preferable.

## Replication

To replicate, you can try loading the following ontology file:

[strateos-catalog-individuals.ttl.txt](https://github.com/owlcs/owlapi/files/6994028/strateos-catalog-individuals.ttl.txt)

I got the failure doing the following:

    java -jar ~/src/HermiT/HermiT.jar strateos-catalog-individuals.ttl

Adding the `--verbose=3` flag did not get me any more information because the system tries multiple parsers and only errors out when all have failed.

## Remarks on the 301

* If I try to get the ontology file in question with `wget` it works fine.
* If I use `curl` we can see the 301 page, and verify that it lines up with what OWLAPI is trying to parse:
```
$ curl -v  https://www.dropbox.com/s/s1e2dzw64m01f9n/container-ontology.ttl
*   Trying 162.125.3.18...
* TCP_NODELAY set
* Connected to www.dropbox.com (162.125.3.18) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Dropbox, Inc; CN=*.dropbox.com
*  start date: Oct 27 00:00:00 2020 GMT
*  expire date: Nov 21 23:59:59 2021 GMT
*  subjectAltName: host "www.dropbox.com" matched cert's "*.dropbox.com"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 High Assurance Server CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fd8fa00f600)
> GET /s/s1e2dzw64m01f9n/container-ontology.ttl HTTP/2
> Host: www.dropbox.com
> User-Agent: curl/7.64.1
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 301
< cache-control: no-cache,no-cache, no-store
< content-security-policy: sandbox
< location: /s/raw/s1e2dzw64m01f9n/container-ontology.ttl
< referrer-policy: strict-origin-when-cross-origin
< set-cookie:  locale=en; Domain=dropbox.com; expires=Sat, 15 Aug 2026 16:55:14 GMT; Path=/; secure
< set-cookie:  gvc=NzA5NzM3NTE3NjE0NzQwOTgyMDg5Nzc5NTI2OTQ4MDk1ODk3MDc%3D; expires=Sat, 15 Aug 2026 16:55:14 GMT; httponly; Path=/; secure
< set-cookie:  flash=; Domain=dropbox.com; expires=Mon, 16 Aug 2021 16:55:14 GMT; Path=/; secure
< set-cookie:  bang=; Domain=dropbox.com; expires=Mon, 16 Aug 2021 16:55:14 GMT; Path=/; secure
< set-cookie:  t=lcAI8RWAHHJ2DSsDlxDh2R5W; Domain=dropbox.com; expires=Thu, 15 Aug 2024 16:55:14 GMT; httponly; Path=/; secure
< set-cookie:  __Host-js_csrf=lcAI8RWAHHJ2DSsDlxDh2R5W; expires=Thu, 15 Aug 2024 16:55:14 GMT; Path=/; secure
< x-content-type-options: nosniff
< x-frame-options: DENY
< x-permitted-cross-domain-policies: none
< x-robots-tag: noindex, nofollow, noimageindex
< x-xss-protection: 1; mode=block
< content-type: text/html; charset=utf-8
< accept-encoding: identity,gzip
< date: Mon, 16 Aug 2021 16:55:13 GMT
< server: envoy
< strict-transport-security: max-age=31536000; includeSubDomains
< strict-transport-security: max-age=31536000; includeSubDomains
< strict-transport-security: max-age=31536000; includeSubDomains
< vary: Accept-Encoding
< x-dropbox-response-origin: far_remote
< x-dropbox-request-id: 1159c40980a249109b9182e59aea29e6
<
301 Moved Permanently
The resource has been moved to /s/raw/s1e2dzw64m01f9n/container-ontology.ttl;
you should be redirected automatically.


Connection #0 to host www.dropbox.com left intact
Closing connection 0
```

**Comment by ignazio1977** [comment]
The support for catalog files is not automatic - a mapper needs to be specified via code. HermiT doesn't do that, so this won't work from the command line tool for HermiT.

Protege supports catalog files and should be supplying the right mapping to OWLAPI (class OntologyLoader in Protege seems to be doing just that).

Can you mention the Protege and HermiT versions?

Following redirects has been supported for a while but there have been bugs fixed in relatively recent OWLAPI versions (4.5.17 and 4.5.18). Most likely Protege and HermiT are not using a recent enough version.

For catalog support outside Protege, OWLAPI supports catalog files if they are included in a zip file, i.e., the ontology files and the catalog file are zipped together. Then the following can be used:

        File file = new File("owlzipwithcatalog.zip");
        OWLZipClosureIRIMapper source = new OWLZipClosureIRIMapper(file);
        ontologyManager.getIRIMappers().add(source);

ontologyManager can then be used to load an ontology where the ontology IRI is remapped to a file name in the catalog file included in the zip file.
