### ISSUE TITLE
Question: How to Check Object Property contains super property of chain

### ISSUE THREAD

**Issue by shyamaW** [owlcs/owlapi#1012]
Hi

I am working on OWL API 5. 

Kindly assist me to get **super property of (Chain)** of a given object property OR How can I check an object property contains the axiom sub-property chain axiom.

By the way, I know to get all sub chain property axiom using this: o.getAxioms(AxiomType.SUB_PROPERTY_CHAIN_OF).

I need to get supPropertyOf chain axioms related to a particular object property

Thanking You
Shyama

**Comment by ignazio1977** [comment]
The axiom type `OWLSubPropertyChainOfAxiom` contains `getSuperProperty()` and `getPropertyChain()`, are these the methods you're after?

**Comment by shyamaW** [comment]
Many Thanks.. :) 
Got it..!!!
 ontology.getAxioms(AxiomType.SUB_PROPERTY_CHAIN_OF).forEach(s -> System.out.println("Super Property" + s.getSuperProperty()));
