### ISSUE TITLE
Question: How to know which axioms are inconsistent in the ontology

### ISSUE THREAD

**Issue by shyamaW** [owlcs/owlapi#1013]
Hi

I really appreciate it If you could assist me, how do I get all inconsistent axioms? 
I used the method: **reasoner.isConsistent()** to check whether the ontology is consistent or not. If not how do I get all inconsistent axioms?

Many thanks in advance 
Shyama

**Comment by matentzn** [comment]
What you are looking for are called "explanations", in this case explanation for inconsistent ontology. if you use ROBOT, you can use the `robot explain` method (http://robot.obolibrary.org/explain), which uses the @matthewhorridge [explanation framework](https://github.com/matthewhorridge/owlexplanation). You can get explanations for inconsistencies basically by asking an explanation for why owl:Thing is a subclass of owl:Nothing; here is an example: https://github.com/ontodev/robot/blob/36a07f110974079c783fb7b4e6c8d5a0ba30ce6e/robot-core/src/main/java/org/obolibrary/robot/ExplainOperation.java#L68

**Comment by shyamaW** [comment]
Great! Thank You very much, I'll go through it
