### ISSUE TITLE
what is the most compatible Pellet reasoner for latest OWL API 5.1.17 /5.1.18

### ISSUE THREAD

**Issue by shyamaW** [owlcs/owlapi#1018]
Hi
Up to now, I have worked with HermiT (1.4...) reasoner. However, it took a long time to perform reasoner. When I added Pellet to Protege and I noticed my ontology took few seconds for reasoning. Thus I thought to work with Pellet reasoner with OWL API. I use OWL API 5.1.17 version. Thus, I would appreciate it if you could recommend the compatible version of Pellet for the OWL API 5.1.17/5.1.18. 

Thank You
SW

**Comment by ignazio1977** [comment]
The Openllet project is the most recent fork of Pellet and works with OWLAPI 5. Version 2.6.4 works with Java 8 and newer, version 2.6.5 works with Java 11 and newer.

https://github.com/Galigator/openllet

**Comment by shyamaW** [comment]
Thank You for your prompt respond
