### ISSUE TITLE
can not load an ontology with owl functional syntax

### ISSUE THREAD

**Issue by fatong1124** [owlcs/owlapi#1019]

**Comment by matentzn** [comment]
Did you try http://visualdataweb.de/validator/?

**Comment by fatong1124** [comment]
Thank you for your prompt reply,I just want to know if this project supports OWL functional syntax,my file is too large,It's a local file,about 165MB.When I load with OWL functional syntax, it fails to run.

**Comment by fatong1124** [comment]
> Did you try http://visualdataweb.de/validator/?

Thank you for your prompt reply,I just want to know if this project supports OWL functional syntax,my file is too large,It's a local file,about 165MB.When I load with OWL functional syntax, it fails to run.

**Comment by matentzn** [comment]
It definitely does, we are using owl functional syntax everwhere. 

You can try to use http://robot.obolibrary.org/ which is a widely used wrapper of the OWLAPI, or otherwise provide a more detailed error report.

**Comment by ignazio1977** [comment]
> _No description provided._

Hi, we need a bit more information than this. Which exception do you get?

Functional syntax is supported.

**Comment by fatong1124** [comment]
![owlapi](https://user-images.githubusercontent.com/90091218/132610542-d4c0862f-c0a8-4dec-a870-f7b654f112f8.png)

**Comment by fatong1124** [comment]
This is the details of the error. Is it related to insufficient memory?
![owlapi](https://user-images.githubusercontent.com/90091218/132610663-12c7324e-5b86-46f6-9e41-7db8e11224b3.png)

**Comment by fatong1124** [comment]
Here are some details from the source code：
![snomed](https://user-images.githubusercontent.com/90091218/132611910-56d07e1e-abfa-471b-9d7c-a5f28ad37200.png)
![snomed_txt](https://user-images.githubusercontent.com/90091218/132611935-a5f4e2e9-730b-4db0-bab0-dc591531c0ce.png)
This is the error details, I used shouldLoadAndSave for the test：
![error](https://user-images.githubusercontent.com/90091218/132612095-f79b3482-27bd-49f0-a14d-0181406aab20.png)

**Comment by fatong1124** [comment]
This is the source file I want to load：
[ontology-2021-08-27_16-25-32.zip](https://github.com/owlcs/owlapi/files/7132893/ontology-2021-08-27_16-25-32.zip)

**Comment by ignazio1977** [comment]
The exception you got is raised when attempting to read `ontology-2021-08-27_16-25-32.txt` from the classpath.

The TestFiles class is a convenience for unit tests. For regular use, it's easier to just call

`manager.loadOntologyFromOntologyDocument(new FileInputStream("path/to/your/file/ontology-2021-08-27_16-25-32.txt"));
