### ISSUE TITLE
abox and tbox

### ISSUE THREAD

**Issue by luisenriqueramos1977** [owlcs/owlapi#1025]
HI!,

I wonder if it is possible to generate abox and tbox from an existing ontology created with owl api, as well as uploading a file with abox and one with a tbox in a owl api reasoner?.

Best regards

Luis Ramos

**Comment by ignazio1977** [comment]
AxiomTypes includes the lists of abox, tbox and rbox axiom types; these can be used to extract from an ontology all the axioms belonging to each box.

If you wish to feed these separately to a reasoner, you can extract the axioms from an ontology, save them as separate files, and load them in the reasoner. Similarly, you could create separate ontologies in memory - the best approach will depend on your needs.
