### ISSUE TITLE
Does any of the axiom generator classes generate inferred domains and ranges?

### ISSUE THREAD

**Issue by matentzn** [owlcs/owlapi#1027]
I was looking at https://owlcs.github.io/owlapi/apidocs_4/org/semanticweb/owlapi/util/InferredObjectPropertyAxiomGenerator.html

and wondering wether there is an axiom generator for ObjectPropertyDomainOf and range..

Thanks :)

**Comment by ignazio1977** [comment]
I can't spot one in the existing classes, so that'd need to be a new one.

**Comment by matentzn** [comment]
Just wanted to double check wether I was missing something fundamental, thanks :)
