### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space error

### ISSUE THREAD

**Issue by OmkarKatkade** [owlcs/owlapi#1033]
Hello Team,

I have a feature where I need to get subclasses of a particular class. I am using reasoner to get the same. The code for the same is something like this:

Set<OWLClass> set1 = reasoner.getSubClasses(parentClass, false).getFlattened();

This particular line of code is taking a lot of time(probably because of the HashSet) and gave me the Heap space error. For now, I have increased the heap space for the project but I would like to understand if there is a better solution to this issue. Also, the project I am working on uses 3.4.10 version of OWLAPI.

Thank you.

**Comment by ignazio1977** [comment]
Hi,
While it's possible that there's a memory issue in the OWLAPI, in scenarios like these we've always found ontology and reasoner implementation to be the deciding factors in memory requirements. Can you add information about those?
