### ISSUE TITLE
Command Line Capabilities / Tools for reasoning

### ISSUE THREAD

**Issue by 4rcadiaN** [owlcs/owlapi#1035]
Hello everyone,

I hope you had a nice christmas.

I wanted to ask if there are ways / tools to use the owl api via the command line (e.g. powershell) to do reasoning on onthologies. I am asking because I am currently automatically generating onthologies from data and now want to check the consistency of these with a reasoner. Is there a command line version/jar of the owl api or a reasoner that could make this possible?

**Comment by balhoff** [comment]
[ROBOT](http://robot.obolibrary.org/) is a CLI for OWL API.

**Comment by 4rcadiaN** [comment]
This looks very promising, thx for the info 👍.

**Comment by ignazio1977** [comment]
Recent HermiT releases also include a command line interface (same one documented on the HermiT pages)
