### ISSUE TITLE
Persistent storage

### ISSUE THREAD

**Issue by luisenriqueramos1977** [owlcs/owlapi#1039]
Dear All,

I wonder if there is a persistent storage for owl API?, I mean a DB or triple store?, because I checked this tutorial:
http://syllabus.cs.manchester.ac.uk/pgt/2021/COMP62342/introduction-owl-api-msc.pdf

and I only found reading and writing to files, not to dbs.

Best regards

Luis Ramos

**Comment by ignazio1977** [comment]
That's correct, OWLAPI doesn't include a lot of support for triple stores. There is a RioMemoryTripleSource that can read from a RDF4J source, which allows connection to a triple store, but this is not commonly used. You might take a look at ONTAPI, which implements the OWLAPI api package on top of Apache Jena and so might offer triple store access via that library.
