### ISSUE TITLE
owl-api

### ISSUE THREAD

**Issue by hafsabajwa** [owlcs/owlapi#1042]
Hello,
I am new to owl-api .
I want to load to .owl file from my local machine in eclipse. but I don't know how to do that. Could you help me with a simple tutorial or other way?

**Comment by hafsabajwa** [comment]
I have created an ontology on protege. now i want to load it on eclipse. it there any way to do that?

**Comment by ignazio1977** [comment]
Hi, the most recent tutorial is available here:http://syllabus.cs.manchester.ac.uk/pgt/2021/COMP62342/introduction-owl-api-msc.pdf

There are also examples in the wiki:
https://github.com/owlcs/owlapi/wiki/Tutorial:-A-starter's-starter
https://github.com/owlcs/owlapi/wiki/Documentation
