### ISSUE TITLE
IRI remainder not properly retrieved if starting by a digit

### ISSUE THREAD

**Issue by neobernad** [owlcs/owlapi#1049]
Hello all,

We are having IRIs whose reminder start by a digit, e.g. `https://ontology.toto.com/Toto/MyTotoOntology/1totoTerm`. If we run the following code we get the namespace wrong:

```java
IRI testIri = IRI.create("https://ontology.toto.com/Toto/MyTotoOntology/1totoTerm");
System.out.println("\t" + testIri.getNamespace()+ " - " + testIri.getRemainder());
```

It outputs this namespace and reminder:

```cmd
"https://ontology.toto.com/Toto/MyTotoOntology/1" - "totoTerm"
```

Is this due the QNAMEs cannot start by a digit? Or what would be the reason of this?

PS: I know this issue has been addressed some years ago, but it seems it is still an issue and I do not know the current status of this.

For this test we used the following owlapi version:

```xml
<dependency>
    <groupId>net.sourceforge.owlapi</groupId>
    <artifactId>owlapi-api</artifactId>
    <version>5.1.13</version>
</dependency>
<dependency>
    <groupId>net.sourceforge.owlapi</groupId>
    <artifactId>owlapi-apibinding</artifactId>
    <version>5.1.13</version>
</dependency>
```

**Comment by ignazio1977** [comment]
Yes, the split point is decided according to QName rules.

**Comment by neobernad** [comment]
Hi @ignazio1977 , thanks for the confirmation! :-)
