### ISSUE TITLE
Cannot load the ontology DOLCE from a file using the API. It never stop.

### ISSUE THREAD

**Issue by iamcrowd** [owlcs/owlapi#1058]
I also attach the fil
[dul.n3.zip](https://github.com/owlcs/owlapi/files/8522849/dul.n3.zip)
e

**Comment by iamcrowd** [comment]
This is the last message logged:

14:55:26.553 [main] DEBUG org.semanticweb.owlapi.rdf.rdfxml.parser.TripleLogger - Loaded OntologyID(OntologyIRI(<http://www.ontologydesignpatterns.org/ont/dul/DUL.owl>) VersionIRI(<null>))

**Comment by ignazio1977** [comment]
Can you share the code?
The following loads the ontology in seconds, and finds 1500 axioms in it.

        OWLOntology o = OWLManager.createOWLOntologyManager()
            .loadOntologyFromOntologyDocument(new File("/Users/ignazio/Downloads/dul.n3"));
        System.out.println("LoadDolce.main() " + o.getAxiomCount());
