### ISSUE TITLE
Patch for 4.5.x w.r.t #892?

### ISSUE THREAD

**Issue by psiotwo** [owlcs/owlapi#1067]
[This commit](https://github.com/owlcs/owlapi/commit/faf3f5eac176e7bc01ce4cdd5c8867fbb2bf2d1f#diff-184f139cebe1e5895c425491d6bfdd3f36e13f88828fbb7ace9302d59c118b61) seems to be part of the resolution for #892. It is correctly present in the 5.x releases, but could not find it in the 4.x releases, although the changelog of 4.5.15 does speak about resolving #892 in the same way as the changelog of 5.1.13 does.

In particular, in the class `tools/src/main/java/org/semanticweb/owlapi6/utility/OWLEntityRenamer.java` the following method

```public List<OWLOntologyChange> changeIRI(IRI iri, IRI newIRI)```

seems to instantiatiate the OWLObjectDuplicator as

```OWLObjectDuplicator dup = new OWLObjectDuplicator(m, uriMap);```

instead of

```OWLObjectDuplicator dup = new OWLObjectDuplicator(m, uriMap, new RemappingIndividualProvider(false, m.getOWLDataFactory()));```

which seems to be causing e.g. [this problem](https://github.com/ontodev/robot/issues/1015).

**Comment by ignazio1977** [comment]
In version 4 the relevant commits are 
ece4475b25fe79e067ed32cd88ed13edf8232f93
c9817d3c42a3c306f7d9b23afa7c86931601bc0a

Looks like the fix was made first in version 4 and then cherry picked to version 5, but the patch sets are not identical. There are two instantiations of `RemappingIndividualProvider` in version 4 `OWLEntityRenamer` but three in version 5 and 6.

**Comment by ignazio1977** [comment]
One of the OWLObjectDuplicator constructs leaves the anon remapper null.

**Comment by psiotwo** [comment]
@ignazio1977 thanks for the comment - what sort of resolution has this issue then? Do you consider it a bug in 4.5.x? Shall another ticket be created for it?

**Comment by ignazio1977** [comment]
@psiotwo it's a bug in version 4, I've fixed it, pushed the fix under #892. You should be able to see it at the top of the version4 branch.

I'll be doing a release shortly once I've sorted out a few more open issues.
