### ISSUE TITLE
Question to the construction of OWL Literals

### ISSUE THREAD

**Issue by psiotwo** [owlcs/owlapi#1070]
I have came across this question when investigating https://github.com/ontodev/robot/issues/1020.

When the plain literal "a@b" is processed using getOWLLiteral method, [it tries to interpret it as a lang literal](https://github.com/owlcs/owlapi/blob/429b50ac82da2439b3509783398dfa15c58906cc/impl/src/main/java/uk/ac/manchester/cs/owl/owlapi/OWLDataFactoryInternalsImplNoCache.java#L143). What is rationale behind this behaviour? In the ticket above, it is causing problems when at-signs are used inside a literal.

**Comment by ignazio1977** [comment]
That's the syntax for rdf:langString literals. If the literal must be interpreted as xsd:string, it should be typed explicitly. Unfortunately the syntax choices for literals are confusing to say the least, they've confused me enough times and I'm not the only one bitten by them.

**Comment by psiotwo** [comment]
@ignazio1977 thanks for pointing me to the spec - I missed that bit. Although I can understand the intention, it is _more_ than confusing, indeed ...
