### ISSUE TITLE
get owl:equivalentProperty 

### ISSUE THREAD

**Issue by abidiwaa** [owlcs/owlapi#1071]
Hello,
I am currently working on the development of a Protégé plugin allowing the extraction, the edition and the validation of ontology metadata. I use the OWL API.
For the extraction phase, my properties are retrieved from the file https://github.com/sifrproject/MOD-Ontology/blob/master/mod-v2.0_profile.ttl , my problem now is that I can't retrieve the equivalent properties for a given property in the file.
For example, for dcterms:title you can see that there are 5 equivalent properties defined in the file : cc:attributionName 
,omv:name ,schema:name ,skos:prefLabel ,foaf:name ,I would like to get a collection of String containing the 5 which doesn't work when I use EntitySearcher.getEquivalentProperties(OWLProperty e ,OWLOntology o ).

**Comment by ignazio1977** [comment]
By equivalent properties, do you mean this fragment?

    dcterms:title    dcterms:relation       cc:attributionName ,
                                            omv:name ,
                                            schema:name ,
                                            skos:prefLabel ,
                                            foaf:name ;

This isn't an OWL standard way of defining equivalent properties, so it won't be parsed to EquivalentProperty axioms. For that to work, a reasoning step would be necessary, with a reasoner that knows how to handle `dcterms:relation`

**Comment by abidiwaa** [comment]
hello , the problem is old now and the file has been modified , before there was owl:equivalentProperty but thanks anyway for your answer
