### ISSUE TITLE
Fetch the SWRLRule used in reasoning process

### ISSUE THREAD

**Issue by zeeceye** [owlcs/owlapi#1076]
How to Fetch the SWRLRule used in reasoning process?

**Comment by ignazio1977** [comment]
SWRL rules declared in an ontology can be retrieved with:

    ontology.axioms(AxiomType.SWRL_RULE);

But this says nothing about whether they are used by the reasoner during reasoning - OWLAPI offers access to them regardless of a presence of a reasoner that supports SWRL rules.

**Comment by zeeceye** [comment]
I was sad to kown it, but thank you all the same.
