### ISSUE TITLE
Remove org.openrdf.rio.RDFParserFactory

### ISSUE THREAD

**Issue by reckart** [owlcs/owlapi#1125]
The RIO RDFParserFactories shipped by owlapi no longer implement `org.openrdf.rio.RDFParserFactory`. So, `/META-INF/org.openrdf.rio.RDFParserFactory` should be removed.

```
java.util.ServiceConfigurationError: org.openrdf.rio.RDFParserFactory: org.semanticweb.owlapi.rio.RioManchesterSyntaxParserFactory not a subtype
```

**Comment by ignazio1977** [comment]
removed from version 4 and 5
