### ISSUE TITLE
Uncaught NumberFormatException when comparing (large) integers

### ISSUE THREAD

**Issue by gouttegd** [owlcs/owlapi#1126]
This issue was [initially reported](https://github.com/protegeproject/protege/issues/1191) on the Protégé bug tracker.

Protégé encounters an uncaught `NumberFormatException` in the OWL API when trying to display the `http://www.semanticweb.org/ReproduceError/Testing/SuperClass1#subclass` class from the ontology in the attached file: 
[ReproduceErrorNumberFormatException2.txt](https://github.com/owlcs/owlapi/files/14379067/ReproduceErrorNumberFormatException2.txt)

This is because of the large integer value 92740100783 in one of the class expressions defining the class.

In code, the easiest way to reproduce the bug is (assuming `df` is an `OWLDataFactory`):

```java
OWLLiteral smallInteger = df.getOWLLiteral(123);
OWLLiteral largeInteger = df.getOWLLiteral("92740100783", df.getIntegerOWLDatatype());
smallInteger.compareTo(largeInteger);
```

The `compareTo` call raises a `NumberFormatException`. I believe the issues lies in the [equals(OWLObject) method](https://github.com/owlcs/owlapi/blob/c5c2bd29b8d4be6779b8993110f8e7e56af0cf46/impl/src/main/java/uk/ac/manchester/cs/owl/owlapi/OWLLiteralImplInteger.java#L158) of the `OWLLiteralImplInteger` class:

```java
public boolean equals(Object obj) {
    if (this == obj) {
        return true;
    }
    if (!super.equals(obj)) {
        return false;
    }
    if (obj instanceof OWLLiteralImplInteger) {
        OWLLiteralImplInteger other = (OWLLiteralImplInteger) obj;
        return literal == other.literal;
    }
    if (obj instanceof OWLLiteral) {
        return ((OWLLiteral) obj).isInteger()
            && ((OWLLiteral) obj).getLiteral().charAt(0) != '0'
            && literal == ((OWLLiteral) obj).parseInteger();
    }
    return false;
}
```

because the call to `parseInteger()` is not protected. If `obj` happens to be an instance of `OWLLiteralImplNoCompression` containing the string representation of a large integer, that call will raise the `NumberFormatException`.

**Comment by ignazio1977** [comment]
Looks like there's also some funny business in the literal parsing, as the value for owl:hasValue does not have a specified datatype and so shouldn't have been parsed to an integer literal.
