### ISSUE TITLE
Many duplicated dependencies on Android while importing owlapi-distribution

### ISSUE THREAD

**Issue by Redych-the-kid** [owlcs/owlapi#1133]
I get many duplicated dependencies while importing your library in Kotlin in Android Studio

**Comment by ignazio1977** [comment]
Hi, can you add more details?

- Which OWLAPI version?
- Which duplicates? Where do the other copies come from?

**Comment by Redych-the-kid** [comment]
I'm using 
'implementation("net.sourceforge.owlapi:owlapi-distribution:4.5.7")'(higher versions doesn't work either)
Output of Gradle is in the file
[gradle_out.txt](https://github.com/owlcs/owlapi/files/15238519/gradle_out.txt)

**Comment by ignazio1977** [comment]
owlapi-distribution is an OSGi jar that includes all OWLAPI jars as dependencies packaged in the jar file. You can avoid these warnings by either excluding transitive dependencies on the net.sourceforge.owlapi group or by depending on owlapi-binding instead - that will leave out the OSGi packaging infrastructure.

These should just be warnings - the class definitions are identical.

**Comment by Redych-the-kid** [comment]
How can I do that?

**Comment by Redych-the-kid** [comment]
Fixed by switching to 4.5.6 and importing Google Guava. But now when trying to create manager, it crashes with                                                                                                     java.lang.Error: java.lang.NoSuchFieldException: No field threadLocalRandomProbe in class Ljava/lang/Thread;

**Comment by ignazio1977** [comment]
I recommend NOT going back to 4.5.6, it's years out of date.

4.7.0 is not an OWLAPI version, not sure where that's coming from. However, just switch owlapi-distribution to owlapi-apibinding should remove the duplication you're seeing.
