### ISSUE TITLE
Version 4.5.27 missing from Maven central

### ISSUE THREAD

**Issue by rzese** [owlcs/owlapi#1136]
Dear all,
on 9 May 2024, version 4.5.28 of OWLAPI was added to maven central. The problem is that version 4.5.27 is currently missing from Maven central. Unfortunately, in some of my projects I use some artifacts that in turn use this version of OWLAPI. Could version 4.5.27 be made available again on Maven Central?

Thank you very much
Best

Riccardo

**Comment by ignazio1977** [comment]
4.5.27 deployment failed midway through, and resulted in some artifacts being deployed, thus blocking further attempts at publishing 4.5.27 in full. This is why 4.5.28 was created.

How are you using 4.5.27? It was never fully published.

**Comment by rzese** [comment]
I'm using it due to pellet-owlapi, the dllearner version

**Comment by ignazio1977** [comment]
Can you add a reference to that library? The only pellet-owlapi I'm aware of uses OWLAPI 3 and has not been updated for years.

**Comment by rzese** [comment]
For reasons of compatibility so far I have used the version published by the University of Leipzig (https://maven.aksw.org/repository/internal/com/clarkparsia/pellet/pellet-distribution/)

I guess I will have to remove this compatibility. It is currently of little importance to maintain it from a semantic point of view, but it could be very labour-intensive to replace all the libraries.

**Comment by ignazio1977** [comment]
Cheers, I wasn't aware of that distribution.

They must be picking up the latest OWLAPI build available, rather than specifically 4.5.27, though, given the last release is from 2019.

I've just released 4.5.29 to correct an osgi issue. I assume your build stack will pick it up soon, if not you should be able to refer 4.5.29 in your own pom and that should work at runtime.

**Comment by rzese** [comment]
Same problem also with net.sourceforge.owlapi:owlexplanation@2.0.1

**Comment by ignazio1977** [comment]
Same as above, that library can't be referencing 4.5.27 specifically.

4.5.29 should be on maven central any minute now.

**Comment by rzese** [comment]
I confirm that working with the POM fixed the problem.

Thank you
