### ISSUE TITLE
Example Question

### ISSUE THREAD

**Issue by OrselChiang** [owlcs/owlapi#1139]

**Comment by OrselChiang** [comment]
https://github.com/owlcs/owlapi/blob/version4/contract/src/test/java/uk/ac/manchester/owl/owlapi/tutorialowled2011/TutorialSnippetsTestCase.java

本示例中的 df 似乎没有定义,使用了72次，给的Rough guide里也有出现，但也没找到定义
![OWLguide](https://github.com/owlcs/owlapi/assets/48945755/169938a9-1edc-447c-b50b-b40510c915d9)

**Comment by ignazio1977** [comment]
`df` is an instance of `org.semanticweb.owlapi.model.OWLDataFactory`

**Comment by OrselChiang** [comment]
> `df` is an instance of `org.semanticweb.owlapi.model.OWLDataFactory`

Thank you for your kind explaination!
