### ISSUE TITLE
owlapi-apibinding is missing from the owlapi-bom

### ISSUE THREAD

**Issue by reckart** [owlcs/owlapi#1154]
The  `owlapi-apibinding` module is missing from the `owlapi-bom`. However, it includes classes, in particular the `OWLManager` which seems to be the main class for loading and saving ontologies. 

Could you please add the managed version for `owlapi-apibinding` to the `owlapi-bom` as well?

**Comment by ignazio1977** [comment]
fixed, released owlapi-bom-5.5.1.1

**Comment by reckart** [comment]
Wow, that was fast :) Thanks!
