### ISSUE TITLE
Consider adding OWLObject.getFunctionalSyntaxArguments (or similar)

### ISSUE THREAD

**Issue by matthewhorridge** [owlcs/owlapi#159]
I think it would be useful to add a method to OWLObject getFunctionalSyntaxArguments (probably with a better name) to returns a list of OWLObjects corresponding to the functional syntax arguments.  I've found myself wanting this for various things that I've implemented e.g. renderers.  For version 5.0 there should be some corresponding method that works with Java 8.0's lambda expressions.

**Comment by ignazio1977** [comment]
In version 5 there is a components() method that does this, with variants for annotations (it's used for equals() and hashCode(), and also equalsIgnoreAnnotations())
