### ISSUE TITLE
Add a goal/task to build to fetch , dependency mangle, and test OWLAPI *dependents*

### ISSUE THREAD

**Issue by sesuncedu** [owlcs/owlapi#162]
4.0 and 5.0 change APIs- so tracking client compilation issues, testing shims/fixers, etc would be good. 

git is not great at dealing with multiple repositories so just copying stuff into main repo is not great idea. 

Might be worth forking copies and creating version4 / version5 branches if want to be able to test building with refactoring/fixing applied (could get complicated fast though)

Some of:
Reasoners - hermit, jfact, pellet?
Libraries: protege-owlapi?
App: protege desktop, Protege server?

Should not be in unit tests, but could be in integration tests.

**Comment by ignazio1977** [comment]
I've got a local pom to do the mangling, however it currently takes a lot of effort to move versions forward and test. Not for public consumption at this point.
