### ISSUE TITLE
Use okhttp for http URL access

### ISSUE THREAD

**Issue by sesuncedu** [owlcs/owlapi#186]
1. There is already a dependency on http components introduced via owlapi-rio (and hence on to its dependents (e.g. apibinding).  
2. ParsableOWLOntologyFactory  is fairly promiscuous in its use of URLs; canLoad()  opens and closes an inputStream just to see if it can;  loading will dereference the URL  once per parse attempt.
3. AbstractOWLParser does a lot of special case processing for http URLs, using java http connection.  There is no response cache implemented, so each fetch is repeated. 
4. [okhttp](https://github.com/square/okhttp) has more shimming , but  changes are fairly localized, so http components is not too much of a hassle

**Comment by cmungall** [comment]
I'm not sure if this is related, but the OWLAPI fails when we attempt to load http://purl.obolibrary.org/obo/pr.obo

I suspect this is something to do with a 302 redirect to an ftp site

The corresponding .owl file seems to work (but the obo is handier as it is so much more compact)

**Comment by ignazio1977** [comment]
Done in master for version 6
