### ISSUE TITLE
FSS Token Manager seems disproportionately slow

### ISSUE THREAD

**Issue by sesuncedu** [owlcs/owlapi#188]
Tokenizing an FSS dump of the Gene Ontology (file size 56MB) takes  2.29s (taken over 20 iterations, jdk8u HEAD).
Parsing the ontology takes 6.31s.
Creating a BufferedReader and reading line by line (touching each char at least once, and consing up a string) takes 0.124s

[100% CPU usage , no disk I/O]

The generated tokenizer seems rather slow.

**Comment by ignazio1977** [comment]
All improvements merged a long time ago.
