### ISSUE TITLE
OWLLiteral uses rdf:PlainLiteral for language literals instead of rdf:langString

### ISSUE THREAD

**Issue by ansell** [owlcs/owlapi#19]
OWLLiteral currently has a contract to use the datatype rdf:PlainLiteral for language literals. The current RDF-1.1 drafts however define the datatype of language literals to be rdf:langString.

If version 4 is going to be compatible with RDF-1.1 then it should be using rdf:langString.

Some of the javadoc seems to imply that rdf:langString will appear in Turtle/N-Triples as a datatype in addition to the language. In RDF-1.1 it is still not allowed to have a datatype in the Turtle document if you have a language. The parser/interpreter needs to infer rdf:langString internally for language literals.

PlainLiterals in RDF-1.1 should be typed as xsd:string internally, but I think that works properly currently.

**Comment by ansell** [comment]
Can this now be closed after the integration of pull requests to utilise both Sesame-4 (pr #454) and Commons RDF (pr #446) that are both based on RDF-1.1?

**Comment by ignazio1977** [comment]
I assume so.
