### ISSUE TITLE
Annotations on SWRL rules don't survive the round trip to/from RDF/XML

### ISSUE THREAD

**Issue by matthewhorridge** [owlcs/owlapi#200]
A possible bug report.  Needs verifying, but here for now.  Will update when I have reproduced it.

**Comment by ignazio1977** [comment]
We spotted and fixed the actual cause of this later on. It was due to old ontologies where SWRL rules had an IRI - annotations were then attached to the IRI, which is not associated to the SWRL rule in more recent parsers.
