### ISSUE TITLE
Reasoner getting the subclasses

### ISSUE THREAD

**Issue by joaofonseca-mindera** [owlcs/owlapi#237]
Imagine that you have class A and this class is subclass from class X and class Y but when i use the HermiT reasoner on Protege it inferrer that is also subclass from Z like the example bellow...

![captura de ecra 2014-07-3 as 00 55 37](https://cloud.githubusercontent.com/assets/5941079/3464121/8775945e-0246-11e4-8f10-969d31ae5a72.png)

Using the OWL API how can i get the inferred subclass from the reasoner??
...so far im using this:

```
reasoner.getSubClasses(ClassZ,true);
```

the result of this is=>Node( owl:Nothing )...

**Comment by saket24111993** [comment]
Can you please help me with a similar issue? I am also using HermiT Reasoner. I am still in the learning phase. Hence I am using the pizza ontology. Using the OWLApi I am able to obtain only two subclasses of pizza class.
![code](https://cloud.githubusercontent.com/assets/14356566/23953031/725cf1e8-09b9-11e7-99c9-9a06b7770143.PNG)
The Output is
![output](https://cloud.githubusercontent.com/assets/14356566/23953097/9bdb61e4-09b9-11e7-896f-be4258aafa43.PNG)

**Comment by sesuncedu** [comment]
True means direct subclasses only.

**Comment by saket24111993** [comment]
I changed 'true' to 'false' but the output is still the same. There are many other classes which don't get printed.
![code2](https://cloud.githubusercontent.com/assets/14356566/23953560/f8661796-09ba-11e7-8d0c-e766bda47b84.PNG)
The Output
![output2](https://cloud.githubusercontent.com/assets/14356566/23953578/0714ecae-09bb-11e7-8da8-48f326b76c52.PNG)

This is the pizza Ontology.
![onto](https://cloud.githubusercontent.com/assets/14356566/23953604/19dfdba0-09bb-11e7-9a19-088abe526541.PNG)

**Comment by saket24111993** [comment]
After some experimentation with the code, I have found that if I give an IRI of the online version of pizza ontology i.e., http://www.co-ode.org/ontologies/pizza/pizza.owl , I am able to get the desired result. But as soon as I switch to the version of ontology which is on my system, I get the faulty output. Also if I try to change the IRI, i.e., from file:/G/project/ontos/pizza.owl#Pizza to file:/G/project/ontos/pizza.owl#ValuePartition I get the same wrong output.

Can someone please explain me the correct way of using IRI, especially if the ontology is saved on the system?

**Comment by ignazio1977** [comment]
You've posted a picture instead of code, so apologies for rewriting it:

    File file = ... // no matter how you get the file
    OWLOntology o = manager.loadOntologyFromOntologyDocument(file);

No need to mention IRIs.

**Comment by saket24111993** [comment]
I apologise if I am not able to get it. But to get the subclasses of a particular class (here it is 'Pizza') I need to first locate it using a specific IRI. I my case the IRI should be "G:/project/ontos/pizza.owl#Pizza".

The code is :

public static void conceptLevel() throws OWLOntologyCreationException{
		
		OWLOntologyManager manager3 = OWLManager.createOWLOntologyManager();
		
		File file3 = new File("G:/project/ontos/pizza.owl");
		IRI docIRI3 = IRI.create(file3);
		OWLOntology ont3 = manager3.loadOntologyFromOntologyDocument(file3);
		System.out.println("Loaded " + ont3.getOntologyID());
	
		OWLReasoner reasonerFactory3 =  new Reasoner.ReasonerFactory().createReasoner(ont3);
		
		OWLDataFactory fac3 = manager3.getOWLDataFactory();
		
		IRI docIRI = IRI.create("G:/project/ontos/pizza.owl#Pizza");
		
		OWLClass pizza = fac3.getOWLClass(docIRI);
		NodeSet<OWLClass> subClses = reasonerFactory3.getSubClasses(pizza, false);
		
		Set<OWLClass> clses = subClses.getFlattened();
		System.out.println("Subclasses of pizza : ");
		for (OWLClass cls1 : clses) {
			System.out.println(" " + cls1);
		}
		
	}

No matter what I do whether I change the code from 'true' to 'false' or give a different 'docIRI' (G:/project/ontos/pizza.owl#ValuePartition) the result doesn't change.

The result is -
![output](https://cloud.githubusercontent.com/assets/14356566/23966687/4b6fe026-09e2-11e7-930d-e8c127dc617b.PNG)

Also I am not sure if this is the correct way to get the desired result from ontologies which are on the local system. 
I would be very much grateful if this issue is resolved as this has taken my good amount of time and I don't know where to look for it.

**Comment by saket24111993** [comment]
Thanks ignazio1977!! I solved my problem with your solution. Keep up the good work.
