### ISSUE TITLE
Order of axiom rendering gives suboptimal compression ratios for FSS (possibly others)

### ISSUE THREAD

**Issue by sesuncedu** [owlcs/owlapi#238]
The size of the effect was somewhat surprising.  
Using an FSS rendering of  ncbitaxon as a test case.

Compression|Size (Unsorted)|Size (Sorted)
-----------------|---------------------|------------------
none           | 455M                | 455M
gzip            |30M                   |   27M
bzip2          |21M                   |   20M
lzma           |22M                   |  17M

Since the sorted order depends on the value of any axiom annotations, it may be too expensive to do a full sort, but rendering e.g. rendering property assertion Axioms sorted by predicate might not be too expensive. 

I'm not sure how widely this result generalizes, or if its worth addressing  ; noting it here as I found it noteworthy.

**Comment by ignazio1977** [comment]
@sesuncedu has provided patches for this sorting and they have been included in version 4 and 5
