### ISSUE TITLE
IRI refactorings

### ISSUE THREAD

**Issue by sesuncedu** [owlcs/owlapi#244]
For 64-bit hotspot JVM using compressed oops (4 byte object references)
 
General Notes
----------------------------
1. Every object and array has a 12 byte header
2. Every array has an additional 4 byte length field
3. Allocations sizes must be padded to a multiple of 8 bytes 
4. The minimum size of a java object is thus 16 bytes (up to one 4 byte value, or an empty array).
 
IRI
----
Every instance of IRI contains the following instance variables 
```java
public class IRI {
    @Nonnull private final Optional<String> remainder;
    @Nonnull private final String namespace;
    private int hashCode = 0;
    private int length;
}
```

12  (header)  +  4 (remainder)  + 4(namespace) + 4 (hashCode) + 4 (length) = *28* .  
Since this is not a multiple of 8 bytes, the size is padded to **32** bytes. 

The ```namespace``` field is generally shared by multiple objects, and can be ignored for current purposes. 

The ```remainder``` field is an implementation of guava ```Optional<String>```.  
If a remainder is present, this field will reference and instance of ```Present<String>```. 
This class has a single reference member, and thus adds **16** bytes to the heap used. 

If no remainder is present, the value will be set to a single static instance of ```Absent```.  This should only happen for blank nodes, which I will ignore because blank nodes. 

```String``` has a base cost of 24 bytes, plus 16 bytes of header for the ```char[]``` value,  + 8 bytes for every four characters or part thereof.  The minimum size is thus 40 bytes for an empty string, and or 48 bytes for a non empty one. 

A remainder with an empty string thus adds **64** bytes to the size of the heap used. 

The minimum size of an IRI is thus 32 + 16 + 40 = *88* bytes, plus  8 bytes  for every four characters in the remainder. 

Quick savings 
-------------------
1. The remainder fields can be set to a static instance of "" if null or a zero length string is passed in to a builder method. 
2. ```String``` already caches the value of hash code.  The IRI hashCode is simply the sum sums of the hash of the prefix and the value of the remainder (or "" if absent). 
3. The length field is only used in one place is in the main code base (XMLWriterImpl::writeStartElement).  The performance cost of the possible cache miss will be amortized by temporally local reuse. Also, **XML**.
4.  In most cases, uses of remainder are internally fetching the value using .or(""). 
5.  New Optional instances can be created for remainder on demand if desired. 

These changes can save 24 bytes per instance. 

EDIT: these changes have been implemented. Repurposing the issue to discussion of further enhancements/refactoring.

 More serious savings involve moving to  flyweight strings, and would be part of far more extensive changes.

Refactoring
---------------
IRI should be made an abstract class with no members.  A provider could be statically injected - [though](https://code.google.com/p/google-guice/wiki/Injections#Static_Injections).  Ideally it should be an interface, and IRI creation should be done via dataFactory, but that requires careful consideration of how multiple implementations might co-exist (e.g. a concrete implementation might need to construct a new IRI whenever it is passed an IRI from a different implementation).

**Comment by ignazio1977** [comment]
#398 and #310  are relevant to IRI remainders and prefixes as well
