### ISSUE TITLE
Use of LinkedHashMultiMap in Internals is quite memory intensive.

### ISSUE THREAD

**Issue by sesuncedu** [owlcs/owlapi#246]
*Note: These dumps were taken before the changes to IRI and String Literals were made; this makes the relative overhead higher.* 

The use the guava collections LinkedHashMultiMap adds considerable overhead to indexes in internals.   

For example,for ncbiTaxon,  the overhead for the map at Internals.owlDatatypeReferences, with 3,243,648 entries, has a cost of  **172,472,672** bytes. 
This is the retained size calculated by MAT, which goes not include space used by objects reachable from other places. 

For reference:  the retained size of the OWLOntologyImpl is **1,778,394,680**.

For a dummy ontology impl, the retained size of an ArrayList of Axioms is **670,587,512**   

Every item stored in a LinkedHashMultiMap is quadruply linked; previous and next entries in order of adding to the map, and previous/next entries in the set of values for a particular key.  

This level of navigability is probably not necessary; nothing internally or in the public interface makes use of the links at the map level. 

For a possible small win, I will measure the effects of using a LinkedHashMap of LinkedHashSet (which is really a wrapped LinkedHashMap.

I will also  measure baseline heap usage for plain HashMultiMap.

**Comment by ignazio1977** [comment]
I think this is already up to date in version 5. To double check and close.
