### ISSUE TITLE
Axiom ordering - sort or keep original order?

### ISSUE THREAD

**Issue by ignazio1977** [owlcs/owlapi#273]
Having chanced upon http://douroucouli.wordpress.com/2014/03/30/the-perils-of-managing-owl-in-a-version-control-system/ I wonder if the OWLAPI should alleviate the pain of diffs on Turtle/XML syntaxes.

The simplest solution I can think of is a counter on OWLObject that keeps track of the order in which the objects were created. Then, when sorting axioms, class expressions and what have you for output, use it together with the current criteria.

Example:

Ontology contains three equivalent axioms, one class assertion

During parsing, the axioms are numbered 1, 2, 3, 4

Add new equivalent axiom, numbered 5

Output order is 
1, 2, 3, 5, 4

i.e., the new equivalent axiom is the last of the equivalent axioms list.

What are your thoughts? @matthewhorridge @cmungall anyone else?

**Comment by ignazio1977** [comment]
Simon sorted some of the syntaxes, save for manchester (and the legacy ones, e.g., krss).

**Comment by cmungall** [comment]
@sesuncedu which version of the owlapi are these fixes in? Useful to know for ensuring everyone's Protege is in sync

**Comment by cmungall** [comment]
@ignazio1977 do you know?

**Comment by ignazio1977** [comment]
Should be in all versions. I'll double check.

**Comment by cmungall** [comment]
What does all versions mean? I'm trying to figure out which versions of protege support this, and whether we need a new protege build

**Comment by ignazio1977** [comment]
All most recent versions: 3.5.2, 4.0.2 and version 5 master. It's included in the 4.1.0 release candidate as well.

From past experience, Protege 4.3 and 5 can be adapted to use 3.5.2 by dropping the 3.5.2 osgidistribution jar in the protege plugins folder.

**Comment by cmungall** [comment]
I am using Protege 5beta18 snapshot, it saves with this version of the owlapi:

```
<!-- Generated by the OWL API (version 3.5.3.20150903-2211) http://owlapi.sourceforge.net -->
```

Yet we still get spurious diffs, e.g.
https://github.com/oborel/obo-relations/commit/f9e17bf16fedaf316c9ebafe1e7f3d0ef5873ce7

This is in RDF/XML. I'm going to re-open as my understanding was that the intent was to implement deterministic ordering for non-legacy syntaxes (unless rdf/xml is considered legacy...)

Feel free to re-close but let me know where this is fully implemented

**Comment by ignazio1977** [comment]
I seem to have missed a commit on 3.5.2 when I checked. My bad.

**Comment by cmungall** [comment]
OK, was that just for rdf/xml or does it affect all?

**Comment by ignazio1977** [comment]
Not sure yet, looks like Turtle and RDF/XML

**Comment by sesuncedu** [comment]
I just finished slouching in to Bethlehem so not really brain-enabled, but
I think the relevant code is in one of the base rdf renderers. (I know that
in version 4 it changed blank node ids for the rio writers (since I had to
adjust test cases)

**Comment by ignazio1977** [comment]
@cmungall  I've fixed the issue, but one problem you'll see for that ontology is that the next save will still introduce random changes - the previous versions were not sorted. After that things should normalize.

I'll put a Protege build with the updated jar up for evaluation once I'm done.

**Comment by ignazio1977** [comment]
@sesuncedu one thing I'm not clear about is the change to `RDFXMLRenderer`

    private void writeCommentForEntity(String msg, OWLEntity entity) {
        checkNotNull(entity, msg);
        String iriString = entity.getIRI().toString();
        String labelString = labelMaker.getShortForm(entity);
        String commentString = null;
        if (!iriString.equals(labelString)) {
            commentString = labelString;
        } else {
            commentString = iriString;
        }
        writer.writeComment(XMLUtils.escapeXML(commentString));
        }

If I interpret the results correctly, this will change the banner in XML files to use the (one of the) labels for the entity being written out. That sounds like a great idea to me, but it will also introduce a number of changes to existing ontologies. Was the intention to make this configurable?

**Comment by ignazio1977** [comment]
Now fixed in the version3 branch, I've used the ontology linked by @cmungall to verify and cherry picked the manchester syntax sorting as well.
The sorting test is now the same for version 3 and 4.

I've not enabled @sesuncedu's change to use a label in RDF/XML banner for entities, as this would introduce more changes in the output. I'm planning to add it and make it switchable.

**Comment by ignazio1977** [comment]
Test build available here:
https://github.com/ignazio1977/protegetests/blob/master/Protege-5.0.0-beta-18-SNAPSHOT_owlapi354-snapshot.zip

**Comment by Public-Health-Bioinformatics** [comment]
I couldn't quite tell from the thread, so could someone summarize the sort order employed now in OWLAPI/Protege >= 5.0.0-beta-18?  Is it deterministic down to the triplet?  Does it parallel being able to sort an XML document by tag name, and then by attribute name and value, then content, or some-such? It sounds like OWLAPI sorts before it writes out to various formats, which sounds great.

In other words, now we do have diff'able ontology output via OWLAPI and Protege, with no caveats?

I appreciate all the work done on this!

**Comment by sesuncedu** [comment]
It should now be deterministic.

Hedge case:

It *is* still possible for small ontology level changes to generate
disproportionately large textual changes.
I believe that this should only occur if the output format explicitly
renders all blank nodes (e.g. N-triples), and the ontology level change
alters the number of blank nodes required to render some axioms (and which
have other axioms rendered after them).

There's not much that can be done about this, as these blank nodes don't
exist at the OWL level.  Fortunately these blank nodes are not explicitly
rendered in most formats.

Some metrics using GO are in my  2015 owled paper -
http://cgi.csc.liv.ac.uk/~valli/OWLED2015/OWLED_2015_paper_12.pdf

**Comment by ignazio1977** [comment]
To the extent that it can be tested, it is deterministic and tested to stay so. As @sesuncedu said, this is not an absolute absolute, due to a few things. However, blank node ids are generated in sequence when parsing and are used in sorting blank nodes, so corner cases should be fairly uncommon.

Node identity comes after a number of other factors; ordering is implemented as follows:

- declarations first; entities are grouped by type (annotation-object-data-properties, datatypes, classes, named individuals, I believe it's the sequence)
- Axioms ordered by type (the exact sequence is embedded in the axiom type declaration, and matches the strategy used for hashcode computation.
- General containment axioms come last; they are ordered again by axiom type.

Sequences of axioms or any other OWL objects are sorted by type first, then by values of contained properties/expressions, down to IRI (alphabetical) when necessary. Most of the time this is enough to have stable order.

**Comment by cmungall** [comment]
Everything has been working perfectly for me for the last year or so.

**Comment by Public-Health-Bioinformatics** [comment]
Great, thanks for this feedback.
