### ISSUE TITLE
Turtle parser in 3.5.x and default turtle parser in 4.0.0 cannot parse IRIs with escaped brackets in them

### ISSUE THREAD

**Issue by matthewhorridge** [owlcs/owlapi#283]
See this issue:

https://github.com/protegeproject/protege/issues/89

Perhaps it's time to ditch the custom turtle parse in 4 and use the RIO stuff instead (or at least RIO by default).

The above issue refers to this being fixed in 4.0.0 - well this is because I can use the RIO stuff.

**Comment by ignazio1977** [comment]
Rio turtle is now the first parser tried.
