### ISSUE TITLE
SWRL rules saved by older versions of OWLAPI/Protege lose annotations

### ISSUE THREAD

**Issue by ignazio1977** [owlcs/owlapi#292]
SWRL rules serialized with old versions of OWLAPI (pre 3.1) and old versions of Protege (3.5, for example) have IRIs. When parsed with recent OWLAPI versions (up to and including 4.0) annotations on such rules are parsed as annotation assertions on the IRI, but the IRI is no longer associated to the rule.

For correct parsing it is necessary to discard the IRI and map the annotations to the rule axiom instead.

**Comment by hankiz** [comment]
Hi all:
I have some problems when create rules, and how I can save the rules file(.rule) in protege4.3 version,

**Comment by ignazio1977** [comment]
Hi @hankiz, can you provide more details?
If you wish you can create a new issue.

**Comment by hankiz** [comment]
Hi @ignazio1977 ,I first have createde Ontology for one domain use protege4.3,then have write the rules in Rules plug-in in protege4.3.Now how I can save the rules as rules  file(X.rules) for ues in jena, after then I can appilication this ontology for semantic retriveling.whish your answer.thanks a lot.
I cant past this screenshot here.

**Comment by ignazio1977** [comment]
I'm not an expert about Jena rules. I've found this StackOverflow question that sounds similar to your issue: http://stackoverflow.com/questions/17357836/using-swrl-with-jena-and-pellet

**Comment by hankiz** [comment]
Thank you very much,let me see first this page,if you have another sollution please connact me. thanks again.
