### ISSUE TITLE
OWL Literal String objects can be represented more compactly

### ISSUE THREAD

**Issue by sesuncedu** [owlcs/owlapi#310]
# General Notes

 For 64-bit Hotspot with compressed object pointers:
Arrays have a 16 byte header. 
Array (and object) lengths must be aligned to an 8 byte boundary. 
Java chars are 2 bytes wide.
java.lang.String objects have an overhead of 24 bytes.
# Using NCBO taxons as data sample:

There are 3,243,649 string literals, containing a total 52,025,624 characters.
All of these characters have code points <256.
## Analysis of overhead

| Measurement | Total size | Ratio |
| --- | --- | --- |
| raw byte size | 52,025,624 | 1.00 |
| aligned byte size | 60,102,184 | 1.16 |
| raw char size | 104,051,248 | 2.00 |
| aligned char size | 114,976,048 | 2.21 |
| byte array size | 112,000,568 | 2.15 |
| char array size | 166,874,432 | 3.21 |
| String size | 244,722,008 | 4.70 |
## Deciles :

| stat | 0% | 10% | 20% | 30% | 40% | 50% | 60% | 70% | 80% | 90% | 100% |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| chars | 2 | 7 | 7 | 8 | 13 | 13 | 13 | 18 | 23 | 28 | 244 |
| raw byte size | 2 | 7 | 7 | 8 | 13 | 13 | 13 | 18 | 23 | 28 | 244 |
| raw char size | 4 | 14 | 14 | 16 | 26 | 26 | 26 | 36 | 46 | 56 | 488 |
| aligned byte size | 8 | 8 | 8 | 8 | 16 | 16 | 16 | 24 | 24 | 32 | 248 |
| aligned char size | 8 | 16 | 16 | 16 | 32 | 32 | 32 | 40 | 48 | 56 | 488 |
| byte array size | 24 | 24 | 24 | 24 | 32 | 32 | 32 | 40 | 40 | 48 | 264 |
| char array size | 24 | 32 | 32 | 32 | 48 | 48 | 48 | 56 | 64 | 72 | 504 |
| java string size | 48 | 56 | 56 | 56 | 72 | 72 | 72 | 80 | 88 | 96 | 528 |

**Comment by ignazio1977** [comment]
Java 9 will do the byte array optimisation for us -yai.
