### ISSUE TITLE
OWL2: Axiom Annotations vs. AnnotationAssertionAxioms

### ISSUE THREAD

**Issue by NicolasRouquette** [owlcs/owlapi#315]
There is a subtle difference between the two.

Although the OWL2 Functional Syntax spec clearly states that Ontologies & Axioms can have annotations (see Fig 1 in http://www.w3.org/TR/owl2-syntax),
the spec only explains the case of ontology annotations (see http://www.w3.org/TR/owl2-syntax/#Ontology_Annotations) and leaves the topic of axiom annotations somewhat unclear.

To help appreciate the distinction, I made a slight modification to a test case:

/owlapi/contract/src/test/java/org/semanticweb/owlapi/api/test/annotations/AxiomAnnotationsRoundTrippingTestCase.java

```java
    @Override
    protected OWLOntology createOntology() {
        OWLOntology ont = getOWLOntology("OntA");
        OWLAnnotationProperty prop = AnnotationProperty(OWLRDFVocabulary.RDFS_LABEL
                .getIRI());
        addAxiom(ont, Declaration(prop));
        
        OWLEntity entity = NamedIndividual(IRI("http://www.another.com/ont#peter"));
        Set<OWLAnnotation> entityAnnotations = new HashSet<>();        
        for (int i = 0; i < 2; i++) {
            OWLLiteral lit = Literal("EntityAnnotation " + (i + 1));
            entityAnnotations.add(df.getOWLAnnotation(RDFSLabel(), lit));
        }        
        addAxiom(ont, Declaration(entity, entityAnnotations));
                
        Set<OWLAnnotation> annotations = new HashSet<>();
        for (int i = 0; i < 2; i++) {
            OWLLiteral lit = Literal("Annotation " + (i + 1));
            annotations.add(df.getOWLAnnotation(RDFSLabel(), lit));
        }
        OWLAnnotationAssertionAxiom ax = df.getOWLAnnotationAssertionAxiom(
                prop, entity.getIRI(), Literal("X", "en"), annotations);
        addAxiom(ont, ax);
        return ont;
    }
```

This test creates an ontology with 3 axioms:
1) a declaration of an annotation property
2) a declaration of a named individual with 2 annotations
3) an annotation assertion axiom with 2 annotations

The problem is that (2) and (3) have identical serializations in several formats
(RDF/XML, JsonLD, Turtle, N3, …)

```rdf
<?xml version="1.0"?>
<rdf:RDF xmlns="http://www.semanticweb.org/owlapi/test/OntA#"
     xml:base="http://www.semanticweb.org/owlapi/test/OntA"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:owl="http://www.w3.org/2002/07/owl#"
     xmlns:xml="http://www.w3.org/XML/1998/namespace"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">
    <owl:Ontology rdf:about="http://www.semanticweb.org/owlapi/test/OntA"/>
    


    <!-- 
    ///////////////////////////////////////////////////////////////////////////////////////
    //
    // Annotation properties
    //
    ///////////////////////////////////////////////////////////////////////////////////////
     -->


    


    <!-- http://www.w3.org/2000/01/rdf-schema#label -->


    <owl:AnnotationProperty rdf:about="http://www.w3.org/2000/01/rdf-schema#label"/>
    


    <!-- 
    ///////////////////////////////////////////////////////////////////////////////////////
    //
    // Individuals
    //
    ///////////////////////////////////////////////////////////////////////////////////////
     -->


    


    <!-- http://www.another.com/ont#peter -->


    <owl:NamedIndividual rdf:about="http://www.another.com/ont#peter"/>
    <owl:Axiom>
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">EntityAnnotation 1</rdfs:label>
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">EntityAnnotation 2</rdfs:label>
        <owl:annotatedSource rdf:resource="http://www.another.com/ont#peter"/>
        <owl:annotatedProperty rdf:resource="http://www.w3.org/1999/02/22-rdf-syntax-ns#type"/>
        <owl:annotatedTarget rdf:resource="http://www.w3.org/2002/07/owl#NamedIndividual"/>
    </owl:Axiom>
    


    <!-- 
    ///////////////////////////////////////////////////////////////////////////////////////
    //
    // Annotations
    //
    ///////////////////////////////////////////////////////////////////////////////////////
     -->


    <rdf:Description rdf:about="http://www.another.com/ont#peter">
        <rdfs:label xml:lang="en">X</rdfs:label>
    </rdf:Description>
    <owl:Axiom>
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Annotation 1</rdfs:label>
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Annotation 2</rdfs:label>
        <owl:annotatedTarget xml:lang="en">X</owl:annotatedTarget>
        <owl:annotatedSource rdf:resource="http://www.another.com/ont#peter"/>
        <owl:annotatedProperty rdf:resource="http://www.w3.org/2000/01/rdf-schema#label"/>
    </owl:Axiom>
</rdf:RDF>



<!-- Generated by the OWL API (version 5.0.0-ALPHA) https://github.com/owlcs/owlapi/ -->
```

The subtle but important distinction between (2) and (3) is preserved in OWL Functional Syntax and OWL/XML at least.

```owl
Prefix(:=<http://www.semanticweb.org/owlapi/test/OntA#>)
Prefix(owl:=<http://www.w3.org/2002/07/owl#>)
Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>)
Prefix(xml:=<http://www.w3.org/XML/1998/namespace>)
Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>)
Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>)


Ontology(<http://www.semanticweb.org/owlapi/test/OntA>

Declaration(Annotation(rdfs:label "EntityAnnotation 1"^^xsd:string) Annotation(rdfs:label "EntityAnnotation 2"^^xsd:string) NamedIndividual(<http://www.another.com/ont#peter>))
Declaration(AnnotationProperty(rdfs:label))
AnnotationAssertion(Annotation(rdfs:label "Annotation 1"^^xsd:string) Annotation(rdfs:label "Annotation 2"^^xsd:string) rdfs:label <http://www.another.com/ont#peter> "X"@en)
)
```

This problem affects the versions 3.4.x and 3.5.x of the owl2 v3 api
I checked out the version5 from github and the problem is still there.

**Comment by ignazio1977** [comment]
The reification of annotation axioms in order to annotate them is surely a confusing topic (I feel reading the previous sentence like a mental tongue twister, which is never a good thing when trying to debug code).
I am not sure how to differentiate annotations on entities and annotations on annotation assertions, other than as shown: the first case you present is annotating the entity declaration axiom, while the second is annotating the annotation assertion. It is far from the best solution, in terms of how to understand what went wrong if parsing does not produce the expected results, but I can't tell if this is the case here.
I have tried roundtripping the ontology in Functional Syntax and RDF/XML, and the parsed ontologies contain exactly the same axioms as the original ontology, so the parsers seem to be able to rebuild the original objects.
I can see how this would fail if there were two instances of the same annotation assertion 

    Peter rdfs:label "X"

with two distinct sets of annotations. I that case, I imagine the reified axioms would look just the same, and the parser would likely merge the annotation sets into a single assertion with the union of annotations attached.
Is this part of the scenario you're presenting?

(Apologies for the late response, btw)

**Comment by ignazio1977** [comment]
As far as I can tell, the current RDF/XML serialization is equivalent to theFSS serialization and is parsed to the same axioms - matching the intentions of the original test case.

    <?xml version="1.0"?>
    <rdf:RDF xmlns="http://www.semanticweb.org/owlapi/test/OntA#"
     xml:base="http://www.semanticweb.org/owlapi/test/OntA"
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
     xmlns:owl="http://www.w3.org/2002/07/owl#"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:xml="http://www.w3.org/XML/1998/namespace">
    <owl:Ontology rdf:about="http://www.semanticweb.org/owlapi/test/OntA"/>
    
    <owl:AnnotationProperty rdf:about="http://www.w3.org/2000/01/rdf-schema#label"/>
    
    <owl:NamedIndividual rdf:about="http://www.another.com/ont#peter">
        <rdfs:label xml:lang="en">X</rdfs:label>
    </owl:NamedIndividual>
    <owl:Axiom>
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">EntityAnnotation 1</rdfs:label>
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">EntityAnnotation 2</rdfs:label>
        <owl:annotatedSource rdf:resource="http://www.another.com/ont#peter"/>
        <owl:annotatedProperty rdf:resource="http://www.w3.org/1999/02/22-rdf-syntax-ns#type"/>
        <owl:annotatedTarget rdf:resource="http://www.w3.org/2002/07/owl#NamedIndividual"/>
    </owl:Axiom>
    <owl:Axiom>
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Annotation 1</rdfs:label>
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Annotation 2</rdfs:label>
        <owl:annotatedSource rdf:resource="http://www.another.com/ont#peter"/>
        <owl:annotatedProperty rdf:resource="http://www.w3.org/2000/01/rdf-schema#label"/>
        <owl:annotatedTarget xml:lang="en">X</owl:annotatedTarget>
    </owl:Axiom>
    </rdf:RDF>


Parsing and saving as FSS: 

    Prefix(:=<http://www.semanticweb.org/owlapi/test/OntA#>)
    Prefix(owl:=<http://www.w3.org/2002/07/owl#>)
    Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>)
    Prefix(xml:=<http://www.w3.org/XML/1998/namespace>)
    Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>)
    Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>)

    Ontology(<http://www.semanticweb.org/owlapi/test/OntA>

    Declaration(Annotation(rdfs:label "EntityAnnotation 1"^^xsd:string) Annotation(rdfs:label "EntityAnnotation 2"^^xsd:string) NamedIndividual(<http://www.another.com/ont#peter>))
    Declaration(AnnotationProperty(rdfs:label))

    # Individual: <http://www.another.com/ont#peter> (X)

    AnnotationAssertion(Annotation(rdfs:label "Annotation 1"^^xsd:string) Annotation(rdfs:label "Annotation 2"^^xsd:string) rdfs:label <http://www.another.com/ont#peter> "X"@en)
    )
