### ISSUE TITLE
DefaultExplanationOrderer - seems to be required by protege, but not in 3.5.1 bundle

### ISSUE THREAD

**Issue by sesuncedu** [owlcs/owlapi#334]
The class ```uk.ac.manchester.cs.owl.explanation.ordering.DefaultExplanationOrderer ``` seems to be required by the protege mansplainer;  however, the [class lives](https://github.com/owlcs/owlapi/blob/master/contract/src/main/java/uk/ac/manchester/cs/owl/explanation/ordering/DefaultExplanationOrderer.java) in the contract tree, and doesn't seem to be in the osgi distro.   

It is marked as deprecated, but it seems odd to have it still exist (I should check the pom to see if it should be getting included, or if I have rogue local versions).

Protege builds different bits using many different versions of owlapi , but runs using osgidistribution, which does not include contract.  

I will submit a pull-request for the mansplanation-workbench  to not use the deprecated class (and to use a newer version of the protege owlapi extensions.  I'm not sure if this class should return to the tools directory, or should vanish completely.

**Comment by ignazio1977** [comment]
Should vanish - I think it has already in version 4?
There's a replacement for it, ExplanationOrdererImpl. Protege is also going to move to a release with version 4 and consequent updates of a number of projects, including owlapi extensions. I've got all this compiling locally, although I can't rule out all issues with this class.

**Comment by sesuncedu** [comment]
Yeah - it just looks like it breaks explanations in the current version 5 master

**Comment by ignazio1977** [comment]
I might try updating my pull requests for owlapi 4.0.1. Haven't checked Protege code base for a while, I know Matthew was meaning to push the update but he's been busy too.

**Comment by ignazio1977** [comment]
Protege is in the process of updating to 4.1.0  (soon as it's in RC, i.e., tomorrow)

**Comment by sesuncedu** [comment]
I am not reopening this issue, but segueing to a vaguely related issue,
which is that a) there are a few reasoners that are white-box.
It would be useful to be able to add API methods to expose this later.

If 4.1 switches language level to 1.8 then this sort of change becomes
easier to add,  as default methods can be added to interfaces.

There is already a break in backwards compatibility with 4.0 since the
return type of add-axioms has changed.

For canonical semantic versioning, the bump ought to be to major  version
5, which would require the current version5 to move higher up the chain.

A cute idea might be to skip version number 5 completely, and make putative
4.1 become 6.0.

Protégé using (the owlapi formerly known as 4) should be a  major bump from
5 (loss of backwards compatibility); both could move to 6.

Current owlapi version 5 could shift to version 7 (an auspicious number in
Asia and Cupertino)

Will copy this to the right issue when I'm at the computer. I think there
is a suitable existing issue.

**Comment by ignazio1977** [comment]
> There is already a break in backwards compatibility with 4.0 since the return type of add-axioms has changed.

True, although I considered that a bug (unfortunately visible in the interface).

Regarding the various version numbers, I have no objection at pushing them up a peg. Not sure whether it's worth adding extra methods on this branch or maybe just speeding up the release of 5.

**Comment by matthewhorridge** [comment]
>  Protégé using (the owlapi formerly known as 4) should be a  major bump from
5 (loss of backwards compatibility); both could move to 6.

Well, we are still in Beta (there's no 5 release so far).
