### ISSUE TITLE
OWLRDFConsumer fills guessed type declaration table with blank nodes

### ISSUE THREAD

**Issue by sesuncedu** [owlcs/owlapi#336]
There are a couple of issues, but the biggest problem seems to be related to cons cells being marked as data-range or class (eg in TPIntersectionOfHandler ).  These guesses get recorded, but will never get removed.   

Not recording blank nodes in the guessed type map cuts memory usage for OpenGalen-FULL by 66% when loaded from XML.

**Comment by ansell** [comment]
I was under the impression that it was necessary to record those for some cases where there are no IRI's and the intersection needed to know about the types of each subpart at some stage in the future. How does it know about the type later if the entries are not in the map?

I went through this code quite a few times when working on the Rio integration and didn't see any way around it at that point in time.

**Comment by sesuncedu** [comment]
There are two places where info is recorded: there are the  sets of IRIs
(one for classes, one for restrictions, one for each kind of property,
etc).  These are only kept for the duration of the parsing.
Then there is a multimap, which records guessed-at types, removing them if
an explicit type is seen. This is stored in the format that is kept in the
ontology manager.

The hack of  pretending that the cons cell is really a class or a datatype
does not need the multimap.

This class and the triple handlers should be refactored. I believe it will
have precisely two :-)

**Comment by ignazio1977** [comment]
Good catch, I noticed recently that the map was holding a lot of memory but didn't dig out the reason.
