### ISSUE TITLE
OWL-API: DOCTYPE declaration missing in XML serialization

### ISSUE THREAD

**Issue by ignazio1977** [owlcs/owlapi#338]
From http://answers.semanticweb.com/questions/31593/owl-api-doctype-declaration-missing-in-xml-serialization

I am using OWL API (version 3.4.4) to load, then serialize an instance of org.semanticweb.owlapi.model.OWLOntology as follows:

manager.saveOntology(ontology, format, IRI.create(destination));
Where format is an instance of org.semanticweb.owlapi.io.RDFXMLOntologyFormat, and destination is a local file URI.

While the RDF/XML file the ontology was initially loaded from contains a DOCTYPE declaration with several ENTITY prefixes used throughout the document, the resulting serialized file does not.

How can I ensure that a DOCTYPE and ENTITY elements are included in the output, so as to reduce the file size? I want to use the RDF/XML format, and without using XML entities for URI prefixes, the document is around 2x larger (or more!) than it has to be.

**Comment by ignazio1977** [comment]
To get this to work, one has currently to do the following:

    @Test
    public void shouldRoundtripEntities() throws Exception {
        String input = "<?xml version=\"1.0\"?>\n"
                + "<!DOCTYPE rdf:RDF [\n"
                + "    <!ENTITY vin  \"http://www.w3.org/TR/2004/REC-owl-guide-20040210/wine#\" >\n"
                + "    <!ENTITY food \"http://www.w3.org/TR/2004/REC-owl-guide-20040210/food#\" > ]>\n"
                + "<rdf:RDF \n"
                + "    xmlns:owl =\"http://www.w3.org/2002/07/owl#\"\n"
                + "    xmlns:rdf =\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
                + "    xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n"
                + "    xmlns:xsd =\"http://www.w3.org/2001/XMLSchema#\"> \n"
                + "<owl:Ontology rdf:about=\"\"> \n"
                + "  <rdfs:comment>An example OWL ontology</rdfs:comment>\n"
                + "  <owl:priorVersion rdf:resource=\"&vin;test\"/> \n"
                + "</owl:Ontology>" + "</rdf:RDF>";
        XMLWriterPreferences.getInstance().setUseNamespaceEntities(true);
        OWLOntology o = m
                .loadOntologyFromOntologyDocument(new StringDocumentSource(
                        input, IRI.create("urn:test"),
                        new RDFXMLDocumentFormat(), null));
        m.getOntologyFormat(o)
                .asPrefixOWLOntologyFormat()
                .setPrefix("vin:",
                        "http://www.w3.org/TR/2004/REC-owl-guide-20040210/wine#");
        StringDocumentTarget o2 = saveOntology(o);
        assertTrue(
                o2.toString(),
                o2.toString().contains(
                        "<owl:priorVersion rdf:resource=\"&vin;test\"/>"));
    }

Would be better to be able to store the entities as namespaces during parsing.

**Comment by ignazio1977** [comment]
The requirement to have entities outputted is now only to set the flag:

    XMLWriterPreferences.getInstance().setUseNamespaceEntities(true);

**Comment by milnor11** [comment]
It seems that XMLWriterPreferences has been removed from the OWLAPI at some point before version 5.0.2.  Using 5.0.2, how can one serialize an OWLOntology in RDFXML ensuring that a DOCTYPE and ENTITY elements are included in the output?

**Comment by ignazio1977** [comment]
That setting is now in `OWLOntologyWriterConfiguration`, it can be configured for each ontology manager or globally with a system property or a configuration file. See the javadoc on `ConfigurationOptions`.
