### ISSUE TITLE
ELProfile incorrectly rejects DisjointClasses axioms. 

### ISSUE THREAD

**Issue by sesuncedu** [owlcs/owlapi#343]
[OWL 2 Profiles](http://www.w3.org/TR/owl2-profiles/#Feature_Overview) says:

>OWL 2 EL supports the following axioms, all of which are restricted to the allowed set of class expressions:
> * [...]
> * class disjointness (**DisjointClasses**)
> * [...]

[OWL2ELProfile](https://github.com/owlcs/owlapi/blob/version4/api/src/main/java/org/semanticweb/owlapi/profiles/OWL2ELProfile.java#L284) says:
```java
        @Override
        public void visit(OWLDisjointClassesAxiom axiom) {
            profileViolations.add(new UseOfIllegalAxiom(getCurrentOntology(),
                    axiom));
        }

```

**Comment by ignazio1977** [comment]
Good catch. Fixed in the three branches.
