### ISSUE TITLE
owl:imports and serving gzipped or binaryowl files

### ISSUE THREAD

**Issue by cmungall** [owlcs/owlapi#348]
We serve up a lot of OWL (RDF/XML) for OBO library ontologies. This takes a bit of disk space, but more annoying (for users) is twiddling thumbs whilst the voluminous RDF/XML crawls over the wire. We often make ultra-minimal import modules but we still often need to pull a full ontology from its external URL using the owlapi

gzip gives me 20-fold smaller files; haven't tried binary OWL yet.

How should the infrastructure be set up such that we don't incur these penalties? Am happy to do what is required on the server side, not sure what is required on the owlapi/client side. Presumably sending this in the request header:

```
Accept-Encoding: gzip
```

Not sure if/how this extends to binary OWL. Just deciding on a standard name?

This may be related to #186, not sure

Maybe this is all handled already in which case I just need a nudge in the direction of the right documentation.

cc @hdietze @ShahimEssaid

**Comment by sesuncedu** [comment]
OWLAPI sends requests with  accept-encodings of gzip and deflate by default - [See AbstractOWLParser.java](https://github.com/owlcs/owlapi/blob/master/api/src/main/java/org/semanticweb/owlapi/io/AbstractOWLParser.java#L131)

Binary OWL does not compress as well as might be expected for many converted OBO files;  this is due to the lack of a sorted literal table.  OWL FSS, compresses remarkably well, but only with all axioms sorted lexicographically. Otherwise it compresses to larger files than owl in rdf/xml. 
 
xz performs much better than gzip, but is not currently supported.

**Comment by sesuncedu** [comment]
For gene_ontology_write.obo, noticed how binowl is has smallest uncompressed size, but the largest compressed size.

Also, note the difference in size between ofn with sorted axioms, and ofn without. 

format|raw     |gzip       | xz
--------|---------|-----------|--- 
binowl | **31M** | 10.0M  | 5.2M
obo    | *33M* | **4.2M**    | **2.6M**
ofn    | 99M | 6.1M     | 4.7M
ofn-sorted | 99M | *5.0M* | *3.3M*

**Comment by sesuncedu** [comment]
Using more aggressive settings for xz, we can improve compression ratios for everything but binowl:
Aggressive xz optimization gives 
 obo files  92% of the size vs straight "xz-9",
 ofn-sorted 85%, (16% bigger than obo vs 30% bigger than obo)
 ofn-unsorted  76%  (50% bigger than obo vs 80% bigger than obo) 

format|raw     |gzip       | xz | xz (slow)
--------|---------|-----------|------|------------- 
binowl        | **31M** (1)     | 10.0M  (2.4)     | 5.2M   (2.0)     | 5.2M  (2.2)
obo            | *33M*    (1.06) | **4.2M** (1)    | **2.6M** (1)  | 2.4M (1) 
ofn-sorted | 99M    (3.2)     | *5.0M* (1.2)     | *3.3M*    (1.3)  | 2.8M (1.16)
ofn            | 99M     (3.2)    | 6.1M    (1.45)   |  4.7M      (1.8)  | 3.6M (1.5)

**Comment by sesuncedu** [comment]
Running "strings" on the binowl file shows how grouping and sorting the string content improves compression:  Notice that the strings make up about 2/3rds of the binowl file, 58% of the compressed file.
Sorting reduces the size of the compressed strings by 1.2M.
format                    | raw  | compressed
-------------------------|--------|-----------------
binowl                   |31M   |  5.2M
strings                   | 21M | 3.0M
strings + sort          | 21M | 1.8M
strings +sort + uniq | 18M  | 1.8M

**Comment by cmungall** [comment]
v useful, thanks.

binowl may be moot at this point. I would like to serve it up as I understand it is faster to parse. However, if I serve a binowl in response to a request for an owl file initiated by an owl:imports in the client, then I will mess with non-binowl-compliant consumers. AFAICT there would need to be some initial handshake whereby the client says they accept binowl and the server serves this if available (presumably using `Accept-Encoding` or similar)?

Anyway, for now it seems that given the owlapi supports gzip and deflate we should write some guidelines for publishers of large OWL ontologies, helping them either turn on on-the-fly compression in apache, or storing the files compressed.

**Comment by cmungall** [comment]
xv stuff is interesting. But I'd be happy with the win of gzip for now

Also I was also assuming compressed RDF/XML since we need to support Jena etc, but maybe there is a way to have the handshake negotiate the format that is compressed too; this may need more smarts on the server but shouldn't be hard

**Comment by sesuncedu** [comment]
To enable this functionality with  apache, you can edit httpd.conf, changing the default settings for [mod_mime](http://httpd.apache.org/docs/current/mod/mod_mime.html#addencoding):

```
<IfModule mime_module>
  [...]
    AddEncoding x-gzip .gz .tgz  
  [...]
```

**Comment by sesuncedu** [comment]
mod_rewrite recipe: 
```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{HTTP:Accept-Encoding} gzip
    RewriteCond %{REQUEST_FILENAME}.gz -f
    RewriteRule (.*\.(owl))$ $1.gz [L]

</IfModule>

AddEncoding x-gzip .gz
<FilesMatch .*\.owl.gz>
    ForceType application/rdf+xml
</FilesMatch>
```

**Comment by sesuncedu** [comment]
A Large Storage BinOWL
[![10055200_m](https://cloud.githubusercontent.com/assets/411675/8810680/9c366c50-2fbe-11e5-8de6-5445090d4234.jpg)](http://www.tjskids.com/skip-hop-zoo-large-storage-bin-owl-p-17498.html)

**Comment by ignazio1977** [comment]
Love it.

**Comment by cmungall** [comment]
I don't see any ZIPs on it

**Comment by cmungall** [comment]
But it looks like it would compress nicely

**Comment by ignazio1977** [comment]
They're in there but they're small and packed tightly.

**Comment by sesuncedu** [comment]
I see feathers, but no tar.

**Comment by ignazio1977** [comment]
as per design, as it's zip instead...

**Comment by ignazio1977** [comment]
#375 implements most of it. What's left is to use the root optionally defined in a zip file as the ontology matching a document IRI of the zip file, so that I can say `http://something.com/ontology.zip` is the document IRI for the logical IRI `http://something.com.ontology.owl`. As implemented so far, I can only say there's an IRI mapper based on `http://something.com/ontology.zip` and some ontologies can be resolved from there.

**Comment by ignazio1977** [comment]
#887 allows parsing of remote gz/xz/zip files, on top of the existing support for compressed streams. So the remote files can be stored in zip/gzip form and, as long as the import ends with .gz or the content headers specify a file name with .gz, (xz/zip respectively) download and loading will work fine. OWLAPI will not try to interpret the data stream to figure out if there's a compressed file in there though.
