### ISSUE TITLE
Provide non-bundled jars

### ISSUE THREAD

**Issue by joeferner** [owlcs/owlapi#359]
I'm trying to incorporate owlapi in my project but your bundled jars are overriding my dependencies. I have newer versions of some of the libraries you are using.

**Comment by ignazio1977** [comment]
The non bundled jars are already available. You can refer owlapi-distribution, or the separate jars for each module:

http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22net.sourceforge.owlapi%22%20AND%20v%3A%224.0.1%22

You'd need owlapi-fixers	4.0.1, owlapi-rio	4.0.1, owlapi-parsers	4.0.1,  owlapi-oboformat	4.0.1, owlapi-impl	4.0.1, owlapi-api	4.0.1, owlapi-tools	4.0.1, owlapi-apibinding	4.0.1. from the above list.

If needed, also owlapi-compatibility	4.0.1

**Comment by joeferner** [comment]
I just downloaded the api and distribution jar. Both of them have com.google.common packages within the jars.

**Comment by sesuncedu** [comment]
There's a shade plugin in the parent pom.xml, but only in the release profile. This is causing the problems (and why it's hard to spot on a local build). 

Solution don't throw shade!  Also, this may be worth a quick release. 

Also why not make the artifact type bundle?

**Comment by ignazio1977** [comment]
This was discussed in the mailing list in December

https://github.com/owlcs/owlapi/commit/74d9e7c72e6f94301ac491d052fea753b7bb0063

I thought that it went in 4.0.1, but it was after that.

**Comment by sesuncedu** [comment]
Shading everything is still the wrong thing to do here (the distribution shade configuration is the only one that filters stuff out!)

**Comment by ignazio1977** [comment]
That's true, I was referring to the bundle/jar bit.

**Comment by sesuncedu** [comment]
https://github.com/owlcs/owlapi/pull/360   (tests fail because the entity expansion setting throws an exception)

**Comment by ignazio1977** [comment]
Cheers, I'll merge after fixing the tests.

**Comment by sesuncedu** [comment]
The problem was the shade, not the bundle.
 All the 3.5.2 sub-projects are bundles, with exports set to {local-package}.  The dependencies on imported packages are just marked as requirements for wiring.

**Comment by sesuncedu** [comment]
Source and javadocs are built (or not built) as required

**Comment by ignazio1977** [comment]
I've merged the fix. I'll do a 4.0.2 release as soon as I can manage to have a look at what issues are outstanding.

**Comment by joeferner** [comment]
Looks to be fixed in 4.0.2. Thanks
