### ISSUE TITLE
Thread safety issue involving OWLParserFactoryRegistry

### ISSUE THREAD

**Issue by sesuncedu** [owlcs/owlapi#361]
(The ontology is in FSS). 

```org.semanticweb.owlapi.io.UnparsableOntologyException: Problem parsing string:ontology1195
Could not parse ontology.  Either a suitable parser could not be found, or parsing failed.  See parser logs below for explanation.
The following parsers were tried:

1) RDFXMLParser
2) RDFXMLParser
3) RDFXMLParser
4) RDFXMLParser
5) RDFXMLParser
6) RDFXMLParser
7) RDFXMLParser
8) RDFXMLParser
9) RDFXMLParser
10) RDFXMLParser
11) RDFXMLParser
12) OWLXMLParser
13) TurtleOntologyParser
14) KRSS2OWLParser
15) ManchesterOWLSyntaxOntologyParser
16) OBOFormatOWLAPIParser
17) OWLOBO12Parser
```

**Comment by ignazio1977** [comment]
That's unexpected, I would have thought a few random parsers could have been missing, but not one repeated ten times.

**Comment by ignazio1977** [comment]
I can't explain right away how this happened. The parser factoy list is initialised in the OWLManager static initializer - if that was a static method, I could see multiple threads trying to call it at once and the list becoming confused, with the threads overwriting each other haphazardly. But a static initializer is supposed to be called on class load, before anything else can access it - there's a trick to ensure single initialization of singletons that relies on this behaviour. There's also no clear and no other write accesses from inside OWL API - does anything of the sort happen in protege-owlapi?

**Comment by sesuncedu** [comment]
It's triggered by tests  that mess with the registry.  I'm going to be unclean and just use a COWList, since this is all handled differently in version 4.  Storers are per-manager, and parsers are global. Sigh.

**Comment by sesuncedu** [comment]
The registry is set up in one class, and initialized in another.  OWLMananger doesn't have any lock on the class, and test classes are playing with it.

**Comment by ignazio1977** [comment]
Uhm alternatively add a synchronized  registerParsers(parser...). CopyOWriteList is good enough too.
I wonder if the clear() method should go?

**Comment by ignazio1977** [comment]
Thinking again, copy on write list won't do if adds are called multiple times, as we'd have duplicates. Concurrent linked set?

**Comment by ignazio1977** [comment]
I'm not sure if this commit is enough to fix the issue completely. OWLManager should carry out the initialization atomically now.

**Comment by sesuncedu** [comment]
I did both.  
COW was necessary because getParsers returned a view of the list (which could be modified).

**Comment by sesuncedu** [comment]
Making the registry thread safe is enough to get things working.  An extremely perverse test scheduler
