### ISSUE TITLE
Java 7 methods in Java 6 branch

### ISSUE THREAD

**Issue by hdietze** [owlcs/owlapi#368]
The 3.5.x branch is Java6 but contains currently two methods calls to Java 7 static methods.

**Comment by ignazio1977** [comment]
Weird, maven compiler is set to 1.6. Which calls?

**Comment by hdietze** [comment]
I found the error, when using a JDK6.
Unfortunately the compliance settings, still allow you to use Java 7 methods.
There is also already a commit with the two fixes.

**Comment by ignazio1977** [comment]
Cheers - I didn't expect that setting target to 1.6 would allow to reference 1.7 methods. Sounds like the compiler does not have a way to tell which methods were available in which previous version...

**Comment by ansell** [comment]
You can use animalsniffer-maven-plugin to enforce compliance with jdk6/jdk7 on the relevant branches. Eventually they will also have a jdk8 compliance checker module, but that is missing last I checked.

**Comment by ignazio1977** [comment]
I'll stick the checks in version 3 and 4

**Comment by ignazio1977** [comment]
I seem to have hit a bug in animal_sniffer :-( null pointer on checking a class, but no clues about which class cannot be found.

**Comment by ansell** [comment]
I haven't seen that bug before. Which module does it occur on?

**Comment by sesuncedu** [comment]
There's an issue with the 1.14  version of the plugin - version 1.13 works fine.  

I made a pull request, but it seems to be non-auto-mergy and I'm too fuzzy to look at it closely.  
Cherry pick if you feel like it.

**Comment by sesuncedu** [comment]
https://github.com/owlcs/owlapi/pull/369

**Comment by sesuncedu** [comment]
@ignazio1977  merged this;  the OBOAltId tests were failing as of last night, but everything else passed. 
I have not filed a ticket for animal sniffer.

**Comment by ignazio1977** [comment]
This should be fixed now.
