### ISSUE TITLE
Should RDF/XML Renderer include annotation assertions from the entire closure?

### ISSUE THREAD

**Issue by sesuncedu** [owlcs/owlapi#371]
The more I think about this, the more I agree with this guy:
 
![2344222-2040381-thorsay_thee_nay_3](https://cloud.githubusercontent.com/assets/411675/6622191/957f6b7e-c8b1-11e4-8044-de6b0a584a09.png)

**Comment by ignazio1977** [comment]
My gut feeling is no as well. the mapping from owl to RDF/XML should say something about this, I guess &lt;runs to the specs/>

**Comment by ignazio1977** [comment]
Not a word about it in the spec. Let's assume the reasonable thing is the right one to do.
