### ISSUE TITLE
ManchesterOWLSyntaxParser could use a convenience method parseClassExpression(String s)

### ISSUE THREAD

**Issue by semitrivial** [owlcs/owlapi#384]
ManchesterOWLSyntaxParser could use a convenience method parseClassExpression(String s) which would be equivalent to setStringToParse(s) followed by parseClassExpression().  (Similarly for other methods like parseClassExpressionList etc., though I don't personally need any of those.)

**Comment by ignazio1977** [comment]
Sounds like a good idea. Probably for 4.1, definitely in version 5 where we can put convenience methods on the interface
