### ISSUE TITLE
New release of Protege 4 required with a more recent version of the OWLAPI

### ISSUE THREAD

**Issue by cmungall** [owlcs/owlapi#385]
It looks like P4 is using a version of the OWLAPI from 2012.

With so many ontologies migrating to github, which uses https, we need a version of P4 that uses a v of the OWLAPI that incorporates this bug fix:
http://sourceforge.net/p/owlapi/bugs/367/

For example, the sponge ontology is served from github 
http://purl.obolibrary.org/obo/poro.owl

Works in P5 and direct load via owlapi, fails in P4
`org.xml.sax.SAXParseException: White spaces are required between publicId and systemId.`

Unfortunately our users find P5 still too crashy to use

**Comment by ignazio1977** [comment]
What's the latest Protege 4? 4.3?

**Comment by matthewhorridge** [comment]
> Unfortunately our users find P5 still too crashy to use

I would rather try and fix these problems.

**Comment by ignazio1977** [comment]
> > Unfortunately our users find P5 still too crashy to use

> I would rather try and fix these problems.

Ideally, yes. I'm guessing there are issues raised in Protege ml/issue tracker?

**Comment by matthewhorridge** [comment]
> Ideally, yes. I'm guessing there are issues raised in Protege ml/issue tracker?

There's this one  https://github.com/protegeproject/protege/issues/112

**Comment by ignazio1977** [comment]
I've had a play at hacking the 4.3.0 release to use OWLAPI 3.5.1. There's a problem with FaCT++ not finding its native libraries, so I've removed that plugin.
This is not an official Protege release, but hopefully it will be helpful as a stopgap measure 
https://github.com/ignazio1977/protegetests/blob/master/protege-4.3.0-owlapi351-nofactplusplus.zip

**Comment by cmungall** [comment]
Thanks! Will try this out
