### ISSUE TITLE
Using a PriorityCollection for IRI mappers (and perhaps other things) is confusing

### ISSUE THREAD

**Issue by matthewhorridge** [owlcs/owlapi#386]
In OWL API versions prior to 4.0.0 the order in which IRI mappers were added had a direct effect on the order in which they were used.  It seems like this is no longer the case with the priority collections.  I find this confusing - especially if custom mappers are used.  Having a simple list would be better, and more predictable I think.

@ignazio1977 please can you clarify why priority collections were introduced?  I seem to remember something about Guice and multi binders but I'm not sure.

**Comment by matthewhorridge** [comment]
I just had a quick look at #234 and #383, which seem related.  I'd like to revisit the reasons for PriorityCollection and see if we can just inject lists of factories, storers or whatever where they are needed.

**Comment by sesuncedu** [comment]
Multibinder and Mapbinder  preserve order within a single module (but only
within etc.)

**Comment by ignazio1977** [comment]
The main reason was to reduce the number of methods required to manage the collections. addX, removeX, clearX and so on.
We also added a number of parsers and a way to add more parsers, which raised the question of how to decide which parser to use first. 
PriorityCollections are just an abstraction over sorted collections, currently sorted with the HasPriority annotation.

Regarding IRI mappers, we can make this rely only on insertion order by removing all HasPriority annotations from the IRIMapper implementations.

**Comment by matthewhorridge** [comment]
> Multibinder and Mapbinder  preserve order within a single module (but only
within etc.)

I also noticed that.  

I was wondering whether it would be cleaner (and more obvious as to what was going on) if a *List* of parsers was injected where needed (same for factories and storers).  To do this, there could be a module that binds ```List<OWLParser>``` to a provider i.e. ```Provider<List<OWLParser>>```.  This provider could have a list of ```Provider<OWLParser>``` objects injected into it.  This doesn't solve the problem if you want to scatter multiple parsers over multiple modules (at least if you want them to be tried in a given order), but I think that's not a great thing to do anyway.  Clients that want customisation should really fully control the setup.

I think the issue is more problematic with IRIMappers, which almost certainly should be tried in a specific order.

> Regarding IRI mappers, we can make this rely only on insertion order by removing all HasPriority annotations from the IRIMapper implementations.

I'm not really keen on this.  If a mapper with an annotation was inserted by accident then it's order could be shifted.  I'd rather it just be a straightforward list.  (btw I don't mean to sound critical, sorry if I do!).

**Comment by ignazio1977** [comment]
On 7 Apr 2015 18:43, "Matthew Horridge" <notifications@github.com> wrote:
>>
>> Multibinder and Mapbinder preserve order within a single module (but only
>> within etc.)
>
> I also noticed that.
>
> I was wondering whether it would be cleaner (and more obvious as to what
was going on) if a List of parsers was injected where needed (same for
factories and storers). To do this, there could be a module that binds
List<OWLParser> to a provider i.e. Provider<List<OWLParser>>. This provider
could have a list of Provider<OWLParser> objects injected into it. This
doesn't solve the problem if you want to scatter multiple parsers over
multiple modules (at least if you want them to be tried in a given order),
but I think that's not a great thing to do anyway. Clients that want
customisation should really fully control the setup.
>

We have more freedom with parser order as they're mostly non overlapping.
There are exceptions though, obo and Manchester syntax being an example. I
think I saw a similar issue with one of the Rio parsers, but I still need
to recreate it.

> I think the issue is more problematic with IRIMappers, which almost
certainly should be tried in a specific order.
>>
>> Regarding IRI mappers, we can make this rely only on insertion order by
removing all HasPriority annotations from the IRIMapper implementations.
>
> I'm not really keen on this. If a mapper with an annotation was inserted
by accident then it's order could be shifted. I'd rather it just be a
straightforward list. (btw I don't mean to sound critical, sorry if I do!).
>

I think we can do this for iri mappers leaving the rest as is, by using an
ad hoc priority collection that uses insertion order for priority.
For backwards compatibility, was the old list a stack or an actual list?

**Comment by matthewhorridge** [comment]
> We have more freedom with parser order as they're mostly non overlapping.
There are exceptions though, obo and Manchester syntax being an example. I
think I saw a similar issue with one of the Rio parsers, but I still need
to recreate it.

o.k. I was just thinking about the parsers yesterday (while thinking about a concurrent OWLOntologyManager - this is how this stuff came up).  It would be the same idea with IRI mappers though.

>  I think we can do this for iri mappers leaving the rest as is, by using an
ad hoc priority collection that uses insertion order for priority.

o.k. I see.  (I still think there's some baggage here).

> For backwards compatibility, was the old list a stack or an actual list?

I think it was a stack.  Would have to go back and look.

**Comment by ignazio1977** [comment]
The old collection was a stack:
 
    @Override
    public void addIRIMapper(OWLOntologyIRIMapper mapper) {
        documentMappers.add(0, mapper);
    }

**Comment by ignazio1977** [comment]
Regarding the parsers, one problem is that the multibinding and the service loader make little guarantees on the order things will be returned, and the multibinder only allows to inject Sets directly. As you described above, we could use List providers, but we'd have to rely on whichever order is picked by the service or binder, and on whichever order the subsets of parsers coming from OWL API implementation and from RIO show up.

I guess we could cheat and, since we know the package names for the parsers we already include, we could keep the relative order of those parsers constant (i.e., all OWLAPI impl followed by all RIO implementations.)

For an input like: 
A, B, OWLAPI Y, C, RIO, OWLAPI OBO, OWLAPI TURTLE, RIO TURTLE, OWLAPI Z, D
we would have the parsers sorted as: 
A, B, OWLAPI Y, C, OWLAPI Z, RIO TURTLE, OWLAPI OBO, OWLAPI TURTLE, RIO, D

e.g, always move OBO after all OWLAPI parsers, always move RIO after OWLAPI, except for TURTLE - where we know RIO is better than OWLAPI, but we cannot discard OWLAPI yet (couple of corner cases on that).

Becomes quickly nightmarish though.

How about, injecting a collection works as it is now, and sorting is only performed on such inputs as
set(Set|Collection), while using set(List|vararg) leaves the order as specified by the arguments?
The various add() methods would not invoke sort(), so that any modification made by an user application would be free to specify the order it prefers?

**Comment by sesuncedu** [comment]
I wonder how much of this kind of prioritization should be baked in rather
than configured via properties or similar?

**Comment by ignazio1977** [comment]
Good point. It could be one extra option on OWLOntologyLoaderConfiguration.
OWLOntologyManager is already a provider for the default config, and it can be set through HasOntologyLoaderConfiguration.

Options could be: SORT_PRIORITY_COLLECTION_ALWAYS  (what it does currently), SORT_PRIORITY_COLLECTION_ON_SET_INJECTION_ONLY (what I proposed), 
SORT_PRIORITY_COLLECTION_NEVER (Collection acts as list, with initial order equal to traversal of any input collection, add() adds at the beginning, as in version 3.5.x ).

I would propose SORT_PRIORITY_COLLECTION_ON_SET_INJECTION_ONLY as default value, as it preserves current sorting of parsers and allows for fine tuning as proposed by Matthew after the injection has happened.
