### ISSUE TITLE
Use one injector per OWLOntologyManager

### ISSUE THREAD

**Issue by matthewhorridge** [owlcs/owlapi#392]
The injector in OWLManager is currently static.  If we use one injector per manager then OWLOntologyManager, OWLDataFactory and other things, in particular OWLOntologyBuilder and ReadWriteLock could be bound in singleton scope.

**Comment by matthewhorridge** [comment]
@ignazio1977 do you foresee any problems with this?

**Comment by ignazio1977** [comment]
I like the lock as an injected singleton.
I don't think we gain much by a singleton data factory per manager - an injected singleton data factory mapping to just the one data factory would make caches more efficient, although at the same time a factory that goes out of scope would also guarantee its caches to be emptied, so I'm a bit on the fence on that one.

When you say one per manager, do you mean OWLOntologyManager or OWLManager? Would we have OWLManager instances around?

**Comment by matthewhorridge** [comment]
> I like the lock as an injected singleton.

Yeah.  This makes things a whole lot easier.

> I don't think we gain much by a singleton data factory per manager - an injected singleton data factory mapping to just the one data factory would make caches more efficient, although at the same time a factory that goes out of scope would also guarantee its caches to be emptied, so I'm a bit on the fence on that one.

o.k.  It would easily give us the option either way.  We could leave as is for now.

> When you say one per manager, do you mean OWLOntologyManager or OWLManager? Would we have OWLManager instances around?

OWLOntologyManager.  No OWLManager instances around.  Basically, I'm proposing we use one injector per "contained" object graph and I'm proposing this object graph is at the level of OWLOntologyManager.

**Comment by ignazio1977** [comment]
Sounds good.

**Comment by matthewhorridge** [comment]
There's some ugliness as the OWLOntologyFactory interface specifies an OWLOntologyManager for creation and loading.  I'd rather this be injected into OWLOntologyImpl with the injector.  Hmmmm....

**Comment by ignazio1977** [comment]
Implementations can ignore the parameter. Not too nice, but compatible

**Comment by sesuncedu** [comment]
It is nice to have access to a globally shared datafactory, but it ought to
be the Ontology Manager (at least) that has the final say.

I think it would be nice to be able  to have a representation  where the
created objects belong to a single OntologyManager or document, where
property assertions, subclassing etc,  directly linked to the objects (with
the axioms being views of these objects ).

**Comment by ignazio1977** [comment]
> I think it would be nice to be able  to have a representation  where the
created objects belong to a single OntologyManager or document, where
property assertions, subclassing etc,  directly linked to the objects (with
the axioms being views of these objects ).

I can sort of see what you mean but I'm not clear on whether this API is very similar or very different from the one we have. Do you have any example of what this would allow, that cannot be done (or is hard to do) with the current one?
