### ISSUE TITLE
PriorityCollectionSorting should be fixed at manager creation time

### ISSUE THREAD

**Issue by matthewhorridge** [owlcs/owlapi#395]
... I think.  Injecting HasOntologyLoaderConfiguration into PriorityCollection doesn't make me feel good.

**Comment by ignazio1977** [comment]
Should we have a way to inject the OWLOntologyLoaderConfiguration at OWLOntologyManager creation?
I've noticed the most common use of the config is to tell the manager to be silent about missing imports, which usually happens just after it has been created. Being able to configure it from the start would save some awkward code.

**Comment by matthewhorridge** [comment]
I think that this is something to consider.
