### ISSUE TITLE
Release 4.0.2 before completing the inclusion of protege-owlapi transactionality code?

### ISSUE THREAD

**Issue by ignazio1977** [owlcs/owlapi#396]
@matthewhorridge suggested to include this code and any related changes only under a 4.1 release, as they're too much for a patch release.
However this might take a bit and 4.0.2 is quite plump with bug fixes and optimizations already; plus, a number of other projects are waiting on it being released so that they can be released as well (JFact, Pellet, HermiT, various Protege plugins).
If Protege is going to wait for the protege-owlapi code to be sorted anyway, I'd like to proceed with 4.0.2.
Thoughts, @ansell @sesuncedu ?

**Comment by ansell** [comment]
Releasing 4.0.2 is a good idea to get the bug fixes out and used/tested.

However, I don't think new features need necessarily be restricted to minor releases, although that would be the best pattern. The main distinction for minor and patch release is the size of the feature addition, which is subjective at best as a bug fix may necessarily add a new feature sometimes, so there is room for sway. The main driving feature of SemVer (and similar) is that code that relied on 4.0.x still works in any 4.x in the future, as long as it wasn't relying on a bug in 4.0.x to work (but even that is subjective).

For example, in terms of Sesame, we may have broken SemVer in 2.8.x by migrating to RDF-1.1, which appeared to be the right choice at the time. However, defining "not always checking language tag on literal before datatype" as a "bug", as the backwards incompatible part of RDF-1.1, is subjective, as there was no concept of a literal that always had a datatype in Sesame-2.1 so it was a consequence that couldn't be foreseen or tested for previously. Hence, most code written for Sesame-2.7.x and earlier is likely to have one or more cases where the language tag on a literal is lost or rdf:LangString is emitted in a concrete syntax as a datatype, in place of the language tag.

In this case, if the transactionality code can still be made to work for existing 4.0.x coded software it is low risk and although it is a new feature, could be added to 4.x, (ie, 4.0.3 or 4.1), but obviously if you don't mind waiting, 4.1 would be more indicative of the new feature addition. If it can't be made to work for 4.0.x software then 5.x would be better, but hopefully it can work without changing any of the existing methods.

**Comment by matthewhorridge** [comment]
I agree with what @ansell says.  I'd proceed with 4.0.2.  I think the concurrency stuff needs some more testing (I hope to finish it today and include an option for a concurrent or non-concurrent ontology manager).

Inline with what Peter says, my feeling is that the concurrency stuff is a big enough feature to merit a 4.1.0 release.

**Comment by ignazio1977** [comment]
Done as of yesterday evening :-)
