### ISSUE TITLE
Inject OWLDataFactoryInternals into OWLDataFactoryImpl

### ISSUE THREAD

**Issue by matthewhorridge** [owlcs/owlapi#397]
At the moment, a boolean is passed in as a parameter in order to specify the implementation of OWLDataFactoryInternals.  

A binding should be configured via the OWLAPIImplModule

**Comment by matthewhorridge** [comment]
Are the two methods below needed?  They aren't used in the project as far as I can tell (and they are not in the OWLDataFactory interface).

```java
 public boolean isCachingEnabled() {
        return cachingEnabled;
    }

public boolean isCompressionEnabled() {
        return compressionEnabled;
}
```

**Comment by sesuncedu** [comment]
I ended up adding those recently, then didn't need them for the use case.
There's a lot of stuff in data factory that ought to be delegated to the
internals (I just took the quick win for annotations)

**Comment by matthewhorridge** [comment]
@sesuncedu thanks for the clarification!  I'll get rid of them.
