### ISSUE TITLE
Losing Annotations on Annotation Assertion Axioms

### ISSUE THREAD

**Issue by jamesaoverton** [owlcs/owlapi#406]
Below is a minimal test case with one class W, an annotation X on W, and two annotations Y and Z on X. Under OWLAPI 4.0.2, Y is being silently dropped on save. This problem does not affect OWLAPI 3.5.2.

    <?xml version="1.0"?>
    <rdf:RDF xmlns="http://example.com#"
         xml:base="http://example.com"
         xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
         xmlns:owl="http://www.w3.org/2002/07/owl#"
         xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
         xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
         xmlns:oboInOwl="http://www.geneontology.org/formats/oboInOwl#">
        <owl:Ontology rdf:about="http://example.com"/>

        <owl:AnnotationProperty rdf:about="http://www.geneontology.org/formats/oboInOwl#source"/>

        <owl:Class rdf:about="http://purl.obolibrary.org/obo/UBERON_0000033">
            <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">head</rdfs:label>
            <oboInOwl:hasDbXref rdf:datatype="http://www.w3.org/2001/XMLSchema#string">UMLS:C0018670</oboInOwl:hasDbXref>
        </owl:Class>
        <owl:Axiom>
            <oboInOwl:source rdf:datatype="http://www.w3.org/2001/XMLSchema#string">NIFSTD:birnlex_1230</oboInOwl:source>
            <owl:annotatedTarget rdf:datatype="http://www.w3.org/2001/XMLSchema#string">UMLS:C0018670</owl:annotatedTarget>
            <owl:annotatedSource rdf:resource="http://purl.obolibrary.org/obo/UBERON_0000033"/>
            <owl:annotatedProperty rdf:resource="http://www.geneontology.org/formats/oboInOwl#hasDbXref"/>
        </owl:Axiom>
        <owl:Axiom>
            <owl:annotatedTarget rdf:datatype="http://www.w3.org/2001/XMLSchema#string">UMLS:C0018670</owl:annotatedTarget>
            <oboInOwl:source rdf:datatype="http://www.w3.org/2001/XMLSchema#string">ncithesaurus:Head</oboInOwl:source>
            <owl:annotatedSource rdf:resource="http://purl.obolibrary.org/obo/UBERON_0000033"/>
            <owl:annotatedProperty rdf:resource="http://www.geneontology.org/formats/oboInOwl#hasDbXref"/>
        </owl:Axiom>
    </rdf:RDF>

To reproduce, load the test case ontology, save it, then load the saved copy. The number of annotation assertion axioms on the target class is the same before and after under OWLAPI 3.5.2, but different under OWLAPI 4.0.2.

    IRI subject = IRI.create("http://purl.obolibrary.org/obo/UBERON_0000033");
    OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
    OWLOntology testcase = manager.loadOntologyFromOntologyDocument(new File("testcase.owl"));
    int before = testcase.getAnnotationAssertionAxioms(subject).size();
    manager.saveOntology(testcase, IRI.create(new File("result.owl")));
    manager.removeOntology(testcase);
    OWLOntology result = manager.loadOntologyFromOntologyDocument(new File("result.owl"));
    int after = result.getAnnotationAssertionAxioms(subject).size();
    assertEquals(before, after); // expected <3> but was <2>

**Comment by ignazio1977** [comment]
The problem seems to be with the rendering of the ontology: The output looks like this.
This is only one annotation for the annotation assertion axiom, so of course the second parsing does not provide the expected axioms.

    <owl:Axiom>
        <owl:annotatedSource rdf:resource="http://purl.obolibrary.org/obo/UBERON_0000033"/>
        <owl:annotatedProperty rdf:resource="http://www.geneontology.org/formats/oboInOwl#hasDbXref"/>
        <owl:annotatedTarget rdf:datatype="http://www.w3.org/2001/XMLSchema#string">UMLS:C0018670</owl:annotatedTarget>
        <oboInOwl:source rdf:datatype="http://www.w3.org/2001/XMLSchema#string">NIFSTD:birnlex_1230</oboInOwl:source>
    </owl:Axiom>

**Comment by ignazio1977** [comment]
The cause for this one is the use of TreeSets at rendering combined with an ancient bug: axioms are checked for equality by including annotations, but annotations are ignored when sorting them. This causes the TreeSet to ignore some axioms - namely, separate annotations assertion axioms on the same axiom. It's probably been knocked out when we started sorting axioms more reliably - ironically.
