### ISSUE TITLE
Examples file needs review

### ISSUE THREAD

**Issue by pmidford** [owlcs/owlapi#407]
It is sometimes months between times when I do something with the owlapi and I frequently use the examples file for a quick refresher.  I was recently trying to use the reasoner example to assure myself that HermiT and Elk would continue to work when I upgraded to owlapi4 (no problems there).  The problem is that the code doesn't agree with the comments, even to the point of what ontologies are loaded.  There seems to have been an incomplete attempt to substitute an inline KOALA ontology for the pizza ontology, but the comments and some of the code (no test assertions to fail I noticed) still reflect the pizza ontology and some other ontology about individuals and their pets.  And there's supposed to be an unsatisfiable class named 'mad_cow' that is only mentioned in the comments.  If co-ode and other external resources are subject to link rot, by all means move to inline the ontologies or add the owl files to the repository, but these examples (and probably the dl-query example) need a good review.

**Comment by ignazio1977** [comment]
A number of the functions in the examples are also shown in the TutorialSnippetsTestCase.
