### ISSUE TITLE
Consider renaming branches

### ISSUE THREAD

**Issue by matthewhorridge** [owlcs/owlapi#409]
I'm suggesting:

- we rename `master` to `version-3` (or something like this)
- we rename `version4` to `master`

**Comment by ignazio1977** [comment]
Not a problem for me. Will screw up people's branches, if you have anything about to be worked in a pull request, though.

**Comment by matthewhorridge** [comment]
Yes, we would of course need some sort of agreement.
I wouldn't mind keeping version4 as version4 actually.... I just have a problem with the fact that master is an old version :)

**Comment by ignazio1977** [comment]
Yeah I've thought the same.

I don't think there's anyone about to contribute pull requests on version 3.x, so it should be mostly safe to rename. Also, if there is no master branch, there won't be ambiguity  - it's not like the pull request will all of a sudden become unmergeable without explanation, GitHub will just say: there's no master branch here to issue the pull request.

**Comment by sesuncedu** [comment]
+1

**Comment by ansell** [comment]
Either not having a master branch, or having the master branch as the latest alpha version (version 5 in this case) would be useful in the long term, and when version 5 is released, it could branch and the master could become the early beginnings of version 6, or just not updated until version 6 actually gets to the planning stages.

**Comment by ignazio1977** [comment]
Renamed master to version3
