### ISSUE TITLE
about swrl

### ISSUE THREAD

**Issue by hankiz** [owlcs/owlapi#411]
hello everyone,I want to know how can saving .rules file in protege4.3 or 5.0,thank you very much.

**Comment by ignazio1977** [comment]
Hi, which format do you want your .rules file to contain?

**Comment by hankiz** [comment]
I have download some systems about semantic retrivele using jena, there have .rules file,and in the code also using .rules file,so I think there should be has the .rules file, but i can't import the file from protege -owl . And I don't know the .rules file contain which format,because i can't open the .rules file.

**Comment by ignazio1977** [comment]
Jena rules are different from swrl rules, as far as I know, and the owl api does not support them.

**Comment by hankiz** [comment]
ok,so if I want to impliment semantic retrieval use jena,and before i have builded the owl ontology containing swrl on protege,than how can i do this?

**Comment by hankiz** [comment]
hello everyone,I want to know how can write Data Range Atom of SWRL in protege4.3 or 5.0? For example, in the following rules,it is normal reasoning  the bornInYear in protege3.x,but couldn't reason in protege4.3.
Person(?p), date(?date), bornOnDate(?p, ?date), date(?date, ?year, ?month, ?day, ?timezone) -> bornInYear(?p, ?year)
