### ISSUE TITLE
Create annotation on ObjectPropertyAssertion of a specific individual

### ISSUE THREAD

**Issue by pkarop** [owlcs/owlapi#414]
I have this Java code

			PrefixManager pm = new DefaultPrefixManager(owlURI);
			OWLClass visitor = factory.getOWLClass(":Visitor", pm);
			OWLObjectProperty scans = factory.getOWLObjectProperty("scans", pm);

			OWLNamedIndividual sessionId = factory.getOWLNamedIndividual(":UserSomething", pm);
			OWLNamedIndividual poi= factory.getOWLNamedIndividual("POI", pm);

			OWLAnnotationProperty  p=factory.getOWLAnnotationProperty(IRI.create("test.owl#duration"));			
			OWLAnnotationValue val=factory.getOWLAnonymousIndividual("20");
			OWLAnnotation annotation = factory.getOWLAnnotation(p,val);
			
			OWLObjectPropertyRangeAxiom axiom1=factory.getOWLObjectPropertyRangeAxiom(scans, visitor, Collections.singleton(annotation));
					
			System.out.println(axiom1.toString());
			AddAxiom addAxiomChange1 = new AddAxiom(ontology, axiom1);
			manager.applyChange(addAxiomChange1);	

What I get is 'Visitor' class to be added in Ranges of object property 'scans', with annotation 'duration'

What I need is to add annotation 'duration', with constant value 20 to the object property assertion 'scans' 'POI' of the individual 'UserSomething'

The object property assertion 'scans' 'POI' of the individual 'UserSomething' is already added in another part of code and works.

**Comment by ignazio1977** [comment]
`Collections.singleton(annotation)` is the set of annotations that you should add to the object property assertion axiom - it's not possible to set that annotation on a range or domain axiom and get it applied to the assertions for that property, unfortunately.
