### ISSUE TITLE
Multiple OWL Facet Restrictions sorted

### ISSUE THREAD

**Issue by LorenzBuehmann** [owlcs/owlapi#417]
A small enhancement request:

Is it possible to make the set of facet restrictions(OWLFacetRestriction) of a datatype restriction(uk.ac.manchester.cs.owl.owlapi.OWLDatatypeRestrictionImpl) sorted, like it's done for nary class expressions? This would ensure that the toString() method always returns the same.

I've seen that the Manchester OWL renderer does a sort on each OWL object, thus, it's supposed to print the same string, but this does not whole for the default OWL API rendering.

For example, sometimes minInclusive and sometimes maxInclusive is printed first:

<pre>
DataSomeValuesFrom(<http://example.org/ontology/dateProperty> 
  DataRangeRestriction(xsd:date 
    facetRestriction(maxInclusive "1971-09-24"^^xsd:date)        
    facetRestriction(minInclusive "1970-10-22"^^xsd:date)))
DataSomeValuesFrom(<http://example.org/ontology/dateProperty> 
   DataRangeRestriction(xsd:date 
     facetRestriction(minInclusive "1970-01-22"^^xsd:date)
     facetRestriction(maxInclusive "1999-03-03"^^xsd:date)))
</pre>

**Comment by ignazio1977** [comment]
Good catch, we're forever chasing this sort of thing. They're annoyingly complicated to get straight.

**Comment by sesuncedu** [comment]
Manx isn't sorted yet; OFN should be.

**Comment by ignazio1977** [comment]
Now sorted and tested
