### ISSUE TITLE
[Typedef] created_by don't support space

### ISSUE THREAD

**Issue by vemonet** [owlcs/owlapi#419]
When parsing OBO files we are facing error when the "created_by: " of [Termdef] contains a space

For example "created_by: John Doe" is ok to describe a [Term] but not to describe a [Typedef]. 
But "created_by: John_Doe" works

The error raised is the following:
    Parser: org.semanticweb.owlapi.oboformat.OBOFormatOWLAPIParser@####
    LINENO: ### - expected newline or end of line but found: Doe
    LINE: created_by: John Doe

Is it a normal behavior or should it take spaces?

**Comment by ignazio1977** [comment]
Bug - according to the [spec](http://oboformat.googlecode.com/svn/trunk/doc/GO.format.obo-1_4.html) created_by behaves the same way for terms and typedefs.
