### ISSUE TITLE
ttl namespace abbreviations not preserved on serialization

### ISSUE THREAD

**Issue by tgbugs** [owlcs/owlapi#421]
When I load some ttl files with a specified prefix and then save them again the PREFIX:fragement version from the original file is not serialized but instead the full IRI is inserted in its place. An example of a file that does this is [here](https://github.com/tgbugs/methodsOntology/blob/master/ttl/hbp_abam_ontology.ttl), the issue occurs with owlapi v3 in the official protege release and in the v4 version that @ignazio1977 has [here](https://github.com/ignazio1977/protegetests/blob/master/protege-distribution-5.0.0-beta-18-SNAPSHOT-platform-independent.zip). An example of the switch:
before: ```ABA:1```
after: ```<http://api.brain-map.org/api/v2/data/Structure/1>```

**Comment by ignazio1977** [comment]
As suspected, the Turtle renderer is being overly restrictive, by using the same rules that apply to XML output for IRIs, where QNames must be preserved. Turtle has no such syntactic restrictions on IRI split points.
