### ISSUE TITLE
save ontology before reasoner call?

### ISSUE THREAD

**Issue by AneesMehdi** [owlcs/owlapi#424]
Hi,
I am trying to understand if I do have to call manager.saveOntology(O) before I can use a reasoner. This is whats happening: I add few axioms to O, say ex:a rdf:type ex:C. When I call the reasoner
to check if a is an instance of C, the reasoner returns false. 
But now if I save the ontology, and call the reasoner again, it returns true.
I was assuming that an ontology has some sort of buffer or what. May be that is not the case and one has to save the ontology before using a reasoner.

Any help or comment?

Thanks

**Comment by ignazio1977** [comment]
Saving before reasoning is not necessary.

Can you share how you create the ontology? The case you describe is unusual.

**Comment by AneesMehdi** [comment]
Thanks for the prompt reply. Well I don't create the ontology rather I load it. The ontology itself has been created using Protege. I just load it using  OWLManager, say manager:
manager.manager.loadOntologyFromOntologyDocument(new File(ontologySource))

where ontologySource holds the ontology on the harddrive.

**Comment by ignazio1977** [comment]
If the reasoner is created as a buffering reasoner, and changes to the ontology are made after the reasoner is created, it is necessary to synchronize the reasoner (or call reasoner.flush()) before the reasoner can see the updates. When loading the ontology from a file, all changes are seen at once. So this might explain what you're seeing.

**Comment by AneesMehdi** [comment]
Yes you are right iganzio1977. I am now using flush() and its working.
