### ISSUE TITLE
setting prefixes on a format harder than it should be

### ISSUE THREAD

**Issue by ignazio1977** [owlcs/owlapi#425]
http://stackoverflow.com/questions/31644894/how-to-store-owl-ontology-in-functional-syntax/31650998#31650998

This code works:

    OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
    OWLOntology ontology = manager.createOntology();
    OWLDataFactory factory = manager.getOWLDataFactory();
    FunctionalSyntaxDocumentFormat pm = new FunctionalSyntaxDocumentFormat();
    pm.setPrefix(":", "http://test.owl/test#");
    manager.setOntologyFormat(ontology, pm);
    OWLClass item = factory.getOWLClass("item", pm);
    manager.addAxiom(ontology, factory.getOWLDeclarationAxiom(item));
    manager.saveOntology(ontology, System.out);

However, this should work the same way without setting pm as the ontology format, but just passing it to saveOntology. Default prefix managers get in the way, though.

**Comment by sesuncedu** [comment]
I think I partly fixed this in my local copy this week to stop fss from ignoring the passed in format in favor of any existing saved format. Not quite right cos I needed a temporary hack for some measurements for OWLED.

**Comment by ignazio1977** [comment]
Works without any other changes on 4.1.4 and 5:

        OWLClass item = df.getOWLClass("http://test.owl/test#item");
        OWLDeclarationAxiom declaration = df.getOWLDeclarationAxiom(item);
        OWLOntology o1 = m.createOntology();
        FunctionalSyntaxDocumentFormat pm1 = new FunctionalSyntaxDocumentFormat();
        pm1.setPrefix(":", "http://test.owl/test#");
        m.setOntologyFormat(o1, pm1);
        m.addAxiom(o1, declaration);
        StringDocumentTarget t1 = new StringDocumentTarget();
        m.saveOntology(o1, t1);
        OWLOntology o2 = m1.createOntology();
        FunctionalSyntaxDocumentFormat pm2 = new FunctionalSyntaxDocumentFormat();
        pm2.setPrefix(":", "http://test.owl/test#");
        m1.addAxiom(o2, declaration);
        StringDocumentTarget t2 = new StringDocumentTarget();
        m1.saveOntology(o1, pm2, t2);
        assertTrue(t2.toString().contains("Declaration(Class(:item))"));
        assertEquals(t1.toString(), t2.toString());
