### ISSUE TITLE
hash collision in owlapi 3.5.2

### ISSUE THREAD

**Issue by ccondit** [owlcs/owlapi#428]
Just ran into a hash collision with `OWLClassExpression`s in 3.5.2. It can be reproduced with:

````
@Test
public void testHashCollision() {
    OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
    OWLDataFactory factory = manager.getOWLDataFactory();
    OWLObjectProperty BFO50 = factory.getOWLObjectProperty(IRI.create("http://purl.obolibrary.org/obo/BFO_0000050"));
    OWLObjectProperty BFO51 = factory.getOWLObjectProperty(IRI.create("http://purl.obolibrary.org/obo/BFO_0000051"));
    OWLClass UBERON2129 = factory.getOWLClass(IRI.create("http://purl.obolibrary.org/obo/UBERON_0002129"));
    OWLClass UBERON2113 = factory.getOWLClass(IRI.create("http://purl.obolibrary.org/obo/UBERON_0002113"));

    OWLClassExpression expr1 = factory.getOWLObjectSomeValuesFrom(BFO50, UBERON2129);
    OWLClassExpression expr2 = factory.getOWLObjectSomeValuesFrom(BFO51, UBERON2113);

    assertThat(expr1.hashCode(), is(not(expr2.hashCode())));
  }
````

This issue is resolved in version 4.x, but it would be nice to get a fix in 3.x if possible.

/cc @hdietze

**Comment by ansell** [comment]
Hash codes are not generally required to be unique for different objects. The only formal constraint for hashcodes is that they need to be equal if the objects are ".equals" equal.

Are the objects .equals in this case?

**Comment by ccondit** [comment]
Understood - just noticed that this was changed in 4.x to get the hash code from the URI instead of the string representation - presumably for some reason.
