### ISSUE TITLE
StructureWalker does not visit annotations

### ISSUE THREAD

**Issue by sesuncedu** [owlcs/owlapi#431]
Unless they're ontology annotations...

Is there specific reason for this?

**Comment by ignazio1977** [comment]
I don't think there should be a reason.

StructureWalker has this:

    @Override
    public void visit(OWLAnnotation node) {
        process(node);
        walkerCallback.setAnnotation(node);
        node.getProperty().accept(this);
        node.getValue().accept(this);
    }

I think this visits annotations, or am I missing a bit?

**Comment by sesuncedu** [comment]
That method is called if the walker is passed an annotation.  However, there's nothing that iterates through  any getAnnotations().  At least, not till I create a pull request...

**Comment by ignazio1977** [comment]
I believe #432 fixes it for version 4. I'll tag it for version 5.

**Comment by ignazio1977** [comment]
Done.
