### ISSUE TITLE
DisjointWith axiom issues with PROV-O  when checking for OWL RL violations

### ISSUE THREAD

**Issue by nimonika** [owlcs/owlapi#438]
The OWL API throws up "Axiom type not allowed" violations for DisjointWith axioms when checked for the PROV-O  version available at http://www.w3.org/ns/prov#. Two violations specifically reported are:

Axiom type not
allowed in profile [DisjointClasses(<http://www.w3.org/ns/prov#Agent>
<http://www.w3.org/ns/prov#InstantaneousEvent>) in
OntologyID(OntologyIRI(<http://www.w3.org/ns/prov-o#>)
VersionIRI(<http://www.w3.org/ns/prov-o-20130430>))], 

Axiom type not
allowed in profile [DisjointClasses(<http://www.w3.org/ns/prov#Activity>
<http://www.w3.org/ns/prov#Entity>) in
OntologyID(OntologyIRI(<http://www.w3.org/ns/prov-o#>)
VersionIRI(<http://www.w3.org/ns/prov-o-20130430>))], 

I think this is incorrect as per the spec at http://www.w3.org/TR/owl2-profiles/#Reasoning_in_OWL_2_RL_and_RDF_Graphs_using_Rules. Has anyone experienced this as well or am I missing something here?

**Comment by ignazio1977** [comment]
I think this is the same problem that originated #435 - can you have a read of the first few comments there and confirm?

#435 is still open due to ambiguities in the specs spotted by @sesuncedu but the disjoint bugs have been fixed and will be released with 4.1.0

**Comment by nimonika** [comment]
It is indeed. I have read that thread, but could not conclude if the issue was resolved or not, hence the separate thread.

**Comment by ignazio1977** [comment]
Cool, thank you for confirming that.

There's no release available with the fix yet, unfortunately. 4.1.0 will be released at the beginning of October.
