### ISSUE TITLE
Some methods that I can't use but that exist in the Javadoc

### ISSUE THREAD

**Issue by luispcosta** [owlcs/owlapi#440]
First of all, thank you for your hard work in this API.

I'm following the examples at `org.semanticweb.owlapi.examples.Example` but there are some methods that I can't use because Eclipse reports that that method signature does not exist. I downloaded the latest release from sourcefrog (4.0.2) and included all the .jar files into my eclipse project.

Here are some of the methods that I can't use:

### Prefix Manager
Trying to use:
```java
IRI ontologyIRI = IRI.create("...");
PrefixManager pm = new DefaultPrefixManager(null, null, ontologyIRI.toString());`
```
But the only constructors that I have available for this method are:

```java
new DefaultPrefixManager();
new DefaultPrefixManager(PrefixManager);
new DefaultPrefixManager(String);
```

### IRIMapper
Trying to use
```java
OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
IRI ontologyIRI = IRI.create("...");
IRI documentIRI = IRI.create("file:///...");
SimpleIRIMapper mapper = new SimpleIRIMapper(ontologyIRI, documentIRI);
manager.getIRIMappers().add(mapper);
```

But I can only use: (even though this method is deprecated)

```java
manager.addIRIMapper(mapper);
```

### Saving ontology
Trying to use
```java
OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
OWLOntology ontology = manager.loadOntologyFromOntologyDocument(new StringDocumentSource(KOALA));
IRI destination = IRI.create("...");
manager.saveOntology(ontology, new OWLXMLDocumentFormat(), destination);
```

But I can only use:

```java
manager.saveOntology(OWLOntology, IRI);
manager.saveOntology(OWLOntology);
```

### InferredOntologyGenerator

I'm trying to run:

```java
// ... some setup code
OWLOntology infOnt = manager.createOntology();
InferredOntologyGenerator iog = new InferredOntologyGenerator(reasoner, gens);
iog.fillOntology(manager.getOWLDataFactory(), infOnt);
```

But eclipse reports that I can only use:

```java
iog.fillOntology(manager, infOnt);
```

I don't exactly know what I'm doing wrong here. All the .jars are correctly imported into the project. I'm using Java 8 version. Why can't use these method's signatures, as described in the javadoc?

Thank you.

**Comment by luispcosta** [comment]
Ok so the API 4.0.2 at sourcefrog that I was using doesn't have some of the methods built in the API repository. I cloned this repository and built the .jar of the whole my self and included it into my project and it's working now, I can use **some** of the methods I couldn't before. 
For instance, by building the .jar myself, I still can't use the method `manager.getIRIMappers()`, it says that such method doesn't exist.
Is this normal? What's wrong with the API at sourcefrog?

**Comment by ignazio1977** [comment]
There shouldn't be any issue with that method, all the classes are in the OWLAPI-API module. The version on SourceForge is the same as the one available on Maven Central.
Can you show the classpath you're using?

**Comment by luispcosta** [comment]
I downloaded the 4.0.2 release from sourcefrog, placed the .jar file in a specific location in my file system (where I place all external libraries), opened up Eclipse, created a new project, configured the project's Java Build Path and added external JARs to the project. This is what I did. 

Sorry if that doesn't answer the question but I guess this was what you were asking

**Comment by luispcosta** [comment]
Never mind this question: I created a new project using maven and added the 4.0.2 version in the dependencies and everything seems to be working now! Sorry for the dumb question
