### ISSUE TITLE
Lost ontology annotations and blank node annotations

### ISSUE THREAD

**Issue by ignazio1977** [owlcs/owlapi#442]
Shahim Essaid reported:

if I save an anonymous individual annotation value in RDF/XML it works. I get this:

    <owl:Class rdf:about="http://E">
        <rdfs:comment>
            <rdf:Description>
                <rdfs:comment>E comment.</rdfs:comment>
            </rdf:Description>
        </rdfs:comment>
    </owl:Class>

Open and re-save in RDF/XML, still good. But if I open and save in functional then RDF/XML the annotation is lost. When saving in functional I get (also notice the persisted nodeID that I would like to see in RDF/XML):

Declaration(Class(<http://E>))
AnnotationAssertion(rdfs:comment <http://E> _:genid1)
AnnotationAssertion(rdfs:comment _:genid1 "E comment.")

Then back to RDF/XML:

    <owl:Class rdf:about="http://E">
        <rdfs:comment>
            <rdf:Description/>
        </rdfs:comment>
    </owl:Class>
    <rdf:Description>
        <rdfs:comment>E comment.</rdfs:comment>
    </rdf:Description>

This is related to an older bug about blank nodes used in ontology annotations losing their properties.

**Comment by ignazio1977** [comment]
Fixed on 3, 4, 5

**Comment by avilesg** [comment]
Seeing a similar behavior for ttl files that are loaded into Protege and saved back out.  Protege seems to be using the folloowing version of the owl api...
###  Generated by the OWL API (version 4.2.5.20160517-0735) https://github.com/owlcs/owlapi

Have you come across this?

**Comment by ignazio1977** [comment]
Do you have an example?

**Comment by avilesg** [comment]
Here's an example of the triple prior to loading into Protege:

test:subject_001 rdfs:subClassOf
[
    rdf:type owl:Restriction ;
    owl:onProperty test:property_001 ;
    owl:minQualifiedCardinality "0"^^xsd:nonNegativeInteger ;
    owl:onClass am-test:class_001 ;
    skos:editorialNote "version 1.0.13 - created for ..."
]

... and then here's what happens after making a change in protege and saving the file:

test:subject_001 rdfs:subClassOf _:blanknode_001 .
_:blanknode_001 rdf:type owl:Restriction .
_:blanknode_001 owl:onProperty test:property_001 .
_:blanknode_001 owl:minQualifiedCardinality "0"^^xsd:nonNegativeInteger .
_:blanknode_001 owl:onClass am-test:class_001 .
_:blanknode_002 skos:editorialNote "version 1.0.13 - created for ..." .
