### ISSUE TITLE
Throw error on malformed ontologies when parsing is strict (avoid Error1 classes)

### ISSUE THREAD

**Issue by hekrie** [owlcs/owlapi#444]
Reading in a turtle file with the following code:

     @prefix : <http://www.example.com#> .
     @prefix owl: <http://www.w3.org/2002/07/owl#> .
     @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
     @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
     @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
    
     :subject rdf:type owl:Class ;
       rdfs:subClassOf [ rdf:type owl:Restriction ;
                    owl:onProperty :unknownproperty;
                    owl:minCardinality "0"^^xsd:nonNegativeInteger
       ] 
    .

and simply writing it back to turtle gives the following output:

     @prefix : <http://www.example.com#> .
     @prefix owl: <http://www.w3.org/2002/07/owl#> .
     @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
     @prefix xml: <http://www.w3.org/XML/1998/namespace> .
     @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
     @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
     @base <http://www.w3.org/2002/07/owl#> .
    
    [ rdf:type owl:Ontology
    ] .
    
    
    #################################################################
    #
    #    Annotation properties
    #
    #################################################################
    
    
    ###  http://www.w3.org/2002/07/owl#minCardinality
    
    owl:minCardinality rdf:type owl:AnnotationProperty .
    
    
    
    
    
    #################################################################
    #
    #    Classes
    #
    #################################################################
    
    
    ###  http://org.semanticweb.owlapi/error#Error1
    
    <http://org.semanticweb.owlapi/error#Error1> rdf:type owl:Class .
    
    
    
    ###  http://www.example.com#subject
    
    :subject rdf:type owl:Class ;
             
             rdfs:subClassOf <http://org.semanticweb.owlapi/error#Error1> .
    
    
    
    [ owl:minCardinality "0"  xsd:nonNegativeInteger
    ] .
    
    ###  Generated by the OWL API (version 4.1.0-SNAPSHOT) https://github.com/owlcs/owlapi

The error occurs during parsing of the turtle. There seems to be no suitable ClassExpressionTranslator for this kind of property restriction and due to that the method org.semanticweb.owlapi.rdf.rdfxml.parser.Translators.TranslatorAccessor.translateClassExpressionInternal(IRI) runs into consumer.generateAndLogParseError which in the end leads to a corrupted output file. 
In this example, the property of the restriction is unknown/undefined in the current namespace. The same error occurs if the property belongs to an imported ontology. 
It would be very helpful if someone could support to a solution of this problem.

**Comment by ignazio1977** [comment]
The problem (when no imports are specified) is that the unknown property means that the parser cannot determine if the restriction is an object min cardinality or a data min cardinality. As the expression is an unqualified cardinality restriction, it cannot be inferred from the filler type.

Should probably throw an exception rather than create an Error1 class.

If the property is declared in an imported ontology, it would be a bug to not be able to parse the expression correctly.

**Comment by ignazio1977** [comment]
I've tested the case in which the property is declared in an imported ontology and that's working as expected (loaded the imported ontology manually so I didn't have to worry about providing IRIMappers):

    @Test
    public void shouldRoundtripPropertyWithMissingDeclaration() throws OWLOntologyCreationException,
        OWLOntologyStorageException {
        String imported = "@prefix : <http://www.semanticweb.org/owlapi/test/urn:test:imported#> .\n" +
            "@prefix owl: <http://www.w3.org/2002/07/owl#> .\n" +
            "@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\n" +
            "@prefix xml: <http://www.w3.org/XML/1998/namespace> .\n" +
            "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n" +
            "@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .\n" +
            "@base <http://www.semanticweb.org/owlapi/test/urn:test:imported> .\n" +
            "<http://www.example.com#imported> rdf:type owl:Ontology .\n" +
            "<http://www.example.com#unknownproperty> rdf:type owl:ObjectProperty .";
        String input = " @prefix : <http://www.example.com#> .\n" +
            " @prefix owl: <http://www.w3.org/2002/07/owl#> .\n" +
            " @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\n" +
            " @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n" +
            " @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .\n"
            + "<urn:test:testonotlogy> a owl:Ontology ;\n" +
            "    owl:imports <http://www.example.com#imported>." +
            " :subject rdf:type owl:Class ;\n" +
            "   rdfs:subClassOf [ rdf:type owl:Restriction ;\n" +
            "                owl:onProperty :unknownproperty;\n" +
            "                owl:minCardinality \"0\"^^xsd:nonNegativeInteger\n" +
            "   ] .";
        OWLOntologyManager man = OWLManager.createOWLOntologyManager();
        man.loadOntologyFromOntologyDocument(new StringDocumentSource(imported));
        OWLOntology o = man
            .loadOntologyFromOntologyDocument(
                new StringDocumentSource(input));
        // OWLOntology o = loadOntologyFromString(input);
        // man.applyChange(new AddImport(o,
        // df.getOWLImportsDeclaration(IRI.create("urn:test:imported"))));
        StringDocumentTarget t = saveOntology(o);
        System.out.println("TurtleTestCase.shouldRoundtripPropertyWithMissingDeclaration() " + t);
        assertFalse(t.toString().contains("Error"));
    }


Output:

    @prefix : <http://www.example.com#> .
    @prefix owl: <http://www.w3.org/2002/07/owl#> .
    @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
    @prefix xml: <http://www.w3.org/XML/1998/namespace> .
    @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
    <urn:test:testonotlogy> a owl:Ontology ;
	owl:imports :imported .
    :subject a owl:Class ;
	rdfs:subClassOf _:genid1 .
    _:genid1 a owl:Restriction ;
	owl:onProperty :unknownproperty ;
	owl:minCardinality "0"^^xsd:nonNegativeInteger .

**Comment by ignazio1977** [comment]
Using `ErrorX` for non well formed ontologies is an ancient feature in the API. It would be useful to be able to throw an exception in these cases, but to avoid changes in behaviour we need to make this switchable. I'll attach this to the strict/lax parsing mode.

**Comment by hekrie** [comment]
Ignazio, thank you very much for your support. 
I could reproduce your results, the restriction on the externally imported property is parsed correctly in your example. The problem still persists in my case. Could you please explain what is wrong in my approach? 
I used the following test code:

	@Test
	public void roundtripWithImport() throws OWLOntologyCreationException, OWLOntologyStorageException, FileNotFoundException
	{
		String inputTTL = "input.ttl";
		String importTTL = "imported.ttl";

		OWLOntologyManager manager = OWLManager.createOWLOntologyManager();

		manager.loadOntologyFromOntologyDocument(new java.io.File(importTTL));

		OWLOntology ontology = manager.loadOntologyFromOntologyDocument(new java.io.File(inputTTL));

		manager.applyChange(new AddImport(ontology, manager.getOWLDataFactory().getOWLImportsDeclaration(IRI.create("http://www.example.com/importontology"))));

		manager.saveOntology(ontology, manager.getOntologyFormat(ontology), new java.io.FileOutputStream(new java.io.File("output.ttl")));
	}

with input.ttl:
   
    @prefix : <http://www.example.com/inputontology#> .
    @prefix owl: <http://www.w3.org/2002/07/owl#> .
    @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
    @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
    
    <http://www.example.com/inputontology> rdf:type owl:Ontology ;
      owl:imports <http://www.example.com/importontology>
    .
      
    :subject rdf:type owl:Class ;
      rdfs:subClassOf [ rdf:type owl:Restriction ;
                        owl:onProperty :unknownproperty;
                        owl:minCardinality "0"^^xsd:nonNegativeInteger
                      ] 
    .

and imported.ttl:

     @prefix : <http://www.example.com/importontology#> .
     @prefix owl: <http://www.w3.org/2002/07/owl#> .
     @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
     @prefix xml: <http://www.w3.org/XML/1998/namespace> .
     @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
     @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
     @base <http://www.example.com/importontology> .
    
    <http://www.example.com/importontology> rdf:type owl:Ontology .
    
    :unknownproperty rdf:type owl:ObjectProperty .

which gives an output.ttl with error:

     @prefix : <http://www.example.com/inputontology#> .
     @prefix owl: <http://www.w3.org/2002/07/owl#> .
     @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
     @prefix xml: <http://www.w3.org/XML/1998/namespace> .
     @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
     @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
    
    <http://www.example.com/inputontology> a owl:Ontology ;
    	owl:imports <http://www.example.com/importontology> .
    # 
    # 
    # #################################################################
    # #
    # #    Annotation properties
    # #
    # #################################################################
    # 
    # 
    # http://www.w3.org/2002/07/owl#minCardinality
    
    owl:minCardinality a owl:AnnotationProperty .
    # 
    # 
    # 
    # #################################################################
    # #
    # #    Classes
    # #
    # #################################################################
    # 
    # 
    # http://org.semanticweb.owlapi/error#Error1
    
    <http://org.semanticweb.owlapi/error#Error1> a owl:Class .
    # 
    # http://www.example.com/inputontology#subject
    
    :subject a owl:Class ;
    	rdfs:subClassOf <http://org.semanticweb.owlapi/error#Error1> .
    # 
    
    _:genid1 owl:minCardinality "0"^^xsd:nonNegativeInteger .
    # Generated by the OWL API (version 4.1.0-SNAPSHOT) https://github.com/owlcs/owlapi
    
I suppose the problem is the definition of the IRI or the mapping of IRIs. Do you have an idea?

**Comment by ignazio1977** [comment]
:unknownproperty is a relative iri in both ontologies, but their base is different, so the iris are different. Declare the property with its full IRI and make sure it's used the same way - easier to have the same namespace abbreviation in both ontologies, probably.

**Comment by hekrie** [comment]
Thanks again. So the problem was between chair and screen :-)
I appreciate your support. 
Greetings!

**Comment by ignazio1977** [comment]
I need this open to remember to do the exception throwing in strict mode.
