### ISSUE TITLE
Axioms with the same semantics are ignored

### ISSUE THREAD

**Issue by teymourlouie** [owlcs/owlapi#445]
I have an ontology with these axioms:
```xml
<owl:Class rdf:about="http://dbpedia.org/ontology/ClubMoss">
        <rdfs:subClassOf rdf:resource="http://dbpedia.org/ontology/Plant"/>
    </owl:Class>
    <owl:Axiom>
        <owl:annotatedSource rdf:resource="http://dbpedia.org/ontology/ClubMoss"/>
        <owl:annotatedProperty rdf:resource="http://www.w3.org/2000/01/rdf-schema#subClassOf"/>
        <owl:annotatedTarget rdf:resource="http://dbpedia.org/ontology/Plant"/>
        <annotations:confidence rdf:datatype="http://www.w3.org/2001/XMLSchema#double">1.0</annotations:confidence>
        <annotations:support rdf:datatype="http://www.w3.org/2001/XMLSchema#double">0.004</annotations:support>
    </owl:Axiom>
```
When I load the ontology, I expected to have two SubClassOf axioms in my ontology, but owlapi ignores the subclassof axiom which has no annotations. So ontology will have just one of these axioms.
used api version: 4.1.0-RC2

**Comment by teymourlouie** [comment]
the full ontology is like this:
```xml
<?xml version="1.0"?>
<rdf:RDF xmlns="http://dwsrg.ir/debugger/buglist/cached/"
     xml:base="http://dwsrg.ir/debugger/buglist/cached/"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:owl="http://www.w3.org/2002/07/owl#"
     xmlns:xml="http://www.w3.org/XML/1998/namespace"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
     xmlns:annotations="http://ki.informatik.uni-mannheim.de/gold-miner/annotations#"
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">
    <owl:Ontology rdf:about="http://dwsrg.ir/debugger/buglist/cached/"/>
    <!-- 
    ///////////////////////////////////////////////////////////////////////////////////////
    //
    // Annotation properties
    //
    ///////////////////////////////////////////////////////////////////////////////////////
     -->
    <!-- confidence -->

    <owl:AnnotationProperty rdf:about="http://ki.informatik.uni-mannheim.de/gold-miner/annotations#confidence"/>
    
   <!-- support -->

    <owl:AnnotationProperty rdf:about="http://ki.informatik.uni-mannheim.de/gold-miner/annotations#support"/>
    <!-- 
    ///////////////////////////////////////////////////////////////////////////////////////
    //
    // Classes
    //
    ///////////////////////////////////////////////////////////////////////////////////////
     -->
    <!-- ClubMoss -->

    <owl:Class rdf:about="http://dbpedia.org/ontology/ClubMoss">
        <rdfs:subClassOf rdf:resource="http://dbpedia.org/ontology/Plant"/>
    </owl:Class>
    <owl:Axiom>
        <owl:annotatedSource rdf:resource="http://dbpedia.org/ontology/ClubMoss"/>
        <owl:annotatedProperty rdf:resource="http://www.w3.org/2000/01/rdf-schema#subClassOf"/>
        <owl:annotatedTarget rdf:resource="http://dbpedia.org/ontology/Plant"/>
        <annotations:confidence rdf:datatype="http://www.w3.org/2001/XMLSchema#double">1.0</annotations:confidence>
        <annotations:support rdf:datatype="http://www.w3.org/2001/XMLSchema#double">0.004</annotations:support>
    </owl:Axiom>
</rdf:RDF>


<!-- Generated by the OWL API (version 4.1.0-RC2.20150605-1957) http://owlapi.sourceforge.net -->

```

**Comment by ignazio1977** [comment]
On 20 Oct 2015 1:07 pm, "teymourlouie" <notifications@github.com> wrote:
>
> I have an ontology with these axioms:
>
> <owl:Class rdf:about="http://dbpedia.org/ontology/ClubMoss">
>         <rdfs:subClassOf rdf:resource="http://dbpedia.org/ontology/Plant
"/>
>     </owl:Class>
>     <owl:Axiom>
>         <owl:annotatedSource rdf:resource="
http://dbpedia.org/ontology/ClubMoss"/>
>         <owl:annotatedProperty rdf:resource="
http://www.w3.org/2000/01/rdf-schema#subClassOf"/>
>         <owl:annotatedTarget rdf:resource="
http://dbpedia.org/ontology/Plant"/>
>         <annotations:confidence rdf:datatype="
http://www.w3.org/2001/XMLSchema#double">1.0</annotations:confidence>
>         <annotations:support rdf:datatype="
http://www.w3.org/2001/XMLSchema#double">0.004</annotations:support>
>     </owl:Axiom>
>
> When I load the ontology, I expected to have two SubClassOf axioms in my
ontology, but owlapi ignores the subclassof axiom which has no annotations.
So ontology will have just one of these axioms.
> used api version: 4.1.0-RC2
>

This is known. The problem is that the annotated axiom is acting as a
reference to the non annotated axiom. The parser cannot tell that the
triples generated for the first one are distinct from the triples generated
for the other one.

Currently there is no workaround for this limitation.
I.

**Comment by ignazio1977** [comment]
For reference, this case is described in the specs:

http://www.w3.org/TR/owl2-mapping-to-rdf/#Parsing_of_Annotations

If G contains this pattern...	

     x *:y xlt .
    { AP(*:y) ≠ ε and there is no blank node _:w such that G contains the following triples:
    _:w rdf:type owl:Annotation .
    _:w owl:annotatedSource x .
    _:w owl:annotatedProperty *:y .
    _:w owl:annotatedTarget xlt . }	

...then this annotation is added to ANN(x).

    Annotation( *:y xlt )

If G contains this pattern...	

    x *:y xlt .
    _:w rdf:type owl:Annotation .
    _:w owl:annotatedSource x .
    _:w owl:annotatedProperty *:y .
    _:w owl:annotatedTarget xlt .
    { AP(*:y) ≠ ε and no other triple in G contains _:w in subject or object position }	

...then this annotation is added to ANN(x).

    Annotation( ANN(_:w) *:y xlt )


Unfortunately the second pattern includes `x *:y xlt .`, which is the complete serialization of the same axiom without annotations, which means these two axioms cannot appear in the same input ontology and be distinct - the annotationless axiom needs to be saved in a separate RDF graph.
