### ISSUE TITLE
Commons RDF integration

### ISSUE THREAD

**Issue by ignazio1977** [owlcs/owlapi#452]
@stain suggested:

How about Commons RDF integration for things like Triple, URI, BlankNode?
https://commonsrdf.incubator.apache.org/

The Commons RDF API is now stabilizing, although we appreciate any feedback
or suggested modifications before releasing 1.0.0.

It would make it easier to use other (de)serializers, e.g. JSON-LD or RDFa.

I had a rough go at this, just trying to add the interface
at the right places:

https://github.com/owlcs/owlapi/pull/446

The changes are minimal, and most of the RDF* methods already match
1:1, e.g. getDataType().

For full benefits it could be taken further, e.g. adding a RDFConsumer and
RDFRendererBase that takes a Commons RDF Graph instance instead of a file and
format.

**Comment by ansell** [comment]
In terms of the RDFConsumer/RDFRendererBase, the current Rio code may be able to be reused in some way.

In terms of exposing the OWLAPI RDF API using Commons RDF API, one big hurdle will be recognising RDF-1.1, as the triples that people submit, and expect to find, using Commons RDF API must support rdf:LangString, and default to xsd:string, from the Commons RDF API methods, in all cases where current literals do not have datatypes assigned and are not language literals. The big questions there is whether that is independent, in addition to, or instead of, both rdf:PlainLiteral and xsd:string.

**Comment by ignazio1977** [comment]
Comment from @stain pull request that implements this feature:

[Apache Commons RDF](http://commonsrdf.incubator.apache.org/) (incubating) is an effort for making a common API (e.g. Java interfaces) for RDF concepts like [`IRI`](http://commonsrdf.incubator.apache.org/apidocs/org/apache/commons/rdf/api/IRI.html) and [`BlankNode`](http://commonsrdf.incubator.apache.org/apidocs/org/apache/commons/rdf/api/Literal.html). Commons RDF aims to become a common interface between frameworks like Jena and Sesame so that you can have direct API compatibility without having to serialize and deserialize RDF. 

## Motivation

* Commons RDF tries to stay as close as possible to the [RDF 1.1 concepts](http://www.w3.org/TR/rdf11-concepts/) and to be neutral common ground between the Java RDF frameworks.
* The Commons RDF API is now stabilizing, although we appreciate any [feedback](http://commonsrdf.incubator.apache.org/contributing.html) or suggested modifications before releasing 1.0.0.
* Commons RDF integration is planned in most of the Java framework projects, e.g. Apache Jena [JENA-1015](https://issues.apache.org/jira/browse/JENA-1015), Sesame [SES-2091](https://openrdf.atlassian.net/browse/SES-2091) and Apache Clerezza.
* Integrating Commons RDF with OWLAPI means that users (and OWLAPI) has the potential to combine the two in a more direct way, and can use parsers, writers and triple stores from these frameworks.   

## Implementation

This patch shows the OWLAPI modifications needed to the types `RDFLiteral`, `RDFResource`, `RDFNode`, `RDFLiteral`, `RDFTriple` and `IRI`.  Changes are generally minimal, as the overlap was already big.

OWLAPI doesn't really have the concept of a `Graph` as statements are generated or consumed on the fly.

OWLAPI has both `IRI` and `RDFResourceIRI` - I am not sure why both are needed, but it was easy enough to make both of them compatible with Common RDF's `IRI`.

Note that Commons RDF also expects [.equals()](http://commonsrdf.incubator.apache.org/apidocs/org/apache/commons/rdf/api/IRI.html#equals-java.lang.Object-) to work across implementations on the core concepts, so therefore this patch also modifies OWLAPI .equals() to support a fallback to other Common RDF instances. 

I included a `CommonsRDFTermTest` to use Common RDF test suite. Some of the failing tests are ignored as they deal with validation of things like the Literal language string, which I am not sure OWLAPI needs to do as it is not an RDF framework.

## Further work

Further work would be needed on this branch to support RDF framework integration smoothly, e.g. as a special kind of OWLAPI `RDFConsumer` or `RDFRendererBase` that takes a Commons RDF [`Graph`](http://commonsrdf.incubator.apache.org/apidocs/org/apache/commons/rdf/api/Graph.html) instance instead of a file and format.

This integration could be taken further by removing some or all of the RDF* types in favour of the Commons RDF Simple implementation, like where there is no additional benefits given - however this would mean adding API changes from OWLAPI 4.


This patch highlights a few potential method renames in the OWLAPI to be directly compatible and avoid duplicate methods, however I have not suggested that as part of this patch as it is more drastic:

* RDFLiteral.getLexicalValue() -> getLexicalValue()
* RDFLiteral.getLang() -> getLanguageTag()
* IRI.toQuotedString() -> ntriplesString()

I also found that `RDFLiteral` deals with RDF 1.0 strings and uses `rdf:PlainLiteral` (RDF 1.1 merges plain literals to `xsd:string`) - I've tried to keep `rdf:PlainLiteral` support, but output both of those without `^^` type in the new `literal.ntriplesString()`, as Commons RDF follows RDF 1.1 specifications.  I also made the `rdf:langString` as a default type if a lang is given - but didn't force this as a type if BOTH lang and data type is given. (RDF 1.1 specs however says it must be `rdf:langString in this case) --- should this be raised as separate bugs?

There could be some potential bugs in OWLAPI highlighted in terms of equivalence, as OWLAPI BlankNodes can carry with them their local identifier, but that means that two such blank nodes from two different parser runs could potentially accidentally overlap if they were both added to a common Commons RDF `Graph` instance.

**Comment by ansell** [comment]
The pull request for this has been merged, so closing this issue.
