### ISSUE TITLE
Update Sesame/RIO components to Sesame 4

### ISSUE THREAD

**Issue by ignazio1977** [owlcs/owlapi#453]
@ansell suggested:

Sesame-4 that was released last week would be a good fit for OWLAPI-5,
as both depend on Java-8. I.e., skip Sesame-2.8.

**Comment by ansell** [comment]
This still requires us to interoperate with RDF-1.1 though, given that RDF-1.1 serialisers are almost all going to ignore xsd:string from now on in their output (in the same way that OWLAPI ignores rdf:PlainLiteral when serialising). All round tripping that required a distinction between rdf:PlainLiteral and xsd:string will hence be broken (and probably already is given the uptake of RDF-1.1 by other libraries already).

Should I look into rebasing pull request #218 onto the version 5 branch with a change to make it use Sesame-4?

**Comment by ignazio1977** [comment]
I'd appreciate that if you have the time; otherwise I'll do it.

**Comment by sesuncedu** [comment]
The loss of the xsd:strings when rendering is a possible problem for
round-trip testing though I have a vague memory of writing a comparator for
testing that handled this.

I'm trying to think if there are any cases where there are sets of literals
that require at least two structurally different literals (I don't think
so).

**Comment by ansell** [comment]
I will try to rebase it. The last set of changes were stable when the discussion stagnated, but they were only one possible solution. With Stian's pull request for Commons RDF, which is also RDF-1.1, the discussion may have critical mass to stay open this time and be implemented for version 5.

**Comment by ignazio1977** [comment]
Included in version 5
