### ISSUE TITLE
Unintentional OSGi Embedding

### ISSUE THREAD

**Issue by skahmann** [owlcs/owlapi#455]
It looks like the OSGi distribution is mis-configured to include dependency jars that it should not be including. The following lines configuring the dependency embedding:

```xml
<Embed-Dependency>
    groupId=${project.groupId};inline=true;scope=compile|runtime|provided,
    groupId=!${project.groupId};scope=compile|runtime|provided;inline=false,
    groupId=trove4j;scope=compile|runtime|provided;inline=false 
</Embed-Dependency>
<Embed-Directory>lib</Embed-Directory>
<Embed-Transitive>true</Embed-Transitive>
```

The first line says to embed and inline all artifacts with groupId `net.sourceforge.owlapi`. This is probably intentional. The second line says to embed all artifacts that do not have groupId `net.sourceforge.owlapi`. This is probably unintentional. The third line says to embed artifacts with groupId `trove4j`. There are none, `net.sf.trovej4` was probably the intended groupId.

This configuration is a problem for us because the sesame jars are being embedded. This limits us to using the specific version of sesame (2.7.12) that is included in the disitribution. We have moved on to 2.8.6 which most likely is backwards compatible (we are still investigating that).

The intended configuration should probably be:

```xml
<Embed-Dependency>
    groupId=${project.groupId};inline=true;scope=compile|runtime|provided,
    groupId=net.sf.trove4j;scope=compile|runtime|provided;inline=false
</Embed-Dependency>
<Embed-Directory>lib</Embed-Directory>
<Embed-Transitive>true</Embed-Transitive>
```

**Comment by ignazio1977** [comment]
> The second line says to embed all artifacts that do not have groupId net.sourceforge.owlapi. This is probably unintentional.


That is intentional - the purpose of the OSGi distribution is to be deployed within Protégé, and we need those dependencies embedded, or available as OSGi jars. The second solution required too much effort.

For your use case, I believe the owlapi-distribution artifact would work better.

**Comment by skahmann** [comment]
Is it possible to build an OSGi artifact that doesn't have the embedded dependencies? Unless I'm mistaken, the owlapi-distribution module does not create OSGi Manifest headers. We need to deploy owlapi in an OSGi environment without the embedded dependencies. Building bundles in that way is really counter to the OSGi way.

**Comment by ignazio1977** [comment]
I'll see what can be done.

It's probably better to change the osgidistribution to just add headers to distribution rather than build the output from scratch anyway.

**Comment by sesuncedu** [comment]
At one point every artifact was being built as a bundle,  with the main
difference between the regular distribution and the OSGI distribution being
the lack of bundled jars (and different maven dependencies).

**Comment by matthewhorridge** [comment]
We are also having problems with this.  Specifically, guava, which is a bundle and slf4j, which is also a bundle.

**Comment by matthewhorridge** [comment]
It looks like the following are bundles that need not be embedded in the OSGi distribution.

guava
guice
guice-assistedinject
guice-multibindings
slf4j
commons-codec
commons-io

Also, commons-io is embedded twice once as commons-o-2.4.jar and once as org.apache.commons.io-2.4.jar.

**Comment by ignazio1977** [comment]
Good catch @matthewhorridge, I'll sort those.

**Comment by matthewhorridge** [comment]
Thanks for sorting them!  I'm porting Protege 5 to use 4.1.1 so this would be really helpful.  Everything compiles fine and test run and pass, but things fail at run time due to some osgi use constraint violations that are caused by this.

**Comment by sesuncedu** [comment]
Guice and OSGI are ungainly even without embedding, and slf4j requires a
little bit of magic if the implementation is not also embedded (not sure if
that was in the integration test).

Jigsaw adds a new dimension of fun :)

Simon

**Comment by matthewhorridge** [comment]
I'm using logback with slf4j and these are also happily bundles.

**Comment by sesuncedu** [comment]
Also, the embedded artifact is slf4j-api - slf4j does static configuration
that requires extra headers. Or not embedding.

There is a possible need to embed any dependent non-modules, but not any
actual modules. Deployment is  something that OSGI didn't standardize on.

Simon

**Comment by sesuncedu** [comment]
Right- if you deploy slf4j-api as a module all is well. If you embed, you
need to do magic else it won't see slf4j-logback.

**Comment by ignazio1977** [comment]
@matthewhorridge did you already push any required changes? Would be good for me to be able to test that the new jar works.

**Comment by ignazio1977** [comment]
Any suggestions on how to provide the required bundles for the integration test? Else we're losing the ability to test the bundle without actually deploying it.

**Comment by sesuncedu** [comment]
I need to review the class and maven config. I think there might be an
additional test issue with having classes reachable via the standard class
path.

**Comment by ignazio1977** [comment]
I might have figured out the trick with installing more bundles - I'll copy the way it's done already with slf4j-api

**Comment by ignazio1977** [comment]
Fantastic, guava 4 is a bundle but does not embed its dependencies, and one of them is not a bundle.
I'll try to find a wrapped version.

One day I'm going to find out why OSGi was a good idea. Preferably before it's obsoleted by Java modules.

**Comment by matthewhorridge** [comment]
> Fantastic, guava 4 is a bundle but does not embed its dependencies, and one of them is not a bundle.
I'll try to find a wrapped version.

Which dependency is it?

> One day I'm going to find out why OSGi was a good idea. Preferably before it's obsoleted by Java modules.

.... :)

**Comment by ignazio1977** [comment]
> Which dependency is it?

javax.inject and aopalliance.
I've got around it by adding two wrapped versions as extra dependencies on the osgi distro.
I'm trying to figure out info.aduna.io now - I believe it's Sesame related.

**Comment by ignazio1977** [comment]
Well, surprise, I got a successful build.

I'll email you a test jar.

**Comment by ignazio1977** [comment]
I've checked out the latest protege owlapi 4 branch and managed to make progress. With the current owlapi 4.1.2 snapshot, I've made the following changes:

    +++ b/pom.xml
    -		<owlapi.version>4.1.1</owlapi.version>
    +		<owlapi.version>4.1.2-SNAPSHOT</owlapi.version>
    + 			<dependency>
    +				
    +				<groupId>org.apache.servicemix.bundles</groupId>
    +				<artifactId>org.apache.servicemix.bundles.javax-inject</artifactId>
    +				<version>1_2</version>
    +			</dependency>
    +			<dependency>
    +				<groupId>org.apache.servicemix.bundles</groupId>
    +				<artifactId>org.apache.servicemix.bundles.aopalliance</artifactId>
    +				<version>1.0_6</version>
    +			</dependency>
    diff --git a/protege-desktop/src/main/assembly/dependency-sets.xml
    + <include>net.sourceforge.owlapi:owlapi-osgidistribution:jar</include>
    + <include>org.apache.servicemix.bundles:org.apache.servicemix.bundles.javax-inject:jar</include>
    + <include>org.apache.servicemix.bundles:org.apache.servicemix.bundles.aopalliance:jar</include>

The new build threw this exception:

    An error was thrown: Illegal character in scheme name at index 11: Optional.of(http://www.semanticweb.org/ontologies/2015/10/untitled-ontology-146)
    java.lang.IllegalArgumentException: Illegal character in scheme name at index 11: Optional.of(http://www.semanticweb.org/ontologies/2015/10/untitled-ontology-146)
	at java.net.URI.create(URI.java:852) ~[na:1.8.0_65]
	at org.protege.editor.owl.OWLEditorKit.handleNewRequest(OWLEditorKit.java:239) ~[na:na]

So, a bona fide bug - the Optional is not being unwrapped.
I'll try and fix this locally, and if I can successfully start Protege I'll release 4.1.2.

@skahmann I've also made changes to owlapi-distribution - if you're in a position to test it and let me know if it's working for you, that'd be awesome.

**Comment by ignazio1977** [comment]
diff --git a/protege-editor-owl/src/main/java/org/protege/editor/owl/OWLEditorKit.java
    -        OWLOntology ont = getModelManager().createNewOntology(id, URI.create(id.getDefaultDocumentIRI().toString()));
    +        OWLOntology ont = getModelManager().createNewOntology(id, URI.create(id.getDefaultDocumentIRI().get().toString()));

With this, I get Protege to start - @matthewhorridge maybe a quick check to all references to OWLOntologyID, in case there are other similar problems?

The console shows errors about the two new bundles added to the bundles folder - they cannot be started, as they are "fragment" bundles. I believe that's expected given their nature.

**Comment by sesuncedu** [comment]
I've gotten myself a bit tangled on this issue,  and I'm trying to figure
out if there's a simple way to build better OSGI tests.

I get the feeling that the simplest solution may involve parsing manifests
and the embedded maven META-INF files, which doesn't seem right (though
service discovery may make checking other META-INF files worthwhile.

New issue time.

**Comment by skahmann** [comment]
Sorry for the delay. I think it looks good to me. I was able to deploy in karaf. Is there a restriction on the openrdf version required? We are running sesame 4, but I believe you guys build for 2.7.

**Comment by ignazio1977** [comment]
Open rdf is available for OWLAPI 5 (still in alpha), we are using 0.1.0 and sesame 4 for that.
