### ISSUE TITLE
[4.1.0] Bug or missing documentation: OWLOntologyManager.saveOntology(OWLOntology) crashes when source file exists

### ISSUE THREAD

**Issue by Zsar** [owlcs/owlapi#457]
With `OWLOntologyManager manager = OWLManager.createOWLOntologyManager();`:
Assume that an ontology is loaded from local disk via
`manager.loadOntologyFromOntologyDocument(new FileInputStream(<someReadableFile>));`
If this Ontology is later saved using
`manager.saveOntology(ontology);`
the method will throw an unhandled exception:
`java.net.MalformedURLException: unknown protocol: inputstream`
`unknown protocol: inputstream`

Now assume that a source file does not exist and instead a new ontology is instantiated via
`file.createNewFile();`
`return manager.createOntology(IRI.create(<someReadableFile>));`
If this ontology is then saved using
`manager.saveOntology(ontology);`
the file will be correctly saved and no exception occur.

Issue is **at least** that the method `OWLOntologyManager.saveOntology(OWLOntology)` is not supposed to throw this kind of exception to begin with.

Proper solution would be to handle or better prevent the exception internally, so that the expected result of saving an ontology into its source file, when said file is not empty (aka *on every but the very first access*), works correctly.

If the method *is not supposed* to be able to save an ontology into its source file, then this limitation should be remarked on in its javadoc page.

Here is a short program to test this behaviour. It will work correctly the first time it is run (and create `Test.owl` in the process), but crash the second time (when `Test.owl` is already present).

    public class App 
    {
      public static void reportThrowable(Throwable t, String source)
      {
        System.err.println("\nUnexpected Exception in " + source + " :\n");
        do
        {
          System.err.println(t.getMessage());
          t = t.getCause();
        }
        while(t != null);
      }
      
      protected static OWLOntology loadOntology(String name)
      {
        try
        {
          File file = new File(name);
          if(file.canRead())
            return manager.loadOntologyFromOntologyDocument(new FileInputStream(file));
          else if(!file.exists())
            if(file.createNewFile())
              return manager.createOntology(IRI.create(file));
        }
        catch(Throwable t) { reportThrowable(t, "App::loadOntology"); }
        return null;
      }
      
      protected static boolean saveOntology(OWLOntology ontology)
      {
        try
        {
          manager.saveOntology(ontology);
          return true;
        }
        catch(Throwable t) { reportThrowable(t, "App::saveOntology"); }
        return false;
      }
      
      public static void main(String[] args)
      {
        OWLOntology ontology = App.loadOntology("Test.owl");

        System.out.println(ontology);
        System.out.println(manager.getOntologyDocumentIRI(ontology));
        
        App.saveOntology(ontology);
      }
      
      protected static OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
    }

**Comment by Zsar** [comment]
Actually, it would seem that it is not this method but rather
`OWLOntologyManager.loadOntologyFromOntologyDocument(InputStream)`
that is to blame.

After creating a new ontology using
`manager.createOntology(IRI.create(file));`
as seen above, the result of
`System.out.println(manager.getOntologyDocumentIRI(ontology));`
is
`file:/H:/Java/MavenTest/Onto-Manager/Test.owl`
as expected.

But loading the ontology via
`manager.loadOntologyFromOntologyDocument(new FileInputStream(file));`
instead yields
`inputstream:ontology1`
which would probably cause the exception as observed above.

*Does this work as intended?* In both cases, the ontology itself is displayed as
`Ontology(OntologyID(OntologyIRI(<file:/H:/Java/MavenTest/Onto-Manager/Test.owl>))`
` VersionIRI(<null>))) [Axioms: 0 Logical Axioms: 0] First 20 axioms: {}`

**Comment by Zsar** [comment]
Indeed, not using InputStreams circumvents the issue.

I am not convinced that this is as it should be, as an InputStream is obviously *not* a document and therefore should not be considered when returning a document IRI, whereas the underlying object of the stream (in this case a file) *is* a document and *should*.

**Comment by sesuncedu** [comment]
You are calling the loadOntology method with an input stream, so there's no
location to write to.
The exception should be wrapped as an OWLOntologyCreationIOException; is
this not happening?

**Comment by sesuncedu** [comment]
Since FileInputStream does not provide an access method to the path name (if one was provided), it is probably best to use the File specific methods when file like behaviour is wanted, and to provide an output stream or other target if the document source was an input stream

**Comment by vigvaithi** [comment]
File file = new File("<someReadableFile>");// file works in place of FileInputStream and does not give //that error
OWLOntology ontology = manager.loadOntologyFromOntologyDocument(file); System.out.println("Loaded ontology: " + ontology);
.... //add all changes 
manager.saveOntology(ontology);
