### ISSUE TITLE
Allow SyntacticLocalityModuleExtractor to exclude type assertions.

### ISSUE THREAD

**Issue by nimonika** [owlcs/owlapi#462]
This does not seem to be working. It returns the complete ontology instead of the module corresponding to the seed set. Has anyone else tried this recently and did it work for them?

**Comment by ignazio1977** [comment]
Can you show how you called it?

**Comment by nimonika** [comment]
This is the minimum snippet. Let me know if more details are needed.

     SyntacticLocalityModuleExtractor sme = new SyntacticLocalityModuleExtractor(manager, ontology, ModuleType.TOP);
     IRI moduleIRI = IRI.create("urn:test:AnimalModule.owl");
     OWLOntology mod = sme.extractAsOntology(seedSig, moduleIRI);

**Comment by ignazio1977** [comment]
Thanks, I'll try with a test ontology.

One thing that would be important is the input signature - depending on the ontology, it might cause the whole ontology to be returned.

**Comment by nimonika** [comment]
You could try on this one

http://aligned.cs.ox.ac.uk/ontologies/TestOWLRLAxioms.owl

With the input signature as "Animal"

**Comment by tsarkov** [comment]
Note that you are using the TOP module -- they are usually very big and can easily coincide with the whole ontology. Can you try to use BOT module, and see whether you get something smaller?

**Comment by nimonika** [comment]
I actually tried  BOT, STAR and TOP in that order. I always get the complete ontology.

**Comment by nimonika** [comment]
I think the problem may be due to individuals being present in the ontology. Their types get pulled in and therefore the complete ontology gets returned. I got rid of the class assertions and the extractor seems to work as expected. Is there a flag that can be set to ignore the assertions? I could not find it in the API.

**Comment by ignazio1977** [comment]
Yes, class assertions would do that - if the type is not in the signature and is not equivalent to top, it will be included.
The current code does not have an option to exclude class assertions from the modularisation process; I'm not sure what would be the consequences, e.g., whether skipping the assertions would change the properties of the resulting module. I don't believe there should be consequences if there are no nominals, but I can't be sure.

**Comment by rsgoncalves** [comment]
Locality-based modules can have that effect when individuals are present. A workaround is extracting against the Tbox alone, and subsequently getting axioms "involving" individuals of classes already in the module signature, where "involving" could be only type assertions, the whole usage of each individual, or no Abox axioms depending on the use case / need for module completeness.

**Comment by ignazio1977** [comment]
Added a boolean flag to the constructor:

    public SyntacticLocalityModuleExtractor(@Nonnull OWLOntologyManager man, IRI ontIRI,
        @Nonnull Set<OWLAxiom> axs, @Nonnull ModuleType moduleType) {
        this(man, ontIRI, axs, moduleType, false);
    }

    public SyntacticLocalityModuleExtractor(@Nonnull OWLOntologyManager man, IRI ontIRI,
        @Nonnull Set<OWLAxiom> axs, @Nonnull ModuleType moduleType, boolean excludeAssertions) {
