### ISSUE TITLE
How to import and remove ontologies

### ISSUE THREAD

**Issue by e-jajaga** [owlcs/owlapi#466]
I am looking to load a core ontology and dynamically load and unload data ontologies as required.
I have followed the examples for loading an ontology and its imports through OWLAPI and created the following code:
```    
InputStream inputCoreOntology = new FileInputStream("file1path"); 
OWLOntology owlModel = manager.loadOntologyFromOntologyDocument(inputCoreOntology);
System.out.println("Loaded ontology: " + owlModel);    
DefaultPrefixManager prefixManager = new DefaultPrefixManager();
OWLDocumentFormat format = owlModel.getOWLOntologyManager().getOntologyFormat(owlModel);
if (format.isPrefixOWLOntologyFormat())
 prefixManager.copyPrefixesFrom(format.asPrefixOWLOntologyFormat().getPrefixName2PrefixMap());
//IMPORTS
InputStream inputImportOntology = new FileInputStream("file2path"); 
manager.loadOntologyFromOntologyDocument(inputImportOntology);
SimpleIRIMapper iriMapper =  new SimpleIRIMapper(IRI.create("http://.../file2.owl"), IRI.create(new File("file2path")));
manager.addIRIMapper(iriMapper);
printOntologyAndImports(manager, owlModel);
```
The imported ontology does not show up. I would like to also add and remove another imports dynamically. The printOntologyAndImports(manager, owlModel); method is taken from https://github.com/owlcs/owlapi/blob/version4/contract/src/test/java/org/semanticweb/owlapi/examples/Examples.java

**Comment by ignazio1977** [comment]
You haven't added an `OWLImportsDeclaration` to your root `OWLOntology`.

For an example, see the following:

   OWLOntology ontology = manager.createOntology(ontologyIRI);
    OWLImportsDeclaration importDeclaraton = factory.getOWLImportsDeclaration(importIRI); 
    manager.applyChange(new AddImport(ontology, importDeclaraton));

From:

http://stackoverflow.com/questions/9334875/how-to-define-a-owlimports-with-owl-api-v3
