### ISSUE TITLE
Constraint Sesame Versions in OSGi Imports

### ISSUE THREAD

**Issue by skahmann** [owlcs/owlapi#471]
The distribution bundle does not constrain the imported Sesame packages. The following should be added to the maven-bundle-plugin imports:

```xml
<Import-Package>
    !sun.misc,
    !com.google.inject.internal.*;resolution:=optional,
    org.openrdf*;version="[2.7,3.0)",
    *
</Import-Package>
```

**Comment by ansell** [comment]
[2.7,2.8) would be more appropriate as OWLAPI-4 does not support the RDF-1.1 features that was added in 2.8.

The equivalent for OWLAPI-5 would be [4.0,5.0).

**Comment by skahmann** [comment]
The sesame bundle also has the info.aduna packages. You also need to constrain those. `info.aduna.iteration;version="[2.7,2.8)",`

**Comment by skahmann** [comment]
Thank you for being so responsive! After looking at the issue, I believe 2.8 is backwards compatible with 2.7 so you should be able to use 2.8 at runtime. Does the typed literal change cause problems?

**Comment by ignazio1977** [comment]
Yes - it impacts a number of places in the api and it affects reasoners as well. I've found out that HermiT, for example, requires a couple of changes to work with rdf:langString. So we won't be able to slide 2.8 in and be sure there isn't any breakage. It might be worth trying on some local development but I'm not confident enough to put it in a 4.x release.

I'd rather speed up 5.0 to be released, say, in February :-)

**Comment by skahmann** [comment]
That would be excellent! :-)

**Comment by sesuncedu** [comment]
Hermit is somewhat insistent on correctly enforcing the official set of
reserved datatypes (except for bugs).

In order to work with RDF 1.1, langString needs to be mapped to
PlainLiteral in literal types,  and to a restriction on PlainLiteral if
used as a data range.

This could be handled with an option on the ontology manager
