### ISSUE TITLE
Problem compiling examples: broken dependency

### ISSUE THREAD

**Issue by Xorbit17** [owlcs/owlapi#472]
Hello,

New to ontologies, not new to java. I trying to learn about this API by running some examples this community provided:
owlapi/contract/src/test/java/org/semanticweb/owlapi/examples/Examples.java 

However, the file imports a testbase class:
import org.semanticweb.owlapi.api.test.baseclasses.TestBase; //Not found

This is not found. org.semanticweb.owlapi.api does not exist. Also the @Nonnull annotation fails as well.

import javax.annotation.Nonnull; //Not found

What jar(s) do I need to refer to to fix this and run the example? I looked hard for a solution but I could not find it.

Thanks!

**Comment by ansell** [comment]
Are you using Maven or another package manager to build your project?

**Comment by ignazio1977** [comment]
The TestBase class is in the same module as Examples.java:

https://github.com/owlcs/owlapi/blob/version4/contract/src/test/java/org/semanticweb/owlapi/api/test/baseclasses/TestBase.java

The @Nonnull annotation comes from http://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.0/

**Comment by Xorbit17** [comment]
@ansell Thanks for your help. I am not using Maven at the moment. I come from a world where java is used in an engineering context to design automation software. A complex build system or dependency management is not needed there so I don't know how maven works. Maybe I should learn how to use it? I have tried it but it is not something you can master in a few hours.

@ignazio1977: Thanks! Your link lets me download java files. Should I download all files from the org/semanticweb/owlapi/api/test and make a jar myself and import it? The screenshot shows the simple dependencies I have set up at the moment. I suspect I should link to my jar file I compiled from the source code? Or is this too complicated...
The Examples class from the screenshot below is the example code I was talking about.
![screenproject](https://cloud.githubusercontent.com/assets/16345017/11894490/d89d275e-a577-11e5-9129-85b0b9b78714.png)
The link you provided allows me to download a specific java file(s).

**Comment by ignazio1977** [comment]
If you check out the whole source repository, you can use File->import existing Maven projects in Eclipse. It will sort the classpath for you, without need for you to interact directly with Maven.

The list of dependencies is quite long, so letting Eclipse play its magic saves a lot of effort.

**Comment by ignazio1977** [comment]
The referenced classes are in the contract test section, so they won't be released as maven artifacts. TestBase only contains utility methods though, so you could copy and paste the parts you need.

**Comment by Xorbit17** [comment]
Dear contributors,

I learned how to use git properly. I used the git plugin to get the owlapi version 4 branch on my system. Then I used the import project>Exisiting maven project functionality to get all dependencies automatically. I still don't understand everything I did. But the solution to the problem is truly learning how to use eclipse, maven and git.

Thanks for your support. I have found the classes I need.

**Comment by estathop** [comment]
I am using maven, I imported the owlapi-distribution dependency but I have the same problem, it can't find the TestBase file

**Comment by ignazio1977** [comment]
@estathop The answer is the same. That file is not part of the maven release, so it cannot be found simply using the maven dependency. You must check out the OWLAPI source code to access it.

**Comment by takwazakaria** [comment]
hello, i am new in java and new in ontologies, i create a maven project, add the dependency of the owl api, and i am trying to excute the code of loading ontology (from Examples.java) but when i put 
import org.semanticweb.owlapi.api.test.baseclasses.TestBase; , i get the error Package not found. import javax.annotation.Nonnull; //also not found.
 @ignazio1977 , i read your suggesion to @Xorbit17 but i have not understand how to fix the problem, can you please guide me how to do that?

**Comment by takwazakaria** [comment]
@estathop , i have the same problem as you, if you have fixed the problem, can you please help me?

**Comment by ignazio1977** [comment]
@takwazakaria you should not try to use `TestBase` if you're using only the Maven dependencies to use OWLAPI. `TestBase` is a utility class for OWLAPI unit tests only. `Examples` is meant to provide snippets for you to copy to your own code.

To resolve the missing Nonnull import, use one of the Maven dependencies that provide that annotation class. OWLAPI uses

 		<dependency>
			<groupId>com.google.code.findbugs</groupId>
			<artifactId>jsr305</artifactId>
			<version>[2.0.0,4)</version>
		</dependency>

**Comment by takwazakaria** [comment]
@ignazio1977, thank you very much, i get how to add a non maven jar to a maven project from https://dzone.com/articles/the-maven-way-to-add-non-maven-jars-to-a-maven-pro
