### ISSUE TITLE
Parsing of nested anonymous nodes broken in 4.1.1

### ISSUE THREAD

**Issue by tgbugs** [owlcs/owlapi#478]
When converting https://github.com/SciCrunch/NIF-Ontology/blob/fma/BiomaterialEntities/sequence.owl to ttl using owlapi 4.1.1 all instances of oboInOwl:hasDbXref are treated as individuals (or at least are put at the end of the file) and dissociated from their enclosing tags. 4.0.2 does not exhibit this behavior and the ttl output is as expected. This also happens in other files that us oboInOwl:hasDbXref, and might occur with similar constructs.

**Comment by ignazio1977** [comment]
I've reduced this to a small snippet reproducing the issue:

    <?xml version="1.0"?>
    <rdf:RDF xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
       xmlns:owl="http://www.w3.org/2002/07/owl#"
       xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
       xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
       xmlns:oboInOwl="http://www.geneontology.org/formats/oboInOwl#">
      <owl:Ontology rdf:about="http://ontology.neuinfo.org/NIF/BiomaterialEntities/sequence.owl"/>
      <owl:AnnotationProperty rdf:about="http://www.geneontology.org/formats/oboInOwl#hasDefinition"/>
      <owl:ObjectProperty rdf:about="http://purl.obolibrary.org/obo/obo#adjacent_to">
        <oboInOwl:hasDefinition>
            <oboInOwl:Definition>
                <oboInOwl:hasDbXref>
                    <oboInOwl:DbXref>
                        <oboInOwl:hasURI rdf:datatype="http://www.w3.org/2001/XMLSchema#anyURI">http://purl.obolibrary.org/obo/SO#SO_ke</oboInOwl:hasURI>
                    </oboInOwl:DbXref>
                </oboInOwl:hasDbXref>
            </oboInOwl:Definition>
        </oboInOwl:hasDefinition>
      </owl:ObjectProperty>
    </rdf:RDF>

In Turtle, the output is:

    @prefix : <http://ontology.neuinfo.org/NIF/BiomaterialEntities/sequence.owl#> .
    @prefix owl: <http://www.w3.org/2002/07/owl#> .
    @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
    @prefix xml: <http://www.w3.org/XML/1998/namespace> .
    @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
    @base <http://ontology.neuinfo.org/NIF/BiomaterialEntities/sequence.owl> .
    <http://ontology.neuinfo.org/NIF/BiomaterialEntities/sequence.owl> rdf:type owl:Ontology .
    <http://www.geneontology.org/formats/oboInOwl#hasDbXref> rdf:type owl:AnnotationProperty .
    <http://www.geneontology.org/formats/oboInOwl#hasDefinition> rdf:type owl:AnnotationProperty .
    <http://www.geneontology.org/formats/oboInOwl#hasURI> rdf:type owl:AnnotationProperty .
    <http://purl.obolibrary.org/obo/obo#adjacent_to> rdf:type owl:ObjectProperty ;
        <http://www.geneontology.org/formats/oboInOwl#hasDefinition> [
                  rdf:type <http://www.geneontology.org/formats/oboInOwl#Definition>
        ] .
    <http://www.geneontology.org/formats/oboInOwl#DbXref> rdf:type owl:Class .
    <http://www.geneontology.org/formats/oboInOwl#Definition> rdf:type owl:Class .
    [ <http://www.geneontology.org/formats/oboInOwl#hasDbXref> [ 
            rdf:type <http://www.geneontology.org/formats/oboInOwl#DbXref> ;
            <http://www.geneontology.org/formats/oboInOwl#hasURI> "http://purl.obolibrary.org/obo/SO#SO_ke"^^xsd:anyURI
      ]
    ] .


However the issue is not in the Turtle renderer but in the RDF/XML parsing. The parsed ontology has the following axioms:

    AnnotationAssertion(<http://www.geneontology.org/formats/oboInOwl#hasURI> _:genid4 "http://purl.obolibrary.org/obo/SO#SO_ke"^^xsd:anyURI)
    Declaration(AnnotationProperty(<http://www.geneontology.org/formats/oboInOwl#hasDefinition>))
    AnnotationAssertion(<http://www.geneontology.org/formats/oboInOwl#hasDefinition> <http://purl.obolibrary.org/obo/obo#adjacent_to> _:genid2)
    AnnotationAssertion(<http://www.geneontology.org/formats/oboInOwl#hasDbXref> _:genid1 _:genid4)
    ClassAssertion(<http://www.geneontology.org/formats/oboInOwl#Definition> _:genid2)
    ClassAssertion(<http://www.geneontology.org/formats/oboInOwl#DbXref> _:genid4)
    Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/obo#adjacent_to>))


This separates the nested annotations and leaves them unconnected - clearly a parsing bug.

**Comment by sesuncedu** [comment]
Does anything change if all the annotation properties are declared?

**Comment by sesuncedu** [comment]
Never mind - I see them

**Comment by vincentvialard** [comment]
There is a problem remaining with nested annotations that could be related. Ignazio did fix the OWL/XML roundtrip, but importing OWL/XML and exporting it to triples does break something.
I just tested it with version 4.1.4-SNAPSHOT.20160112-1210.
For details see attached files.
[nested-annotations.zip](https://github.com/owlcs/owlapi/files/88874/nested-annotations.zip)

**Comment by ignazio1977** [comment]
The Rio turtle output is fragmented - some triples that should appear together appear various lines apart. I can't imagine that helps the parser.

As a result of the roundtrip I get:

   1 ObjectPropertyAssertion(Annotation(Annotation(rdfs:commment "comment for one") rdfs:label "one") Annotation(Annotation(rdfs:commment "comment for two") rdfs:label "two") <#r> <#a> <#b>)
    ObjectPropertyAssertion(Annotation(Annotation(rdfs:commment "comment for three") rdfs:label "three") <#r> <#b> <#c>)


    2 ObjectPropertyAssertion(Annotation(rdfs:commment "comment for three") Annotation(Annotation(rdfs:commment "comment for one") rdfs:label "one") Annotation(rdfs:label "two") <#r> _:genid7 <#b>)
    2 ObjectPropertyAssertion(Annotation(rdfs:label "one") Annotation(Annotation(rdfs:commment "comment for two") rdfs:label "two") <#r> <#a> <#b>)
CheckSequence.should() 2 ObjectPropertyAssertion(Annotation(rdfs:label "three") <#r> <#b> <#c>)

Looks a lot like the bug I fixed a while back (with much pain, I might add) :-( I hoped to have seen the back of that...

My fix was in the main RDF parsing/outputting, however for Rio Turtle and N-TRIPLES that's not used. Regular Turtle would still use the RDF/XML component, but which factory gets picked up for the output I'm not sure - I believe as default we use Rio Turtle, because the OWLAPI Turtle parser is not something we like a lot - so it might be the same parer/outputter for both Turtle flavors.

I'm not sure whether this is the same bug reported in the first post or another - in one case we have multiple nested annotations on an axiom, in the other multiple levels of nesting for one annotation on an entity. Due to the contortions required to fit an axiom as an annotation subject, the two are dealt with in very different ways, so I'm guessing these are two distinct bugs.

**Comment by ignazio1977** [comment]
What's better, the second issue (the one reported by Vincent) happens when roundtripping twice, i.e., saving and reloading the same ontology twice, but not when doing it once. This means there is state saved somewhere that is interfering with the process. Given what the error looks like, I think it's in the generation of node ids.

**Comment by vincentvialard** [comment]
As I wrote, after loading OWL/XML and saving it to Rio Turtle already broke something (the annotation on the annotation refers to the wrong node id - see the README file),  but it becomes really obvious after the second roundtrip. So I also think it there is something wrong with node ids.

**Comment by ignazio1977** [comment]
The previous bug I fixed presented itself multiple times; in 2014, I had a (fairly bad) fix specific to RIO formats. Turns out it now interferes with the better fix that was put in place last November.
I've removed the older fix and a good number of failures have disappeared.

There are indeed multiple issues at play here - I'll try and fix the remaining problem.

**Comment by ignazio1977** [comment]
The new tests now pass - the two issues involved here were
- bug in handling of anonymous individuals used in nested annotations. There was one usage left of a plain OWLDataFactory for creating individuals, should have been delegated to the consumer like the others.
- bug in OWL/XML to Rio Turtle translation: all Rio triple based formats (TriX, Turtle, NTriples, JSON) are fed from a renderer that remaps blank nodes to avoid structure sharing issues (structure sharing in these formats leads to unparseable files), but this remapping included anonymous individuals as well, which is incorrect. Anonymous individuals reused across axioms are not shared structure, they're a legitimate feature.

I believe the commits fix the issues, but I'd appreciate confirmation.

**Comment by ansell** [comment]
I will run the tests to see if they pass for me as well. I haven't been through the Rio parser/renderer code for a while, but I think I understand what you changed and it looks okay to me.

**Comment by ansell** [comment]
All of the tests pass for me.

**Comment by vincentvialard** [comment]
The actual 4.1.4-SNAPSHOT looks good, thanks for fixing that!

During my test run I noticed that there are some logging infos left in somewhere in the code that should be removed before release:

```
10:43:13 INFO  OWLRDFConsumer            :: dumping remaining triples
10:43:13 INFO  OWLRDFConsumer            :: _:genid-nodeid-genid-96880448f7314b5c9778542d2acb5a9e-genid5 -> http://www.w3.org/2002/07/owl#annotatedSource -> _:genid-nodeid-genid-96880448f7314b5c9778542d2acb5a9e-genid4
10:43:13 INFO  OWLRDFConsumer            :: _:genid-nodeid-genid-96880448f7314b5c9778542d2acb5a9e-genid5 -> http://www.w3.org/2002/07/owl#annotatedProperty -> http://www.w3.org/2000/01/rdf-schema#label
10:43:13 INFO  OWLRDFConsumer            :: _:genid-nodeid-genid-96880448f7314b5c9778542d2acb5a9e-genid2 -> http://www.w3.org/2002/07/owl#annotatedSource -> _:genid-nodeid-genid-96880448f7314b5c9778542d2acb5a9e-genid1
10:43:13 INFO  OWLRDFConsumer            :: _:genid-nodeid-genid-96880448f7314b5c9778542d2acb5a9e-genid2 -> http://www.w3.org/2002/07/owl#annotatedProperty -> http://www.w3.org/2000/01/rdf-schema#label
10:43:13 INFO  OWLRDFConsumer            :: _:genid-nodeid-genid-96880448f7314b5c9778542d2acb5a9e-genid3 -> http://www.w3.org/2002/07/owl#annotatedSource -> _:genid-nodeid-genid-96880448f7314b5c9778542d2acb5a9e-genid1
10:43:13 INFO  OWLRDFConsumer            :: _:genid-nodeid-genid-96880448f7314b5c9778542d2acb5a9e-genid3 -> http://www.w3.org/2002/07/owl#annotatedProperty -> http://www.w3.org/2000/01/rdf-schema#label
10:43:13 INFO  OWLRDFConsumer            :: _:genid-nodeid-genid-96880448f7314b5c9778542d2acb5a9e-genid5 -> http://www.w3.org/2002/07/owl#annotatedTarget -> "three"
10:43:13 INFO  OWLRDFConsumer            :: _:genid-nodeid-genid-96880448f7314b5c9778542d2acb5a9e-genid2 -> http://www.w3.org/2002/07/owl#annotatedTarget -> "one"
10:43:13 INFO  OWLRDFConsumer            :: _:genid-nodeid-genid-96880448f7314b5c9778542d2acb5a9e-genid3 -> http://www.w3.org/2002/07/owl#annotatedTarget -> "two"
10:43:13 INFO  OWLRDFConsumer            :: done dumping remaining triples
```

**Comment by vincentvialard** [comment]
The 4.1.4 relase still outputs this information.

In my test case this happens during the parsing of an ontology that was saved under `RioTurtleDocumentFormat` with `manager.loadOntologyFromOntologyDocument`.

**Comment by ignazio1977** [comment]
That is logging information that is printed if the logging level is set to INFO. I believe it's set to ERROR in the release, but I'll double check. In the meantime, can you check whether you have a different setting in your sl4j settings?

**Comment by ignazio1977** [comment]
There's an example in contract/src/test/resources/simplelogger.properties

**Comment by vincentvialard** [comment]
There was a mismatch in my IDE and the snapshot and release coexisted. I dumped the snapshot and now no logging anymore. Sorry for the trouble!

**Comment by ignazio1977** [comment]
No problem

**Comment by ignazio1977** [comment]
The bug that never dies part 2: still alive

**Comment by ignazio1977** [comment]
Fixed (again...)

**Comment by sesuncedu** [comment]
Uncaught exception: ThisTimeForSureError

**Comment by ignazio1977** [comment]
Seven bugs on nested annotations alone. (>..<) really hope I'm done with this.
