### ISSUE TITLE
RBox axiom types

### ISSUE THREAD

**Issue by ignazio1977** [owlcs/owlapi#479]
Vincent Vialard's email on ML:

There seems to be different "definitions" for the RBox out there. For instance some include functionality axioms while others don't...

As it looks like the OWLAPI decided to have disjoint TBox and RBox, I would base my choice on the description from Krötzsch, Simančík and Horrocks in "Description Logic" [1].

According to their classification, the following axiom types are from the current TBoxAxiomTypes should be in RBoxAxiomTypes: INVERSE_OBJECT_PROPERTIES, SYMMETRIC_OBJECT_PROPERTY,  ASYMMETRIC_OBJECT_PROPERTY, REFLEXIVE_OBJECT_PROPERTY and IRREFLEXIVE_OBJECT_PROPERTY.

But as noted in the paper, reflexivity can be expressed as "top implies exists r self", so one could argue that it is a concept inclusion, like functionality (same goes for irreflexivity).

So I would say that at least INVERSE_OBJECT_PROPERTIES, SYMMETRIC_OBJECT_PROPERTY and ASYMMETRIC_OBJECT_PROPERTY should be moved to RBoxAxiomTypes.

**Comment by tsarkov** [comment]
Reflexivity axiom is less restrictive than its implementation via "top implies exists r self". ObjectHasSelf expression should contains a simple property to be in OWL 2 DL; the reflexivity axiom does not have this restriction. I would vote to keep Reflexivity axiom as a purely RBox one

**Comment by sesuncedu** [comment]
Do you have any idea of how the definitions are currently used?

Given that OWL-DL had no R box, and the role related axioms it provided
were in the T-box, defining the OWL 2-DL classes of axioms  as disjoint
seems arbitrary.

This suggests that the assignment of the various axiom types to sets may
have its roots in some immediate implementation requirement.  If the change
logs go back far enough this may give more insight.  If the subtyping was
done for implementation reasons, changes may have side effects.

(It's also possible that most uses end up fetching and filtering /
processing both sets. )

**Comment by ignazio1977** [comment]
There's no subtyping or formal distinction; the original list was made because of developers asking for a convenient way to fetch rbox axioms, for the purpose of computing metrics - if memory serves, some of this ended up in the categorisation criteria for ORE ontologies.

So, aside from a field effective shortcut, there is currently no deeper implication. I believe tbox and rbox categories are not used in the OWLAPI itself - we go by logical/non logical mostly.

Partition of the axiom types might be excessive, because of the issues described. I'm open to the idea of overlapping subsets, if we can agree to what makes an axiom type belong to one or the other. A bitmap of attributes might help explain and document this.

**Comment by sesuncedu** [comment]
I didn't mean to imply subtyping in the java type system- just the sets of
axiom types.

If the groupings mostly used for ORE then it may be safer to leave things
as is,  and handle retrieving subsets of axioms by axiom type with a better
self-tuning general filter / index approach (which is probably 5.1).

Which reminds me that I have some indexing changes I want to try and get in
for 5.0. Sigh.

**Comment by ignazio1977** [comment]
This isn't retrieving axioms per se - there's a convenience method on OWLOntology that uses this list to provide the axioms, but Vincent's original question simply refers to the list on AxiomType. 

Of those we can easily have many, since it's just static sets; it's too bad there isn't a method that takes in a few axiom types and collects them, efficiently or inefficiently - far as I understand the usage scenarios, a few milliseconds spent collecting the axioms are not important, since more complex operations happen afterwards. It just avoids having to write the boring code to select axiom types and pull the actual axioms out of the ontology.

Our quest for better indexing continues...

**Comment by ignazio1977** [comment]
... method accepting a few AxiomTypes and returning all matching axioms eh?... That could happen for 5, slow as it might be...
