### ISSUE TITLE
OWLOntologyManager.copyOntology does not copy imports

### ISSUE THREAD

**Issue by JoyW3000** [owlcs/owlapi#480]
Using the following code, the rdf import statement (<owl:imports rdf:resource="http://protege.stanford.edu/junitOntologies/testset/travel.owl"/>) is missing in the copied ontology when setting OntologyCopy to DEEP or SHALLOW.  MOVE is the only setting that copies the statement over. 

         OWLOntologyManager owlManager = OWLManager.createOWLOntologyManager();
         tOntology = owlManager.copyOntology(ontology, OntologyCopy.DEEP);

Furthermore, tOntology.getDirectImports() returns empty set even the rdf import statement exists in the copied ontology.

The sample ontology used in the test:
[protegeSample.txt](https://github.com/owlcs/owlapi/files/99559/protegeSample.txt)

**Comment by sesuncedu** [comment]
I am not sure if this is a bug or not; for a deep copy I am more inclined
to think yes.
Copying a ontology copies the axioms.  Import declarations aren't axioms,
so the imports would become lost.  I'm not sure what happens to imports
that are turned into includes (horrible rdf format edge case).

Copying just the declarations is not always what is wanted; most of the
time (but not always) one also wants the OWLOntology objects that the
imports resolved to.

The best approach might be a new copy mode,  OntologyCopyWithImports, which
would copy the entire imports closure, adding all imports declarations.

A temporary workaround is to copy imports declarations and resolved
imported ontologies by hand.

**Comment by JoyW3000** [comment]
Yes, copying imports declarations would work.  But the document itself remains without the import statements.  Are the toCopy ontology and the DEEP-copying ontology considered equivalent (equals())?  I would suggest to add imports to the DEEP copy.

**Comment by ignazio1977** [comment]
The javadoc for the method does not mention imports - but it does not mention annotations either and they are copied, so I think bug.

However, note:  

> tOntology.getDirectImports() returns empty set even the rdf import statement exists in the copied ontology.

This is expected behaviour. The ontology copied to a new manager is only the specified ontology, not its imports closure. And imported ontologies are not loaded in a manager when the imports annotation is added - only when the ontology is loaded from storage. This is existing behaviour, to allow adding an import to an ontology without having to load the import (think importing very large ontologies; one doesn't want to do that just to add an import and save).

**Comment by ignazio1977** [comment]
On version 5, this test passes:

    @Test
    public void testDeep() throws OWLOntologyCreationException {
        OWLOntology o = m.loadOntologyFromOntologyDocument(new StringDocumentSource(s));
        OWLOntology copy = m1.copyOntology(o, OntologyCopy.DEEP);
        assertEquals(m1, copy.getOWLOntologyManager());
        assertTrue(m.contains(o));
        assertTrue(m1.contains(copy));
        assertNotNull(m.getOntologyFormat(o));
        assertNotNull(m1.getOntologyFormat(o));
        assertEquals(asSet(o.annotations()), asSet(copy.annotations()));
    }

I'll try on 4.

**Comment by ignazio1977** [comment]
Imports declarations are ontology annotations. But we don't treat them the same as ontology annotations, and therefore they're not included in OWLOntology::annotations()

Why, why why do we make life harder for ourselves?

Bug.

**Comment by matthewhorridge** [comment]
> Imports declarations are ontology annotations

According the the OWL 2 FS doc they are distinguished from annotations.  Also, adding/removing an import slurps in or removes axioms to/from the imports closure - annotations don't do this.

**Comment by ignazio1977** [comment]
But `owl:imports` is an annotation property :-)

> There are also several built-in ontology properties; they are owl:imports, owl:priorVersion, owl:backwardCompatibleWith, and owl:incompatibleWith. Ontology annotations that use owl:imports have the extra effect of importing the target ontology.

https://www.w3.org/TR/owl-semantics/syntax.html


Anyway, my bad - I should have added a test for that.

**Comment by matthewhorridge** [comment]
> But owl:imports is an annotation property :-)
> https://www.w3.org/TR/owl-semantics/syntax.html

Hang on, thats ancient OWL 1....

In OWL 2 imports declarations are distinct from ontology annotations...

http://www.w3.org/TR/owl2-syntax/#General_Definitions

**Comment by sesuncedu** [comment]
Imports declarations are things that are retrieved for an OWLOntology using
a different set of methods to those used to retrieve axioms.

#operationalSemantics

**Comment by ignazio1977** [comment]
fixed on 4 and 5
