### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by mpuebla** [owlcs/owlapi#481]
How do you know if there exists a class in the ontology ?, so I understand the following code is for that:
 
OWLClass continend = factory.getOWLClass (IRI.create (ontologyIRI.toString () + "#" + "Continent"));

However, when instead of "Continent", put any other class name absent from the ontology, the code creates a new class with that name. Why do I need ?, is only access the class, if it already exists, not create it if it does not exist.

Another question:
 
When I run this:
ontology = manager.loadOntologyFromOntologyDocument (file);

OWLAPI load ontology in internal memory ?, ie load the entire file in internal memory.

Regards.

**Comment by ignazio1977** [comment]
> How do you know if there exists a class in the ontology ?, so I understand
> the following code is for that:
>
> OWLClass continend = factory.getOWLClass (IRI.create (ontologyIRI.toString
> () + "#" + "Continent"));
>
> However, when instead of "Continent", put any other class name absent from
> the ontology, the code creates a new class with that name. Why do I need ?,
> is only access the class, if it already exists, not create it if it does not
> exist.

An ontology contains axioms rather than classes, so what you need is
to test if an axiom in the ontology refers the class.
A shorthand for this is:

ontology.containsClassInSignature(IRI.create (ontologyIRI.toString() +
"#" + "Continent"));

>
> Another question:
>
> When I run this:
> ontology = manager.loadOntologyFromOntologyDocument (file);
>
> OWLAPI load ontology in internal memory ?, ie load the entire file in
> internal memory.
>

Yes.

**Comment by mpuebla** [comment]
Why ?, I do not think you need. Do you know a homologous to OWLAPI, do not do that?

I guess they do to accelerate the reasoning on the ontology, and exchange with reasoners. In my view, this disables the use of OWLAPI to ontologies with many individuals.

Regards.
