### ISSUE TITLE
New MigrateTo4Tricks

### ISSUE THREAD

**Issue by vincentvialard** [owlcs/owlapi#482]
Hi there,

I am updating some applications to the OWLAPI 4. I stumbled upon a couple of things that are not mentioned in the migration documentation.

* `OWLManager.createOWLOntologyManager(OWLDataFactory dataFactory)` is no longer available.
* `OWLOntologyID.getOntologyIRI()` now returns `Optional<IRI>`, had to replace calls with `.getOntologyIRI().get()`. Same goes for `OntologyID().getVersionIRI()`.

Furthermore, the interface `OWLDocumentFormat` still has "historical" `OntologyFormat` method names:
```java
    boolean isPrefixOWLOntologyFormat();
    PrefixDocumentFormat asPrefixOWLOntologyFormat();
```
and there is a link to the `OWLOntologyFormat` somewhere in its Javadoc. I can't tell if it is intentional (to limit API changes) or if it been overseen.

Vincent.

**Comment by ignazio1977** [comment]
Page updated.

It was mostly by mistake... However now that the release is out, it's best left as is, I think.
