### ISSUE TITLE
Replace all literal instances in an ontology.

### ISSUE THREAD

**Issue by mgskjaeveland** [owlcs/owlapi#487]
Hi, what would be the suggested approach to replace a literal throughout an ontology? I would like to replace all instances of the literal "Ann" with "Bob". I have found OWLEntityRenamer which would do the similar trick for entities, but no immediate solution for literals.
Thanks!

**Comment by ignazio1977** [comment]
As far as I know there is no class to do this. If you're willing to help with testing, though, it shouldn't be hard to add one.

**Comment by ignazio1977** [comment]
I've introduced OWLLiteralReplacer to handle this. It's currently available on the version4 branch. If you can check it out and build locally, I'd appreciate your feedback.

**Comment by matthewhorridge** [comment]
Would perhaps be nice to be able to slot it a matcher interface (Predicate) that matches literals to be replaced.  There could be some out of the box impls, based on RegEx patterns perhaps.

**Comment by ignazio1977** [comment]
Interesting idea, but how about a Function instead, producing the replacement literal? For non matches it would just return the input.

On the other hand the Predicate would be useful for determining which axioms need rebuilding, rather than rebuilding by default.

**Comment by matthewhorridge** [comment]
Good idea.

Actually, the whole thing could just be an OWLObject replacer :)

**Comment by ignazio1977** [comment]
`OWLObjectDuplicator` needs a second look - it's probably a good base for this.

**Comment by ignazio1977** [comment]
`OWLObjectTransformer` does the trick nicely, I think.
The predicate decides whether a particular object must further be edited; the function provides a way to replace any of the objects.

Problems: entities are easy to find for the predicate, through signatures. However expressions and literals are not so easy to spot. This means complex predicates (basically `OWLObjectVisitors`), or inefficient ones.
Also, this design supports one specific transform; to transform multiple types, e.g., object and data intersections, the function will look a lot like another `OWLObjectVisitor`.

The current design can be inefficient for intensive use and large number of different changes, but on the other hand it's fairly simple.
