### ISSUE TITLE
OWLManager error

### ISSUE THREAD

**Issue by phillord** [owlcs/owlapi#488]
I'm just trying to update tawny to OWL API 4. With 4.1.1 I get the following
error when trying to get the OWLManager.

    Caused by: java.lang.NoSuchMethodError: org.semanticweb.owlapi.util.CollectionFactory.emptySet()Ljava/util/Set;
    	at uk.ac.manchester.cs.owl.owlapi.OWLObjectImplWithoutEntityAndAnonCaching.<clinit>(OWLObjectImplWithoutEntityAndAnonCaching.java:40)
    	at uk.ac.manchester.cs.owl.owlapi.OWLDataFactoryImpl.<clinit>(OWLDataFactoryImpl.java:42)
        at org.semanticweb.owlapi.apibinding.OWLManager.getOWLDataFactory(OWLManager.java:154)

4.1.0 crashes in a different way -- looks more like my problem.

The OWL API binding package is 404 in the Javadoc online which isn't helping!

**Comment by ignazio1977** [comment]
On 2 Feb 2016 10:25 am, "Phil Lord" <notifications@github.com> wrote:
>
> I'm just trying to update tawny to OWL API 4 With 411 I get the following
> error when trying to get the OWLManager
>
> Caused by: javalangNoSuchMethodError:
orgsemanticwebowlapiutilCollectionFactoryemptySet()Ljava/util/Set;

Feels like multiple versions in the classpath - is that possible?

Incidentally, I'll release 4.1.4 soon, it includes a few fixes to maven
dependencies - this might make your job easier.

'Soon' here to mean this evening, possibly.

I.

>     at
ukacmanchestercsowlowlapiOWLObjectImplWithoutEntityAndAnonCaching<clinit>(OWLObjectImplWithoutEntityAndAnonCachingjava:40)
>     at
ukacmanchestercsowlowlapiOWLDataFactoryImpl<clinit>(OWLDataFactoryImpljava:42)
>     at
orgsemanticwebowlapiapibindingOWLManagergetOWLDataFactory(OWLManagerjava:154)
>
> 410 crashes in a different way -- looks more like my problem
>
> The OWL API binding package is 404 in the Javadoc online which isn't
helping!

**Comment by phillord** [comment]
Yeah, got it. Multiple versions. Sorry.

Forgot to comment out the reasoner dependencies -- they were pulling in the wrong versions. Of course, that will be a different problem! Now I need to find updated reasoners.
