### ISSUE TITLE
java.lang.NoClassDefFoundError: org/openrdf/rio/RDFFormat

### ISSUE THREAD

**Issue by Buglish** [owlcs/owlapi#490]
Hi,

I have developed an application making use of the Stanford NLP and openIE libraries and now interact SQWRLQueryEngine to run SQWRL queries on an Ontology using both OWLAPI lib and swrlapi source. (<modelVersion>4.0.0</modelVersion>)

I have tried many different version combinations but the error persists. Originally I attempted at including different versions of sesame-rio-api (2.7.0-beta1/2.7.16/2.8.9/4.0.1)

My error is similar to this link: https://github.com/owlcs/owlapi/issues/447

Then after seeing the link above I tried diffirent versions of OWLAPI (3.5.4/4.1.0/4.1.4) with no success by trying osgi or distribution separately.

The logic works fine up to the point where the OWLOntologyManager is instantiated
OWLOntologyManager ontologyManager = OWLManager.createOWLOntologyManager();

Included Libraries:
aopalliance-1.0
axis-1.4
checker-1.9.10
guava-18.0
guice-3.0
guice-assistedinject-3.0
guice-multibindings-3.0
javanlp-core
javax.inject
jena-arq-3.0.0
jep-2.23
log4j-1.2.17
owlapi-distribution-4.1.0
sesame-rio-api-4.0.1
stanford-openie-src

My Exception Stack Trace
INFO: An exception was caught and reported. Message: java.lang.NoClassDefFoundError: org/openrdf/rio/RDFFormat
org.semanticweb.owlapi.model.OWLRuntimeException: Injection failed for factory: interface org.semanticweb.owlapi.model.OWLDocumentFormatFactory type: interface org.semanticweb.owlapi.model.OWLDocumentFormat
	at org.semanticweb.owlapi.OWLAPIServiceLoaderModule.loadFactories(OWLAPIServiceLoaderModule.java:114)
	at org.semanticweb.owlapi.OWLAPIServiceLoaderModule.configure(OWLAPIServiceLoaderModule.java:58)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:59)
	at org.semanticweb.owlapi.apibinding.OWLManager.createInjector(OWLManager.java:89)
	at org.semanticweb.owlapi.apibinding.OWLManager.instatiateOWLOntologyManager(OWLManager.java:97)
	at org.semanticweb.owlapi.apibinding.OWLManager.createOWLOntologyManager(OWLManager.java:58)
	at org.sjdp.sqwrl.GUI.parseTextToQueryAndRun(GUI.java:295)
	at org.sjdp.sqwrl.GUI.actionPerformed(GUI.java:220)
Caused by: java.util.ServiceConfigurationError: org.semanticweb.owlapi.model.OWLDocumentFormatFactory: Provider org.semanticweb.owlapi.formats.BinaryRDFDocumentFormatFactory could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
Caused by: java.lang.NoClassDefFoundError: org/openrdf/rio/RDFFormat

**Comment by ignazio1977** [comment]
The problem is that not all required jars are available on the classpath. The full list of external dependencies required is as follows (the paths are from my local maven repository but the jars can be downloaded without maven, although it's a bit of a laborious process)

    /.m2/repository/com/google/code/findbugs/jsr305/3.0.0/jsr305-3.0.0.jar
    /.m2/repository/org/tukaani/xz/1.5/xz-1.5.jar
    /.m2/repository/org/openrdf/sesame/sesame-model/2.7.16/sesame-model-2.7.16.jar
    /.m2/repository/org/openrdf/sesame/sesame-util/2.7.16/sesame-util-2.7.16.jar
    /.m2/repository/org/openrdf/sesame/sesame-rio-api/2.7.16/sesame-rio-api-2.7.16.jar
    /.m2/repository/org/openrdf/sesame/sesame-rio-languages/2.7.16/sesame-rio-languages-2.7.16.jar
    /.m2/repository/org/openrdf/sesame/sesame-rio-datatypes/2.7.16/sesame-rio-datatypes-2.7.16.jar
    /.m2/repository/org/openrdf/sesame/sesame-rio-binary/2.7.16/sesame-rio-binary-2.7.16.jar
    /.m2/repository/org/openrdf/sesame/sesame-rio-n3/2.7.16/sesame-rio-n3-2.7.16.jar
    /.m2/repository/org/openrdf/sesame/sesame-rio-nquads/2.7.16/sesame-rio-nquads-2.7.16.jar
    /.m2/repository/org/openrdf/sesame/sesame-rio-ntriples/2.7.16/sesame-rio-ntriples-2.7.16.jar
    /.m2/repository/org/openrdf/sesame/sesame-rio-rdfjson/2.7.16/sesame-rio-rdfjson-2.7.16.jar
    /.m2/repository/com/fasterxml/jackson/core/jackson-core/2.5.1/jackson-core-2.5.1.jar
    /.m2/repository/org/openrdf/sesame/sesame-rio-rdfxml/2.7.16/sesame-rio-rdfxml-2.7.16.jar
    /.m2/repository/org/openrdf/sesame/sesame-rio-trix/2.7.16/sesame-rio-trix-2.7.16.jar
    /.m2/repository/org/openrdf/sesame/sesame-rio-turtle/2.7.16/sesame-rio-turtle-2.7.16.jar
    /.m2/repository/org/openrdf/sesame/sesame-rio-trig/2.7.16/sesame-rio-trig-2.7.16.jar
    /.m2/repository/com/github/jsonld-java/jsonld-java-sesame/0.5.0/jsonld-java-sesame-0.5.0.jar
    /.m2/repository/com/github/jsonld-java/jsonld-java/0.5.0/jsonld-java-0.5.0.jar
    /.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.5.1/jackson-databind-2.5.1.jar
    /.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.5.1/jackson-annotations-2.5.1.jar
    /.m2/repository/org/apache/httpcomponents/httpclient-cache/4.2.5/httpclient-cache-4.2.5.jar
    /.m2/repository/org/apache/httpcomponents/httpclient/4.2.5/httpclient-4.2.5.jar
    /.m2/repository/org/apache/httpcomponents/httpcore/4.2.4/httpcore-4.2.4.jar
    /.m2/repository/commons-codec/commons-codec/1.6/commons-codec-1.6.jar
    /.m2/repository/org/slf4j/jcl-over-slf4j/1.7.7/jcl-over-slf4j-1.7.7.jar
    /.m2/repository/org/semarglproject/semargl-sesame/0.6.1/semargl-sesame-0.6.1.jar
    /.m2/repository/org/semarglproject/semargl-core/0.6.1/semargl-core-0.6.1.jar
    /.m2/repository/org/semarglproject/semargl-rdfa/0.6.1/semargl-rdfa-0.6.1.jar
    /.m2/repository/org/semarglproject/semargl-rdf/0.6.1/semargl-rdf-0.6.1.jar
    /.m2/repository/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
    /.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
    /.m2/repository/junit/junit/4.12/junit-4.12.jar
    /.m2/repository/org/mockito/mockito-all/1.9.5/mockito-all-1.9.5.jar
    /.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar
    /.m2/repository/com/google/inject/guice/4.0/guice-4.0.jar
    /.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar
    /.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
    /.m2/repository/com/google/inject/extensions/guice-assistedinject/4.0/guice-assistedinject-4.0.jar
    /.m2/repository/com/google/inject/extensions/guice-multibindings/4.0/guice-multibindings-4.0.jar
    /.m2/repository/com/google/code/findbugs/jsr305/2.0.1/jsr305-2.0.1.jar
    /.m2/repository/org/slf4j/slf4j-api/1.7.10/slf4j-api-1.7.10.jar
    /.m2/repository/org/slf4j/slf4j-simple/1.7.10/slf4j-simple-1.7.10.jar
    /.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar

**Comment by Buglish** [comment]
Thank you the dependency issue is now gone :)

**Comment by jindeli05** [comment]
do i have to download all

**Comment by ignazio1977** [comment]
Yes
