### ISSUE TITLE
org.semanticweb.owlapi.model.IRI.getShortForm() unhandled cases

### ISSUE THREAD

**Issue by adrianR2** [owlcs/owlapi#491]
I encountered several cases where getShortForm() did not provide the expected result. I put two of them herein:

```
// this one is OK
	IRI iri= org.semanticweb.owlapi.model.IRI.create("http://semantic.r-2apps.com/IOC_rol/C#Auberge_de_la_Gare_2015_SENC");
	String str1= iri.getShortForm(); System.out.println("ShortForm="+str1);
	String str2 = iri.getNamespace(); System.out.println("Namespace="+str2);
```
Output:
ShortForm=Auberge_de_la_Gare_2015_SENC
Namespace=http://semantic.r-2apps.com/IOC_rol/C#

```
	iri= org.semanticweb.owlapi.model.IRI.create("http://semantic.r-2apps.com/IOC_rol/C#City_Power_Sweeping_(2015)");
	str1= iri.getShortForm(); System.out.println("ShortForm="+str1);
	str2 = iri.getNamespace(); System.out.println("Namespace="+str2);
```
Output:
ShortForm=C#City_Power_Sweeping_(2015)
Namespace=http://semantic.r-2apps.com/IOC_rol/C#City_Power_Sweeping_(2015)

	iri= org.semanticweb.owlapi.model.IRI.create("http://semantic.r-2apps.com/IOC_rol/C#Fenêtres_A.G.M._(2015)_Inc.");
	str1= iri.getShortForm(); System.out.println("ShortForm="+str1);
	str2 = iri.getNamespace(); System.out.println("Namespace="+str2);
Output:
ShortForm=__Inc.
Namespace=http://semantic.r-2apps.com/IOC_rol/C#Fenêtres_A.G.M._(2015)

**Comment by ignazio1977** [comment]
`HasShortForm::getShortForm` is not specified as providing any constraints on its output. The IRI implementation is using the remainder, if one exists, or the substring from the last '/' character.

What features would you expect in this rendering? There might be another method already doing the job.

**Comment by adrianR2** [comment]
Thank you for clarification. Therefore, all the results I showed above are in accordance with the intended functionality of getShortForm()?
I expected it to return the substring that follows '#' in all cases, like it did in my first example.
