### ISSUE TITLE
Anonymous individuals parsing problems

### ISSUE THREAD

**Issue by vincentvialard** [owlcs/owlapi#494]
Hi there,

we had troubles with a dataset from a SPARQL Test Suite and found out the OWLAPI still has problems with anonymous individuals. This problem seems to be related to closed issue #443.

I wrote an ontology with 1 anonymous individual and 2 assertions `C(_:a), r(_:a,_:a)` in OWL/XML and NTriple format. We have a weird behavior in both cases:

1. Load OWL/XML file (.owx) and take a look at the axioms:
  * ClassAssertion(<http://www.derivo.de/ontologies/examples/anonymous-individuals#C> _:genid1)
  * ObjectPropertyAssertion(<http://www.derivo.de/ontologies/examples/anonymous-individuals#r> _:genid2 _:genid3)
  
  The three occurences of the anonymous individual have **not been identified as refering to the same individual**, and it gets saved that way when you save the ontology under NTriples, OWL/XML, RDF/XML, RioTurtle and Turtle formats.

2. Load NTriples file (.nt) and take a look at the axioms:
  * ClassAssertion(<http://www.derivo.de/ontologies/examples/anonymous-individuals#C> _:genid1)
  * ObjectPropertyAssertion(<http://www.derivo.de/ontologies/examples/anonymous-individuals#r> _:genid1 _:genid1)

  The three occurences of the anonymous individual have been correctly identified as refering to the same individual, and it gets saved that way under OWL/XML format, but **the assertions are not saved at all** under NTriples, RDF/XML, RioTurtle and Turtle formats.

I attached the original and converted ontologies in a zip file. the first extension give the source format, the second the target format (.owx.ttl means OWL/XML was loaded and saved to Turtle).
[anonymous-individuals.zip](https://github.com/owlcs/owlapi/files/150638/anonymous-individuals.zip)

Vincent.

**Comment by ignazio1977** [comment]
Clearly OWL/XML was feeling left out, what with being non rdf based and not being one of the special languages either :-)

**Comment by vincentvialard** [comment]
It sure looks like a kind of format jungle out there being at the border between various communities...

Do you have an Idea why the other renderers seem to ignore anonymous individuals?

**Comment by ignazio1977** [comment]
Not yet, it could be a number of causes.

**Comment by ignazio1977** [comment]
Looks like you have a talent for spotting double bugs - this is the second instance, I believe :-)

The OWL/XML parsing loses the shared individual in the usual manner - same bug as #443 in a different place. However, the assertions are lost because of a different issue: anonymous node assertions take root anonymous nodes as starting point, and a root anon node is a node that never appears as an object. Problem here is that this node also appears as an object, so it never gets selected. Good catch.

**Comment by vincentvialard** [comment]
Thanks for the fix Ignazio!

I've been away from my OWLAPI projects for a while, and updated to 4.2.3 today.

There is still an issue remaining with TurtleDocumentFormat, it looses self referencing in my example because it tries to write everything using unlabelled blank nodes with the `[]` syntax. This syntax can not be used to represent parts of the graph that have cycles.

Everything is fine with the RioTurtleDocumentFormat though...

OWL/XML input:
``
    <ClassAssertion>
        <Class IRI="#C"/>
        <AnonymousIndividual nodeID="a"/>
    </ClassAssertion>
    <ObjectPropertyAssertion>
        <ObjectProperty IRI="#r"/>
        <AnonymousIndividual nodeID="a"/>
        <AnonymousIndividual nodeID="a"/>
    </ObjectPropertyAssertion>
``

TurtleDocumentFormat output:
``
[ rdf:type :C ;
  :r [ ]
] .
``

RioTurtleDocumentFormat output:
``
_:genid1 a :C ;
	:r _:genid1 .
``
