### ISSUE TITLE
read skos Collection/orderCollection with owlapi

### ISSUE THREAD

**Issue by miledrousset** [owlcs/owlapi#497]
Hello,
I use skos-api-onejar OWLAPI version 4.0.2,
I would like to know how to read such tags SKOS (ConceptGroup or skos: Collection)
I try to read the thesaurus of Unesco
type tags (iso-thes: ConceptGroup) xmlns: iso-thes = "http://purl.org/iso25964/skos-thes#"
are not readed by the API, but only the tags:
Skos: ConceptScheme
and
Skos: Concept

thank you in advance for your help
I you nead a sample, i can give you some one.

**Comment by ignazio1977** [comment]
Yes, an example would be useful

**Comment by miledrousset** [comment]
here is an example,

<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
  xmlns:skos="http://www.w3.org/2004/02/skos/core#"
  xmlns:uneskos="http://purl.org/umu/uneskos#"
  xmlns:dcterms="http://purl.org/dc/terms/"
  xmlns:iso-thes="http://purl.org/iso25964/skos-thes#"
  xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">

** this part is readed correctly **

  <skos:ConceptScheme rdf:about="http://skos.um.es/unescothes/CS000">
    <uneskos:hasMicroThesaurus rdf:resource="http://skos.um.es/unescothes/COL001"/>
    <dcterms:title xml:lang="en">UNESCO Thesaurus</dcterms:title>
    <dcterms:title xml:lang="es">Tesauro de la UNESCO</dcterms:title>
    <dcterms:title xml:lang="fr">Thésaurus de l'UNESCO</dcterms:title>
    <dcterms:title xml:lang="ru">Тезаурус ЮНЕСКО</dcterms:title>
    <skos:prefLabel xml:lang="en">UNESCO Thesaurus</skos:prefLabel>
    <skos:prefLabel xml:lang="es">Tesauro de la UNESCO</skos:prefLabel>
    <skos:prefLabel xml:lang="fr">Thésaurus de l'UNESCO</skos:prefLabel>
    <skos:prefLabel xml:lang="ru">Тезаурус ЮНЕСКО</skos:prefLabel>
    <dcterms:source rdf:resource="http://databases.unesco.org/thesaurus/"/>
    <dcterms:source rdf:resource="http://www2.ulcc.ac.uk/unesco/"/>
    <dcterms:creator>UNESCO</dcterms:creator>
    <dcterms:publisher>Juan Antonio Pastor Sánchez</dcterms:publisher>
    <dcterms:date rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2015-09-16T00:00:00Z</dcterms:date>
    <skos:hasTopConcept rdf:resource="http://skos.um.es/unescothes/C00008"/>
    
    <skos:hasTopConcept rdf:resource="http://skos.um.es/unescothes/C00016"/>
  </skos:ConceptScheme>


** this part is not readed by the API ** **it s same with    ConceptGroup or Collection or orderedCollection**

  <skos:Collection rdf:about="http://skos.um.es/unescothes/COL001">
    <rdfs:label xml:lang="en">Education</rdfs:label>
    <rdfs:label xml:lang="fr">Education</rdfs:label>
    <rdfs:label xml:lang="es">Educación</rdfs:label>
    <rdfs:label xml:lang="ru">Образование</rdfs:label>
    <skos:prefLabel xml:lang="en">Education</skos:prefLabel>
    <skos:prefLabel xml:lang="fr">Education</skos:prefLabel>
    <skos:prefLabel xml:lang="es">Educación</skos:prefLabel>
    <skos:prefLabel xml:lang="ru">Образование</skos:prefLabel>
    <skos:notation>1</skos:notation>
    <iso-thes:microThesaurusOf rdf:resource="http://skos.um.es/unescothes/CS000"/>
    <iso-thes:subGroup rdf:resource="http://skos.um.es/unescothes/COL165"/>
  </skos:Collection>

  <skos:Collection rdf:about="http://skos.um.es/unescothes/COL165">
    <rdfs:label xml:lang="en">Educational evaluation</rdfs:label>
    <rdfs:label xml:lang="fr">Evaluation de l'éducation</rdfs:label>
    <rdfs:label xml:lang="es">Evaluación de la educación</rdfs:label>
    <rdfs:label xml:lang="ru">Процессы оценки в сфере образования</rdfs:label>
    <skos:prefLabel xml:lang="en">Educational evaluation</skos:prefLabel>
    <skos:prefLabel xml:lang="fr">Evaluation de l'éducation</skos:prefLabel>
    <skos:prefLabel xml:lang="es">Evaluación de la educación</skos:prefLabel>
    <skos:prefLabel xml:lang="ru">Процессы оценки в сфере образования</skos:prefLabel>
    <skos:notation>1.65</skos:notation>
    <iso-thes:superGroup rdf:resource="http://skos.um.es/unescothes/COL001"/>
    <skos:member rdf:resource="http://skos.um.es/unescothes/C00008"/>
    <skos:member rdf:resource="http://skos.um.es/unescothes/C00010"/>
    <skos:member rdf:resource="http://skos.um.es/unescothes/C01110"/>
    <uneskos:hasMainConcept rdf:resource="http://skos.um.es/unescothes/C00008"/>
  </skos:Collection>


** this part is readed correctly **
  <skos:Concept rdf:about="http://skos.um.es/unescothes/C00008">
    <skos:prefLabel xml:lang="en">Academic achievement</skos:prefLabel>
    <skos:prefLabel xml:lang="fr">Rendement scolaire</skos:prefLabel>
    <skos:prefLabel xml:lang="es">Rendimiento escolar</skos:prefLabel>
    <skos:prefLabel xml:lang="ru">Академическая успеваемость</skos:prefLabel>
    <uneskos:memberOf rdf:resource="http://skos.um.es/unescothes/COL165"/>
    <skos:inScheme rdf:resource="http://skos.um.es/unescothes/CS000"/>
    <skos:altLabel xml:lang="en">Academic performance</skos:altLabel>
    <skos:altLabel xml:lang="en">Student achievement</skos:altLabel>
    <skos:altLabel xml:lang="en">Student progress</skos:altLabel>
    <skos:altLabel xml:lang="es">Progreso académico</skos:altLabel>
    <skos:altLabel xml:lang="es">Progreso escolar</skos:altLabel>
    <skos:altLabel xml:lang="es">Progreso estudiantil</skos:altLabel>
    <skos:altLabel xml:lang="es">Rendimiento académico</skos:altLabel>
    <skos:altLabel xml:lang="es">Rendimiento del estudiante</skos:altLabel>
    <skos:altLabel xml:lang="es">Rendimiento estudiantil</skos:altLabel>
    <skos:altLabel xml:lang="fr">Performance académique</skos:altLabel>
    <skos:altLabel xml:lang="fr">Performance scolaire</skos:altLabel>
    <skos:altLabel xml:lang="fr">Rendement académique</skos:altLabel>
    <skos:altLabel xml:lang="fr">Rendement de l'étudiant</skos:altLabel>
    <skos:altLabel xml:lang="ru">Характеристики академической работы</skos:altLabel>
    <skos:altLabel xml:lang="ru">Успеваемость учащихся</skos:altLabel>
    <skos:altLabel xml:lang="ru">Успехи учащихся</skos:altLabel>
    <skos:narrower rdf:resource="http://skos.um.es/unescothes/C00010"/>
    <skos:related rdf:resource="http://skos.um.es/unescothes/C00014"/>
    <skos:related rdf:resource="http://skos.um.es/unescothes/C00028"/>
    <skos:related rdf:resource="http://skos.um.es/unescothes/C01271"/>
    <skos:related rdf:resource="http://skos.um.es/unescothes/C03862"/>
    <skos:related rdf:resource="http://skos.um.es/unescothes/C03949"/>
    <uneskos:mainConceptOf rdf:resource="http://skos.um.es/unescothes/COL165"/>
    <skos:topConceptOf rdf:resource="http://skos.um.es/unescothes/CS000"/>
  </skos:Concept>

  <skos:Concept rdf:about="http://skos.um.es/unescothes/C00010">
    <skos:prefLabel xml:lang="en">Academic failure</skos:prefLabel>
    <skos:prefLabel xml:lang="fr">Échec scolaire</skos:prefLabel>
    <skos:prefLabel xml:lang="es">Fracaso escolar</skos:prefLabel>
    <skos:prefLabel xml:lang="ru">Академическая неуспеваемость</skos:prefLabel>
    <uneskos:memberOf rdf:resource="http://skos.um.es/unescothes/COL165"/>
    <skos:inScheme rdf:resource="http://skos.um.es/unescothes/CS000"/>
    <skos:broader rdf:resource="http://skos.um.es/unescothes/C00008"/>
    <skos:narrower rdf:resource="http://skos.um.es/unescothes/C01110"/>
    <skos:narrower rdf:resource="http://skos.um.es/unescothes/C01717"/>
    <skos:related rdf:resource="http://skos.um.es/unescothes/C01109"/>
    <skos:related rdf:resource="http://skos.um.es/unescothes/C02336"/>
  </skos:Concept>

  <skos:Concept rdf:about="http://skos.um.es/unescothes/C01110">
    <skos:prefLabel xml:lang="en">Dropping out</skos:prefLabel>
    <skos:prefLabel xml:lang="fr">Abandon en cours d'études</skos:prefLabel>
    <skos:prefLabel xml:lang="es">Deserción escolar</skos:prefLabel>
    <skos:prefLabel xml:lang="ru">Отсев учащихся</skos:prefLabel>
    <uneskos:memberOf rdf:resource="http://skos.um.es/unescothes/COL165"/>
    <skos:inScheme rdf:resource="http://skos.um.es/unescothes/CS000"/>
    <skos:broader rdf:resource="http://skos.um.es/unescothes/C00010"/>
    <skos:related rdf:resource="http://skos.um.es/unescothes/C01108"/>
    <skos:related rdf:resource="http://skos.um.es/unescothes/C01109"/>
    <skos:related rdf:resource="http://skos.um.es/unescothes/C01297"/>
    <skos:scopeNote xml:lang="es">Partida prematura del colegio antes de haber concluído un ciclo completo o un curso ya iniciado.</skos:scopeNote>
    <skos:scopeNote xml:lang="fr">Départ prématuré de l'école avant d'avoir complété un cycle ou un cours commencés.</skos:scopeNote>
    <skos:scopeNote xml:lang="ru">Преждевременное завершение пребывания в школе до окончания начатого цикла или курса обучения.</skos:scopeNote>
    <skos:altLabel xml:lang="es">Abandono escolar</skos:altLabel>
    <skos:altLabel xml:lang="fr">Abandon précoce</skos:altLabel>
    <skos:altLabel xml:lang="fr">Abandon scolaire</skos:altLabel>
    <skos:altLabel xml:lang="fr">Décrochage scolaire</skos:altLabel>
  </skos:Concept>

</rdf:RDF>

**Comment by miledrousset** [comment]
[test_unesco.rdf.zip](https://github.com/owlcs/owlapi/files/167121/test_unesco.rdf.zip)

**Comment by ignazio1977** [comment]
The SKOS API does not seem to have methods to access collections. However, loading the file with OWL API allows you to access all assertions about the Collection instances:

            OWLOntologyManager m = OWLManager.createOWLOntologyManager();
            m.getOntologyParsers().set(new RDFXMLParserFactory());
            OWLOntology ont = m.loadOntologyFromOntologyDocument(new File("test_unesco.rdf"));
            OWLNamedIndividual ind = m.getOWLDataFactory().getOWLNamedIndividual(IRI.create(
                "http://skos.um.es/unescothes/COL001"));
            Set<? extends OWLAxiom> axioms = ont.getAxioms(ind);
            for (OWLAxiom ax : axioms) {
                System.out.println("ReadSKOSExample.ReadSKOSExample() " + ax);
            }
            axioms = ont.getAnnotationAssertionAxioms(ind.getIRI());
            for (OWLAxiom ax : axioms) {
                System.out.println("ReadSKOSExample.ReadSKOSExample() " + ax);
            }
            axioms = ont.getDataPropertyAssertionAxioms(ind);
            for (OWLAxiom ax : axioms) {
                System.out.println("ReadSKOSExample.ReadSKOSExample() " + ax);
            }
            axioms = ont.getObjectPropertyAssertionAxioms(ind);
            for (OWLAxiom ax : axioms) {
                System.out.println("ReadSKOSExample.ReadSKOSExample() " + ax);
            }

**Comment by miledrousset** [comment]
thank you very much
it works perfectly

**Comment by jlamarque34** [comment]
Hello,
I am searching a way to extract metadata placed under a **skos:ConceptScheme** like in the example of @miledrousset  above but without knowing the IRI of the ontology.
I only use owlapi and when parsing a skos file the ontology is seen as "anonymous" so no axioms/annotations can be processed.
How to get the **skos:ConceptScheme** element and read the annotations within ?
Is it possible ? Could you please help with some examples ?
Thank you.
Jérôme

**Comment by ignazio1977** [comment]
@jlamarque34 By 'not knowing the IRI of the ontology' do you mean cases where you don't know where the ontology can be retrieved from, or the fact that the example used here results in an anonymous ontology in OWL API?

The example above is an anonymous ontology because it, strictly speaking, is not an ontology - it's just an RDF file, and there is no ontology declaration in it. It can be loaded but it cannot have an ontology IRI associated.

If you know where to retrieve the RDF file you're interested in, you can always load it and it will result in an anonymous ontology but one you can get axioms out of (depending on the actual content of the RDF file).

**Comment by jlamarque34** [comment]
Thanks for your reply.
As a newbie in semantic web, my vocabulary (joke... ) may lack of precision...

I am trying to rely on the example you gave above :

```
OWLNamedIndividual ind = m.getOWLDataFactory().getOWLNamedIndividual(IRI.create(
            "http://skos.um.es/unescothes/COL001"));
```

But I am stuck with **http://skos.um.es/unescothes/COL001** which I do not know in my case.
Files are uploaded and then parsed in our system and we need to extract some metadata (defined within an **owl:Ontology** or a **skos:ConceptScheme**).
With a "real" ontology it is okay.

Let's take another example : 

```
<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF xml:base="http://www.eionet.europa.eu/gemet/"
 xmlns:sioc="http://rdfs.org/sioc/ns#"
 xmlns:dc="http://purl.org/dc/elements/1.1/"
 xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
 xmlns:geo="http://www.w3.org/2003/01/geo/wgs84_pos#"
 xmlns:foaf="http://xmlns.com/foaf/0.1/"
 xmlns:dwc="http://rs.tdwg.org/dwc/terms/"
 xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
 xmlns:owl="http://www.w3.org/2002/07/owl#"
 xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
 xmlns:skos="http://www.w3.org/2004/02/skos/core#"
 xmlns:cc="http://creativecommons.org/ns#"
 xmlns:dcterms="http://purl.org/dc/terms/"
 xmlns="http://www.eionet.europa.eu/gemet/2004/06/gemet-schema.rdf#">

<skos:ConceptScheme rdf:about="gemetThesaurus/">
    <rdfs:label>GEMET - Concepts, version 4.0.1, 2017-06-28T14:17:23.117209+00:00</rdfs:label>
    <dcterms:licence rdf:resource="http://creativecommons.org/licenses/by/2.5/dk/"/>
</skos:ConceptScheme>
...
...
```

How to programmatically retrieve metadata under **<skos:ConceptScheme rdf:about="gemetThesaurus/">** i.e. getting the SKOS thesaurus IRI to be able to invoke : 

```
OWLNamedIndividual ind = m.getOWLDataFactory().getOWLNamedIndividual(IRI.create(
                "http://www.eionet.europa.eu/gemet/gemetThesaurus/"));
Set<? extends OWLAxiom> axioms = ont.getAnnotationAssertionAxioms(ind.getIRI());  // Works !
```

Hope to be clear enough...
Thanks again.

Jérôme
