### ISSUE TITLE
Profile validation throws exception on ontology annotations

### ISSUE THREAD

**Issue by JoyW3000** [owlcs/owlapi#498]
I used some sample files for ontology validation against profiles using OWLProfileReport report = profile.checkOntology(ontology).  The method throws "org.semanticweb.owlapi.model.OWLRuntimeException:  No current axiom; is the walker being used outside of an ontology visit?" caused by ontology annotation lines that has annotation properties that are not in the built-in rdf vocab list.  If you comment them out, they run fine.  But these owl/xml or turtle formats seem legit.  I'm not sure if it's a bug or something.  I attached two files that got these exceptions.  The lines that caused the exceptions are:

<protege:defaultLanguage rdf:datatype="http://www.w3.org/2001/XMLSchema#string">en</protege:defaultLanguage>

<http://purl.org/dc/elements/1.1/date> "2007-01-01"^^xsd:date ;

<http://purl.org/dc/elements/1.1/format> "text/turtle"^^xsd:string ;

[sample1.txt](https://github.com/owlcs/owlapi/files/167666/sample1.txt)
[sample2.txt](https://github.com/owlcs/owlapi/files/167667/sample2.txt)

**Comment by ignazio1977** [comment]
Which version of OWLAPI are you using? This looks like a bug that was fixed a while ago.

**Comment by JoyW3000** [comment]
I use owlapi-osgidistribution/4.1.3

**Comment by ignazio1977** [comment]
It's a bug - the code that checks the current axiom is duplicated. One copy got fixed two years ago, but the other escaped detection and it is what's failing here.
