### ISSUE TITLE
Should o.signature() in OWL API 5 return Thing and Nothing?

### ISSUE THREAD

**Issue by matentzn** [owlcs/owlapi#499]
I think it should.

OWLOntologyManager man = OWLManager.createOWLOntologyManager();
IRI IOR = IRI.create("http://owl.api.tutorial");
OWLOntology o = man.createOntology(IOR);
o.signature().forEach(System.out::println);

Currently returns nothing.

**Comment by ignazio1977** [comment]
I genuinely don't know.

I cannot find any definition of signature that specifies whether Thing and Nothing (or Top and Bottom) are included or excluded; there would obviously be an effect on all applications working with the signature, so if anything I'd be tempted to add a new method (e.g., `signatureAndBuiltins()`).

However, if Thing and Nothing are included, should TopDataProperty, TopObjectProperty, etc - also appear? Should all builtin entities be represented?

**Comment by matentzn** [comment]
Okay, I asked a bit around (Uli Sattler etc.), and unless there are other views, we leave it as is and do not return them.
