### ISSUE TITLE
Expressivity Checker for EL and FL

### ISSUE THREAD

**Issue by matentzn** [owlcs/owlapi#500]
Usually, we use the DLExpressivityChecker to determine the logical language in which the ontology can be expressed in. However, there are many extremely lightweight ontologies out there, and we would like to distinguish all three base languages (EL, FL and AL, currently we get only AL, see here: https://en.wikipedia.org/wiki/Description_logic#Naming_convention).  Now, since this languages are somewhat independent, the ExpressivityChecker will need to most likely return three sets of constructs, one from the EL, one from the FL and one from the AL perspective. Long story cut short: I have had many people ask for: is this ontology in EL++? and I think the OWL API should be able to tell.

**Comment by LorenzBuehmann** [comment]
For EL, there is `org.semanticweb.owlapi.profiles.OWL2ELProfile::checkOntology(OWLOntology ontology)` [1]

[1] http://owlapi.sourceforge.net/javadoc/org/semanticweb/owlapi/profiles/OWL2ELProfile.html

**Comment by ignazio1977** [comment]
Fresh DLExpressivityChecker now available in version 6, 5, and 4.
