### ISSUE TITLE
Annotations lost on entity renaming of SWRLRules

### ISSUE THREAD

**Issue by matthewhorridge** [owlcs/owlapi#501]
See https://github.com/protegeproject/protege/issues/371

**Comment by ignazio1977** [comment]
Bug indeed

**Comment by martinjoconnor** [comment]
Great. Thanks for the quick fix. 

Any idea when you will be doing a new incremental release?

**Comment by ignazio1977** [comment]
There are a couple more niggles to be fixed - probably Thursday
