### ISSUE TITLE
OWLProfileReport mistakenly defines UseOfUndeclaredAnnotationProperty on ontology annotations

### ISSUE THREAD

**Issue by JoyW3000** [owlcs/owlapi#504]
OWLProfileReport defines "UseOfUndeclaredAnnotationProperty" on annotation property of ontology annotations.  According to OWL2, declaration of an annotation property should only apply to axioms, specifically AnnotationAxiom.  The sample ontology I used to check (DL) violations is attached.  I received the following violations:

_Use of undeclared annotation property: <http://purl.org/dc/elements/1.1/date> in annotation [Annotation(<http://purl.org/dc/elements/1.1/date> "2014-07-21"^^xsd:date) in null]

Use of undeclared annotation property: <http://purl.org/dc/elements/1.1/contributor> in annotation [Annotation(<http://purl.org/dc/elements/1.1/contributor> "Joe Smith"^^xsd:string) in null]

Use of undeclared annotation property: <http://purl.org/dc/elements/1.1/title> in annotation [Annotation(<http://purl.org/dc/elements/1.1/title> "Annotation Properties"^^xsd:string) in null]_

Apparently, it only affects the annotation properties with special namespaces.  

P.S. I use owlapi-osgidistribution-5.0.0

[sample.txt](https://github.com/owlcs/owlapi/files/176598/sample.txt)

**Comment by ignazio1977** [comment]
Far as I can tell, the standard mapping to rdf requires annotation properties used in ontology annotations to be declared https://www.w3.org/TR/owl2-mapping-to-rdf/#Parsing_of_the_Ontology_Header_and_Declarations

The patterns to produce ontology annotations are no different from those for regular annotations, and require the property IRI, e.g., i, to have AP(i) matched from a declaration.
This is not necessary for built-in properties, where the declaration is implicit.

Can you point out where the restriction to annotation axioms comes from?

**Comment by ignazio1977** [comment]
Kudos for being an OWLAPI 5 user, you're the first I know of outside the inner circle of contributors.

**Comment by JoyW3000** [comment]
Thank you.  We've been waiting for a updated version that uses sesame 4.  As to the issue with OWLProfileReport and declaration of annotation properties, I was following the suggestion from https://www.w3.org/TR/2012/REC-owl2-syntax-20121211/#Declaration_Consistency, which only covers the axioms.  But your point is definitely valid.  

However, the issue would become whether or not a null pointer exception should be thrown by OWLProfileViolation.getAxiom() or how it should be handled when taking ontology annotations into consideration.

**Comment by ignazio1977** [comment]
The null pointer issue is a bug, it was fixed a few days ago. I'll make a release including it soon, probably around the weekend.

**Comment by JoyW3000** [comment]
I appreciate it.  What branch has that fix?

**Comment by ignazio1977** [comment]
Both version4 and version5 have it

**Comment by ignazio1977** [comment]
https://github.com/owlcs/owlapi/issues/498 fixed in 5.0.1 (the release is currently being published to maven central)
