### ISSUE TITLE
Fixing punnings fails on dp subDataPropertyOf rdfs:label

### ISSUE THREAD

**Issue by wismill** [owlcs/owlapi#505]
(this is a clone from an [issue on Protégé](https://github.com/protegeproject/protege/issues/370): I do not know where is the relevant place).

I faced an error `org.semanticweb.owlapi.model.OWLRuntimeException: Not OWLDataProperty` using Protégé git master (402839a556d289901a30787ba5ffbb1cd8860193) but *not* with protégé 5.0.0-beta-23. There is an error windows opening but empty and the Turtle file (see below) is not loaded.

- OS: Windows 7 64 bits
- Java 8

File:
```
@prefix : <http://www.test.org/qudt#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix qudt: <http://qudt.org/schema/qudt#> .


<http://www.test.org/qudt>
  a owl:Ontology ;
  owl:imports <http://qudt.org/1.1/vocab/dimensionalunit> .

:hasQuantityKind
  a owl:ObjectProperty ;
  owl:propertyChainAxiom (
    qudt:quantityValue
    qudt:unit
    qudt:quantityKind
  ) .
```

Error message from the console:

```
An error was thrown: Not OWLDataProperty
org.semanticweb.owlapi.model.OWLRuntimeException: Not OWLDataProperty
        at uk.ac.manchester.cs.owl.owlapi.OWLAnnotationPropertyImpl.asOWLDataProperty(OWLAnnotationPropertyImpl.java:123) ~[na:na]
        at org.semanticweb.owlapi.util.OWLAnnotationPropertyTransformer.visit(OWLAnnotationPropertyTransformer.java:859) ~[na:na]
        at uk.ac.manchester.cs.owl.owlapi.OWLSubAnnotationPropertyOfAxiomImpl.accept(OWLSubAnnotationPropertyOfAxiomImpl.java:119) ~[na:na]
        at org.semanticweb.owlapi.util.OWLAnnotationPropertyTransformer.transformObject(OWLAnnotationPropertyTransformer.java:96) ~[na:na]
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.fixIllegalPunnings(OWLOntologyManagerImpl.java:1116) ~[na:na]

**Comment by ignazio1977** [comment]
This is due to an owlapi issue. There is an illegal punning in the ontology, due to missing declarations; but the repair code is failing to rebuild the axioms that were generated incorrectly.

**Comment by ignazio1977** [comment]
Whoops, not true: it's not a missing declaration, it's an actual illegal punning in one of the imported ontologies:

`http://www.linkedmodel.org/1.2/schema/vaem` has:

    <owl:DatatypeProperty rdf:about="http://www.linkedmodel.org/schema/vaem#name">
        <rdfs:comment rdf:datatype="http://www.w3.org/2001/XMLSchema#string">The property 'vaem:name' is intended for general use. In many cases 'rdfs:label' could be used give names to resources. In the case where compliance with a specific naming rule is needed, 'vaem:name' allows a resource to carry a name that is used in more specific contexts. Making 'vaem:name' a sub-property of 'rdfs:label' allows 'vaem:name' to serve in the same way as an 'rdfs:label'.</rdfs:comment>
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">name</rdfs:label>
        <rdfs:range rdf:resource="http://www.w3.org/2001/XMLSchema#string"/>
        <rdfs:subPropertyOf rdf:resource="http://www.w3.org/2000/01/rdf-schema#label"/>
    </owl:DatatypeProperty>

A workaround while I fix the bug would be to amend this illegal punning, if possible.
