### ISSUE TITLE
Incorrect classification of OWL individuals as SWRL variables in head built-ins

### ISSUE THREAD

**Issue by martinjoconnor** [owlcs/owlapi#506]
If I have a SWRL rule that uses an OWL individual as an argument to a SWRL head built-in that individual gets incorrectly classified as a SWRL variable.

For example, if I have and OWL ontology with class ```A``` and an individual ```a1``` with type ```A``` and the following rule

```
A(a1) -> sqwrl:select(a1) ∧ A(a1)
```

and run the following code

```
      OWLOntologyManager ontologyManager = OWLManager.createOWLOntologyManager();
      OWLOntology ontology = ontologyManager
        .loadOntologyFromOntologyDocument(OWLAPIExp.class.getResourceAsStream("/OWLAPIIssue506.owl"));

      for (SWRLRule swrlRule : ontology.getAxioms(AxiomType.SWRL_RULE, Imports.INCLUDED)) {
        for (SWRLAtom swrlAtom: swrlRule.getBody())
          System.out.println("Body SWRLAtom: " + swrlAtom);
        for (SWRLAtom swrlAtom: swrlRule.getHead())
          System.out.println("Head SWRLAtom: " + swrlAtom);
      }
```

I get

```
Body SWRLAtom: ClassAtom
(
<http://www.semanticweb.org/martin/ontologies/2016/2/untitled-ontology-805#A> 
<http://www.semanticweb.org/martin/ontologies/2016/2/untitled-ontology-805#a1>
)
Head SWRLAtom: BuiltInAtom
(
<http://sqwrl.stanford.edu/ontologies/built-ins/3.4/sqwrl.owl#select> 
Variable(<http://www.semanticweb.org/martin/ontologies/2016/2/untitled-ontology-805#a1>) 
)
Head SWRLAtom: ClassAtom
(
<http://www.semanticweb.org/martin/ontologies/2016/2/untitled-ontology-805#A> 
<http://www.semanticweb.org/martin/ontologies/2016/2/untitled-ontology-805#a1>
)
```

That is, the individual ```a1``` gets incorrectly classified as a SWRL variable if used in a SWRL built-in in the rule head. 

I am using version 4.2.1 of the OWLAPI. I enclose an ontology with the above example.

Thanks.
Martin

[OWLAPIIssue506.owl.txt](https://github.com/owlcs/owlapi/files/181164/OWLAPIIssue506.owl.txt)

**Comment by ignazio1977** [comment]
Sounds like a parsing issue. Thanks for the test.

**Comment by ignazio1977** [comment]
The API currently has, for SWRLBuiltin, an IRI and a List of SWRLDArgument - the problem being that SWRLDArgument only covers variables and literals.

I'm not enough of a SWRL expert to know whether this means only literals and variables are allowed for builtin arguments, or whether SWRLIndividuals should also be allowed and the API is forbidding that.

**Comment by ignazio1977** [comment]
From https://www.w3.org/Submission/SWRL/#owls_dObject, I think the API is correct and the issue here is that an individual is not allowed in that position in the rule.

**Comment by martinjoconnor** [comment]
You are correct. This is not a bug.

I forgot that I am doing some special handling in several places in my code do work around this part of the specification. I want to allow IRIs representing OWL entities to be accepted a built-in parameters because it allows me to support quite a few features in the SQWRL query language (such as counting numbers of entities, for example). 

Thanks.
Martin
