### ISSUE TITLE
how to check if a statement if a valid OWL axiom 

### ISSUE THREAD

**Issue by mahaalfate7** [owlcs/owlapi#507]
Hi, 

Is there a way to parse and check if the pattern written in Manchester format for example:

?X subclassOf:  attaches-to some ?Y

is valid, so that it can be converted to an OWL axiom ?

Thanks a lot

**Comment by ignazio1977** [comment]
The interface you need to use for this is `ManchesterOWLSyntaxParser`. It has a method called `parseAxiom()` that will parse inline axioms.

An example of how this is currently used:

   OWLEntityChecker entityChecker = new ShortFormEntityChecker(new SimpleShortFormProvider()); 
   ManchesterOWLSyntaxParser parser = OWLManager.createManchesterParser();
    parser.setOWLEntityChecker(entityChecker);
    parser.setStringToParse(input);
    OWLAxiom axiom=parser.parseAxiom();

Note: In order for an axiom to be parsed, it is necessary for the entities found in the axiom to be resolvable by the `OWLEntityChecker` passed to the parser; in your case, this means that you need to provide an `OWLEntityChecker` implementation that, given `X` as input, can tell `X` is an OWLClass.

Also, the entity checker must be able to resolve `attaches-to` - the standard checkers use the ontologies available to a manager to do so:

    OWLEntityChecker entityChecker = new ShortFormEntityChecker(
        new BidirectionalShortFormProviderAdapter(
            manager, ontology.getImportsClosure(),new SimpleShortFormProvider()));

What I would do in your case is create a new `OWLEntityChecker` which has the `entityChecker` above as a delegate checker, and for each call received tests whether the delegate can resolve it. When the delegate cannot resolve it, the main checker would test for patterns like `?X` and `?Y`, and resolve them according to your own application needs. 

This will basically extend the Manchester parser by enabling handling of non-IRI entities; however, I don't know how the question mark will be handled - you might need to replace those with other characters, or make up a prefix; something like a simple string replacement:

    variable:X subclassOf: attaches-to some variable:Y

**Comment by mahaalfate7** [comment]
Thanks a lot for your detailed answer, I really appreciate it. As you said most examples I found
parse whole ontology. 
I couldn't actually create a parser by 
 ManchesterOWLSyntaxParser parser = OWLManager.createManchesterParser();

I tried to use a manager object but didn't work. 
I appreciate your response please!

**Comment by ignazio1977** [comment]
What error did you get?

**Comment by mahaalfate7** [comment]
Error:(22, 54) java: cannot find symbol
  symbol:   method createManchesterParser()
  location: class org.semanticweb.owlapi.apibinding.OWLManager

**Comment by ignazio1977** [comment]
Which version of OWLAPI are you using? These suggestions apply to OWLAPI 4 and 5.

The method was introduced in OWLAPI 4. If you're using OWLAPI 3, you need to create a new `ManchesterOWLSyntaxEditorParser` object instead.

**Comment by mahaalfate7** [comment]
Thanks for a lot for that. I converted to using OWLAPI 4. and now when I tried to input the Machester
	```
Data property namesyntax such as:  input = "Arm subClassOf (hasPart some Finger)"
        ManchesterOWLSyntaxParser parser = OWLManager.createManchesterParser();
        parser.setOWLEntityChecker(entityChecker);
        parser.setStringToParse(input);
        OWLAxiom axiom = parser.parseAxiom();
        System.out.println(axiom.toString());
```

 I get exception:
```
Exception in thread "main" org.semanticweb.owlapi.manchestersyntax.renderer.ParserException: Encountered Arm at line 1 column 1. Expected one of:
	Class name
	Object property name
	Data property name

```

**Comment by csnyulas** [comment]
Shouldn't there be a prefix manager set, that would provide the namespace for the default prefix. Otherwise "Arm" can't be resolved to an IRI.

**Comment by ignazio1977** [comment]
Yes that's the problem - the entity checker needs to know about `Arm` and other classes used in the axiom, or the parser will fail.

**Comment by monaalsh** [comment]
@csnyulas @ignazio1977 
I have tried that too, as the following, but didn't work;
               ```
 String input = "Prefix: pr: <www.somewhere.net/>\n" +
                "pr:Arm subClassOf (pr:hasPart some pr:Finger)";
                ManchesterOWLSyntaxParser parser = OWLManager.createManchesterParser();
                parser.setOWLEntityChecker(entityChecker);
                parser.setStringToParse(input);
                OWLAxiom axiom = parser.parseAxiom();

```

I have used the following way by using OWLAPI 3 and it worked
http://stackoverflow.com/questions/21005908/convert-string-in-manchester-syntax-to-owlaxiom-object-using-owlapi-3-in-java

But is there a way to check if a String of the following simple Arm subClassOf (hasPart some Finger) form is written in Manchester Syntax or not, without having to append it with keywords such as 
Class, ObjectProperty and such. If no there is no way, then I just create a simple parser 
to parse this simple form and append all the needed info and use the method mentioned in the StackOverflow link.

However, I prefer the way @ignazio1977  suggested using OWLAPI 4, but I don't know how to make it, 
I appreciate your reply.

**Comment by mahaalfate7** [comment]
@csnyulas @ignazio1977
I have tried that too, as the following, but didn't work;

```

 String input = "Prefix: pr: <www.somewhere.net/>\n" +
                "pr:Arm subClassOf (pr:hasPart some pr:Finger)";
                ManchesterOWLSyntaxParser parser = OWLManager.createManchesterParser();
                parser.setOWLEntityChecker(entityChecker);
                parser.setStringToParse(input);
                OWLAxiom axiom = parser.parseAxiom();
```


I have used the following way by using OWLAPI 3 and it worked
http://stackoverflow.com/questions/21005908/convert-string-in-manchester-syntax-to-owlaxiom-object-using-owlapi-3-in-java

But is there a way to check if a String of the following simple Arm subClassOf (hasPart some Finger) form is written in Manchester Syntax or not, without having to append it with keywords such as
Class, ObjectProperty and such. If no there is no way, then I just create a simple parser
to parse this simple form and append all the needed info and use the method mentioned in the StackOverflow link.

However, I prefer the way @ignazio1977 suggested using OWLAPI 4, but I don't know how to make it,
I appreciate your reply.

**Comment by ignazio1977** [comment]
That's not what I meant - prefixes in the string will only be interpreted when parsing it as a whole ontology.

The code I had in mind looks like this:

    static class Provider extends CachingBidirectionalShortFormProvider {

        private SimpleShortFormProvider provider = new SimpleShortFormProvider();

        @Override
        protected String generateShortForm(OWLEntity entity) {
            return provider.getShortForm(entity);
        }
    }

    public static void main(String[] args) throws OWLOntologyCreationException, OWLOntologyStorageException {
        OWLDataFactory df = OWLManager.getOWLDataFactory();
        Provider shortFormProvider = new Provider();
        OWLEntityChecker entityChecker = new ShortFormEntityChecker(shortFormProvider);
        shortFormProvider.add(df.getOWLClass(IRI.create("http://example.org/Arm")));
        shortFormProvider.add(df.getOWLClass(IRI.create("http://example.org/Finger")));
        shortFormProvider.add(df.getOWLObjectProperty(IRI.create("http://example.org/hasPart")));
        String input = "Arm subClassOf (hasPart some Finger)";
        ManchesterOWLSyntaxParser parser = OWLManager.createManchesterParser();
        parser.setOWLEntityChecker(entityChecker);
        parser.setStringToParse(input);
        OWLAxiom axiom = parser.parseAxiom();
        System.out.println("CheckManchesterSyntax.main() " + axiom);
    }


However, it is more useful, in my experience, to parse axioms against a known ontology, to avoid having to set up a lot of entities this way:

        OWLOntologyManager manager=OWLManager.createOWLOntologyManager();
        OWLOntology rootOntology=manager.createOntology();

This is the basic ontology, containing all the entities and axioms you already know about.

        Set<OWLOntology> importsClosure = rootOntology.getImportsClosure();
        // Create a bidirectional short form provider to do the actual mapping.
        // It will generate names using the input
        // short form provider.
        OWLEntityChecker entityChecker = new ShortFormEntityChecker(
            new BidirectionalShortFormProviderAdapter(manager, importsClosure, 
                new SimpleShortFormProvider()));
        ManchesterOWLSyntaxParser parser = OWLManager.createManchesterParser();
        parser.setDefaultOntology(rootOntology);
        parser.setOWLEntityChecker(entityChecker);
        parser.setStringToParse("Arm subClassOf (hasPart some Finger)");
        OWLAxiom axiom = parser.parseAxiom();
        System.out.println("CheckManchesterSyntax.main() " + axiom);
