### ISSUE TITLE
OWL 2 Full Profile

### ISSUE THREAD

**Issue by Brian-McG** [owlcs/owlapi#508]
With regards to [_OWL2Profile.java_](https://github.com/owlcs/owlapi/blob/version4/api/src/main/java/org/semanticweb/owlapi/profiles/OWL2Profile.java), if an ontology passes this profile check, can it be considered in OWL 2 Full?

The class comment mentions the following:
 ```Checks to see if an ontology and its imports closure fall into the OWL 2 DL profile. An ontology is OWL Full if any of the global structural restrictions are violated, if there is punning between object and data properties```

However the IRI returned is the IRI for OWL 2 Full and the name returned does not mention a profile.

I am using v4 of the API

**Comment by ignazio1977** [comment]
Looks like the javadoc is a copy and paste from OWL 2 DL profiles. The checks in OWL2Profile are only the basic ones for a valid OWL ontology (e.g., the IRI must be absolute), so failing this profile means the ontology is not a valid OWL ontology, rather than an OWL Full ontology.

**Comment by Brian-McG** [comment]
Based on your changes could getName rather return "OWL 2 Full"?

**Comment by ignazio1977** [comment]
Indeed
