### ISSUE TITLE
Loading ontology with unescaped HTML results in empty ontology

### ISSUE THREAD

**Issue by jvendetti** [owlcs/owlapi#510]
I'm working on the [BioPortal](http://bioportal.bioontology.org/) project and someone recently submitted an OWL ontology that contained unescaped HTML.  We're currently using 4.2.1, which successfully parsed the file, but the resulting ontology object was empty (axiom count 0).  I noticed a comment regarding [empty ontologies](/owlcs/owlapi/issues/496#issuecomment-192761168) in issue #496.  

This is a [small test ontology](https://github.com/owlcs/owlapi/files/196782/testanchor2.owl.zip) to reproduce the issue, the pertinent section being:
```
<owl:Class rdf:about="http://ontologies.owl/A">
  <rdfs:comment rdf:datatype="http://www.w3.org/2001/XMLSchema#string">See more at <a href="http://abc.com">abc</a></rdfs:comment>
</owl:Class>.
```
This code snippet using lax parsing will produce the empty ontology:
```
File file = new File("testanchor2.owl");
OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
OWLOntology ontology = manager.loadOntology(IRI.create(file));
```
Using non-lax parsing and specification of a document format will give parsing errors that point out the syntax issue:
```
FileDocumentSource fileDocumentSource = new FileDocumentSource(new File("testanchor2.owl"), new RDFXMLDocumentFormat());
OWLOntologyLoaderConfiguration configuration = new OWLOntologyLoaderConfiguration(); 
configuration.setStrict(true);
OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
OWLOntology ontology = manager.loadOntologyFromOntologyDocument(fileDocumentSource, configuration);
```
Partial stack trace from code directly above:
```
org.semanticweb.owlapi.io.UnparsableOntologyException: Problem parsing file:/Users/jvendetti/Development/IntelliJ_Projects/owlapi-example-code/src/test/resources/testanchor2.owl
Could not parse ontology.  Either a suitable parser could not be found, or parsing failed.  See parser logs below for explanation.
The following parsers were tried:
1) org.semanticweb.owlapi.rdf.rdfxml.parser.RDFXMLParser@6337c201

Detailed logs:
--------------------------------------------------------------------------------
Parser: org.semanticweb.owlapi.rdf.rdfxml.parser.RDFXMLParser@6337c201
    Stack trace:
org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParserException: [line=27:column=115] Text was seen and new node is started.        
org.semanticweb.owlapi.rdf.rdfxml.parser.RDFXMLParser.parse(RDFXMLParser.java:76)
uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:193)
uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.actualParse(OWLOntologyManagerImpl.java:1061)
uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1017)
uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:973)
edu.stanford.ncbo.bioportal.EmbeddedHTMLTest.load_EmbeddedHTMLWithNonLaxParsing_ExceptionThrown(EmbeddedHTMLTest.java:39)
```
The results are the same with versions 4.2.3 and 5.0.1.

I understand that the ontology file submitted to us is incorrect because the HTML should be properly escaped.  However, I wasn't expecting to get an empty ontology using the lax parsing method.

**Comment by ignazio1977** [comment]
The difference in behaviour is not due to the strict parsing but to specifying the desired format in the document source constructor.

Attempting to set strict parsing as shown will not work: the config object with updated flag is not used. Should have been:

    OWLOntologyLoaderConfiguration configuration = new OWLOntologyLoaderConfiguration().setStrict(true);

**Comment by ignazio1977** [comment]
The fact that the parsing is different in the two cases is because in the first case one of the parsers is not throwing exceptions, although it is also not parsing anything. I'll try to pinpoint which one it is.

**Comment by ignazio1977** [comment]
The guilty party seems to be TriX, from the RIO parsers.

**Comment by ignazio1977** [comment]
I'm not sure how reliable a fix to this will be - as a workaround, is there any known set of formats that the submitters are expected to use? You could throw an exception if the detected format does not match the expected one(s)

**Comment by sesuncedu** [comment]
Thinking about this:

1. There is only a certain amount of recovery that is possible in this
situation (embedded raw *ml).

2. If the contents of the literal happen to contain an unbalanced close tag
that is the same as the one closing that would mark the end of the
literal,  the results are unpredictable, and the error location is lost.

3. It would seem plausible that an exception is being thrown, but is being
caught too early (the ontology object is still live after the parse.

4. It does not seem unreasonable for lax mode to abort when parsing bad
RDF/XML (what happens with RIO?

5. Was the original file generated by some owlapi version?

**Comment by ignazio1977** [comment]
1. and 2. indeed

3. This could be happening in the RIO parsers but it's hard to tell.

4a. The lax mode is indeed aborting (the parsing with RDF/XML only fails, and the strict mode is not getting set).

4b. RIO behaviour is less well known. In at least the TriX case, it's not spitting exceptions on bad input.

5. The test ontology provided by Jennifer has `<!-- Generated by the OWL API (version 4.2.1.20160306-0033) https://github.com/owlcs/owlapi -->`, so it looks generated by the OWL API. Not sure if there is/should be any validation on the content of string literals.

**Comment by sesuncedu** [comment]
Looks like the rio trix parser completely ignores any unrecognized tags.

Does trix need to be enabled by default?

**Comment by sesuncedu** [comment]
> Looks like the rio trix parser completely ignores any unrecognized tags.

NB I only looked at code for 2.8, but I don't think this is a hotbed of
active development...

**Comment by ignazio1977** [comment]
It can be disabled but it requires surgery on the distribution jar, to remove the corresponding entry from the services file.

**Comment by jvendetti** [comment]
The test ontology was generated with Protege 5.0.0 beta, build 24 (which uses OWL API 4.2.1.20160306-0033 as you mentioned above).

In terms of the ontology that was submitted to BioPortal, I asked the authors how they generated it, but I haven't gotten a response.  It definitely wasn't Protege, as the OWL file didn't contain the typical comment at the bottom indicating the OWL API version used to generate.

**Comment by ignazio1977** [comment]
I think there are two things to implement here:

- Test that string literals containing tags are written and read back correctly; adjust if not
- Add a mechanism to exclude available parsers, to work around issues like this one; I think it can be a property containing the parser names to skip.

**Comment by ignazio1977** [comment]
When creating a literal like this:

        String in = "See more at <a href=\"http://abc.com\">abc</a>";
        OWLAnnotationAssertionAxiom ax = df.getOWLAnnotationAssertionAxiom(df.getRDFSComment(), createIndividual().getIRI(), df.getOWLLiteral(in));

OWLAPI 4.2.3 creates the following XML:

    <?xml version="1.0"?>
    <rdf:RDF xmlns="http://www.semanticweb.org/owlapi/test/urn:test#"
     xml:base="http://www.semanticweb.org/owlapi/test/urn:test"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:owl="http://www.w3.org/2002/07/owl#"
     xmlns:xml="http://www.w3.org/XML/1998/namespace"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">
    <owl:Ontology rdf:about="http://www.semanticweb.org/owlapi/test/urn:test"/>
    <rdf:Description rdf:about="urn:tests#uri1">
        <rdfs:comment rdf:datatype="http://www.w3.org/2001/XMLSchema#string">See more at &lt;a href=&quot;http://abc.com&quot;&gt;abc&lt;/a&gt;</rdfs:comment>
    </rdf:Description>
    </rdf:RDF>

which is parsed correctly and parses back the same literal.

I'll try this in 4.2.1.

**Comment by ignazio1977** [comment]
4.2.1 appears to work the same. I've tried generating the literal from Protege beta 23 and beta 24 and I got the same result.

Jennifer, can you confirm how you replicated this through Protege?
I pasted the following string in an rdfs:comment on an individual:

    See more at <a href="http://abc.com">abc</a>

The saved ontology was:

    <?xml version="1.0"?>
    <rdf:RDF xmlns="http://www.semanticweb.org/ontologies/2016/3/untitled-ontology-186#"
     xml:base="http://www.semanticweb.org/ontologies/2016/3/untitled-ontology-186"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:owl="http://www.w3.org/2002/07/owl#"
     xmlns:xml="http://www.w3.org/XML/1998/namespace"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">
    <owl:Ontology rdf:about="http://www.semanticweb.org/ontologies/2016/3/untitled-ontology-186"/>
    <owl:Thing rdf:about="http://www.semanticweb.org/ontologies/2016/3/untitled-ontology-186#Test">
        <rdf:type rdf:resource="http://www.w3.org/2002/07/owl#NamedIndividual"/>
        <rdfs:comment>See more at &lt;a href=&quot;http://abc.com&quot;&gt;abc&lt;/a&gt;</rdfs:comment>
    </owl:Thing>
    </rdf:RDF>

**Comment by ignazio1977** [comment]
The latest commit has added a property to disable one or more parsers:

    String name = "org.semanticweb.owlapi.rio.RioTrixParserFactory org.semanticweb.owlapi.rio.RioRDFaParserFactory";
    OWLOntologyLoaderConfiguration config = manager.getOntologyLoaderConfiguration().setBannedParsers(name);

This can be set like the other properties, via an entry in a config file or via a system property:

    System.setProperty(
        "org.semanticweb.owlapi.model.parameters.ConfigurationOptions.BANNED_PARSERS", 
        "org.semanticweb.owlapi.rio.RioTrixParserFactory org.semanticweb.owlapi.rio.RioRDFaParserFactory");


(Or any equivalent way of setting up the property, like command line options)

**Comment by jvendetti** [comment]
Apologies @ignazio1977 - I looked back through my notes and realized the comment I left about how the test ontology was generated wasn't accurate.  The ontology was first generated with Protege 5.0.0 beta build 24, but then the rdfs:comment tag was hand-edited to include the unescaped HTML anchor tag.

**Comment by ignazio1977** [comment]
No worries. I'm guessing that there isn't anything else we can do on this topic then.
