### ISSUE TITLE
Add a link to old documentation

### ISSUE THREAD

**Issue by phillord** [owlcs/owlapi#515]
It would be nice to link to the OWL API 3 java doc from the documentation page.

I'm porting!

**Comment by ignazio1977** [comment]
There's one at http://owlcs.github.io/owlapi/
the link is http://owlcs.github.io/owlapi/apidocs_3_5_4/index.html

I've had a look at the documentation page and I'm not sure where to add these links :-) it's a wiki, so feel free to edit and add.
