### ISSUE TITLE
propertyChainAxiom restriction - at least two properties?

### ISSUE THREAD

**Issue by chile12** [owlcs/owlapi#518]
I have an issue with the propertyChainAxiom and owlapi.

"Not enough property expressions; at least two needed"

I don't think OWL restricts the number of members in the property list to two, yet owlapi does.
And yes there are good reasons to list only one property in there :).

**Comment by ignazio1977** [comment]
The specs show two or more expressions, same as equivalent classes/properties expressions: see owl2-syntax, section 9.2.1. Looks like with only one property you're meant to use a sub property axiom.

I'm curious though: can you show an example, and what's the reason for having just the one property?

**Comment by chile12** [comment]
OP some transitive property
PC1 subPropertyOf OP 
PC2 subPropertyOf OP

a PC1 b PC2 c  PC2 d => a OP b, a OP c, a OP d, b OP c, b OP d, c OP d

If property chains 1 & 2 are only containing one property i am spared to define all possible combinations of two following properties in my property hierarchy.

But i guess i was just too lazy.

**Comment by csnyulas** [comment]
Applying Ignazio's comment to your example:
If you got 
`PC1 subPropertyOf OP`
and
`a PC1 b`
then the reasoner would infer that
`a OP b`
No need to declare any property chains.

**Comment by csnyulas** [comment]
Also, in addition to what I said before that 
```
PC1 subPropertyOf OP
a PC1 b
```
entails `a OP b`, if you add
```
PC2 subPropertyOf OP
OP some transitive property
```
a reasoner 
- from `b PC2 c` would infer `b OP c`
- from `a PC1 b PC2 c` would infer `a OP b OP c` and `a OP c`
- from `b PC2 c PC2 d` would infer `b OP c OP d` and `b OP d`
- from `a PC1 b PC2 c PC2 d` would infer `a OP b OP c OP d` and `a OP d`

So you would not have to specify anything more than the 3 axioms that you already have about your properties to have everything that you need entailed.

**Comment by chile12** [comment]
@csnyulas all of this is very obvious

but since PC1 & 2 are property chains i would need to group always two properties together to make up PC1 or PC2. This was my case.

**Comment by csnyulas** [comment]
Sorry, I don't understand "PC1 & 2 are property chains". Neither can I comprehend what you meaan by "to make up PC1 or PC2". Can you give us a concrete example? Maybe using real property names, so that we can get the intuition.

**Comment by chile12** [comment]
Ok:
lets assume there are 3 existing properties (x,y,z) and a Class A.
Lets define them:

x := AxA
y := AyA
z := AzA

Now i want to define a property-chain p with an arbitrary length :
p := trans(ApA)
(used to span paths, where x and z appear at least once and where x has to be used first and z last)

To do this i want to define sub properties used like chain links, which when used transitively make up the actual chain of properties.

If property chains could have just one member, all i needed to do is (pc is property chain):
Note: we can not make x,y,z sub properties of p

subP1 := subProp(pc(x), p), 
subP2 := subProp(pc(y), p), 
subP3 := subProp(pc(z), p), 

Otherwise:

subP0 := subProp(pc(x,z), p), 
subP1 := subProp(pc(x,y), p), 
subP2 := subProp(pc(x,x), p), 
subP2 := subProp(pc(y,y), p), 
subP2 := subProp(pc(z,z), p), 
subP3 := subProp(pc(y,z), p), 
subP4 := subProp(pc(x,y,z), p), 
subP5 := subProp(pc(x,y,y), p), 
subP6 := subProp(pc(y,y,z), p), 
subP7 := subProp(pc(x,x,y), p), 
subP8 := subProp(pc(y,z,z), p), 


Example: assume we have a path like this x/x/x/x/y/y/z
first approach: -> (x)(x)(x)(x)(y)(y)(z)
second approach: -> (xx)(xx)(yyz) 

So by the existence of path fragments like xx,xx,yyz we can infer subP2 and subP6, since we can sequence the whole path with sub-properties of p, we conclude that x/x/x/x/y/y/z is in fact an instance of p.

**Comment by csnyulas** [comment]
Sorry @chile12 but I don't understand your example, since I am not familiar with the notation you use. Hopefully someone understands it and maybe they will be able to help you. I would have had a better chance to understand your problem if you would have used real property names. Alternatively you could share with us a sample ontology that we can look at.

Although the issue is closed, meaning that there is nothing that needs to be done on the OWLAPI side, apparently you still have a use case where you think the expressivity of the OWL language (and OWL API) are not enough to model efficiently what you need. That's why I think it is still interesting to explore this issue further. However, ultimately it is your call whether you want to drop it, or not.

**Comment by csnyulas** [comment]
Thinking more about your example, and in case I understand correctly what you are trying to do, I may have a simple solution.

The easiest solution would be to declare `x`, `y` and `z` transitive and declare (using Manchester syntax) `x o y o z SubPropertyOf p`.

If x, y and z cannot be made transitive, you could create `xChain` a transitive superproperty of `x`, `yChain` a transitive superproperty of `y`, and `zChain` a transitive superproperty of `z`, and  declare `xChain o yChain o zChain SubPropertyOf p`

This would make any of the following property chains:
 ```
x o y o z
x o x o y o z
x o y o y o z
x o y o z o z
x o x o y o y o z
x o y o y o z o z
x o x o y o y o z o z
x o ... o x o y o z
x o y o ... o y o z
x o y o z o ... o z
x o ... o x o y o ... o y o z
x o ... o x o y o z o ... o z
x o y o ... o y o z o ... o z
x o ... o x o y o ... o y o z o ... o z
```   
subproperty of `p`

If the presence of `y` is optional in the chain (and relying on the fact that you already stated that `x` needs to be at the beginning and `z` at the end of the chain), you can add the following declaration `xChain o zChain SubPropertyOf p` to cover all your cases.

**Comment by chile12** [comment]
I think now we are not longer talking about different thing here :)

What you wrote is absolutely correct and has also crossed my mind.
Unfortunately i can not change x,y and z, since they stem from foreign ontologies.
If i build transitive sub-properties like you suggested, i run into the problem with inferencing.

While i can infer subP6 (see my last example) from the existence of  (y o y o z) i can not infer (yChain o yChain o zChain) from it.

In fact, all sub-properties i created will never be instantiated but only inferred by the existence of paths like (y o y o y) in my graph. 

And this is the crux of my problem, also i may had trouble describing it.
This is why i was looking for describing chains with only one member.

Thanks for the continued interest in my problem.

regards

**Comment by csnyulas** [comment]
I still do not understand your notation, and how you are trying to solve the problem with subP1, subP2, etc., so sorry if I don't understand your last comment either. However, I was able to understand, I think, what you try to achieve overall: to create a property chain that matches a series of properties involving any number of `x` followed by any number of `y` followed by any number of `z`. My solution can do this, even if you have no control over `x`, `y` and `z` as they are coming from a different ontology. You can still add axioms in **your** ontology, which imports the original ontology containing these properties. The key is that you need to create **superproperties** of `x`, `y` and `z` (not subproperties!), and make those superproperties **transitive**. Then write your chain using the new superproperties.
