### ISSUE TITLE
Can't load Ontology

### ISSUE THREAD

**Issue by CCCynthia** [owlcs/owlapi#519]
I just start to learn Reasoner and have a simple question. I wanna try the DLquery program with my own ontology. should I transfer my ontology also in String and how? (I have created by Protege) Or can I load my local file? By updating to some website and get a link like http://protege.stanford.edu/ontologies/pizza/pizza.owl ?

**Comment by ignazio1977** [comment]
You can replace the string document source with a File or an IRI to load the ontology from a local or remote file.

**Comment by CCCynthia** [comment]
i have replace it with 
`private final static String koala = "http://www.semanticweb.org/linjian/ontologies/2016/3/untitled-ontology-17.owl";`

but it doesn't work.
here is the error
**Parser: ManchesterOWLSyntaxOntologyParser
Encountered 'http://www.semanticweb.org/linjian/ontologies/2016/3/untitled-ontology-17' at line 1 column 1.  Expected either 'Ontology:' or 'Prefix:' (Line 1)**

**Comment by ignazio1977** [comment]
The string is wrapped as a StringDocumentSource. You are using an IRI so replace the StringDocumentSource with IRI.create(your string here)

**Comment by CCCynthia** [comment]
As you said, I change it with IRI and I load with my IRI
`private final static IRI koala = IRI.create("http://www.semanticweb.org/linjian/ontologies/2016/3/untitled-ontology-17.owl");`
but it shows **Could not load ontology: http://semanticweb.org/linjian/ontologies/2016/3/untitled-ontology-17.owl**
I've also tried with the example **pizza.owl** and it worked.
Do you have any idea of what's wrong with my IRI? I copy it directly from Protege.

Thank you for your patience!

**Comment by ignazio1977** [comment]
The IRI must be accessible online. If you have it only as a local file just use new File instead

**Comment by CCCynthia** [comment]
Now i tried to load my local file, but i still have a problem.
`private final static URI koala = URI.create("file:///C:/Users/Lin Jian/Dropbox/Modell.owl");
  
    public static void main(String[] args) {
        try {
            OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
            OWLOntology ontology = manager.loadOntologyFromPhysicalURI(koala);`
There is error with** loadOntologyFromPhysicalURI**, it says **The method loadOntologyFromPhysicalURI(URI) is undefined for the type OWLOntologyManager**
What should I do? I thought it's included in OWLOntologyManager

**Comment by CCCynthia** [comment]
I've loaded my owl file! Thank u!
