### ISSUE TITLE
DLquery not work

### ISSUE THREAD

**Issue by CCCynthia** [owlcs/owlapi#521]
I want to do the query exactly like it in Protege. For example, I haved loaded the example pizza.owl, when execute "hasCountryOfOrigin value America", the result in Protege is two subclasses: "American" and "AmericanHot". But in the program, the result is none.
Why is it?

**Comment by ignazio1977** [comment]
Are you using a reasoner?

Which class IRIs are being parsed? It's important that the namespaces match.

**Comment by CCCynthia** [comment]
I tried with HermiT and now it works. Thanks!
