### ISSUE TITLE
Default prefix overrides explicit prefixes

### ISSUE THREAD

**Issue by danielepantaleone** [owlcs/owlapi#522]
I'm experiencing some issues when serializing OWL ontologies in Functional Style Syntax. Whenever I use the `FunctionalSyntaxDocumentFormat` the default prefix `:` is generated even though I didn't specify it, and it is used in place of the one I specify instead. I added a verifiable example [here](https://github.com/protegeproject/protege/issues/375#issuecomment-217516054). This problem does not happen when using `ManchesterSyntaxDocumentFormat` or `TurtleDocumentFormat`.

I traced the problem till [here](https://github.com/owlcs/owlapi/blob/a47928d545ef9bca510fb0cb0c29c3a4983982cc/parsers/src/main/java/org/semanticweb/owlapi/functional/renderer/FunctionalSyntaxObjectRenderer.java#L75) where the `FunctionalSyntaxObjectRenderer` automatically generates the default prefix if the ontology is not anonymous (i.e. an IRI has been specified).

**Comment by ignazio1977** [comment]
The problem is that the default prefix is allowed to override manually set prefixes in the reverse mapping. 

I've changed this and get this output now:

    Prefix(:=<http://www.dis.uniroma1.it/example/>)
    Prefix(owl:=<http://www.w3.org/2002/07/owl#>)
    Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>)
    Prefix(xml:=<http://www.w3.org/XML/1998/namespace>)
    Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>)
    Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>)
    Prefix(example:=<http://www.dis.uniroma1.it/example/>)
    Ontology(<http://www.dis.uniroma1.it/example/>
    Declaration(Class(example:pizza))
    )

**Comment by danielepantaleone** [comment]
Thanks you very much for solving this problem!
