### ISSUE TITLE
How to put query results into array?

### ISSUE THREAD

**Issue by CCCynthia** [owlcs/owlapi#524]
Maybe it's a silly question. I use the DLquery with HermiT and want to put the results separately into a String array, 
for example   string result[]="Indivual1,Indivual2,individual3"
but I don't know how to separate the string.
Can you maybe give me a small example?
Thank you so much!

**Comment by ignazio1977** [comment]
Can you give a bit more context? In what structure are the results currently kept?

All Collection classes have a toArray() method.
Out of curiosity, why an array? In most cases, a list or a set would do the same job and are easier to use.

**Comment by CCCynthia** [comment]
I just wanna take out the results as string separately, no matter in an array or in a list.

`public void askQuery(String classExpression) {
        if (classExpression.length() == 0) {
            System.out.println("No class expression specified");
        } else {
            try {
                StringBuilder sb = new StringBuilder();
                sb.append("\\nQUERY:   ").append(classExpression).append("\\n\\n");
                Set<OWLNamedIndividual> individuals = dlQueryEngine.getInstances(
                        classExpression, true);
                printEntities("Instances", individuals, sb);
                System.out.println(sb.toString());
            } catch (ParserException e) {
                System.out.println(e.getMessage());
            }
            }
        }

    private void printEntities(String name, Set<? extends OWLEntity> entities,
            StringBuilder sb) {
        sb.append(name);
        int length = 50 - name.length();
        for (int i = 0; i < length; i++) {
            sb.append(".");
        }
        sb.append("\\n\\n");
        if (!entities.isEmpty()) {
            for (OWLEntity entity : entities) {
                sb.append("\\t").append(shortFormProvider.getShortForm(entity))
                        .append("\\n");
            }
        } else {
            sb.append("\\t[NONE]\\n");
            }
        sb.append("\\n");
        }
    }`

Are the query results kept in "entity"? I don't fully understand "shortFormProvider.getShortForm(entity)"

sorry about the silly question. It's my first java program

**Comment by ignazio1977** [comment]
Yes, `entities` contains the query results.

You can ignore the use of shortFormProvider in this method, it is only used to reduce the length of the string in output.

**Comment by CCCynthia** [comment]
In which form is "entities"? Is it an array?

**Comment by ignazio1977** [comment]
It's a Set, i.e., a Collection that can be iterated on, same as an array. It guarantees no duplicate values.

**Comment by CCCynthia** [comment]
Thanks, I have got the results in a List.
Now there is some thing strange with mu program.
I wrote those in my main function:
```
            String GFtoTF = "Teilfunktion and erfordert value ";
        	String[] ArrGFName = new String[2];
        	ArrGFName[1]="GF1_Eingabestation_Anwesenheit_pruefen";
        	String cEGFtoTF = GFtoTF + ArrGFName[1];
            dlQueryPrinter.askQuery(cEGFtoTF.trim()); 

        	
            String TFtoGF = "Grundfunktion and erfordert_bei value ";
        	String[] ArrTFBName = new String[2];
        	ArrTFBName[1]="TF1_Werkstueck_zum_Foerderband_transportieren";
        	String cETFtoGF = TFtoGF + ArrTFBName[1];
            dlQueryPrinter.askQuery(cETFtoGF.trim()); 
```
but the result is 
Grundfunktion and geloest_bei value K1_Anwesenheitssensor_Ein

[GF1_Eingabestation_Anwesenheit_pruefen]

Teilsystem and verhaltet_inaktiv_durch value 1_Werkstueck_kann_nicht_vor_den_Foerderkorb_liefern

org.semanticweb.owlapi.expression.ParserException: Encountered 1_Werkstueck_kann_nicht_vor_den_Foerderkorb_liefern at line 1 column 46. Expected one of:
	Individual name

That means the first query succeed, but the second not. I've already tried them in Protege and both work.
Why does that happen?
