### ISSUE TITLE
Turtle Renderer doesn't escape periods

### ISSUE THREAD

**Issue by matthewhorridge** [owlcs/owlapi#525]
Generate an ontology with an entity whose IRI has periods e.g.

```
http://www.semanticweb.org/ontology#A...
```

If the empty prefix is 

```
http://www.semanticweb.org/ontology#
``` 

then the IRI is serialised as 

```
A...
``` 

which is invalid turtle.

**Comment by ignazio1977** [comment]
/giggle

Do you know what's the escape sequence for periods?

**Comment by ignazio1977** [comment]
Looks like it's just \.
https://www.w3.org/TR/turtle/#sec-escapes

**Comment by ansell** [comment]
Technically, only the last period is illegal, they can occur unescaped anywhere in the middle (can't be the start).

**Comment by matthewhorridge** [comment]
Should this be closed now then?
