### ISSUE TITLE
Log Error Message for Punning could be more helpful

### ISSUE THREAD

**Issue by matthewhorridge** [owlcs/owlapi#531]
The OWL API prints out an error message if there is illegal punning....

> ERROR: Illegal redeclaration of entities : reuse of entity is punning not allowed 

It would be more useful to end users if the message included the entities that are the source of the problem.

**Comment by ignazio1977** [comment]
In which version is the logging not showing the entities?

The code looks like this:

    LOGGER.error("Illegal redeclarations of entities: reuse of entity {} in punning not allowed {}", e
                    .getKey(), e.getValue());

So it should already include the punned entities.

**Comment by matthewhorridge** [comment]
4.2.5 I believe.

**Comment by sesuncedu** [comment]
Hmm...

Matthew's message says "reuse of entity **is** punning", but the code
snippet Ignazio shows says "reuse of entity {} **in** punning".

**Comment by sesuncedu** [comment]
Also, is 4.2.5 tagged,  and what is the magic maven invocation to change all the poms to version 4.2.6-SNAPSHOT?

**Comment by ignazio1977** [comment]
Indeed, I noticed the difference in spelling and searched for "Illegal redeclaration". There are only two occurrences in version4 and version5, no traces in version3. I assumed it was a typing error.

**Comment by ignazio1977** [comment]
4.2.5 is tagged, to set a new version value get to the root OWLAPI folder and run mvn versions:set. This will open a prompt asking for the new version. There's a way of passing the new value on the command line but it takes a lot more typing, so I never learned it...

**Comment by ignazio1977** [comment]
Logging from existing tests looks like this:

    ERROR uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl - Illegal redeclarations of entities: reuse of entity http://www.example.org#p in punning not allowed [Declaration(ObjectProperty(<http://www.example.org#p>)), Declaration(DataProperty(<http://www.example.org#p>))]

**Comment by matthewhorridge** [comment]
I'll close this issue as I cannot reproduce it now.  I did copy and paste it from the log though, so I'm not sure what happened.
