### ISSUE TITLE
ManchesterOWLSyntaxRenderer renders SubPropertyOf inconsistently

### ISSUE THREAD

**Issue by ykazakov** [owlcs/owlapi#534]
For example a SubObjectPropertyOf axiom is rendered using ManchesterOWLSyntaxRenderer as

`R SubPropertyOf S`

But the parser seem to expect the keyword with colon:

`R SubPropertyOf: S`

I did not check other types of axioms. Was just debugging this.

**Comment by ignazio1977** [comment]
This is due to the renderer not being used directly when saving in manchester syntax - these axioms are actually rendered without a visit() call, so the code is not tested in the roundtrip tests.

**Comment by ykazakov** [comment]
@ignazio1977 
in your fix, you chose to render SubObjectOfPropery axioms with the colon instead of parsing it without the colon, but then SubClassOf axioms are rendered without the colon.
Should it be somehow consistent?
In the [official specs](https://www.w3.org/TR/owl2-manchester-syntax/), all axiom keywords are with colon.
Dows owlapi implementation follow these specs?

**Comment by ykazakov** [comment]
Actually, looking at these specs, I do not understand how GCIs should be rendered.
E.g., SubClassOf(ObjectIntersectionOf(:A :B) :C).
The SubClassOf: constructor can be present only in concept frames, i.e., it can have only concepts on the left side. Am I missing something?

**Comment by matthewhorridge** [comment]
GCIs cannot be represented in the official Manchester Syntax.

**Comment by ykazakov** [comment]
So, the Manchester syntax produced by owlapi is "unofficial" or GCIs are ignored when ontology is rendered in Manchester syntax?

**Comment by sesuncedu** [comment]
So, the Manchester syntax produced by owlapi is "unofficial" or GCIs are
ignored when ontology is rendered in Manchester syntax?

The W3C Technical Recommendation describing OMN is a only Note, not a
Recommendation, so technically the specification is officially unofficial
and only unofficially official. The document  «* is a draft document and
may be updated, replaced or obsoleted by other documents at any time.*»

There are no objections from the OWL working group to an official editor
acting  to update the grammar unofficially.

If the Matthew Horridge, affiliated with the University of Manchester who
is identified in the 2012 document as the first editor is in fact the same
individual  as the Matthew Horridge who is a committer to this repository
then any intentional changes to the grammar are thus not necessarily not
officially unofficially official.

[Thank you Bernard]

The official unofficial transformation for rendering GCIs is to name the
LHS using a fresh IRI. This could be automated if the fresh name is
generated in an owlapi controlled namespace, as a function of the RHS, and
annotated as such to allow for reversible parsing.

Or the ugly name could be kept to discourage the use of GCIs. 😈

**Comment by ykazakov** [comment]
I just checked: in the functional-style rendering in Protege ignores GCIs:
<img width="848" alt="screen shot 2017-05-17 at 22 12 46" src="https://cloud.githubusercontent.com/assets/2140361/26174044/53186620-3b4e-11e7-874a-090952095b22.png">
However, the code in the [ManchesterOWLSyntaxObjectRenderer](https://github.com/owlcs/owlapi/blob/2d7969c3e9d417d97839c59b634b878df6a006aa/parsers/src/main/java/org/semanticweb/owlapi/manchestersyntax/renderer/ManchesterOWLSyntaxObjectRenderer.java) of OWL API seems to handle it
```
    @Override
    public void visit(@Nonnull OWLSubClassOfAxiom axiom) {
        setAxiomWriting();
        axiom.getSubClass().accept(this);
        write(SUBCLASS_OF);
        axiom.getSuperClass().accept(this);
        restore();
    }
```
Did not check what is produced in the result, but I guess something like `A and B SubClassOf C`

**Comment by ykazakov** [comment]
OK, mystery solved.
The [ManchesterOWLSyntaxFrameRenderer](https://github.com/owlcs/owlapi/blob/2d7969c3e9d417d97839c59b634b878df6a006aa/parsers/src/main/java/org/semanticweb/owlapi/manchestersyntax/renderer/ManchesterOWLSyntaxFrameRenderer.java) that is used by [ManchesterSyntaxStorer](https://github.com/owlcs/owlapi/blob/2d7969c3e9d417d97839c59b634b878df6a006aa/parsers/src/main/java/org/semanticweb/owlapi/manchestersyntax/renderer/ManchesterSyntaxStorer.java) to write the ontology, filters out GCIs, and actually does not use the methods for rendering individual axioms. The output is then like in the linked "officially unofficial" specs, i.e., SubClassOf is written with the colon.

**Comment by ykazakov** [comment]
@ignazio1977, you say that the axioms rendered by ManchesterOWLSyntaxObjectRenderer are not tested with the ManchesterOWLSyntaxParserImpl. Can they be actually parsed by some parser?
I ran a quick test with the [owl primer ontology](https://www.w3.org/TR/owl2-primer/#Appendix:_The_Complete_Sample_Ontology) and many rendered axioms fail to parse by ManchesterOWLSyntaxParserImpl:
```
 Functional: hasHusband
 not (Jack hasAge 53)
hasBrother(?<http://example.com/owl/families/y>, ?<http://example.com/owl/families/z>), hasParent(?<http://example.com/owl/families/x>, ?<http://example.com/owl/families/y>) -> hasUncle(?<http://example.com/owl/families/x>, ?<http://example.com/owl/families/z>)
John Type hasChild max 4 Parent
Person HasKey hasSSN
 Transitive: hasAncestor
Mary Type Person
 Symmetric: hasSpouse
hasChild EquivalentTo child
John SameAs JohnBrown
 Irreflexive: parentOf
hasChild InverseOf hasParent
John Type hasChild exactly 5 Thing
 Reflexive: hasRelative
<http://example.com/owl/families/Person> comment "Represents the set of all people."
John Type Father
hasWife Domain Man
 InverseFunctional: hasHusband
 Asymmetric: hasChild
 not (Bill hasDaughter Susan)
hasBrother(?<http://example.com/owl/families/y>, ?<http://example.com/owl/families/z>), hasParent(?<http://example.com/owl/families/x>, ?<http://example.com/owl/families/y>) -> (hasUncle some Person)(?<http://example.com/owl/families/x>)
Woman(?<http://example.com/owl/families/x>) -> Person(?<http://example.com/owl/families/x>)
John Type hasChild min 2 Parent
hasAge Domain Person
EquivalentProperties: hasAge, age
```
It would be nice if the output of a renderer were parsable, e.g., so that in Protege it is possible to enter such axioms directly. 

Here is the  test:
```
public void testManchesterParser() throws OWLOntologyCreationException {

		OWLOntologyManager manager = OWLManager.createOWLOntologyManager();

		OWLOntology ontology = manager.loadOntologyFromOntologyDocument(
				getInputOntology("owl2primer.owl"));
		ManchesterOWLSyntaxParser parser = new ManchesterOWLSyntaxParserImpl(
				new Provider<OWLOntologyLoaderConfiguration>() {
					@Override
					public OWLOntologyLoaderConfiguration get() {
						return new OWLOntologyLoaderConfiguration();
					}
				}, manager.getOWLDataFactory());
		parser.setOWLEntityChecker(new OntologyEntityChecker(ontology));
		for (OWLAxiom axiom : ontology.getAxioms()) {
			String rendered = render(axiom);
			if (axiom.isOfType(AxiomType.DECLARATION)) {
				continue;
			}
			try {
				parser.setStringToParse(rendered);
				OWLAxiom parsed = parser.parseAxiom();
				assertEquals(axiom, parsed);
			} catch (OWLParserException e) {
				System.err.println(rendered);
			}
		}

	}
```
