### ISSUE TITLE
OWL/XML format does not support SWRL variable IRIs

### ISSUE THREAD

**Issue by martinjoconnor** [owlcs/owlapi#535]
I have a question about the OWL/XML serialization of SWRL variables using the OWLAPI. 

Below is a simple ontology with the rule ```sameAs(?x, ?y) ->```. No prefixes were set or modified.

```
<?xml version="1.0"?>
<Ontology xmlns="http://www.w3.org/2002/07/owl#"
     xml:base="http://www.semanticweb.org/z002yycx/ontologies/2016/5/untitled-ontology-9"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:xml="http://www.w3.org/XML/1998/namespace"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
     ontologyIRI="http://www.semanticweb.org/z002yycx/ontologies/2016/5/untitled-ontology-9">
    <Prefix name="owl" IRI="http://www.w3.org/2002/07/owl#"/>
    <Prefix name="rdf" IRI="http://www.w3.org/1999/02/22-rdf-syntax-ns#"/>
    <Prefix name="xml" IRI="http://www.w3.org/XML/1998/namespace"/>
    <Prefix name="xsd" IRI="http://www.w3.org/2001/XMLSchema#"/>
    <Prefix name="rdfs" IRI="http://www.w3.org/2000/01/rdf-schema#"/>
    <DLSafeRule>
        … some annotations deleted … 
        <Body>
            <SameIndividualAtom>
                <Variable IRI="x"/>
                <Variable IRI="y"/>
            </SameIndividualAtom>
        </Body>
        <Head/>
    </DLSafeRule>
</Ontology>

<!-- Generated by the OWL API (version 4.2.5.20160517-0735) https://github.com/owlcs/owlapi -->
```

The IRIs of variables ```x``` and ```y``` effectively become ```http://www.semanticweb.org/z002yycx/ontologies/2016/5/untitled-ontology-9x```
and ```http://www.semanticweb.org/z002yycx/ontologies/2016/5/untitled-ontology-9y```.

The IRI remainders extracted for use as SWRL variable names are thus ```untitled-ontology-9x``` and ```untitled-ontology-9y```, which is not as expected.

Is this serialization correct? The RDF/XML serialization does not exhibit this issue. There, variable IRIs effectively have a ```#``` between the namespace and the remainder.

**Comment by danielepantaleone** [comment]
I guess te problem may be related to https://github.com/owlcs/owlapi/issues/529

**Comment by ignazio1977** [comment]
The variable IRIs are meant to have `urn:swrl#` namespaces, so this should be 

    <Variable IRI="urn:swrl#x"/>
    <Variable IRI="urn:swrl#y"/>

I am amending the code to deal with the relative case correctly.
