### ISSUE TITLE
How can i load multiple ontology files automatically using a Restful style

### ISSUE THREAD

**Issue by jindeli05** [owlcs/owlapi#538]
I am am trying to get a good understanding of OWL API but i find few examples. how can i create a method that will enable me dynamically load the files(.owl). I dont know but OWL API i guess does not support sqarql.
There isn't much books and resources with detailed examples to start programming easily

**Comment by ignazio1977** [comment]
OWLAPI does not support SPARQL, that's correct.

Have you seen the examples here? https://github.com/owlcs/owlapi/wiki/Documentation
There is a tutorial here: http://owlapi.sourceforge.net/owled2011_tutorial.pdf

**Comment by jindeli05** [comment]
Thanks ignazio. i have seen the documentation and the tutorials to load. But how do i use the hermit reasoner to make the reasoning for getting all classes, subclasses, properties, and objects with the code. Aagain, what is an axiom?

**Comment by sesuncedu** [comment]
An Axiom is a  statement that is taken to be true by definition. 
For example in an ontology we might assert two axioms : 
* Dog subClassOf Mammal
* Mammal subClassOf Animal 

The semantics of OWL are defined such that for all A, B, C,  
A subClassOf B, B subClassOf C |= A subClassOf C

A reasoner can infer that Dog subClassOf Animal.  

It is possible to add an Axiom that states that not (Dog subClassOf Animal). 
This would create an inconsistency in an OWL ontology.

**Comment by cmungall** [comment]
You might find it useful to start with the OWL Primer https://www.w3.org/TR/owl2-primer/
