### ISSUE TITLE
Eclipse RDF4J changeover

### ISSUE THREAD

**Issue by ansell** [owlcs/owlapi#539]
The OpenRDF Sesame project will not be releasing any new versions, as they are focusing their effort on the first Eclipse RDF4J release. Eclipse RDF4J-2.0 will be based on the last OpenRDF Sesame release, 4.1.2, but the package names have changed, from org.openrdf.\* to org.eclipse.*, so it isn't a drop in replacement in that way.

Given that there will be no further maintenance releases of OpenRDF Sesame, it is a moderate priority for OWLAPI to offer a version based on RDF4J that is maintained. So far there have only been milestone builds of the new RDF4J modules, with a full release date only being held up by the Eclipse Legal Team.

However, given that the package names have changed and we are exposing some of the org.openrdf packages in OWLAPI method signatures, it probably needs to wait for an OWLAPI-6 (ughh, but it fits with Semantic Versioning...)

**Comment by ansell** [comment]
That of course presumes that the version 5 branch is already locked down in terms of API compatibility, seeing it has had a release already.

**Comment by sesuncedu** [comment]
The affected code is almost entirely restricted to the rio sub-project.  

The exceptions seem to be:
1. Rio Test cases in the 'contract' sub-project.
2.  OpenSesamRDF dependencies in the distribution and osgi-distribution sub-projects.

It would not seem too difficult to provide good-enough backwards compatibility for this:
1. Creating a separate sub-project for the sesame-rio, with sesame-mode-no-more-bug-fixes-ever support.
2. Merge the openrdf fixes into version5 rio, renaming the project to openrdf-rio. 
3. Either generate two separate distributions for the two versions, or have the rio parsers be independent modules, or arrange some sort of eventual transition.  

 On a related note:  rio and parsers both create classes in the ```org.semanticweb.owlapi.formats``` package.  This will cause problems with jdk9 jigsaw, which really, really, dislikes using the same package name in different modules (can't do it in a single class loader). This is an instance of a more general problem, and should be taken care of for version6, which is due for  some serious module decomposition.

**Comment by ansell** [comment]
I merged the changes into master and changed its version number to 6, but if you can make it work with version 5 that would be great.

I haven't looked into jdk9 jigsaw at all yet, so not sure what we will do about that. There is a lot of legacy code out there that will just flatout fail if they enforce the package name uniqueness restriction. You thought the javadoc fuss that people put up for jdk8 was bad, a package name uniqueness constraint will make them go ballistic!

**Comment by ignazio1977** [comment]
Given that there will be no maintenance releases under the old library names, there is little point in keeping them around. I'll do a release for 4 and 5 to include the latest bug fixes, then update both to Eclipse RDF4J.

Speaking of which, we might want a plan for version 4 - Protege uses it, but it might be time to start thinking about updates.

**Comment by ignazio1977** [comment]
Having started making the same changes on version 5, I don't think there is any impact on code using OWLAPI, unless that code relies on the RIO classes themselves; the RIO proxy formats for OWLAPI still implement the same interfaces (e.g., the contract tests needed no changes to run). I think it's straightforward to release the update as 5.1.0; I expect it to be backwards compatible with almost all dependent code.

**Comment by ansell** [comment]
That would be great to have it on version 5.1. 

In terms of the module package name uniqueness, adding a subpackage like org.semanticweb.owlapi.formats.rio may be useful for version 6 (assuming we are targeting version 6 at jdk9/jigsaw)

**Comment by ignazio1977** [comment]
Using the same package name for different formats was just convenience; we could even move them all to one module. The format class without the format parsers and storers is not useful, but it's not damaging either, so we have pretty much a free hand in this.

**Comment by sesuncedu** [comment]
Formats could be part of the API, so that different implementations of eg
turtle owl could be supported. Also metadata out of formats now.

Also, this is one of the places where OSGI has some definite advantages
over jigsaw ; versions in OSGI are per-package, though a lot of libraries
just use the build version for each package. This can avoid having to
update dependents that don't use unaffected packages, and thus can make
semantic versioning less disruptive.

It's amazing how good jigsaw makes OSGI look :)

**Comment by ignazio1977** [comment]
I've been wondering about that - as we are planning better integration with RDF4J, as RDF4J already has format classes to use as markers of intended formats, as we are already using some interfaces (OWLAPI IRI extends RDF4J IRI) - we might ditch duplication in those areas, or at least extend existing class structures rather than reinvent and adapt.

Might be big API changes though, so a thought for version 6.

**Comment by sesuncedu** [comment]
I would really like to make IRI  an interface. Creation should really be
via a factory.
The static create methods could be marked deprecated; the default
implementation would probably still have to live in impl.

**Comment by ansell** [comment]
+1 for factories for IRIs and defining more things using interfaces. Factories are also very useful for Blank Node creation and identity maintenance so you don't need a munging standard for blank node identifiers.

See the salt pattern for blank node creation by factories that I contributed to Commons RDF before I left the project:

https://github.com/apache/commons-rdf/blob/master/api/src/main/java/org/apache/commons/rdf/api/BlankNode.java

https://github.com/apache/commons-rdf/blob/master/api/src/main/java/org/apache/commons/rdf/api/RDF.java

https://github.com/apache/commons-rdf/blob/master/simple/src/main/java/org/apache/commons/rdf/simple/BlankNodeImpl.java

https://github.com/apache/commons-rdf/blob/master/simple/src/main/java/org/apache/commons/rdf/simple/SimpleRDF.java#L53

**Comment by sesuncedu** [comment]
An interesting related point is that Commons RDF makes BlankNode objects be globally unique, whilst simultaneously scoping named blank-node id lookup / creation to an entire RDF object... which is the factory for DataSets.   Everybody loves blanknodes...
