### ISSUE TITLE
Slow inferred disjoint generator

### ISSUE THREAD

**Issue by ignazio1977** [owlcs/owlapi#542]
From https://bmir-gforge.stanford.edu/gf/project/owleditor/tracker/?action=TrackerItemEdit&tracker_item_id=2654&start=0

(original diagnosis from Birte and Timothy)

InferredDisjointClassesAxiomGenerator does not use getDisjointClasses, but it tries to encode the reasoning problem itself by testing for each pair of classes, whether the intersection of the first with the negaion of the second class is satisfiable. This definitely should be changed since it bypasses all optimisations that we do within the reasoner. 

Ideally, precomputeInferences(InferenceType.DISJOINT_CLASSES) should be used. That way, we know that all such entailments are needed and we could use a one-pass classification with extra axioms which allows us to find all disjoint classes from the resulting class hierarchy. We wouldn't do that if you ask getDisjointClasses(class) for each class separately because in case you want to know the disjoint classes of just one class, the one-pass classification is too expensive and does more work than possibly required. Even getDisjointClasses is not as simplistic as to test the intersection of the given class with the negation of any other class.

    List<InferredAxiomGenerator<? extends OWLAxiom>> generators=new ArrayList<InferredAxiomGenerator<? extends OWLAxiom>>();
    // materialize subclasses
    generators.add(new InferredSubClassAxiomGenerator());
    // now add a customized one for disjoint classes
    generators.add(new InferredDisjointClassesAxiomGenerator() {
        boolean precomputed=false;
        protected void addAxioms(OWLClass entity, OWLReasoner reasoner,
OWLDataFactory dataFactory, Set<OWLDisjointClassesAxiom> result) {
            if (!precomputed) {
                reasoner.precomputeInferences(InferenceType.DISJOINT_CLASSES);
                precomputed=true;
            }
            for (OWLClass cls : reasoner.getDisjointClasses(entity).getFlattened()) {
                result.add(dataFactory.getOWLDisjointClassesAxiom(entity, cls));
            }
        }
    });

Computing disjoint classes will still be expensive, but at least our [HermiT] optimizations are then no longer ignored and you get the progress bar.
The code is not HermiT specific, so any OWLReasoner should work (provided they implemented the methods).

**Comment by sesuncedu** [comment]
I wrote some reasoner neutral code that did some optimization for computing
(not quite all) inferred disjoint classes, which used asserted disjoints
and inferred class hierarchy to eliminate a lot of redundant testing.

It worked well for the case i was looking at (EL, with all anonymous class
expressions named), but I'm not sure how big a win it is in general.
