### ISSUE TITLE
bug with SWRL saving

### ISSUE THREAD

**Issue by ignazio1977** [owlcs/owlapi#546]
From: http://stackoverflow.com/questions/38604003/protege-5-adds-prefix-to-swrl-rules

I've noticed each rule i write in SWRL tab its variables is prefixed by my ontology uri . for example if i have a ckd ontology and then add this rule in swrl tab:

has_Age(?x, ?y) ^ Personal_Profile(?x) -> has_Stage(?x, ?y) 
it will turn to :

has_Age(?ckdx, ?ckdy) ^ Personal_Profile(?ckdx) -> has_Stage(?ckdx, ?ckdy)
And the worse is that if i try to edit this rule after confirm the rule will be prefixed by another ckd . so each time a rule is edited a prefix is added to its variables:

has_Age(?ckdckdx, ?ckdckdy) ^ Personal_Profile(?ckdckdx) -> has_Stage(?ckdckdx, ?ckdckdy)

**Comment by martinjoconnor** [comment]
I think that this is a SWRLAPI bug. I am looking into it.

**Comment by ignazio1977** [comment]
Cheers Martin

**Comment by martinjoconnor** [comment]
Was a SWRLAPI bug. Fixed in the latest 1.0.12 SWRLAPI release.
