### ISSUE TITLE
OMN Parser mistakes punned class for object property

### ISSUE THREAD

**Issue by nemishas** [owlcs/owlapi#548]
Hi

I'm facing an error trying to obtain the class expression from a string using ManchesterOWLSyntaxParser.parseClassExpression() when the string contains a class name which is also an object property name. My input is simply 'A or B', where B is a class and it also happens to be an object property. I get:
```
Exception in thread "main" org.semanticweb.owlapi.manchestersyntax.renderer.ParserException: Encountered |EOF| at line 1 column 13. Expected one of:
	min
	exactly
	max
	value
	Self
	only
	some

	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl$ExceptionBuilder.build(ManchesterOWLSyntaxParserImpl.java:2441)
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.parseObjectRestriction(ManchesterOWLSyntaxParserImpl.java:669)
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.parseNonNaryClassExpression(ManchesterOWLSyntaxParserImpl.java:581)
...
```
Not sure how much punning is supported, but based on the [specification](https://www.w3.org/TR/owl2-new-features/#F12:_Punning) I was expecting the API to understand from context whether I'm talking about the class or the object property. Apparently the code first checks whether the token is an object property name, then proceeds to create an object restriction. I guess even checking for class name first wouldn't be correct. What could be the solution to this?

Please shed some light on this.. Also, I haven't checked if other parsers share this behavior.

**Comment by ignazio1977** [comment]
The problem there is that the parser does not know if B is the start of a class expression (`B min 1` for example) or the last element in the disjoint. Resolving this ambiguity, in general, requires the parser to be LL(K) or to start backtracking (i.e., assume that B is a property and try to finish parsing; if a failure arises, try with B as class - and replicate this process for each ambiguous point.

This could be simplified if parentheses were mandatory around nested class expressions; however, that's not the case with the current grammar.

The most feasible solution is probably to change the order of checking for known primitives according to the context (parsing a series of classes or not?), although this won't stop all failures of this kind, just reduce them.

**Comment by ignazio1977** [comment]
With the latest version4, this test works:

    @Test
    public void shouldSupportPunningClassesAndPropertiesInManchesterSyntax() throws OWLOntologyCreationException {
        OWLClass b = df.getOWLClass(IRI.create("urn:test#", "B"));
        OWLClass a = df.getOWLClass(IRI.create("urn:test#", "A"));
        OWLOntology o = m.createOntology();
        m.addAxiom(o, df.getOWLDeclarationAxiom(df.getOWLObjectProperty(IRI.create("urn:test#", "B"))));
        m.addAxiom(o, df.getOWLDeclarationAxiom(b));
        m.addAxiom(o, df.getOWLDeclarationAxiom(a));
        ManchesterOWLSyntaxParserImpl parser = (ManchesterOWLSyntaxParserImpl) OWLManager.createManchesterParser();
        parser.getPrefixManager().setDefaultPrefix("urn:test#");
        parser.setDefaultOntology(o);
        parser.setStringToParse(":A or :B");
        OWLClassExpression parseClassExpression = parser.parseClassExpression();
        assertEquals(parseClassExpression, df.getOWLObjectUnionOf(a, b));
    }
