### ISSUE TITLE
ManchesterOWLSyntaxParser doesn't handle the OWL 2 datatypes

### ISSUE THREAD

**Issue by SuhasDoijad** [owlcs/owlapi#556]
Converting String (which is in Manchester OWL Syntax) to `OWLClassExpression `using `ManchesterOWLSyntaxParser `gives exception if String contains **OWL 2 datatypes** like `owl:real` and `owl:rational`. `ManchesterOWLSyntaxParser`'s `.parseClassExpression()` method is used.

May be, because **OWL 2 datatypes** are not added into `dataTypeNames `and `owlEntityChecker.getOWLDatatype()` doesnt have any reference of that DataType if it is occurred first time.

From :[http://stackoverflow.com/questions/39033108/owlapi-parserexception-while-converting-string-to-class-expression-using-man](http://stackoverflow.com/questions/39033108/owlapi-parserexception-while-converting-string-to-class-expression-using-man)

**Comment by sesuncedu** [comment]
Is there any reason not to iterate over OWL2Datatypes.values()? 

That shouldn't be over inclusive, right?
