### ISSUE TITLE
Relative Ontology IRI causes missing declaration

### ISSUE THREAD

**Issue by Gnuko** [owlcs/owlapi#557]
This code creates ClassAssertion instead of DataPropertyAssertion
```
OWLDataProperty prop = factory.getOWLDataProperty(IRI.create(getOntologyIRI()  + "#" +  owlDataProp));
OWLNamedIndividual ind = factory.getOWLNamedIndividual(IRI.create(getOntologyIRI()  + "#" +  owlNamedIndividual));
OWLLiteral lit = factory.getOWLLiteral(val);

OWLDataPropertyAssertionAxiom axiom = factory.getOWLDataPropertyAssertionAxiom(prop, ind, lit);
if(manager.addAxiom(this.ontology, axiom) == ChangeApplied.SUCCESSFULLY)
    return saveOntology();
return false;
```

also here [Stackoverflow](http://stackoverflow.com/questions/37407277/unable-to-create-datapropertyassertion-with-owl-api)

**Comment by ignazio1977** [comment]
Including StackOverflow content for clarity:

CODE:

    OWLDataProperty prop = factory.getOWLDataProperty(IRI.create(getOntologyIRI()  + "#" + owlDataProp));
    OWLNamedIndividual ind = factory.getOWLNamedIndividual(IRI.create(getOntologyIRI()  + "#" +  owlNamedIndividual));
    OWLLiteral lit = factory.getOWLLiteral(val);

    OWLDataPropertyAssertionAxiom axiom = factory.getOWLDataPropertyAssertionAxiom(prop, ind, lit);
    if (manager.addAxiom(this.ontology, axiom) == ChangeApplied.SUCCESSFULLY)
        return saveOntology();
    return false;

Creates an annotation assertion.

Expected result is (manually created):

data property assertion

I try to create OWLNegativeDataPropertyAssertionAxiom and it works fine. Also if I create getOWLNegativeDataPropertyAssertionAxiom first and then create OWLDataPropertyAssertionAxiom - it works.

OWLAPI: owlapi-distribution-4.1.4.jar

EDIT:

Created ontologies:

    <?xml version="1.0"?>
    <rdf:RDF xmlns="gunkoFB.owl#" xml:base="gunkoFB.owl" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:owl="http://www.w3.org/2002/07/owl#" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:xsd="http://www.w3.org/2001/XMLSchema#" xmlns:gunkoFB="gunkoFB.owl#" xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">
    <owl:Ontology rdf:about="gunkoFB.owl"/>
    <owl:DatatypeProperty rdf:about="gunkoFB.owl#hasFirstName"/>
    <owl:NamedIndividual rdf:about="gunkoFB.owl#Michal_Joštiak">
    <hasFirstName rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Michal</hasFirstName>
    </owl:NamedIndividual>

    <?xml version="1.0"?>

    <rdf:RDF xmlns="gunkoFB.owl#"
     xml:base="gunkoFB.owl"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:owl="http://www.w3.org/2002/07/owl#"
     xmlns:xml="http://www.w3.org/XML/1998/namespace"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">
    <owl:Ontology rdf:about="gunkoFB.owl"/>

    <owl:DatatypeProperty rdf:about="gunkoFB.owl#hasFirstName"/>

    <owl:NamedIndividual rdf:about="gunkoFB.owl#Michal_Joštiak"/>
    <rdf:Description>
    <rdf:type rdf:resource="http://www.w3.org/2002/07/owl#NegativePropertyAssertion"/>
    <owl:sourceIndividual rdf:resource="gunkoFB.owl#Michal_Joštiak"/>
    <owl:assertionProperty rdf:resource="gunkoFB.owl#hasFirstName"/>
    <owl:targetValue rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Michal</owl:targetValue>
    </rdf:Description>

  	
 		
This case is when I save ontology as RDF/XML. Maybe its just Protege fail. When I save ontology as OWL/XML its OK again.

**Comment by ignazio1977** [comment]
My guess is OWL/XML is not storing all required declarations.

**Comment by ignazio1977** [comment]
I cannot replicate the failure. The following code:

    public class RDFXMLProblemWithDatapropertyTestCase extends TestBase {
    @Test
    public void shouldStoreDeclarationForDataproperty() throws OWLOntologyCreationException, OWLOntologyStorageException {
        OWLDataProperty prop = df.getOWLDataProperty(IRI.create("gunkoFB.owl#hasFirstName"));
        OWLNamedIndividual ind = df.getOWLNamedIndividual(IRI.create("gunkoFB.owl#Michal_Joštiak"));
        OWLLiteral lit = df.getOWLLiteral("Michal");

        OWLDataPropertyAssertionAxiom axiom = df.getOWLDataPropertyAssertionAxiom(prop, ind, lit);
        OWLOntology o = m.createOntology(IRI.create("urn:test:ontology"));
        m.addAxiom(o, axiom);
        StringDocumentTarget save = saveOntology(o, new RDFXMLDocumentFormat());
        System.out.println(save);
        OWLOntology o2=loadOntologyFromString(save);
        for(OWLAxiom ax:o2.getAxioms()) {
            System.out.println(ax);
        }
    }
    }

Produces this output:

    <?xml version="1.0"?>
    <rdf:RDF xmlns="urn:test:ontology#"
     xml:base="urn:test:ontology"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:owl="http://www.w3.org/2002/07/owl#"
     xmlns:xml="http://www.w3.org/XML/1998/namespace"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
     xmlns:gunkoFB="gunkoFB.owl#"
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">
    <owl:Ontology rdf:about="urn:test:ontology"/>
    
    <owl:DatatypeProperty rdf:about="gunkoFB.owl#hasFirstName"/>
    
    <owl:NamedIndividual rdf:about="gunkoFB.owl#Michal_Joštiak">
        <gunkoFB:hasFirstName rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Michal</gunkoFB:hasFirstName>
    </owl:NamedIndividual>
    </rdf:RDF>

    Declaration(NamedIndividual(<gunkoFB.owl#Michal_Joštiak>))
    Declaration(DataProperty(<gunkoFB.owl#hasFirstName>))
    DataPropertyAssertion(<gunkoFB.owl#hasFirstName> <gunkoFB.owl#Michal_Joštiak> "Michal"^^xsd:string)


Can you provide a full sample that reproduces the error? this might be due to something else existing in the ontology.

**Comment by Gnuko** [comment]
Sample project with created owl:

[GitHubBugSample.zip](https://github.com/owlcs/owlapi/files/463552/GitHubBugSample.zip)

**Comment by ignazio1977** [comment]
Thanks for the code example.

When I run it, I get, for both OWLAPI 4.1.4 and 5.0.2, the following output:

    <?xml version="1.0"?>
    <rdf:RDF xmlns="test.owl#"
     xml:base="test.owl"
     xmlns:test="test.owl#"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:owl="http://www.w3.org/2002/07/owl#"
     xmlns:xml="http://www.w3.org/XML/1998/namespace"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">
    <owl:Ontology rdf:about="test.owl"/>
    
    <owl:DatatypeProperty rdf:about="test.owl#dataProp"/>
    
    <owl:NamedIndividual rdf:about="test.owl#namedIndivindi">
        <dataProp rdf:datatype="http://www.w3.org/2001/XMLSchema#string">val</dataProp>
    </owl:NamedIndividual>
    </rdf:RDF>

When parsed, these axioms are found:

    AnnotationAssertion(<test.owl#dataProp> <file:/Users/ignazio/workspace/GitHubBugSample/test.owl#namedIndivindi> "val"^^xsd:string)
    Declaration(NamedIndividual(<file:/Users/ignazio/workspace/GitHubBugSample/test.owl#namedIndivindi>))
    Declaration(DataProperty(<file:/Users/ignazio/workspace/GitHubBugSample/test.owl#dataProp>))

As it is evident, the issue is that the namespaces for the properties do not match. This is due to the ontology IRI being a relative one; the axiom property is stored as created, while the declaration is resolved to be absolute. On parsing, these no longer match, causing the OWLAPI to think the property is not declared.

As a workaround, use absolute IRIs for the ontology IRI. The IRIs should have been made absolute consistently.

    static String ontologyPath = "http://test.owl";
