### ISSUE TITLE
getImportsClosure fails on this ontology

### ISSUE THREAD

**Issue by alanruttenberg** [owlcs/owlapi#558]
http://biohub.cs.manchester.ac.uk/ontology/biohub-kb.owl

Also manifested as wonky imports graph using OWLViz Imports Graph (included below). My problems are using OWLAPI v4.2.5, Protege is version 5.0.0

![screen shot 2016-09-05 at 10 33 29 pm](https://cloud.githubusercontent.com/assets/241934/18260110/ce222b2a-73b8-11e6-9bda-6a50cd4d550e.PNG)

**Comment by matthewhorridge** [comment]
I'm just wondering if this is related to this other issue:  https://github.com/owlcs/owlapi/issues/541

**Comment by ignazio1977** [comment]
I've tried replicating the issue on the current version4, results below. Does it look like the expected direct graph?

    0	http://www.unilever.com/ontologies/biohub
	    1	uberon/ext.owl
    		2	uberon/go_import.owl
    		2	uberon/cl_import.owl
    		2	uberon/pr_import.owl
    		2	uberon/ncbitaxon_import.owl
    		2	uberon/chebi_import.owl
    		2	uberon/envo_import.owl
    		2	uberon/nbo_import.owl
    		2	uberon/ro_import.owl
    		2	uberon/pato_import.owl
    	1	chebi.owl
    	1	po.owl
    	1	http://www.purl.org/ontolink/tawny
    	1	cl.owl
    		2	cl/imports/pato_import.owl
    		2	cl/imports/clo_import.owl
    		2	cl/imports/ro_import.owl
    		2	cl/imports/ncbitaxon_import.owl
    		2	cl/imports/chebi_import.owl
    		2	cl/imports/pr_import.owl
    		2	cl/imports/uberon_import.owl
    		2	cl/imports/go_import.owl
    	1	ro.owl
    		2	ro/annotations.owl
    		2	ro/pato_import.owl
    		2	ro/temporal-intervals.owl
    			3	ro/annotations.owl
    			3	ro/core.owl
    				4	ro/annotations.owl
    				4	ro/bfo-classes-minimal.owl
    					5	ro/annotations.owl
    		2	ro/go_mf_import.owl
    		2	ro/core.owl
    			3	ro/annotations.owl
    			3	ro/bfo-classes-minimal.owl
    				4	ro/annotations.owl
    		2	ro/rohom.owl
    		2	ro/go-biotic.owl
    		2	ro/el-constraints.owl

**Comment by ignazio1977** [comment]
The imports closure comes out like this, without anonymous ontologies like in the picture.

    http://www.unilever.com/ontologies/biohub
    http://purl.obolibrary.org/obo/po.owl
    http://purl.obolibrary.org/obo/cl.owl
    http://purl.obolibrary.org/obo/cl/imports/pr_import.owl
    http://purl.obolibrary.org/obo/cl/imports/uberon_import.owl
    http://purl.obolibrary.org/obo/cl/imports/ro_import.owl
    http://purl.obolibrary.org/obo/cl/imports/ncbitaxon_import.owl
    http://purl.obolibrary.org/obo/cl/imports/clo_import.owl
    http://purl.obolibrary.org/obo/cl/imports/chebi_import.owl
    http://purl.obolibrary.org/obo/cl/imports/pato_import.owl
    http://purl.obolibrary.org/obo/cl/imports/go_import.owl
    http://www.purl.org/ontolink/tawny
    http://purl.obolibrary.org/obo/uberon/ext.owl
    http://purl.obolibrary.org/obo/uberon/chebi_import.owl
    http://purl.obolibrary.org/obo/uberon/nbo_import.owl
    http://purl.obolibrary.org/obo/uberon/cl_import.owl
    http://purl.obolibrary.org/obo/uberon/ro_import.owl
    http://purl.obolibrary.org/obo/uberon/envo_import.owl
    http://purl.obolibrary.org/obo/uberon/pr_import.owl
    http://purl.obolibrary.org/obo/uberon/pato_import.owl
    http://purl.obolibrary.org/obo/uberon/ncbitaxon_import.owl
    http://purl.obolibrary.org/obo/uberon/go_import.owl
    http://purl.obolibrary.org/obo/chebi.owl
    http://purl.obolibrary.org/obo/ro.owl
    http://purl.obolibrary.org/obo/ro/pato_import.owl
    http://purl.obolibrary.org/obo/ro/core.owl
    http://purl.obolibrary.org/obo/ro/annotations.owl
    http://purl.obolibrary.org/obo/ro/bfo-classes-minimal.owl
    http://purl.obolibrary.org/obo/ro/temporal-intervals.owl
    http://purl.obolibrary.org/obo/ro/go_mf_import.owl
    http://purl.obolibrary.org/obo/ro/el-constraints.owl
    http://purl.obolibrary.org/obo/ro/go-biotic.owl
    http://purl.obolibrary.org/obo/ro/rohom.owl

**Comment by alanruttenberg** [comment]
I'm getting the ontology with loadOntologyFromOntologyDocument
 
o-> 
#<uk.ac.manchester.cs.owl.owlapi.concurrent.ConcurrentOWLOntologyImpl Ontology(OntologyID(Anonymous-2).... {7E9CCE00}>

I try to get the size 

o.getImportsClosure().size() 

and the answer is 1

I've also used o.iterator() , o.toArray() - same deal.

This is with just-downloaded 4.2.6

**Comment by alanruttenberg** [comment]
Can you share the code you use to generate your result?

**Comment by ignazio1977** [comment]
public void shouldPrintOutImportsClosure() throws OWLOntologyCreationException {
        OWLOntology o = m.loadOntology(IRI.create("http://biohub.cs.manchester.ac.uk/ontology/biohub-kb.owl"));
        level(0, o);
        for (OWLOntology o1:o.getImportsClosure()) {
            System.out.println(o1.getOntologyID().getOntologyIRI().get());
        }
    }
    private void level(int level, OWLOntology o) {
        System.out.println(Strings.repeat("\t", level)+level+"\t"+o.getOntologyID().getOntologyIRI().get().toString().replace("http://purl.obolibrary.org/obo/", ""));
        for(OWLImportsDeclaration d:o.getImportsDeclarations()) {
            level(level+1, o.getOWLOntologyManager().getOntology(d.getIRI()));
        }
    }

**Comment by alanruttenberg** [comment]
Nope. Still losing. getImportsClosure returns a set with a single element.
Calling level gives me an error:
Java exception 'java.lang.IllegalStateException: Optional.get() cannot be called on an absent value'.

I thought maybe this was some library thing so I used the maven dependencies plugin to collect all the jars. I've listed the jars on my class path in case you see something.

Just for yucks, could you describe the recommended method of installing the OWLAPI and any necessary dependencies without relying on maven?

```
org.semanticweb.hermit-1.3.8.413.jar 
owlapi-distribution-4.2.6.jar 
owlapi-4.2.6-dependencies/aopalliance-1.0.jar 
owlapi-4.2.6-dependencies/commons-codec-1.6.jar 
owlapi-4.2.6-dependencies/commons-io-2.4.jar 
owlapi-4.2.6-dependencies/guava-18.0.jar 
owlapi-4.2.6-dependencies/guice-4.0.jar 
owlapi-4.2.6-dependencies/guice-assistedinject-4.0.jar 
owlapi-4.2.6-dependencies/guice-multibindings-4.0.jar 
owlapi-4.2.6-dependencies/hamcrest-core-1.3.jar 
owlapi-4.2.6-dependencies/httpclient-4.2.5.jar 
owlapi-4.2.6-dependencies/httpclient-cache-4.2.5.jar 
owlapi-4.2.6-dependencies/httpcore-4.2.4.jar 
owlapi-4.2.6-dependencies/jackson-annotations-2.5.1.jar 
owlapi-4.2.6-dependencies/jackson-core-2.5.1.jar 
owlapi-4.2.6-dependencies/jackson-databind-2.5.1.jar 
owlapi-4.2.6-dependencies/javax.inject-1.jar 
owlapi-4.2.6-dependencies/jcl-over-slf4j-1.7.7.jar 
owlapi-4.2.6-dependencies/jsonld-java-0.5.0.jar 
owlapi-4.2.6-dependencies/jsonld-java-sesame-0.5.0.jar 
owlapi-4.2.6-dependencies/jsr305-2.0.1.jar 
owlapi-4.2.6-dependencies/junit-4.12.jar 
owlapi-4.2.6-dependencies/mockito-all-1.9.5.jar 
owlapi-4.2.6-dependencies/owlapi-api-4.2.5.jar 
owlapi-4.2.6-dependencies/owlapi-apibinding-4.2.5.jar 
owlapi-4.2.6-dependencies/owlapi-fixers-4.2.5.jar 
owlapi-4.2.6-dependencies/owlapi-impl-4.2.5.jar 
owlapi-4.2.6-dependencies/owlapi-oboformat-4.2.5.jar 
owlapi-4.2.6-dependencies/owlapi-parsers-4.2.5.jar 
owlapi-4.2.6-dependencies/owlapi-rio-4.2.5.jar 
owlapi-4.2.6-dependencies/owlapi-tools-4.2.5.jar 
owlapi-4.2.6-dependencies/semargl-core-0.6.1.jar 
owlapi-4.2.6-dependencies/semargl-rdf-0.6.1.jar 
owlapi-4.2.6-dependencies/semargl-rdfa-0.6.1.jar 
owlapi-4.2.6-dependencies/semargl-sesame-0.6.1.jar 
owlapi-4.2.6-dependencies/sesame-model-2.7.16.jar 
owlapi-4.2.6-dependencies/sesame-rio-api-2.7.16.jar 
owlapi-4.2.6-dependencies/sesame-rio-binary-2.7.16.jar 
owlapi-4.2.6-dependencies/sesame-rio-datatypes-2.7.16.jar 
owlapi-4.2.6-dependencies/sesame-rio-languages-2.7.16.jar 
owlapi-4.2.6-dependencies/sesame-rio-n3-2.7.16.jar 
owlapi-4.2.6-dependencies/sesame-rio-nquads-2.7.16.jar 
owlapi-4.2.6-dependencies/sesame-rio-ntriples-2.7.16.jar 
owlapi-4.2.6-dependencies/sesame-rio-rdfjson-2.7.16.jar 
owlapi-4.2.6-dependencies/sesame-rio-rdfxml-2.7.16.jar 
owlapi-4.2.6-dependencies/sesame-rio-trig-2.7.16.jar 
owlapi-4.2.6-dependencies/sesame-rio-trix-2.7.16.jar 
owlapi-4.2.6-dependencies/sesame-rio-turtle-2.7.16.jar 
owlapi-4.2.6-dependencies/sesame-util-2.7.16.jar 
owlapi-4.2.6-dependencies/slf4j-api-1.7.10.jar 
owlapi-4.2.6-dependencies/slf4j-simple-1.7.10.jar 
owlapi-4.2.6-dependencies/trove4j-3.0.3.jar 
owlapi-4.2.6-dependencies/xz-1.5.jar 
factplusplus-1.6.4-SNAPSHOT.jar 
sc-prefuse.jar 
prefuse-demos.jar 
prefuse.jar 
abcl-contrib.jar 
abcl.jar 
Access_JDBC30.jar 
asm-all-3.1.jar 
httpserver.jar 
mysql-connector-java-5.1.31-bin.jar 
ojdbc6.jar 
postgresql-9.3-1101.jdbc41.jar 
script-api.jar 
sqlite-jdbc-3.7.2.jar 
sqljdbc4.jar 
virtjdbc3.jar 
xalan-j_2_7_1/serializer.jar 
xalan-j_2_7_1/xalan.jar 
xalan-j_2_7_1/xercesImpl.jar 
xalan-j_2_7_1/xml-apis.jar 
xalan-j_2_7_1/xsltc.jar 
md5.jar 
```

**Comment by ignazio1977** [comment]
> Calling level gives me an error:
Java exception 'java.lang.IllegalStateException: Optional.get() cannot be called on an absent value'.

That error means that one of the ontologies being parsed is anonymous - which is quite surprising, as the same IRIs parsed over here do not pull in any anonymous ontology.

The only difference I can find is that you mentioned you're using `loadOntologyFromOntologyDocument` while in my code I'm doing `loadOntology(IRI iri)`

**Comment by ignazio1977** [comment]
There is no official 'install without Maven' process, but basically what's needed is all the jars added to the classpath. At a guess, you already have all the right ones. Mockito, JUnit and HamCrest are extra, actually, as they're only needed at test time.

**Comment by ignazio1977** [comment]
See #584 for non maven usage
