### ISSUE TITLE
How can i read a lot of <skos:Collection> from Rdf-skos file

### ISSUE THREAD

**Issue by miledrousset** [owlcs/owlapi#559]
Hi, 
I would like to read an RDF-SKOS file that contains tags like <skos: Collection>, but only the collections and tags (and access all assertions about the Collection instances). Can you help me please to use the best solution?
thank you in advance.
Here is an example explained:
![capture d ecran 2016-09-16 a 12 50 38](https://cloud.githubusercontent.com/assets/3404662/18583858/86665790-7c0d-11e6-8c4a-69d5bd1dcfb2.png)

**Comment by sesuncedu** [comment]
DThe first issue is whether you want all assertions about the collection
instances, or everything that is known about the collection instance.

If you just want directly asserted rdf triples, then you might be better
off using an RDF api such as openrdf.

If you want inferred information (e.g.  the inferred skos:member data),
inferred labels, etc, then you need to use a reasoner.
As long as there are no ordered collections, you will be generally OK
(ordered collections use rdf:list, which is not allowed in OWL-DL, which is
the only kind of owl used in reasoners or which can legally be parsed from
rdf -  though owlapi and protégé will turn a blind eye in non-strict mode).

Some important inferences are not specified in the SKOS OWL (except as
comments); relevant ones include subgroup membership. I can't remember if
some of these are addressed in the ISO extensions.

If use OWLAPI, a good approach might be to create an ontology file that
imports the dependencies used as namespaces, as well as the rdf file .

Then you can create an OWLOntologyManager, load the ontology file, then
create an OWLReasoner, passing it the loaded ontology. You will need a
reasoner like pellet, Hermit, fact++ etc.  You can query the reasoner for
all instances of Collection, then get data and object property values from
the reasoner for each property of interest. Annotation Properties can be
retrieved from the OWLOntology.

**Comment by ignazio1977** [comment]
The SKOS API project might also be useful here.
