### ISSUE TITLE
Broken links in javadoc at GitHub

### ISSUE THREAD

**Issue by mikel-egana-aranguren** [owlcs/owlapi#560]
Hi;

Looking at http://owlcs.github.io/owlapi/apidocs_5_0_1/index.html, I have seen links that result in 404s, for example [org.semanticweb.owlapi.apibinding](http://owlcs.github.io/owlapi/apidocs_5_0_1/org/semanticweb/owlapi/apibinding/package-frame.html). 

Thanks

**Comment by ignazio1977** [comment]
Looks like not all files were uploaded for 5.0.1. To be fixed with the javadoc for next release.
