### ISSUE TITLE
Problem with migration to 4.2.6

### ISSUE THREAD

**Issue by fedeMarra** [owlcs/owlapi#561]
I use owl api 3.5.0 version and i would like to migrate to 4.x. I use Eclipse and for the dependency I use maven repository. For the migration I added/modified to my pom file these dependencies:
```
<!-- https://mvnrepository.com/artifact/net.sourceforge.owlapi/owlapi-distribution -->
	<dependency>
	    <groupId>net.sourceforge.owlapi</groupId>
	    <artifactId>owlapi-distribution</artifactId>
	    <version>4.2.6</version>
	</dependency>
    <!-- https://mvnrepository.com/artifact/net.sourceforge.owlapi/pellet-owlapi-ignazio1977 -->
	<dependency>
	    <groupId>net.sourceforge.owlapi</groupId>
	    <artifactId>pellet-owlapi-ignazio1977</artifactId>
	    <version>2.4.0-ignazio1977</version>
	</dependency>
	<!-- https://mvnrepository.com/artifact/org.slf4j/slf4j-simple -->
	<dependency>
	    <groupId>org.slf4j</groupId>
	    <artifactId>slf4j-simple</artifactId>
	    <version>1.7.21</version>
	</dependency>
```
For the test i use the tutorial SimpleHierarchyExample.java. But I have different warn and error.
`[main] WARN org.semanticweb.owlapi.util.SAXParsers - http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit not supported by parser type org.apache.xerces.jaxp.SAXParserImpl
[main] WARN org.semanticweb.owlapi.util.SAXParsers - entityExpansionLimit not supported by parser type org.apache.xerces.jaxp.SAXParserImpl
[main] WARN org.semanticweb.owlapi.util.SAXParsers - http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit not supported by parser type org.apache.xerces.jaxp.SAXParserImpl
[main] WARN org.semanticweb.owlapi.util.SAXParsers - entityExpansionLimit not supported by parser type org.apache.xerces.jaxp.SAXParserImpl

Exception in thread "main" java.lang.NullPointerException
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at KnowladgeBase.KB.SimpleHierarchyExample.main(SimpleHierarchyExample.java:115)
`

I tried different test but I can't to resolve. I do not know if I was right to migrate and I don't know if it's worth it. it's better if I stay at the 3 version?
Thanks for the help.

**Comment by ignazio1977** [comment]
The warnings depend on the XML parser - looks like you might have multiple versions on the classpath. Can you check the dependency hierarchy and report on all XML related libraries shown?

**Comment by ignazio1977** [comment]
The null pointer exception seems unrelated though. Is there a value for the reasoner class name in your version of the code?

**Comment by fedeMarra** [comment]
Thank you for the answer. For the first problem I resolved deleting the pellet dependency. But now if I want to use pellet as reasoner, how should I do? 
For the second problem the value for the reasonerFactoryClassName is equal to null as written in the code example.

**Comment by sesuncedu** [comment]
If pellet has a dependency on xerces, it needs to be removed. Also, I
thought that owlapi 4 compatibility had been merged into the main
complexible tree?

**Comment by fedeMarra** [comment]
@sesuncedu What is the maven repository for complexible tree? I couldn't to found this repo.  
Thanks.

**Comment by fedeMarra** [comment]
Sorry, you could report me what is the right version of Pellet for owl api 4? Where should I search the repository?

**Comment by ignazio1977** [comment]
My changes for owlapi 4 were merged but the owlapi version was rolled back to 3.5.x - at least that was the case a few months ago.

There is a Pellet fork called Openllet that uses owlapi 5. It is better supported than my fork (2.4.0-ignazio1977). You can find it here: http://search.maven.org/#search%7Cga%7C1%7COpenllet

The reasoner name must be changed from null to the actual class name of the OWLReasonerFactory that you plan to use - this is reasoner specific. I'm sure there's a comment to that effect.

**Comment by fedeMarra** [comment]
Thank you! I resolved the nullpointException. 
Now I try to use Openllet. Do you know if Openllet supports closed world assumption?

**Comment by ignazio1977** [comment]
It should the same way as Pellet does - with a configuration file, if I recall correctly.
