### ISSUE TITLE
I want to retrieve some specific values from an ontology.

### ISSUE THREAD

**Issue by Khansaka** [owlcs/owlapi#562]
What I need to do is retrieve some values from an ontology.

 I was research for weeks but I couldn’t found a way to accomplish my task
 I have attached the owl file(please get change the extension to .owl)
 I tried using Owl API but I was able only able to get class names and on property names.Below is a class that is available in the ontology. I need a java code to get  below mentioned sample output.  Please help me in this it will be a great help. Many thanks in Advance.

    <owl:Class rdf:about="http://www.semanticweb.org/ontologies/research/mid-review#Line">
        <rdfs:subClassOf>
            <owl:Restriction>
                <owl:onProperty rdf:resource="http://www.semanticweb.org/ontologies/research/mid-review#hasCharacterCount"/>
                <owl:someValuesFrom>
                    <rdfs:Datatype>
                        <owl:onDatatype rdf:resource="&xsd;integer"/>
                        <owl:withRestrictions rdf:parseType="Collection">
                            <rdf:Description>
                                <xsd:maxInclusive rdf:datatype="&xsd;integer">60</xsd:maxInclusive>
                            </rdf:Description>
                            <rdf:Description>
                                <xsd:minInclusive rdf:datatype="&xsd;integer">40</xsd:minInclusive>
                            </rdf:Description>
                        </owl:withRestrictions>
                    </rdfs:Datatype>
                </owl:someValuesFrom>
            </owl:Restriction>
        </rdfs:subClassOf>
        <rdfs:subClassOf>
            <owl:Restriction>
                <owl:onProperty rdf:resource="http://www.semanticweb.org/ontologies/research/mid-review#hasWordCount"/>
                <owl:someValuesFrom>
                    <rdfs:Datatype>
                        <owl:onDatatype rdf:resource="&xsd;integer"/>
                        <owl:withRestrictions rdf:parseType="Collection">
                            <rdf:Description>
                                <xsd:maxInclusive rdf:datatype="&xsd;integer">15</xsd:maxInclusive>
                            </rdf:Description>
                            <rdf:Description>
                                <xsd:minInclusive rdf:datatype="&xsd;integer">9</xsd:minInclusive>
                            </rdf:Description>
                        </owl:withRestrictions>
                    </rdfs:Datatype>
                </owl:someValuesFrom>
            </owl:Restriction>
        </rdfs:subClassOf>
    </owl:Class>

 sample output i need from above mentioned owl class
 class : - Line
 property- hasCharacterCount
 max -60
 min - 40
 
 property- hasWordCount
 max -15
 min - 9

[mid-review_v2.1.txt](https://github.com/owlcs/owlapi/files/510393/mid-review_v2.1.txt)

**Comment by ignazio1977** [comment]
This can be achieved as follows: (input is a string containing your ontology; replace with any other way to load an ontology)

        OWLOntologyManager m = OWLManager.createOWLOntologyManager();
        OWLOntology o = m.loadOntologyFromOntologyDocument(new StringDocumentSource(in));
        OWLClass line = m.getOWLDataFactory().getOWLClass(IRI.create(
            "http://www.semanticweb.org/ontologies/research/mid-review#Line"));
        for (OWLSubClassOfAxiom e : o.getSubClassAxiomsForSubClass(line)) {
            e.getSuperClass().accept(new OWLClassExpressionVisitorAdapter() {

                @Override
                public void visit(OWLDataSomeValuesFrom ce) {
                    System.out.println(ce.getProperty());
                    ce.getFiller().accept(new OWLDataRangeVisitor() {

                        @Override
                        public void visit(OWLDatatypeRestriction node) {
                            for (OWLFacetRestriction f : node.getFacetRestrictions()) {
                                System.out.println(f.getFacet() + " " + f.getFacetValue());
                            }
                        }

                        @Override
                        public void visit(OWLDataUnionOf node) {
                            // TODO Auto-generated method stub
                        }

                        @Override
                        public void visit(OWLDataIntersectionOf node) {
                            // TODO Auto-generated method stub
                        }

                        @Override
                        public void visit(OWLDataComplementOf node) {
                            // TODO Auto-generated method stub
                        }

                        @Override
                        public void visit(OWLDataOneOf node) {
                            // TODO Auto-generated method stub
                        }

                        @Override
                        public void visit(OWLDatatype node) {
                            // TODO Auto-generated method stub
                        }
                    });
                }
            });


In this version the visitor is inlined but you can create separate classes to reduce clutter.
