### ISSUE TITLE
Serialization Issues with 3.5.4 and 4.2.6

### ISSUE THREAD

**Issue by cbobed** [owlcs/owlapi#566]
Hi, 

I've found some problems when serialising OWLOntology instances. 

- In 3.5.4 version, the owlOntologyManager is serialized before the ontologyID and raises a nullPointer exception when trying to invoke hashCode exception. At first sight, it seems that moving the order of the declarations solves the problem, but it does not serialize the logical axioms correctly (the cloned ontology has 0 axioms). 
- In 4.2.6 version, the reordering at OWLImmutableOntology does not work (I cannot figure right now why). In my local repository, I've developed a workaround by adding a protected int hashCode which is initialized the first time is accessed, and a modified hashCode method which does not call directly the ontologyID hashCode(). It seems that this allows to serialize and clone already loaded/parsed ontologies, which cannot be done with the current version. 

Cheers, 
Carlos

**Comment by ignazio1977** [comment]
The fix is the same for both versions - a custom readObject/writeObject method is required.

**Comment by ignazio1977** [comment]
07f03b282a6af3edee96d950d7d753b278cd6633

6e5cd8188017c14f82eccb07907105b469a3f5a5

**Comment by ignazio1977** [comment]
I'm guessing the same problem exists in version 5

**Comment by ignazio1977** [comment]
3.5.5 and 4.2.7 have been released

**Comment by ignazio1977** [comment]
For version 5, the same bugs existing in version 4 need to be addressed. Also, AxiomWrapper needs to be made serializable.

**Comment by ignazio1977** [comment]
There seem to be no need for custom serialization/deserialization though. I believe the difference is the Java 8 compiler.
