### ISSUE TITLE
Incomplete Parsing of DifferentIndividuals with distinctMembers

### ISSUE THREAD

**Issue by alanruttenberg** [owlcs/owlapi#569]
[repl-thread] INFO org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFConsumer - Unparsed triple: _:genid109 -> http://www.w3.org/1999/02/22-rdf-syntax-ns#type -> http://www.w3.org/2002/07/owl#AllDifferent

**Comment by ignazio1977** [comment]
AllDifferent comes in two flavors: with members or distinctMembers.
The two variants are identical except for the tag name, but they were 
treated with two different handlers, one of which did not consume the 
type triple. Fixed by having one handler handle both versions.

**Comment by NashwaMohammed** [comment]
I have faced the same error. INFO org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFConsumer - Unparsed triple: http://www.w3.org/1999/02/22-rdf-syntax-ns#type -> http://www.semanticweb.org/nashwa/ontologies/Sketches#bus1 -> _:genid244

I am a new OWL user and don't know what I should do from the suggested answer. Could you please elaborate more?

**Comment by ignazio1977** [comment]
This was a bug, you shouldn't have to do anything. Which owlapi version are you using?

**Comment by NashwaMohammed** [comment]
Thanks for your reply. I am using owlapi 5.1.0

**Comment by ignazio1977** [comment]
It can't be the same problem then. Can you provide the ontology, or a part of it that includes the problem?

**Comment by NashwaMohammed** [comment]
Sorry, the ontology is still a work on progress and it's not mine. It's a part of work of my research group, in which I am a member and I don't have permission to send it. But I will try to explain what I want to do. 

Here is the list of errors I faced. I think there is a problem which I don't know in the way of describing some individuals.

1354 [main] INFO org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFConsumer - Unparsed triple: http://www.w3.org/1999/02/22-rdf-syntax-ns#type -> http://www.semanticweb.org/nashwa/ontologies/Sketches#bus1 -> _:genid244
1354 [main] INFO org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFConsumer - Unparsed triple: http://www.w3.org/1999/02/22-rdf-syntax-ns#type -> http://www.semanticweb.org/nashwa/ontologies/Sketches#bike1 -> _:genid236
1355 [main] INFO org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFConsumer - Unparsed triple: http://www.w3.org/1999/02/22-rdf-syntax-ns#type -> http://www.semanticweb.org/nashwa/ontologies/Sketches#house1 -> _:genid253
1355 [main] INFO org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFConsumer - Unparsed triple: http://www.w3.org/1999/02/22-rdf-syntax-ns#type -> http://www.semanticweb.org/nashwa/ontologies/Sketches#ntpp5 -> _:genid265
1355 [main] INFO org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFConsumer - Unparsed triple: http://www.w3.org/1999/02/22-rdf-syntax-ns#type -> http://www.semanticweb.org/nashwa/ontologies/Sketches#ntpp9 -> _:genid271
1355 [main] INFO org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFConsumer - Unparsed triple: http://www.w3.org/1999/02/22-rdf-syntax-ns#type -> http://www.semanticweb.org/nashwa/ontologies/Sketches#ntpp6 -> _:genid268
1355 [main] INFO org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFConsumer - Unparsed triple: http://www.w3.org/1999/02/22-rdf-syntax-ns#type -> http://www.semanticweb.org/nashwa/ontologies/Sketches#wh1 -> _:genid274
1355 [main] INFO org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFConsumer - Unparsed triple: http://www.w3.org/1999/02/22-rdf-syntax-ns#type -> http://www.semanticweb.org/nashwa/ontologies/Sketches#wh2 -> _:genid278
1355 [main] INFO org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFConsumer - Unparsed triple: http://www.w3.org/1999/02/22-rdf-syntax-ns#type -> http://www.semanticweb.org/nashwa/ontologies/Sketches#ntpp10 -> _:genid262


I am going to give you the description of some individuals and maybe the same problem applies for others.

For example, the individuals ntpp5, ntpp6, ntpp9, and ntpp10 have the same form of description like the following:
ntpp5 is of type NTPP and to only({st2}) and there is an object property assertion to st2. The same applies for the others by changing the name of the individual st2 to whatever.


Thanks a lot, your help are highly appreciated.

**Comment by ignazio1977** [comment]
Unfortunately that's not enough to identify the bug. Looks like there is an anonymous individual used in place of a class, but I cannot tell more, or whether it's a bug or missing data.
