### ISSUE TITLE
Order of RDF triples affects annotation parsing

### ISSUE THREAD

**Issue by balhoff** [owlcs/owlapi#574]
I've noticed that when parsing ontologies in RDF turtle format, ontology annotation triples that come before the `rdf:type owl:Ontology` triple are lost. Is there supposed to be such a dependence on the order of RDF triples? I will attach an example via pull request.

**Comment by ansell** [comment]
No, it isn't supposed to be order dependent. However, there are some parts of the parser that support streaming, and may have some incorrect assumptions right now as to whether they should delay parsing of triples or parse them when they first receive them.

**Comment by balhoff** [comment]
Thanks, both of you!
