### ISSUE TITLE
Problem Tagging an .OWL File in Java

### ISSUE THREAD

**Issue by ZakiaSalod** [owlcs/owlapi#578]
Hi All,

I am retrieving my .OWL Ontology file in Java using the Jena API.

I have a string called for example >>>
String str1 = "Organism bacteria tb virus HIV"

I am then checking my Ontology (looping and getting names of classes and subclasses) if my class or subclass name is any of the above terms, for example, if I have a class in my Ontology named "bacteria", then I want to replace the above str1 string's "bacteria" with "< bacteria >bacteria< / bacteria >". However, my replace doesn't seem to be working.

I have it as follows >>>
`OntClass ontologyClass = (OntClass) classes.next();
String ontologyClassStr = ontologyClass.getLocalName().toString();
if (str1.toLowerCase().contains(ontologyClassStr.toString().toLowerCase())) {
str1= str1.trim().replace(ontologyClassStr.toString().trim(), "<"+ontologyClassStr.toString().trim()+">" + ontologyClassStr.toString().trim() + "</"+ontologyClassStr.toString().trim()+">");
}`

Please help. I have "toString()" the Ontology class name, so I don't see why it is not working.
After the above runs, and I display the output is still the following >>>
Organism bacteria tb virus HIV

I want it to be >>>
Organism < bacteria >bacteria< / bacteria > tb virus HIV

Thanks in advance for the help.
Zakia

**Comment by sesuncedu** [comment]
>I am retrieving my .OWL Ontology file in Java using the Jena API.

This is the **OWLAPI** issue tracker; from the description this does not appear to be an OWLAPI bug...( BTW, Jena OWL support is limited and rather outdated. Migrating to OWLAPI may be a net win, depending on how heavily committed you are to other parts of the Jena codebase.) 

If this *were* a Jena support forum, I would still not be able to definitively answer your question, but as a hint would suggest that you look to see what Jena thinks the value of localName is.  I'm being vague in case this is a student project where there may be an honour code limiting the amount of assistance permissible. If this is for a commercial project, then I would be glad to offer contract support.
