### ISSUE TITLE
Imports not properly loaded after all ontologies removed

### ISSUE THREAD

**Issue by ykazakov** [owlcs/owlapi#580]
Create a test Java project and place these two ontologies into the resources folder:

`A.owl`:
```owl
Prefix(owl:=<http://www.w3.org/2002/07/owl#>)
Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>)
Prefix(xml:=<http://www.w3.org/XML/1998/namespace>)
Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>)
Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>)
Prefix(:=<http://www.example.com#>)

Ontology(<http://www.example.com#A>

Import(<http://www.example.com#B>)

SubClassOf(:A :B) # <= any axiom is OK

)
```

`B.owl`:

```owl
Prefix(owl:=<http://www.w3.org/2002/07/owl#>)
Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>)
Prefix(xml:=<http://www.w3.org/XML/1998/namespace>)
Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>)
Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>)
Prefix(:=<http://www.example.com#>)

Ontology(<http://www.example.com#B>

SubClassOf(:B :C) # <= any axiom is OK

)
```

The following test fails for me with OWLAPI 4.2.7 :

```java
import static org.junit.Assert.assertEquals;

import java.io.File;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.Collections;

import org.junit.Test;
import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;
import org.semanticweb.owlapi.model.OWLOntologyCreationException;
import org.semanticweb.owlapi.model.OWLOntologyIRIMapper;
import org.semanticweb.owlapi.model.OWLOntologyManager;

public class TestImports {

	@Test
	public void testImports() throws Exception {
		OWLOntologyManager man = OWLManager.createOWLOntologyManager();
		OWLOntology root = loadOntology(man, "A.owl");
		assertEquals(1, root.getImports().size()); // <= OK
		for (OWLOntology ontology : man.getOntologies()) {
			man.removeOntology(ontology);
		}
		assertEquals(0, man.getOntologies().size()); // <= no ontologies left!
		root = loadOntology(man, "A.owl");
		assertEquals(1, root.getImports().size()); // <= FAIL!
	}

	private OWLOntology loadOntology(OWLOntologyManager man, String name)
			throws URISyntaxException, OWLOntologyCreationException {

		final URI ontologyRoot = getClass().getClassLoader().getResource("")
				.toURI();

		OWLOntologyIRIMapper iriMapper = new TestIRIMapper(
				ontologyRoot.toString());

		man.setIRIMappers(Collections.singleton(iriMapper));

		final URI mainOntology = getClass().getClassLoader().getResource(name)
				.toURI();

		return man.loadOntologyFromOntologyDocument(new File(mainOntology));

	}

	static class TestIRIMapper implements OWLOntologyIRIMapper {
		private static final long serialVersionUID = 1L;

		final String root;

		TestIRIMapper(String root) {
			this.root = root;
		}

		@Override
		public IRI getDocumentIRI(IRI ontologyIRI) {
			return IRI.create(root + "/" + ontologyIRI.getShortForm() + ".owl");
		}
	}

}
```

It seems that after A.owl is initially loaded (with the import B.owl) and the ontologies are removed from the manager, loading of A.owl does not resulting in loading of the imported ontology B.owl any longer.

Background: I am trying to reuse one instance of OWLOntologyManager in JUnit tests. After test is finished, I just remove all ontologies from the manager. This is, generally, faster than creating a new OWLOntologyManager. However, the behaviour seems to be incorrect. 

Is there any better way of clearing OWLOntologyManager that I may miss?

**Comment by sesuncedu** [comment]
Not sure if this is a typo in the bug report?

Import(<http://www.example.com#B <http://www.example.com/#B>>)

But

Ontology(<http://www.example.com/B>

**Comment by ignazio1977** [comment]
Creating fresh managers is slow because of Guice injection. A workaround is shown in the base test class for owlapi unit tests - basically reuse the lists of parsers and storers from one instance.

**Comment by ykazakov** [comment]
Simon, good point! I fixed the typos and retested with the same outcomes.
Actually, I wonder if OWLAPI really checks that the imported ontology has the same IRI as in the import declaration. If I replace the ontology IRI of B.owl with something completely different, it still report that A.owl has one import in the first assert.

Ignazio, thanks for the pointer to OWL API unit tests. I'll take a look.

**Comment by ykazakov** [comment]
@ignazio1977 just to double check: do you mean [this base test class](https://github.com/owlcs/owlapi/blob/f701672d2bc82eec129c53d6cccfb2e8aa32c83b/contract/src/test/java/org/semanticweb/owlapi/api/test/baseclasses/TestBase.java)?

**Comment by ignazio1977** [comment]
Yes. setupManager() is the method initialising the required lists.

One limitation of that approach is that the code will behave differently if other injected fields are added - so it's something to check when updating versions.

**Comment by ykazakov** [comment]
Thanks!
It would be useful to have this base test class distributed with owl-api so that one can always inherit this class in unit tests.
Actually, even more useful would be if `OWLManager.createOWLOntologyManager()` would create a manager just like in `setupManager()`. Would it be possible?

**Comment by ignazio1977** [comment]
I've not given it enough thought, it could just be that we're doing something inefficient with the Guice injectors.

The main problem is ensuring class path updates do not invalidate cached managers. For unit tests this is not a concern, usually, but a public method might start being misused, so I need to be sure.

**Comment by ykazakov** [comment]
From profiling it seems like creating an injector (`Guice.createInjector()`) takes most of the time (due to calls to `Throwable.getStackTrace()`).
However, looking at [OWLManager](https://github.com/owlcs/owlapi/blob/master/apibinding/src/main/java/org/semanticweb/owlapi/apibinding/OWLManager.java), it seems that there are only two injectors needed: one for `Concurrency.CONCURRENT` and another one for `Concurrency.NON_CONCURRENT`. Why not to cache them? Do you mean it is not safe to cache them because somehow the class path can change during the runtime?? But then, would't it be unsafe to cache essentially any value like ontologies or reasoners?

BTW, have you been able to reproduce the problem in the test above?

**Comment by ignazio1977** [comment]
I've replicated the problem, and what happens is that not all sets containing IRIs/ontology ids are cleared correctly. Specifically, the first offending set is importedIRIs, which has a list of the IRIs for which importing has been tried already; when an ontology is loaded multiple times, or cannot be loaded, this set stops multiple parsing attempts for the same import.

Unfortunately, not cleaning it up when removing an ontology means that, if the imported ontology is removed, it won't be parsed again with that manager.

There is a workaround: use OWLOntologyManager::clearOntologies() - this also clears the imported ontologies set.

**Comment by ignazio1977** [comment]
About classpath changes, the real issue is storers and parsers - these are meant to be added and removed by just being present on the classpath (via ServiceLoader), and when running as OSGi classpath changes are possible. Not necessarily likely, though: the worst situation would be a parser that was seen but has since been removed, where we'd get a class not found exception.

**Comment by ignazio1977** [comment]
cherry pick on version 4 on the way

**Comment by ignazio1977** [comment]
Performance issue: a large part of the issue with the injector is that Guice by default 'includes stack traces' - I believe to use in error reports - and this takes a lot of time. Setting that value to OFF before creating the injector reduces time on my machine from 2.3 seconds to 1.5.

This is for the first manager created. Subsequent managers take 50 to 100 milliseconds to create, so not really worth optimizing.

There is more to be gained, though. The expensive module is `OWLAPIServiceLoaderModule`, which is also the only one sensitive to expected classpath changes. Most of the time is spent loading classes and adding them to the injector, but collecting the class names seems fast. If the class names do not change between runs, we know the injector can be reused; however this does not help with the first load.

However, currently the injector loads all classes that could ever be used - all parsers and all storers. Not all of them are necessarily used - for example, for a manager used only to parse RDF/XML, only one class loaded is actually used. This suggests that instead of injecting classes the injector could merely inject class names, to be instantiated lazily when needed. This requires a few changes to OWLOntologyManager though.

**Comment by sesuncedu** [comment]
Another approach would be to make the injector injectable... Using slf4j
style static binding to make the whole configuration system replaceable.

There are definite advantages to doing things this way on android. It's
also possible to get some use out of OSGI, which jigsaw keeps making look
better :)

**Comment by ignazio1977** [comment]
Far from me to promote a recursive solution, but in this case the injector is injectable - or, to be more precise, there is nothing magic about OWLManager. The whole apibinding module can be skipped, and OWLManager replaced with another initialization class (with or without injectors).
Rather than complicating the injection strategy, I'd rather go down that route and provide a builder for explicit, manual injection.

**Comment by matthewhorridge** [comment]
Consider replacing Guice with Dagger (which doesn't use reflection and has better performance - it's quite nice)

**Comment by ansell** [comment]
+1 on the Jigsaw comment with it adding service advertisements to the module system which should speed performance up significantly for these use cases:

http://openjdk.java.net/projects/jigsaw/quick-start#services

**Comment by ignazio1977** [comment]
The same fix on version 4 works about 30% better than on version 5 - pleasant but unexplained.

Cheers for the Dagger reference and the other suggestions, all useful for future work.
