### ISSUE TITLE
Apache Harmoony SAX parser not supported

### ISSUE THREAD

**Issue by BatuhanKaratas** [owlcs/owlapi#581]
I'm using Android Studio 2.2.2 and my purpose is using OWL API in Android application. Exception is displayed as;

> org.semanticweb.owlapi.model.OWLRuntimeException: org.xml.sax.SAXNotRecognizedException: http://apache.org/xml/features/nonvalidating/load-external-dtd

in log records. This problem always shows up while the ontology is loading. I used owlapi-distribution-4.2.3 and its dependencies are;

`
- roboguice-4.0.0.jar
- jfact-4.0.0.jar,
 

- guice-4.0.jar

- javax.inject-1.jar

- slf4j-api-1.7.21.jar

- guava-18.0.jar

- guice-assistedinject-4.0.jar

- aopalliance-1.0.jar

- guice-multibindings-4.0.jar

- slf4j-log4j12-1.7.21.jar

- log4j-1.2.17.jar

- jsr305-3.0.1.jar

- semargl-core-0.6.1.jar

- semargl-rdf-0.6.1.jar

- semargl-rdfa-0.6.1.jar

- semargl-sesame-0.6.1.jar

- sesame-model-2.7.16.jar
- sesame-rio-api-2.7.16.jar
- sesame-rio-binary-2.7.16.jar
- sesame-rio-datatypes-2.7.16.jar
- sesame-rio-languages-2.7.16.jar
- sesame-rio-n3-2.7.16.jar
- sesame-rio-nquads-2.7.16.jar
- sesame-rio-ntriples-2.7.16.jar
- sesame-rio-rdfjson-2.7.16.jar
- sesame-rio-rdfxml-2.7.16.jar
- sesame-rio-trig-2.7.16.jar

- sesame-rio-trix-2.7.16.jarsesame
- rio-turtle-2.7.16.jar
- sesame-util-2.7.16.jar
- jsonld-java-0.5.0.jar
- jsonld-java-sesame-0.5.0.jar
- trove4j-3.0.3.jar
- commons-codec-1.6.jar
- commons-io-2.4.jar
- httpclient-4.2.5.jar
- httpclient-cache-4.2.5.jar
- httpcore-4.2.4.jar
- jackson-annotations-2.5.1.jar
- jackson-core-2.5.1.jar
- jackson-databind-2.5.1.jar
- jcl-over-slf4j-1.7.21.jar
- xz-1.5.jar
- owlapi-distribution-4.2.3.jar

`

I implemented this code. This code contains some ontology loading combinations.

` 
import android.os.AsyncTask;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.TextView;
import android.widget.Toast;
import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.io.StringDocumentSource;
import org.semanticweb.owlapi.model.AddImport;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLOntology;
import org.semanticweb.owlapi.model.OWLOntologyChange;
import org.semanticweb.owlapi.model.OWLOntologyCreationException;
import org.semanticweb.owlapi.model.OWLOntologyManager;
import org.semanticweb.owlapi.model.OWLOntologyStorageException;
import org.semanticweb.owlapi.reasoner.InferenceType;
import org.semanticweb.owlapi.reasoner.Node;
import org.semanticweb.owlapi.reasoner.OWLReasoner;
import org.semanticweb.owlapi.reasoner.OWLReasonerConfiguration;
import org.semanticweb.owlapi.reasoner.OWLReasonerFactory;
import org.semanticweb.owlapi.reasoner.SimpleConfiguration;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

import uk.ac.manchester.cs.jfact.JFactFactory;

public class MainActivity extends AppCompatActivity
{
    static OWLReasoner reasoner = null;
    static OWLOntology pizzaOntology = null;

    static String input = "<?xml version=\"1.0\"?>\n"
            + "<rdf:RDF xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n"
            + "     xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
            + "     xmlns:xsd=\"http://www.w3.org/2001/XMLSchema#\"\n"
            + "     xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\">\n"
            + "    <owl:Ontology rdf:about=\"http://www.semanticweb.org/fake/ontologies/2012/8/1\">\n"
            + "        <owl:imports rdf:resource=\"http://www.bbc.co.uk/news/\"/>\n"
            + "    </owl:Ontology>\n" + "</rdf:RDF>";

    @Override
    protected void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        ((Button) findViewById(R.id.isConsistentButton)).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                new ConsistentCheckOntologyOperation().execute((Void) null);
            }
        });
    }

    private class ConsistentCheckOntologyOperation extends AsyncTask<Void, Void, Void> {

        @Override
        protected void onPreExecute() {
            super.onPreExecute();
            reasoner = null;
            pizzaOntology = null;
            TextView myAwesomeTextView = (TextView) findViewById(R.id.ontologyResultContent);
            myAwesomeTextView.setText("");
        }

        @Override
        protected Void doInBackground(Void... params) {
            OWLOntologyManager manager = OWLManager.createOWLOntologyManager();

            try {
                IRI iri = IRI.create("http://protege.stanford.edu/ontologies/pizza/pizza.owl");
                IRI iri2 = IRI.create("http://owl.cs.manchester.ac.uk/co-ode-files/ontologies/pizza.owl");

                /*
                InputStream is = null;
                try {
                    is = getAssets().open("pizza.owl");
                    pizzaOntology = manager.loadOntologyFromOntologyDocument(is);
                } catch (IOException e) {
                    ;
                }
                */

                // pizzaOntology = manager.loadOntologyFromOntologyDocument(new StringDocumentSource(input));
                pizzaOntology = manager.loadOntologyFromOntologyDocument(iri);

            } catch (Exception e) {
                Log.d("OntologyConnectionError", e.getMessage());
            }

            return null;
        }

        @Override
        protected void onPostExecute(Void result) {

        }

        @Override
        protected void onProgressUpdate(Void... values) {}
    }
}`

The exception occurs when loadOntologyFromOntologyDocument method is called.

I investigated and tried a lot of possibilities ( rdf format ontology, different owl api version ( owlapi-osgidistribution-4.2.6.jar ), using gradle for owl api dependencies) but the result is not changed.

**Comment by ignazio1977** [comment]
The sax parser factory throws this exception when the javax.xml.SAXParserFactory.newInstance() method returns a factory instance that does not support `http://apache.org/xml/features/nonvalidating/load-external-dtd`.

Can you find out the class being provided by your setup (for example by printing out the value of javax.xml.SAXParserFactory.newInstance().getClass().getName()) and paste it here?

**Comment by BatuhanKaratas** [comment]
Android Studio gave "javax.xml.SAXParserFactory" pattern is not found. Therefore, I wrote this; "javax.xml.parsers.SAXParserFactory.newInstance().getClass().getName()" and the output is "org.apache.harmony.xml.parsers.SAXParserFactoryImpl".

**Comment by ignazio1977** [comment]
Changing to `getFeature()` will not help in this case; the main problem is that the harmony sax parser factory does not support some properties that the OWLAPI uses. This one in particular should not stop parsing but might make it quite slow.

However this will require a modification to the OWLAPI and a new version.

**Comment by ansell** [comment]
Rio parsers have the entity expansion bug handled by default using the following setting so they shouldn't be vulnerable:

https://docs.oracle.com/javase/6/docs/api/javax/xml/XMLConstants.html#FEATURE_SECURE_PROCESSING

https://bitbucket.org/openrdf/sesame/src/11f1f0e681cea47e167bd79929873370e199a19f/core/rio/api/src/main/java/org/openrdf/rio/helpers/XMLParserSettings.java?at=2.7.x&fileviewer=file-view-default#XMLParserSettings.java-38
