### ISSUE TITLE
Documentation for CLI for using owlapi?

### ISSUE THREAD

**Issue by darrenleeweber** [owlcs/owlapi#582]
Where is the documentation for a CLI to use the owlapi?  Could this be noted on the main README page for this repository?

**Comment by ignazio1977** [comment]
The OWL API is a library and has no command line interface. Can you provide more details on what you're planning to achieve?

**Comment by darrenleeweber** [comment]
This question is motivated by wanting to validate an ontology with a recent version of the owlapi.  There is a web service at http://mowl-power.cs.man.ac.uk:8080/validator/, but it is using ver 3.4.5 of the owlapi.  There must be a CLI for using owlapi ver 5.x to do an ontology validation, right?

**Comment by darrenleeweber** [comment]
I want to validate whether http://id.loc.gov/ontologies/bibframe.rdf is an OWL-2-DL ontology.

**Comment by matthewhorridge** [comment]
Take a look at https://github.com/ontodev/robot, it might be able to do what you want.

**Comment by darrenleeweber** [comment]
`robot help` should be the answer to everything ;-)

**Comment by darrenleeweber** [comment]
Although `robot` might be outdated too, i.e. it's on 4.x of the owlapi
https://github.com/ontodev/robot/blob/master/pom.xml#L62-L66

**Comment by sesuncedu** [comment]
I'm pretty sure that it wasn't, but that may have changed.
At least it now has the concept of a particular copy of a book.

**Comment by darrenleeweber** [comment]
The `robot help` is kinda terse:
```
robot help
usage: robot [command] [options] <arguments>
 -h,--help                  print usage information
 -noprefixes                do not use default prefixes
 -p,--prefix <arg>          add a prefix 'foo: http://bar'
 -P,--prefixes <arg>        use prefixes from JSON-LD file
 -V,--version               print version information
 -v,--verbose               increased logging
 -vv,--very-verbose         high logging
 -vvv,--very-very-verbose   maximum logging
 -x,--xml-entities          use entity substitution with ontology XML
                            output
commands:
 help            print help for command
 annotate        annotate ontology
 convert         convert ontology
 diff            find the differences between two ontologies
 export-prefixes export prefixes to a file
 extract         extract terms from an ontology
 filter          filter ontology axioms
 materialize     materialize ontology
 merge           merge ontologies
 query           query an ontology
 reason          reason ontology
 reduce          reduce ontology
 relax           relax ontology
 template        build an ontology from a template
```

**Comment by darrenleeweber** [comment]
Also reviewed the doc at https://github.com/ontodev/robot/blob/master/examples/README.md but nothing leaps out as a validation tool there.  I'll start a discussion there to see what happens.

**Comment by ignazio1977** [comment]
> There must be a CLI for using owlapi ver 5.x to do an ontology validation

That's outside the scope of a library - it could be done as a dependent project, but I'm not aware of one existing.

However, for this particular use case you only need a few lines of code to implement the functionality:

    OWLOntologyManager m = OWLManager.createOWLOntologyManager();
    OWLOntology onto = m.loadOntology(IRI.create("http://id.loc.gov/ontologies/bibframe.rdf"));
    OWLProfileReport checkOntology = Profiles.OWL2_DL.checkOntology(onto);
    if (!checkOntology.isInProfile()) {
        checkOntology.getViolations().forEach(System.out::println);
    }


The results, for your ontology, are too many for this comment. However, reducing only to violation name and entity, they look like this:

    <http://www.w3.org/2004/02/skos/core#hasTopConcept> org.semanticweb.owlapi.profiles.violations.UseOfUndeclaredAnnotationProperty
    <http://id.loc.gov/vocabulary/relators/role> org.semanticweb.owlapi.profiles.violations.UseOfUndeclaredObjectProperty
    <http://purl.org/dc/terms/modified> org.semanticweb.owlapi.profiles.violations.UseOfUndeclaredAnnotationProperty
    <http://www.w3.org/2004/02/skos/core#notation> org.semanticweb.owlapi.profiles.violations.UseOfUndeclaredAnnotationProperty
    <http://www.loc.gov/mads/rdf/v1#hasTopMemberOfMADSScheme> org.semanticweb.owlapi.profiles.violations.UseOfUndeclaredAnnotationProperty
    <http://www.w3.org/2004/02/skos/core#definition> org.semanticweb.owlapi.profiles.violations.UseOfUndeclaredAnnotationProperty
    <http://www.loc.gov/mads/rdf/v1#code> org.semanticweb.owlapi.profiles.violations.UseOfUndeclaredAnnotationProperty
    <http://purl.org/dc/elements/1.1/contributor> org.semanticweb.owlapi.profiles.violations.UseOfUndeclaredObjectProperty
    <http://www.w3.org/2004/02/skos/core#prefLabel> org.semanticweb.owlapi.profiles.violations.UseOfUndeclaredAnnotationProperty
    <http://www.loc.gov/mads/rdf/v1#Topic> org.semanticweb.owlapi.profiles.violations.UseOfUndeclaredClass
    rdfs:Resource org.semanticweb.owlapi.profiles.violations.UseOfUndeclaredClass
    <http://www.loc.gov/mads/rdf/v1#authoritativeLabel> org.semanticweb.owlapi.profiles.violations.UseOfUndeclaredAnnotationProperty
    rdfs:Resource org.semanticweb.owlapi.profiles.violations.UseOfReservedVocabularyForClassIRI
    <http://www.loc.gov/mads/rdf/v1#Authority> org.semanticweb.owlapi.profiles.violations.UseOfUndeclaredClass
    <http://www.w3.org/2004/02/skos/core#Concept> org.semanticweb.owlapi.profiles.violations.UseOfUndeclaredClass
    <http://www.loc.gov/mads/rdf/v1#MADSCollection> org.semanticweb.owlapi.profiles.violations.UseOfUndeclaredClass
    <http://www.loc.gov/mads/rdf/v1#hasMADSSchemeMember> org.semanticweb.owlapi.profiles.violations.UseOfUndeclaredAnnotationProperty
    <http://purl.org/dc/elements/1.1/publisher> org.semanticweb.owlapi.profiles.violations.UseOfUndeclaredObjectProperty
    <http://id.loc.gov/vocabulary/relators/lei> org.semanticweb.owlapi.profiles.violations.UseOfUndeclaredObjectProperty
    <http://www.loc.gov/mads/rdf/v1#MADSScheme> org.semanticweb.owlapi.profiles.violations.UseOfUndeclaredClass
    <http://purl.org/dc/elements/1.1/creator> org.semanticweb.owlapi.profiles.violations.UseOfUndeclaredObjectProperty
    <http://xmlns.com/foaf/0.1/Agent> org.semanticweb.owlapi.profiles.violations.UseOfUndeclaredClass
    <http://purl.org/dc/elements/1.1/subject> org.semanticweb.owlapi.profiles.violations.UseOfUndeclaredObjectProperty
    <http://www.w3.org/2004/02/skos/core#ConceptScheme> org.semanticweb.owlapi.profiles.violations.UseOfUndeclaredClass

**Comment by darrenleeweber** [comment]
Thanks for the code tip.  Resolved this in https://github.com/ontodev/robot/issues/117
