### ISSUE TITLE
Issue with serialization - OWLAPI version 3.5.5

### ISSUE THREAD

**Issue by cbobed** [owlcs/owlapi#586]
Hi, 
it seems that some fields of the inner structures might not be being correctly serialized. When asking for the number of logical axioms of a cloned ontology, it returns 0, while it seems that it has completely cloned the axiom sets. 

I've checked out that this does not happen with OWLAPI version 4.2.7. 

Cheers, 

The ouput: 

> Original Axiom count: 4756
> Original Logical Axiom count: 4280
> Cloned Axiom count: 4756
> Cloned Logical Axiom count: 0
> true

The code: 
```
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.OWLOntology;
import org.semanticweb.owlapi.model.OWLOntologyManager;

public class OWLOntologySerializationTest {
	
	public static void main(String[] args) {
		OWLOntologyManager om = OWLManager.createOWLOntologyManager(); 
		OWLOntology ont = null;
		
		try{		
			ont = om.loadOntologyFromOntologyDocument(new File(args[0]));
			
			ByteArrayOutputStream bos = new ByteArrayOutputStream();
	        ObjectOutputStream out = new ObjectOutputStream(bos);
	        out.writeObject(ont);
	 
	        //De-serialization of object
	        ByteArrayInputStream bis = new   ByteArrayInputStream(bos.toByteArray());
	        ObjectInputStream in = new ObjectInputStream(bis);
	        OWLOntology ont2 = (OWLOntology) in.readObject();
	        
	        System.out.println("Original Axiom count: "+ont.getAxiomCount()); 
	        System.out.println("Original Logical Axiom count: "+ont.getLogicalAxiomCount()); 
	        System.out.println("Cloned Axiom count: "+ont2.getAxiomCount()); 
	        System.out.println("Cloned Logical Axiom count: "+ont2.getLogicalAxiomCount()); 
	        System.out.println(ont.getAxioms().containsAll(ont2.getAxioms()) && ont2.getAxioms().containsAll(ont.getAxioms())); 

		}
		catch (Exception e) {
			e.printStackTrace(); 
		}
	}
}
```

**Comment by cbobed** [comment]
I've changed the title as it is not a minor issue ... if you build a reasoner over a cloned ontology, you don't get the same results. It seems that it takes every element in the ontology as an individual, and therefore the reasoning is not well performed anymore. 

It might be important as there are some reasoners that are still using this version. 

Cheers,

**Comment by ignazio1977** [comment]
Bad AxiomType - deserialized AxiomTypes did not have the same hash code, therefore could not be found in the maps, even when the axioms were all there.
