### ISSUE TITLE
how to use imported ontologies

### ISSUE THREAD

**Issue by zzw95** [owlcs/owlapi#587]
Hi,
I import two ontologies (family and familyA) to a new ontology (map), but I don't know how to use these imported ontologies. And when I open the map.owl , there is nothing except import declarations.
(If I use Protege to import ontologies, the classes,individuals,properties are automatically imported).
Cheers.

Code:
```
OWLOntologyManager m=OWLManager.createOWLOntologyManager();
    	File owlFile = new File("C:\\Users\\zzw\\Desktop\\Ontology\\map.owl");
    	File file1 = new File("C:\\Users\\zzw\\Desktop\\Ontology\\family.owl");
    	File file2 = new File("C:\\Users\\zzw\\Desktop\\Ontology\\familyA.owl");
    	
    	IRI iri1= IRI.create("http://semanticweb.org/zzw/ontologies/2016/10/family");
    	IRI iri2= IRI.create("http://semanticweb.org/zzw/ontologies/2016/11/familyA");
    	m.getIRIMappers().add(new SimpleIRIMapper(iri1, IRI.create("C:\\Users\\zzw\\Desktop\\Ontology\\family.owl")));
    	m.getIRIMappers().add(new SimpleIRIMapper(iri2, IRI.create("C:\\Users\\zzw\\Desktop\\Ontology\\familyA.owl")));
    	OWLOntology onto1=m.loadOntologyFromOntologyDocument(file1);
    	OWLOntology onto2=m.loadOntologyFromOntologyDocument(file2);
    	OWLOntology onto=m.loadOntologyFromOntologyDocument(owlFile);
    	IRI iri=onto.getOntologyID().getOntologyIRI().get();
    	
    	OWLDataFactory factory=m.getOWLDataFactory();
    	OWLImportsDeclaration importDeclaration1 = factory.getOWLImportsDeclaration(iri1);
    	OWLImportsDeclaration importDeclaration2 = factory.getOWLImportsDeclaration(iri2);
    	AddImport addImport1=new AddImport(onto, importDeclaration1);
    	AddImport addImport2=new AddImport(onto, importDeclaration2);
    	m.saveOntology(onto);
```

**Comment by ignazio1977** [comment]
> when I open the map.owl , there is nothing except import declarations.

That's correct behaviour. The imports mean that you do not have to declare the classes and properties described in the imported ontologies before creating axioms in the new ontology.

In order to use them, you just create axioms using those classes and properties. Reasoners will take into account your new axioms and the ones in the imported ontology.

> (If I use Protege to import ontologies, the classes,individuals,properties are automatically imported).

I'm not sure what you mean here.

**Comment by zzw95** [comment]
I mean that if there is a class People in family.owl and a class PeopleA in familyA.owl,  and map.owl imports family and familyA . Then in Protege People and PeopleA are automatically loaded, so I can run SWRL rule
"People(?p) -> PeopleA(?p)" successfully.
![image](https://cloud.githubusercontent.com/assets/23278066/21006277/240e9b0a-bd73-11e6-886c-91fe32875733.png)

But in Java ,there is an exception like "Exception in thread "main" org.swrlapi.parser.SWRLParseException: Invalid SWRL atom predicate 'A'".
```
     
        SWRLRuleEngine swrlRuleEngine = SWRLAPIFactory.createSWRLRuleEngine(ontology);
        swrlRuleEngine.createSWRLRule("rule1", "People(?p)->PeopleA(?p)");
        SQWRLQueryEngine queryEngine = SWRLAPIFactory.createSQWRLQueryEngine(ontology);
        String query="People(?p)->sqwrl:select(?p)";
        SQWRLResult result= queryEngine.runSQWRLQuery("output",query);
        System.out.println(result.toString());;

```

**Comment by zzw95** [comment]
I mean that if there is a class People in family.owl and a class PeopleA in familyA.owl, and map.owl imports family and familyA . Then in Protege People and PeopleA are automatically loaded, so I can run SWRL rule
"People(?p) -> PeopleA(?p)" successfully.
![image](https://cloud.githubusercontent.com/assets/23278066/21006523/38007c4a-bd74-11e6-831e-4cb7ca912d7d.png)


But in Java ,there is an exception like "Exception in thread "main" org.swrlapi.parser.SWRLParseException: Invalid SWRL atom predicate 'A'".

     ```

        SWRLRuleEngine swrlRuleEngine = SWRLAPIFactory.createSWRLRuleEngine(ontology);
        swrlRuleEngine.createSWRLRule("rule1", "People(?p)->PeopleA(?p)");
        SQWRLQueryEngine queryEngine = SWRLAPIFactory.createSQWRLQueryEngine(ontology);
        String query="People(?p)->sqwrl:select(?p)";
        SQWRLResult result= queryEngine.runSQWRLQuery("output",query);
        System.out.println(result.toString());;
```

**Comment by ignazio1977** [comment]
That's down to the swrlapi being able to resolve PeopleA to the correct IRI. This depends on the correct prefixes being found - however the code for that is in the swrlapi not the owlapi.

You can try to use the full IRI rather than the shortened version to see if that resolves the problem.

**Comment by csnyulas** [comment]
There is an issue opened on the SWRL API repository for this (protegeproject/swrlapi#25), so I think we can close this one here.
