### ISSUE TITLE
Tomcat ThreadLocal memory leak warning

### ISSUE THREAD

**Issue by ansell** [owlcs/owlapi#6]
What is the best way to remove the IRI ThreadLocal<WeakCache> to avoid memory leaks?

I am receiving the following warnings when I reload a context in Tomcat-7.

May 20, 2013 3:39:08 PM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [/podd] created a ThreadLocal with key of type [org.semanticweb.owlapi.model.IRI$1](value [org.semanticweb.owlapi.model.IRI$1@62a11cb0]) and a value of type [org.semanticweb.owlapi.util.WeakCache](value [org.semanticweb.owlapi.util.WeakCache@3f629966]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
May 20, 2013 3:39:08 PM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [/podd] created a ThreadLocal with key of type [uk.ac.manchester.cs.owl.owlapi.OWLDataFactoryInternalsImpl$1](value [uk.ac.manchester.cs.owl.owlapi.OWLDataFactoryInternalsImpl$1@6245180c]) and a value of type [org.semanticweb.owlapi.util.WeakCache](value [org.semanticweb.owlapi.util.WeakCache@262dee3b]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
May 20, 2013 3:39:08 PM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [/podd] created a ThreadLocal with key of type [org.semanticweb.owlapi.model.IRI$1](value [org.semanticweb.owlapi.model.IRI$1@62a11cb0]) and a value of type [org.semanticweb.owlapi.util.WeakCache](value [org.semanticweb.owlapi.util.WeakCache@11737712]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
May 20, 2013 3:39:08 PM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [/podd] created a ThreadLocal with key of type [org.semanticweb.owlapi.model.IRI$1](value [org.semanticweb.owlapi.model.IRI$1@62a11cb0]) and a value of type [org.semanticweb.owlapi.util.WeakCache](value [org.semanticweb.owlapi.util.WeakCache@338e47b1]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
May 20, 2013 3:39:08 PM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [/podd] created a ThreadLocal with key of type [org.semanticweb.owlapi.model.IRI$1](value [org.semanticweb.owlapi.model.IRI$1@62a11cb0]) and a value of type [org.semanticweb.owlapi.util.WeakCache](value [org.semanticweb.owlapi.util.WeakCache@4204cfe8]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

**Comment by sujoykr1** [comment]
Threads are going to be renewed over time to try and avoid a probable memory leak
