### ISSUE TITLE
Switch build system to gradle

### ISSUE THREAD

**Issue by sesuncedu** [owlcs/owlapi#602]
Switching from mvn to gradle makes it much easier to customize the build process to deal with variant builds. 

For example it is much easier to write a task to use common data to generate  jigsaw module-info and OSGI bundles. It is also much easier to use multiple source directories (e.g.  1.8 vs. 9), and is much easier to use to generate & test Android libraries. 

POM stuff that requires manual translation 
- OSGI distribution
- pom generation for uploading.

**Comment by sesuncedu** [comment]
I've gotten things pretty much working, except for a few loose ends with the osgi distribution (I got caught in a maze of twisty passages when I tried to over-ride the jar task.  Gradle provides a flag for replacing a task, which works... except that any tasks that depend on the original task aren't *always* affected.)

However, the more I look at it, the less I understand the motivation for having the osgi distribution set up as is.  I will open a separate issue.

**Comment by ignazio1977** [comment]
If you can share your work so far in a branch, I'm happy to investigate. I've tried moving to Gradle before but didn't build up the momentum to write a verification test to ensure the build results were equivalent.

**Comment by sesuncedu** [comment]
This is a start: https://github.com/owlcs/owlapi/tree/gradle-build

The tricky stuff is the distribution build ; the distribution jar is not great practice, so it requires some hackery (gradle supports modifying a few fields in the generated POM, then says go modify the generated XML).  I took a third way out, and did my own mangling of the dependencies so that all the directly used dependencies of the child projects (apart from owlapi ones), with the actual resolved version numbers instead of the ranges.

I probably ought to do this for all the jars, but since I might want to use the newer maven publishing plugin I haven't bothered yet.

**Comment by sesuncedu** [comment]
A whole bunch of new stuff.  Contains some caused by trying to make builds be repeatable, where the documentation is the source code.  

Also, I now am capable of hating three (possibly four) different flavors of dependency injection with a single command.
