### ISSUE TITLE
Why does the OSGI distribution embed foreign dependencies?

### ISSUE THREAD

**Issue by sesuncedu** [owlcs/owlapi#603]
The canonical user of the big osgi-distribution jar is protege, so I will go out on a limb and hazard a guess that this was the original driver? 

Where there are dependencies on libraries that do not have bundle metadata, it is trivial to generate naively packaged OSGI wrapped bundles using  bnd/bndlib   (this was done for the  servicemix dependencies). 

It also doesn't seem to make a great deal of sense for things like apache httpc omponents, which have osgi versions, or for things like commons-codec, which *are* OSGI bundles. 

The bundle dependencies can be generated  from gradle/maven, with remote dependencies auto fetched;  or apps  like protege can pre-fetch all the required bundle jars as part of the distribution build.

**Comment by ignazio1977** [comment]
Most of these questions have a simple answer: I designed the thing by duct taping anything that seemed to not have to move and WD40'ed anything else.

Regarding dependencies, I tried not mentioning them explicitly but all I got for my trouble were error messages. I could not tell at the time if it was due to some other mistakes, or just necessary, so I settled for anything that worked.

About foreign jars, I tried to locate all those that already had an OSGi bundle, but failed in many cases. I guess improvement is possible :-)

**Comment by sesuncedu** [comment]
[Strange fact: Duct tape was originally called Duck tape, then it wasn't, then enough time past that a company registered Duck Tape as a trademark, so Duck Tape ⊑ Duct Tape.  There is Hello Kitty licensed Duck Tape.  A friend got some for her Roller Derby skates, because Hello Kitty = Hitting people. ]

Embedded dependencies are considered and anti-pattern, and there are ways to resolve them cleanly. This may be too much of a pain to do the perfect way, but the other ways are not too bad.  

Things that are worth doing, but which are a bit of a pain:  versioning packages individually, instead of always bumping version to match bundle version.  That avoids a dependency cascade when only one package in a bundle changes but every package number is bumped, and everything that depends on other packages in the bundle has to also be bumped. 

The win for this would be for setups like protege so that plugins that mostly just use model don't introduce  a zillion different versions of owlapi 5.X  and dependents :) 

Jigsaw exports packages, but imports and versions modules. It doesn't support versions constraints for imports, but will be adding a feature to record the version of the module imported at compile time (which will in general be ignored).    The more one looks at the history of the spec, the more obvious the reasons for it missing multiple JDK releases, and delaying jdk9 become :-)
