### ISSUE TITLE
Improve OWLDataFactoryTestCase

### ISSUE THREAD

**Issue by sesuncedu** [owlcs/owlapi#606]
Apart from an explicit creation of an instance of OWLDataFactoryImpl , all the tests use the public api

**Comment by ignazio1977** [comment]
I'm not sure if that's a problem. The idea here was to move the test as close to the class as possible. The contract module exists for examples, tutorials, and all those unit tests that need an OWLManager and a set of parsers/storers; this test does not need those, so it seemed convenient to have it in the impl test folder.
