### ISSUE TITLE
Turtle parser failure on some bioportal ontology

### ISSUE THREAD

**Issue by ignazio1977** [owlcs/owlapi#610]
From: http://stackoverflow.com/questions/41768250/cannot-parse-some-turtle-format-files-with-owl-api

http://bioportal.bioontology.org/ontologies/LOINC/

`	<http://purl.bioontology.org/ontology/LNC/LRN2> """3'''-acetate; [cut]"""^^xsd:string ;`

The problem is the three quotes: `'''` those are interpreted as equivalent to `"""`, which is the literal delimiter. Older OWLAPI behaved incorrectly with the specs in this, but it appears this literal is malformed and so it fails with newer OWLAPI. Protege Beta up to (I think) version 15 uses OWLAPI 3.5, which has an older parser.

I'm not sure if this can be corrected in the parsers or if the data needs to be fixed instead, at this stage. I'll raise an issue on GitHub.

**Comment by ansell** [comment]
The parser needs to keep track of the opening quotes:

https://www.w3.org/TR/turtle/#grammar-production-STRING_LITERAL_LONG_SINGLE_QUOTE

https://www.w3.org/TR/turtle/#grammar-production-STRING_LITERAL_LONG_QUOTE
