### ISSUE TITLE
Add japicmp to quantify API variations

### ISSUE THREAD

**Issue by ansell** [owlcs/owlapi#612]
The japicmp maven plugin can be used to quantify API variations across time to determine whether releases are backwards compatible in terms of either binary or source.

**Comment by ansell** [comment]
Added japicmp maven plugin to versions 3/4/5 branches to generate reports that can be used to clarify the extent of incompatibility between the original versions released to maven central (3.3/3.4 in the case of version 3) and the current development version.

Can add similar to the master branch when presumably a version6 branch is created after the first 6.0.0 release, but not useful to add it in until there is some development occurring to warrant it.

**Comment by sesuncedu** [comment]
I've added the japicmp gradle plugin to the gradle build.  Now I'm preparing the pull request for aforesaid plugin so that it works if the old jar has different dependencies than the new jar :).
