### ISSUE TITLE
ontology manager save to is including classes and annotations from imported ontologies

### ISSUE THREAD

**Issue by marianobntz** [owlcs/owlapi#613]
Hello,

I am working on generating RDF data out of ontologies I am defining in my application using owlapi 5.0.5. 

I create the ontologies manually in memory and importing some external ontologies for classes and other definitions. 

The thing is that when I use ontologyManager.saveTo(ontology... new RDFXMLDocumentFormat() )  if get the output below which contains all the things I reference from the other ontologies, is there a way to avoid this? or is there something wrong in the imported ontologies?

Thanks

`<rdf:RDF xmlns="http://www.example.com/spec/AAA/About-AAA.rdf#"
     xml:base="http://www.example.com/spec/AAA/About-AAA.rdf"
     xmlns:dct="http://purl.org/dc/terms/"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:owl="http://www.w3.org/2002/07/owl#"
     xmlns:xml="http://www.w3.org/XML/1998/namespace"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
     xmlns:skos="http://www.w3.org/2004/02/skos/core#"
     xmlns:sm="http://www.omg.org/techprocess/ab/SpecificationMetadata/"
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">
    <owl:Ontology rdf:about="http://www.example.com/spec/AAA/About-AAA.rdf">
        <owl:versionIRI rdf:resource="http://www.example.com/spec/AAA/2.1/About-AAA.rdf"/>
        <owl:imports rdf:resource="http://www.omg.org/techprocess/ab/SpecificationMetadata/"/>
        <dct:license rdf:resource="http://www.omg.org/techprocess/ab/SpecificationMetadata/MITLicense"/>
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">About the AAA Example Specification Version 2.1</rdfs:label>
        <sm:filename rdf:datatype="http://www.w3.org/2001/XMLSchema#string">About-AAA.rdf</sm:filename>
        <sm:creationDate rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">1996-01-01T00:00:00-0300</sm:creationDate>
        <owl:versionInfo rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Generated on 2017-01-24T08:51:14-0300</owl:versionInfo>
    </owl:Ontology>   
   
    
    <owl:AnnotationProperty rdf:about="http://www.omg.org/techprocess/ab/SpecificationMetadata/publicationDate"/>
    
    <owl:AnnotationProperty rdf:about="http://www.omg.org/techprocess/ab/SpecificationMetadata/specificationAbbreviation"/>
    
    <owl:AnnotationProperty rdf:about="http://www.omg.org/techprocess/ab/SpecificationMetadata/specificationAbstract"/>
    
    <owl:AnnotationProperty rdf:about="http://www.omg.org/techprocess/ab/SpecificationMetadata/specificationTitle"/>
    
    <owl:AnnotationProperty rdf:about="http://www.omg.org/techprocess/ab/SpecificationMetadata/specificationURL"/>
    
    
    <owl:Class rdf:about="http://www.omg.org/techprocess/ab/SpecificationMetadata/specification"/>
    
    
    <owl:NamedIndividual rdf:about="http://www.example.com/spec/AAA">
        <rdf:type rdf:resource="http://www.omg.org/techprocess/ab/SpecificationMetadata/specification"/>
        <sm:publicationDate rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">1996-01-01T00:00:00-0300</sm:publicationDate>
        <sm:specificationAbbreviation rdf:datatype="http://www.w3.org/2001/XMLSchema#string">AAA</sm:specificationAbbreviation>
        <sm:specificationAbstract rdf:datatype="http://www.w3.org/2001/XMLSchema#string">AAA Description</sm:specificationAbstract>
        <sm:specificationTitle rdf:datatype="http://www.w3.org/2001/XMLSchema#string">AAA Example</sm:specificationTitle>
        <sm:specificationURL rdf:resource="http://www.example.com/spec/AAA/About-AAA.html"/>
    </owl:NamedIndividual>
</rdf:RDF>
`

**Comment by ignazio1977** [comment]
You should call `setAddMissingTypes(false)` on the format object before saving the ontology. This will stop missing type declarations from being added.

**Comment by marianobntz** [comment]
Thanks Ignazio! That worked! You get the warning about the types but it´s fine. The warning means that the import declaration is not working? the missing declaration are here: 
<owl:imports rdf:resource="http://www.omg.org/techprocess/ab/SpecificationMetadata/"/>

**Comment by ignazio1977** [comment]
Depends whether there are actual declarations in the imported ontologies. The warnings should include the import closure.
