### ISSUE TITLE
API Documentations 404s

### ISSUE THREAD

**Issue by alanruttenberg** [owlcs/owlapi#615]
e.g http://owlcs.github.io/owlapi/apidocs_4_2_3/org/semanticweb/owlapi/model/OWLAxiomCollectionNoArgs.html

**Comment by alanruttenberg** [comment]
this was top google hit for "getAxiomsIgnoreAnnotations"

**Comment by ignazio1977** [comment]
http://owlcs.github.io/owlapi/apidocs_4_2_8/org/semanticweb/owlapi/model/OWLAxiomCollectionNoArgs.html

Google spiders have not updated their links yet, I guess.

**Comment by alanruttenberg** [comment]
"cool URIs don't change"

**Comment by alanruttenberg** [comment]
ps. I don't think google spiders are going to fix people's broken bookmarks.

Is there any reason not to leave the javadocs for old versions up?

**Comment by ignazio1977** [comment]
> "cool URIs don't change"

Javadoc ain't cool...

**Comment by ignazio1977** [comment]
If we want to keep stable URLs, the best way is to reduce the version number in the URL to the main release only. Interfaces are not meant to change - only extend - in the same main release, so newer javadoc will only expand wrt older versions.

**Comment by alanruttenberg** [comment]
That would be better than now. However despite intentions I keep finding my stuff breaking on new releases. So maybe keep the last for each major version.

**Comment by alanruttenberg** [comment]
In know that there are projects I care about that are using 3,4,5. Its not fun to figure out how to make them work together. I started looking at OSGI but it's a total piece of hair, and doesn't really solve the problem unless people are very careful about saying what their dependencies are (they aren't). And unless you like wearing a straightjacket.

**Comment by alanruttenberg** [comment]
We're agreeing. I didn't read carefully enough.

I think there's a way to request that Google re index the site.

**Comment by ignazio1977** [comment]
> there are projects I care about that are using 3,4,5

If they're receptive to pull requests I'm happy to help update.

**Comment by ansell** [comment]
I added japicmp a few days ago to the build process to generate programmatic reports of how APIs have changed between versions. https://github.com/owlcs/owlapi/commit/d84d68ee63f49f5589d152ff926f226cf39922b3 If you wanted a change report between 3.4.5 and the most recent version3 head commit it is fairly easy to generate such a report. That doesn't tell you about behavioural changes, but it will highlight any changed APIs.

**Comment by ignazio1977** [comment]
19f0e819571abf062692cd99a3ffd8115dac71eb moves javadoc folders to be 3/4/5 only, so future releases will have stable links
