### ISSUE TITLE
Guice dependencies are widespread

### ISSUE THREAD

**Issue by sesuncedu** [owlcs/owlapi#616]
Guice is being used directly in a lot of different places. If we are going to make owlapi as independent of a specific DI framework a possible, we need to isolate this usage as much as possible. 

The following sub-projects use classes from com.google.inject.*
1. api
1. apibinding
1. impl
1. parsers
1. rio

Theoretically the current  apibinding project would be the guice based binder. 
 There should definitely be no guice dependencies in api.  I have absolutely no idea why there is a Provides annotation on ```org.semanticweb.owlapi.profiles.Profiles```

Rio shouldn't need to create  an Injector to get an ontology manager factory; surely OWLManager is sufficient? 

```java
public abstract class RioAbstractParserFactory implements RDFParserFactory {
    private static final Injector INJECTOR = Guice
            .createInjector(new OWLAPIServiceLoaderModule());
...
    public RDFParser getParser() {
        RioOWLRDFParser rioOWLRDFParser = new RioOWLRDFParser(getRDFFormat());
        INJECTOR.injectMembers(rioOWLRDFParser);
        return rioOWLRDFParser;
    }
}
--------
public class RioOWLRDFParser extends AbstractRDFParser {
    private final Set<OWLOntologyManagerFactory> ontologyManagerFactories
...
    @Inject
    public void setOntologyManagerFactories(Set<OWLOntologyManagerFactory> factories)
...
    void render(OWLOntologyDocumentSource source) {
...
            for (OWLOntologyManagerFactory f : ontologyManagerFactories) {
                OWLOntology ontology = f.get().loadOntologyFromOntologyDocument(source);
                       ...
                return;
           }
    }
}

```
The following Guice classes are used from the listed owlapi locations. 

* com/google/inject/AbstractModule.java
  * impl/src/main/java/uk/ac/manchester/cs/owl/owlapi/OWLAPIImplModule.java
  * parsers/src/main/java/org/semanticweb/owlapi/OWLAPIParsersModule.java
  * api/src/main/java/org/semanticweb/owlapi/OWLAPIServiceLoaderModule.java
* com/google/inject/Binder.java
     * impl/src/main/java/uk/ac/manchester/cs/owl/owlapi/OWLAPIImplModule.java 
     * api/src/main/java/org/semanticweb/owlapi/OWLAPIServiceLoaderModule.java 

* com/google/inject/binder/AnnotatedBindingBuilder.java
  * impl/src/main/java/uk/ac/manchester/cs/owl/owlapi/OWLAPIImplModule.java 

* com/google/inject/binder/LinkedBindingBuilder.java
  * impl/src/main/java/uk/ac/manchester/cs/owl/owlapi/OWLAPIImplModule.java
  * api/src/main/java/org/semanticweb/owlapi/OWLAPIServiceLoaderModule.java
  
* com/google/inject/binder/ScopedBindingBuilder.java
  * impl/src/main/java/uk/ac/manchester/cs/owl/owlapi/OWLAPIImplModule.java
 
* com/google/inject/BindingAnnotation.java
  * impl/src/main/java/uk/ac/manchester/cs/owl/owlapi/concurrent/NonConcurrentDelegate.java
  * impl/src/main/java/uk/ac/manchester/cs/owl/owlapi/CompressionEnabled.java

* com/google/inject/Guice.java 
  * apibinding/src/main/java/org/semanticweb/owlapi/apibinding/OWLManager.java
  * rio/src/main/java/org/semanticweb/owlapi/rio/RioAbstractParserFactory.java

* com/google/inject/Injector.java 
  * apibinding/src/main/java/org/semanticweb/owlapi/apibinding/OWLManager.java
  * rio/src/main/java/org/semanticweb/owlapi/rio/RioAbstractParserFactory.java

* com/google/inject/Module.java
  * impl/src/main/java/uk/ac/manchester/cs/owl/owlapi/OWLAPIImplModule.java

* com/google/inject/multibindings/Multibinder.java
  * impl/src/main/java/uk/ac/manchester/cs/owl/owlapi/OWLAPIImplModule.java
  * api/src/main/java/org/semanticweb/owlapi/OWLAPIServiceLoaderModule.java

* com/google/inject/Provides.java
  * parsers/src/main/java/org/semanticweb/owlapi/OWLAPIParsersModule.java
  * api/src/main/java/org/semanticweb/owlapi/profiles/Profiles.java

**Comment by ignazio1977** [comment]
> Rio shouldn't need to create an Injector to get an ontology manager factory; surely OWLManager is sufficient?

Not exactly. Rio itself has a set of factories to be used - I don't believe these are the same used in OWLManager. However, I only have vague memories of that, so I might be mistaken.

**Comment by ansell** [comment]
There are three OWLAPI parsers (Manchester/Functional/OWLXML I think) that are exposed as Rio RDFParserFactory's so users can smoothly (ymmv) convert ontologies in those languages into the equivalent RDF4J Statement's and process/store them as RDF. 

These are discovered by the RDF4J Rio.createParser method when owlapi-rio is on the classpath. These users need to have Rio.createParser work smoothly without having to create an OWLOntologyManager or statically initialize anything inside of OWLAPI themselves.

**Comment by ignazio1977** [comment]
Problem reduced - the RIO module still uses Guava directly

**Comment by sesuncedu** [comment]
Guava,  not a problem :) Though guava version ranges are weird, because they mostly just do major releases,  depreciation is not just a threat, and breaking changes happen on even numbers... 

The reason that the use of the owlapi service loader  directly seemed odd is that I thought that did about the same amount of work as the OwlManager setup. 


Off-topic: I've been reading up on the problem of dependency resolution, and how the worst case is NPC, and I have to remember that that's bad.

**Comment by ignazio1977** [comment]
Sorry I meant Guice.

**Comment by ignazio1977** [comment]
The fact that dependency resolution is NP complete explains how comes similarly structured issues appear everywhere all the time.
