### ISSUE TITLE
OWLOntology doesn't use ToStringRender

### ISSUE THREAD

**Issue by phillord** [owlcs/owlapi#620]
toString rendering is pluggable for the default implementation, except for OWLOntology which seems slightly odd.

**Comment by ignazio1977** [comment]
It used to be a toString() of the id only. I added a toString() of the first twenty axioms for convenience of debugging for tiny ontologies (typically unit tests).

The reason not to use the same full renderer as for all other OWLObjects is mostly performance - if debugging a loaded copy of Snomed, clicking by mistake on the ontology in the debugger kind of stops the thing in its tracks.

**Comment by phillord** [comment]
Yeah, unfortunately a paragraph long toString() makes debugging very hard for me. The ToString renderer, I believe, can behave differently for different classes?

Anyway, up to you. I've found a workaround for this now in my environment (I supress toString() and use something else instead!), so, perhaps, I care less:-)

**Comment by ignazio1977** [comment]
The way plugging toStringRenderer works is pretty cumbersome as is, however there's another enhancement request that would help with this too. See #205 - when we get around to  implement it, we can treat all objects the same way for explicitly set renderers, and remove the static hacks.
