### ISSUE TITLE
Import ontology from jar

### ISSUE THREAD

**Issue by donmendelson** [owlcs/owlapi#621]
I would like to distribute an application to create or edit ontologies that would import an ontology that I supply.  I expect that the base ontology would be provided as a resource in a distributed jar file. My application works if the imported ontology resides as a flat file, but I am unable to load it from the jar. I've tried providing a file:// protocol on the document IRI in SimpleIRIMapper, but that doesn't work. Usually such resources are accessed by 

`InputStream ClassLoader.getResourceAsStream(String name)`

I can't find a way to adapt that to the API. Any suggestions?

**Comment by ignazio1977** [comment]
There is no ready made utility for this but you should be able to load this kind of ontology subclassing a StreamDocumentSource.

Currently it's not possible to achieve this with an IRI mapper - jar paths are not understood as resolvable IRIs.

**Comment by donmendelson** [comment]
IRI mapper returns null if it cannot resolve the document IRI. I created a workaround that seems to work. It allows the document to be resolved whether it is in the file system or as a resource in the application jar. It uses URLClassLoader, which can access members of a jar.

```
URLClassLoader jarClassLoader = new URLClassLoader(new URL [] {new URL("file://")});

    URL documentURL = this.getClass().getClassLoader().getResource("orchestra2016.ttl");
    if (documentURL == null) {
      // Retrieve from the jar
      documentURL = jarClassLoader.getResource("orchestra2016.ttl");
    }

    PriorityCollection<OWLOntologyIRIMapper> iriMappers = ontologyManager.getIRIMappers();
    iriMappers.add(new SimpleIRIMapper(orchestraIRI, IRI.create(documentURL)));
```

**Comment by ignazio1977** [comment]
AutoIRIMapper can now do this.

**Comment by ykazakov** [comment]
@ignazio1977 could you provide a bit more detail how to do it using AutoIRIMapper.
Should this be enough?

     ontologyManager.getIRIMappers().add(new AutoIRIMapper(new File("ontologies.jar"), true));

This does not seem to work for me. I get (with OWL API v 5.1.4):

```
org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <http://www.example.com#impA> Cause: Problem parsing http://www.example.com#impA
Could not parse ontology. 
```

And below:

```
--------------------------------------------------------------------------------
Parser: org.semanticweb.owlapi.functional.parser.OWLFunctionalSyntaxOWLParser@29a60c27
    Stack trace:
Encountered unexpected token: "<!doctype html>" <FULLIRI>
    at line 1, column 1.

Was expecting one of:

    "Ontology"
    "Prefix"
```

My jar contains an ontology in functional-style syntax with there required IRI.

If necessary I can create a complete test, but I wanted to double check if this is a proper way to load imports from jar.

**Comment by ykazakov** [comment]
I also tried to give the AutoIRIMapper as an argument the directory in which the jar is located with the same result. The documentation of AutoIRIMapper also does not seem to mention jar files.

**Comment by ignazio1977** [comment]
Can you attach the jar you're using?

The error message shows a fragment of HTML page - I suspect there might be an unresolvable import.

**Comment by ykazakov** [comment]
Here you go: [owlapi5-tryout.zip](https://github.com/owlcs/owlapi/files/1675100/owlapi5-tryout.zip)

**Comment by ykazakov** [comment]
Interesting, if I replace the ontology IRIs from

    <http://www.example.com#impA>

to

    <http://www.example.com/A>

Then I get a different error message:

    java.io.FileNotFoundException: http://www.example.com/A

Here is the update project: [owlapi5-tryout.zip](https://github.com/owlcs/owlapi/files/1675232/owlapi5-tryout.zip)

**Comment by ykazakov** [comment]
The @donmendelson solution does not seem to work for me either.
If instead of adding AutoIRIMapper I do:

    man.getIRIMappers().add(new SimpleIRIMapper(IRI.create("http://www.example.com/A"),
						IRI.create(jarClassLoader.getResource("impA.owl"))));

I get:

    Could not find an appropriate factory to load ontology from ontology document: <jar:file:/path/to/target/owlapi5-tryout-0.0.1-SNAPSHOT-ontologies.jar!/impA.owl>

**Comment by ykazakov** [comment]
OK, I checked the source code and I think the changes to AutoIRIMapper have not been released yet.
@ignazio1977, is there a snapshot repository for OWL API?
Is there a workarounds to load imports from a jar file for the released OWL API?

**Comment by ykazakov** [comment]
OK, one workaround would be to create a custom OWLOntologyFactory which would load ontologies from the jar file using their IRIs. Here is an example:

		man.getOntologyFactories().add(new OWLOntologyFactory() {

			private static final long serialVersionUID = 1L;

			public OWLOntology createOWLOntology(OWLOntologyManager manager,
					OWLOntologyID ontologyID, IRI documentIRI,
					OWLOntologyCreationHandler handler)
					throws OWLOntologyCreationException {
				return null;
			}

			public OWLOntology loadOWLOntology(OWLOntologyManager manager,
					OWLOntologyDocumentSource documentSource,
					OWLOntologyCreationHandler handler,
					OWLOntologyLoaderConfiguration configuration)
					throws OWLOntologyCreationException {
				// Get the name of the ontology file inside the jar
				String name = documentSource.getDocumentIRI().getFragment()
						+ ".owl";
				return manager.loadOntologyFromOntologyDocument(
						jarClassLoader.getResourceAsStream(name));
			}

			public boolean canCreateFromDocumentIRI(IRI documentIRI) {
				return false;
			}

			public boolean canAttemptLoading(
					OWLOntologyDocumentSource documentSource) {
				return (documentSource instanceof IRIDocumentSource);
			}

		});

Here is the example project which now works: [owlapi5-tryout.zip](https://github.com/owlcs/owlapi/files/1677312/owlapi5-tryout.zip)

**Comment by ignazio1977** [comment]
Another way would be to cherry pick the changes to AutoIRIMapper, factory and zip mapper from the commits for #375. It is not finished yet as there are a few other requirements on the YAML format, but I wasn't planning on backporting those - people sneer at extra dependencies.

**Comment by ykazakov** [comment]
@ignazio1977 It would be nice if it were documented how to use AutoIRIMapper to load ontologies from JAR files:
```
 /**
     * Creates an auto-mapper which examines ontologies that reside in the specified root folder
     * (and possibly sub-folders).
     *
     * @param rootDirectory The root directory which should be searched for ontologies.
     * @param recursive Sub directories will be searched recursively if {@code true}.
     */
    public AutoIRIMapper(File rootDirectory, boolean recursive)
```

Does it now look for ontologies also in the jar/zip files in the provided rootDirectory? Or the rootDirectory must be a jar/zip file?

**Comment by ignazio1977** [comment]
It works pointed directly at a zip/jar file or to a folder containing zip/jar files. I'll update the javadoc.
