### ISSUE TITLE
Standardizing on code format  / import sorting/optimization ? 

### ISSUE THREAD

**Issue by sesuncedu** [owlcs/owlapi#627]
I keep finding that I have or cause merge issues or distracting diffs due to ide assisted import optimization and layout settings. It would be nice if we could pick a convention,  export the settings for idea/eclipse, and apply them to the whole code base as a jumbo set of commits. Adding a hook / gradle plugin can wait. 

The convention on imports  is probably the most important thing to agree on are 

1. Sorting. 
2. Wildcard vs. Explicit. I used to think that switching to wildcard imports after a certain threshold is met reduced noise, but now I am leaning towards explicit imports. In idea it doesn't make much if a difference for navigation, as navigating to the defining class is a key click ; however when looking at code on github wildcards can be a pain. 

3. Whether to sort java and javax specially (e.g. to start or end of import list).  Start is probably best. 

4. Whether to treat certain java packages specially for wildcards (eg. java.util and java.io).

 i think there's a relatively safe way to do this in git where the author and dates are set so as to match that of the last committer (it's safe because these would be new commits against HEAD, so irs not rewriting history). That'd keeps blame useful, though the real changes would be one step down.  Better that than a force-push (grrrr).

**Comment by sesuncedu** [comment]
[Google style guide](https://github.com/google/styleguide/blob/gh-pages/javaguide.html)
[intellij  settings] (https://github.com/google/styleguide/blob/gh-pages/intellij-java-google-style.xml) 
[Eclipse settings ](https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml)

There's also a checkstyle config

**Comment by ansell** [comment]
Anything that can be consistently and automatically applied by the different IDEs in use would be great to minimise (and hopefully completely remove) diff noise. The actual style choices don't matter to me as much as the consistency to reduce time required to review PRs.

**Comment by sesuncedu** [comment]
Right! Though I still find the probably  trivial but have to look at merge
fails more annoying.

The Google rules seem good enough, and checkstyle /eclipse /intellij are
all covered, so I will install the style pack and run them on version5 and
submit a REALLY annoying PR :-)

**Comment by ansell** [comment]
I trust the Github PR process to show me the net result of merge commits+other commits, rather than having to review the actual commit itself. If we wanted to avoid having to review merge commits we would need to change to a rebase workflow where all patches come off the tip.

**Comment by sesuncedu** [comment]
I'm talking about having a long-running parallel branch, which often has a couple of files end up with formatting related merge conflicts . Down, not across.  

Also, https://github.com/owlcs/owlapi/pull/628 - 1,799 files changed.

**Comment by ansell** [comment]
The 2-space Google style in #628 a little strange to look at after viewing everything else Java in 4-space, but consistent is useful.

**Comment by matthewhorridge** [comment]
> The 2-space Google style in #628 a little strange to look at after viewing everything else Java in 4-space, but consistent is useful.

+1.  Please can we use 4 spaces?

**Comment by sesuncedu** [comment]
Tomorrow :-) I just had to go file a ticket at jetbrains :-)

On Thu, Feb 23, 2017 at 11:17 PM, Matthew Horridge <notifications@github.com

**Comment by matthewhorridge** [comment]
Thanks Simon.

**Comment by ignazio1977** [comment]
+4 for spaces

About merge commits, I prefer to avoid them - I have git configured to rebase rather than merge. Recently pull requests on GitHub can be rebased before merge so as not to introduce merge commits as well. History looks simpler and easier to read, especially when there are three or four branches going (version3, version4, version5... and master!).

**Comment by sesuncedu** [comment]
New PR: https://github.com/owlcs/owlapi/pull/630

**Comment by sesuncedu** [comment]
I think this is closable. Debates can be held in the bike shed.
