### ISSUE TITLE
Adding new tags in OWLXML Format

### ISSUE THREAD

**Issue by vaibhav1248** [owlcs/owlapi#629]
How can I add a new tag in OWL file?
![1](https://cloud.githubusercontent.com/assets/26009012/23310929/33e7039c-fada-11e6-9516-632b7d8b2546.jpg)

**Comment by ignazio1977** [comment]
I'd like to know who the lecturer is that assigns these projects.

Modifying the parser for any of the OWL languages supported by the owl api is probably the most difficult change one could attempt to make, especially if the final objective is to make the change appear in tools like Protégé. It takes at least a week and could be up to a month of work for someone who is familiar with the code base. For someone who is not, it's a lost battle.

That said, the OWLXML parser is implemented within the OWLXMLParser class and the companion enumerations - OWLXMLPH and PARSER_OWLXMLVocabulary.

Those classes are complex and not designed for extension - languages are not supposed to change often.
