### ISSUE TITLE
get one level direct parent node in owlapi

### ISSUE THREAD

**Issue by mahaalfate7** [owlcs/owlapi#634]
Is there a way to get the direct super class (only one level above).
This below will give all of the super classes to owl:Thing but as 
a non ordered list. 
`NodeSet<OWLClass> superclasses = reasoner.getSuperClasses(c, true);`

 This one is also not what I need:
`Set<OWLClassExpression> superclasses = c.getSuperClasses(ontology);`

I just need the direct parent node (so I can iterate until owl:Thing) or the set of nodes until owl:Thing ordered.

**Comment by sesuncedu** [comment]
```NodeSet<OWLClass> superclasses = reasoner.getSuperClasses(c, true)``` should return the set of all and only the named, *direct* superclasses of c. If you are not getting direct superclasses, then this is may be a bug. 
I believe that ```Thing``` by definition a direct superclass of every class, but I'd have to recheck. 

You can check to see if the only superclass is Thing (i.e. the only entry in the nodeset is ```Thing```) by using calling ```superclasses.isTopSingleton()```. 

You can get the set of classes in a Node , excluding Thing, by calling getEntitiesMinusTop() on the node. 


Do you have  a unit test that shows a problem , comparing actual results to expected results? If not, can you create one and submit it?

**Comment by mahaalfate7** [comment]
sorry, I set ` NodeSet<OWLClass> superclasses = reasoner.getSuperClasses(c, false);`
This gives the whole set including owl:Thing, but not ordered
This is the output:
class3      class0       class4      class1      owl:Thing   class2   
the expected output is:
class4     class3        class2      class1      class0    owl:Thing

**Comment by ignazio1977** [comment]
> I set `NodeSet<OWLClass> superclasses = reasoner.getSuperClasses(c, false);`

That `false` needs to be `true`. The flag determines if direct relations only (`true`) are to be returned, or if all should be returned.

**Comment by sesuncedu** [comment]
Also, there is in general no unique order in which to generate a list of the superclasses of a class. The right order for you depends on what you are trying to do.
