### ISSUE TITLE
A class is missing or dependency problem

### ISSUE THREAD

**Issue by Galigator** [owlcs/owlapi#636]
Hello thx for your every day work.

Here the commands I just use :

git clone https://github.com/owlcs/owlapi.git
cd owlapi/
mvn clean install -DskipTests=true

Here exception I get :
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/Versioned

It turn out that the solution could be that :
http://stackoverflow.com/questions/24488888/noclassdeffounderror-org-codehaus-jackson-versioned-using-jackson-json-parser

**Comment by Galigator** [comment]
The first commit that result in fail build is  c2bde1c6da6192ada2b8991007e9fb6838d67c85 the 2017-01-10 22:14:17  (plugins updates)

**Comment by ignazio1977** [comment]
That's unexpected, my builds and Travis don't get errors.

That commit updates Jackson as well as other dependencies, and some of the maven plugins as well. Which version of maven and which platform are you using?

**Comment by Galigator** [comment]
I am using  Maven 3.3.3 with  Java version 1.8.0_121 on linux.

I am going to try on lastest maven.

**Comment by Galigator** [comment]
Same problem with Maven 3.3.9 (and default settings.xml)

**Comment by Galigator** [comment]
I have remove all my .m2/repository/com/fasterxml  (jackson) to force a rebuild of the local cache.
Now it is working. 


Sorry for the inconvenience
