### ISSUE TITLE
Do not output xsd:string when unnecessary

### ISSUE THREAD

**Issue by sesuncedu** [owlcs/owlapi#640]
I'm assuming that there's some plain literal stuff happening on input (which is plain literal), but which is not happening on output?

Output generated by protege 5.1.0 (owlapi 4.2.6)
```xml
        <dcterms:modified>2016-04-21 (New)</dcterms:modified>
        <dcterms:modified>2016-04-29 (added inverse)</dcterms:modified>
```
Output generated by owlapi 5.0.5 
```xml
        <dcterms:modified rdf:datatype="&xsd;string">2016-04-21 (New)</dcterms:modified>
        <dcterms:modified rdf:datatype="&xsd;string">2016-04-29 (added inverse, updated range)</dcterms:modified>
```

**Comment by sesuncedu** [comment]
Ah - I see where the conversion is taking place;  I'm not sure why isPlainLiteral returns false, also, should that  method be used in the renderers  to decide whether to generate "simple" literals? Is it true for any Literals ?

(I'm trying to set up a gradle script that checks that a source file is strictly parseable DL, then renders the content in a variety of formats. The xsd:string contagion affects omn and ofn as well turtle and rdf/xml.  )

I

**Comment by ignazio1977** [comment]
Seems to me it ought to say true - no datatype, no language tag. Both 4.2.6 and 5 should be able to deal with the langString malarkey, and should do so the same way. Maybe some small change got sanded off since.

**Comment by sesuncedu** [comment]
The tests were changed to make this the expected behavior.  
https://github.com/owlcs/owlapi/blob/version5/contract/src/test/java/org/semanticweb/owlapi/api/test/literals/LiteralTestCase.java#L70

**Comment by ignazio1977** [comment]
I'm as usual confused by plain literals.

Your test case has no language tags - I seem to remember now that language tags means plain literal, no language tags means langString or equivalent to literals typed as strings. On rendering, though, a literal typed as string does not /require/ an explicit string output...

**Comment by sesuncedu** [comment]
simple...
I think I have a fix.
