### ISSUE TITLE
Inference in Protege different from Java

### ISSUE THREAD

**Issue by Ayanleye** [owlcs/owlapi#642]
Hello,

Please i need a quick help,
When i load the attached ontology on protege and start the reasoner i get a different result from when i do the same using java. I am using hermit library and i get what i want from protege but not the same on java.I get Bus and walking from protege which is what i want on the java application as well.Below is how i made my inference in java i am getting the individuals from a treeMap.I do not get the Bus class inferred at all and i get Car instead of Walking for sequence3.

    Configuration config = new Configuration();
    org.semanticweb.HermiT.Reasoner reasoner=new Reasoner(config,vehicle_ontology);
    for(int seq_key:inferred_sequences.keySet()) {
        OWLNamedIndividual ind = inferred_sequences.get(seq_key);
        NodeSet<OWLClass> classes = reasoner.getTypes(ind, false);
        System.out.println(ind.getIRI().getFragment()+ind.getDataPropertyValues(vehicle_ontology));
        for(OWLClass inf_class : classes.getFlattened()) {
              System.out.println(inf_class.getIRI().getFragment());
        }
    }

[vehicle.txt](https://github.com/owlcs/owlapi/files/838540/vehicle.txt)

**Comment by ignazio1977** [comment]
Which version of HermiT, owlapi and Protege are you using?

**Comment by sesuncedu** [comment]
If you look at the trailer in the attached ontology, the version number for
owlapi seems more like a  Hermit version number , if that's any help

**Comment by Ayanleye** [comment]
Thanks for the response 
I am not sure of the hermit version but i downloaded from the link http://www.hermit-reasoner.com/download.html  the latest version specified and it had included all the required dependecies. I am using Protege-5.1.0

**Comment by ignazio1977** [comment]
Protégé 5.1.8 is using HermiT 1.3.8.413, which is different in a number of small details from the HermiT versions downloadable at the link you suggest.

**Comment by Ayanleye** [comment]
I guess i would have to try using the HermiT 1.3.8.413 then but are they compatible in terms of codes used to reason.

**Comment by ignazio1977** [comment]
Yes, the difference is in compatibility with owlapi 4. You can check the changes in my HermiT fork, that's where 413 was released from.

**Comment by Ayanleye** [comment]
Alright, thanks a lot for your help.

**Comment by Ayanleye** [comment]
Hello, i just tried using HermiT 1.3.8.413 with owlapi 4 and i am having the same issue.Now i am frustrated, i will appreciate if anyone can just try inferring from java and let me know if he or she get's the same on protege.

**Comment by ignazio1977** [comment]
Do you have a test ontology we can use for this?

**Comment by ignazio1977** [comment]
In issue #646 a few bugs in OWLAPI 4.3.0 have been discovered and fixed. These will be released in  version 4.3.1, and there will be a HermiT version 1.3.8.431 release as well, for these fixes to be available.

**Comment by Ayanleye** [comment]
Yes i added the ontology as a txt file vehicle.txt in my first post due the file type restriction.

Please i am still stuck with my research and a resolution will be appreciated. I just need to get what i get in protege in my app. Thanks

**Comment by ignazio1977** [comment]
HermiT 1.3.8.431 is available on maven central now

**Comment by ignazio1977** [comment]
http://repo1.maven.org/maven2/net/sourceforge/owlapi/org.semanticweb.hermit/1.3.8.431/

**Comment by Ayanleye** [comment]
Alright, thanks a lot i will give it a try now

**Comment by ignazio1977** [comment]
Running with HermiT 1.3.8.431 I get:

    myMobile0{
            <#phone_number>=[uk.ac.manchester.cs.owl.owlapi.OWLLiteralImplString@7c150122]
        }
        MobileEntity
        Thing
    sequence3{
            <#avg_speed>=["2.1684210300445557"^^xsd:double], 
            <#end_time>=["2017-01-12T14:18:58.285"^^xsd:dateTime], 
            <#bus_stop_count>=["2"^^xsd:integer], 
            <#avg_course_change>=["77.73684"^^xsd:float], 
            <#start_time>=["2017-01-12T14:17:48.999"^^xsd:dateTime], 
            <#train_stop_count>=["0"^^xsd:integer]
        }
        Walking
        Sequence
        NonMobilityAidSequence
        Thing
    sequence1{
            <#avg_course_change>=["12.482196"^^xsd:float], 
            <#start_time>=["2017-01-12T14:02:26"^^xsd:dateTime], 
            <#bus_stop_count>=["10"^^xsd:integer], 
            <#end_time>=["2017-01-12T14:16:32.999"^^xsd:dateTime], 
            <#train_stop_count>=["0"^^xsd:integer], 
            <#avg_speed>=["22.42186737060547"^^xsd:double]
        }
        Bus
        MobilityAidSequence
        Sequence
        Thing

which I believe is what you're after - Bus and Walking are there.

**Comment by ignazio1977** [comment]
Code I ran:

     public static void main(String[] args) throws Exception {
        OWLOntology o = OWLManager.createOWLOntologyManager()
            .loadOntologyFromOntologyDocument(new File("vehicle.txt"));
        Configuration config = new Configuration();
        OWLReasoner reasoner = new ReasonerFactory().createReasoner(o, config);
        for (OWLNamedIndividual ind : o.getIndividualsInSignature()) {
            NodeSet<OWLClass> classes = reasoner.getTypes(ind, false);
            System.out.println(ind.getIRI().getFragment()
                + EntitySearcher.getDataPropertyValues(ind, o).asMap().toString().replace(
                    "http://www.semanticweb.org/ayanleyo/ontologies/2017/2/VehicleClassification",
                    ""));
            for (OWLClass inf_class : classes.getFlattened()) {
                System.out.println(inf_class.getIRI().getFragment());
            }
        }
    }

**Comment by Ayanleye** [comment]
This is exactly what i want thank you! i have no idea what i am doing wrong cause the code is just about the same but i will try again.If i am not asking for too much can you please send the zip file of the dependencies you used may be i am missing something somewhere. my email is ayanleyeolatunde@yahoo.co.uk

**Comment by Ayanleye** [comment]
Thank you very much!!!...it finally gives me what i want.I appreciate the help...bless you!
