### ISSUE TITLE
Unable to get object properties in inferred Ontology file using OWL API Reasoner

### ISSUE THREAD

**Issue by karanthpallavi** [owlcs/owlapi#643]
Hello,

Have used Hermit Reasoner to reason an Ontology file. Have added generators with all axioms as mentioned below. The inferred ontology file does not contain any object properties which are present in the original ontology file.
May I know what is the cause and how to resolve this?
Thanks,
Please find below my code:

OWLOntology ontology=manager.loadOntologyFromOntologyDocument(inputOntologyFile);
        OWLDataFactory df = manager.getOWLDataFactory();

Reasoner.ReasonerFactory rf = new Reasoner.ReasonerFactory() {
            @Override
            public OWLReasoner createReasoner(OWLOntology ontology,
OWLReasonerConfiguration config) {
                Configuration configuration = new Configuration();
                configuration.ignoreUnsupportedDatatypes = true;
                return super.createReasoner(ontology, configuration);
                }
        };
          
        Reasoner reasoner=(Reasoner)rf.createReasoner(ontology);
        boolean consistencyCheck = reasoner.isConsistent();
        if(consistencyCheck)
        {
            reasoner.precomputeInferences(InferenceType.CLASS_HIERARCHY, InferenceType.CLASS_ASSERTIONS, InferenceType.OBJECT_PROPERTY_HIERARCHY, InferenceType.DATA_PROPERTY_HIERARCHY, InferenceType.OBJECT_PROPERTY_ASSERTIONS);
        // We now have to decide which kinds of inferences we want to compute. For different types 
        // there are different InferredAxiomGenerator implementations available in the OWL API and 
        // we use the InferredSubClassAxiomGenerator and the InferredClassAssertionAxiomGenerator 
        // here. The different generators are added to a list that is then passed to an 
        // InferredOntologyGenerator. 
            List<InferredAxiomGenerator<? extends OWLAxiom>> generators=new ArrayList<InferredAxiomGenerator<? extends OWLAxiom>>();
            generators.add(new InferredSubClassAxiomGenerator());
            generators.add(new InferredClassAssertionAxiomGenerator());
            generators.add(new InferredDataPropertyCharacteristicAxiomGenerator());
    generators.add(new InferredEquivalentClassAxiomGenerator());
    generators.add(new InferredEquivalentDataPropertiesAxiomGenerator());
    generators.add(new InferredEquivalentObjectPropertyAxiomGenerator());
    generators.add(new InferredInverseObjectPropertiesAxiomGenerator());
    generators.add(new InferredObjectPropertyCharacteristicAxiomGenerator());
    
    // NOTE: InferredPropertyAssertionGenerator significantly slows down
    // inference computation
    generators.add(new org.semanticweb.owlapi.util.InferredPropertyAssertionGenerator());
    
    generators.add(new InferredSubClassAxiomGenerator());
    generators.add(new InferredSubDataPropertyAxiomGenerator());
    generators.add(new InferredSubObjectPropertyAxiomGenerator());
    List<InferredIndividualAxiomGenerator<? extends OWLIndividualAxiom>> individualAxioms= new ArrayList<InferredIndividualAxiomGenerator<? extends OWLIndividualAxiom>>();
		  generators.addAll(individualAxioms);
		  
        // We dynamically overwrite the default disjoint classes generator since it tries to 
        // encode the reasoning problem itself instead of using the appropriate methods in the 
        // reasoner. That bypasses all our optimisations and means there is not progress report :-( 
        // We don't want that!
        generators.add(new InferredDisjointClassesAxiomGenerator() {
            boolean precomputed=false;
            protected void addAxioms(OWLClass entity, OWLReasoner reasoner, OWLDataFactory dataFactory, Set<OWLDisjointClassesAxiom> result) {
                if (!precomputed) {
                    reasoner.precomputeInferences(InferenceType.DISJOINT_CLASSES);
                    precomputed=true;
                }
                for (OWLClass cls : reasoner.getDisjointClasses(entity).getFlattened()) {
                    result.add(dataFactory.getOWLDisjointClassesAxiom(entity, cls));
                }
            }
        });
        // We can now create an instance of InferredOntologyGenerator. 
        InferredOntologyGenerator iog=new InferredOntologyGenerator(reasoner,generators);
        // Before we actually generate the axioms into an ontology, we first have to create that ontology. 
        // The manager creates the for now empty ontology for the inferred axioms for us. 
        OWLOntology inferredAxiomsOntology=manager.createOntology();
        // Now we use the inferred ontology generator to fill the ontology. That might take some 
        // time since it involves possibly a lot of calls to the reasoner.    
        iog.fillOntology( df, inferredAxiomsOntology);
        // Now the axioms are computed and added to the ontology, but we still have to save 
        // the ontology into a file. Since we cannot write to relative files, we have to resolve the 
        // relative path to an absolute one in an OS independent form. We do this by (virtually) creating a 
        // file with a relative path from which we get the absolute file.  
        File inferredOntologyFile=new File(inferredFileName);
        if (!inferredOntologyFile.exists())
            inferredOntologyFile.createNewFile();
        inferredOntologyFile=inferredOntologyFile.getAbsoluteFile();
        // Now we create a stream since the ontology manager can then write to that stream. 
        OutputStream outputStream=new FileOutputStream(inferredOntologyFile);
        // We use the same format as for the input ontology.
        manager.saveOntology(inferredAxiomsOntology, manager.getOntologyFormat(ontology), outputStream);
        // Now that ontology that contains the inferred axioms should be in the ontologies subfolder 
        // (you Java IDE, e.g., Eclipse, might have to refresh its view of files in the file system) 
        // before the file is visible.  
        System.out.println("The ontology in " + inferredFileName + " should now contain all inferred axioms (you might need to refresh the IDE file view). ");
        }// End if consistencyCheck
        else
        {
            System.out.println("Inconsistent input Ontology, Please check the OWL File");
        }

**Comment by ignazio1977** [comment]
Do you have an ontology we can use to test this?

**Comment by karanthpallavi** [comment]
Yes, I used the standard pizza ontology at
https://github.com/owlcs/pizza-ontology/blob/master/pizza.owl

**Comment by sesuncedu** [comment]
I thought axioms from the original ontology weren't supposed to be copied
into the inferred ontology?

**Comment by karanthpallavi** [comment]
The inferred file contains only class and subclass axioms... Property axioms are lost...

**Comment by ignazio1977** [comment]
I've made minor changes to your code and run it with OWLAPI 4.3.1-SNAPSHOT and HermiT 1.3.8.431-SNAPSHOT (these versions contain fixes detailed in issue #646 )

The output file contains object properties.

    public static void main(String[] args) throws Exception {
        OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
        OWLOntology ontology = manager.loadOntology(
            IRI.create("https://raw.githubusercontent.com/owlcs/pizza-ontology/master/pizza.owl"));
        OWLDataFactory df = manager.getOWLDataFactory();

        Configuration configuration = new Configuration();
        configuration.ignoreUnsupportedDatatypes = true;
        ReasonerFactory rf = new ReasonerFactory();

        OWLReasoner reasoner = rf.createReasoner(ontology, configuration);
        boolean consistencyCheck = reasoner.isConsistent();
        if (consistencyCheck) {
            reasoner.precomputeInferences(InferenceType.CLASS_HIERARCHY,
                InferenceType.CLASS_ASSERTIONS, InferenceType.OBJECT_PROPERTY_HIERARCHY,
                InferenceType.DATA_PROPERTY_HIERARCHY, InferenceType.OBJECT_PROPERTY_ASSERTIONS);

            List<InferredAxiomGenerator<? extends OWLAxiom>> generators = new ArrayList<>();
            generators.add(new InferredSubClassAxiomGenerator());
            generators.add(new InferredClassAssertionAxiomGenerator());
            generators.add(new InferredDataPropertyCharacteristicAxiomGenerator());
            generators.add(new InferredEquivalentClassAxiomGenerator());
            generators.add(new InferredEquivalentDataPropertiesAxiomGenerator());
            generators.add(new InferredEquivalentObjectPropertyAxiomGenerator());
            generators.add(new InferredInverseObjectPropertiesAxiomGenerator());
            generators.add(new InferredObjectPropertyCharacteristicAxiomGenerator());

            // NOTE: InferredPropertyAssertionGenerator significantly slows down
            // inference computation
            generators.add(new org.semanticweb.owlapi.util.InferredPropertyAssertionGenerator());

            generators.add(new InferredSubClassAxiomGenerator());
            generators.add(new InferredSubDataPropertyAxiomGenerator());
            generators.add(new InferredSubObjectPropertyAxiomGenerator());
            List<InferredIndividualAxiomGenerator<? extends OWLIndividualAxiom>> individualAxioms =
                new ArrayList<>();
            generators.addAll(individualAxioms);

            generators.add(new InferredDisjointClassesAxiomGenerator());
            InferredOntologyGenerator iog = new InferredOntologyGenerator(reasoner, generators);
            OWLOntology inferredAxiomsOntology = manager.createOntology();
            iog.fillOntology(df, inferredAxiomsOntology);
            File inferredOntologyFile = new File("output.txt");
            // Now we create a stream since the ontology manager can then write to that stream.
            try (OutputStream outputStream = new FileOutputStream(inferredOntologyFile)) {
                // We use the same format as for the input ontology.
                manager.saveOntology(inferredAxiomsOntology, outputStream);
            }
        } // End if consistencyCheck
        else {
            System.out.println("Inconsistent input Ontology, Please check the OWL File");
        }
    }

**Comment by karanthpallavi** [comment]
Thanks for the update on this..
May i know how i can get the snapshot versions of these APIs?
Tried including in pom.xml, but it gives error as:
The POM for net.sourceforge.owlapi:org.semanticweb.hermit:jar:1.3.8.431-SNAPSHOT is missing, no dependency information available
The POM for net.sourceforge.owlapi:owlapi-api:jar:4.3.1-SNAPSHOT is missing, no dependency information available

**Comment by ignazio1977** [comment]
HermiT and owlapi have been released in the meantime, so you can use HermiT 1.3.8.431 now

**Comment by karanthpallavi** [comment]
Thanks a ton, Helped solve the issue, Properties appear in inferred file,
Thanks much for all the support
