### ISSUE TITLE
examples 4 - cannot import libraryíes

### ISSUE THREAD

**Issue by danish-monu** [owlcs/owlapi#649]
Hey

I am trying to run the examples at https://github.com/owlcs/owlapi/blob/version4/contract/src/test/java/org/semanticweb/owlapi/examples/Examples.java

But, i cannot import them.

does anybody has the solution?

org.coode.owlapi.manchesterowlsyntax.ManchesterOWLSyntaxOntologyFormat;
org.coode.owlapi.turtle.TurtleOntologyFormat;
org.semanticweb.owlapi.io.OWLXMLOntologyFormat;
org.semanticweb.owlapi.io.RDFXMLOntologyFormat;
org.semanticweb.owlapi.model.OWLOntologyFormat;

**Comment by ignazio1977** [comment]
Use this in your POM file

    <dependency>
    <groupId>net.sourceforge.owlapi</groupId>
    <artifactId>owlapi-distribution</artifactId>
    <version>4.3.1</version>
    </dependency>

**Comment by danish-monu** [comment]
thanks
