### ISSUE TITLE
Problem checking a profile

### ISSUE THREAD

**Issue by alanruttenberg** [owlcs/owlapi#650]
I'm getting an exception trying to check whether an ontology is in the DL Profile.
The call is effectively 
checker = new OWL2DLProfile
checker.checkOntology(ont)

The below is a lisp stack trace - sorry. The lines with exclamation at the start is the bit of java stack leading from the call to the exception.

    Java exception 'org.semanticweb.owlapi.model.OWLRuntimeException: No current axiom; is the walker being used outside of an ontology visit?'.
       [Condition of type java-exception]

    Backtrace:
      0: (invoke-debugger #<java-exception org.semanticweb.owlapi.model.OWLRuntimeException: No current axiom; is the walker being used outside of an ontology visit? {3F9F5DEE}>)
      1: org.armedbear.lisp.Lisp.error(Lisp.java:382)
      2: ! org.semanticweb.owlapi.util.OWLOntologyWalkerVisitor.getCurrentAxiom(OWLOntologyWalkerVisitor.java:48)
      3: ! org.semanticweb.owlapi.profiles.OWL2DLProfile$OWL2DLProfileObjectVisitor.visit(OWL2DLProfile.java:484)
      4: ! uk.ac.manchester.cs.owl.owlapi.OWLAnnotationPropertyImpl.accept(OWLAnnotationPropertyImpl.java:83)
      5: ! org.semanticweb.owlapi.util.OWLObjectWalker.passToVisitor(OWLObjectWalker.java:137)
      6: ! org.semanticweb.owlapi.util.StructureWalker.process(StructureWalker.java:87)
      7: ! org.semanticweb.owlapi.util.StructureWalker.visit(StructureWalker.java:687)
      8: ! uk.ac.manchester.cs.owl.owlapi.OWLAnnotationPropertyImpl.accept(OWLAnnotationPropertyImpl.java:83)
      9: ! org.semanticweb.owlapi.profiles.OWLOntologyProfileWalker$1.visit(OWLOntologyProfileWalker.java:56)
     10: ! uk.ac.manchester.cs.owl.owlapi.OWLAnnotationImpl.accept(OWLAnnotationImpl.java:141)
     11: ! org.semanticweb.owlapi.util.StructureWalker.process(StructureWalker.java:101)
     12: ! org.semanticweb.owlapi.util.StructureWalker.visit(StructureWalker.java:116)
     13: ! uk.ac.manchester.cs.owl.owlapi.OWLImmutableOntologyImpl.accept(OWLImmutableOntologyImpl.java:850)
     14: ! org.semanticweb.owlapi.util.OWLObjectWalker.walkStructure(OWLObjectWalker.java:181)
     15: ! org.semanticweb.owlapi.profiles.OWL2DLProfile.checkOntology(OWL2DLProfile.java:146)
     16: ! java.lang.reflect.Method.invoke(Method.java:497)
     17: (jcall "checkOntology" #<org.semanticweb.owlapi.profiles.OWL2DLProfile org.semanticweb.owlapi.profiles.OWL2DLProfile@389566c0 {6BCFFACE}> #<uk.ac.manchester.cs.owl.owlapi.concurrent.ConcurrentOWLOntol..

**Comment by ignazio1977** [comment]
It's a bug with ontology annotations - the profile has found a violation and it's trying to report it, but the exception is trying to use the current axiom in the output. Problem is, ontology annotations are not axioms.

Workaround: delete the ontology annotations before checking.

**Comment by alanruttenberg** [comment]
That works. That suggests that one can have an ontology violation in an ontology annotation(which I was actually trying to reproduce), which is surprising, particularly as in this case the violation would because of a value of an annotation property. This is the subject of a discussion https://github.com/OBOFoundry/OBOFoundry.github.io/issues/411#issuecomment-290044592 where I contend that annotations should not effect the determination of the profile. Your thoughts?

**Comment by sesuncedu** [comment]
Off the top of my head
1. Anonymous individuals as values violate EL
2. Using a object /data property as the  annotation property would be an
illegal  pun, but I'm not sure if that could trigger here.

**Comment by ignazio1977** [comment]
Which owlapi version is failing? There's a bug fix already in for this sort of error, and I can't match line 48 in the stack trace.

**Comment by alanruttenberg** [comment]
I'm using the maven dependency net.sourceforge.owlapi/owlapi-distribution/4.2.6 

Full set:

* org.slf4j/slf4j-api/1.7.21
* net.sourceforge.owlapi/pellet-cli-ignazio1977/2.4.0-ignazio1977
* org.semanticweb.elk/elk-reasoner/0.4.3
* net.sourceforge.owlapi/org.semanticweb.hermit/1.3.8.413
* net.sourceforge.owlapi/owlapi-distribution/4.2.6
* net.sourceforge.owlapi/owlexplanation/2.0.0
* factplusplus-1.6.4-SNAPSHOT.jar

**Comment by alanruttenberg** [comment]
bleh. I hate maven. Here's what it turns out is in my classpath when maven is done loading. 

* /net/sourceforge/owlapi/pellet-owlapi-ignazio1977/2.4.0-ignazio1977/pellet-owlapi-ignazio1977-2.4.0-ignazio1977.jar
* /net/sourceforge/owlapi/owlapi-distribution/4.1.3/owlapi-distribution-4.1.3.jar 
* /net/sourceforge/owlapi/owlapi-osgidistribution/4.1.3/owlapi-osgidistribution-4.1.3.jar
* /net/sourceforge/owlapi/owlapi-distribution/4.1.4/owlapi-distribution-4.1.4.jar
* /net/sourceforge/owlapi/owlapi-distribution/4.2.6/owlapi-distribution-4.2.6.jar


I'm not sure what java is doing with all this :-( or how to manage this without going into the complete hellhole of OSGI (where of the distributions have dependencies on protege!)

**Comment by alanruttenberg** [comment]
If, despite the dependencies on the earlier versions, they all can use the latest OWLAPIv4 then I can implement a filter during the maven processing that will prevent all but that being loaded.

**Comment by alanruttenberg** [comment]
***&^@%&*$&%@$!**

It's using 4.1.4, at least for `org.semanticweb.owlapi.reasoner.OWLReasonerRuntimeException` and `uk.ac.manchester.cs.owl.owlapi.OWLOntologyImpl`

Not your job, but I could really use some help figuring out a sane way to use all the reasoners in the same app.

**Comment by matentzn** [comment]
Second that (all reasoners in same app). It must be possible (since protege does it), but it is really cumbersome. Also the imports closure of Maven: I import so many tools that have explicit references to OWLAPI versions, that my pom.xml has more exclusion statements in there than actual dependencies (all to various owlapi distributions, like osgi, api, distribution and more). Alan, should we maybe write a post somewhere on how to properly build a multi reasoner application with OA4? With the exact pom that should be used and so on? How to avoid these versions clashing? 

W.r.t profiles: We should really start a discussion on 1) how profiles violations are justified and 2) how they should be repaired. I maintain my own version of the Profile checker, which is by now superseded by the OA4, but I dont want to give it up because of the repair strategies I implemented. Where would be the best place to discuss dubious violations? Here? One thread per dubious violation?

**Comment by ignazio1977** [comment]
Short term, exclusions are the only way. Long term, a list of guilty libraries would be useful.

I've been thinking how to combine an evolving api with this sort of dependency hell, and it's not easy.

Re alternative repairs: one issue with all the repairs, or a pull request - then we can work our way through them.

**Comment by alanruttenberg** [comment]
@matentzn +1 on posting something about building multi-reasoner applications. Also maybe an easy way to let reasoner writers test their implementation in such an environment. Ideally/Eventually this could turn into putting together a set of maven packages with proper dependencies so it's easy again.

Could you share your POM, btw? That will save me a bit of time. 

If the OWLAPI folks don't mind us having the discussion here we can use their issue list, using tags so devs know when it's not yet something to act on. If they would rather not, let's start another repo. I'm definitely interested in reviewing the different violations you've found.

Do you know about https://github.com/ontodev/robot ? Might be good to work with James to incorporate checks and suggestions and repairs into that as it is used by a number of ontologies in their release process.

**Comment by ignazio1977** [comment]
> If the OWLAPI folks don't mind us having the discussion here we can use their issue list

By all means.

A bunch of the libraries mentioned here are either stuff we've built or forked, or whose developers we know - so sorting an update to the latest OWLAPI should be easy enough.

(I don't remember what ELK's status is in this respect, but all the other reasoners have OWLAPI 5 compatible versions /hint /hint)

**Comment by ansell** [comment]
RDF4J ships with a BOM (Bill-Of-Materials) that should (almost certainly won't in all corner cases) select the expected OWLAPI version. The basic usage is to put the following inside of dependencyManagement/dependencies, with the keys being type=pom and scope=import that are together interpreted specially:

```
      <dependency>
        <groupId>org.eclipse.rdf4j</groupId>
        <artifactId>rdf4j-bom</artifactId>
        <version>${rdf4j.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
```

https://github.com/eclipse/rdf4j/blob/master/bom/pom.xml

May be useful to do the same thing for OWLAPI (and also pull in the RDF4J BOM into OWLAPI)
