### ISSUE TITLE
OWLAPI 5.0

### ISSUE THREAD

**Issue by zll15811176022** [owlcs/owlapi#653]
OWLAnnotationAssertionAxiom ax = df.getOWLAnnotationAssertionAxiom(prop,      cls.getIRI(),Literal("abc","en"),yy);

as shown above,why the third parameter is wrong?how can I correct it?my veision is OWLAPI5.0

**Comment by ignazio1977** [comment]
Is Literal() a method you've implemented, or does it refer to a utility class? If it's the one defined in the contract module of OWLAPI, it's only available in tests. Use `df.getOWLLiteral()` with the same arguments instead.
