### ISSUE TITLE
add annotations for annotationassertion

### ISSUE THREAD

**Issue by zll15811176022** [owlcs/owlapi#654]
I have added annotations X on a class A, how can add annotations on X with java programming(OWLAPI)？

**Comment by ignazio1977** [comment]
OWLDataFactory.getAnnotation() has a collection of annotations as last argument, these are taken as nested annotations - I.e., annotations on X in your example. Use 5.1.0 if you're using an RDF based format, there are important bug fixes on nested annotations included in the latest version.

**Comment by ignazio1977** [comment]
OWLAnnotationProperty prop=df.getOWLAnnotationProperty("http://purl.org/linguistics/gold/freeTranslation");
    OWLAnnotation yy = df.getOWLAnnotation(prop, df.getOWLLiteral(tab[x][4]));
    OWLAnnotationAssertionAxiom ax = df.getOWLAnnotationAssertionAxiom(prop, cls.getIRI(), df.getOWLLiteral("中文定义","cn"), Collections.singleton(yy));
