### ISSUE TITLE
Unable to get OntologyIRI in java using latest owl api jar file 

### ISSUE THREAD

**Issue by vaibhav1248** [owlcs/owlapi#656]
getOntologyIRI() returns an Optional which throws an error "The type com.google.common.base.Optional cannot be resolved. It is indirectly referenced from required .class files"

How to resolve it?

**Comment by csnyulas** [comment]
I am not sure from where exactly you get this exception thrown, but it seems that you are missing the guava Optional class. Base on the `pom.xml` file, OWLAPI has a dependency on Guava version 20.0:
https://github.com/owlcs/owlapi/blob/version5/pom.xml#L104
