### ISSUE TITLE
OWL/XML does not throw errors on XML files that are not valid OWL/XML

### ISSUE THREAD

**Issue by cmungall** [owlcs/owlapi#657]
Some of the OBO Library PURLs redirect to ontologies served from here:

http://ontologies.berkeleybop.org/

E.g. http://purl.obolibrary.org/obo/symp.owl -> http://ontologies.berkeleybop.org/symp.owl

Which is all good.

However, due to to a series of unfortunate events at our end, we ended up a PURL accidentally redirecting to the root http://ontologies.berkeleybop.org/

If this had failed fast, we would have noticed the error. Unfortunately, the OWLAPI will readibly think that the amazon S3 XML payload at this URL is an empty ontology:

```
$ owltools http://ontologies.berkeleybop.org/ -o /tmp/z
$ cat /tmp/z
<?xml version="1.0"?>
<rdf:RDF xmlns="http://www.w3.org/2002/07/owl#"
     xml:base="http://www.w3.org/2002/07/owl"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:owl="http://www.w3.org/2002/07/owl#"
     xmlns:xml="http://www.w3.org/XML/1998/namespace"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">
    <Ontology/>
</rdf:RDF>

<!-- Generated by the OWL API (version 4.2.6) https://github.com/owlcs/owlapi -->
```

Presumably it is syntactically valid empty ontology according to one of the N parsers. This is a problem with having so many concrete syntaxes...

I suppose we can have a fix at our end and simply throw an error if an ontology is empty and has no ontology IRI. But it might be nice to push the checks up to the OWLAPI. Not sure exactly how this would manifest, without accidentally rejecting perverse but valid intended ontologies.

**Comment by cmungall** [comment]
The XML looks like this btw:

```
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<Name>bbop-ontologies</Name>
<Prefix/>
<Marker/>
<MaxKeys>1000</MaxKeys>
<IsTruncated>true</IsTruncated>
<Contents>
<Key>aeo.obo</Key>
<LastModified>2016-11-24T23:12:24.000Z</LastModified>
<ETag>"f7a6a0717bd7ede5af05c87c4640e8f3"</ETag>
<Size>73206</Size>
<StorageClass>REDUCED_REDUNDANCY</StorageClass>
</Contents>
<Contents>
<Key>aeo.obo.gz</Key>
<LastModified>2017-04-10T10:00:36.000Z</LastModified>
<ETag>"8ea8655f83e4d9c13354421733e7c77c"</ETag>
<Size>14024</Size>
<StorageClass>REDUCED_REDUNDANCY</StorageClass>
</Contents>
...
```

**Comment by ignazio1977** [comment]
The OWL/XML parser believes this to be correct OWL/XML - I'm really surprised there isn't any error coming out of this...

In the meantime, if OWL/XML is not one of the languages you need, it can be banned from being used for parsing with a system property, see #510

**Comment by ignazio1977** [comment]
Forcing the OWL/XML parser to throw an exception on unrecognized tags works, to an extent. However, then the TriX parser considers the file a valid ontology...
Incidentally that's the same parser that caused #510, so it looks like the banning introduced to fix that bug is exactly what's needed here.
