### ISSUE TITLE
netbeans integration

### ISSUE THREAD

**Issue by danish-monu** [owlcs/owlapi#658]
i am making a gui in netbeans for handling of my ontologies.

I make a button, clicking which should load an ontology save in my hard disk.

When i build it and run with the comman java -jar .jar, 
and click the button meant for loading the ontology, the button does not do anything meaning its hanged somewhere.

the button works for method from non owlapi classes.

**Comment by sesuncedu** [comment]
There's not nearly enough information here to give any sort of diagnosis.  

What specific jars are loaded, what methods are invoked, what errors and exceptions are logged, etc.

**Comment by danish-monu** [comment]
i guess that is a maven configuration issue. i will resolve it. i guess it has to do with packaging the dependencies also in the jar something like this:

                   <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
