### ISSUE TITLE
Typo in OWLOntologyDocumentSource

### ISSUE THREAD

**Issue by hirokiht** [owlcs/owlapi#659]
I suppose hasAlredyFailedOnStreams() and hasAlredyFailedOnIRIResolution() should be named "hasAlready..." instead of "hasAlredy..."

**Comment by ignazio1977** [comment]
Indeed, problem is that the typo is part of a public interface and fixing it means risking non backward compatible changes.

In version 6 this will be fixed (because the methods re gone :-) )
