### ISSUE TITLE
EntitySearcher.getEquivalentClasses incorrectly returns itself

### ISSUE THREAD

**Issue by phillord** [owlcs/owlapi#663]
When using getEquivalentClasses, I find that it returns the class searched
for. While this is, I guess, logically correct, I think this is wrong because
it is inconsistent with the behaviour of, getSuperClasses and also
getEquivalentClasses when there is no other equivalent classes.

See following usage in tawny (sorry as always!)

    tawny.owl> (defontology o)
    #'tawny.owl/o
    tawny.owl> (defclass A)
    #'tawny.owl/A
    tawny.owl> (defclass B)
    #'tawny.owl/B
    tawny.owl> (defclass C :super A)
    #'tawny.owl/C
    tawny.owl> (defclass D :equivalent A)
    #'tawny.owl/D
    tawny.owl> (EntitySearcher/getSuperClasses C o)
    [#[Class 0x50830ccf A]]
    tawny.owl> (EntitySearcher/getEquivalentClasses C o)
    #{}
    tawny.owl> (EntitySearcher/getSuperClasses D o)
    []
    tawny.owl> (EntitySearcher/getEquivalentClasses D o)
    #{#[Class 0x50830ccf A] #[Class 0x62961680 D]}

As you an see getEquivalentClasses returns the empty set for C, but returns
both A and D for class D.

This is for version 4.

**Comment by wrclegg** [comment]
It is also inconsistent with 3.5 C.getEquivalentClasses(o) which it purports to replace.
