### ISSUE TITLE
Retrieve Class to which an Individual belongs to

### ISSUE THREAD

**Issue by ridoibm75** [owlcs/owlapi#666]
hello; 
i need to retrieve Class to which an Individual belongs to (i'm using OWL api 5.0) and this is my piece of code: 
```
for (OWLNamedIndividual m : sentence ) {    
   Searcher.values(myOntology.axioms(AxiomType.OBJECT_PROPERTY_ASSERTION), isComposedBy).peek(System.out::println);
System.out.println("INTERMEDIATE " + m);
EntitySearcher.getObjectPropertyValues(m, contains, myOntology). forEach(System.out::println);        
EntitySearcher.getTypes(m,myOntology).forEach(System.out::println);                                                                                                            } 
```
the 4th line return to me instances of properties OK 
in fact i want to use the result (output) of the 4th line in my last line to get the class of every instance 
i tried to declare my 4th line with a variable but i get an error : incompatible types ! because she return me void as type !

**Comment by ignazio1977** [comment]
for (OWLNamedIndividual m : sentence ) {    
       Searcher.values(myOntology.axioms(AxiomType.OBJECT_PROPERTY_ASSERTION), isComposedBy).peek(System.out::println);
    System.out.println("INTERMEDIATE " + m);
    List<OWLIndividual> list= OWLAPIStreamUtils.asList(EntitySearcher.getObjectPropertyValues(m, contains, myOntology));
    list.forEach(System.out::println);  
    EntitySearcher.getTypes(m,myOntology).forEach(System.out::println);

**Comment by ridoibm75** [comment]
Thank you for your answer, i understood your idea BUT in fact the problem is really in the last line ! because i want to retrieve the classes of every instance of the output 
so this instruction :
`EntitySearcher.getTypes(m,myOntology).forEach(System.out::println);` 
retrun to me the class of every sentence and it's logic because _'m'_ look the sentences :
`for (OWLNamedIndividual m : sentence )` 
So i need to replace the _'m'_ in the last instruction  
the variable **list** store the instances (let's suppose that these instances are words) 
when i replaced it i was obliged to cast it like this :
`EntitySearcher.getTypes((OWLIndividual) list, myOntology).forEach(System.out::println);  ` 
and i get error : 
> ClassCastException: java.util.ArrayList cannot be cast to org.semanticweb.owlapi.model.OWLIndividual

i wish that i was clear and sorry because i asked the question with the wrong instruction

**Comment by ignazio1977** [comment]
Don't cast the list. Iterate over it - with a for or with a .forEach call.

**Comment by ridoibm75** [comment]
what do mean please, my English is not as weel to inderstand every thing

**Comment by ignazio1977** [comment]
List<OWLIndividual> list= OWLAPIStreamUtils.asList(EntitySearcher.getObjectPropertyValues(m, contains, myOntology));
    list.forEach(i -> EntitySearcher.getTypes(i, myOntology).forEach(System.out::println));

**Comment by ridoibm75** [comment]
it works, 
my last question please : 
to get the short form in the out put 
i know with variables like OWLclass we need to do : myClass.getIRI().getShortForm() or getFragment()
i'm searching to get the same thing with varaibles like OWLIndividual 
Thank you so much Ignazio :)

**Comment by ignazio1977** [comment]
Only OWLNamedIndividual instances have an IRI, so you need to check and cast OWLIndividual instances to OWLNamedIndividual instances. Then they can be treated like classes and properties.

**Comment by ridoibm75** [comment]
i understood what are you saying & i did like this : 
```
List <OWLIndividual> list = OWLAPIStreamUtils.asList(EntitySearcher.getObjectPropertyValues(m, contains, myOntology)); 
OWLNamedIndividual list_final = (OWLNamedIndividual) list ;
list_final.forEach(i -> EntitySearcher.getTypes(i, myOntology).forEach(System.out::println));      
```   
i get error with the foreach ! 
let's suppose i do not have error !! How to call the getIRI().getShortForm() i mean where ? 
because with my class i know i can just use 
`System.out.println("MY CLASS : " + cls.getIRI().getShortForm());`

PS : to be honest, it's the first time to me to handle the _foreach_ and _system.ou::println_ 
this is my last question
thank you very much ...

**Comment by ignazio1977** [comment]
That's failing because you're still attempting to cast a collection to the class of one of its element. That's not going to work.

    List <OWLIndividual> list = OWLAPIStreamUtils.asList(
        EntitySearcher.getObjectPropertyValues(m, contains, myOntology)); 
    list.stream()
        .filter(x->x instanceof OWLNamedIndividual)
        .forEach(i -> EntitySearcher.getTypes(i, myOntology).forEach(System.out::println));

**Comment by ridoibm75** [comment]
Ok thank you for the explanation, we did a cast to OWLNamedIndividual with the variable x !
now i try to modify your code and add the necessary but i could not ! i mean how can i add the method getIRI().getShortForm ? where ? because i trtied to use the x, list to get the method but i couldn't ! 

My output is like this : 
<http://www.limics.fr/ontologies/ontoparon#Patient> 
BUT i want just : Patient

**Comment by ignazio1977** [comment]
List <OWLIndividual> list = OWLAPIStreamUtils.asList(
        EntitySearcher.getObjectPropertyValues(m, contains, myOntology)); 
    list.stream()
        .filter(x->x instanceof OWLNamedIndividual)
        .forEach(i -> EntitySearcher.getTypes(i, myOntology).forEach(j -> System.out.println(j.getIRI().getFragment()));

**Comment by ridoibm75** [comment]
yes i tried to do this, but i had an error with .getIRI() 
error : cannot find symbole !

**Comment by ignazio1977** [comment]
It is sufficient to test the type of returned superclasses and cast:

    list.stream()
        .filter(x->x instanceof OWLNamedIndividual)
        .forEach(i -> EntitySearcher.getTypes(i, myOntology)
            .filter(c->c instanceof OWLClass)
            .map(c->(OWLClass)c)
            .forEach(j -> System.out.println(j.getIRI().getFragment())));

**Comment by sathyamoorthyrr** [comment]
I'm extracting `Subject` from the `ObjectPropertyAssertions`

If the same word has multiple types, both are returned upon using `EntitySearcher.getTypes`

How can I get the type specified in the `ObjectPropertyAssertion`?

**Comment by ignazio1977** [comment]
An object property assertion axiom does not specify types for the individuals involved in the axiom, so the question doesn't have an answer as is. Can you provide an example?

Of the example is not related to this issue, feel free to create a new issue.
