### ISSUE TITLE
Profiles.OWL2_FULL returns Profiles.OWL2_DL

### ISSUE THREAD

**Issue by darrenleeweber** [owlcs/owlapi#667]
This issue started at https://github.com/ontodev/robot/issues/162, which tracks it upstream to the OWL-API.

**Comment by darrenleeweber** [comment]
I can't find the Profiles.java in the master branch.

**Comment by ignazio1977** [comment]
In master it has moved to the tools module.

It's a bug. I blame copy/paste.

**Comment by ignazio1977** [comment]
I see robot is using OWLAPI 4.2.6. Are you happy to update to 4.3.2 (once it's released)?

**Comment by ignazio1977** [comment]
Workaround is to manually instantiate OWL2Profile - Profiles is just a convenience to avoid creating unnecessary copies.

**Comment by jamesaoverton** [comment]
We've been trying to track the version of OWLAPI used by Protégé. The workaround should be fine. Thanks!
