### ISSUE TITLE
Reasoner support OWL API 5

### ISSUE THREAD

**Issue by matentzn** [owlcs/owlapi#669]
We have migrated most of our teaching to OWL API 5. However, as we make heavy use of reasoners, we do need urgently migrated versions (at least some good enough for teaching).

pellet-owlapi-ignazio1977 does not work because in OA 5, some "getFiller()" methods do not exist. 
jfact has some bugs (I just posted a critical one regarding equivalent classes).

Is there any reliable alternative we can use?

**Comment by ignazio1977** [comment]
Openllet

https://github.com/Galigator/openllet

**Comment by ignazio1977** [comment]
Also HermiT 1.3.8.510 (uses OWLAPI 5.1.0)

**Comment by matentzn** [comment]
This is perfect. Thanks a lot!
