### ISSUE TITLE
Enumeration (oneOf) - 3.5.x

### ISSUE THREAD

**Issue by Port8181** [owlcs/owlapi#670]
Hello,

I would like to add an enumerated class to an ontology like described in https://www.w3.org/TR/2004/REC-owl-guide-20040210/#EnumeratedClasses : 

```
<owl:Class rdf:ID="WineColor">
  <rdfs:subClassOf rdf:resource="#WineDescriptor"/>
  <owl:oneOf rdf:parseType="Collection">
    <owl:Thing rdf:about="#White"/>
    <owl:Thing rdf:about="#Rose"/>
    <owl:Thing rdf:about="#Red"/>
  </owl:oneOf>
</owl:Class>
```
How can I do this with owlapi version 3.5.x?

Thanks
Stefan

**Comment by ignazio1977** [comment]
The process is the same with all OWLAPI versions

    public static void main(String[] args)
        throws OWLOntologyCreationException, OWLOntologyStorageException {
        OWLOntologyManager m = OWLManager.createOWLOntologyManager();
        OWLDataFactory df = m.getOWLDataFactory();
        OWLOntology o = m.createOntology();
        OWLClass c1 = df.getOWLClass(IRI.create("urn:test:c1"));
        OWLNamedIndividual i1 = df.getOWLNamedIndividual(IRI.create("urn:test:i1"));
        OWLNamedIndividual i2 = df.getOWLNamedIndividual(IRI.create("urn:test:i2"));
        OWLNamedIndividual i3 = df.getOWLNamedIndividual(IRI.create("urn:test:i3"));
        OWLAxiom ax = df.getOWLSubClassOfAxiom(c1, df.getOWLObjectOneOf(i1, i2, i3));
        m.addAxiom(o, ax);
        m.saveOntology(o, System.out);
    }

**Comment by Port8181** [comment]
Thank you. Hmmm ... it is not exactly the same

```
    <Class rdf:about="#AccessModifierDomain">
        <rdfs:subClassOf>
            <Class>
                <oneOf rdf:parseType="Collection">
                    <rdf:Description rdf:about="#package"/>
                    <rdf:Description rdf:about="#private"/>
                    <rdf:Description rdf:about="#protected"/>
                    <rdf:Description rdf:about="#public"/>
                </oneOf>
            </Class>
        </rdfs:subClassOf>
    </Class>
```

Is it sematical equal?

**Comment by ignazio1977** [comment]
Yes. Ignore superficial differences in the XML output.

**Comment by Port8181** [comment]
Great, thank you :-)

**Comment by Port8181** [comment]
Sorry, I have to reopen the question. Maybe there was some confusion regarding my example. Your code generates the following owl:

```
    <Class rdf:about="urn:test:c1">
        <rdfs:subClassOf>
            <Class>
                <oneOf rdf:parseType="Collection">
                    <rdf:Description rdf:about="urn:test:i1"/>
                    <rdf:Description rdf:about="urn:test:i2"/>
                    <rdf:Description rdf:about="urn:test:i3"/>
                </oneOf>
            </Class>
        </rdfs:subClassOf>
    </Class>
  
    <NamedIndividual rdf:about="urn:test:i1"/>
    <NamedIndividual rdf:about="urn:test:i2"/>
    <NamedIndividual rdf:about="urn:test:i3"/>
```
But I would like to generate this owl:

```
    <Class rdf:about="urn:test:c1">
                <oneOf rdf:parseType="Collection">
                    <urn:test:c1 rdf:about="urn:test:i1"/>
                    <urn:test:c1 rdf:about="urn:test:i2"/>
                    <urn:test:c1 rdf:about="urn:test:i3"/>
                </oneOf>
    </Class>
  
    <urn:test:c1 rdf:about="urn:test:i1"/>
    <urn:test:c1 rdf:about="urn:test:i2"/>
    <urn:test:c1 rdf:about="urn:test:i3"/>
```
I compared both in Protege and it doesn't seems like that they are semantical equal. Could I achieve semantical equivalence if I call

`m.addAxiom(o, df.getOWLClassAssertionAxiom(c1, i1));`

for each individual?

**Comment by ignazio1977** [comment]
That cannot be a correct ontology. Ontologies are sets of axioms, and what you've written is a class expression only; it cannot appear by itself without a surrounding axiom in an OWL file.

Incidentally, such a class expression must be anonymous as well - it cannot be named `urn:test:c1`. See https://www.w3.org/TR/owl2-mapping-to-rdf/ for the RDF to OWL abstract syntax mapping.

Protege will not find the two forms equivalent because the second cannot be parsed; I believe it might produce a few annotations with a `oneof` annotation property, as the parser attempts to match the pattern to a known form.

**Comment by ignazio1977** [comment]
Have you tried creating the axioms you want in Protege and saving them to see what their serialization looks like?

**Comment by Port8181** [comment]
Hmmmm ... I'm a little confused. How does my example differ from the example in the "official" owl guide at https://www.w3.org/TR/2004/REC-owl-guide-20040210/#EnumeratedClasses ? But I have to admit, that I'm not an owl pro :-( . 

I had to google how to add a "oneOf-relation". It seems like I have to add the set of the [individuals as equivalent class](http://stackoverflow.com/questions/28004964/using-owloneof-in-protege). This generates the following code:

```
<owl:Class rdf:about="http://www.semanticweb.org/stefan/ontologies/2017/4/untitled-ontology-15#WineColor">
	<owl:equivalentClass>
		<owl:Class>
			<owl:oneOf rdf:parseType="Collection">
				<rdf:Description rdf:about="http://www.semanticweb.org/stefan/ontologies/2017/4/untitled-ontology-15#Red"/>
				<rdf:Description rdf:about="http://www.semanticweb.org/stefan/ontologies/2017/4/untitled-ontology-15#Rose"/>
				<rdf:Description rdf:about="http://www.semanticweb.org/stefan/ontologies/2017/4/untitled-ontology-15#White"/>
			</owl:oneOf>
		</owl:Class>
	</owl:equivalentClass>
</owl:Class>

<owl:NamedIndividual rdf:about="http://www.semanticweb.org/stefan/ontologies/2017/4/untitled-ontology-15#Red">
	<rdf:type rdf:resource="http://www.semanticweb.org/stefan/ontologies/2017/4/untitled-ontology-15#WineColor"/>
</owl:NamedIndividual>

<owl:NamedIndividual rdf:about="http://www.semanticweb.org/stefan/ontologies/2017/4/untitled-ontology-15#Rose">
	<rdf:type rdf:resource="http://www.semanticweb.org/stefan/ontologies/2017/4/untitled-ontology-15#WineColor"/>
</owl:NamedIndividual>

<owl:NamedIndividual rdf:about="http://www.semanticweb.org/stefan/ontologies/2017/4/untitled-ontology-15#White">
	<rdf:type rdf:resource="http://www.semanticweb.org/stefan/ontologies/2017/4/untitled-ontology-15#WineColor"/>
</owl:NamedIndividual>
```

which does not seem to be much different from your code. So I guess you're right but the w3 example is still confusing ...

**Comment by ignazio1977** [comment]
Those examples are indeed confusing - they're showing two axioms each (the `rdfs:subClassOf` term only appears in axioms, not class expressions). Part of the problem might be that that's the 2004 version of the OWL guide, and so it refers to OWL 1. OWLAPI 3.5 and newer refer to OWL 2.

**Comment by Port8181** [comment]
ok, thanks for your explanation :-)
