### ISSUE TITLE
setSubClass Disjoint Error

### ISSUE THREAD

**Issue by asbhavsar** [owlcs/owlapi#672]
I am getting below error when I am trying to make all subclasses of my super class disjoint.

  Animals.setSubclassesDisjoint(true);
  
I am getting the below exception

Exception in thread "main" java.lang.RuntimeException: Could not find slot http://protege.stanford.edu/plugins/owl/protege#subclassesDisjoint
	at edu.stanford.smi.protegex.owl.model.impl.DefaultOWLNamedClass.setSubclassesDisjoint(Unknown Source)
	at version1.myOntology.ont1(myOntology.java:482)
	at version1.myOntology.main(myOntology.java:47)

**Comment by ignazio1977** [comment]
You're going to have to show more code for us to help.

As far as I can tell setSubclassesDisjoint is not owlapi code.

**Comment by ignazio1977** [comment]
You're going to have to show more code for us to help.

As far as I can tell setSubclassesDisjoint is not owlapi code.

**Comment by asbhavsar** [comment]
below is my full code. if setSubclassesDisjoint  is not the owl api then
what is the way to make classes disjoint in owl ?

import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.OWLNamedClass;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.OWLObjectProperty;
import edu.stanford.smi.protege.exception.OntologyLoadException;
import edu.stanford.smi.protegex.owl.ProtegeOWL;
import edu.stanford.smi.protegex.owl.ui.properties.*;
import edu.stanford.smi.protegex.owl.model.ProtegeSlot;
import edu.stanford.smi.protege.exception.OntologyLoadException;
import edu.stanford.smi.protegex.owl.jena.*;
import edu.stanford.smi.protegex.owl.jena.JenaOWLModel;

public class myOntology {
public static void main(String args[]){
OWLModel owlModel = ProtegeOWL.createJenaOWLModel();
owlModel.getNamespaceManager().setDefaultNamespace("http://www.test.com#");
OWLNamedClass mythings = owlModel.createOWLNamedClass("mythings");
OWLNamedClass animal = owlModel.createOWLNamedSubclass("Animals",mythings);
OWLNamedClass human = owlModel.createOWLNamedSubclass("Animals",humans);
mythings.setSubclassesDisjoint(true);
}
}

Thanks,
AB

On Thu, Jun 1, 2017 at 10:54 AM, Ignazio Palmisano <notifications@github.com

**Comment by ignazio1977** [comment]
As I thought - this is Protégé 3.5 api, which was Jena based. I know very little about this code base, you'll get better help on the protégé project mailing list or on one of the github projects under the protegeproject umbrella.
