### ISSUE TITLE
Best Way to Search a OWL class

### ISSUE THREAD

**Issue by asbhavsar** [owlcs/owlapi#674]
Hi All,

Can someone tell me what would be the fastest way to search a particular Class from a set of OWL classes?

I am basically trying to get a search a class from a set using the class name and getting a reference to that class so that I can assign restrictions and properties dynamically.

Thanks,
Anurag

**Comment by csnyulas** [comment]
@asbhavsar, as I suggested on the Protégé mailing list, you should provide more information. Also, it  would be much more appropriate to make this a question on the OWL API mailing list, rather than an issue on the AWL API issue tracker.

**Comment by ignazio1977** [comment]
@csnyulas an issue is ok - it can be tagged as a question. But yes, more information is useful.

**Comment by ignazio1977** [comment]
@asbhavsar by name what do you mean exactly? The full IRI? In that case the fastest way is to use an `OWLDataFactory` and call `OWLDataFactory::getOWLClass(IRI)`.

If you mean the IRI fragment, then there is no 'fastest way'. IRI fragments are not indexed and potentially not unique, so the only way is to iterate through the classes in the set and check if the IRI ends with the fragment you have. You could build a reverse map from fragment to class, if you're repeating this operation very often.

**Comment by asbhavsar** [comment]
Thank you. That helps!

On Tue, Jun 13, 2017 at 1:02 PM, Ignazio Palmisano <notifications@github.com

**Comment by paulbauriegel** [comment]
What would then be the best way to list **all** OWLClasses in the ontology

**Comment by ignazio1977** [comment]
`OWLOntology::classesInSignature()`
