### ISSUE TITLE
ConcurrentModificationException using Hermit 1.3.8.413 in Protege 5.2

### ISSUE THREAD

**Issue by alanruttenberg** [owlcs/owlapi#675]
Not really sure where the problem is. Attached are the ontologies. To reproduce, load database-to-ontology.owl, which will import the other one. In preferences>reasoner>initialization check off
* class hierarchy
* class assertions
* object property assertions
* same individuals.

If I uncheck same individuals the exception does not occur.

For displayed inferences I have all the class inferences and individual inferences checked off.

Pellet in the same Protege version reasons without an error. Fact++ doesn't because of the hasKey axioms.

An oddity: The class patient does not display any instances, though a dl-query for instance of patient works fine. Maybe a Protege thing.

[database-to-ontology.owl.txt](https://github.com/owlcs/owlapi/files/1087015/database-to-ontology.owl.txt)
[database-mapped.owl.txt](https://github.com/owlcs/owlapi/files/1087014/database-mapped.owl.txt)

**Comment by ignazio1977** [comment]
Does it happen also with HermiT 1.3.8.431?

**Comment by alanruttenberg** [comment]
Not offered using the update function in Protege. Is there a protege plugin version?

**Comment by ignazio1977** [comment]
Yes the maven artifact on Maven Central is also a Protege plugin, you can just replace the jar in the Protege installation and it will be picked up.

http://repo1.maven.org/maven2/net/sourceforge/owlapi/org.semanticweb.hermit/1.3.8.431/org.semanticweb.hermit-1.3.8.431.jar

**Comment by ignazio1977** [comment]
There's a set being updated while it is also being iterated on - bug in HermiT. Will be fixed and available in the next release.

**Comment by ignazio1977** [comment]
HermiT 1.4.0.432 has been released and is available on Maven Central; currently it must be installed manually in Protege, copying the jar file in the protege folder and deleting the existing HermiT file.
