### ISSUE TITLE
How to populate owl file with new individual

### ISSUE THREAD

**Issue by Ebiyejames** [owlcs/owlapi#676]
Hello,
I have been trying to populate an owl file which I created with Protege 5.1.0 with new individuals using the OWL API in order to add them automatically. The main issues is that adding the individuals into the owl file and saving it will overwrite previous information. See my code:

    public static void main(String[] args) throws OWLOntologyCreationException, OWLOntologyStorageException {
        OWLOntologyManager man = OWLManager.createOWLOntologyManager();
        String base = "http://www.semanticweb.org/faweib.j/ontologies/2017/5/untitled-ontology-53";
        OWLOntology ont = man.createOntology(IRI.create(base));
        OWLDataFactory dataFactory = man.getOWLDataFactory();
        
        String Subject = "#James";
        
        String Object = "#Larceny1";
       
        OWLIndividual subject = dataFactory.getOWLNamedIndividual(IRI.create(base + Subject));
        OWLIndividual object = dataFactory.getOWLNamedIndividual(IRI.create(base + Object));
        
        OWLClass personClass = dataFactory.getOWLClass(IRI.create(base + "#Person"));
        OWLClass crimeClass = dataFactory.getOWLClass(IRI.create(base + "#Crime"));
        
        OWLClassAssertionAxiom ax = dataFactory.getOWLClassAssertionAxiom(personClass, subject);
        OWLClassAssertionAxiom ax1 = dataFactory.getOWLClassAssertionAxiom(crimeClass, object);
        
        man.addAxiom(ont, ax);
        man.addAxiom(ont, ax1);
        File file = new File("C:\\Users\\Fawei B. J\\Downloads\\TE.owl");
        
        man.saveOntology(ont, IRI.create(file));
        System.out.println("Data assertion was successful!");
    }

I need some kind assistance.

Kind regards
Ebiye

**Comment by ignazio1977** [comment]
In order to add to an existing ontology without overwriting the existing information, load the file instead of creating the ontology from scratch.

    File file = new File("C:\\Users\\Fawei B. J\\Downloads\\TE.owl");
    OWLOntology ont = man.loadOntologyFromOntologyDocument(file);

**Comment by Ebiyejames** [comment]
Hello

Thanks a lot for the new information. However, loading the ontology with
this method, I have this problem "The method create(String) in the type IRI
is not applicable for the arguments (OWLOntology)". See portion of code
having this error:

OWLOntology ont1 = manager.loadOntologyFromOntologyDocument(file);
manager.saveOntology(ont, IRI.create(ont1));

How do I fix this error?


Kind regards
Ebiye

On Sat, Jun 24, 2017 at 9:48 PM, Ignazio Palmisano <notifications@github.com

**Comment by ignazio1977** [comment]
I did not suggest to load a new ontology, but to change the creation of the ont variable.

Put the two lines I wrote in place of the declaration of ont in your original code.
