### ISSUE TITLE
Pellet Reasoner Error

### ISSUE THREAD

**Issue by asbhavsar** [owlcs/owlapi#679]
I am getting below error when I am trying to create an instance of Pellet reasoner. Can some one help me here : 

Exception in thread "main" java.lang.NoSuchMethodError: org.semanticweb.owlapi.model.OWLObjectSomeValuesFrom.getProperty()Lorg/semanticweb/owlapi/model/OWLObjectPropertyExpression;

This is how I am creating the reasoner

OWLReasonerFactory reasonerFactory1 = new PelletReasonerFactory();
OWLReasoner reasoner1 = reasonerFactory1.createReasoner(ontology);

below are my maven dependencies : 

<dependency>
    <groupId>net.sourceforge.owlapi</groupId>
    <artifactId>pellet-owlapi-ignazio1977</artifactId>
    <version>2.4.0-ignazio1977</version>
</dependency>

 <dependency>
    <groupId>net.sourceforge.owlapi</groupId>
    <artifactId>owlapi-distribution</artifactId>
    <version>4.0.0</version>
 </dependency>

Thanks,
AB

**Comment by ignazio1977** [comment]
Pellet 2.4.0 requires OWLAPI 4.0.2 or newer (up to 4.3.1 it should be fine)
