### ISSUE TITLE
[Question] Help migrating to version 5.1.0

### ISSUE THREAD

**Issue by sadger** [owlcs/owlapi#680]
Hello,

In the process of converting my code from version 3.5.2 to 5.1.0  and trying to remove the deprecated warnings from my code.  My application mainly focuses on using `OWLLogicalAxioms` and I used to call the `OWLOntology.getLogicalAxioms()` method to retrieve a `Set<OWLLogicalAxiom>` what's the best way to do this with the new stream API? Similarly how do I filter a  `Set<OWLClass>`  objects from `axiom.signature()` stream?

Secondly I want to set the default renderer to use the DLSyntaxRenderer so when System.out.println() anything it will render using DL Syntax . Is this still possible? I used to do something like this:

```
DLSyntaxObjectRenderer renderer =  new DLSyntaxObjectRenderer();
OWLObjectRenderer stringRender =  ToStringRenderer.getInstance();
stringRender.setRenderer(renderer)

```

Thanks

**Comment by ignazio1977** [comment]
You can use directly the `Stream` if you only need to iterate over the logical axioms. For repeated lookups, you should collect the axioms in a set, there's a utility in OWLAPI but you can do this with Java alone by using `Stream::collect`

    OWLAPIStreamUtils.asSet(o.logicalAxioms());

The same method can be used for any Stream object.

Regarding the renderer, you need to set a Provider object now:

    DLSyntaxObjectRenderer renderer =  new DLSyntaxObjectRenderer();
    ToStringRenderer.setRenderer(()->renderer);

**Comment by sadger** [comment]
Great, thanks for your reply. Will give it a go.
