### ISSUE TITLE
Memory issues with reasoners

### ISSUE THREAD

**Issue by asbhavsar** [owlcs/owlapi#681]
I am trying to run JFact/Pellet/Hermit reasoner over a very large ontology but I am continuously getting Java Heap memory error. Can someone help me understand how much this reasoner scale? Or any faster reasoned and less heap memory greedy reasoners which support closure axioms. I have made sure to follow best of the coding standards and also manually called garbage collector before reasoning. Thank you!

**Comment by ignazio1977** [comment]
Depending on the ontology expressivity, you might have better luck with ELK https://github.com/liveontologies/elk-reasoner/wiki/ElkOwlApi

Which size did you set for the java heap?

**Comment by asbhavsar** [comment]
I have set 12GB as my heap size. Yes, ELK does help but as my Ontology has
Closure Axioms which is not supported by ELK, I am looking for other
options.

Thanks,
AB

On Tue, Jul 11, 2017 at 1:16 AM, Ignazio Palmisano <notifications@github.com

**Comment by ignazio1977** [comment]
Can you explain what closure axioms are?

**Comment by asbhavsar** [comment]
The use of "only"(ObjectAllValuesFrom. Axiom). For example, hasPart only
PlasmaMembrane.

Also, my Ontology has ObjectPropertyRange Axiom which is also not supported
by ELK.



On Tue, Jul 11, 2017 at 3:44 PM, Ignazio Palmisano <notifications@github.com

**Comment by ignazio1977** [comment]
I think for very large ontologies your best bet are reasoners that use modularisation or atomic decomposition to reduce the size of the (sub)ontologies they work with. I am aware of MORe and TRoWL, there's an experiment I've worked on called Chainsaw, and I believe others are working on this topic but cannot find the links at the moment. I hope this provides some pointers.

**Comment by ykazakov** [comment]
ObjectPropertyRange axioms will be supported in ELK. You can try it with [the development snapshots of ELK](https://github.com/liveontologies/elk-reasoner/wiki/GettingElk#development-snapshot-builds)
Which other features (in addition to ObjectAllValuesFrom and ObjectPropertyRange) do you have for which ELK complains?

You could also try the [Konclude reasoner](http://derivo.de/produkte/konclude/). It is currently the fastest reasoner that supports almost all of OWL. But if you need to access it from OWL API, you need to use OWL Link, which can be slow for large ontologies.
