### ISSUE TITLE
OWL API - Need to get all properties for which a class is in the domain/range of the property

### ISSUE THREAD

**Issue by karanthpallavi** [owlcs/owlapi#682]
My application needs to get all properties for which class A or any of its subclasses are in the property's domain or range.
Tried getting classesInSignature for a property, its not working.
May i know how to get classes involved as domain and range in a property?
Also, how can we compute subgraph with just class and its properties?
Need your help on this issue.
Thanks

**Comment by karanthpallavi** [comment]
Please help me in getting object properties for which a class in question is the domain or range of the property.

**Comment by ignazio1977** [comment]
Sorry for the delay, I'll answer your question once I get back to my laptop.

**Comment by karanthpallavi** [comment]
sure, thanks

**Comment by ignazio1977** [comment]
You can use an `OWLReasoner` and the `getDataPropertyDomains()` and `getObjectPropertyDomains()` for domains - and the corresponding `-Ranges()` method for object properties; this will provide complete results.

If you cannot use a reasoner, you can get partial results looking for asserted domains/ranges:

    OWLOntology o = ...
    OWLObjectProperty p = ...
    o.objectPropertyDomainAxioms(p).map(x->x.getDomain());

You might also be interested in the subclasses of each of the returned classes; however, without a reasoner there could be missing ranges, as the OWLOntology interface does no inference.

A subgraph composed only of a class and its properties is more complex to determine, as it's not as well defined a concept as it sounds. I recommend reading up on modularisation for the theoretical background.

A rough solution is to collect the axioms shown above:

    o.objectPropertyDomainAxioms(p);
    o.objectPropertyRangeAxioms(p);
    o.dataPropertyDomainAxioms(p);

and add the referencing axioms:
    o.referencingAxioms(p);

This should include all the axioms you need.

**Comment by karanthpallavi** [comment]
Thanks for this answer,
May i also know how i can get a subgraph of few classes, their connecting properties from an ontology?
Thanks in advance

**Comment by ignazio1977** [comment]
You can either apply the same process to classes (using `getReferencingAxioms()`) or use the modularisation techniques I mentioned above. The best approach depends on what your requirements are.

**Comment by karanthpallavi** [comment]
Sorry for more doubts,
Being a novice to OWL API,
few more doubts.
From Ontology, how do i get object property expressions from reasoner or ontology to send as parameter to OWLObjectPropertyDomains function?
Thanks

**Comment by karanthpallavi** [comment]
May i get help on this please?
How to get object property expressions for all object properties in an ontology?
Kindly help.

**Comment by ignazio1977** [comment]
The ontology has methods to access all the declared properties:

    o.objectPropertiesInSignature()

**Comment by karanthpallavi** [comment]
Thanks much
