### ISSUE TITLE
java.lang.ClassCastException: org.semanticweb.owlapi.reasoner.impl.OWLClassNode cannot be cast to org.semanticweb.owlapi.model.OWLClass

### ISSUE THREAD

**Issue by karanthpallavi** [owlcs/owlapi#685]
Have got classes in domain of a property by using:
          NodeSet<OWLClass> classesAsDomainOfProp = reasoner.getObjectPropertyDomains((OWLObjectPropertyExpression) propInQues, true);

When i try to get the individual class in classesAsDomainOfProp in:
            Iterator clsIter = classesAsDomainOfProp.iterator();
            while(clsIter.hasNext())
            {
                OWLClass classAsDomain = (OWLClass)clsIter.next();
            }
I get ClassCastException, how can i avoid this?
Where am i going wrong?
Kindly help

**Comment by ignazio1977** [comment]
`NodeSet::iterator()` returns an iterator of `OWLClassNode` objects, not of `OWLClass` objects.

A Node has potentially multiple OWLClass entities contained (all inferred to be equivalent to each other). To explore, you can use the `.iterator()` or `.entities()` methods and iterate on them. The objects contained are then `OWLClass` objects.

**Comment by karanthpallavi** [comment]
Thanks for your response, tried using the method contains for classesAsDomainOfProp,
Thanks much
