### ISSUE TITLE
Why aren't axioms from the original ontology  present in a generated inferred ontology? (was: Domains and Ranges disappear in inferred ontology file) 

### ISSUE THREAD

**Issue by karanthpallavi** [owlcs/owlapi#686]
Have used Hermit Reasoner 1.3.8.431 and OWL API 4.0.2, Following is my inference code:

Reasoner.ReasonerFactory rf = new Reasoner.ReasonerFactory() {
            @Override
            public OWLReasoner createReasoner(OWLOntology ontology,
OWLReasonerConfiguration config) {
                Configuration configuration = new Configuration();
                configuration.ignoreUnsupportedDatatypes = true;
                return super.createReasoner(ontology, configuration);
                }
        };
          
        Reasoner reasoner=(Reasoner)rf.createReasoner(ontology);
        boolean consistencyCheck = reasoner.isConsistent();
        if(consistencyCheck)
        {
            reasoner.precomputeInferences(InferenceType.CLASS_HIERARCHY, InferenceType.CLASS_ASSERTIONS, InferenceType.OBJECT_PROPERTY_HIERARCHY, InferenceType.DATA_PROPERTY_HIERARCHY, InferenceType.OBJECT_PROPERTY_ASSERTIONS);
        // We now have to decide which kinds of inferences we want to compute. For different types 
        // there are different InferredAxiomGenerator implementations available in the OWL API and 
        // we use the InferredSubClassAxiomGenerator and the InferredClassAssertionAxiomGenerator 
        // here. The different generators are added to a list that is then passed to an 
        // InferredOntologyGenerator. 
            List<InferredAxiomGenerator<? extends OWLAxiom>> generators=new ArrayList<InferredAxiomGenerator<? extends OWLAxiom>>();
            generators.add(new InferredSubClassAxiomGenerator());
            generators.add(new InferredClassAssertionAxiomGenerator());
            generators.add(new InferredDataPropertyCharacteristicAxiomGenerator());
    generators.add(new InferredEquivalentClassAxiomGenerator());
    generators.add(new InferredEquivalentDataPropertiesAxiomGenerator());
    generators.add(new InferredEquivalentObjectPropertyAxiomGenerator());
    generators.add(new InferredInverseObjectPropertiesAxiomGenerator());
    generators.add(new InferredObjectPropertyCharacteristicAxiomGenerator());
    
    // NOTE: InferredPropertyAssertionGenerator significantly slows down
    // inference computation
    generators.add(new org.semanticweb.owlapi.util.InferredPropertyAssertionGenerator());
    
    generators.add(new InferredSubClassAxiomGenerator());
    generators.add(new InferredSubDataPropertyAxiomGenerator());
    generators.add(new InferredSubObjectPropertyAxiomGenerator());
    List<InferredIndividualAxiomGenerator<? extends OWLIndividualAxiom>> individualAxioms= new ArrayList<InferredIndividualAxiomGenerator<? extends OWLIndividualAxiom>>();
		  generators.addAll(individualAxioms);
		  
        // We dynamically overwrite the default disjoint classes generator since it tries to 
        // encode the reasoning problem itself instead of using the appropriate methods in the 
        // reasoner. That bypasses all our optimisations and means there is not progress report :-( 
        // We don't want that!
        generators.add(new InferredDisjointClassesAxiomGenerator() {
            boolean precomputed=false;
            protected void addAxioms(OWLClass entity, OWLReasoner reasoner, OWLDataFactory dataFactory, Set<OWLDisjointClassesAxiom> result) {
                if (!precomputed) {
                    reasoner.precomputeInferences(InferenceType.DISJOINT_CLASSES);
                    precomputed=true;
                }
                for (OWLClass cls : reasoner.getDisjointClasses(entity).getFlattened()) {
                    result.add(dataFactory.getOWLDisjointClassesAxiom(entity, cls));
                }
            }
        });
        // We can now create an instance of InferredOntologyGenerator. 
        InferredOntologyGenerator iog=new InferredOntologyGenerator(reasoner,generators);
        // Before we actually generate the axioms into an ontology, we first have to create that ontology. 
        // The manager creates the for now empty ontology for the inferred axioms for us. 
        OWLOntology inferredAxiomsOntology=manager.createOntology();
        OWLOntology inferredTriplesOntology = manager.createOntology();
        // Now we use the inferred ontology generator to fill the ontology. That might take some 
        // time since it involves possibly a lot of calls to the reasoner.    
        iog.fillOntology( df, inferredAxiomsOntology);
        iog.fillOntology(df,inferredTriplesOntology);
        // Now the axioms are computed and added to the ontology, but we still have to save 
        // the ontology into a file. Since we cannot write to relative files, we have to resolve the 
        // relative path to an absolute one in an OS independent form. We do this by (virtually) creating a 
        // file with a relative path from which we get the absolute file.  
        File inferredOntologyFile=new File(inferredFileName);
        if (!inferredOntologyFile.exists())
            inferredOntologyFile.createNewFile();
        inferredOntologyFile=inferredOntologyFile.getAbsoluteFile();

In the inferred file, properties exist along with equivalent, inverse, property hierarchy but no domain and range 
Kindly help in resolving this

**Comment by sesuncedu** [comment]
The ontology generated by InferredOntologyGenerator contains only  inferred axioms. It does not  copy axioms from the original ontology. If you want to create an ontology document containing the axioms from both, you just need to get the axioms from the original ontology object , and add them to the new one.

**Comment by karanthpallavi** [comment]
May I know how to copy all original axioms to new inferred ontology?
Thanks much

**Comment by ignazio1977** [comment]
manager.addAxioms(inferredAxiomsOntology, ontology.getAxioms());

**Comment by karanthpallavi** [comment]
Thanks for the support
