### ISSUE TITLE
Did this api used to be called org.semanticweb.owl?

### ISSUE THREAD

**Issue by leesue630** [owlcs/owlapi#688]
the SKOS API imports org.semanticweb.owl and does not work.

**Comment by ignazio1977** [comment]
That's not clear. In which way does the SKOS api not work? org.semantic.web is not a library name, as far as I know. the OWL API has always been called its current name.

**Comment by leesue630** [comment]
SKOS API uses "import org.semanticweb.owl" and when trying to run the code using the newest owl api version results in a class not found exception. I went threw previous versions and the owl api version 2.2.0 seems to work. Thank you for your response!

**Comment by ignazio1977** [comment]
I would strongly discourage that. SKOS API 3.2 was released last month and it uses OWLAPI 4.2.8. OWLAPI 2.2 was for OWL 1.0 and is years old. SKOS SPI has not used it for years.

Show us which class not found exception you get and we might be able to help.

**Comment by leesue630** [comment]
Turns out I was downloading the jar file from http://skosapi.sourceforge.net/source.html and looking at code from https://sourceforge.net/p/skosapi/code/HEAD/tree/version_3/. This code is indeed from 2011 and that is why I was confused. I did, however, find the java-skos-api github page and have downloaded the latest skos api and everything now works using the owl api 4.2.8. Sorry for the hassle!

**Comment by ignazio1977** [comment]
No worries
