### ISSUE TITLE
How to get Object Property Chains present in an ontology and delete the chain axioms?

### ISSUE THREAD

**Issue by karanthpallavi** [owlcs/owlapi#690]

**Comment by ignazio1977** [comment]
Chains are accessed same as other types of axioms:

    ontology.axioms(AxiomType.SUB_PROPERTY_CHAIN_OF)

Removal of axioms is via `OWLOntologyManager::removeAxoms(OWLOntology, Collection<OWLAxiom>)` or `OWLOntology::removeAxioms(Collection<OWLAxiom>)`

**Comment by karanthpallavi** [comment]
Thanks a ton!
