### ISSUE TITLE
Exception in thread "main" java.lang.ClassCastException: uk.ac.manchester.cs.owl.owlapi.OWLClassImpl cannot be cast to java.lang.CharSequence

### ISSUE THREAD

**Issue by karanthpallavi** [owlcs/owlapi#691]
Have this code which throws ClassCastException:

OWLObjectProperty propInQues = (OWLObjectProperty) propIter.next();
            classesAsDomainOfProp = reasoner.getObjectPropertyDomains((OWLObjectPropertyExpression) propInQues, true);
String classAsDomainName = classesAsDomainOfProp.getFlattened().toString();
            boolean classAsDomainContainsClassName = classAsDomainName.contains((CharSequence) className);
            if(classAsDomainContainsClassName)
            {
                System.out.println("if satisfied");
                String PropertyName = propInQues.getIRI().getShortForm();
                System.out.println(PropertyName+" is added \n");
                propNames.add(PropertyName);
                break;
            }

It throws ClassCastException, Kindly help

**Comment by ignazio1977** [comment]
You have three problems here:

- you're not showing the declaration of className
- className is an OWLClass not a CharSequence. Casting cannot change the type of objects
- you're turning a collection of objects into a string for the purpose of checking that it contains an object. Why? Just check that the collection contains the object

**Comment by karanthpallavi** [comment]
Thanks for pointing them out,
I have tried using this:
if(classesAsDomainOfProp.containsEntity(className))

This is not working,
classesAsDomainOfProp.getFlattened().toString() prints:
[<http://www.semanticweb.org/drkm/ontologies/2017/4/untitled-ontology-82#FoodOrDrink>]
Contents of className is:
http://www.semanticweb.org/drkm/ontologies/2017/4/untitled-ontology-82#FoodOrDrink

Anyways, will check out what has gone wrong..
