### ISSUE TITLE
How obtain information of OWLAnonymousIndividual [question]

### ISSUE THREAD

**Issue by luca-tom** [owlcs/owlapi#693]
I try to read file owl with OWLApi, from this part of file:

	:RGBCapability rdf:type owl:Class ;
		rdfs:subClassOf :Capability ,
			[ rdf:type owl:Restriction ;
				owl:onProperty :hasParameter ;
				owl:hasValue [ 
					rdf:type :Parameter ;
					:name "g"^^xsd:string ;
					:mandatory "true"^^xsd:boolean ;
					:hasDatatype xsd:integer
				]
			] ,
			[ rdf:type owl:Restriction ;
				owl:onProperty :hasParameter ;
				owl:hasValue [ 
					rdf:type :Parameter ;
					:name "r"^^xsd:string ;
					:mandatory "true"^^xsd:boolean ;
					:hasDatatype xsd:integer
				]
			] ,
			[ rdf:type owl:Restriction ;
				owl:onProperty :hasParameter ;
				owl:hasValue [ 
					rdf:type :Parameter ;
					:name "b"^^xsd:string ;
					:mandatory "true"^^xsd:boolean ;
					:hasDatatype xsd:integer
				]
			].

I obtain this OWLClassExpression:

	(uk.ac.manchester.cs.owl.owlapi.OWLObjectHasValueImpl) ObjectHasValue(<http://www.url.com/#hasParameter> _:genid4)

So I have that property is hasParameter but OWLIndividual is OWLAnonymousIndividual, how i can take other information of _:genid4 like :type :Parameter, :name "g"^^xsd:string, and so on

**Comment by ignazio1977** [comment]
You can use an ontology method to get all assertions about an individual:

    OWLAnonymousIndividual i = ...
    ontology.axioms(i).forEach(System.out::println);
