### ISSUE TITLE
Poor performance in OWLImmutableOntologyImpl.getImportsClosure

### ISSUE THREAD

**Issue by matthewhorridge** [owlcs/owlapi#696]
The poor performance is due to the null check that contains unguarded string concatenation.  See below:

```java
@Override
    public OWLOntologyManager getOWLOntologyManager() {
        return verifyNotNull(manager, "Manager on ontology " + getOntologyID()
            + " is null; the ontology is no longer associated to a manager. Ensure the ontology is not being used after being removed from its manager.");
    }
```

**Comment by ignazio1977** [comment]
Is this in version 4? In version 5 this has been replaced with a supplier to avoid the issue. I'll see what can be done to retrofit.

**Comment by matthewhorridge** [comment]
Yes, it's version 4.  Thanks!

**Comment by matthewhorridge** [comment]
Also looks like it's in version 5 too.

**Comment by ignazio1977** [comment]
Related to #568

**Comment by ignazio1977** [comment]
If the fix looks good, the time is ripe for a release

**Comment by matthewhorridge** [comment]
Looks good.  Can't you get rid of 

```java
return verifyNotNull(m, "manager cannot be null at this stage");
```

now?  (I've only looked at OWLImmutableOntologyImpl).

A release would be awesome.  Thanks a lot.

**Comment by ignazio1977** [comment]
The verifyNotNull() is just so I don't get warnings (manager is @Nullable, the method is @Nonnull, and all that). The string is constant and should never be needed either, as that line will only be reached when `m` is not null.

**Comment by matthewhorridge** [comment]
Ohhh ok.  You could just suppress the warnings :)
