### ISSUE TITLE
Entity local names starting with a digit (IRI vs XML spec)

### ISSUE THREAD

**Issue by RalphBln** [owlcs/owlapi#699]
I see that the IRI class uses the XMLUtils class for creating IRIs from single Strings (in order to separate the prefix from the local name (which might be the last path segment or, if present, the fragment).

The problem with relying on XML syntax for IRI creation is that XML forbids local names starting with a digit, while the IRI specification does not (http://www.ietf.org/rfc/rfc3987.txt, pp. 6-7). This results in wrong interpretation of Strings representing IRIs like, for example, "http://example.org/test/1" where the whole String will be interpreted as the namespace part, and the local name would be empty.

I do see the dilemma with RDF/XML serialization. Still, I'd prefer if the IRI class stuck to the IRI spec.

**Comment by ansell** [comment]
The IRI spec does not comment on splitting IRIs into ``prefix`` and/or ``localName``, it only comments on path segments, which are not intended to be used for namespacing. The basis for the ``localName`` concept comes directly from XML, specifically from ``QName`` and its dependent ``NCName``. The only distinctions that can be made from the OWLAPI ``IRI`` methods need to be made in line with the XML specification. This isn't related to RDF or RDF/XML at that point, just XML.

**Comment by RalphBln** [comment]
Mhh, I'm not sure. The [section about IRIs in the OWL 2 structural specification](https://www.w3.org/TR/owl2-syntax/#IRIs) says:

```
fullIRI := an IRI as defined in [RFC3987], enclosed in a pair of < (U+3C) and > (U+3E) characters
prefixName := a finite sequence of characters matching the as PNAME_NS production of [SPARQL]
abbreviatedIRI := a finite sequence of characters matching the PNAME_LN production of [SPARQL]
```

The [SPARQL specification](https://www.w3.org/TR/rdf-sparql-query/#rPN_LOCAL) defines the PNAME_LN production rule as follows:

```
PN_LOCAL ::=  ( PN_CHARS_U | [0-9] ) ((PN_CHARS | '.')* PN_CHARS)?
```

and explicitly states

```
Note that SPARQL local names allow leading digits while XML local names do not.
```

So as far as my interpretation of it goes, named entities in OWL 2 can have any IRI (as specified by RFC 3987) as their name, independently of any restrictions imposed by the XML standard. Or did I miss something?

**Comment by ansell** [comment]
Hmmm, and then confusion ensues...

The section I was looking at was 4.6, where you referred to 2.4:

https://www.w3.org/TR/owl2-syntax/#IRIs_2

No idea how to resolve those, but just for reference, OWL-1 also had the equivalent references so the origins for it are ancient:

https://www.w3.org/TR/owl-syntax/#IRIs

https://www.w3.org/TR/owl-syntax/#IRIs_2

**Comment by ansell** [comment]
Scratch that, "owl-syntax" is actually OWL-2...

OWL-1 is at the following address, but doesn't have references to IRI (OWL-1 was standardised in 2004 and hence predated the 2005 IRI specification in RFC3987):

https://www.w3.org/TR/owl-ref/

**Comment by ignazio1977** [comment]
> So as far as my interpretation of it goes, named entities in OWL 2 can have any IRI (as specified by RFC 3987) as their name, independently of any restrictions imposed by the XML standard.

That is true of the current IRI implementation. It is not stopping you from using an IRI where the last segment starts with numbers, it just won't have a namespace/local name split.

The only real issue with that will happen if said IRI is a property IRI and the serialization used is RDF/XML; otherwise it's just the local name convenience that's lost.

**Comment by ignazio1977** [comment]
To support the split being just a convenience, in OWLAPI 5 and newer, IRI implements `org.apache.commons.rdf.api.IRI`, which has no local name/fragment method.

**Comment by RalphBln** [comment]
> That is true of the current IRI implementation. It is not stopping you from using an IRI where the last segment starts with numbers, it just won't have a namespace/local name split.

I noticed this because Protégé displays those entity names incorrectly if the rendering mode is set to "Render by prefixed name". We are currently working with the RDA vocabulary, where practically all entity names are numbers.

> To support the split being just a convenience, in OWLAPI 5 and newer, IRI implements org.apache.commons.rdf.api.IRI, which has no local name/fragment method.

I see. But the IRI implementation in OWLAPI 5 and upwards still relies on the XMLUtils for creating URIs from strings, so `iri.getNamespace()` will still return the entire IRI string and `iri.getRemainder())` will return `Optional.empty` for IRIs that have been created using `IRI.create(String)`(e.g. whenever an ontology is loaded from a file).

Unless the Protégé developer works around it, the rendering issue will remain. However, I still see it as a deserialization issue rather than a rendering issue.

**Comment by ignazio1977** [comment]
Most definitely a rendering issue, that one: 'prefixed name' is not well defined on iris with no NCName, as it's based on the XML definition. The renderer needs to be aware that the ncname might be absent and take corrective action.

**Comment by matthewhorridge** [comment]
I guess we need to update Protege in response to changes in the IRI implementation and DefaultPrefixManager in the OWL API.  Earlier versions of the OWL API (possibly early versions of 4.x) did not use to split using using the XML utils (neither did DefaultPrefixManager as far as I remember).  This meant that in earlier versions of the OWL API it was possible to split <http://example.org/test/1> with a prefix of "http://example.org/test/" and a local name of "1".  The DefaultPrefixManager used to allow such prefix local name splits but it does not now.

**Comment by matthewhorridge** [comment]
Just for the trail... the changes that upset the rendering in Protege are caused by changes in commit c5bc844f309b76bce35217b8ad744f3503dbda30.  See DefaultPrefixManager in that commit, where line 153 was edited and 
```java 
XMLUtils.isQName(prefixed)
``` 
was added as a conjunct to the IF clause.

**Comment by ignazio1977** [comment]
`IRI.getShortForm()` will implement the previous behaviour. I'm thinking to start recommending it for this sort of uses, as it's closer to what users want, usually.

**Comment by matthewhorridge** [comment]
I think the problem in the Protege case is the DefaultPrefixManager.  IRI.getShortForm is fine.  The problem occurs when the user has selected the "render by prefix name option".  The easiest solution for Protege is for us (me) to write our own prefix manager I think.  The current DefaultPrefixManager lets the prefix be set, but won't supply a prefixed name when asked because of the XMLUtils.isQName condition.

**Comment by ignazio1977** [comment]
If I follow this correctly, the `DefaultPrefixManager` call should ultimately delegate to `IRI::prefixedBy(String)`, however that method returns the input for `IRIs` without remainder. That sounds a bit odd, however all the places that currently use it are likely to use it on IRIs that have a remainder, and changing it doesn't look straightforward.

Fixing the prefix manager is also nasty - the main problem is that the same class is used for output syntaxes, and that means that tweaking it might break the save functions. A prefix manager specific to rendering for UI seems like the best of a few bad options.
