### ISSUE TITLE
How to store a Class to which an Individual belongs rather than printing it [Question]

### ISSUE THREAD

**Issue by mobab** [owlcs/owlapi#701]
`EntitySearcher.getTypes(individual, ontology)` returns a `Stream<OWLClassExpression>`.

to print it we do:

` EntitySearcher.getTypes(individual, ontology).forEach(System.out::println);`

Instead i want to store the output in an `OWLClass `or a `Set of OWLClass` to deal with it later. How do i do that? I want to get the `OWLClass `to which an individual belongs to and store it in an  `OWLClass` variable.

The Stream operations are confusing me.

Sincere regards

**Comment by ignazio1977** [comment]
To turn a stream into a set, there's a utility in `OWLAPIStreamUtils::asSet(Stream)` - this is just a convenience around the standard `Collectors` class.

To get OWLClass only, you need to filter the types:

    Set<OWLClass> classes = OWLAPIStreamUtils.asSet(
                                                     EntitySearcher.getTypes(individual, ontology)
                                                     .filter(OWLClassExpression::isOWLClass));
