### ISSUE TITLE
SyntacticLocalityModuleExtractor and AtomicDecompositionImpl are inconsistent

### ISSUE THREAD

**Issue by mrnolte** [owlcs/owlapi#704]
Hey there,
I observed an inconsistency between `SyntacticLocalityModuleExtractor ` and `AtomicDecompositionImpl `. Consider the ontology [enm.enanomapper.14](https://github.com/owlcs/owlapi/files/1317985/enm.enanomapper.14.zip), which I downloaded [here](http://doi.org/10.5281/zenodo.439510) and will refer to as _ENM_. ENM imports the ontology [_GO Slim_](http://purl.enanomapper.org/onto/external/go-slim.owl), which contains two axioms _a1_ and _a2_. According to `AtomicDecompositionImpl ` for ENM, they each form single element atoms which depend on a third non-empty atom _c_. When extracting the module of ENM with respect to the signature of GO Slim using `SyntacticLocalityModuleExtractor `, I receive only the axioms a1 and a2. The fact that c is not a subset of the received module violates the logical guarantee given by the atom characteristics. Below is some example code to recreate the error:
```
final OWLOntologyManager manager = OWLManager.createConcurrentOWLOntologyManager();
System.out.println("Loading Ontology");
final OWLOntology ontology = manager.loadOntologyFromOntologyDocument(new File("enm.enanomapper.14.orig"));
final SyntacticLocalityModuleExtractor extractor = new SyntacticLocalityModuleExtractor(manager, ontology, ModuleType.STAR);
System.out.println("Extracting Module");
final Set<OWLAxiom> module = extractor.extract(go.signature().collect(Collectors.toSet())).stream().filter(axiom -> axiom.isLogicalAxiom()).collect(Collectors.toSet());
System.out.println("Module of 'go':");
module.forEach(axiom -> {
	System.out.println("\t" + axiom);
});
System.out.println("Calculating atomic Decomposition");
final AtomicDecomposition atomicDecomposition = new AtomicDecompositionImpl(ontology, ModuleType.STAR);
final Set<Atom> atomicSuperset = new HashSet<>();
ontology.logicalAxioms().forEach(axiom -> atomicSuperset.add(atomicDecomposition.getAtomForAxiom(axiom)));
System.out.println("Atomic overlap of 'go':");
int i = 1;
for (final Atom atom : atomicSuperset) {
	System.out.println("\tAtom " + i++ + ":");
	System.out.println("\t\tAxioms:");
	for (final OWLAxiom axiom : atom.getAxioms()) {
		System.out.println("\t\t\t" + axiom);
	}
	System.out.println("\tDependencies:");
	for (final Atom next : atomicDecomposition.getDependencies(atom)) {
		System.out.println("\t\tAxioms:");
		for (final OWLAxiom axiom : next.getAxioms()) {
			System.out.println("\t\t\t" + axiom);
		}
	}
}
atomicDecomposition.getModule(go.signature(), false, ModuleType.STAR).forEach(axiom -> {
	System.out.println("\t" + axiom);
});
System.exit(0);
```
I have shown this observation to Thomas Schneider, one of the authors of the original paper on atomic decomposition. He confirmed that this behaviour appears to be erroneous or at least inconsistent. Our first assumption is that the dependency relationship may be misdirected, meaning that `getDependencies` and `getDependendents` produce mixed-up results. I think it is desirable for the OWL API to be consistent in this matter and I would appreciate it if you could take a look at this issue.

Thanks for reading,
Robin Nolte

Edit: Typos, Code

**Comment by ignazio1977** [comment]
Thank you for the report.

Can you add the source for ModularityAnalyzer as well? I don't believe the class is available anywhere publicly accessible, and I cannot replicate the issue without it.

**Comment by mrnolte** [comment]
I was finally able to reconstruct the inconsistent behavior:
Consider the ontology [example.owl](https://github.com/owlcs/owlapi/files/1468436/example.zip), which consists of three logical axioms:

Axiom | Content                        
----- | -----
a1    | FatherChristmas ⊑ owl:Nothing 
a2    | SantaClause ⊑ likes.Cookies  
a3    | FatherChristmas ≡ SantaClause 

When extracting the modules using the class `SyntacticLocalityModuleExtractor` and `ModuleType.STAR` for the signature of each axiom I get

Axiom | Module(Signature of Label, example.owl)
----- | -----
a1 | {a1, a3}
a2 | {a1, a2, a3}
a3 | {a1, a3}

Since there are modules containing _a1_ and _a3_ but not _a2_, these axioms should be parts of different atoms. Contrary to this expectation, `AtomicDecompositionImpl` (again using `ModuleType.STAR`) only returns the atom _{a1, a2, a3}_.

Interestingly, `uk.ac.manchester.cs.jfact.JFactReasoner` behaves in the same way.

Below you will find source code to replicate the above results:
```java
final OWLOntologyManager manager = OWLManager.createConcurrentOWLOntologyManager();
final OWLOntology ontology = manager.loadOntologyFromOntologyDocument(new File("example.owl"));
final SyntacticLocalityModuleExtractor ex = new SyntacticLocalityModuleExtractor(manager, ontology, ModuleType.STAR);
ontology.logicalAxioms().forEach(axiom -> System.out.println(axiom + " " + ex.extract(axiom.signature().collect(Collectors.toSet()))));
final AtomicDecompositionImpl ad = new AtomicDecompositionImpl(ontology, ModuleType.STAR);
ad.getAtoms().forEach(atom -> System.out.println(atom));
```

Thanks for reading,
Robin Nolte

**Comment by ignazio1977** [comment]
I was just about to update this - I had troubles with the ontologies above because some imports are currently not resolvable. Can you confirm the modules you were seeing in the previous example were:

Module of 'go':

    b	SubClassOf(<http://purl.obolibrary.org/obo/GO_0050663> <http://purl.obolibrary.org/obo/OBI_0000070>)
    b	SubClassOf(<http://purl.obolibrary.org/obo/GO_0009293> <http://purl.obolibrary.org/obo/OBI_0000070>)

Calculating atomic Decomposition
Atomic overlap of 'go':

    a	DifferentIndividuals(<http://purl.obolibrary.org/obo/IAO_0000120> <http://purl.obolibrary.org/obo/IAO_0000121> <http://purl.obolibrary.org/obo/IAO_0000122> <http://purl.obolibrary.org/obo/IAO_0000123> <http://purl.obolibrary.org/obo/IAO_0000124> <http://purl.obolibrary.org/obo/IAO_0000125> <http://purl.obolibrary.org/obo/IAO_0000423> <http://purl.obolibrary.org/obo/IAO_0000428> )
    a	DifferentIndividuals(<http://purl.obolibrary.org/obo/IAO_0000226> <http://purl.obolibrary.org/obo/IAO_0000227> <http://purl.obolibrary.org/obo/IAO_0000228> <http://purl.obolibrary.org/obo/IAO_0000229> )
    a	SubClassOf(<http://purl.obolibrary.org/obo/GO_0050663> <http://purl.obolibrary.org/obo/OBI_0000070>)
    a	SubClassOf(<http://purl.obolibrary.org/obo/OBI_0000070> <http://purl.obolibrary.org/obo/BFO_0000015>)
    a	SubClassOf(<http://purl.obolibrary.org/obo/GO_0009293> <http://purl.obolibrary.org/obo/OBI_0000070>)
    a	SubClassOf(<http://purl.obolibrary.org/obo/BFO_0000015> <http://purl.obolibrary.org/obo/BFO_0000001>)

**Comment by ignazio1977** [comment]
Thanks for the smaller example

**Comment by mrnolte** [comment]
Although I do not have any notes and therefore cannot confirm the result beyond doubt, it matches my memories.

Note that I introduced the term _atomic overlap_ (or _atomic superset_) in my bachelor thesis to describe the set of all atoms that intersect with an (imported) ontology. Accordingly, it is unlikely to be commonplace.

**Comment by ignazio1977** [comment]
There's a known bug I've been trying to fix for a while that might be related, as the symptoms are the same - the AtomicDecomposition generated modules do not match the SyntacticLocalityModuleExtractor. There's a good chance the underlying issue is the same in your test case and in the OldModularisationEquivalenceTestCase.

I'm wondering if the fact that your two named classes are equivalent to `owl:Nothing`, which makes the remaining axiom tautological, have anything to do with the result. I wouldn't think so, but I expect the Semantic modularisation would give different results.

**Comment by ignazio1977** [comment]
Sounds like an interesting topic, is your thesis available somewhere? I'd
be interested in reading it.

**Comment by mrnolte** [comment]
If the generated atoms differ from the actual atoms, the interdependencies between them may change. Since the dependency relation is used to calculate the modules, these deviate logically from the actual modules. Therefore, this error could be the cause of the other.

I'm currently unsure about your thoughts about the semantic locality, and I'll go over it tomorrow.

Thank you for your interest. My bachelor thesis is currently only available in German. It is planned to submit a paper for a workshop as soon as I can review the results presented there. I have done experiments on certain ontologies, but because of this bug I don't know if they are meaningful. To give a short overview about the topic, you'll find the abstract below:

> OWL developers may import external ontologies, for instance to reuse knowledge. Since an ontology holds the statements of all imports, it extends each. Apart from that, it is in general not known how imports are logically dependent on each other or on importing ontologies.
In this thesis graph-based methods are presented to investigate these connections and quantify differences regarding the import relation. For the analysis of logical structures, we use well-understood techniques, in particular module extraction and atomic decomposition. Time complexity, undecidability of minimal modules and different import understandings are discussed and dealt with.
Finally, we identify both formal relationships and result-related correlations between certain methods.

**Comment by ignazio1977** [comment]
As a workaround, FaCT++ implements the same algorithm in C++ without the bug (I used it to verify the failing test mentioned above). A FaCT++ reasoner provides methods to create an atomic decomposition for the ontology used to create the reasoner, and you could use it in place of the OWLAPI atomic decomposition.

**Comment by th42sch** [comment]
Hi Ignazio (and Robin),

Thanks for looking into it, very much appreciated!

> I'm wondering if the fact that your two named classes are equivalent to `owl:Nothing`, which makes the remaining axiom tautological, have anything to do with the result.

I don't think it should. Locality treats axioms separately and thus cannot "see" axioms other than the one currently checked. In addition, syntactic locality is unaware of tautologies.

And a side remark, not sure if it helps:

> but I expect the Semantic modularisation would give different results.

If you mean modules based on semantic locality, then the result would be the same as in Robin's table (again because each axiom is treated "locally", independently of the others).

If you refer to "a minimal module w.r.t. model-theoretic inseparability", then the result does indeed differ, though not much:

- the signature of a1 would lead to {a1}  (each model of {a1} can be extended to a model of {a1,a2,a3} by interpreting SC as FC and both l,C as top).
- the signature of a2 would still lead to {a1,a2,a3} as the minimal module!  
- the signature of a3 would still lead to {a1,a3}.

Cheers

Thomas

**Comment by ignazio1977** [comment]
Cheers. I'll keep looking for the bug.

**Comment by mrnolte** [comment]
Hi Ignazio and Thomas,
I was finally able to take a closer look at the atomic decomposition code and think I found the bug:
`uk.ac.manchester.cs.atomicdecomposition.AtomicDecompositionImpl` uses `org.semanticweb.owlapitools.decomposition.decomposer` to construct the atoms, which in turn uses `org.semanticweb.owlapitools.decomposition.Modularizer` to calculate the necessary modules. The calculated TOP-module for _a1_ (output in the method `Modularizer.extract`) is not _{a1, a3}_, but _{a1,a2,a3}_. For this reason, I think that the locality check of the class `org.semanticweb.owlapitools.decomposition.SyntacticLocalityChecker` used by `Modularizer` is incorrect. I tried using `org.semanticweb.owlapitools.decomposition.SemanticLocalityChecker`, but only got `NullpointerException`s or no Atoms at all.

To calculate the modules, the implementation of atomic decomposition does not use the proposed procedure of [(Del Vescovo et al, 2011)](http://www.cs.man.ac.uk/~sattler/publications/IJCAI2011.pdf), but simply delegates to the same erroneous syntactic locality check. This in itself is not necessarily a bug, as the proposed method is currently unwieldy, but it is the reason for the error you observed.

I still have some time this week and I am willing to continue to work on it. My suggestion is to clean up the three implementations of the locality check from `com.clarkparsia.owlapi.modularity.locality.SyntacticLocalityEvaluator`, `uk.ac.manchester.cs.factplusplusad.SyntacticLocalityChecker`, and `org.semanticweb.owlapitools.decomposition.SyntacticLocalityChecker`. Since the implementation by `factplusplusad` behaves analogous to `org.semanticweb.owlapitools.decomposition.SyntacticLocalityChecker`, it would be best to take the by the results above assumingly correct `com.clarkparsia.owlapi.modularity.locality.SyntacticLocalityEvaluator` instead. This way, there is no need to maintain three implementations any more. For the same reason, I suggest choosing an implementation of atomic decomposition out of `uk.ac.manchester.cs.atomicdecomposition.AtomicDecompositionImpl` and `uk.ac.manchester.cs.factplusplusad.AtomicDecomposer`. Because the latter ist is package private, but does not seem to be used anywhere in the package, I tend towards the former. Unfortunately, `SyntacticLocalityEvaluator` cannot be used within `AtomicDecompositionImpl` at the moment, because this requires an `OWLOntologyManager`, which cannot be generated by the `OWLManager` because of otherwise cyclic dependencies of the gits. Accordingly, either `SyntacticLocalityEvaluator` or `AtomicDecompositionImpl` also need new method interfaces. I offer to adapt them using Java 8 `Streams`, too, as it happened everywhere else in the OWLAPI 5.

Thanks for reading,
Robin Nolte

**Comment by ignazio1977** [comment]
I believe you're very close to the bug I've been chasing for a long time.
The `factplusplusad` package contains a port of the FaCT++ implementation and it was intended as a temporary package, to be removed once the code base got harmonised and started using only one implementation of decomposition - however this bug crept in, and stopped the process.

I have pinpointed the issue to the same problem - a decomposition from Modularizer is larger than it ought to be. This appears to be due to some collection being modified differently in the Java version and on the C++ version - pointers to pointers in C++ are behaving differently in the Java version. However, I've inspected the code multiple times looking for typos that would explain the behaviour and still not managed to pinpoint the problem (as well as with this example ontology, the problem can be replicated with existing unit tests that use the Koala ontology. The tests are currently disabled.)

**Comment by mrnolte** [comment]
> I have pinpointed the issue to the same problem - a decomposition from Modularizer is larger than it ought to be. This appears to be due to some collection being modified differently in the Java version and on the C++ version - pointers to pointers in C++ are behaving differently in the Java version. However, I've inspected the code multiple times looking for typos that would explain the behaviour and still not managed to pinpoint the problem (as well as with this example ontology, the problem can be replicated with existing unit tests that use the Koala ontology. The tests are currently disabled.)

That might very well be the case, but could be solved by using `uk.ac.manchester.cs.owlapi.modularity.SyntacticLocalityModuleExtractor` instead of `org.semanticweb.owlapitools.decomposition.Modulariter` within `org.semanticweb.owlapitools.decomposition.Decomposer`, as I intended to state above, but switched the classes up. There would be no need to debug the code further.

**Comment by ignazio1977** [comment]
The issue there is that the FaCT++ algorithm is meant to be faster :-D

**Comment by mrnolte** [comment]
Are they just different implementations of the same algorithm or does the Fact++ implementation use further optimizations?

**Comment by ignazio1977** [comment]
FaCT++ uses further optimizations described by Dmitry in the latest papers on the topic (2012). https://dblp.org/pers/hd/t/Tsarkov:Dmitry

**Comment by mrnolte** [comment]
I was finally able to fix the bug:
The method `uk.ac.manchester.cs.owlapi.modularity.ModuleType.Modularizer.extractModule(List<AxiomWrapper>, Signature, ModuleType)` modified the signature when calculating the first $\bottom$-module, but did not change it back when extracting the following $\top$-module. Now the above example works as intended. I will create a pull request concerning this matter.

I also began writing an updated and more maintainable version of both the module extraction and the atomic decomposition and will propose to use them instead as soon as they are finished. It was somewhat laborious to debug the Fact++ port.

**Comment by ignazio1977** [comment]
Very much appreciated, thank you.

**Comment by mrnolte** [comment]
Thank you very much. Didn't thought about it first, but should those changes be applied to the version 4 branch too?

**Comment by mrnolte** [comment]
Hey Ignazio,

> Sounds like an interesting topic, is your thesis available somewhere? I'd be interested in reading it.

If you are still interested, Thomas and I submitted an article to DL 2019 on this topic. We did some experiments based on the corrected code, too. You can find the article [here](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=2ahUKEwiX7d3UsbTjAhVHAWMBHc0xAGwQFjAAegQIAhAC&url=http%3A%2F%2Fceur-ws.org%2FVol-2373%2Fpaper-21.pdf&usg=AOvVaw39W-CC_mfIMUjegkUqiDCH
).

Note that there is a small typo in definition 1, where it should be <a href="https://www.codecogs.com/eqnedit.php?latex=|E&space;\cap&space;E'|\,/\,|E|" target="_blank"><img src="https://latex.codecogs.com/gif.latex?|E&space;\cap&space;E'|\,/\,|E|" title="|E \cap E'|\,/\,|E|" /></a> instead of <a href="https://www.codecogs.com/eqnedit.php?latex=\dpi{100}&space;|E&space;\cap&space;E'|\,/\,|E'|" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\dpi{100}&space;|E&space;\cap&space;E'|\,/\,|E'|" title="|E \cap E'|\,/\,|E'|" /></a>.

Cheers, Robin
