### ISSUE TITLE
Could not find an appropriate factory to load ontology from ontology document

### ISSUE THREAD

**Issue by linako111** [owlcs/owlapi#707]
I'm new to ontologies. I downloaded the test project (v4), added a ttl file as an argument (used full path), and trying to run SimpleHierarchyExample. I can see it prints correct file name with a path and then says: "Could not find an appropriate factory to load ontology from ontology document". I used maven. But may be I missed some steps, as I'm new to maven as well... 
Actually, found a solution, by adding "file:" before the path. Now it reads it okey, but I get this error:

Document IRI: file:/Users/***/Downloads/***.ttl
Ontology : OntologyID(OntologyIRI(<http://***.owl>) VersionIRI(<http://***.owl>))
Format      : Turtle
Exception in thread "main" java.lang.NullPointerException
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at uk.ac.manchester.owl.owlapi.tutorial.examples.SimpleHierarchyExample.main(SimpleHierarchyExample.java:131)

**Comment by ignazio1977** [comment]
Hi,
the test module is not self standing - it requires many other modules to be downloaded as well.

The easiest way is to check out the whole branch; otherwise, you'll need to amend the maven configuration to point at an actual owlapi version (e.g., 4.5.0).

The pom file looks like this currently:

    <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>owlapi-apibinding</artifactId>
        <version>${project.version}</version>
    </dependency>

You need to replace project.groupId with net.sourceforge.owlapi and project.version with 4.5.0 - this will allow Maven to resolve the actual OWLAPI artifacts you need to run the tests by themselves.

**Comment by linako111** [comment]
Thanks, Ignazio, I downloaded the whole branch (I think - could you confirm that it is indeed the whole branch) from here: https://github.com/owlcs/owlapi/tree/version4
That's how it looks like in eclipse: 
<img width="1440" alt="screen shot 2017-10-16 at 10 14 56 am" src="https://user-images.githubusercontent.com/29641360/31616661-497e096a-b25b-11e7-849c-74a0c5cdc77c.png">
Is there anything else I need to download or install?

**Comment by ignazio1977** [comment]
The setup is correct. Now, see that `reasonerFactoryclassName` valiable purposefully left as null? You need to put the class name of a reasoner factory for the reasoner of your choice there.

Reasoner implementations are not part of OWLAPI, that's why we cannot put a hardcoded one in there. You need to choose a reasoner implementation, add it to your classpath and put the factory class name there.

**Comment by linako111** [comment]
Thank you again for a quick answer. How can I choose an implementation? Does it depend on file type (ttl in my case), do I do an implementation myself? Do you have an example? Thanks!

**Comment by ignazio1977** [comment]
Check the documentation for a list of reasoners you can use. They're available on Maven Central.
https://github.com/owlcs/owlapi/wiki

**Comment by ignazio1977** [comment]
I recommend HermiT. It is the same reasoner Protege includes by default.

**Comment by linako111** [comment]
In a wiki example this is the way to set up a reasoner factory:
OWLReasonerFactory reasonerFactory = new Reasoner.ReasonerFactory();
And in here it is asking for a name. I'm a bit confused. What would be a name for Hermit factory? 
Or may be do not use the name and use this:
OWLReasonerFactory reasonerFactory = new Reasoner.ReasonerFactory();
SimpleHierarchyExample simpleHierarchy = new SimpleHierarchyExample(reasonerFactory, ontology);
?

**Comment by ignazio1977** [comment]
> OWLReasonerFactory reasonerFactory = new Reasoner.ReasonerFactory();
SimpleHierarchyExample simpleHierarchy = new SimpleHierarchyExample(reasonerFactory, ontology);

Yes this is correct

**Comment by linako111** [comment]
ok)) so I've used this instructions to use HermiT: 
http://www.hermit-reasoner.com/java.html
To follow the instruction the only thing I did is modification to the owlapi-contract/pom.xml file to include hermit dependencies:
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<artifactId>owlapi-contract</artifactId>
	<name>OWLAPI :: Tests and Tutorials</name>
	<parent>
		<groupId>net.sourceforge.owlapi</groupId>
		<artifactId>owlapi-parent</artifactId>
		<version>5.1.2</version>
	</parent>
	<dependencies>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>owlapi-apibinding</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
  			<groupId>com.hermit-reasoner</groupId>
  			<artifactId>org.semanticweb.hermit</artifactId>
  			<version>1.3.8.4</version>
		</dependency>
	</dependencies>
</project>
May be there is an additional step - like to download jar files for hermit and include them manually in the project somehow? 
I also modified code a little. The program does not crash on the creation of SimpleHierarchyExample, but later on - on
 OWLReasoner reasoner = reasonerFactory.createReasoner(ontology);
So there is still a problem with reasonerFactory it seems. But I'm sure there is some steps that i'm missing...
<img width="1440" alt="screen shot 2017-10-16 at 9 42 05 pm" src="https://user-images.githubusercontent.com/29641360/31642801-f98868dc-b2ba-11e7-815b-6861c4d22b22.png">

**Comment by ignazio1977** [comment]
You're not using a version compatible with the latest OWLAPI. Use HermiT 1.4.0.432 (432 is for OWLAPI 4.3.2)

http://search.maven.org/#artifactdetails%7Cnet.sourceforge.owlapi%7Corg.semanticweb.hermit%7C1.4.0.432%7Cbundle

**Comment by linako111** [comment]
Yes, it worked with a different version, thanks so much!
