### ISSUE TITLE
load Ontology

### ISSUE THREAD

**Issue by Nidhalos** [owlcs/owlapi#709]
hello 
I have a problem with accessing my local .OWL File with eclipse , i has imported owl-api library this my java code ;
package net.sourceforge.owlapi;

import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.io.OWLOntologyDocumentSource;
import org.semanticweb.owlapi.io.StreamDocumentSource;
import org.semanticweb.owlapi.model.OWLException;
import org.semanticweb.owlapi.model.OWLOntology;
import org.semanticweb.owlapi.model.OWLOntologyManager;

public class app {
	public void loadOntology() throws OWLException {
		String famille = "";
		 OWLOntologyManager om = OWLManager.createOWLOntologyManager();
		 OWLOntologyDocumentSource source = new StreamDocumentSource(getClass().
		 getResourceAsStream("data/famille.owl"));
		 om.loadOntologyFromOntologyDocument(source);
		 OWLOntology famille = om.createOntology();	}
	
    System.out.println("famille");

}

when i run my code

-------------------------------------------------------------------------------------------------------
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.676 s
[INFO] Finished at: 2017-10-19T19:48:31+02:00
[INFO] Final Memory: 4M/63M
[INFO] ------------------------------------------------------------------------
[ERROR] No goals have been specified for this build. You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoGoalSpecifiedException
-----------------------------------------------------------------------------------------------------------------
i need help please

**Comment by ignazio1977** [comment]
Hi, you're not showing how you are running this code.

Did you run 

`mvn`

on the command line? Maven needs instructions, e.g., `clean`, `build` or `test`.

However your class is not a unit test and does not have a main method, so it cannot run by itself. Are you calling it from some other class?

**Comment by Nidhalos** [comment]
actually i don't know where is exactement the error , i'm not a java developer but i was trying to follow this steps : 
https://www.pressinnov.com/2016/04/owl-api-une-api-java-pour-manipuler-des-ontologies/

and i don't know what i have to learn for create and generate a file .owl with java

**Comment by ignazio1977** [comment]
Since you have the code in Eclipse, you can leave aside the Maven commands for the moment.

To run a Java method, you need to add a `main` method to your class; you'll then be able to run the class from Eclipse (Right click on the class and select - Run as Java application)

A `main` method looks like this:

    public static void main(String[] args) {
        new app().loadOntology();
    }

**Comment by mohammed74** [comment]
you must add file of jena API or other api to librares's of project
