### ISSUE TITLE
How to find paths between any two owl entities?

### ISSUE THREAD

**Issue by karanthpallavi** [owlcs/owlapi#711]
Using OWL API, I have got axioms of two owl classes in loaded Ontology. May I know how to find paths between the owl entities? Can a reasoner help? I need to compute shortest paths... Please help

**Comment by ignazio1977** [comment]
Paths along which dimension? Which entity types?

**Comment by karanthpallavi** [comment]
Paths between any two classes or individuals

**Comment by karanthpallavi** [comment]
May I know if I can get all paths between any two classes or individuals using OWL API?If so, how? Please help..

**Comment by ignazio1977** [comment]
Please provide an example of what sort of paths you're after. There are too many possibilities to explore.

**Comment by karanthpallavi** [comment]
Ways to reach one class from another,
Have a new algorithm for Semantic Distance,
Need to find all paths existing between any two classes or individuals to
compute distance between any two classes or individuals.
Not sure if my explanation is understandable,
Path will be a combination of taxonomical  and  property edges i.e.
rdfs:subClassOf or is:a edges and owl: Property edges.

**Comment by karanthpallavi** [comment]
Thanks much,
Will try iterating over axioms,

For more clarification, will get back..
Thanks...
