### ISSUE TITLE
Is there a way to convert an OWLClass to JSON format?

### ISSUE THREAD

**Issue by linako111** [owlcs/owlapi#712]
Thanks.

**Comment by ignazio1977** [comment]
There's no way to convert a single class to JSON - it's possible to save an ontology to JSON (see `RDFJsonLDDocumentFormat` and `RDFJsonDocumentFormat`).

However an OWLClass is just an IRI plus a type, so it's easy enough to write a custom serializer and deserializer. The deserializer needs an `OWLDataFactory` to create an OWLClass object from an IRI, which can be created from a plain string.

**Comment by sathyamoorthyrr** [comment]
> There's no way to convert a single class to JSON - it's possible to save an ontology to JSON (see `RDFJsonLDDocumentFormat` and `RDFJsonDocumentFormat`).
> 
> However an OWLClass is just an IRI plus a type, so it's easy enough to write a custom serializer and deserializer. The deserializer needs an `OWLDataFactory` to create an OWLClass object from an IRI, which can be created from a plain string.

yes. `RDFJsonLDDocumentFormat` and `RDFJsonDocumentFormat` works good.

But, is there a way to remove prefixes like,
`http://www.w3.org/1999/02/22-rdf-syntax-ns`
`http://www.w3.org/2002/07/owl#NamedIndividual`

any pointers would be helpful!
