### ISSUE TITLE
OWL API 4.5.0 Dependency Conflict due to Guava 19.0/20.0 (owlapi-api)

### ISSUE THREAD

**Issue by andrewdbate** [owlcs/owlapi#714]
I am the developer of a new (soon to be released) OWL Reasoner called Sequoia, and have discovered a dependency conflict that exists when using the OWL API Interfaces artifact version 4.5.0.

Specifically, I have the following Maven dependency:
```
<dependency>
    <groupId>net.sourceforge.owlapi</groupId>
    <artifactId>owlapi-api</artifactId>
    <version>4.5.0</version>
</dependency>
```
Here is the diagram of dependencies of the `owlapi-api` artifact:
![owl-api-4 5-dependencies](https://user-images.githubusercontent.com/2998569/32986440-820efd6a-ccc9-11e7-98f2-fe473f1aeb06.png)

The diagram shows the dependency conflict with `com.google.guava`: `guice` expects `guava` version 19.0 but the OWL API `pom.xml` explicitly requires `guava` version 20.0.

My build tool (SBT, which generated the above dependency diagram) is complaining each time I compile because of this dependency conflict. Is it possible to fix this? Or is there a reason why you require version 20.0?

Thanks!

**Comment by ansell** [comment]
There will always be conflicts on non-trivial projects with Guava (and with Guice) because Google increment the major version regularly when they make breaking changes, but they have always reused the same package/class names so you cannot colocate different major versions on the same classpath as you can with Apache Commons libraries. The only possible solution to this is to find a version that works for you and force your build tool to use it.

**Comment by andrewdbate** [comment]
So you are prepared to close this with no solution or useful workaround at all?
If that is the case, then the OWL API shouldn't have such dependencies.

**Comment by andrewdbate** [comment]
Your comment does not address the issue as to why `owlapi-api` explicitly depends on version 20.0. The underlying problem seems to be an overindulgence in dependencies of all kinds, resulting in megabytes of bloat and dependency conflicts for anyone trying to develop anything on top.

**Comment by ansell** [comment]
I personally don't use Guava or Guice in my personal projects for these reasons. However, there is widespread reliance on both Guava and Guice in OWLAPI so it can't be avoided at this point. In particular, Guice is used in public APIs to offer extensibility, so it cannot be shaded.

The only possible solution is for you to look at which Guava/Guice versions work for you and hardcode those into your build tool.
