### ISSUE TITLE
Guice Dependency in Distribution is Wrong

### ISSUE THREAD

**Issue by mnmercer** [owlcs/owlapi#720]
We recently upgraded OWLAPI in our application from version `5.0.3` to `5.1.3` and are running into issues with the imported guice package in the `distribution` manifest. The `distribution` pom in version `5.0.3` optionally imports `com.google.inject`.
```xml
<Import-Package>
    !sun.misc,
    !com.google.inject.internal.*;resolution:=optional,
    org.openrdf*;version="[4.0,5.0)",
    info.aduna.iteration;version="[4.0,5.0)",
    *
</Import-Package>
```
However the `5.1.3` pom includes the `com.google.inject` package with an incorrect package version number. The exported package version from guice `v4.1.0` is `1.4`, but this pom has `4.1.0`.
````xml
<Import-Package>
    !sun.misc,
    org.eclipse.rdf4j.*;version="[2.0,3.0)",
    com.google.inject.*;version=4.1.0,
    org.apache.commons.io.*;version=2.5,
    org.apache.commons.logging.*;version=1.2,
    *
</Import-Package>
````
The way I see it, there are two options. Either the `com.google.inject` import should be optional like it was before or the package number should be fixed.

**Comment by ignazio1977** [comment]
> The exported package version from guice v4.1.0 is 1.4

I am trying to figure out where the 1.4 comes from, can you clarify how to verify that?

**Comment by ignazio1977** [comment]
> !com.google.inject.internal.*;resolution:=optional,

That's an exclusion for the internal package, not an inclusion

**Comment by skahmann** [comment]
Ah yes, they are a bit different. I would think you could just remove the manual import of `com.google.inject.*;version=4.1.0,` because I would think the * import at the end of the list would catch it. If not, you'll need to use 1.4 as the version. If you look at the guice jar, they use version 1.4 for their exported packages:

```
Export-Package: com.google.inject;version="1.4",com.google.inject.spi;
 version="1.4",com.google.inject.matcher;version="1.4",com.google.inje
 ct.util;version="1.4",com.google.inject.binder;version="1.4",com.goog
 le.inject.name;version="1.4"
```

So it should probably be `com.google.inject.*;version=1.4`. You may actually need `com.google.inject*;version=1.4` (note the missing period) to catch the `com.google.inject` package.

**Comment by skahmann** [comment]
Removing the line entirely yields the following in the imports list:

```
com.google.inject;version="[1.4,2)",com.google.inject.assiste
 dinject;version="[1.4,2)",com.google.inject.binder;version="[1.4,2)",
 com.google.inject.multibindings;version="[1.4,2)"
```

If we can trust the guice project to correctly semantically version their software, then this seems like a good solution.

**Comment by mnmercer** [comment]
I discovered another issue where the bundle attempts to import `javax.annotation;version="[3.0,4)"` which is only available from [here](https://mvnrepository.com/artifact/com.google.code.findbugs/jsr305/3.0.1). `owlapi-osgidistribution` accounts for this by excluding this package, but `owlapi-distribution` does not.

The changes I would like to make are removing `com.google.inject.*;version=4.1.0` and adding `!javax.annotation` to `Import-Package`. What's the process for creating a pull request? Should I just make one into `master`? Will that be applied to 5.1?

**Comment by ignazio1977** [comment]
Thank you. The process for pull requests, as far as I know, is to fork the repository (GitHub allows that through the buttons in the main code page), commit your changes to the fork, then use the buttons on the fork to create a pull request against the branch you wish to modify.
(I've done this a few years ago for a number of other projects and Protege plugins, it's actually easier to do than to describe)

You can choose whether you want to make the change on the master branch or on version5 - either way I'll copy it across to the other branches. Not sure if this issue applies to version 4, but if so I'll update that too.

**Comment by skahmann** [comment]
Any idea when this may be released?

**Comment by ignazio1977** [comment]
Soon - likely this week.

**Comment by ignazio1977** [comment]
Merged in version5. Marking for version 6 so I don't forget.

**Comment by ignazio1977** [comment]
Version 5.1.4 was released this morning

**Comment by mnmercer** [comment]
Thank you so much with your help on this @ignazio1977. When will 5.1.4 be pushed to Maven central?

**Comment by ignazio1977** [comment]
Depends on the time required for sync after the release is completed but usually it's a couple of hours. I haven't checked if Maven Central is already up to date, but I expect so.
