### ISSUE TITLE
Exception java.lang.IndexOutOfBoundsException: Index: 0, Size: 0 while loading of ontology in Eclipse IDE

### ISSUE THREAD

**Issue by resarcher2016** [owlcs/owlapi#724]
Hi All,

I am trying to learn the concepts of semantic web and in this course, i have developed an ontology in Protege 5.2.0. . I have successfully run an example ontology and added SWRL rules to it. Using Drools engine in protege, i am able to draw inferences also in protege. Thus, all is working fine in protege. I have used Fact ++ reasoner. 
Though, everything is working fine in Protege:
1. )I am not understanding why we use both a reasoner and a rule engine.I mean will this be ok if i use only drools and no reasoner from protege.. 

2. Now i want to repeat the whole process of inferencing programmitically in Java. For this task, after going through available resources on internet, i have successfully pulled out Swrlapi-drools-engine maven project from GIThub
**This is the pom.xml file in my project**
<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>edu.stanford.swrl</groupId>
    <artifactId>swrlapi-parent</artifactId>
    <version>2.0.5</version>
  </parent>

  <artifactId>swrlapi-drools-engine</artifactId>
  <packaging>bundle</packaging>
  <name>Drools-based SWRL Rule Engine</name>
  <description>Drools implementation of SWRLAPI-based SWRL rule engine</description>
  <url>https://github.com/protegeproject/swrlapi-drools-engine/wiki/SWRLAPI-Drools-Engine</url>

  <properties>

    <swrlapi.version>2.0.5</swrlapi.version>

  </properties>

  <scm>
    <connection>scm:git:git@github.com:protegeproject/swrlapi-drools-engine.git</connection>
    <developerConnection>scm:git:git@github.com:protegeproject/swrlapi-drools-engine.git</developerConnection>
    <url>https://github.com/protegeproject/swrlapi</url>
    <tag>release-2.0.5</tag>
  </scm>

  <issueManagement>
    <system>GitHub</system>
    <url>https://github.com/protegeproject/swrlapi-drools-engine/issues</url>
  </issueManagement>

  <dependencies>

    <dependency>
      <groupId>edu.stanford.swrl</groupId>
      <artifactId>swrlapi</artifactId>
      <version>${swrlapi.version}</version>
    </dependency>

    <dependency>
      <groupId>net.sourceforge.owlapi</groupId>
      <artifactId>owlapi-osgidistribution</artifactId>
    </dependency>

    

    <dependency>
      <groupId>org.drools</groupId>
      <artifactId>drools-osgi-integration</artifactId>
    </dependency>

    <dependency>
      <groupId>org.drools</groupId>
      <artifactId>knowledge-api</artifactId>
    </dependency>

    

    
    
    <dependency>
      <groupId>org.checkerframework</groupId>
      <artifactId>checker</artifactId>
    </dependency>

    <dependency>
      <groupId>org.checkerframework</groupId>
      <artifactId>checker-qual</artifactId>
    </dependency>

    <dependency>
      <groupId>org.checkerframework</groupId>
      <artifactId>jdk8</artifactId>
    </dependency>

    
    
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </dependency>

    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-log4j12</artifactId>
      <scope>test</scope>
    </dependency>

  </dependencies>

  <build>

    <plugins>

      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
      </plugin>

      <plugin>   
        <groupId>org.apache.felix</groupId>
        <artifactId>maven-bundle-plugin</artifactId>
        <extensions>true</extensions>

        <configuration>

          <instructions>
            <Bundle-SymbolicName>${project.artifactId}</Bundle-SymbolicName>
            <Include-Resource>{maven-resources}</Include-Resource>
            <Import-Package>
              org.drools.*;version="${drools.version}",
              org.semanticweb.owlapi.*;version="[4.1.3,5.0.0)",
              org.swrlapi.*;version="1.0.0",
              *
            </Import-Package>
            <Export-Package>
              org.swrlapi.drools.*;version="1.0.0",
            </Export-Package>
          </instructions>
        </configuration>

        <executions>
          <execution>
            <id>bundle-manifest</id>
            <phase>process-classes</phase>
            <goals>    
              <goal>manifest</goal>
            </goals>   
          </execution>
        </executions>

      </plugin>

    </plugins>

    <pluginManagement>
    	<plugins>
    		
    		<plugin>
    			<groupId>org.eclipse.m2e</groupId>
    			<artifactId>lifecycle-mapping</artifactId>
    			<version>1.0.0</version>
    			<configuration>
    				<lifecycleMappingMetadata>
    					<pluginExecutions>
    						<pluginExecution>
    							<pluginExecutionFilter>
    								<groupId>org.apache.felix</groupId>
    								<artifactId>
    									maven-bundle-plugin
    								</artifactId>
    								<versionRange>
    									[2.5.4,)
    								</versionRange>
    								<goals>
    									<goal>manifest</goal>
    								</goals>
    							</pluginExecutionFilter>
    							<action>
    								<ignore></ignore>
    							</action>
    						</pluginExecution>
    					</pluginExecutions>
    				</lifecycleMappingMetadata>
    			</configuration>
    		</plugin>
    	</plugins>
    </pluginManagement>
  </build>

</project>

For reading ontology, this is the readOntology.java
package reader;
import static org.semanticweb.owlapi.search.Searcher.annotations;
import static org.semanticweb.owlapi.vocab.OWLRDFVocabulary.RDFS_LABEL;

import java.util.ArrayList;
import java.util.List;

import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLAnnotation;
import org.semanticweb.owlapi.model.OWLAnnotationProperty;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLException;
import org.semanticweb.owlapi.model.OWLLiteral;
import org.semanticweb.owlapi.model.OWLOntology;
import org.semanticweb.owlapi.model.OWLOntologyCreationException;
import org.semanticweb.owlapi.model.OWLOntologyManager;

public class readOntology {

    private final OWLOntology ontology;
    private OWLDataFactory df;

    public readOntology
    (OWLOntology ontology, OWLDataFactory df) {
        this.ontology = ontology;
        this.df = df;
    }

    public void parseOntology()
            throws OWLOntologyCreationException {

        for (OWLClass cls : ontology.getClassesInSignature()) {
            String id = cls.getIRI().toString();
            **String label = get(cls, RDFS_LABEL.toString()).get(0);
            System.out.println(label + " [" + id + "]");
        }
    }

    private List<String> get(OWLClass clazz, String property) {
        List<String> ret = new ArrayList<>();**

        **final OWLAnnotationProperty owlProperty = df
                .getOWLAnnotationProperty(IRI.create(property));
        for (OWLOntology o : ontology.getImportsClosure()) {
            for (OWLAnnotation annotation : annotations(
                    o.getAnnotationAssertionAxioms(clazz.getIRI()), owlProperty)) {
                if (annotation.getValue() instanceof OWLLiteral) {
                    OWLLiteral val = (OWLLiteral) annotation.getValue();
                    ret.add(val.getLiteral());
                }
            }**
        }
        return ret;
    }

    public static void main(String[] args) throws OWLException,
            InstantiationException, IllegalAccessException,
            ClassNotFoundException {

            	String x="file:G:/Framework/SystemComponents/OWL/instOntology.owl";
    	IRI documentIRI = IRI.create(x);
        OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
        OWLOntology ontology = manager
                .loadOntologyFromOntologyDocument(documentIRI);
        readOntology parser = new readOntology(ontology, manager.getOWLDataFactory());
        parser.parseOntology();
    }
}
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at reader.readOntology.parseOntology(readOntology.java:36)
	at reader.readOntology.main(readOntology.java:69)

I did debug my program to understand where it faults. As highlighted in above code:
   private List<String> get(OWLClass clazz, String property) {
        List<String> ret = new ArrayList<>();**

        **final OWLAnnotationProperty owlProperty = df
                .getOWLAnnotationProperty(IRI.create(property));
        for (OWLOntology o : ontology.getImportsClosure()) {
            for (OWLAnnotation annotation : annotations(
                    o.getAnnotationAssertionAxioms(clazz.getIRI()), owlProperty)) {
                if (annotation.getValue() instanceof OWLLiteral) {
                    OWLLiteral val = (OWLLiteral) annotation.getValue();
                    ret.add(val.getLiteral());
                }
            }**
        }
        return ret;
    }
 this code returns exception. Please guide me through that why this program is not reading the properties of identified class. 

Thanks in advance for your support and  precious time.

**Comment by ignazio1977** [comment]
The failure looks due to the fact that there are no matching labels in the ontology you're using.

We can't say more without the ontology, I'd say.

**Comment by resarcher2016** [comment]
Thanks a lot for Reply!!
I am trying to learn about these basics of ontology development and their access in java.
I have few very basic doubts in ontology development.sorry for such trivial questions
1. When we create ontology in protege, 
![image](https://user-images.githubusercontent.com/20816179/34559010-43c1837c-f166-11e7-8216-f5227ccbcbf6.png)
We need to define ontology IRI, so my question is how is IRI different from physical location of a file on device?
2. Is it necessary to define IRI of a ontology on localhost or web i.e with  http:// protocol
3. Is it ok to write IRI as file:/G:/test/abc.owl?
4. How to add prefix of an active ontology? actually when i add a prefix manually in Ontology prefixes TAB, and go to SWRL Tab to write rule, the prefix is lost and the SWRL gives error that Prefix is not registered with ontology or Invalid atom predicate.
5. Please suggest some good material to understand these fundamentals of ontology.

Regards
