### ISSUE TITLE
How to get all individuals in a specific range of a property?

### ISSUE THREAD

**Issue by fahedAlkhabbas** [owlcs/owlapi#725]
Hello, 

I am new to OWLAPI, suppose we have the following scenario
user1 hasLocation room1 
smartphone1 hasLocation room1 
sensor1 hasLocation room1
where user1, smartphone1, sensor1 and room1 are individuals. Given the individual (location) room1 how can I get smartphone1, sensor1 based on their class (Device) and as they both hasLocation room1? I use the latest OWLAPI (V5.1.3)

Thanks a lot for your support!

Regards,

**Comment by ignazio1977** [comment]
You can create a class that is the intersection of Device and some hasLocation {room1} (a OneOf expression as the filler for hasLocation, where the meaning is '' all individuals that have a hasLocation property with object the individual room1 and are also Devices).

Assuming we have the right variables initialised, the code looks like:

        OWLDataFactory df = ...
        OWLObjectProperty hasLocation = null;
        OWLIndividual room1 = null;
        OWLClass device = null;
        OWLReasoner r = null;
        OWLObjectIntersectionOf request = df.getOWLObjectIntersectionOf(
            device, 
            df.getOWLObjectSomeValuesFrom(hasLocation, df.getOWLObjectOneOf(room1)));
        NodeSet<OWLNamedIndividual> instances = r.getInstances(request);

The instances are all the individuals that match all requirements.

**Comment by fahedAlkhabbas** [comment]
Thanks a lot!
