### ISSUE TITLE
Does OWLEntity class have equal and hashcode methods implemented?

### ISSUE THREAD

**Issue by karanthpallavi** [owlcs/owlapi#726]

**Comment by karanthpallavi** [comment]
Hi, 
Am using OWLEntity as a type of vertex in the Directed Graph am creating using JGraphT,
May i know if equals and hashcode methods are available in the class OWLEntity?
This is needed if i have to construct a graph of vertices of type OWLEntity.
Can these methods be added into OWL Entity class?

More details for equals and hash code is here: https://github.com/jgrapht/jgrapht/wiki/EqualsAndHashCode

Thanks much in advance,
Awaiting your help..

**Comment by ignazio1977** [comment]
OWLEntity is an interface.

equals() and hashCode() are implemented in OWLObject.

**Comment by karanthpallavi** [comment]
Thanks much for the info..
