### ISSUE TITLE
Regarding display of entities(Individuals)

### ISSUE THREAD

**Issue by resarcher2016** [owlcs/owlapi#728]
Hi ,

I am working on semantic web and for the same, i am learning to create and consume ontologies through programming (Eclipse IDE) as well through GUI(Protege 5.2.0). I run the example code (https://github.com/phillord/owl-api/blob/master/contract/src/test/java/org/coode/owlapi/examples/Examples.java) for accessing the entities as below

    OWLOntologyManager ontologyManager = OWLManager.createOWLOntologyManager();
    File file = new File("G:/Framework/SystemComponents/OWL/instOntology.owl");
    OWLOntology localInstitute = ontologyManager.loadOntologyFromOntologyDocument(file);
    OWLDataFactory factory = ontologyManager.getOWLDataFactory();
    String base="https://localhost/Institute";
    PrefixManager pm = new DefaultPrefixManager(base);
    OWLClass person2= factory.getOWLClass(":Person",pm);
    OWLNamedIndividual user = factory.getOWLNamedIndividual(":Neha", pm);
    OWLClassAssertionAxiom classAssertion = factory.getOWLClassAssertionAxiom(person2, user);
    ontologyManager.addAxiom(localInstitute, classAssertion);
    OWLDataProperty age = factory.getOWLDataProperty("age", pm);
    OWLDataPropertyAssertionAxiom agePropertyAssertion = 
    factory.getOWLDataPropertyAssertionAxiom(age, user, 41);
		        
    ontologyManager.addAxiom(localInstitute, agePropertyAssertion);

 Now when i run below code to see instances added to ontology, it does not show Neha as an Instance of person.

    OWLClass instance = factory.getOWLClass(IRI.create("http://localhost/Institute#Person"));
    // Ask the reasoner for the instances of person
    NodeSet<OWLNamedIndividual> individualsNodeSet = reasoner.getInstances(instance,true);

    // The reasoner returns a NodeSet again. This time the NodeSet contains
    // individuals. Again, we just want the individuals, so get a flattened set.
    Set<OWLNamedIndividual> individuals = individualsNodeSet.getFlattened();
    System.out.println("Instances of Person: ");
    for (OWLNamedIndividual ind : individuals) {
        System.out.println("    " + ind);
    }
    System.out.println("\n");

Output: Instances of Person:
Could anyone please guide , which line of code is missing?

**Comment by ignazio1977** [comment]
Can you add the reasoner initialisation to your example? It is likely where the problem is.

**Comment by resarcher2016** [comment]
Yes, i am have run code with reasoner also. This is the updated code

  	OWLOntologyManager ontologyManager = OWLManager.createOWLOntologyManager();
		    	File file = new File("G:/Framework/SystemComponents/OWL/instOntology.owl");
		    	OWLOntology localInstitute = ontologyManager.loadOntologyFromOntologyDocument(file);
		       		        
		        OWLDataFactory factory = ontologyManager.getOWLDataFactory();
		               
		        String base="https://localhost/Institute";
		        PrefixManager pm = new DefaultPrefixManager(base);
		      	        
		        OWLClass person2= factory.getOWLClass(":Person",pm);
		     
		        OWLNamedIndividual user = factory.getOWLNamedIndividual(":Neha", pm);
		    		        
		        OWLClassAssertionAxiom classAssertion = factory.getOWLClassAssertionAxiom(person2, user);
		              
		        ontologyManager.addAxiom(localInstitute, classAssertion);
		        
		        OWLDataProperty age = factory.getOWLDataProperty("age", pm);
		        		
		        OWLDataPropertyAssertionAxiom agePropertyAssertion = factory.getOWLDataPropertyAssertionAxiom(age, user, 41);
		        
		        ontologyManager.addAxiom(localInstitute, agePropertyAssertion);
		        
		       //Run reasoner to validate axiom additions Method shouldUseReasoner()
		        OWLReasonerFactory reasonerFactory = new StructuralReasonerFactory();
		        ConsoleProgressMonitor progressMonitor = new ConsoleProgressMonitor();
		        OWLReasonerConfiguration config = new SimpleConfiguration(progressMonitor);
		        OWLReasoner reasoner = reasonerFactory.createReasoner(localInstitute, config);
		        reasoner.precomputeInferences();
		        boolean consistent = reasoner.isConsistent();
		        System.out.println("Consistent: " + consistent);
		        System.out.println("\n");
		        
		        Node<OWLClass> bottomNode = reasoner.getUnsatisfiableClasses();
		        Set<OWLClass> unsatisfiable = bottomNode.getEntitiesMinusBottom();
		        if (!unsatisfiable.isEmpty()) {
		            System.out.println("The following classes are unsatisfiable: ");
		            for (OWLClass cls : unsatisfiable) {
		                System.out.println("    " + cls);
		            }
		        } else {
		            System.out.println("There are no unsatisfiable classes");
		        }
		        System.out.println("\n");
		        System.out.println(localInstitute);
		      
		        OWLClass person = factory.getOWLClass(IRI.create("http://localhost/Institute#Person"));
		        NodeSet<OWLClass> subClses = reasoner.getSubClasses(person, true);
		        Set<OWLClass> clses = subClses.getFlattened();
		        System.out.println("Subclasses of Person: ");
		        for (OWLClass cls : clses) {
		            System.out.println("    " + cls);
		        }
		        System.out.println("\n");
		        
		           
		        
		      //Display Instances of class Person
		        OWLClass instance = factory.getOWLClass(IRI.create("http://localhost/Institute#Person"));
		        // Ask the reasoner for the instances of person
		        NodeSet<OWLNamedIndividual> individualsNodeSet = reasoner.getInstances(instance,true);
		        
		        // The reasoner returns a NodeSet again. This time the NodeSet contains
		        // individuals. Again, we just want the individuals, so get a flattened
		        // set.
		        Set<OWLNamedIndividual> individuals = individualsNodeSet.getFlattened();
		        System.out.println("Instances of Person: ");
		        for (OWLNamedIndividual ind : individuals) {
		            System.out.println("    " + ind.toString());
		        }
		        System.out.println("\n");
		        
		      		
Output of above code is:
Consistent: true


There are no unsatisfiable classes


Ontology(OntologyID(OntologyIRI(<http://localhost/Institute>) VersionIRI(<null>))) [Axioms: 723 Logical Axioms: 527] First 20 axioms: {AnnotationAssertion(rdfs:comment <http://localhost/Institute#eventsAttended> "A person attended national and internatinal events, for example, Seminars, Conferences, Symposiums, Workshops, etc."^^xsd:string) AnnotationAssertion(rdfs:comment <http://localhost/Institute#resourcePersonOf> "A person being invited as a resource person to deliver lectures, etc."^^xsd:string) AnnotationAssertion(rdfs:label <http://localhost/Institute#firstName> "First Name"^^xsd:string) AnnotationAssertion(rdfs:comment <http://localhost/Institute#Gender> "Programes offered by the Institute"^^xsd:string) AnnotationAssertion(rdfs:comment <http://localhost/Institute#PhD> "Bachelors of .......

Subclasses of Person: 
    <http://localhost/Institute#Teacher>
    <http://localhost/Institute#AdministrativeStaff>
    <http://localhost/Institute#Student>
    <http://localhost/Institute#Assistant>


Instances of Person: 

//Classes are consistent as per code and code successfully display subclass of Person also. In .owl file there is no instance of Person class but i am adding it in code. So i guess it should display the instance..

**Comment by ignazio1977** [comment]
The clone of OWLAPI that you're using as examples is outdated and is missing a crucial comment on the reasoner variable:

https://github.com/owlcs/owlapi/blob/version5/contract/src/test/java/org/semanticweb/owlapi/examples/Examples.java

 // We need to create an instance of OWLReasoner. An OWLReasoner provides
        // the basic query functionality that we need, for example the ability
        // obtain the subclasses of a class etc. To do this we use a reasoner
        // factory. Create a reasoner factory. In this case, we will use HermiT,
        // but we could also use FaCT++ (http://code.google.com/p/factplusplus/)
        // or Pellet(http://clarkparsia.com/pellet) Note that (as of 03 Feb
        // 2010) FaCT++ and Pellet OWL API 3.0.0 compatible libraries are
        // expected to be available in the near future). For now, we'll use
        // HermiT HermiT can be downloaded from http://hermit-reasoner.com Make
        // sure you get the HermiT library and add it to your class path. You
        // can then instantiate the HermiT reasoner factory: Comment out the
        // first line below and uncomment the second line below to instantiate
        // the HermiT reasoner factory. You'll also need to import the
        // org.semanticweb.HermiT.Reasoner package.
        OWLReasonerFactory reasonerFactory = new StructuralReasonerFactory();


The structural reasoner does not do inferences. I am convinced StructuralReasoner is a misnomer. It should have been called MockReasoner or NonReasoner.
