### ISSUE TITLE
do not register deprecated oboparser by default

### ISSUE THREAD

**Issue by cmungall** [owlcs/owlapi#729]
There are two obo parsers

 1. org.coode.owlapi.obo12.parser.OBOParser
 2. org.semanticweb.owlapi.oboformat.OBOFormatOWLAPIParser

The former is deprecated, and does not interpret a lot of tags correctly. In practice it causes a lot of problems by having it be registered by default. It is less strict than 2, which means it is often unintentionally used and silently garbles the input.

example ontology:

```
[Term]
id: X:1
name: x1
synonym: "foo" EXACT []
not_a_tag: foo
```

this fails parsing using 2 but succeeds using 1. Thankfully there is a clue when this happens as we see:

```
[Fatal Error] :1:1: Content is not allowed in prolog.
```

caused by a naughty rdf parser leaking to stderr. Normally this behavior is annoying but here it's a vital clue (due to the order of precedence we don't see it if 2 succeeds).

If we then output the OWL using the valid oboformat writer we get

```
[Term]
id: X:1
name: x1
property_value: hasExactSynonym "foo" xsd:string
property_value: http://purl.obolibrary.org/obo/not_a_tag "foo" xsd:string
```

which is not ideal when a user tries to save the file back..

I can't think of any scenario whereby anyone would want obo12.parser.OBOParser - it was vital back in the day but no one should use it now

Perhaps bioportal have some legacy obo ontologies that are not syntactically valid using the new parser? I'd rather work with them to fix this and have only a single parser.

**Comment by ignazio1977** [comment]
Workaround (works with OWLAPI 4 and 5): you can use the org.semanticweb.owlapi.model.parameters.ConfigurationOptions.BANNED_PARSERS property to exclude one or more parsers. It's a space separated string containing class names for parsers that should not be used for parsing unless specified explicitly by the caller.

We've used this in the past when some parsers misbehaved - e.g., TriX.

**Comment by ignazio1977** [comment]
For the record, 

> [Fatal Error] :1:1: Content is not allowed in prolog.

is not coming form the RDF parser, it's the SAX handler implementation complaining loudly on stderr. We could wrap stderr to silence it (we've created a utility to silence SLF4J messages of the same sort) but it's a contended area - should we or should we not? As a library, I think we shouldn't hide other libraries' messages, because there's always a chance we hide something important.
