### ISSUE TITLE
Performance measurements and detect if ontology file gets updated.

### ISSUE THREAD

**Issue by fahedAlkhabbas** [owlcs/owlapi#730]
Hi, 
I am writing a paper and I am using the OWL-API, thanks for developing such a great API. I wonder if you have performed some scalability tests to measure the response time of different operations when the number of individuals increases? 

I also wonder if there is any mechanism to detect if the loaded ontology original file has changed during the execution, for example, to change the ontology file by a tool like a Protege and to detect the change automatically by the API. 

Please let me know ASPA since the submitting deadline is approaching. 

Thanks a lot, appreciated!

Best, 
Fahed

**Comment by ignazio1977** [comment]
Hi, we've tried ontologies with different numbers of individuals but we don't have a systemic study of scalability (i.e., an ontology, a set of operations and an increasing number of individuals, with associated time and space requirements).

At a guess, my feeling is that the operations will scale linearly with the number of individuals (retrieving individuals and axioms is based on indexes built from in memory maps) and the memory requirements will grow linearly as well. There are caches for named individuals and namespaces instances, so repeated use of individuals does not create large numbers of copies, and there are caches for signatures, so operations like OWLObject::signature() do not do all the work from scratch every time. All caches are size limited, so I'd expect the memory footprint to increase with use up to a point, and there will be access patterns that are suboptimal (e.g., calling signature() on all objects in a large ontology in sequence, multiple times, is likely to cause poor cache hit ratio while keeping them full).

There's currently no functionality to detect changes and reload - whether this function is desired is very application dependent, so it's been left out of the API.

**Comment by ignazio1977** [comment]
There's a benchmark module in the source, which uses JMH and a few large ontologies for profiling - this is more for identifying hot spots than to assess scalability, but it might be useful for your purposes.

**Comment by fahedAlkhabbas** [comment]
Thanks Ignazio for your answers, appreciated. 
For the second part, I now create a new manager and reload a new copy of the ontology every now and then and then had to make both null. It is not the best solution but it works for my purposes. 

Thanks again!
