### ISSUE TITLE
SWRL variable IRIs violate URN spec

### ISSUE THREAD

**Issue by balhoff** [owlcs/owlapi#732]
OWL API produces SWRL variables with IRIs like `urn:swrl#foo` (at least it reads these into `?foo`, maybe they're only created by Protégé?). But a URN [should have two colons](https://tools.ietf.org/html/rfc2141):

```
<URN> ::= "urn:" <NID> ":" <NSS>
```

Could they be changed to `urn:swrl:foo` or `urn:swrl:var#foo`? We ran into one tool that complains about `urn:swrl#foo`.

**Comment by ignazio1977** [comment]
That string is used as a marker for variable IRIs - the SWRL classes use IRIs for variable identifiers, and so they're forced to have something to replace the "?" used, for example, in Manchester syntax.

(Protege has no responsibility for that :-) )

The fact that it only has one colon is an error, one that most tools don't care about...
