### ISSUE TITLE
Question: Equals and HashCode methods in OWL API 

### ISSUE THREAD

**Issue by karanthpallavi** [owlcs/owlapi#733]
Hi,

Found that OWL Entity is interface and equals and hashcode method is implemented in OWLObject from my earlier posted question.
But OWL Object is also interface,
May i know any class which implements OWLEntity and has equals and hashcode method?

From axiom.getSignature - am getting entities in the axiom as List<OWLEntity> entitiesInOntology,
When i try to compare and get index of an OWL entity using
int indexOfSource = entitiesInOntology.indexOf(source),
although the entity exists in ontology, it returns -1.
Equals and hashcode implementation is required,
May i know how to tackle this?
Thanks much

**Comment by ignazio1977** [comment]
OWLObjectImpl.java

Can you show the code you use for the example above?

**Comment by karanthpallavi** [comment]
public List<OWLEntity> entitiesOfGraph = new ArrayList<>();

Set<OWLEntity> entitiesInAxiom = axiomInQues.getSignature();
Iterator entityIter = entitiesInAxiom.iterator();
                while(entityIter.hasNext())
                {
                    OWLEntity entity1 = (OWLEntity) entityIter.next();
                    OWLEntity entity2 = (OWLEntity) entityIter.next();
}
entitiesOfGraph.add(entity1);
indexOfEntity1 = entitiesOfGraph.indexOf(entity1);
System.out.println("Entity "+entity1+" Index: "+indexOfEntity1);

indexOfEntity1 is printed as -1

May I know if i have to use OWLObjectImpl List instead of List<OWLEntity>?
Thanks

**Comment by karanthpallavi** [comment]
May I know if there's any way to solve this?
Thanks much,
Have tried using List of OWLObjectImpl objects.
The result is same...

**Comment by ignazio1977** [comment]
As it is, your code snippet does not compile - entity1 is out of scope.

Rewritten like this:

        List entitiesOfGraph = new ArrayList<>();
        Set entitiesInAxiom = axiomInQues.getSignature();
        Iterator entityIter = entitiesInAxiom.iterator();
        while (entityIter.hasNext()) {
            OWLEntity entity1 = (OWLEntity) entityIter.next();
            OWLEntity entity2 = (OWLEntity) entityIter.next();

            entitiesOfGraph.add(entity1);
            int indexOfEntity1 = entitiesOfGraph.indexOf(entity1);
            System.out.println("Entity " + entity1 + " Index: " + indexOfEntity1);
        }

It compiles and run as expected, printing 0.

Where is entity1 coming from in your original code? I suspect it's being initialised to a different value than you expect.

**Comment by ignazio1977** [comment]
Defining the list as OWLObject or OWLObjectImpl has no bearing on this issue; it is the runtime type of the objects that determines which equals() method to use, not the list declaration.
