### ISSUE TITLE
DL Quary tab not working with Protege 5.2.0

### ISSUE THREAD

**Issue by ying6991** [owlcs/owlapi#735]
When I  load the DL Quary tab, it always prompts for the following error.

![1](https://user-images.githubusercontent.com/26991546/35975654-5fceeed8-0d18-11e8-9233-fd0994e7f3da.jpg)

![2](https://user-images.githubusercontent.com/26991546/35975699-93f769ba-0d18-11e8-896e-007007ef3774.jpg)

**Comment by ykazakov** [comment]
Looks like an issue of [Protege](https://github.com/protegeproject/protege).

**Comment by ignazio1977** [comment]
Indeed.

**Comment by csnyulas** [comment]
@ying6991 can you open an issue on the [Protege issue tracker](https://github.com/protegeproject/protege/issues) about this? Please also provide the logs or, whatever is written on your console? You can close this issue here.
