### ISSUE TITLE
Deprecated classes in OWLAPI 4 missing in JavaDoc

### ISSUE THREAD

**Issue by buergerj** [owlcs/owlapi#740]
I recently upgraded OWLAPI in a project from 3 to 4.
I could resolve all compilation errors using the wiki page https://github.com/owlcs/owlapi/wiki/Migrate-from-version-3.4-and-3.5-to-4.0
But there is a number of classes which is now deprecated and was not in OWLAPI 3, for example
org.coode.owlapi.obo.parser.OBOOntologyFormat
org.coode.owlapi.turtle.TurtleOntologyFormat
org.semanticweb.owlapi.io.OWLFunctionalSyntaxOntologyFormat
org.semanticweb.owlapi.io.OWLXMLOntologyFormat
org.semanticweb.owlapi.io.RDFXMLOntologyFormat
org.semanticweb.owlapi.model.OWLOntologyFormat

Sadly, these classes are missing in the JavaDoc so it is hard to figure out which alternative classes to use.
Any hints?

**Comment by ignazio1977** [comment]
The wiki has a page for 3 to 4 migration.

Those classes have been renamed from Ontology to Document.

**Comment by buergerj** [comment]
Thanks for your information. As I wrote, I already consulted the wiki page.
Correct me if I'm wrong, but for instance the renaming you mentioned is neither explicitly nor implicitly stated there. So it may be a good idea to add this.

**Comment by ignazio1977** [comment]
Page updated.
