### ISSUE TITLE
saveOntology writes empty file on failure

### ISSUE THREAD

**Issue by rctauber** [owlcs/owlapi#741]
When saving an ontology in ROBOT with the OWLAPI native save function ([in IOHelper](https://github.com/ontodev/robot/blob/master/robot-core/src/main/java/org/obolibrary/robot/IOHelper.java#L440)), we end up with an empty file if there is an exception thrown.

For example: https://github.com/ontodev/robot/pull/256#issuecomment-369618698
If you convert an OWL ontology to OBO format and it violates the OBO structure rules, ROBOT fails with an exception but still creates a new (empty) file.

For the automated workflows that ROBOT is used in, if there was an output file created, it may look like a success. We can work around this, but I wanted to check if this had been looked at in OWLAPI first.

**Comment by matthewhorridge** [comment]
The OWL API used to save to a temporary file before overwriting the target file if the save was successful.  I think this was removed a while back though.  In Protege we save to temp files and then overwrite the real file if all goes well.  It would be best for ROBOT to do something similar I think.

**Comment by ignazio1977** [comment]
If I recall correctly, the reason for removal of the temp file step was because moving the file meant reading it back in and writing it again. That caused its own set of challenges.

**Comment by rctauber** [comment]
@matthewhorridge - that's what we were considering, but I haven't actually played around with it yet. The main concern is performance with larger ontologies, which I would imagine caused issues with reading and writing again? @ignazio1977

**Comment by matthewhorridge** [comment]
> If I recall correctly, the reason for removal of the temp file step was because moving the file meant reading it back in and writing it again. 

I don't remember.  For Protege we thought that it was worth it so that we could increase robustness.  I would need to do some tests to see how much file copying costs in terms of time.

**Comment by matthewhorridge** [comment]
@rctauber 
>The main concern is performance with larger ontologies, which I would imagine caused issues with reading and writing again?
I just eyeballed saving "go-edit" in Protege and the copying took less than 1 second.  Not a scientific test, but in the whole save process, in this case, the copying doesn't seem to dominate.

**Comment by rctauber** [comment]
Thanks for checking! I'll try doing a temp file method and see if it drastically changes the execution times.
