### ISSUE TITLE
Add classes to output set of ontologies to OWL/ZIP file

### ISSUE THREAD

**Issue by ignazio1977** [owlcs/owlapi#742]

**Comment by jamesaoverton** [comment]
I've been following progress on OWL/ZIP eagerly. What is this issue/commit about?

**Comment by ignazio1977** [comment]
The previous commits were to enable OWLAPI to read the contents of zipped files with indexes in various formats; this one is a utility class to create zip files from sets of ontologies - e.g., an ontology and its imports closure.

**Comment by ignazio1977** [comment]
Now added to version 5 and 4 too.
