### ISSUE TITLE
EntitySearcher ignores annotations from imports

### ISSUE THREAD

**Issue by reality** [owlcs/owlapi#745]
The EntitySearcher interface seems to have no way to obtain annotations from classes residing in imported ontologies. The following code will not return any annotations from imported ontologies:

```groovy
EntitySearcher.getAnnotations(oClass, ontology).each { annotation ->
  println annotation
}
```

You can obtain them using the annotationAssertionAxioms stream in OWLOntology:

```groovy
ontology.annotationAssertionAxioms(oClass.getIRI(), Imports.INCLUDED).each {
  println it
}
```

Would it be possible to add the same Imports enum flag to the EntitySearcher annotation methods? I notice that some of the methods already have this functionality, e.g. getAxiomsIgnoreAnnotations

Thank you!

**Comment by ignazio1977** [comment]
To get the annotations from imported ontologies, pass the imports closure in the method. All methods are overloaded to accept a single ontology or a collection/stream of ontologies (depending whether you're using version 4 or 5).

**Comment by jamesamcl** [comment]
> To get the annotations from imported ontologies, pass the imports closure in the method. All methods are overloaded to accept a single ontology or a collection/stream of ontologies (depending whether you're using version 4 or 5).

This seems true for `getAnnotationObjects` but not `getAnnotations`?

I don't see any overload that takes a collection/stream of ontologies: https://github.com/owlcs/owlapi/blob/b683b03cbe7587fbc8a19c4a44360cfa27a97320/api/src/main/java/org/semanticweb/owlapi/search/EntitySearcher.java#L64-L105
