### ISSUE TITLE
Annotations of individuals getting modified incorrectly

### ISSUE THREAD

**Issue by lsarni** [owlcs/owlapi#748]
I'm running this code (I have tried it with version 5.0.0 and 5.1.4 with the same results):

```
OWLOntologyManager man = OWLManager.createOWLOntologyManager();

// Set folder from which to get local imported ontologies
File folder = new File("C:\\Users\\lulas\\Documents\\Curricula Ontology");
AutoIRIMapper mapper=new AutoIRIMapper(folder, true);
man.getIRIMappers().add(mapper); 

// Open the existing ontology
File file = new File("C:\\Users\\lulas\\Documents\\Curricula Ontology\\curricula-instance.owl");
OWLOntology o = man.loadOntologyFromOntologyDocument(file);
OWLDataFactory df = o.getOWLOntologyManager().getOWLDataFactory();

// Defined the IRIs, in this case there are 3 different ontologies being used (as imports)
IRI instanceIOR = IRI.create("http://www.semanticweb.org/lsarni/ontologies/curricula-instance");    
IRI curriculaIOR = IRI.create("http://www.semanticweb.org/lsarni/ontologies/curricula");    
IRI professorsIOR = IRI.create("http://www.semanticweb.org/lsarni/ontologies/curricula-professors");

// Read the Excel file
Workbook workbook = WorkbookFactory.create(new File("C:\\Users\\lulas\\Desktop\\Professors.xlsx"));
Sheet sheet = workbook.getSheetAt(0);

// The first row has the name of the ObjectProperties (including the #)
Row row = sheet.getRow(0);
ArrayList<String> properties = new ArrayList();
for(int i =1; i<row.getLastCellNum(); i++){
  Cell cell = row.getCell(i);
  properties.add(cell.getStringCellValue());
}

for(int i = 1; i<sheet.getLastRowNum(); i++){
  row = sheet.getRow(i);
  
  // The first column corresponds to the individuals
  OWLIndividual individual = df.getOWLNamedIndividual(instanceIOR + "#"+row.getCell(0).getStringCellValue());
  
  // The rest of the columns have the values for each individual of an object property defined at the first row
  for(int j=1; j<row.getLastCellNum(); j++){
    String v = row.getCell(j).getStringCellValue();
    if (v.length() > 0) {               
      OWLIndividual value = df.getOWLNamedIndividual(professorsIOR + "#"+ v);
      OWLObjectProperty objectProperty = df.getOWLObjectProperty(professorsIOR + properties.get(j-1));

      OWLObjectPropertyAssertionAxiom assertion = df.getOWLObjectPropertyAssertionAxiom(objectProperty, individual, value);
      AddAxiom addAxiomChange = new AddAxiom(o, assertion);
      man.applyChange(addAxiomChange);
    }
  }
}
man.saveOntology(o);
```

Which read an excel and creates some `ObjectPropertyAssertion`, but once it's done running apart form creating the expected assertions it has affected a bunch of `Annotations`.
Before:
```
<AnnotationAssertion>
  <AnnotationProperty abbreviatedIRI="rdfs:label"/>
  <IRI>#Basic_Sciences</IRI>
  <Literal xml:lang="en" datatypeIRI="http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral">Basic_Sciences</Literal>
</AnnotationAssertion>
```
After:
```
<AnnotationAssertion>
  <AnnotationProperty abbreviatedIRI="rdfs:label"/>
  <IRI>#Basic_Sciences</IRI>
  <Literal xml:lang="es" datatypeIRI="http://www.w3.org/1999/02/22-rdf-syntax-ns#langString">Ciencias_Básicas</Literal>
</AnnotationAssertion>
```

The same thing happens every time I run it and affects the annotations of all the individuals in my ontology that where using `PlainLiteral`. It doesn't affect the annotations of any imported individuals.

I don't have a minimal example, but I'm attaching the excel (a smaller version of it), the ontologies and the java project.
[CISOnto-develop.zip](https://github.com/owlcs/owlapi/files/1913436/CISOnto-develop.zip)
[Professors.xlsx](https://github.com/owlcs/owlapi/files/1913438/Professors.xlsx)
[my-app.zip](https://github.com/owlcs/owlapi/files/1913443/my-app.zip)

To replicate you will need to change the file, ontology and folder path on the `ProfessorsImport` class to point to the excel file, the `curricula-instances` ontology and the folder containing the ontologies.

I had made [this question](https://stackoverflow.com/questions/49837794/owlapi-add-label-to-individual) but I think it's related with this problem. On the save it might be transforming this new labels to use `langString`.

I'm running this on Windows, but I will try it out on Mac and update.

**Comment by ignazio1977** [comment]
The code is correct, the problem is in the format used. RDF/XML works fine, OWL/XML is the format you're using and that's changed behaviour in version 5.

There's no semantic difference between PlainLiteral and langString, but langString is not as widespread in tools. The difference you showed in the question might be due to the application used to display the data.

**Comment by lsarni** [comment]
Thanks! I was going insane.
I change the format to RDF/XML and run the code and it no longer affected the annotations.
