### ISSUE TITLE
Accessing semantic web technologies with java 

### ISSUE THREAD

**Issue by issamahwach** [owlcs/owlapi#749]
Hello everyone,
I'am new with Semantic Web, and i have a project built in java for a (relief center) that contains a database built in JDBC.
This database contains a lot of specific information about every beneficiary.
All i need is to implement somehow the semantic web technologies in this project to support decisions that should be suggested by the program (to provide sufficient flexibility to be able to represent the database, and logic rules to link them together ).
(For example: to suggest that this person deserve this aid according to his details).
I'am thinking of converting this details for every beneficiary to RDF, but i don't know how to start and what to use exactly.
If i'am wrong please lead me to the correct road.
By the way, i'am using Netbeans as a platform.
Thanks.

**Comment by ansell** [comment]
Hi, This issue tracker is for bugs in the OWLAPI library. You may be able to get general pointers from users of mailing lists such as https://lists.w3.org/Archives/Public/semantic-web/ 

Thanks
