### ISSUE TITLE
JESS(Java Expert System Shell) tab is not Loaded into with Protege 5.2.0

### ISSUE THREAD

**Issue by ying6991** [owlcs/owlapi#751]
I have downloaded the jess.jar and put it in the appropriate file (....\Protege-5.2.0\plugins). When I open Protege 5.2.0, JESS tab is not in Windon-Tabs. And I click the 'Reset selected tab to default state, it has no  effect as well.

**Comment by ansell** [comment]
Hi, you need to be asking these questions on a protege mailing list instead of the OWLAPI issue tracker:

https://protege.stanford.edu/support.php
