### ISSUE TITLE
AutoIRIMapper does not find .owl extended imports for OBO format roots

### ISSUE THREAD

**Issue by matentzn** [owlcs/owlapi#756]
If you check for example a setup like [Drosophila Anatomy](https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/tree/master/fbbt/src/ontology), you can see that the main edit file (fbbt-edit.obo) has import statements that point to .owl extended files. I raced through AutoIRIMapper with a debugger, and it appears that if the root file is an obo file, it only indexes other obo files as imports. Is that intended behaviour?

**Comment by ignazio1977** [comment]
I'm not clear on the setup here. AutoIRIMapper does not parse imports from ontologies, so it does not know of 'root' ontologies, only of root folders and their subfolders, if any.

What files does the folder contain here?

**Comment by matentzn** [comment]
Sorry Iggy, I just tried to create a small testcase, but it didnt work. Seems like that was not the issue. I will close the issue for now, as it might not be OWL API related after all (some weird interaction of ontology iri and the filename perhaps). I will reopen when the issue comes up again.
