### ISSUE TITLE
OWLObjectRenderer cannot render DatarangeAtom

### ISSUE THREAD

**Issue by YifanQie** [owlcs/owlapi#757]
I wrote a swrl Rule in Protege in this way

> A(?x), xsd:integer\[> 1 , < 6\] (?index), AA(?x, ?index) -> BB(?x, 7)

when I use OWLAPI to upload the ontology file I can get this

    Prefix(owl:=<http://www.w3.org/2002/07/owl#>)
    Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>)
    Prefix(xml:=<http://www.w3.org/XML/1998/namespace>)
    Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>)
    Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>)
    Ontology(
        Declaration(Class(<urn:w:a>))
        Declaration(DataProperty(<urn:w:aa>))
        Declaration(DataProperty(<urn:w:bb>))

        DLSafeRule(
                Body(
                        ClassAtom(<urn:w:a> Variable(<urn:swrl#x>))
                        DataRangeAtom(DatatypeRestriction(xsd:integer 
                                xsd:minExclusive "1"^^xsd:integer 
                                xsd:maxExclusive "6"^^xsd:integer) 
                                Variable(<urn:swrl#index>)) 
                        DataPropertyAtom(<urn:w:aa> Variable(<urn:swrl#x>) Variable(<urn:swrl#index>)))
                Head(
                        DataPropertyAtom(<urn:w:bb> Variable(<urn:swrl#x>) "7"^^xsd:integer)))
)

it seems really good because all the information of the rule is expressed. However when I use a code to render this rule there is something missing.
the related code is :

> import org.semanticweb.owlapi.dlsyntax.renderer.DLSyntaxObjectRenderer;
> import org.semanticweb.owlapi.io.OWLObjectRenderer;
> 
> OWLObjectRenderer renderer = new DLSyntaxObjectRenderer(); 
> String tempRule = renderer.render(rule).toString();

and the rule is printed this way:

    bb(?x, 7) ← a(?x) ⋀ (?index) ⋀ aa(?x, ?index)

you see the information about the range of index is missing.

I want to ask (1)how to express the datarange in the swrl form above? (2)how to render swrl rule with data range?

**Comment by YifanQie** [comment]
Maybe instead of import OWLObjectRenderer
import org.semanticweb.owlapi.io.OWLObjectRenderer;
 I should import some swrlrenderer?
because perhaps datarangeatom is not recognizable for owlrendderer?

**Comment by ignazio1977** [comment]
`OWLDatatypeRestriction` is not currently supported in DL syntax, at the moment this must be done by hand. I'm not sure what the syntax looks like tbh.

**Comment by YifanQie** [comment]
I see. Thank you very much! 
I tried to use SWRL built-ins to express these instead since currently I only need to express a range. greaterThan and lessThan could help to some extend.
the swrl rule is written as:
*A(?x), AA(?x, ?index),A(?x), greaterThanOrEqual(?index, 3),lessThan(?index, 6) -> BB(?x, 7)*
this rule can be supported in DL syntax.
Anyway... So far so good. 
Thank you again.
