### ISSUE TITLE
Associate OWLObjectProperty with an instance of a class using DL parser

### ISSUE THREAD

**Issue by visraj1** [owlcs/owlapi#759]
Hi, I was trying to use DLParser to parse an expression of the form 

> testResult value "t"

where testResult is an OWLObjectProperty. But its failing with 

> Encountered "t" at line 1 column 150. Expected one of:
	Individual name

If I change the type of testResult to OWLDataProperty it parses correctly. Is there a way to do it the other way?

**Comment by ignazio1977** [comment]
You need an individual IRI not a literal as value, as the error message says.

**Comment by visraj1** [comment]
Thank you @ignazio1977
