### ISSUE TITLE
Parsing string in Manchester Syntax and adding resources

### ISSUE THREAD

**Issue by visraj1** [owlcs/owlapi#760]
Hi,
Given a triple store and a file containing a rule ( axiom ) represented in Manchester syntax, is there a way to parse the axiom to identify properties and resources and create an ontology out of it ( assuming that the rule is written correctly ) and run a reasoner on top of the ontology? an example rule is 

> resource1 and fulfilledBy some resource2

where in the triple store there is resource1 and resource2 and also property fulfilledBy. some implies somevaluesfrom and 'and' implies intersection

**Comment by ignazio1977** [comment]
If in the file you have no prefix information, it won't be possible to parse these axioms correctly - the IRIs are relative and, lacking prefix information, they will be resolved against the file IRI. This won't match the IRI declarations in the triple store.

The prefix information can either be added to the content of the file before parsing (e.g., loading the file content in a string and prefixing it with the expected prefix declaration), or by creating a `PrefixManager` with the right setup, but this is harder to get right.

You can get an example of what the prefixes must be by creating an empty ontology and adding declarations for the entities you plan to use, then save this ontology in Manchester syntax format - this will provide you with a template, to which you can append the plain axioms.

    OWLOntology o = ...
    OWLDataFactory df = ...
    o.add(df.getOWLNamedIndividual(IRI.create(namespace, "resource1"));
    ....
    o.saveOntology(new ManchesterSyntaxDocumentFormat(), new SystemOutDocumentTarget());

**Comment by visraj1** [comment]
Parsing string based on the format
