### ISSUE TITLE
Reasoning inconsistency for disjoint sets of classes

### ISSUE THREAD

**Issue by visraj1** [owlcs/owlapi#762]
Hi,

I had been trying to use OWL API to check if an ontology is consistent or not. When I try to run the reasoner on Protege I get the correct inconsistency due to the disjointedness  as in the figure below. 
![image](https://user-images.githubusercontent.com/22190957/40715113-d7fda028-6404-11e8-9d6e-de68f66343d8.png)

But when I use the same ontology with the OWL API, its returning true for `hermit.isConsistent()`. Is it due to the wrong usage of the reasoner. I have provided the code below as well . 
Both `Reasoner` and `Configuration` are from the package `org.semanticweb.HermiT`

> Configuration config=new Configuration();
	Reasoner hermit = new Reasoner(config,ontology);	
	if(hermit.isConsistent()) {
		System.out.print("Running safe");
	}

**Comment by visraj1** [comment]
Not relevant here

**Comment by ignazio1977** [comment]
The code is correct. Protégé is not showing an inconsistency, it is showing an unsatisfiable class. The ontology is inconsistent only if the class that's inconsistent has an instance.

**Comment by visraj1** [comment]
Thanks @ignazio1977 . Does it actually mean I have to create a NamedIndividual of the failed class to show its inconsistent?

**Comment by ignazio1977** [comment]
You can show the class is unsatisfiable with the corresponding method in OWLReasoner. If you want the whole ontology to be inconsistent, you need an individual - named or anonymous.

**Comment by visraj1** [comment]
Sorry, but i am not sure if I understood it correctly. I tried different ways and also something like the below, trying to display all the unsatisfied class or subClasses of it. But every time it returns `owl:Nothing`.  Is there just a way to identify this inconsitency, even if not possible to display them?
 
`   OWLReasoner hermit = new Reasoner(config,ontology);
    hermit.unsatisfiableClasses().forEach(classe ->{
    	System.out.println(classe);
    	ontology.getSubClassAxiomsForSuperClass(classe).forEach(System.out::println);;  	
    }`

**Comment by ignazio1977** [comment]
Is the ontology available for replication?

**Comment by visraj1** [comment]
Unfortunately no, But is there any other alternatives I could try for? I am actually saving the ontology immediately  after checking for this satisfiability condition and then trying to view it in Protege.

**Comment by visraj1** [comment]
Kindly ignore. It was related to naming convention used while trying to run the reasoner.
