### ISSUE TITLE
OBO parser creates confusing rdfs labels from XREF fields

### ISSUE THREAD

**Issue by autayeu** [owlcs/owlapi#767]
Some OBO files contain XREF tags with a so-called "dbxref description". For example:
```
[Term]
id: SO:0000003
name: G_quartet
def: "G-quartets are unusual nucleic acid structures consisting of a planar arrangement where each guanine is hydrogen bonded by hoogsteen pairing to another guanine in the quartet." [http://www.ncbi.nlm.nih.gov/pubmed/7919797?dopt=Abstract]
synonym: "G quartet" EXACT []
synonym: "G tetrad" EXACT []
synonym: "G-quadruplex" EXACT []
synonym: "G-quartet" EXACT []
synonym: "G-tetrad" EXACT []
synonym: "G_quadruplex" EXACT []
synonym: "guanine tetrad" EXACT []
xref: http://en.wikipedia.org/wiki/G-quadruplex "wiki"
is_a: SO:0000002 ! sequence_secondary_structure
```
This example comes from [SO.obo](https://github.com/UCDenver-ccp/CRAFT/blob/master/ontology-concepts/SO/SO/SO.obo.zip) from [CRAFT dataset](https://github.com/UCDenver-ccp/CRAFT/).

Currently OBO parser translates such "dbxref description" ("wiki" from above) into "rdfs:label" and they end up inseparable from names ("G_quartet" from above). Perhaps this is not an intended effect.

It looks like this comes from [OWLAPIObo2Owl.java](https://github.com/owlcs/owlapi/blob/2a1c24d5421c782d8cf5004492a687d4a2b479d9/oboformat/src/main/java/org/obolibrary/obo2owl/OWLAPIObo2Owl.java), line 1241:
```java
annotations.add(fac.getRDFSLabel(xrefAnnotation));
```
Here is the surrounding block parsing XREF:
```java
        } else if (tagConstant == OboFormatTag.TAG_XREF) {
            Xref xref = (Xref) clause.getValue();
            String xrefAnnotation = xref.getAnnotation();
            if (xrefAnnotation != null) {
                annotations.add(fac.getRDFSLabel(xrefAnnotation));
            }
            ax = fac.getOWLAnnotationAssertionAxiom(trTagToAnnotationProp(tag), sub,
                trLiteral(clause.getValue()),
                annotations);
        } else {
```

**Comment by ignazio1977** [comment]
Need OBO experts to weigh in :-) @cmungall

**Comment by cmungall** [comment]
This is intentional but so usage is non standard. Intended to capture label of referenced entity. These are separable at either rdf or owl levels since they annotate axioms
