### ISSUE TITLE
OWLReasoner::instances should use IndividualNodeSetPolicy

### ISSUE THREAD

**Issue by Locke** [owlcs/owlapi#772]
I use owiapi with Openllet for a new project. I have some SWRL Rules with SameAs in the consequence, for example to combine different ontology files.

I try to use the Java Stream API as it appears to be the preferred way for new projects / the general future of owlapi.

As I usually don't need "duplicates" I looked into the IndividualNodeSetPolicy BY_SAME_AS.

While I get the expected results from the "old" API, like `getInstances` or `getObjectPropertyValues`, I get all individuals / the "duplicates" when I use the Stream API like `instances` or `objectPropertyValues`.

Technical background: `instances` is not overwritten by Openllet, therefore the default implementation from owlapi `getInstances(ce, direct).entities()` is used, which just flatMaps all entities without consideration of the IndividualNodeSetPolicy.

In my project I workaround this with a small helper function that calls the traditional API and then creates a stream based on `.nodes()` mapped with the `getRepresentativeElement` method.

So now to my question: with the Stream API in mind, should the IndividualNodeSetPolicy be applied at all, and if so on what level?

I currently see some possible directions:
1. change the default implementation `OWLReasoner.instances` et al. to respect IndividualNodeSetPolicy (would be a breaking change, maybe for owlapi 6)
2. keep the default implementations, and leave this to the reasoners, i.e. override `OWLReasoner.instances` in PelletReasoner (seems to me like the preferred way)
3. leave it to the user, who has to build a stream based on the traditional API (that's what I'm doing for now, but it feels wrong with a Stream API present)

**Comment by Locke** [comment]
Just a suggestion, based on my current workaround. You can better judge what approach to take. I'm happy to implement something if you guide me in the right direction.

Add a `representativeEntities` method to the DefaultNodeSet class, to have a direct Stream source:

```java
public Stream<E> representativeEntities() {
    return nodes().map(Node::getRepresentativeElement);
}
```

And change `OWLReasoner.instances` (etc..) to consider the IndividualNodeSetPolicy:

```java
default Stream<OWLNamedIndividual> instances(OWLClassExpression ce, boolean direct) {
    switch (this.getIndividualNodeSetPolicy()) {
        case BY_SAME_AS:
            return getInstances(ce, direct).representativeEntities();
        case BY_NAME:
            return getInstances(ce, direct).entities();
        default:
            throw new AssertionError("Unsupported IndividualNodeSetPolicy : " + this.getIndividualNodeSetPolicy());
    }
}
```

**Comment by ignazio1977** [comment]
Yes that's pretty much my plan :-) I'm going to skip the switch by having the filter on the enumeration and save a few lines of code.
