### ISSUE TITLE
Illegal reflective access for Guice when running ROBOT under Java 10

### ISSUE THREAD

**Issue by jamesaoverton** [owlcs/owlapi#775]
A ROBOT user has reported an "illegal reflective access" warning when using ROBOT with Java 10.0.1: https://github.com/ontodev/robot/issues/308

The warning points to `com.google.inject.internal.cglib.core.$ReflectUtils$2`, which is part of Guice. Since ROBOT doesn't use Guice directly, we think this might be rooted in OWLAPI. ROBOT uses OWLAPI 4.2.6, and we try to keep parity with Protege. The problem seems to have been fixed in more recent Guice releases, but in researching this we saw this recent rollback of to Guice version 4 for the OWLAPI `version4` branch: https://github.com/owlcs/owlapi/commit/71bfd8b52fd912c8bcb722f2f4a986ab7a2b9481

Has anyone else had problems with OWLAPI `version4` and Java 10?

Suggestions would be appreciated.

**Comment by ignazio1977** [comment]
The Guice dependency will be removed altogether. The version change was to revert an earlier, unnecessary version change that caused problems to other users.

**Comment by jamesaoverton** [comment]
Works for me. Thanks!

**Comment by ignazio1977** [comment]
Fixed in OWLAPI 5.1.6 and 4.5.4
