### ISSUE TITLE
Allow creation of tautologies for n-ary axioms

### ISSUE THREAD

**Issue by ignazio1977** [owlcs/owlapi#776]
From ykazakov #306 

For example, we want to provide explanations of entailments in ELK as derivations (sequences of OWL axioms where every next axiom is derived from previous axioms by a simple rule). For this, we may need to use some tautological axioms, like SubClassOf(A A) or EquivalentClasses(ObjectIntersectionOf(A B) ObjectIntersectionOf(B A)) as initial axioms (if one wants to explain a derivation of a tautology, one always need to start with tautologies). The latter axiom would express that the conjunction is a commutative operation. However, OWL API would "swallow" the second argument of EquivalentClasses and our derivation would be broken. It is very difficult to predict when such things happen.

**Comment by ignazio1977** [comment]
Given the way `OWLDataFactoryImpl` and all `OWLObject` implementations currently work, my opinion is that the best way to accommodate this is a specialised provider and a flag passed to the `OWLObject` implementation to skip duplicate removal.

In the context of this requirement, I don't think roundtrip capabilities from an ontology file are required - switching duplicate removal off for general uses would allow roundtrip of these tautologies to file and back but it would be a behaviour change that would affect other applications as well, and would only manifest in those places where arguments get assembled without checking for duplication. This might be very common - hard to tell in advance.

A specialised provider would not affect existing parsers, so the serialization of tautologies will either create axioms with the tautology removed or cause an exception. It could be possible to avoid throwing exceptions in parsing with a property.

Having said that, a property could be enough to allow the functionality without the need for specialised providers. However, this would not allow to fine tune where duplication would be removed and where it would stay - `OWLDataFactoryImpl` is instantiated as a singleton so there would be no context available.

**Comment by Cosmopal** [comment]
> a specialised provider and a flag passed to the OWLObject implementation to skip duplicate removal.

@ignazio1977 I was trying to have a look at how to incorporate this change. Would this mean adding an aditional provider to the list of providers OWLDataFactory implements already? In that case, that new provider would be an extension of DisjointAxiomProvider ?

**Comment by Cosmopal** [comment]
@ignazio1977 
> a specialised provider and a flag passed to the OWLObject implementation to skip duplicate removal.

I was looking at how to go about making this work. Do we need to create a new (specialised provider)? Can't it be done by adding an overload function which takes in a boolean argument to indicate that duplicates need to be kept? 

I am asking this because, as an example, the code creating set from input arguments is in the definition of the interface EquivalentAxiomProvider

Since that is an overload function, it won't matter unless the user specifically chooses to control duplicate removal by passing boolean argument. This will also make sure that existing applications are not affected
