### ISSUE TITLE
Swrl rule engine to work with java code generated from an .owl ontlogy

### ISSUE THREAD

**Issue by olufjen** [owlcs/owlapi#779]
Hello
I am generating java code from an ontology created and maintained in Protege version 5.2.0
In the pom.xml file for generating a .jar file for this generated java code I need the dependency for:
<dependency>
<groupId>edu.stanford.protege</groupId>
<artifactId>org.protege.editor.owl.codegeneration</artifactId>
<version>1.0.2</version>
</dependency>

which is, as far I can see the latest version for the ..owl.codegeneration.

Now, in the dependency tree for this dependency, I get the following:
| | \- net.sourceforge.owlapi:owlapi-distribution:jar:3.4.3:compile
| \- net.sourceforge.owlapi:owlapi-contract:jar:3.4.3:compile
| | \- net.sourceforge.owlapi:owlapi-apibinding:jar:3.4.3:compile
 | | +- net.sourceforge.owlapi:owlapi-api:jar:3.4.3:compile
 | | +- net.sourceforge.owlapi:owlapi-impl:jar:3.4.3:compile
 | | +- net.sourceforge.owlapi:owlapi-parsers:jar:3.4.3:compile
| | \- net.sourceforge.owlapi:owlapi-tools:jar:3.4.3:compile

Now, when I try to include swrl rule engine:
<dependency>
<groupId>edu.stanford.swrl</groupId>
<artifactId>swrlapi</artifactId>
<version>${swrlapi.version}</version>
</dependency>

<dependency>
<groupId>edu.stanford.swrl</groupId>
<artifactId>swrlapi-drools-engine</artifactId>
<version>${swrlapi.drools.version}</version>
</dependency>
Note: ${swrlapi.version} and ${swrlapi.drools.version} is 2.0.5
And the -osgidistribution:

<dependency>
<groupId>net.sourceforge.owlapi</groupId>
<artifactId>owlapi-osgidistribution</artifactId>
<version>4.2.8</version>
</dependency> 

Then these are not compatible with the owlapi-distributions 3.4.3 as shown above.
My question is, how can I make the swrl rule engine work together with the generated java code from my .owl ontology?
Any comment or assistence is appreciated.

**Comment by olufjen** [comment]
Hello
Some additional information:
When I try to replace the 3.4.3 owlapi-distribution with the owlapi-distribution 4.5.4, the ChessFactory fails to create individuals from the java code generated from the .owl ontology.

**Comment by olufjen** [comment]
Hello
The concept "ChessFactory" may be misleading. It is the Factory object that is used to create individuals  from the java code generated from the .owl ontology.
Sorry.

**Comment by ignazio1977** [comment]
I believe the code behind the Protege plugin is in the library code-generation:
edu.stanford.protege:code-generation:2.0.0

The 2.0.0 version uses OWLAPI 4 (it uses HermiT 1.3.8.413 in its dependencies).
This should be compatible with the other libraries you're trying to use.

**Comment by ignazio1977** [comment]
The best suggestion I can offer is to also use stackoverflow with the owl-api and protégé tags, that tends to get answers from a larger community than just the owlapi developers.
