### ISSUE TITLE
Using Hermit 1.3.8.431 to get inferred ontology file and further processing, unable to get inverse object properties

### ISSUE THREAD

**Issue by karanthpallavi** [owlcs/owlapi#781]
Have an object property "cites" and its inverse property "is cited by" in the ontology on which i further use hermit and get inferred ontology file.
In one of my applications, i use the inferred ontology file and have the following code:
for (OWLClass cls : ontology.getClassesInSignature()) 
        {
            if  (cls.getIRI().getFragment().equals("ScientificPublication"))
            {
                // Get all scientific publication
                OWLReasoner reasoner = reasonerFactory.createReasoner(ontology);
                NodeSet<OWLNamedIndividual> indivPapersSet = reasoner.getInstances(cls, true);
                Set<OWLNamedIndividual> Publications = indivPapersSet.getFlattened();
                int numOfPapers = Publications.size();
                System.out.println("Number of Scientific Publications to analyse for citations is "+numOfPapers);
                OWLObjectPropertyExpression expr;
                expr = dataFactory.getOWLObjectProperty("cites", prefixManager);
                Node<OWLObjectPropertyExpression> inversePropertiesNode = reasoner.getInverseObjectProperties(expr);
                Set<OWLObjectPropertyExpression> inverseObjectProperty = inversePropertiesNode.getEntities();
                OWLObjectPropertyExpression inverseProp = inverseObjectProperty.iterator().next();
                for(OWLNamedIndividual indivPublication : Publications)
                {
                    NodeSet<OWLNamedIndividual> isCitedByValues = reasoner.getObjectPropertyValues(indivPublication, inverseProp);
                    System.out.println("Publication : "+indivPublication);
                    System.out.println(" is cited by "+ isCitedByValues.getFlattened());
                }
            }
}

Output is:
Number of Scientific Publications to analyse for citations is 500
Publication : <http://www.semanticweb.org/drkm/ontologies/2018/1/untitled-ontology-105#042fb9d9-840e-445a-84d0-591887d3e880>
 is cited by []
Publication : <http://www.semanticweb.org/drkm/ontologies/2018/1/untitled-ontology-105#0e8e1246-b8c4-4ac9-9254-2a4a650c582b>
 is cited by []
Publication : <http://www.semanticweb.org/drkm/ontologies/2018/1/untitled-ontology-105#09ce5481-a5ec-4a05-99fe-7c9232f3a15c>
 is cited by []
Publication : <http://www.semanticweb.org/drkm/ontologies/2018/1/untitled-ontology-105#001c8744-73c4-4b04-9364-22d31a10dbf1>
 is cited by []
Publication : <http://www.semanticweb.org/drkm/ontologies/2018/1/untitled-ontology-105#04a259d4-1c49-4192-a1ec-c20b1fab56ec>
 is cited by []
Publication : <http://www.semanticweb.org/drkm/ontologies/2018/1/untitled-ontology-105#11671948-b0fb-4452-9e89-f9c0a419093b>
 is cited by []
Publication : <http://www.semanticweb.org/drkm/ontologies/2018/1/untitled-ontology-105#09bd2488-93ff-43e2-bac9-9ff2a9ec1fd5>
 is cited by []
Publication : <http://www.semanticweb.org/drkm/ontologies/2018/1/untitled-ontology-105#1d55283f-d753-4ea6-b4e7-1a796340ed7e>
 is cited by []
.......................... follows

The inverse object property values are null..
May I know why "is cited by" property values are not retrieved?

**Comment by ignazio1977** [comment]
Ensure that the properties you're creating with a prefix manager actually have the URLs used in the ontology.

You're using the first inverse property found for your property, but we don't have the ontology: we can't tell if there is more than one inverse or if they individuals have that property asserted.

You are calling for direct instances of your class - if the instances that have the property are not direct instances, they won't be found.

**Comment by karanthpallavi** [comment]
Thanks for your response,
One doubt:
The individuals in the ontology have been asserted for property "cites", and not for its inverse.
Reasoner should be able to infer the values for "is cited by" - inverse property right?

**Comment by ignazio1977** [comment]
I'd expect so.

**Comment by karanthpallavi** [comment]
This is not happening,
And all individuals for which the property assertions of "is cited by" are direct instances of the class Publication,
Not sure what's the problem?

**Comment by ignazio1977** [comment]
Without the ontology we can't help. Can this be replicated with a small test ontology?

**Comment by karanthpallavi** [comment]
will try that and get back, thanks much

**Comment by karanthpallavi** [comment]
Tried on a small ontology and doesnt seem to work,
Can i attest the small ontology?
May I know what could be the issue?
Tried on a small ontology and doesnt seem to work,
Can i attest the small ontology as text file?
May I know what could be the issue?

[inferredCiattionNetwork_text.txt](https://github.com/owlcs/owlapi/files/2336444/inferredCiattionNetwork_text.txt)

**Comment by ignazio1977** [comment]
The problem is what I recommended checking in my first comment. You have two `cites` properties:

`http://www.semanticweb.org/drkm/ontologies/2018/1/untitled-ontology-104#cites`

`http://purl.org/spar/cito/cites`

I strongly recommend not using prefix managers when dealing with known IRIs. Always use the actual IRI, it removes a common cause of error.

**Comment by karanthpallavi** [comment]
Ok, will rectify this... Thanks much..

**Comment by ignazio1977** [comment]
With the following amendments, code and ontology work:

        OWLOntology o = OWLManager.createOWLOntologyManager().loadOntologyFromOntologyDocument(
                new FileDocumentSource(new File("ontology.txt"), new FunctionalSyntaxDocumentFormat()));
        OWLReasoner r = new ReasonerFactory().createReasoner(o);
        OWLDataFactory df = OWLManager.getOWLDataFactory();
        OWLClass cls = df.getOWLClass(IRI.create("urn:test:ontology#ScientificPublication"));
        // Get all scientific publication
        NodeSet<OWLNamedIndividual> indivPapersSet = r.getInstances(cls, true);
        Set<OWLNamedIndividual> Publications = indivPapersSet.getFlattened();
        int numOfPapers = Publications.size();
        System.out.println("Number of Scientific Publications to analyse for citations is " + numOfPapers);
        OWLObjectPropertyExpression expr;
        expr = df.getOWLObjectProperty(IRI.create("http://purl.org/spar/cito/cites"));
        Node<OWLObjectPropertyExpression> inversePropertiesNode = r.getInverseObjectProperties(expr);
        Set<OWLObjectPropertyExpression> inverseObjectProperty = inversePropertiesNode.getEntities();
        OWLObjectPropertyExpression inverseProp = inverseObjectProperty.iterator().next();
        for (OWLNamedIndividual indivPublication : Publications) {
            NodeSet isCitedByValues = r.getObjectPropertyValues(indivPublication, inverseProp);
            System.out.println("Publication : " + indivPublication);
            System.out.println(" is cited by " + isCitedByValues.getFlattened());
        }


[ontology.txt](https://github.com/owlcs/owlapi/files/2343510/ontology.txt)
