### ISSUE TITLE
Error while parsing some ontologies

### ISSUE THREAD

**Issue by kittani** [owlcs/owlapi#782]
Hi all,

I am trying to parse more than 600 ontologies to extract the list of imported ontologies from each of them, using OWL API 5.1.6. The code failed to load around 100 files. But when I oped the failed files in Protege Desktop, they open without any problem. 
Down is the snippet that I used to load the ontologies and snapshot of the error. Also, I included one of the ontologies that failed.
I need a dynamic programming solution that can extract the list of imported ontologies from each of the tested files, besides the ontology terms (Classes, properties,...).
Thank you in advance.

*******************************************************************************************************
The snippet:
`File file = new File("C:\\vocabs\\" + Ontofile.getName());

OWLOntologyManager m = OWLManager.createOWLOntologyManager();
OWLOntology o;
o = m.loadOntologyFromOntologyDocument(file);
OWLDocumentFormat format = m.getOntologyFormat(o);

OWLOntologyXMLNamespaceManager nsManager = new 
OWLOntologyXMLNamespaceManager(o, format);

//To get the loaded ontology namespace
String ontoNS= nsManager.getDefaultNamespace();

//to extract all the imported ontology namespaces
for (String ns: nsManager.getNamespaces()) {
       System.out.println(ns);
}`

**********************************************************************************************************
the error:

`uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1033)
    uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:933)
    uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadImports(OWLOntologyManagerImpl.java:1630)

....

Could not parse JSONLD        org.eclipse.rdf4j.rio.jsonld.JSONLDParser.parse(JSONLDParser.java:110)
    org.semanticweb.owlapi.rio.RioParserImpl.parseDocumentSource(RioParserImpl.java:172)
    org.semanticweb.owlapi.rio.RioParserImpl.parse(RioParserImpl.java:125)

....

Stack trace:
org.eclipse.rdf4j.rio.RDFParseException: unqualified attribute 'class' not allowed [line 3, column 65]        
org.semanticweb.owlapi.rio.RioParserImpl.parse(RioParserImpl.java:138)
    uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:193)
    uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.load(OWLOntologyManagerImpl.java:1071)
    uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1033)
    uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:933)
    uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadImports(OWLOntologyManagerImpl.java:1630)

....`

*******************************************************************************************************
One of the failed files:

[acm.txt](https://github.com/owlcs/owlapi/files/2347387/acm.txt)

**Comment by ignazio1977** [comment]
Trying to parse the ontology generates errors loading the import:

`http://www.aktors.org/ontology/extension`

`www.aktors.org` appears to redirect to a commercial website selling reading glasses - I believe there is a problem with domains here, the ontology being imported is not available. Not sure how to fix that, other than by editing the ontology and removing the import.

**Comment by ignazio1977** [comment]
Note that imported ontologies won't be found by looking up namespaces.

To get the IRIs imported by an ontology, use

` ontology.importsClosure().map(OWLImportsClosure::getIRI)`

**Comment by kittani** [comment]
So the problem was in www.aktors.org. If I remove this domain name from the ontology, will it work?

**Comment by kittani** [comment]
@ignazio1977  changed the incorrect domain, and run the experiment, but it still gives me the same errors.
I am wondering why it opens in Protege Desktop and failed to load using OWL API!

**Comment by ignazio1977** [comment]
Protege is likely setting the ontology manager to not throw exceptions when imports cannot be loaded. This can be done this way:

        OWLOntologyLoaderConfiguration config = m.getOntologyLoaderConfiguration();
        m.setOntologyLoaderConfiguration(
            config.setMissingImportHandlingStrategy(MissingImportHandlingStrategy.SILENT));
        m.loadOntologyFromOntologyDocument(new File("acm.txt"));

However, when your purpose is to find the imported ontologies from one ontology, this will give you incomplete results - any unreadable ontology will be skipped, so the imports closure will not be complete.

**Comment by kittani** [comment]
@ignazio1977 Great :+1:  It is working now. Thank you very much, Ignazio, you saved me  :) 
For the missed import, maybe I will check them manually.
