### ISSUE TITLE
xsd:nonNegativeInteger from Cardinality Restrictions is not included into the ontology signature

### ISSUE THREAD

**Issue by sszuev** [owlcs/owlapi#783]
Is it by design, as intended?
Thanks in advance.

The snippet:

        OWLDataFactory df = m.getOWLDataFactory();

        // prepare:
        OWLDataRange r = df.getOWLDataOneOf(df.getOWLLiteral("-1", 
                OWL2Datatype.XSD_NEGATIVE_INTEGER), df.getOWLLiteral(2));
        OWLClassExpression c = df.getOWLDataMaxCardinality(12, df.getOWLDataProperty("P"));
        OWLAnnotation a = df.getOWLAnnotation(df.getRDFSComment(), df.getOWLLiteral("L", "lang"));
        // create:
        OWLOntology o = m.createOntology();
        o.add(df.getOWLDatatypeDefinitionAxiom(df.getOWLDatatype("D"), r, Collections.singletonList(a)));
        o.add(df.getOWLSubClassOfAxiom(df.getOWLClass("C"), c));

        // print:
        o.datatypesInSignature().forEach(x -> System.out.println("DT: " + x));

        // expected 6(?) datatypes: <D>, rdf:langString, rdfs:Literal, 
        // xsd:integer, xsd:nonNegativeInteger, xsd:negativeInteger
        Assert.assertEquals(6, o.datatypesInSignature().count());

**Comment by ignazio1977** [comment]
My best guess is that this was intentional. The integer used for cardinalities is not seen as part of the signature because it cannot be any other type.
