### ISSUE TITLE
HermiT rejecting owl:topDataProperty relationships

### ISSUE THREAD

**Issue by albamig** [owlcs/owlapi#786]
An ontology which holds an axiom such that it links an individual with a datatype through the topDataProperty leads HermiT (both 1.4.1 with the OWL API 5.1.5 and 1.3.8.413 with Protègè 5.2.0) to throw the following exception:

```
[Classification Thread] ERROR OWLReasonerManager    An error occurred during reasoning: Error: In OWL 2 DL, owl:topDataProperty is only allowed to occur in the super property position of SubDataPropertyOf axioms, but the ontology contains an axiom tobby topDataProperty "4"^^int that violates this condition..
java.lang.IllegalArgumentException: Error: In OWL 2 DL, owl:topDataProperty is only allowed to occur in the super property position of SubDataPropertyOf axioms, but the ontology contains an axiom tobby topDataProperty "4"^^int that violates this condition.
	at org.semanticweb.HermiT.structural.OWLNormalization$AxiomVisitor.checkTopDataPropertyUse(OWLNormalization.java:697) ~[na:na]
	at org.semanticweb.HermiT.structural.OWLNormalization$AxiomVisitor.visit(OWLNormalization.java:756) ~[na:na]
	at uk.ac.manchester.cs.owl.owlapi.OWLDataPropertyAssertionAxiomImpl.accept(OWLDataPropertyAssertionAxiomImpl.java:119) ~[na:na]
	at org.semanticweb.HermiT.structural.OWLNormalization.processAxioms(OWLNormalization.java:175) ~[na:na]
	at org.semanticweb.HermiT.structural.OWLNormalization.processOntology(OWLNormalization.java:167) ~[na:na]
	at org.semanticweb.HermiT.structural.OWLClausification.preprocessAndClausify(OWLClausification.java:153) ~[na:na]
	at org.semanticweb.HermiT.Reasoner.loadOntology(Reasoner.java:208) ~[na:na]
	at org.semanticweb.HermiT.Reasoner.<init>(Reasoner.java:199) ~[na:na]
	at org.semanticweb.HermiT.Reasoner.<init>(Reasoner.java:173) ~[na:na]
	at org.semanticweb.HermiT.ReasonerFactory.createHermiTOWLReasoner(ReasonerFactory.java:51) ~[na:na]
	at org.semanticweb.HermiT.ReasonerFactory.createReasoner(ReasonerFactory.java:19) ~[na:na]
	at org.protege.editor.owl.model.inference.ReasonerUtilities.createReasoner(ReasonerUtilities.java:20) ~[na:na]
	at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.ensureRunningReasonerInitialized(OWLReasonerManagerImpl.java:428) ~[na:na]
	at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.run(OWLReasonerManagerImpl.java:386) ~[na:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_40]
```

The straightforward ontology [infTestTopDataProp.txt](https://github.com/owlcs/owlapi/files/2366387/infTestTopDataProp.txt) can be used to test this issue.

This should not happen since, as stated in https://www.w3.org/TR/owl2-syntax/#Data_Properties, "The data property with IRI owl:topDataProperty connects all possible individuals with all literals".
I cannot figure out what the error message has to do with the actual axiom either, since the latter does not involve any SubDataPropertyOf relationship (see https://www.w3.org/TR/owl2-syntax/#The_Restrictions_on_the_Axiom_Closure).

What is remarkable is that the [infTestTopDataProp.txt](https://github.com/owlcs/owlapi/files/2366387/infTestTopDataProp.txt) ontology has been created by HermiT itself (1.4.1 through the OWL API 5.1.5) as an inferred ontology of [testTopDataProp.txt](https://github.com/owlcs/owlapi/files/2366388/testTopDataProp.txt) i.e. HermiT is building an ontology which cannot read. This is the snippet of code I am using to create the inferred ontology:

```
List<InferredAxiomGenerator<? extends OWLAxiom>> generators = new ArrayList<InferredAxiomGenerator<? extends OWLAxiom>>();
generators.add(new InferredClassAssertionAxiomGenerator());
generators.add(new InferredDataPropertyCharacteristicAxiomGenerator());
generators.add(new InferredDisjointClassesAxiomGenerator());
generators.add(new InferredEquivalentClassAxiomGenerator());
generators.add(new InferredEquivalentDataPropertiesAxiomGenerator());
generators.add(new InferredEquivalentObjectPropertyAxiomGenerator());
generators.add(new InferredInverseObjectPropertiesAxiomGenerator());
generators.add(new InferredObjectPropertyCharacteristicAxiomGenerator());
generators.add(new InferredPropertyAssertionGenerator());
generators.add(new InferredSubClassAxiomGenerator());
generators.add(new InferredSubDataPropertyAxiomGenerator());
generators.add(new InferredSubObjectPropertyAxiomGenerator());

OWLOntology infOnt = mOntologyManager.createOntology();
InferredOntologyGenerator iog = new InferredOntologyGenerator(mReasoner, generators);
iog.fillOntology(mOntologyManager.getOWLDataFactory(), infOnt);

File fileformated = new File("U:/ontologies/infTestTopDataProp.owl");
OutputStream outputStream = new FileOutputStream(fileformated);
try {
 mOntologyManager.saveOntology(infOnt, outputStream);
} catch (OWLOntologyStorageException e) {
 e.printStackTrace();
}
```

Currently, I use the RDF/XML format but have tested different possibilities and still does not work. 
Furthermore, I have tried to reason over it with both Pellet and Fact++ embedded in Protègè and it works like a charm. This could mean that the bug is somehow in HermiT.

It is also interesting to mention that this just happens when you have already stated some data property to be a subproperty of the topDataProperty. Otherwise, you need a second execution to be able to infer the axioms which connect each pair of individual/datatype through the topDataProperty.

Thank you very much in advance,
Alberto Amigo.

**Comment by ignazio1977** [comment]
OK there are a few independent things going on:

HermiT is not rejecting a sub property axiom, it is saying the construct used can only occur in an asserted axiom if it is a sub property axiom. This is on accordance with the same owl spec you quoted:

> Restriction on owl:topDataProperty. The owl:topDataProperty property occurs in Ax only in the superDataPropertyExpression part of SubDataPropertyOf axioms.

There's an explanation of why the restriction exists in the page. In short, accepting such an axiom invalidates some of the owl semantics.

Pellet and FaCT++ are likely identifying the same issue and deciding to ignore the offending axiom. They might be logging messages to that effect.

It is a good point to ask for reasoners to automatically ignore such axioms - it is likely to be an useful feature. However, it is not wrong for the reasoner to throw of out.

More in the next comment.

**Comment by ignazio1977** [comment]
About HermiT creating an ontology and not being able to read it, that's not a good characterisation of what's happening. The `OWLReasoner` interface implemented by the reasoners mentioned here does not allow them to create or read ontologies - what's happening here is that the inferred axioms are being saved and treated as asserted axioms. This is usually ok, although it can be wasteful - you're reasoning over the data twice. Turning inferred axioms into asserted axioms reduces the time required to answer queries when no reasoner is used, for example by feeding the inferred ontology to a mock reasoner implementation like `StructuralReasoner`. It can, sometimes, reduce the reasoning time - e.g., if a class is asserted to be subclass of owl:Nothing, satisfiability will be very fast. However, most reasoners are not designed to receive as input the result of their inferences, and this can affect their performance (e.g., FaCT++ performs better with DisjointClasses being presented as one axiom rather than explicited as pairwise disjoints, as it happens when generating inferences.

And, as you have found, in some cases inferred axioms cannot be asserted.

**Comment by ignazio1977** [comment]
Side notes: 

 - The format of the ontology is not relevant here. These limitations are format independent.

 - The inference you're computing does not strike me as useful. Any data property assertion is always part of the instances of topDataProperty assertions, same as all individuals are instances of owl:Thing. I'm not sure what is the advantage in expliciting them.

**Comment by albamig** [comment]
Ok, I get it. 

1. I drew a different meaning of this restriction, now it makes sense.

2. I mainly was under the misconception of mixing up asserted and inferred axioms. I thought that was just a pragmatic distinction, but in conceptual terms they were interchangeable.

3. Of course this sort of relationships are completely useless and I don't need them at all. It was just a conceptual issue and wanted to understand why it was behaving the way it did. Actually, I was afraid of how it affected scalability.

Thanks ever so much @ignazio1977 , your support is very much appreciated.
