### ISSUE TITLE
Add OWLClassExpression.isNamed method

### ISSUE THREAD

**Issue by matthewhorridge** [owlcs/owlapi#790]
There is ```OWLClassExpression.isAnonymous``` but please can we have ```OWLClassExpression.isNamed``` or ```OWLClassExpression.isNamedClass```?  This would make some stream processing look nicer.

**Comment by ignazio1977** [comment]
This was introduced in v6 a while back, I'll cherry pick to v4 and v5.

**Comment by matthewhorridge** [comment]
Thanks... from us poor souls stuck on 4 ;)

**Comment by ignazio1977** [comment]
There was a proposal for changing package names for newer versions and add a v4 compatible wrapper layer to simplify upgrading for systems like Protege, where there's a lot of third party code that cannot be left behind. Might be worth giving it some thought.

**Comment by matthewhorridge** [comment]
Well that would be lovely!

**Comment by ignazio1977** [comment]
see #617 for adapters
