### ISSUE TITLE
[Question] OWL API 5 and OWL Link

### ISSUE THREAD

**Issue by mrnolte** [owlcs/owlapi#793]
Hey there,
When trying to get the reasoner Konclude to work, I encounter the problem that the latest version of OWLLink seems to only support the OWL API 3.2. Their implemented reasoner throws exceptions in combination with OWL API 5. Am I correct in assuming that you guys do not support OWL Link?

Best regards,
Robin

**Comment by ignazio1977** [comment]
No, OWLLink is not supported by OWLAPI directly.

Is this the 2011 OWLLink release? I can find the source only on SourceForge. I'm happy to take a a look at what would be required to make it work with OWLAPI 5.

**Comment by ignazio1977** [comment]
I've had a look - doable but by no means a small job. Do you know if Olaf Noppens is still working on this project?

**Comment by mrnolte** [comment]
Thanks for your fast help, it's very much appreciated. The 2011 release seems to be the most recent. I haven't been able to find out if OWLLink is still being maintained (by the appearance of the mailing list my guess is no), but I've written to the developers at derivo and am waiting for an answer.

**Comment by mrnolte** [comment]
As an update, the developers answered me this:
> Hi Marc,
>There are indeed some compatibility issues between the OWLlink adapter and the OWL API due to a lot of refactoring in the versions 4 and 5 of the OWL API. We prototypically upgraded the adapter to be partially compatibly with the OWL API 4 [1], i.e., it should be possible to use the OWLlink client functionalities (e.g., a java program using the OWL API 4.* with the upgraded adapter should be able to communicate with an OWLlink server such as Konclude) and at least some server functionalities should also work (e.g., I managed to provide the new OWL API 4 based reasoner Sequoia via the OWLlink (server) adapter and successfully retrieved the classification result). However, especially the latter may not yet support all kind of queries. Also, there are a few more changes in version 5 of the OWL API and we haven’t upgraded to them yet. But feel free to test the upgraded adapter and let us know, which functionality you require/does not yet work as expected.
>Best,
>Andreas
> [1] https://www.dropbox.com/s/ys3ajpmip0e3s3d/owllinkadapter-for-owlapi-4.7z?dl=1

**Comment by ignazio1977** [comment]
Good to know. I've managed to build against OWLAPI 5 but I'm not happy with the hacks I've had to put in place.

Main issue is that the OWLXML parser in OWLAPI 5 os package protected and has had a lot of class names changed. So, it cannot be easily extended. Using the parser from version 3 and updating it to work with OWLAPI 5 requires less work but also means more code in OWLLink to be maintained in the future.

**Comment by mrnolte** [comment]
> Main issue is that the OWLXML parser in OWLAPI 5 os package protected and has had a lot of class names changed. So, it cannot be easily extended. Using the parser from version 3 and updating it to work with OWLAPI 5 requires less work but also means more code in OWLLink to be maintained in the future.

Please don't bother when it's that much work. The OWLAPI 4 port will do for now as I will adapt my code to it. 

Andreas Steigmiller wrote me that the development of Konclude was resumed this year and that a direct OWLAPI Reasoner interface has already been experimented with. Maybe we' ll hear more about it in the future.

**Comment by ignazio1977** [comment]
I've got a build that compiles with OWLAPI 5, I'm going to push it to https://github.com/ignazio1977/owllink-owlapi/

I can't test it out, but if you want to give it a spin I'd appreciate feedback.

Good to know Konclude is under development :-)

**Comment by mrnolte** [comment]
Thank you very much for all your work!
Currently I get an exception, because `OWLXMLWriter `apparently must not be initialized with `null` as an `OWLOntology`, as done in `org.semanticweb.owlapi.owllink.renderer.OWLlinkXMLWriter` line 76:

```
Exception in thread "main" org.semanticweb.owlapi.owllink.OWLlinkReasonerRuntimeException
	at org.semanticweb.owlapi.owllink.HTTPSessionImpl.performRequests(HTTPSessionImpl.java:222)
	at org.semanticweb.owlapi.owllink.OWLlinkHTTPXMLReasoner.performRequests(OWLlinkHTTPXMLReasoner.java:472)
	at org.semanticweb.owlapi.owllink.OWLlinkHTTPXMLReasoner.performRequest(OWLlinkHTTPXMLReasoner.java:476)
	at org.semanticweb.owlapi.owllink.OWLlinkHTTPXMLReasoner.createDefaultKB(OWLlinkHTTPXMLReasoner.java:460)
	at org.semanticweb.owlapi.owllink.OWLlinkHTTPXMLReasoner.<init>(OWLlinkHTTPXMLReasoner.java:66)
	at org.semanticweb.owlapi.owllink.OWLlinkHTTPXMLReasonerFactory.createReasoner(OWLlinkHTTPXMLReasonerFactory.java:63)
	at dfki.cps.koncludeTest.KoncludeTest5.main(KoncludeTest5.java:41)
Caused by: java.lang.NullPointerException
	at org.semanticweb.owlapi.owlxml.renderer.OWLXMLWriter.<init>(OWLXMLWriter.java:79)
	at org.semanticweb.owlapi.owllink.renderer.OWLlinkXMLWriter.<init>(OWLlinkXMLWriter.java:76)
	at org.semanticweb.owlapi.owllink.renderer.OWLlinkXMLRenderer.render(OWLlinkXMLRenderer.java:68)
	at org.semanticweb.owlapi.owllink.HTTPSessionImpl.performRequests(HTTPSessionImpl.java:142)
	... 6 more

```

This is my code; any `OWLOntology` will reproduce the error:
```
final OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
final OWLOntology ontology = manager.createOntology();
final URL url = new URL("http://localhost:8080");
final OWLlinkReasonerConfiguration reasonerConfiguration = new OWLlinkReasonerConfiguration(url);
final OWLlinkHTTPXMLReasonerFactory factory = new OWLlinkHTTPXMLReasonerFactory();
final OWLReasoner reasoner = factory.createReasoner(ontology, reasonerConfiguration);
```

**Comment by ignazio1977** [comment]
New commit fixes the null pointer exceptions and should be good enough for local builds. Next step is a Maven build for Maven central release.
