### ISSUE TITLE
Allow Atomic Decomposition to skip assertions

### ISSUE THREAD

**Issue by zhaohaoruo** [owlcs/owlapi#796]
If we have an ontology which contains 4 axioms (3 Tbox axioms and 1 Abox axioms):
{A SubclassOf B, B SubClassOf C, D SubClassOf E, d Types D}
Then the bot-AD should gives us three atoms
a_1={A SubclassOf B}, a_2 = {B SubClassOf C}, a_3= {D SubClassOf E, d Types D}. And a_1 depends on a_2, but a_2 doesn't depend on a_3.
What the implementation gives us is that: a_1 depends on a_2, a_2 depends on a_3.

What's more, if you add another axiom: a Types A, the bot-AD result from the implementation will become a huge atom a_1 = {A SubclassOf B, B SubClassOf C, D SubClassOf E, d Types D, a Types A}.

I think the problem of this bug is that:
We do locality check for abox axioms and it will make errors. So modify AxiomSelector would be a good choice. We can just do AD on Tbox axioms and put our Abox axioms to the lowest atoms. 

Wish you have a good day.

**Comment by mrnolte** [comment]
This issue might be related to #704 . Does the proposed fix in #797 solve your problem as well? I wont be able to check it myself for the next few days

**Comment by zhaohaoruo** [comment]
> This issue might be related to #704 . Does the proposed fix in #797 solve your problem as well? I wont be able to check it myself for the next few days

That's not the same problem. I know #704  and #797. They are about STAR AD. 

But my question is about the AxiomSelector in
owlapi/tools/src/main/java/org/semanticweb/owlapitools/decomposition/
The abox and tbox axioms are all selected into the AtomicDecompositionImpl

wich means if you writer new AtomicDecompositionImpl(ontology, ModuleType.Bot) to build a new ad, the locality checker will also check abox axioms which will make the ad structure totally different.

This problem will cause that when people want to use ad method and their ontologies contain abox axioms, they need to delete the abox axioms. If they don't do that, they will get a totally different structure and this structure is not even an AD.

**Comment by mrnolte** [comment]
>The abox and tbox axioms are all selected into the AtomicDecompositionImpl
>
>wich means if you writer new AtomicDecompositionImpl(ontology, ModuleType.Bot) to build a new ad, the locality checker will also check abox axioms which will make the ad structure totally different.

Ah, thank you, now I understand your concern. However, this behavior seems correct to me, since the atomic decomposition is not defined exclusively over TBoxes; at least the [paper](https://www.ijcai.org/Proceedings/11/Papers/372.pdf) does not explicitly exclude them. As far as i understand, every ABox axiom should have a corresponding genuiene module. Because some assertions are not local with respect to a signature, they end up in the modules provided by the locality-based module extraction and are considered by the AD accordingly.
If one now wants to compute an AD only over the TBox axioms the other ones must be removed first as you stated.

**Comment by zhaohaoruo** [comment]
->every ABox axiom should have a corresponding genuine module. 
That's true. Then if you look back to the small example in the first comment.
->{A SubclassOf B, B SubClassOf C, D SubClassOf E, d Types D}
That's why the axiom D SubClassOf E and the axiom d Types D are in the same atom a_3. 
->a_1={A SubclassOf B}, a_2 = {B SubClassOf C}, a_3= {D SubClassOf E, d Types D}
But atom a_3 will never have a dependency relationship with a_2 and a_1. But when we use ad implementation to compute it, a_3 and a_2 will have one dependency relationship.  Then we will get a totally different structure. And when a_2 and a_3 have a dependency relation, the structure is not ad anymore.

And in the next example, the huge atom will tell us more about this problem. If you get genuine module w.r.t. the signature of axiom: d Types D. The signature is {D}, and then axiom: {SubClassOf E} is bot non-local w.r.t. the signature. Then we finish the module. axioms {A SubclassOf B, B SubClassOf C} will never jump into this module.

I am not saying that we should not exclude ABox axioms. I am saying that the ad implementation now makes something wrong with ABox axioms. So I suggest that you can modify the AxiomSelector part to fix this problem. I am a PhD in Manchester and major in AD. I make this suggestion because at least when people get an ad structure without ABox axioms, the structure is not a wrong one. To be honest, the ad algorithm is not friendly to ABox axioms. So we think you guys will compute the whole AD with TBox axioms then add the ABox axioms to the atoms before we find this problem.

If you don't mind, would you please fix this bug in a hurry? At least you can give users a AD structure without ABox axioms temporarily. Then some more modifications can be added.

Wish you have a good night.

**Comment by mrnolte** [comment]
I just tried your example {A⊑B, B⊑C, D⊑E, d:D}. The ⊥-modules with respect to the signature of each axiom are as follows:

Axiom | Module w.r.t. the signature
----- | -----
A⊑B    | {A⊑B, B⊑C, D⊑E, d:D}
B⊑C    | {B⊑C, D⊑E, d:D}
D⊑E   | {D⊑E, d:D}
d:D     | {D⊑E, d:D}

That results in the atoms a_1={A⊑B}, a_2={B⊑C}, a_3={D⊑E, d:D} as you already stated. I am not able to follow your next conclusion, though:

> And a_1 depends on a_2, but a_2 doesn't depend on a_3.

Since {A⊑B, B⊑C, D⊑E, d:D} is the only ⊥-module containing a_1 and includes both a_2 and a_3, a_1 depends on both a_2 and a_3, okay. But {A⊑B, B⊑C, D⊑E, d:D} and {B⊑C, D⊑E, d:D} are the ⊥-modules containing a_2 and both includes a_3, therefore a_2 should depend on a_3, am i right?

>What the implementation gives us is that: a_1 depends on a_2, a_2 depends on a_3.

Seems correct to me.

> And in the next example, the huge atom will tell us more about this problem. If you get genuine module w.r.t. the signature of axiom: d Types D. The signature is {D}, and then axiom: {SubClassOf E} is bot non-local w.r.t. the signature. Then we finish the module. axioms {A SubclassOf B, B SubClassOf C} will never jump into this module.

While D⊑E is non-⊥-local, a:A is non-⊥-local, too. I quote the explanation from [(Cuenca Grau et al., 2007)](http://www.cs.man.ac.uk/~sattler/publications/chks07-just.pdf): 

> Note that according to Definition 4, assertions a:A and r(a, b) can never be local since they can only be satisfied by interpretations that interpret A and r as non-empty sets. Hence, assertions must be included in every locality-based module, which is reflected by the step (3) of the transformation in Proposition 4.

where A isn't included in the signature (as A is not in S={D}). With a:A non-⊥-local, the signature expands and the ⊥-module w.r.t. the signature of each axiom is always {A⊑B, d:D, D⊑E, B⊑C, a:A}. *-modules are there to fix those issues.

**Comment by ignazio1977** [comment]
On issue #462 the functionality required to exclude assertions from module creation was added to the older module extraction classes. I believe what we're saying here is that we need the same functionality in AD.

**Comment by zhaohaoruo** [comment]
> I just tried your example {A⊑B, B⊑C, D⊑E, d:D}. The ⊥-modules with respect to the signature of each axiom are as follows:
> 
> Axiom	Module w.r.t. the signature
> A⊑B	{A⊑B, B⊑C, D⊑E, d:D}
> B⊑C	{B⊑C, D⊑E, d:D}
> D⊑E	{D⊑E, d:D}
> d:D	{D⊑E, d:D}
I think we reach the point. The module w.r.t. the signature {A,B} will not be the whole ontology. The module would be {A⊑B, B⊑C} without {D⊑E, d:D}. The key point is that don't do locality checker on ABox axioms.

Think about this situation, if we have an ontology with n axioms and the ontology contains y terms.

If these terms are all concept names, we just need to add no more than y ABox axioms, we will make the module become the whole ontology.

For example, if we have an ontology with 4 axioms and 8 terms (and they are all concept names):
{A⊑B, C⊑D, E⊑F, G⊑H}
Then we do bot-AD on this ontology, we will have 4 atoms as follows:
atom1={A⊑B}, atom2={C⊑D}, atom3={E⊑F}, atom4={G⊑H}. And these atoms don't have any dependency relations.

Then we just need to add 8 ABox axioms as follows:
{a:A, b:B, c:C, d:D, e:E, f:F, g:G, h:H}.

Then the whole ontology becomes {A⊑B, C⊑D, E⊑F, G⊑H, a:A, b:B, c:C, d:D, e:E, f:F, g:G, h:H}. And we have only one huge atom in the bot-ad 
atom =  {A⊑B, C⊑D, E⊑F, G⊑H, a:A, b:B, c:C, d:D, e:E, f:F, g:G, h:H}

And just have one module (the whole ontology) whatever the signature is
module = {A⊑B, C⊑D, E⊑F, G⊑H, a:A, b:B, c:C, d:D, e:E, f:F, g:G, h:H}

Then our AD algorithm and Syntactic Module extraction algorithm are useless because of this problem. 

So if you don't mind, would you please fix the problem both in AD part and Module Extraction part?

Wish you have a good day.

**Comment by zhaohaoruo** [comment]
Hi All

Just realise it is not a bug. It is just our AD and Modularity methods work badly on the ontology with ABox axioms. It is my misunderstanding of AD and Modularity. Sorry about that. Sorry for any inconvenience I have made.

Wish you all have a good day.

**Comment by ignazio1977** [comment]
As mentioned earlier, modularity has a switch to leave aboxes out. We can add the same convenience to AD.
