### ISSUE TITLE
Error : Can only Iterate over an array of instance Java.lang.iteratable

### ISSUE THREAD

**Issue by Sobitan** [owlcs/owlapi#799]
Hello,
I am abit new in the world of ontology. I got the latest SimpleHierarchyExample.java code from github and included an ontology .owl dataset but the solution does not compile due to an error message on the line getAnnotationObjects(clazz, ontology) where the above error message is returned. 
I attempted to resolve this by creating a collection Collection<OWLAnnotation> ontologyList = (Collection<OWLAnnotation>)getAnnotationObjects(clazz, ontology) but that still lead to an error.
Pls do you have any advise on how I can go about resolving this error?
Thanks

**Comment by ignazio1977** [comment]
Can you show the code that you're using and tell us which OWLAPI version is involved?

**Comment by ignazio1977** [comment]
From the source code of SimpleHierarchyExample, I think the problem is that you're compiling it against a different OWLAPI version than the one it was written for.

**Comment by Sobitan** [comment]
Thanks for the quick response,
Yes, the version of code I am using is the exact one in this below link:
https://github.com/owlcs/owlapi/blob/version4/contract/src/test/java/uk/ac/manchester/owl/owlapi/tutorial/examples/SimpleHierarchyExample.java
The branch version is version 4
I will check the .jar files I am importing as external libraries and confirm.

**Comment by Sobitan** [comment]
Yes I was able to resolve it with the version link https://github.com/owlcs/owlapi/wiki/All-Releases its working correctly now. Thanks for the help.
