### ISSUE TITLE
Unable to get instances of OWL Class correctly - version 5.1.5 of OWL-API and Hermit - 1.4.1.513

### ISSUE THREAD

**Issue by karanthpallavi** [owlcs/owlapi#800]
Have used the following code to get instances of class Movie:

String base = "http://www.semanticweb.org/drkm/ontologies/2018/5/untitled-ontology-42#";
OWLDataFactory dataFactory = manager.getOWLDataFactory();
        OWLClass movieClass = dataFactory.getOWLClass(IRI.create(base+"Movie"));
        System.out.println("Class "+movieClass);
        Reasoner.ReasonerFactory factory = new Reasoner.ReasonerFactory();
         Configuration configuration=new Configuration();
         configuration.throwInconsistentOntologyException=false;
         OWLReasoner reasoner=factory.createReasoner(ontology, configuration);
         System.out.println("In Genre Coverage");
        // Get individuals of class Movie
        Set<OWLNamedIndividual> indivMovies = reasoner.getInstances(movieClass, true).getFlattened();
        OWLObjectProperty hasCast = dataFactory.getOWLObjectProperty(IRI.create(base+"hasCast"));
        Iterator iterMovie = indivMovies.iterator();
        while(iterMovie.hasNext())
        {
            OWLNamedIndividual eachMovie = (OWLNamedIndividual) iterMovie.next();
            // Get hasCast assertions of this individual
            Set<OWLNamedIndividual> castOfThisMovie = reasoner.getObjectPropertyValues(eachMovie, hasCast).getFlattened();
            System.out.println("Movie: "+eachMovie);
            System.out.println("---------------------------------------------------------------------------");
            for(OWLNamedIndividual eachCast: castOfThisMovie)
            {
                System.out.println("Cast "+ eachCast.getIRI().getShortForm());
            }
            System.out.println("---------------------------------------------------------------------------");
        }

May I know what may be the issue?
It gives me instances of all classes and not just Movie class

**Comment by ignazio1977** [comment]
Can you please add the ontology without the inferred axioms? It is impossible to figure out what is being expressed in this ontology due to the noise from irrelevant axioms.

We've been through how unnecessary it is to put the inferred axioms back in the ontology when using a reasoner in other issues.

**Comment by karanthpallavi** [comment]
Ok, thanks will use the latest version of Hermit then,
Thanks much for all the support

**Comment by karanthpallavi** [comment]
Found an issue again with Hermit 1.4.3.517,

Though the ontology does not contain equivalent data properties, when i run my application, i get the following error:
Exception in thread "main" java.lang.IllegalArgumentException: Error: In OWL 2 DL, owl:topDataProperty is only allowed to occur in the super property position of SubDataPropertyOf axioms, but the ontology contains an axiom EquivalentDataProperties(owl:topDataProperty ) that violates this condition.
May i know if this can be resolved?

**Comment by karanthpallavi** [comment]
Found an issue again with Hermit 1.4.3.517,

Though the ontology does not contain equivalent data properties, when i run my application, i get the following error:
Exception in thread "main" java.lang.IllegalArgumentException: Error: In OWL 2 DL, owl:topDataProperty is only allowed to occur in the super property position of SubDataPropertyOf axioms, but the ontology contains an axiom EquivalentDataProperties(owl:topDataProperty ) that violates this condition.
May i know if this can be resolved?

**Comment by ignazio1977** [comment]
I don't get the same issue with the ontology attached to this issue. Which ontology causes the issue?

**Comment by ignazio1977** [comment]
Ok. As discussed a few times before, reasoners don't do well with reasoning on ontologies where inferred axioms are added back in. Also, reasoning again on ontologies where inferred axioms have been asserted is not useful - it just forces the reasoner to do the same work twice.

**Comment by ignazio1977** [comment]
In particular, all inferred axioms that say `property x subproperty of topDataProperty` (or `topObjectProperty`) are useless axioms. They add no information to the ontology.

**Comment by karanthpallavi** [comment]
Ok, i get it..
Will try on the non inferred version of ontology,
Thanks much
