### ISSUE TITLE
Question about TOP, BOT and STAR module types

### ISSUE THREAD

**Issue by fanavarro** [owlcs/owlapi#801]
Hi, I would like to use the module extractor to split ontologies, but I do not understand how work the different strategies that could be applied. I've found some informal definitions on the web for TOP and BOT strategies (thanks to Thomas Schneider in [this post](https://sourceforge.net/p/owlapi/mailman/message/27411646/)):

The BOT module gives you the guarantee that, for every class in the seed signature, all of its (asserted and inferred) superclasses are included in the module, together with the respective axioms that witness this relationship. However, it adds more unnecessary stuff than the STAR module.

The TOP module gives you the dual guarantee: for every class in the seed signature, all of its (asserted and inferred) subclasses are included in the module, together with the respective axioms that witness this relationship. However, it adds more unnecessary stuff than the STAR module and is notorious for being way too large -- after all, if a few top-level classes happen to be in the seed signature, the whole "subtree" of the class hierarchy, and related axioms, are included.

Nonetheless I have not found any explanation for STAR strategy neither in [Manchester modularity page](http://owl.cs.manchester.ac.uk/research/modularity/) nor in the linked articles in that page.

Could you please provide the document where this information is specified or an informal explanation?

Thanks in advance and congratulations for your work.

Fran.

**Comment by ignazio1977** [comment]
STAR consists in applying both top and bottom strategies, repeating the process until no more changes are made to the module.

See for example http://ceur-ws.org/Vol-1081/womo2013_proceedings.pdf for comparisons with other methods.

**Comment by fanavarro** [comment]
Thanks Ignazio, this is what I was looking for.
Greetings,
Fran
