### ISSUE TITLE
Parse exception from API past

### ISSUE THREAD

**Issue by rwynne** [owlcs/owlapi#802]
I have a very old program using version... 2.2.1(?!)...requiring OWL1.1 input.  It hasn't been run in years, but now throws the following exception on parse.

Parser: RDFXMLParser
org.xml.sax.SAXParseException; systemId: http://protege.stanford.edu/plugins/owl/protege; lineNumber: 1; columnNumber: 50; White spaces are required between publicId and systemId.

Can I make a quick edit to the schema location in the OWL, or would I need to refactor my code to the latest version?

**Comment by ignazio1977** [comment]
Depends what the problem actually, is, what's the first line of the input?

**Comment by rwynne** [comment]
Not a DOCTYPE...
The file loads into Protege 3.x and 5 without issue.

<?xml version="1.0"?>
<rdf:RDF
    xmlns:xsp="http://www.owl-ontologies.com/2005/08/07/xsp.owl#"
    xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#"
    xmlns:owl2xml="http://www.w3.org/2006/12/owl2-xml#"
    xmlns:swrlb="http://www.w3.org/2003/11/swrlb#"
    xmlns:swrl="http://www.w3.org/2003/11/swrl#"
    xmlns:protege="http://protege.stanford.edu/plugins/owl/protege#"
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
    xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
    xmlns:owl="http://www.w3.org/2002/07/owl#"
    xmlns:ncicp="http://ncicb.nci.nih.gov/xml/owl/EVS/ComplexProperties.xsd#">
  <owl:Ontology rdf:about="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl">
    <rdfs:comment rdf:datatype="http://www.w3.org/2001/XMLSchema#string"
    >NCI Thesaurus, a controlled vocabulary in support of
NCI administrative and scientific activities.

Produced by the Enterprise Vocabulary System (EVS), a project 
by the NCI Center for Bioinformatics.  National Cancer Institute,
National Institutes of Health, Bethesda, MD 20892, U.S.A.</rdfs:comment>
    <protege:defaultLanguage rdf:datatype="http://www.w3.org/2001/XMLSchema#string"
    >en</protege:defaultLanguage>
    <owl:versionInfo rdf:datatype="http://www.w3.org/2001/XMLSchema#string"
    >11.10e</owl:versionInfo>

**Comment by rwynne** [comment]
Hah, I can't paste it.. but this is the first line..

lessthan ?xml version="1.0"? greaterthan

**Comment by ignazio1977** [comment]
Uhm, puzzling. Doesn't get to 50 characters even.

This program that's not been run in years, will t run often from now on? :-D

**Comment by rwynne** [comment]
It's just an ancient workhorse the editors used, now being looked at for a prototype mapping application.

https://github.com/NCIEVS/ops-owl-applications/tree/master/OWLCompare

The distribution they used (link emailed offline) contains an example raw OWL if you're interested.  I am going to try and rule out Java as it appears I built the jars with 5 and our Tech Stack is now on 8.

**Comment by ignazio1977** [comment]
This might be to do with validation or loading of external DTDs, which in recent OWLAPI versions we disable by default.

Currently we do this by creating all sax parser factories in `SaxParsers` and explicitly tweaking the options. I believe it could be done for all factories without code changes through system properties - otherwise the code for OWLAPI 2 would need tweaking to do the same thing as `SaxParsers`.

**Comment by ignazio1977** [comment]
Updating the code in OWLCompare to OWLAPI 5 looks pretty simple (patch in the next comment), however I wonder if that's a good move - is it meant to work on OWL 1.1 files in the future, or will it work with OWL 2 files? I would expect it to matter little in most cases, but it might turn out that there are assumptions on the input (e.g., I can see references to matching properties by rdf:ID; there might be other dependencies on the exact shape of the OWL file.)

**Comment by ignazio1977** [comment]
Patch content:

diff --git a/OWLCompare/src/gov/nih/nci/owl/OWLCompare.java b/OWLCompare/src/gov/nih/nci/owl/OWLCompare.java
index 512a42a..14705a7 100644
--- a/OWLCompare/src/gov/nih/nci/owl/OWLCompare.java
+++ b/OWLCompare/src/gov/nih/nci/owl/OWLCompare.java
@@ -30,12 +30,13 @@
 import org.apache.poi.ss.usermodel.Row;
 import org.apache.poi.ss.usermodel.Sheet;
 import org.apache.poi.ss.usermodel.Workbook;
-import org.semanticweb.owl.apibinding.OWLManager;
-import org.semanticweb.owl.model.OWLAnnotation;
-import org.semanticweb.owl.model.OWLClass;
-import org.semanticweb.owl.model.OWLException;
-import org.semanticweb.owl.model.OWLOntology;
-import org.semanticweb.owl.model.OWLOntologyManager;
+import org.semanticweb.owlapi.apibinding.OWLManager;
+import org.semanticweb.owlapi.model.IRI;
+import org.semanticweb.owlapi.model.OWLClass;
+import org.semanticweb.owlapi.model.OWLException;
+import org.semanticweb.owlapi.model.OWLOntology;
+import org.semanticweb.owlapi.model.OWLOntologyManager;
+import org.semanticweb.owlapi.search.EntitySearcher;
 
 public class OWLCompare {
 
@@ -196,7 +197,7 @@
 		try {
 			System.out.println("Loading OWL file.");
 			manager = OWLManager.createOWLOntologyManager();
-			ontology = manager.loadOntologyFromPhysicalURI(physicalURI);
+			ontology = manager.loadOntologyFromOntologyDocument(IRI.create(physicalURI));
 		} catch (OWLException e) {
 			e.printStackTrace();
 			System.out
@@ -223,7 +224,7 @@
 		// Where a key exists (match), tack an OWLClass object on as a value.
 		int classCount = 0;
 		boolean allowClass = true;
-		Set<OWLClass> ocls = ontology.getReferencedClasses();
+		Set<OWLClass> ocls = ontology.getClassesInSignature();
 		for (OWLClass c : ocls) {
 
 			classCount++;
@@ -582,7 +583,7 @@
 
 	public Vector<String> getProperties(OWLClass c, String property) {
 		Vector<String> v = new Vector<String>();
-		for (OWLAnnotation anno : c.getAnnotations(ontology)) {
+		EntitySearcher.getAnnotationObjects(c, ontology).forEach(anno-> {
 			String annotationValue = anno.toString();
 			if (annotationValue.contains("Annotation(" + property)) {
 				// get property value, return the new value
@@ -598,7 +599,7 @@
 				 */
 				// System.out.println(property + " match value is: " + value);
 			}
-		}
+		});
 		return v;
 	}
 
@@ -784,26 +785,17 @@
 	}
 
 	private boolean isRetired(OWLClass c) {
-		boolean retired = false;
-		for (OWLAnnotation anno : c.getAnnotations(ontology)) {
-			String annotationValue = anno.toString();
-			if (annotationValue
-			        .contains("Annotation(Concept_Status \"Retired_Concept")) {
-				retired = true;
-				break; // I've seen enough
-			}
-		}
-		return retired;
+		return EntitySearcher.getAnnotationObjects(c, ontology).anyMatch(anno->anno.toString().contains("Annotation(Concept_Status \"Retired_Concept"));
 	}
 
 	private Vector<String> getPropertyValues(OWLClass c) {
 		Vector<String> v = new Vector<String>();
-		String property = new String("");
-		String qualifier = new String("");
 
-		for (OWLAnnotation anno : c.getAnnotations(ontology)) {
+		EntitySearcher.getAnnotationObjects(c, ontology).forEach(anno-> {
 			String annotationValue = anno.toString();
 			for (Vector<String> targetProperty : propertiesToMatch) {
+			    String property = "";
+			    String qualifier = "";
 				if (targetProperty.size() > 1) {
 					property = targetProperty.elementAt(0);
 					qualifier = targetProperty.elementAt(1);
@@ -857,7 +849,7 @@
 					// value);
 				}
 			}
-		}
+		});
 
 		return v;
 	}

**Comment by rwynne** [comment]
Thanks @ignazio1977 !

There was one particular assumption from our OWL1 files the program expects.  The files use embedded xml with CDATA on some annotation values for qualified values.  Now with OWL2 this assumption is removed- those annotations have owl:Axioms targeting the class and value, with the qualified values as annotations.

It makes sense to upgrade the API with a patch as you suggest.  I would also likely need to add an option for the OWL version to toggle the assumption.
