### ISSUE TITLE
Ontology is loaded, but ontology.getAxioms() returns 0 axioms, using version OWL API 5.1.3

### ISSUE THREAD

**Issue by karanthpallavi** [owlcs/owlapi#803]
Hi,
This is the code to load the ontology and after loading, using ontology.getAxioms returns no axioms,
May i know what is the issue?

OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
        // We load an ontology from the URI specified
        // on the command line
        File owlFile = new File(fileName);
        File folder = new File(folderName);
        AutoIRIMapper mapper=new AutoIRIMapper(folder, true);
        manager.addIRIMapper(mapper);
        
        OWLOntology ontology = manager.loadOntologyFromOntologyDocument(owlFile);
        
        // Report information about the ontology
        System.out.println("Ontology Loaded...");
        //System.out.println("Document IRI: " + documentIRI);
        System.out.println("Ontology : " + ontology.getOntologyID());
        System.out.println("Format      : " + manager.getOntologyFormat(ontology));
Set<OWLAxiom> axioms = ontology.getAxioms(Imports.INCLUDED);
        System.out.println(axioms);

**Comment by karanthpallavi** [comment]
[MovieOntologyPopularInferred.txt](https://github.com/owlcs/owlapi/files/2568205/MovieOntologyPopularInferred.txt)

**Comment by ignazio1977** [comment]
Loading the ontology straight from the file you attached works - I've got almost 1200 axioms.

You've set up an IRI mapper to look in a folder, is it possible the folder contains an older version of the ontology?

**Comment by karanthpallavi** [comment]
File exists in the same folder,
Also, stopped using IRI Mapper,
And used getAxiomCount() method,
Got 0..

**Comment by ignazio1977** [comment]
Ok, that's the culprit. The TriX parser often does not throw exceptions even if it cannot read any axioms, so if there is an exception in the proper parser, this parser will mask it and you end up with an empty ontology.

To exclude this parser, add these lines before loading the ontology:

        String name = "org.semanticweb.owlapi.rio.RioTrixParserFactory";
        manager.getOntologyConfigurator().withBannedParsers(name);
        OWLOntology ontology = manager.loadOntologyFromOntologyDocument(owlFile);

**Comment by ignazio1977** [comment]
After the list of parsers there should be a list of specific stack traces, one for each parser. What do they say?

**Comment by ignazio1977** [comment]
Specifically, the OWL/XML parser should give you the actual error.

**Comment by karanthpallavi** [comment]
Parser: org.semanticweb.owlapi.owlxml.parser.OWLXMLParser@35293c05
    Stack trace:
java.lang.IllegalStateException: value cannot be null at this stage        org.semanticweb.owlapi.owlxml.parser.OWLXMLParser.parse(OWLXMLParser.java:61)
        uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:192)
        uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.load(OWLOntologyManagerImpl.java:1070)
        uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1032)
        uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:982)
        uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:995)
        com.mycompany.semanticdistance.SemanticDistance.loadOntology(SemanticDistance.java:127)
        com.mycompany.semanticdistance.SemanticDistance.main(SemanticDistance.java:101)
value cannot be null at this stage        org.semanticweb.owlapi.util.OWLAPIPreconditions.verifyNotNull(OWLAPIPreconditions.java:56)
        org.semanticweb.owlapi.util.OWLAPIPreconditions.verifyNotNull(OWLAPIPreconditions.java:40)
        org.semanticweb.owlapitools.builders.BaseSubBuilder.getSub(BaseSubBuilder.java:73)
        org.semanticweb.owlapi.owlxml.parser.SubClassEH.handleChild(PARSER_OWLXMLVocabulary.java:1683)
        org.semanticweb.owlapi.owlxml.parser.OWLEH$HandleChild.lambda$static$1(PARSER_OWLXMLVocabulary.java:620)
        org.semanticweb.owlapi.owlxml.parser.OWLEH$HandleChild.run(PARSER_OWLXMLVocabulary.java:645)
        org.semanticweb.owlapi.owlxml.parser.OWLEH.endElement(PARSER_OWLXMLVocabulary.java:615)
        org.semanticweb.owlapi.owlxml.parser.OWLXMLPH.endElement(OWLXMLPH.java:513)
        com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
        com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:183)

Have tried with several ontologies,
Am stuck,
Kindly help

**Comment by karanthpallavi** [comment]
Ontologies generated by OWL API have been used as input, 
Had earlier run this application successfully with OWL API generated ontologies,
Not sure why any of the parsers cant parse the ontologies now,
Would be grateful if it can be resolved,
The stack trace from other parser says:
Parser: org.semanticweb.owlapi.krss2.parser.KRSS2OWLParser@189b5fb1
    Stack trace:
org.semanticweb.owlapi.krss2.parser.ParseException: Encountered unexpected token: "<Ontology xmlns=\"http://www.w3.org/2002/07/owl#\"\n     xml:base=\"http://www.semanticweb.org/drkm/ontologies/2018/5/untitled-ontology-42\"\n     xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n     xmlns:xml=\"http://www.w3.org/XML/1998/namespace\"\n     xmlns:xsd=\"http://www.w3.org/2001/XMLSchema#\"\n     xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n     ontologyIRI=\"http://www.semanticweb.org/drkm/ontologies/2018/5/untitled-ontology-42\">" ">"
    at line 1, column 1.

Was expecting:

    <EOF>
        org.semanticweb.owlapi.krss2.parser.KRSS2OWLParser.parse(KRSS2OWLParser.java:248)
        uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:192)
        uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.load(OWLOntologyManagerImpl.java:1070)
        uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1032)
        uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:982)
        uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:995)
        com.mycompany.semanticdistance.SemanticDistance.loadOntology(SemanticDistance.java:127)
        com.mycompany.semanticdistance.SemanticDistance.main(SemanticDistance.java:101)
Encountered unexpected token: "<Ontology xmlns=\"http://www.w3.org/2002/07/owl#\"\n     xml:base=\"http://www.semanticweb.org/drkm/ontologies/2018/5/untitled-ontology-42\"\n     xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n     xmlns:xml=\"http://www.w3.org/XML/1998/namespace\"\n     xmlns:xsd=\"http://www.w3.org/2001/XMLSchema#\"\n     xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n     ontologyIRI=\"http://www.semanticweb.org/drkm/ontologies/2018/5/untitled-ontology-42\">" ">"
    at line 1, column 1.

Was expecting:

    <EOF>
        org.semanticweb.owlapi.krss2.parser.KRSS2Parser.generateParseException(KRSS2Parser.java:2103)
        org.semanticweb.owlapi.krss2.parser.KRSS2Parser.jj_consume_token(KRSS2Parser.java:1968)
        org.semanticweb.owlapi.krss2.parser.KRSS2Parser.parse(KRSS2Parser.java:124)
        org.semanticweb.owlapi.krss2.parser.KRSS2OWLParser.parse(KRSS2OWLParser.java:245)
        uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:192)
        uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.load(OWLOntologyManagerImpl.java:1070)
        uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1032)
        uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:982)
        uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:995)
        com.mycompany.semanticdistance.SemanticDistance.loadOntology(SemanticDistance.java:127)

**Comment by ignazio1977** [comment]
I'm having troubles replicating the issue. I've tried 5.1.3 and 5.1.7, and both versions work fine with your input.

Comparing the stack trace to the code for 5.1.3., there is a mismatch. Line 

`org.semanticweb.owlapitools.builders.BaseSubBuilder.getSub(BaseSubBuilder.java:73)`

does not match executable code in 5.1.3 or 5.1.7. this might mean there's another OWLAPI version in the classpath of your application, and that's causing an old bug to be triggered. 

In particular, this like appears to have been modified to avoid the exception you're seeing in OWLAPI 5.0.2, so I suspect you might have a 5.0.0 or 5.0.1 OWLAPI version conflicting with 5.1.3 in your application.

**Comment by karanthpallavi** [comment]
Thanks for pointing out this,
Had owlapi-fixers version 5.0.1 which was a conflict,
Now, owl api version 5.1.3 works well and my application runs!
Thanks a lot for all the support.
