### ISSUE TITLE
Wrong Classloader Used in Injector.java for OSGi

### ISSUE THREAD

**Issue by skahmann** [owlcs/owlapi#805]
I wrote up this whole post about how in our OSGi setup the ContextClassLoader we are sending to `Injector.java` is actually not null, but it also is not the correct ClassLoader for OWLAPI implementations. I spent some time researching workarounds, then I pulled the latest version5 (which coincidently is also 5.1.7 which confused me for a while) and saw the issue was fixed by searching both the provided ClassLoader and the OWLAPI ClassLoader.

So after a few days of working this, I only need to know when 5.1.8 will be released. If it's not for a while then we either can't upgrade or will have to host our own version of 5.1.7. Any updates on that? :)

Thanks
Stephen

**Comment by ignazio1977** [comment]
There are a couple more issues that need fixing before 5.1.8 can be released, a week should be enough.

**Comment by skahmann** [comment]
Excellent! Thank you for the quick response.

**Comment by ignazio1977** [comment]
5.1.8  released yesterday evening.
