### ISSUE TITLE
help appreciated - loading an ontology

### ISSUE THREAD

**Issue by ianhyland** [owlcs/owlapi#807]
Hi all,

I'm just starting on the OWL API tutorial (Nicolas and Ignazio 2016). I can create an Ontology but get stuck when trying to load from file or IRI - both fail at:

      Exception in thread "main" java.lang.NullPointerException
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology
(OWLOntologyFactoryImpl.java:184)

I've copied the java code (it complies fine) and console output - HELP APPRECIATED !!

package msc;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;

import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.OWLOntology;
import org.semanticweb.owlapi.model.OWLOntologyCreationException;
import org.semanticweb.owlapi.model.OWLOntologyManager;

public class xxload {

	public static void main(String[] args) throws OWLOntologyCreationException, IOException { 
		 
		OWLOntologyManager man = OWLManager.createOWLOntologyManager();

		File file = new File("C:\\Users\\ianhy\\Documents\\pizza.owl.xml");
		System.out.println("file = " + file);

		BufferedReader in = new BufferedReader(new FileReader(file));
		String line = in.readLine();
		while(line != null)
		{
		  System.out.println(line);
		  line = in.readLine();
		}
		in.close();
		
		try { 
			OWLOntology o = man.loadOntologyFromOntologyDocument(file); 
			System.out.println(o); 
			} catch (OWLOntologyCreationException e) { 
				e.printStackTrace(); 
			}  
	 }	
}

……. f:RDF>

Exception in thread "main" java.lang.NullPointerException
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:184)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.load(OWLOntologyManagerImpl.java:1071)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1033)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:983)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:996)
	at msc.xxload.main(xxload.java:32)

================================================

package msc;

import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;
import org.semanticweb.owlapi.model.OWLOntologyCreationException;
import org.semanticweb.owlapi.model.OWLOntologyManager;

public class xxloadIRI {
	
	public static void main(String[] args) throws OWLOntologyCreationException { 
		 
		OWLOntologyManager man = OWLManager.createOWLOntologyManager();
		
		IRI pizzaontology = IRI.create("http://protege.stanford.edu/ontologies/pizza/pizza.owl");
		
		System.out.println("IRI = " + pizzaontology);
		
		try { 
			OWLOntology o = man.loadOntology(pizzaontology); 
			System.out.println(o); 
			} catch (OWLOntologyCreationException e) { 
				e.printStackTrace(); 
			} 
	 }	
}

….. iption rdf:about="http://www.co-ode.org/ontologies/pizza/pizza.owl#Italy"/>
</owl:distinctMembers>
</rdf:Description>
</rdf:RDF>

Exception in thread "main" java.lang.NullPointerException
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:184)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.load(OWLOntologyManagerImpl.java:1071)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1033)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:983)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:996)
	at msc.xxload.main(xxload.java:32)

**Comment by ignazio1977** [comment]
Which OWLAPI version are you using? I need to match line 184 to the actual code running.

**Comment by ignazio1977** [comment]
I've tried replicating this but `xxloadIRI` works fine for me. Is the pizza.owl file in your first example the same pizza.owl file available online?

**Comment by ianhyland** [comment]
Hi Ignazio,

 

I just copied pizza.owl from http://protege.stanford.edu/ontologies/pizza/pizza.owl to a local file pizza2.owl (attached). The file and the URI both load successfully into Protégé. 

 

Both (xxload.java and xxloadIRI.java) generate the same java:184 exception in Eclipse:

 

Exception in thread "main" java.lang.NullPointerException

       at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:184)

 

My code for xxload.java prints out the pizza2.owl file so hopefully the path is set correctly.

 

Any ideas appreciated …………….

 

I’ll try with different source OWL files.

 

 

Best regards,

 

Ian. 

======================================================================================

Ian Hyland                                  Email: ianhyland@ngensys.com <mailto:ianhyland@ngensys.com>                                       Tel: +44 7816 671 524

======================================================================================

**Comment by ignazio1977** [comment]
Same result - I've downloaded the file and done the load locally, no errors.

It shouldn't be possible for a null pointer exception to be raised on that line - all the variables in use have been used before, so if any of them was null the exception would have been thrown earlier.

One possibility to investigate is a corrupted jar file. Try deleting the OWLAPI files (owlapi-distribution, owlapi-impl, and so on) from your local maven repository. They will be downloaded again on the next build.

**Comment by ianhyland** [comment]
Thanks again Ignazio

 

Per your advice I downloaded the files again and now both load from file and load from IRI work

 

Strange that the corruption wasn’t flagged by the JVM ??

 

 

 

Best regards,

 

Ian. 

======================================================================================

Ian Hyland                                  Email: ianhyland@ngensys.com <mailto:ianhyland@ngensys.com>                                       Tel: +44 7816 671 524

======================================================================================

**Comment by ignazio1977** [comment]
Indeed. Possibly the corruption was not detectable - i.e., some of the data entries might have been completely missing.
