### ISSUE TITLE
OBO writer doesn't distinguish allValuesFrom and someValuesFrom

### ISSUE THREAD

**Issue by balhoff** [owlcs/owlapi#808]
Given this functional syntax ontology:

```
Prefix(:=<http://purl.obolibrary.org/obo/uni.obo#>)

Ontology(<http://purl.obolibrary.org/obo/uni.obo>

Declaration(Class(:A))
Declaration(Class(:B))
Declaration(ObjectProperty(:part_of))

SubClassOf(:A ObjectAllValuesFrom(:part_of :B))
)
```

if you save to OBO format the output will be:

```
format-version: 1.2
ontology: uni.obo

[Term]
id: A
relationship: part_of B
```

When you load that OBO file it will be interpreted as:

```
SubClassOf(:A ObjectSomeValuesFrom(:part_of :B))
```

The OBO format is supposed to add a qualifier on allValuesFrom relationships (http://owlcollab.github.io/oboformat/doc/obo-syntax.html). I don't know whether that part of the spec is intended to be supported in the OWL API OBO format or not.

cc @cmungall

**Comment by cmungall** [comment]
Sorry meant to include a WIP note on the PR, my PR was untested, was being lazy and expecting travis.. I can take care of testing but may be a while..

**Comment by ignazio1977** [comment]
No worries, should be straightforward to test
