### ISSUE TITLE
RDFGraph getSubjectsForObjects caught in infinite loop

### ISSUE THREAD

**Issue by daltontc** [owlcs/owlapi#809]
I have an ontology called `OntologyA` that has an import of `VersionIsItself`. `VersionIsItself` designates its version as itself. When I try to render `OntologyA` using `RioRenderer`, the `RDFGraph` method `getSubjectsForObjects` gets caught in an infinite loop. Attached is a copy of `VersionIsItself` for reference.

Is there a way to get around this issue? Perhaps some property to set? As of right now it is breaking issue for me.

[VersionIsItself.ttl.txt](https://github.com/owlcs/owlapi/files/2668723/VersionIsItself.ttl.txt)

**Comment by ignazio1977** [comment]
There's no property to change this behaviour. I'll fix the bug and do a new release.

**Comment by ignazio1977** [comment]
Which version are you using, so I can prioritise which version to release?

**Comment by daltontc** [comment]
5.1.8

**Comment by daltontc** [comment]
When could I expect a release with the fix?

**Comment by ignazio1977** [comment]
I've released 5.1.9 this morning, it's on maven central now.

**Comment by daltontc** [comment]
[ro.owl.txt](https://github.com/owlcs/owlapi/files/2672601/ro.owl.txt)

The Relation Ontology is now failing parsing as an InputStream with a format of `RDFFormat.RDF/XML` in `Rio.parse()`
