### ISSUE TITLE
DLExpressivity checker never computes anything

### ISSUE THREAD

**Issue by matthewhorridge** [owlcs/owlapi#810]
OWL API Version 4.5.7

I'm trying to use the DLExpressivityChecker and I'm finding that it never computes anything.  As far as I can tell from browsing the code, computation should be done in the ```getOrderedConstructs``` method if the ```constructs``` set is ```null```.  However, it is never ```null``` – see the one and only constructor:

```java
public DLExpressivityChecker(Set<OWLOntology> ontologies) {
        this.ontologies = new ArrayList<>(ontologies);
        constructs = new HashSet<>();
}
```
It isn't set to ```null``` anywhere either.

There's an interesting line in this test, which, as far as I can tell is always true, so the test returns and doesn't really do anything:

https://github.com/owlcs/owlapi/blob/b5d32541cf8a9566e3d68d160d922d2514aa2903/contract/src/test/java/org/semanticweb/owlapi/api/test/DLExpressivityCheckerTestCase.java#L489

**Comment by ignazio1977** [comment]
Must be due to me doing all the development in the master branch and cherry picking the fix. The classes in the other branches are not in the same folders, so there were tweaks needed, and I must have missed a line.

**Comment by ignazio1977** [comment]
How urgently do you need this fix, Matt? Wondering if I should release right away or look at any other fix to be included first.

**Comment by matthewhorridge** [comment]
I don't really need it urgently... I'm sure you can spend your Christmas hols doing better things :)

**Comment by ignazio1977** [comment]
4.5.8 released
