### ISSUE TITLE
OWLOntology loadImports

### ISSUE THREAD

**Issue by rkahmann** [owlcs/owlapi#811]
I have an ontology that I want to load that has an invalid import. Below is an example file of something I’d be looking to parse. The error I am getting in this example is `<random:test>` - "Could not find an appropriate factory to load ontology from ontology document”. I would expect that this import would be marked as a failed import rather than failing  the load of the ontology. I have traced the issue back to “OWLOntologyManagerImpl.loadOntology” on line 1062 where it throws a “OWLOntologyFactoryNotFoundException”. I would expect that this exception would be caught on line 1638 in “loadImports” and the import marked as failed, but isn’t. Is this the expected behavior? If I want invalid import IRIs to be marked as failed, how would I do that?

'
@prefix : <http://random.org/ontologies/uhtc#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@base <http://random.org/ontologies/uhtc> .

<http://random.org/ontologies/uhtc> rdf:type owl:Ontology ;

				     owl:imports <random:test> .
'

**Comment by ignazio1977** [comment]
You can use `ConfigurationOptions.MISSING_IMPORT_HANDLING_STRATEGY` to set the manager to throw exceptions on invalid imports.

    OWLOntologyLoaderConfiguration config = new OWLOntologyLoaderConfiguration().setMissingImportHandlingStrategy(MissingImportHandlingStrategy.SILENT);

Then use the `config` object in the loading calls.

Alternatively, you can set an environment variable or create an `owlapi.properties` file (ensuring it's in the classpath) containing:

    org.semanticweb.owlapi.model.parameters.ConfigurationOptions.MISSING_IMPORT_HANDLING_STRATEGY=SILENT
