### ISSUE TITLE
OWL API 4 HasAnnotationValue throws NullpointerException

### ISSUE THREAD

**Issue by mrnolte** [owlcs/owlapi#814]
Hey there,
for OWL API 4, `HasAnnotationValue.literalValue()` throws a `NullpointerException` instead of returning an empty `Optional` when no annotation value is present. From looking into the code, `iriValue()` and `anonymousIndividualValue()` contain the same bug. The problem could easiliy be solved by adapting the OWL API 5 code for those methods.
Cheers,
Robin

**Comment by ignazio1977** [comment]
That code is cumbersome because it converts a Guava optional into a `java.util.Optional`, however looking at the implementation I cannot figure out in which scenario annotation values would be absent.

It's possible that the annotation value is not a literal but an IRI/anonymous individual, but that should not cause a null pointer exception, it should just produce an empty optional. Do yu have a stack trace I can look at?

**Comment by mrnolte** [comment]
Due to the code being property of the DFKI, i cannot show you the full stacktrace. Here is a snippet:
```
java.lang.NullPointerException: use Optional.orNull() instead of Optional.or(null)
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:895)
	at com.google.common.base.Present.or(Present.java:45)
	at org.semanticweb.owlapi.model.HasAnnotationValue.literalValue(HasAnnotationValue.java:30)
```
Since version 21, Guava supports the methods `toJavaUtil` and `fromJavaUtil`. Maybe switsching to them could help?

**Comment by mrnolte** [comment]
As the error message already suggests, you cannot pass `null` to the method. For this reason every `OWLAnnotation` throws this error every time the method `literalValue()` is called. This can easily be checked by the following code, which throws the same `NullPointerException`:
`com.google.common.base.Optional.of(1).or((Integer) null);`

**Comment by mrnolte** [comment]
I just saw that this error might be due to us using Guava 27 and not 18, which the owl api 4 uses. Apparently it was only in a later version that it was forbidden to pass `null`.

**Comment by mrnolte** [comment]
I guess upgrading to a later version might bring up new bugs, but since Guava 18 contains the method `orNull,` too, using that instead of `.or(null)` might solve my issue.

**Comment by ignazio1977** [comment]
> I just saw that this error might be due to us using Guava 27 and not 18, which the owl api 4 uses. Apparently it was only in a later version that it was forbidden to pass null.

That's the only explanation I can find. That method does not fail during OWLAPI build tests, which use the methods involved. Yes, amending the call is a good fix.

**Comment by mrnolte** [comment]
Thanks for your fast reply & fix, much appreciated!
