### ISSUE TITLE
Parsing DBXrefs that have trailing modifiers fails

### ISSUE THREAD

**Issue by matthewhorridge** [owlcs/owlapi#820]
It seems that parsing DBXref definitions that have trailing modified fails.  Here's what the OBO spec says about [DBXRefs](https://owlcollab.github.io/oboformat/doc/GO.format.obo-1_4.html#S.2.2.3) (A key point is the last paragraph:

> Dbxref Formatting
> 
> Dbxref definitions take the following form:
> 
> <dbxref name> {optional-trailing-modifier}
> 
> or
> 
> <dbxref name> "<dbxref description>" {optional-trailing-modifier}
> 
> The dbxref is a colon separated key-value pair. The key should be taken from GO.xrf_abbs but this is not a requirement. If provided, the dbxref description is a string of zero or more characters describing the dbxref. DBXref descriptions are rarely used and as of obof1.4 are discouraged.
> 
> Dbxref lists are used when a tag value must contain several dbxrefs. Dbxref lists take the following form:
> 
> [<dbxref definition>, <dbxref definition>, ...]
> 
> The brackets may contain zero or more comma separated dbxref definitions. An example of a dbxref list can be seen in the GO def for "ribonuclease MRP complex":
> 
> def: "A ribonucleoprotein complex that contains an RNA molecule of the snoRNA family, and cleaves the rRNA precursor as part of rRNA transcript processing. It also has other roles: In S. cerevisiae it is involved in cell cycle-regulated degradation of daughter cell-specific mRNAs, while in mammalian cells it also enters the mitochondria and processes RNAs to create RNA primers for DNA replication." [GOC:sgd_curators, PMID:10690410, PMID:14729943, PMID:7510714]
> 
> Note that the trailing modifiers (like all trailing modifiers) do not need to be decoded or round-tripped by parsers; trailing modifiers can always be optionally ignored. However, all parsers must be able to gracefully ignore trailing modifiers. It is important to recognize that lines which accept a dbxref list may have a trailing modifier for each dbxref in the list, and another trailing modifier for the line itself.
> 

The OBO parser in the OWL API cannot parse XRefs that have optional trailing modifiers.

I've lost track of the status of the OWL API parser.  Is this the "official" OBO 1.4 Format parser that was part of OWL Tools? @cmungall do you know and do you know whether the above is a bug/know problem?

**Comment by ignazio1977** [comment]
> Is this the "official" OBO 1.4 Format parser that was part of OWL Tools?

Yes it is, the code was transplanted a few years ago.

**Comment by matthewhorridge** [comment]
Thanks for the clarification @ignazio1977. And the writer?

**Comment by cmungall** [comment]
I am to blame..

I think this just a bug in the obo format 1.4 guide. The spec is canonical: http://owlcollab.github.io/oboformat/doc/obo-syntax.html

(historically we always had "guides" for obo format but these have always been fuzzy and ambiguous; in theory they were friendlier to non-CS people, but bioinformaticians always implemented parsers by trial and error anyway, ignoring any docs)

I use trailing qualifiers / axiom annotations all the time and don't think there is any issue with the current implementation

**Comment by matthewhorridge** [comment]
@cmungall thanks a lot for the clarification.  Much appreciated. .... and not trying to blame anyone :)

The problem that I was seeing was due to trailing qualifiers on xrefs (inside xref lists)... as you say, buggy guide.  The spec is clear that they cannot occur here.

Thanks a lot for the input @cmungall and @ignazio1977

**Comment by matthewhorridge** [comment]
Closing this issue because it's not actually a bug
