### ISSUE TITLE
Unescaping characters: OBOFormatParser#handleNextChar()

### ISSUE THREAD

**Issue by floschmedding** [owlcs/owlapi#822]
Shouldn't there rather be a tab character ('\t') appended?

https://github.com/owlcs/owlapi/blob/1947fe9e23e1ab261090dad919d102686238cd75/oboformat/src/main/java/org/obolibrary/oboformat/parser/OBOFormatParser.java#L1324-L1325

**Comment by ignazio1977** [comment]
Good catch.
