### ISSUE TITLE
Array as Data Property 

### ISSUE THREAD

**Issue by thomakl** [owlcs/owlapi#823]
Hi, 
It's not a issue. More about a general **question**.
I would like to store a trajectory (list of coordinates) to a specific individual as a DataProperty.
I checked the data type available but it doesn't seem to have `Array` or `List`.

My last resort is to store it as a String and then convert it.

Any idea ?

**Comment by ignazio1977** [comment]
Hi, there's no support for lists as values of data properties. The simplest solution is probably to design a serialization format and turn the list into a string (XML is a supported type, if that helps); another possibility, if the length of the list has a maximum, is to have a few data properties P1..Pn and use them to link the individual coordinates.

**Comment by thomakl** [comment]
Thank you for your answer.
I'll go for one of your way.
