### ISSUE TITLE
Question - Individuals with specific Data Property

### ISSUE THREAD

**Issue by thomakl** [owlcs/owlapi#826]
Hi,

I would like to get a list of all the individuals that have a specific Data Property (and then get its value).
Is it faster to use a reasoner and check who (an individual) is linked with this such Data Property ?

I found this method on the example script but it doesn't seem to fit what I'm looking for : 
`private static boolean hasProperty(@Nonnull OWLOntologyManager man, @Nonnull OWLReasoner reasoner, OWLClass cls,
@Nonnull OWLObjectPropertyExpression prop)`

Thank you for your time,

**Comment by ignazio1977** [comment]
`EntitySearcher::getDataPropertyValues()` will provide the values, to get the individuals from an ontology to use in this method, use `OWLOntology::individualsInSignature()`.

Using a reasoner is almost certainly slower, however a reasoner provides complete answers - i.e., if there are inferences to be made to provide all answers, only a reasoner will be able to provide them.

**Comment by thomakl** [comment]
Thank you for your quick answer.
I made it work without the reasoner.

Now I would like to learn how to do it via a reasoner. I can't find it clearly on the wiki of the project.
I am also very confused with the `OWLClassExpression` type.

What documentation do you recommend to going through rules and reasoner with OWL-API ?
