### ISSUE TITLE
RBOX/TBOX distinctions in AxiomType

### ISSUE THREAD

**Issue by matentzn** [owlcs/owlapi#827]
Hey @ignazio1977, @matthewhorridge 
I am wondering: why are the various functional property characteristics (such as  INVERSE_FUNCTIONAL_OBJECT_PROPERTY and FUNCTIONAL_DATA_PROPERTY) in AxiomType.TBoxAxiomTypes rather than Rbox? I would have the same question about domain and range axioms, but there maybe I can see it easier (classes in signature).

**Comment by ignazio1977** [comment]
Issue #473 was referring the same topic. Main problem is that there does not seem to be one agreed upon partition of axioms between tbox and rbox. Owlapi does not really care - it's more of an application distinction.

**Comment by matentzn** [comment]
Yeah, to be honest I abused the OWL API tracker a bit to answer the question of what the partition should be. Thanks @ignazio1977 , its out there now. Maybe @matthewhorridge has an opinion, as  I also not care, other than that it should be a somewhat plausible 'standard' partition. Maybe someone else did it somewhere.

**Comment by matthewhorridge** [comment]
Hi @matentzn ,

I can't remember that far back :) But, anyway, if you think of ```FunctionalObjectProperty(:q)``` as syntactic sugar for ```SubClassOf(owl:Thing ObjectMaxCardinality(1 :q owl:Thing))``` (i.e. __everything__ has at most one ```:q``` successor) then you can see it as syntactic sugar for a TBox axiom.  Same with inverse functional etc.  Domain and Range re the same too e.g. ```ObjectPropertyDomain(:q :C)``` is syntactic sugar for ```SubClassOf(ObjectSomeValuesFrom(:q owl:Thing) :C)``` etc. etc.

**Comment by matentzn** [comment]
Good enough for me! Thanks @matthewhorridge
