### ISSUE TITLE
Missing escape character in OBO output?

### ISSUE THREAD

**Issue by rctauber** [owlcs/owlapi#828]
Our input OBO file includes a name that has:
`\{[iminio(methylamino)methyl]amino\}`

We would expect to maintain the escape character before the closing bracket.

Instead, the output OBO file contains:
`\{[iminio(methylamino)methyl]amino}`

Does this have something to do with [escapeOboString](https://github.com/owlcs/owlapi/blob/9039c8cb3469fa6323c1fe22c6222a47e715e400/oboformat/src/main/java/org/obolibrary/oboformat/writer/OBOFormatWriter.java#L435)? It looks like escape characters are appended to the opening brackets, but not the closing brackets. I'm not super familiar with OBO format, so I'm not sure if this is standard, but one of our ROBOT users is concerned by the missing escape character.

See https://github.com/ontodev/robot/issues/201

**Comment by ignazio1977** [comment]
`escapeOboString` seems to escape the opening brace and the closing bracket, but not the opening bracket or the closing brace. I would think the intent was to escape both opening and closing ones.

**Comment by ignazio1977** [comment]
The code in version 4 includes this comment:

            // removed for compatibility with OBO-Edit
            // else if (c == '}' && (mode == EscapeMode.most || mode ==
            // EscapeMode.parenthesis)) {
            // modfied = true;
            // sb.append("\\}");
            // }


So at the time the code was included in OWLAPI, this was intentional. Not sure whether this comment still applies. @cmungall do you happen to know?

**Comment by cmungall** [comment]
cc @althonos

**Comment by althonos** [comment]
As far as the syntax goes:
* `[` needs to be escaped at the beginning of Synonym IDs (otherwise you get owlcollab/oboformat#97)
* `]` needs to be escaped in Xrefs IDs (otherwise parsers dont know when the ID stops if there is no trailing definition)
* `{` and `}` probably do not need to be escaped, but I could be wrong

Since this can get somewhat confusing I'd be in favour of escaping everything (`[]{}`) though.
