### ISSUE TITLE
5.1.10 Regression in OwlStringTools#translate(..)

### ISSUE THREAD

**Issue by sszuev** [owlcs/owlapi#829]
commit: https://github.com/owlcs/owlapi/commit/20f70a1134d14c51cf505d04f536595a11ad08a9

- **1)**  **5.1.9**
The following code works fine in 5.1.9:

```
import org.obolibrary.obo2owl.OwlStringTools;
import org.semanticweb.owlapi.model.OWLAxiom;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLOntology;
import org.semanticweb.owlapi.model.OWLOntologyManager;
import uk.ac.manchester.cs.owl.owlapi.OWLDataFactoryImpl;
import uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl;
import uk.ac.manchester.cs.owl.owlapi.OWLOntologyImpl;
import uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl;
import uk.ac.manchester.cs.owl.owlapi.concurrent.NoOpReadWriteLock;

import java.util.Collections;

public class Test_OwlStringTools {

    public static void main(String... args) {
        OWLOntologyManager m = new OWLOntologyManagerImpl(new OWLDataFactoryImpl(), new NoOpReadWriteLock());
        m.setOntologyFactories(Collections.singleton(new OWLOntologyFactoryImpl(OWLOntologyImpl::new)));
        OWLDataFactory df = m.getOWLDataFactory();
        OWLAxiom a = df.getOWLDeclarationAxiom(df.getOWLClass("X"));
        String res = OwlStringTools.translate(Collections.singleton(a), m);
        System.out.println("------------------");
        System.out.println(res);
        System.out.println(m.ontologies().count());
        OWLOntology o = m.ontologies().findFirst().orElseThrow(AssertionError::new);
        if (o.getOWLOntologyManager() != m) {
            throw new AssertionError();
        }
    }
}

```

Here the project's dependencies:
```
    <dependencies>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>1.7.26</version>
        </dependency>
        <dependency>
            <groupId>net.sourceforge.owlapi</groupId>
            <artifactId>owlapi-impl</artifactId>
            <version>${version.owlapi}</version>
        </dependency>
        <dependency>
            <groupId>net.sourceforge.owlapi</groupId>
            <artifactId>owlapi-oboformat</artifactId>
            <version>${version.owlapi}</version>
        </dependency>
    </dependencies>
```

- **2)** **5.1.10**
The code above leads to `AssertionError` (manager does not contain any ontologies)
And also there is an error in logs (although it is not thrown):

```
...

[DEBUG][Injector] 11:29:54.147 No files found for META-INF/services/org.semanticweb.owlapi.model.OWLOntologyBuilder
[ERROR][Injector] 11:29:54.147 No instantiation found for org.semanticweb.owlapi.model.OWLOntologyBuilder arg0
[ERROR][Injector] 11:29:54.147 Instantiation failed
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.semanticweb.owlapi.utilities.Injector.instantiate(Injector.java:363)
	at org.semanticweb.owlapi.utilities.Injector.lambda$load$6(Injector.java:304)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.semanticweb.owlapi.utilities.Injector.inject(Injector.java:206)
	at org.obolibrary.obo2owl.OwlStringTools.translate(OwlStringTools.java:60)
	at ts.owlapiv5.Test_OwlStringTools.main(Test_OwlStringTools.java:26)
Caused by: java.lang.IllegalStateException: value cannot be null at this stage
	at org.semanticweb.owlapi.util.OWLAPIPreconditions.verifyNotNull(OWLAPIPreconditions.java:56)
	at org.semanticweb.owlapi.util.OWLAPIPreconditions.verifyNotNull(OWLAPIPreconditions.java:40)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.<init>(OWLOntologyFactoryImpl.java:65)
	... 21 more
[DEBUG][Injector] 11:29:54.147 Injecting values [[null]] on method public void uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.setOntologyFactories(java.util.Set).
[DEBUG][Injector] 11:29:54.147 Loading file META-INF/services/org.semanticweb.owlapi.model.OWLOntologyIRIMapper
...

```

- **3)** The most important thing for me in the new `OwlStringTools#translate(..)` is that it passes the same factory from the input manager to the temporal manager.
Lines:

           Set<OWLOntologyFactory> set = new HashSet<>();
            translationManager.getOntologyFactories().forEach(set::add);
            m.setOntologyFactories(set);

I have different factories, which requires different OWLOntologyManager, which is not compatible with the default OWLOntologyManagerImpl.
This results another exception and inability to use owlapi-oboformat at all in my projects, 
while interaction with other parsers/storers is ok.

This situation can be roughly emulated by the following code (which works fine in 5.1.9):
```
        OWLOntologyManager manager = new OWLOntologyManagerImpl(new OWLDataFactoryImpl(), new NoOpReadWriteLock());
        manager.setOntologyFactories(Collections.singleton(new OWLOntologyFactoryImpl(OWLOntologyImpl::new) {
            @Override
            public OWLOntology loadOWLOntology(OWLOntologyManager m,
                                               OWLOntologyDocumentSource s,
                                               OWLOntologyCreationHandler h,
                                               OWLOntologyLoaderConfiguration c) {
                throw new AssertionError();
            }
        }));
        String txt = "Prefix(owl:=<http://www.w3.org/2002/07/owl#>)\n" +
                "Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>)\n" +
                "Prefix(xml:=<http://www.w3.org/XML/1998/namespace>)\n" +
                "Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>)\n" +
                "Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>)\n" +
                "Ontology(\n" +
                "Declaration(Class(<X>))\n" +
                ")";
        Collection<OWLAxiom> res = OwlStringTools.translate(txt, manager);
        System.out.println("------------------");
        System.out.println(res);
        System.out.println(manager.ontologies().count());
        OWLOntology o = manager.ontologies().findFirst().orElseThrow(AssertionError::new);
        if (o.getOWLOntologyManager() != manager) {
            throw new AssertionError();
        }
```

**Comment by ignazio1977** [comment]
> I have different factories, which requires different OWLOntologyManager, which is not compatible with the default OWLOntologyManagerImpl.

Can you explain a bit more about this?

The only purpose of a manager in OWLStringTools is to create ontologies for the storage of axioms that cannot be translated to OBO. These ontologies are temporary in intent - they only exist because the functional storer in these OWLAPI versions (4 and 5) does not accept just a set of axioms and requires an ontology to exist.

The manager should actually not be an argument, but created inside the class itself; however this required other changes, due to how OWLOntologyManager are constructed.

Allowing the temporary ontologies to be accessible outside of the storing process was never part of the design (I'd call it a bug, although this is not how the problem of using the same manager in both places). Can I ask what is the purpose you're using these ontologies for?

**Comment by sszuev** [comment]
The methods `OWLStringTools#translate(...)` are public.
Although they are only used internally by OWL-API-OBO itself, I found it useful to point out that their behavior has been changed. Since they are public, someone else may use them directly in their projects.

I don't use these methods directly and don't use any of the temporary ontologies that they create.
These methods are used indirectly by owlapi-oboformat, in the method `org.semanticweb.owlapi.oboformat.OBOFormatOWLAPIParser.parse(...)`.
owlapi-oboformat is used in test-scope of my project to ensure that everything is fine.



> Can you explain a bit more about this?

Moreover, I can point out a test-suite in the external project, that fails due to this issue.
But I'm not sure that this is necessary.
I could also give a full stacktrace, but it would not be very informative for you, since it mostly concerns external project.

In short: I can use any of the OWL-API parsers and storers in my project, 
despite the fact that the physical basis of my implementation is very different from OWL-API-impl.
And any other parsers and storers have been working fine.
The principle here is that the OWL-API parsers fold an ontology by axiom, 
although they just interact with interfaces, and physically a result ontology looks different.
And this principle has been working starting the first release with OWL-API 5.0.1 in dependencies.

I have my own `OWLOntologyFactory` implementation which requires specific manager and ontology implementations.
And everything works fine, as long as some internal mechanism does not try to use this factory directly, which happens in this method: 
a factory is just copied from the given manager (my) to the temporary manager (owl-api-impl).
This seems to be not correct, and can be easily fixed - instead of coping factory you can construct new one in the same way you do it for a temporary manager.

**Comment by ignazio1977** [comment]
I've backported the V6 solution, no ontologies are created during translation now, interface of the class is restored.
