### ISSUE TITLE
OWLDataPropertyAxiom not a subinterface of OWLPropertyAxiom?

### ISSUE THREAD

**Issue by Cydny** [owlcs/owlapi#831]
Is there a reason for "OWLDataPropertyAxiom" not being a subinterface of "OWLPropertyAxiom"?
All subinterfaces of "OWLDataPropertyAxiom" are indeed subinterfaces of "OWLPropertyAxiom".

**Comment by ignazio1977** [comment]
From what I can tell, it looks like it was missed in design (`OWLObjectPropertAxiom` does not have the same issue), but it hasn't caused issues because both interfaces are not defining any methods and are just markers.
