### ISSUE TITLE
Question: Vizualise Ontology in real time

### ISSUE THREAD

**Issue by thomakl** [owlcs/owlapi#835]
Hi,

Do you know a project / API I can use to **visualize** the nodes of my ontologies in real time (adding, deleting, modifying a class / property) ?
I know **OntoGraph** and **OWLViz** / **GraphViz** from Protégé ; however I don't think I can use them with my personal program **as an external library**.

Thank you for your time,

**Comment by ignazio1977** [comment]
I'm not aware of any specific library to do the job, but Protege is using both of them as external libraries, so it should be possible for you to do the same. Exploring Protege's source code would be my first choice.
