### ISSUE TITLE
MaximumNumberOfNamedSuperclasses uses equivalent classes instead of super classes

### ISSUE THREAD

**Issue by dschraudner** [owlcs/owlapi#836]
Is there a reason for MaximumNumberOfNamedSuperclasses using the [equivalent class expressions](https://github.com/owlcs/owlapi/blob/32facb667702040849523c1ca10fd8eda63694e6/tools/src/main/java/org/semanticweb/owlapi/metrics/MaximumNumberOfNamedSuperclasses.java#L53) instead of the super class expressions as the name suggests?

**Comment by ignazio1977** [comment]
It's a bug introduced in 2013 - a refactor with the wrong method.
