### ISSUE TITLE
Allow annotations to be skipped in module extraction

### ISSUE THREAD

**Issue by matentzn** [owlcs/owlapi#838]
Could one of you that is a bit more invested in the syntactic module extractor comment on this issue:

https://github.com/ontodev/robot/issues/456

I dont know whats right or wrong here, just want to get some perspective, maybe @matthewhorridge @ignazio1977 :P

**Comment by matthewhorridge** [comment]
Sorry for my tardy reply @matentzn.  Unfortunately, I can't be much help here.... I'm completely unfamiliar with this code.

**Comment by matentzn** [comment]
Don’t worry! I more wanted to know whether you think this behaviour is desirable or should be changed. I would look into it myself if you think the current behaviour sounds wrong.

**Comment by ignazio1977** [comment]
The `SKIP_MODULE_ANNOTATIONS` option can be used for this purpose

**Comment by matentzn** [comment]
That is really awesome! Thanks a ton!
