### ISSUE TITLE
OWLImmutableOntologyImpl.getGeneralClassAxioms exhibits slow behavior

### ISSUE THREAD

**Issue by matthewhorridge** [owlcs/owlapi#839]
As the subject says.  Open go-edit.owl in Protege to see the behavior - us the up and down arrow keys to rapidly change the selection and observe stuttering.

The ontology can be obtained from here:

https://github.com/geneontology/go-ontology/tree/master/src/ontology

JProfiler tells me the problem is OWLImmutableOntologyImpl.getGeneralClassAxioms

<img width="879" alt="image" src="https://user-images.githubusercontent.com/488607/56166721-2d808100-5f8b-11e9-9cfb-a03407756d68.png">

OWL API version is 4.5.9

**Comment by ignazio1977** [comment]
I would blame `OWLNaryClassAxiomImpl.compareObjectOfSameType` instead - comparison is checking a list (sorted at construction, duplicate free) against a set (which is a copy of an immutable, sorted at construction, duplicate free, list), and in doing so creating a TreeSet from the list and another TreeSet from the set. Pretty expensive, especially considering that accessing the two lists directly skips multiple set creations and sorting.

**Comment by matthewhorridge** [comment]
Sounds interesting.  The external facing method that exhibited the behavior is the getGeneralClassAxioms, so filed as such.

**Comment by ignazio1977** [comment]
Yes that's the first level at which bad performance accrues, there are a few smaller contributors wrapped in it, but the biggest gain is removing the unnecessary sorted sets. Caching the general axioms lookup should also help - at the moment the set is built every time, but it can be cached safely until changes are made.

**Comment by matthewhorridge** [comment]
Okay sounds good

**Comment by ignazio1977** [comment]
4.5.11 released
