### ISSUE TITLE
Multiple Ontology Definitions should obey strict parsing

### ISSUE THREAD

**Issue by daltontc** [owlcs/owlapi#840]
Using the RioParser,
```
RioParserImpl parser = new RioParserImpl(new RioRDFXMLDocumentFormatFactory());
parser.parse(new RioMemoryTripleSource(sesameModel), owlOntology, config);
```
I can create an OWLOntology object from a model that has multiple ontology definitions. It appears that OWLAPI grabs the first OntologyIRI and will use that. I would expect it to not allow multiple ontology definitions in the creation of an OWLOntology. 

If there are multiple VersionIRIs defined for a single OntologyIRI, I would expect the creation to fail. Whereas, now it appears to grab the first VersionIRI and uses that in the OWLOntologyID.

Lastly, a concern I have is that if this behavior is for some reason expected, when the following is loaded,
```
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

<http://www.mobi.com/test/OntologyOneWithVersion> rdf:type owl:Ontology ;
  rdfs:label "Two ontologies each with versions."^^xsd:string ;
  rdfs:comment "This file has two ontologies each with versions."^^xsd:string .

<http://www.mobi.com/test/OntologyTwoWithVersion> rdf:type owl:Ontology ;
  owl:versionIRI <http://www.mobi.com/test/OntologyTwoWithVersionVersion1> .

<http://www.mobi.com/test/OntologyOneWithVersion> owl:versionIRI <http://www.mobi.com/test/OntologyOneWithVersionVersion1> .
```

The end result is an OWLOntologyID with `http://www.mobi.com/test/OntologyOneWithVersion` as the OntologyIRI and `http://www.mobi.com/test/OntologyTwoWithVersionVersion1` as the VersionIRI. This definitely shouldn't happen since the version is associated with a completely different ontology definition.

**Comment by ignazio1977** [comment]
Multiple ontology declarations shouldn't be allowed, however OWLAPI has allowed that for a long time, so undoing it raises a number of questions about behaviour change. It should be controlled by strict configuration - i.e., an exception should be thrown if parsing is set to strict mode, however that's not currently the case.

The version defect is a consequence of the assumption that there is only one ontology declaration per file. With multiple ones, which annotation is used depends on which one is parsed first. Clearly that needs fixing too.

**Comment by ignazio1977** [comment]
For the record, this is not Rio parser specific. The defect is common to all RDF based syntaxes.

**Comment by ignazio1977** [comment]
To throw an exception parsing these ontologies, set the configuration to strict mode (available on the `config` variable in your code). The version will be associated correctly.

(In the next release, I mean)
