### ISSUE TITLE
Axiom count differs for ontology depending on method of program execution

### ISSUE THREAD

**Issue by jvendetti** [owlcs/owlapi#842]
Hi @ignazio1977. I'm using version 4.5.11 and have run into an issue with a particular ontology where the axiom count differs depending on the method of program execution.

Executing the following code from an IDE:

```
File file = new File("src/main/resources/NEO.owl");
FileDocumentSource fileDocumentSource = new FileDocumentSource(file);
OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
OWLOntologyLoaderConfiguration conf = new OWLOntologyLoaderConfiguration();
conf = conf.setMissingImportHandlingStrategy(MissingImportHandlingStrategy.THROW_EXCEPTION);
try {
    OWLOntology ontology = manager.loadOntologyFromOntologyDocument(fileDocumentSource, conf);
    LOG.info("NEO axiom count: {}", ontology.getAxiomCount());
    LOG.info("NEO ontology ID: {}", ontology.getOntologyID());
    LOG.info("NEO ontology format: {}", manager.getOntologyFormat(ontology));
} catch (OWLOntologyCreationException e) {
    e.printStackTrace();
}
```

Results in the following output, indicating a total of 3303 axioms:

```
[main] INFO org.stanford.bmir.bioportal.LoadNEO - NEO axiom count: 3303
[main] INFO org.stanford.bmir.bioportal.LoadNEO - NEO ontology ID: OntologyID(OntologyIRI(<http://webprotege.stanford.edu/project/BbHRvdgdu3Y4vbyVxXTwfu>) VersionIRI(<null>))
[main] INFO org.stanford.bmir.bioportal.LoadNEO - NEO ontology format: RDF/XML
```

However, if I JAR up that code and execute the Java program from the command line, e.g., `java -jar target/owlapi-neo-ont-1.0-SNAPSHOT-jar-with-dependencies.jar`, the resulting output is different (zero axioms, different ontology format):

```
[main] INFO org.stanford.bmir.bioportal.LoadNEO - NEO axiom count: 0
[main] INFO org.stanford.bmir.bioportal.LoadNEO - NEO ontology ID: OntologyID(Anonymous-2)
[main] INFO org.stanford.bmir.bioportal.LoadNEO - NEO ontology format: TriX
```

Additionally, there are no exceptions thrown that would indicate why there are zero axioms.

I found some comments in issue #803 about a loaded ontology with zero axioms, so I tried adding the code you suggested to my program:

```
OWLOntologyLoaderConfiguration conf = new OWLOntologyLoaderConfiguration();
conf = conf.setBannedParsers("org.semanticweb.owlapi.rio.RioTrixParserFactory");
```

When I regenerated the JAR file and executed the program with this code, I did see an exception in the console window indicating the line on which the parser failed.

I'm unclear though on why I'm getting different results solely based on the method of program execution. I've been looking at this because we had an end user that tried to submit this ontology to BioPortal and our system was failing to handle it. I had a difficult time tracking down this issue of zero axioms since there were no exceptions, and I was further confused when I wrote a unit test to parse this ontology outside of our system and the ontology loaded without any issues in my IDE.

I created a small Maven project in IntelliJ with just the code I referenced above so that you have a reproducible case. I'm attaching the project, which contains the ontology file "NEO.owl".
[owlapi-neo-ont.zip](https://github.com/owlcs/owlapi/files/3129415/owlapi-neo-ont.zip)

**Comment by ansell** [comment]
When you create combined jar files you need to combine the `META-INF/services/` files, or the parsers are not detected correctly.

This is the way with the `maven-shade-plugin`, and there is similar for the `maven-assembly-plugin`:

https://github.com/owlcs/owlapi/blob/version5/distribution/pom.xml#L144

**Comment by ignazio1977** [comment]
Also, your POM file has `owlapi-distribution` and other OWLAPI modules mentioned explicitly. `owlapi-distribution` included a shaded file for the available parsers already and includes the other modules, so if only that reference is used you shouldn't see a difference in behaviour.

**Comment by jvendetti** [comment]
Thank you for the pointers @ansell and @ignazio1977. I removed the owlapi-rio and owlapi-compatibility dependencies, and replaced the maven-assembly-plugin with the maven-shade-plugin in the POM file. With my first attempt at a shade configuration:

```
<configuration>
  <transformers>
    <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
    <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
      <mainClass>org.stanford.bmir.bioportal.LoadNEO</mainClass>
    </transformer>
  </transformers>
</configuration>
```

... running the `mvn package` command resulted in a lot of overlapping classes warnings:

```
[WARNING] owlapi-tools-4.5.11.jar, owlapi-distribution-4.5.11.jar define 83 overlapping classes: 
[WARNING] owlapi-fixers-4.5.11.jar, owlapi-distribution-4.5.11.jar define 95 overlapping classes: 
[WARNING] owlapi-api-4.5.11.jar, owlapi-distribution-4.5.11.jar define 766 overlapping classes: 
[WARNING] owlapi-compatibility-4.5.11.jar, owlapi-distribution-4.5.11.jar define 83 overlapping classes: 
[WARNING] owlapi-oboformat-4.5.11.jar, owlapi-distribution-4.5.11.jar define 69 overlapping classes: 
[WARNING] owlapi-impl-4.5.11.jar, owlapi-distribution-4.5.11.jar define 218 overlapping classes: 
[WARNING] owlapi-rio-4.5.11.jar, owlapi-distribution-4.5.11.jar define 73 overlapping classes: 
[WARNING] owlapi-parsers-4.5.11.jar, owlapi-distribution-4.5.11.jar define 592 overlapping classes: 
[WARNING] owlapi-distribution-4.5.11.jar, owlapi-apibinding-4.5.11.jar define 3 overlapping classes: 
``` 

I added the following exclude to the configuration:

```
<artifactSet>
  <excludes>
    <exclude>net.sourceforge.owlapi:owlapi-distribution</exclude>
  </excludes>
</artifactSet>
```

... which resolved those warnings. Does this seem like the correct approach to you? Making these modifications to the POM file resolves the behavior I reported above.

**Comment by ignazio1977** [comment]
I would resolve the warnings in reverse, i.e., exclude the other dependencies (I believe they're there because of transitive dependencies) and use `owlapi-distribution` only. At that point you should not need shading at all, at least as far as OWLAPI is concerned, because `owlapi-distribution` already includes the properly merged files. The final artifact should be the same either way, though, so it's a matter of preference.
