### ISSUE TITLE
OWLLogicalEntity is not an OWLAnnotationProperty

### ISSUE THREAD

**Issue by Cydny** [owlcs/owlapi#847]
The documentation states:

"An OWLLogicalEntity is an OWLEntity that is not an OWLAnnotationProperty."

However, OWLAnnotationProperty is a subinterface of OWLLogicalEntity.

**Comment by ignazio1977** [comment]
Bad documentation. That comment has been incorrect for the past five years. OWLLogicalEntity has been redundant since at least then.
