### ISSUE TITLE
OBOFormatParser does not allow custom tag value pairs

### ISSUE THREAD

**Issue by matthewhorridge** [owlcs/owlapi#848]
The spec seems to indicate that custom tag value pairs should be processed, but any frame with a custom tag value pair generates a parse error.  This happens in the OBOFormatParser class - see https://github.com/owlcs/owlapi/blob/ba4aede81b92e91bc9d7af73ddb7f9dd3649a687/oboformat/src/main/java/org/obolibrary/oboformat/parser/OBOFormatParser.java#L523

The OBO2OWL translator deals with unknown tag value pairs by translating them into annotation assertions.  

I believe that custom tags, translated as annotation values should be supported.

cc @cmungall

**Comment by cmungall** [comment]
I think in retrospect it was a mistake allowing that. The actual behavior of the parser at the moment is incredibly useful as undeclared tags happen as a result of errors a lot (maybe I hand-edit too much).

@althonos what is the behavior of your parser here?

**Comment by althonos** [comment]
The spec allows custom tag values *in the header only*, so my parser will allow that, but my OWL translator will not process them at all. It will fail on unknown tags in other frames.

**Comment by ignazio1977** [comment]
Looks like there are dissenting opinions :-)

Three possibilities:
- header
- anywhere
- nowhere

Which one do you reckon it's best?

**Comment by althonos** [comment]
I think the header-only was thought as a compatibility option for older OBO files, but in order to translate header clauses to annotation values the property value clause can already be used explicitly. As Chris said, not allowing unreserved clauses helps detecting the one that are typos... but there are probably only a handful of persons that are hand-editing.

**Comment by matthewhorridge** [comment]
Isn't it possible to declare these non-builtin tags before they are used?  I seem to recall isMetaTag or something like that.

**Comment by cmungall** [comment]
> Looks like there are dissenting opinions :-)

I defer to @althonos! Yes, it's quite correct that undeclared tags are only permitted in the header according to the spec.

The current OWLAPI behavior is therefore in fact correct.

However, the spec is underspecified in terms of what happens to these in translation. Currently the tag is translated to an oboInOwl property in the OWLAPI which does not contradict anything in the spec. We can formalize this existing behavior in the spec.

> Isn't it possible to declare these non-builtin tags before they are used? I seem to recall isMetaTag or something like that.

Nah, for declaring a Typedef as an AP

Anyway, I think go ahead and make the release without any changes here. We can leave this open til we properly thrash out the details but no sense holding up the release on this

> but there are probably only a handful of persons that are hand-editing

Where is the emoji for "whistles innocently"?
