### ISSUE TITLE
Using OWL API with WordNet 

### ISSUE THREAD

**Issue by TahaniAM** [owlcs/owlapi#849]
Hello all, 
I have created an OWL ontology using Protege OWL 5.5 , one of the tasks was creating synonyms for a property value and classify the objects accordingly. This was done hard-coded (i.e. list of synonyms were defined as individuals in the ontology with hasSynonm property linking them. Now I would like to use OWL API and WordNet libraries in Eclipse to do the following:
1. Define synonyms of a certain individual using WordNet (this should be done dynamically not as mentioned above). 

Since I'm new with OWL API, any advise on where to start shall be highly appreciated. 

Best,
Tahani

**Comment by ignazio1977** [comment]
Sounds like you need to create `SameAs` axioms. Have you checked out the documentation section on the wiki?

**Comment by TahaniAM** [comment]
Thank you for your prompt response. No I haven't , will have a look at it.
