### ISSUE TITLE
Question about trailing modifiers format in OBO files.

### ISSUE THREAD

**Issue by fanavarro** [owlcs/owlapi#853]
Hi all. I would like to ask you a question about trailing modifiers in OBO ontologies.

The OBO parser is showing warning messages indicating that qualifier values should be enclosed by quotes. I have searched information on this I what I have found is the following example from [OBO 1.2 specification](https://owlcollab.github.io/oboformat/doc/GO.format.obo-1_2.html#S.2.2.3):

`[GO:ma, GO:midori "Midori was drinking and came up with this", GO:john {namespace=johnsirrelevantdbxrefs}]`

They are setting an unquoted text for a trailing modifier value. For its part, I have not found an example for OBO 1.4.

My question is what is the correct format for trailing modifiers?

Regards and thanks so much for your time,
Fran.

**Comment by ignazio1977** [comment]
From what the code is doing, it looks to me that the quotes are optional for any data that does not have spaces, commas or `}` closing braces in it; if any such characters appear in the value for the trailing qualifier, then the value must be enclosed in quotes or there might be parsing errors.

From the spec, I'm not sure if this behaviour is fully described, anyway the example in the specs would parse without errors.

**Comment by fanavarro** [comment]
Hi @ignazio1977 , thanks for your answer. What I'm wondering now is if the warning provided by the parser is a real warning or not. I am moving this question to [https://github.com/owlcollab/oboformat/issues/114](https://github.com/owlcollab/oboformat/issues/114), which I think is a better place to discuss about obo format.

Thanks again.
Greetings.

**Comment by fanavarro** [comment]
I have answer from owlcollab, trailing modifiers values should be quoted text.

I am closing this issue as my doubt has been solved.
