### ISSUE TITLE
owlapi Turtle parser does not respect escape character in URI local parts

### ISSUE THREAD

**Issue by cmungall** [owlcs/owlapi#857]
OK, this is actually a surprisingly difficult error to produce a small test case for, due to the existence of two RDF parsers in the OWLAPI. It's necessary to produce a test case with a *separate* problem `P` that causes the Rio parser to fail, where `P` succeeds with the owlapi native parser.

Still with me? Hopefully this example will make things clear:

`test.ttl`:

```turtle
@prefix  obo: <http://purl.obolibrary.org/obo/> .
@prefix  owl: <http://www.w3.org/2002/07/owl#> .

## Rio does not like this as base is not declared
obo:foo a <label> .

## owlapi parser does not like backslash
obo:bar owl:versionIRI obo:foo\/bar .
```

As comparison, note that Jena is cool with this. When I run `riot test.ttl` I get:

```turtle
<http://purl.obolibrary.org/obo/foo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <file:///Users/cjm/repos/owl_patternizer/label> .
<http://purl.obolibrary.org/obo/bar> <http://www.w3.org/2002/07/owl#versionIRI> <http://purl.obolibrary.org/obo/foo/bar> .
```

Note that it creates a default base, which is my filesystem.

However, when I try to parse `test.ttl` with the OWLAPI I get the characteristic Giant Wall of Error Messages (see [log.txt](https://github.com/owlcs/owlapi/files/3318755/log.txt)
). This is particularly confusing as Rio uses the turtle parser to try and parse Trig and N3. But whittling it down to the two main parsers:

Rio turtle:
 ```
Relative URI 'label' cannot be resolved using the opaque base URI 'urn:default:baseUri:' [line 5]        org.openrdf.rio.helpers.RDFParserHelper.reportError(RDFParserHelper.java:348)
```

owlapi turtle:
```
Encountered " <ERROR> "\\ "" at line 8, column 31.
Was expecting:
    "." ...
            org.semanticweb.owlapi.rdf.turtle.parser.TurtleParser.generateParseException(TurtleParser.java:1548)
```

In order to get around this, I can just change my turtle to declare a `@base`. This renders the owlapi parsers behavior moot, as the Rio parser will handle it just fine.

However, I think if the owlapi parser is not deprecated, then it should implement the spec and allow escaping of slashes.

I also think both parsers should implement `@base` in the same way.

However, there is a broader issue here. I see the value in having parser redundancy, it increases the chance of getting some interpretation of the source file. But surely it should be possible to have one parser that follows the spec? My example was whittled down from a much larger file that was failing to parse, it hurt my brain a bit trying to figure out what was going on, as I had forgotten there was parser redundancy.

I can imagine all kinds of cryptic errors creeping in, such that a line change inducing an error in one parser, causing the owlapi to flip to the alternate parser, which rather than causing an error, implements some other different behavior, subtly changing the meaning of the file?

**Comment by ignazio1977** [comment]
Sorry to hear of the problems replicating this - there's a way to specify the format you wish to use, by creating an explicit document source and setting the format in the constructor. This would have saved you time in creating the replication.
