### ISSUE TITLE
Q: local web reads ontology

### ISSUE THREAD

**Issue by thomakl** [owlcs/owlapi#858]
Hi,

I have a question about using OWLAPI with a hosted ontology as Jena-Fuseki would do it.
Is there an alternative to it working with OWLAPI ? I read about Open Semantic Framework : does anyone have tried to make it work with OWLAPI ?
I working on a project where I need to read my ontology and write the result in a local html website

Thank you for your time,

PS: I wanted to ask my question to mailing group but I'm facing an issue. I'm sorry to disturb the code section with my question.

**Comment by ignazio1977** [comment]
Don't worry about the mailing list, all the issues and questions are seen by the same team :-)

I don't know about open semantic network - do you have a link?

Owlapi can be used to write changes to a remote page by using the output stream you can obtain from an http connection, so in that respect there's little difference with working with a local file.
