### ISSUE TITLE
Conversion from OBO to OWL Functional creates invalid IRIs

### ISSUE THREAD

**Issue by althonos** [owlcs/owlapi#863]
Hi ! I noticed this issue while trying to use both `owltools` and `robot` so I assume it is an OWL API issue.

When converting from OBO to OWL Functional, some prefixed identifiers are expanded without proper escaping, creating the invalid IRIs.

Example:
* Download [`ecocore.obo`](http://purl.obolibrary.org/obo/ecocore.obo)
* Run `robot convert --input ecocore.obo --format ofn --output ecocore.ofn` or `owltools ecocore.obo -o -f ofn go.ofn`

The resulting file will contain invalid IRIs such as:
```
http://www.geneontology.org/formats/oboInOwl#http://www.w3.org/2000/01/rdf-schema#seeAlso
```

(this is also an obvious conversion issue but as far as this goes I'm only concerned about the syntax right now).

**Comment by ignazio1977** [comment]
There are two uses of `http://www.w3.org/2000/01/rdf-schema#seeAlso` and many more uses of `seeAlso` in the file, so it seems clear that the main problem is that the data is using a tag incorrectly.
We can add code to detect similar problems bu I'm not sure what the behaviour should be. Probably throw an exception if the IRI is invalid? Alternatively, if the string matches a vocabulary annotation property, we could use that in place of `oboInOwl#`+tag.
