### ISSUE TITLE
containsReference(OWLEntity) should be deprecated

### ISSUE THREAD

**Issue by sszuev** [owlcs/owlapi#864]
What is the difference between `org.semanticweb.owlapi.model.OWLSignature#containsReference(OWLEntity)` and `org.semanticweb.owlapi.model.HasContainsEntityInSignature#containsEntityInSignature(OWLEntity)` for an ontology?

I suppose the first method returns `true` if the entity belongs to some axiom, while the second returns `true`, if the entity belongs either to some axiom or to the ontology header.
Is it correct?

There is no javadoc for the method `#containsReference(OWLEntity)`, so this issue may be considered as a minor bug.

**Comment by ignazio1977** [comment]
`OWLSignature` implements both methods, and from what I can see the two methods are equivalent.

`containsReference` has been in the API since 2009, while the signature terminology has been introduced later. Possibly at some point the functionality was markedly different, but in the current code base `containsReference` might be implemented delegating to the signature methods.

**Comment by sszuev** [comment]
As I said above they are not equivalent, and have different implementations. 
Consider the testcase:

            OWLOntologyManager man = OWLManager.createOWLOntologyManager();
            OWLDataFactory df = man.getOWLDataFactory();

            OWLAnnotationProperty p = df.getOWLAnnotationProperty("P");
            OWLAnnotation a = df.getOWLAnnotation(p, df.getOWLLiteral("xxx"));
            OWLOntologyID id = new OWLOntologyID();

            OWLOntology o = man.createOntology(id);
            man.applyChange(new AddOntologyAnnotation(o, a));

            System.out.println(o.containsReference(p));
            System.out.println(o.containsEntityInSignature(p));

I think if the method has no description since 2009, and nobody cares, it can be marked as deprecated and soon safely delete.
