### ISSUE TITLE
referencingAxioms(OWLPrimitive) misses IRI appearances

### ISSUE THREAD

**Issue by sszuev** [owlcs/owlapi#865]
Unable to find axioms by IRI in the object position.
Testcase:

```
OWLDataFactory df = m.getOWLDataFactory();
OWLOntology o = m.createOntology();
IRI query = IRI.create("someIRI");
o.add(df.getOWLAnnotationPropertyDomainAxiom(df.getOWLAnnotationProperty("AP1"), query));
OWLAnnotation a = df.getOWLAnnotation(df.getOWLAnnotationProperty("AP2"), query);
o.add(df.getOWLSubClassOfAxiom(df.getOWLClass("C"), df.getOWLThing(), Collections.singletonList(a)));
o.add(df.getOWLAnnotationAssertionAxiom(IRI.create("otherIRI"), a));
long count = o.referencingAxioms(query).peek(System.out::println).count();
Assert.assertEquals(3, count);
```

It is not clear from javadocs is it correct behavior or not:
`Gets the axioms where the specified {@link OWLPrimitive} appears in the signature of the axiom.`
Indeed, a naked IRI is not part of signature.
On the other hand, Literal is also not a part of signature, but the search is still performed in its deeps.

current OWL-API ver: 5.1.11

**Comment by ignazio1977** [comment]
Good catch, the IRI search should be performed on annotation domains, annotation ranges and annotations on axioms - it's currently looking only at annotation assertion axioms.
