### ISSUE TITLE
FactoryNotFoundException

### ISSUE THREAD

**Issue by billdyla** [owlcs/owlapi#866]
My ontologies are not self-hosted (web addressable from the ontolgy’s uri). They are web addressable as a query string 

Example:
Ontology uri: http://example.com/ns/core-o
Accessible at: https://example.com/ohoster?ontology=http://example.com/ns/core-o

I’ve managed to load the main ontology using the silent import strategy and can determine which imports were successful using a LoaderListener.

However, some ontology URIs are URN of the form urn:example.com:collibra. These fail on load and cause the main ontology to fail. With 
OWLOntologyFactoryNotFoundException: Could not find an appropriate factory to load ontology from ontology document: <urn:example.com:collibra

How can I handle these?

advTHANKSance
-bd

**Comment by billdyla** [comment]
Clarification: The URN based ontologies are imports of the main.

**Comment by ignazio1977** [comment]
These can't be loadable without knowing a location for the actual ontology. If you know where there actual ontology is available you can add an `OWLOntologyIRIMapper`to your ontology manager instance and map the urn iri to the actual URL. Otherwise it's simply impossible for owlapi to find the data to load.

**Comment by billdyla** [comment]
I can determine the the URL by prepending it with a real host and query string, but I don’t know the imports before I load the main ontology

Do you think it’s possible to catch the exceptions and load the notfound imports then try to reload the main in a loop? Or subclass something that will recognize the urn pattern and rewrite the url somehow using the factory pattern? Or something else?

**Comment by ignazio1977** [comment]
It's possible to write an iri mapper that works by recognising a pattern in the urn and replacing it, have a look at the interface - if you find it difficult to do, please post an update.

**Comment by billdyla** [comment]
Thanks
That works
However, the main ontology is not being mapped
I use the loadOntologyFromOntologyDocument method, which does not go through the mapper.

Do you think it should?

**Comment by ignazio1977** [comment]
It doesn't need to go through the mapping if you have a way of directly addressing the ontology document, so it's up to your needs to decide whether to change that or not.

**Comment by billdyla** [comment]
ok. thanks.
I'm going to close the thread. 
you've been very helpful.
