### ISSUE TITLE
OWLDataRange#isAnonymous() returns false

### ISSUE THREAD

**Issue by sszuev** [owlcs/owlapi#867]
Checked v 5.1.11:

        OWLDataFactory df = OWLManager.createOWLOntologyManager().getOWLDataFactory();
        System.out.println(df.getOWLDataOneOf(df.getOWLLiteral(1)).isAnonymous());
        System.out.println(df.getOWLDataIntersectionOf(df.getStringOWLDatatype()).isNamed());

**Comment by sszuev** [comment]
`OWLLiteral` is also turned out to be named and non-anonymous.

**Comment by sszuev** [comment]
_+_ Currently `OWLAxiom` is anonymous and not named - that is strange, it is not b-node, but rather a triple, which cannot be anonymous - or it should be documented. 
_+_ `OWLAnnotation` - currently it is named and non-anonymous.
I'd suggest to make all these three things (`OWLLiteral`, `OWLAnnotation`, `OWLAxiom`) to be neither named, nor anonymous

**Comment by ignazio1977** [comment]
Axioms are anonymous because they do not have IRIs. It would be much easier to write annotations on RDF/XML if they were not anonymous.

Axioms are not triples, they're set of triples - only some of them are just one triple. But neither case allows them to not be anonymous.

**Comment by sszuev** [comment]
So, a set of triples can be anonymous - ok.  
Can you then cconfirm, that the following is correct: `OWLLiteral` (named=`false`, anonymous=`false`), `OWLAnnotation` (named=`false`, anonymous=`true` (just like for `OWLAxiom`)), `OWLAxiom` (named=`false`, anonymous=`true`)

**Comment by ignazio1977** [comment]
`OWLLiteral` is wrong - `named = !anonymous`, so the two values cannot be equal. I need to take a second look but I believe anonymous should be true.

`OWLAnnotation` should be anonymous. A data range that is not a datatype - so an intersection - should be anonymous. An intersection of one element is something to check on the specs, because for other intersections there's a lower limit on how many elements appear in it - at least two. So there's a possibility that an intersection with one element only is not a valid OWL construct, and therefore named/anonymous is a moot question.

**Comment by sszuev** [comment]
>  so the two values cannot be equal

Why? 

Making `OWLLiteral` to be named or anonymous contradicts the RDF understanding of Literal, it is neither named or anonymous, it is literal. Of course, it is OWL-API literal, which may have it is own additional meanings and rules, depending on devs wishes. But I believe there must be good reasons to make either it named or anonymous or both.

Also, can you provide a ref to that spec ?
Can't find in the official (https://www.w3.org/TR/owl-syntax/) anything, with except of entities and anonymous individuals, which are named or anonymous exactly in RDF sense.

**Comment by ignazio1977** [comment]
> Making OWLLiteral to be named or anonymous contradicts the RDF understanding of Literal

That's not the point.

As you say, the specs only talk of individuals and entities. This is where `isAnonymous()` was defined. However, in code entities and expressions share a hierarchy, and in many places we found ourselves checking if an `OWLObject was an entity or  a named individual, or an anonymous expression. Keeping the method only defined for entities and expressions required to first visit the OWLObject to determine if it was an entity or not, and this created a lot of verbose, inefficient code. Moving the declaration to OWLObject allowed code to become a lot simpler; the understanding being that anything *not* a class, property, datatype or named individual, would be anonymous - the defining characteristic being that a named entity only has an IRI and an entity type of the six entity types.

**Comment by sszuev** [comment]
Well, as for me, such an optimization looks rather suspicious. 
It seems to be a consequence of belief that `instanceOf` works inefficient, which is just some kind of urban legend.
I could not find any example in OWL-API codebase, where the methods `#isAnnonymous()` or `#isNamed()` are called on raw `OWLObject` instance. 
But there are lot of examples where the instance is `OWLClassExpression` (and for this case there is one more sugar-method: `isAnnonymousExpression`).
As for the external use of this functionality - so far no one has found that data ranges are named - and this fact says a lot.

Anyway, since OWL-API is not only this repo, but also any alternative implementations, including ONT-API, that is maintained by me, I am very interested in having a good API module, which includes the good documentation. 
If `OWLLiteral`, `OWLAxiom` and `OWLAnnotation` must be anonymous and non-named, it would be nice to have explanation about it in javadocs.
Well, taking into account that ONT-API is RDF-centric implementation and any axiom there is really backed by the triple set, the first case (i.e. `OWLLiteral`) looks especially ridiculous - but it is okay, if there is a good javadoc. Otherwise, it can really be confusing.
Also, if there is the contract, which states that these two properties cannot be equal simultaneously, 
it should be also described (or, better, one of these pairwise sugar-methods can be made deprecated - just because these kinds of improvements only impair code readability).

**Comment by sszuev** [comment]
It would be nice to see a link (or a couple) to an example of such peculiar optimization from the OWL-API codebase. I suspect that either such things do not exist anymore, or they can be replaced with smarter code.

_+_ `OWLFacetRestriction` also turns out to be named, and non-anonymous. And, it is not anonymous expression (`isAnonymousExpression() = false`).

**Comment by ignazio1977** [comment]
On Sun, 18 Aug 2019 at 11:59, ssz <notifications@github.com> wrote:

> Well, as for me, such an optimization looks rather suspicious.
> It seems to be a consequence of belief that instanceOf works inefficient,
> which is just some kind of urban legend.
>

"It seems" is wrong.

Nothing to do with performance. It was verbose code and unnecessary
visitors, which cause the developers to be slower, not the code to be
slower.


> I could not find any example in OWL-API codebase, where the methods
> #isAnnonymous() or #isNamed() are called on raw OWLObject instance.
> But there are lot of examples where the instance is OWLClassExpression
> (and for this case there is one more sugar-method: isAnnonymousExpression
> ).
> As for the external use of this functionality - so far no one has found
> that data ranges are named - and this fact says a lot.
>
> Anyway, since OWL-API is not only this repo, but also any alternative
> implementations, including ONT-API, that is maintained by me, I am very
> interested in having a good API module, which includes the good
> documentation.
> If OWLLiteral, OWLAxiom and OWLAnnotation must be anonymous and
> non-named, it would be nice to have explanation about it in javadocs.
>

Fair point.


> Well, taking into account that ONT-API is RDF-centric implementation and
> any axiom there is really backed by the triple set, the first case (i.e.
> OWLLiteral) looks especially ridiculous - but it is okay, if there is a
> good javadoc. Otherwise, it can really be confusing.
> Also, if there is the contract, which states that these two properties
> cannot be equal simultaneously,
> it should be also described (or, better, one of these pairwise
> sugar-methods can be made deprecated - just because these kinds of
> improvements only impair code readability).
>

One's shortcut is always someone else's code readability problem.

I.

**Comment by sszuev** [comment]
A couple of points:

> One's shortcut is always someone else's code readability problem

Well, I have no purpose to persuade, but in my humble opinion, [making some stream processing look nicer](https://github.com/owlcs/owlapi/issues/790) is not enough reason to introduce new functionality. 

And FYI: https://effectivesoftwaredesign.com/2013/08/05/simplicity-in-software-design-kiss-yagni-and-occams-razor/
