### ISSUE TITLE
Get type of components in ObjectPropertyAssertionAxiom from OWL Ontology

### ISSUE THREAD

**Issue by sathyamoorthyrr** [owlcs/owlapi#869]
I have the following content in my `.owl` file

```
 <owl:ObjectProperty rdf:about="http://www.semanticweb.org/owlproject#intheRegionOf">
    <rdfs:domain rdf:resource="http://www.semanticweb.org/owlproject#Object"/>
    <rdfs:domain rdf:resource="http://www.semanticweb.org/owlproject#Fruit"/>
    <rdfs:range rdf:resource="http://www.semanticweb.org/owlproject#Region"/>
</owl:ObjectProperty>

 <owl:NamedIndividual rdf:about="http://www.semanticweb.org/owlproject#pen">
	<rdf:type rdf:resource="http://www.semanticweb.org/owlproject#Object"/>
	<intheRegionOf rdf:resource="http://www.semanticweb.org/owlproject#table"/>
 </owl:NamedIndividual>

  <owl:NamedIndividual rdf:about="http://www.semanticweb.org/owlproject#apple">
	<rdf:type rdf:resource="http://www.semanticweb.org/owlproject#Fruit"/>
	<intheRegionOf rdf:resource="http://www.semanticweb.org/owlproject#chair"/>
 </owl:NamedIndividual>
```

As you could infer, there could be a multiple **domain** for a given **range**.

I read the this file as an **ontology** and **iterating** the individuals as below,

```
ontology.individualsInSignature().forEach(i => {
  ontology.objectPropertyAssertionAxioms(i).forEach(ob => {
    // ob.getSubject - ob.getProperty - ob.getObject
    // This correspondingly gives,
    // pen - intheRegionOf - table
    // apple - intheRegionOf - chair
  }
}
```

With this, I could get the values like _pen, intheRegionOf, table, apple, chair_

However, I do need the type it belongs to. like,
pen - _Object_
apple - _Fruit_
(This information seems to present within _<owl:NamedIndividual>_)

Also,
table - Region
chair - Region
(This information seems to present within _<owl:ObjectProperty>_)

Or, is there any other way to iterate and get all `objectPropertyAssertionAxioms` altogether than `ontology.individualsInSignature().forEach`?

**Comment by ignazio1977** [comment]
There's a terminology issue: the object property assertion axiom here is the 

    <intheRegionOf rdf:resource="http://www.semanticweb.org/owlproject#chair"/>

part of the input. The domain and range information comes from the object property domain and range axioms included under the property declaration, i.e., 

    <rdfs:domain rdf:resource="http://www.semanticweb.org/owlproject#Fruit"/>
    <rdfs:range rdf:resource="http://www.semanticweb.org/owlproject#Region"/>

Your objective could be achieved listing the domain axioms and range axioms for each object property, but an easier approach would be to use an OWL reasoner, which provides methods to access the types of an individual without worrying about whether their type is declared or inferred via an object property. OWLAPI does not provide a complete OWL reasoner, but there are various implementations available. Openllet and HermiT are two reasoners available on Maven Central for OWL 2 DL; if your ontology has EL expressivity, you could use ELK.

**Comment by sathyamoorthyrr** [comment]
Sure, I'll then try with the **Reasoner**.
Any recommendation for a suitable reasoner to use based on your experiences?
I'm using `scala` environment.
Also, any idea on what reasoner is being used by the [Protege](https://protege.stanford.edu/) tool under the hood?

**Comment by ignazio1977** [comment]
The reasoners I mentioned above are all pure Java and are usable with protégé.

**Comment by sathyamoorthyrr** [comment]
After trying with the Hermit reasoner(to my knowledge), I came back to the same point as in owlapi.

`reasoner.getObjectPropertyInstances(df.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/owlproject#intheRegionOf")))`

The resultant **HashMap** has a mapping from,
_pen -> table
apple -> chair_

Still, I could not get the `type` of _pen, table, apple or chair_

any idea would be helpful

**Comment by sathyamoorthyrr** [comment]
However, could see that the following methods works fine given the **OWLNamedIndividual**
```
EntitySearcher.getTypes
reasoner.getType
```
But, if the same item has multiple definitions like _Snippet 1 and 2_ in same file, it returns both.
```
<!-- ObjectProperty -->
 <owl:NamedIndividual rdf:about="http://www.semanticweb.org/owlproject#pen">
	<rdf:type rdf:resource="http://www.semanticweb.org/owlproject#Object"/>
	<intheRegionOf rdf:resource="http://www.semanticweb.org/owlproject#table"/>
 </owl:NamedIndividual>

<!-- Snippet 1 -->
 <owl:NamedIndividual rdf:about="http://www.semanticweb.org/owlproject#pen">
	<rdf:type rdf:resource="http://www.semanticweb.org/owlproject#Object"/>
 </owl:NamedIndividual>

<!-- Snippet 2 -->
 <owl:NamedIndividual rdf:about="http://www.semanticweb.org/owlproject#pen">
	<rdf:type rdf:resource="http://www.semanticweb.org/owlproject#NonLivingObject"/>
 </owl:NamedIndividual>
```

The expected result is only **Object** as that is the one present in given _ObjectProperty_ above.

**Comment by ignazio1977** [comment]
Unfortunately you cannot get that from an owl ontology. The types of an individual are inferred from all the relevant axioms in the ontology; if you wish some inferences to be skipped, you either have rp filter the results yourself or remove the undesired axioms from the ontology

**Comment by sathyamoorthyrr** [comment]
means, I hope the tools like _protege_ just draw a relationship between one node and another upon reading **NamedIndividuals** and **ObjectProperties** serially.

Like, for a given Snippet above,
```
1. It first assigns the type **Object** for Node **pen**  <!-- ObjectProperty -->
2. Then, it assigns type **Object** for Node **pen**(actually already set)  <!-- Snippet 1 -->
3. Then, it assigns type **NonLivingObject** for Node **pen**  <!-- Snippet 2 -->
```
Correct me if I'm wrong.

Now, I don't have chance to filter or remove the undesired axioms as suggested.
If my problem could not be solved with _Ontology_ processing, should I go for _XML_ Processing(of an `.owl` file)
Bad Idea though!

**Comment by ignazio1977** [comment]
You're wrong in assuming an individual can have only one type. It can have multiple ones. Protege needs to choose which one to use first when plotting on screen, but they're all equally valid and all represented. The order in which they appear in the file is irrelevant.

**Comment by sathyamoorthyrr** [comment]
Understood. The Individual can have multiple types.
But, why isn't that type bound to **ObjectProperty** axioms?

**Comment by ignazio1977** [comment]
> why don't an ObjectProperty axiom have the types of its Individuals stored within?

Because object property assertions only specify a relation between two individuals, nothing else.

The types of an individual need not be explicit, that's the main feature of ontologies - inferences can be drawn from multiple axioms to make knowledge explicit. In this case, type inference is drawn from the property assertion and the property domain/range axioms, taken as a whole.

**Comment by sathyamoorthyrr** [comment]
closing this issue as
1. the **Individual** can have multiple _types_
2. **Object Property Assertion** only specifies the relationship and not a _Type_ involved.
