### ISSUE TITLE
DL Query

### ISSUE THREAD

**Issue by billdyla** [owlcs/owlapi#873]
I would like to implement something like the DL Query tab in Protege. 
Is there an example directly in the OWLAPI?

**Comment by ignazio1977** [comment]
Check https://github.com/owlcs/owlapi/wiki/DL-Queries-with-a-real-reasoner it might be what you're after.

**Comment by billdyla** [comment]
Yes. That’s a big help.

-bd

**Comment by ignazio1977** [comment]
Look at ToStringRenderer, it allows you to choose the format.

**Comment by billdyla** [comment]
Thanks. That works nicely.
