### ISSUE TITLE
Protégé plugin - class selection

### ISSUE THREAD

**Issue by ianhyland** [owlcs/owlapi#876]
Hi,

I’m developing a Protégé plugin that successfully uses this method:  
OWLClass concept = getOWLWorkspace().getOWLSelectionModel().getLastSelectedClass();

Protege allows for more than one class to be selected at a time i.e. by using the shift or ctrl key.

Is there a method that extends the function of  getLastSelectedClass()  such that it returns all selected classes (and object properties for that matter !!)??

Help appreciated.

**Comment by ignazio1977** [comment]
Hi, I think you need to ask this question on the protegeproject issue tracker.

**Comment by ianhyland** [comment]
Hi,

 

I’m developing a Protege plugin that successfully uses this method:  OWLClass concept = getOWLWorkspace().getOWLSelectionModel().getLastSelectedClass();

 

Protege allows for more than one class to be selected i.e. by using the shift or ctrl key.

 

Is there a method that extends the function of getLastSelectedClass() such that it returns all selected classes (will also need to cover ObjectProperties with presumably a separate method) ??

 

Help appreciated.

 

 

 

 

Best regards,

 

Ian. 

======================================================================================

Ian Hyland                                  Email: ianhyland@ngensys.com <mailto:ianhyland@ngensys.com>                                       Tel: +44 7816 671 524

======================================================================================
