### ISSUE TITLE
Annotated annotation with anon individual serialized in RDF incorrectly

### ISSUE THREAD

**Issue by sszuev** [owlcs/owlapi#877]
Consider the following testcase (checked v 5.1.11):

    public static void main(String... args) throws OWLOntologyCreationException {
        Supplier<OWLOntologyManager> m = OntManagers::createOWL;

        OWLDataFactory df = m.get().getOWLDataFactory();
        OWLDataProperty dp = df.getOWLDataProperty("http://ex-test.argh#D");
        OWLObjectProperty op = df.getOWLObjectProperty("http://ex-test.argh#O");
        OWLAnnotationProperty ap = df.getOWLAnnotationProperty("http://ex-test.argh#A2");
        OWLAnonymousIndividual i = df.getOWLAnonymousIndividual("_:b0");
        OWLAnnotation sub1 = df.getOWLAnnotation(df.getRDFSComment(), df.getOWLLiteral("z1"));
        OWLAnnotation an1 = df.getOWLAnnotation(ap, i, Collections.singletonList(sub1));

        OWLClassExpression c1 = df.getOWLDataAllValuesFrom(dp, df.getBooleanOWLDatatype());
        OWLClassExpression c2 = df.getOWLObjectSomeValuesFrom(op, df.getOWLThing());

        OWLAxiom ax1 = df.getOWLSubClassOfAxiom(c1, c2, Collections.singletonList(an1));

        OWLOntology ont1 = m.get().createOntology();
        ont1.add(ax1);
        OWLDocumentFormat format = new TurtleDocumentFormat();
        String res = makeString(ont1, format);
        System.out.println(res);

        OWLOntology ont2 = fromString(m.get(), res, format);
        System.out.println(makeString(ont2, format));

        List<OWLAxiom> actual = ont2.axioms()
                .peek(x -> System.out.println("Axiom:::" + x))
                .filter(x -> AxiomType.SUBCLASS_OF.equals(x.getAxiomType()))
                .collect(Collectors.toList());
        assertTrue(1 == actual.size());
        OWLAxiom ax2 = actual.get(0);
        System.out.println("E:::" + ax1);
        System.out.println("A:::" + ax2);
        OWLAnnotation an2 = ax2.annotations().findFirst().orElseThrow(AssertionError::new);
        OWLAnnotation sub2 = an2.annotations().findFirst().orElseThrow(AssertionError::new);
        assertTrue(sub2.equals(sub1));
    }

    private static String makeString(OWLOntology ontology, OWLDocumentFormat format) {
        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            ontology.getOWLOntologyManager().saveOntology(ontology, format, out);
            return out.toString(StandardCharsets.UTF_8.name());
        } catch (OWLOntologyStorageException | IOException e) {
            throw new AssertionError(e);
        }
    }

    private static OWLOntology fromString(OWLOntologyManager m, String txt, OWLDocumentFormat format) {
        OWLOntologyDocumentSource src = new StringDocumentSource(txt, IRI.create("http:://fromStr"), format, null);
        try {
            return m.loadOntologyFromOntologyDocument(src);
        } catch (OWLOntologyCreationException e) {
            throw new AssertionError(e);
        }
    }

    private static void assertTrue(boolean ex) {
        if (ex) return;
        throw new AssertionError();
    }

Similar to #874 ,

**Comment by ignazio1977** [comment]
Not sure why you deleted the last sentence in the comment. It's always better to clarify context.

Side bar: if by OWL is RDF you mean they have the same semantics, that's not correct. There's a large overlap but neither contains the other. OWL 2 Full contains the RDF and RDFS semantics, but not OWL 2 DL.
If you mean that all OWL ontologies can be written as RDF files, that's true. When it does not work, that's a bug.
If you mean that all RDF files are valid OWL ontologies, that's not the case.

**Comment by ignazio1977** [comment]
Running the code with OWLAPI version5 branch (with a few bug fixes not yet released) I get the following Turtle output (comments stripped):

    @prefix owl: <http://www.w3.org/2002/07/owl#> .
    @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
    @prefix xml: <http://www.w3.org/XML/1998/namespace> .
    @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
    @base <http://www.w3.org/2002/07/owl#> .
    
    [ rdf:type owl:Ontology ] .
    <http://ex-test.argh#A2> rdf:type owl:AnnotationProperty .
    <http://ex-test.argh#O> rdf:type owl:ObjectProperty .
    <http://ex-test.argh#D> rdf:type owl:DatatypeProperty .
    
    [ rdf:type owl:Annotation ;
      owl:annotatedSource _:genid4 ;
      owl:annotatedProperty <http://ex-test.argh#A2> ;
      owl:annotatedTarget [ ] ;
    rdfs:comment "z1"
    ] .
    
    _:genid4 rdf:type owl:Axiom ;
          owl:annotatedSource [ rdf:type owl:Restriction ;
                                owl:onProperty <http://ex-test.argh#D> ;
                                owl:allValuesFrom xsd:boolean ;
                                rdfs:subClassOf [ rdf:type owl:Restriction ;
                                                  owl:onProperty <http://ex-test.argh#O> ;
                                                  owl:someValuesFrom owl:Thing
                                                ]
                              ] ;
          owl:annotatedProperty rdfs:subClassOf ;
          owl:annotatedTarget [ rdf:type owl:Restriction ;
                                owl:onProperty <http://ex-test.argh#O> ;
                                owl:someValuesFrom owl:Thing
                              ] ;
          <http://ex-test.argh#A2> [ ] .

This output thinks there are two distinct anonymous nodes, used as values of an `A2` annotation. The code shows one anonymous individual only, so this is wrong. The output should contain `_:genid5` or a similar id. I believe it's a bug in the code that looks for individuals with multiple references.
