### ISSUE TITLE
Wrong axioms when the RDF contains annotations

### ISSUE THREAD

**Issue by sszuev** [owlcs/owlapi#879]
It is one more demonstration for #874 

            String txt = "@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\n" +
                    "@prefix owl:   <http://www.w3.org/2002/07/owl#> .\n" +
                    "@prefix x:     <http://argh#> .\n" +
                    "@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .\n" +
                    "@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .\n" +
                    "\n" +
                    "x:P2    a       owl:ObjectProperty .\n" +
                    "\n" +
                    "[ a                      owl:Axiom ;\n" +
                    "  rdfs:comment           \"y\" , \"x\" ;\n" +
                    "  owl:annotatedProperty  rdfs:subClassOf ;\n" +
                    "  owl:annotatedSource    [ a                owl:Restriction ;\n" +
                    "                           rdfs:subClassOf  [ a                   owl:Restriction ;\n" +
                    "                                              owl:onProperty      x:P1 ;\n" +
                    "                                              owl:someValuesFrom  x:C\n" +
                    "                                            ] ;\n" +
                    "                           owl:hasValue     x:I ;\n" +
                    "                           owl:onProperty   x:P1\n" +
                    "                         ] ;\n" +
                    "  owl:annotatedTarget    [ a                   owl:Restriction ;\n" +
                    "                           owl:onProperty      x:P2 ;\n" +
                    "                           owl:someValuesFrom  x:C\n" +
                    "                         ]\n" +
                    "] .\n" +
                    "\n" +
                    "x:I     a       owl:NamedIndividual .\n" +
                    "\n" +
                    "x:P1    a       owl:ObjectProperty .\n" +
                    "\n" +
                    "x:C     a       owl:Class .";

            OWLOntologyDocumentSource src = ReadWriteUtils.getStringDocumentSource(txt, OntFormat.TURTLE);
            OWLOntologyManager man = OntManagers.createOWL();
            OWLOntology o = man.loadOntologyFromOntologyDocument(src);
            o.axioms().forEach(System.out::println);
            Assert.assertEquals(1, o.axioms(AxiomType.SUBCLASS_OF).count());

**Comment by ignazio1977** [comment]
Same input string reformatted to remove Java code and simplify reading. Please correct me if I've mistyped something.

    @prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
    @prefix owl:   <http://www.w3.org/2002/07/owl#> .
    @prefix x:     <http://argh#> .
    @prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .
    @prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
    
    x:P2 a owl:ObjectProperty .
    
    [ a owl:Axiom ;
      rdfs:comment "y" , "x" ;
      owl:annotatedProperty rdfs:subClassOf ;
      owl:annotatedSource [ a owl:Restriction ;
                            rdfs:subClassOf [ a owl:Restriction ;
                                              owl:onProperty x:P1 ;
                                              owl:someValuesFrom x:C
                                            ] ;
                            owl:hasValue x:I ;
                            owl:onProperty x:P1
                          ] ;
      owl:annotatedTarget [ a owl:Restriction ;
                            owl:onProperty x:P2 ;
                            owl:someValuesFrom x:C
                          ]
    ] .
    
    x:I a owl:NamedIndividual .
    x:P1 a owl:ObjectProperty .
    x:C a owl:Class .

**Comment by ignazio1977** [comment]
Eyeball parsing makes me expect *two* subclass axioms here, there are two `rdfs:subClassOf` appearances and their objects are different. Haven't tried running the code yet.

In the OWL mapping to RDF, it's not possible to nest `rdfs:subClassOf` inside another expression - it always creates its own axiom, in this case a GCI `SubClassOf(hasValue P1 {I}, some P1 C)`. Syntax from memory so I might be off. The other axiom looks to be another GCI `SubClassOf(hasValue P1 {I}, some P2 C)` annotated with two comments, "x" and "y".

**Comment by sszuev** [comment]
CTRL-F shows me there are two `rdfs:subClassOf`, correct? 
One - in the predicate position, and the another one - the object position. 
The place where it is predicate - is a regular `SubClassOf` Axiom with two anonymous class expressions as subject and object.
The other place - is a part of reification from the top-level `owl:Axiom` annotation.

So, there is only one `rdfs:subClassOf` axiom, right?

There is a specification for it: https://www.w3.org/TR/owl2-mapping-to-rdf/#Translation_of_Annotations.

**Comment by ignazio1977** [comment]
> So, there is only one rdfs:subClassOf axiom, right?

I don't think so. If these are the same `rdfs:subClassOf`, the object must be the same for both, right? If there is one SPO, O is only one expression. In the graph, the second textual appearance has an object containing `owl:onProperty x:P1` and the first has an object containing `owl:onProperty x:P2` (referenced in the `annotationTarget` section).

In the graph:

    @prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
    @prefix owl:   <http://www.w3.org/2002/07/owl#> .
    @prefix x:     <http://argh#> .
    @prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .
    @prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
    
    x:P2 a owl:ObjectProperty .
    
    [ a owl:Axiom ;
      rdfs:comment "y" , "x" ;
      owl:annotatedProperty rdfs:subClassOf ;
                                             ^^^^ first appearance
      owl:annotatedSource [ a owl:Restriction ;
                            rdfs:subClassOf [ a owl:Restriction ;
                           ^^^^ second appearance
                                              owl:onProperty x:P1 ;
                                              ^^^^ Object with P1
                                              owl:someValuesFrom x:C
                                            ] ;
                            owl:hasValue x:I ;
                            owl:onProperty x:P1
                          ] ;
      owl:annotatedTarget [ a owl:Restriction ;
                            owl:onProperty x:P2 ;
                            ^^^^ Object with P2
                            owl:someValuesFrom x:C
                          ]
    ] .
    
    x:I a owl:NamedIndividual .
    x:P1 a owl:ObjectProperty .
    x:C a owl:Class .

Unless I've missed something, I'm not sure how those two would be the same.

**Comment by sszuev** [comment]
Do you see two statements `_:b0 rdfs:subClassOf _:b1`?

**Comment by ignazio1977** [comment]
Changing the object with P2 to be object with P1, I get one subclass axiom and your test passes. And that makes sense to me because then there is in fact only one axiom described here.

**Comment by sszuev** [comment]
Yes. exactly. Great, you understand this.
So, no bug, right?

**Comment by ignazio1977** [comment]
> Yes. exactly. Great, you understand this.
> So, no bug, right?

Mate, patronise someone else.

Have you read my comment? TEST PASSES AFTER CHANGING YOUR INPUT.

**Comment by ignazio1977** [comment]
You put two axioms in there and expected to see one. I pointed out where the second axiom is. Am I wrong there? Please elaborate.

**Comment by sszuev** [comment]
> You put two axioms in there and expected to see one. I pointed out where the second axiom is. Am I wrong there? Please elaborate.

Yes, you are not right.
There is only one `_:b0 rdfs:subClassOf _:b1` statement => must be only one axiom.
The second statement `_:bx owl:annotatedProperty rdfs:subClassOf` -  is a part of annotation.
Here, the `rdfs:subClassOf` is not even in predicate position. Or what? I add more statements like `a b rdfs:subClassOf`, `rdfs:subClassOf b c`, etc - and OWL-API will treat all of them as `SubClassOf` axioms,?

Why do you think, that a bug is a problem for who started it? 
I expect OWL-API will see only the one axiom, nothing more, nothing less.
Moreover, I created a self-sufficient testcase, with all expectation right in code.
This is just one more demonstration for #874 
One more attempt to make you understand.
If b-node, there would not be the place for such error.
 
Or, in OWL-API, broken data is not a case?

**Comment by sszuev** [comment]
Sorry, the bug-title is not fully correct. Should be something like 'Wrong axioms when the RDF is also wrong and contains nonexistent reference in annotation'.  
If there is a principle that OWL-API is not obliged to work correctly with anything, that has not been produced by OWL-API itself, then the issue can be closed. As any other issue, where the data is not produced by OWL-API itself.

**Comment by sszuev** [comment]
If I was too rude somehow, I apologize, it is not a personal attack.

**Comment by ignazio1977** [comment]
> There is only one _:b0 rdfs:subClassOf _:b1 statement => must be only one axiom.
The second statement _:bx owl:annotatedProperty rdfs:subClassOf - is a part of annotation.
Here, the rdfs:subClassOf is not even in predicate position. Or what? I add more statements like a b rdfs:subClassOf, rdfs:subClassOf b c, etc - and OWL-API will treat all of them as SubClassOf axioms,?

Sorry, no. That is the reification of an axiom, whose purpose is to provide the RDF with a place to hang the annotations. And it is an axiom with a different object than the one included in the subject section. Ergo, there are two axioms there, according to the OWL mapping specs.

Reification of the axiom does not remove it from the ontology. It's easier to see when the subject and object are not expressions; there's such an example in the specs themselves in section https://www.w3.org/TR/owl2-mapping-to-rdf/#Translation_of_Annotations

**Comment by ignazio1977** [comment]
> If there is a principle that OWL-API is not obliged to work correctly with anything, that has not been produced by OWL-API itself, then the issue can be closed. As any other issue about RDF -> OWL mapping.

The principle is that if the input conforms to the specs OWLAPI should parse it and produce the expected ontology; if the input does not conform to the spec, OWLAPI will look at the configuration provided and, if the configuration specifies strict parsing, throw an exception; otherwise, attempt to parse the ontology as best it can (because there are ontologies in common use that are syntactically wrong, either because they were produced by bogus versions of OWLAPI or for other reasons - hand editing being a common cause of errors).

**Comment by sszuev** [comment]
> Sorry, no. That is the reification of an axiom, whose purpose is to provide the RDF with a place to hang the annotations. And it is an axiom with a different object than the one included in the subject section. Ergo, there are two axioms there, according to the OWL mapping specs.

Oh, really ?

Listen, mate.  I am tired. I've wasted a half of day in these discussions, for nothing. 
If you have a bad API (very, very bad, actually) and you want to leave it as it is - OK then. 
It's your choice. 
This issue - was just the last attempt. 
Refuse understanding - OK. Not my business.

No any new issues from me anymore. 
that was the last straw.

**Comment by ignazio1977** [comment]
Don't play the victim here.
