### ISSUE TITLE
Incomplete javadoc on OWLNaryAxiom#asPairwiseAxioms

### ISSUE THREAD

**Issue by sszuev** [owlcs/owlapi#884]
I.e. including the annotations of the base axiom.
This may be incorrect, since javadoc says:

> 
> Gets this axiom as a set of pairwise axioms. 
> Note that annotations on this axiom will not be copied to each axiom returned in the set of pairwise axioms.

So, I expected that for the axiom `EquivalentClasses(Annotation(rdfs:comment "X"^^xsd:string) <C> <D> )` there should be  `EquivalentClasses(<C> <D> )` in the pairwise `Set`, but got the same instance with `Annotation(rdfs:comment "X"^^xsd:string)` inside.

checked v 5.1.11

**Comment by ignazio1977** [comment]
The javadoc is incomplete. The purpose of splitting an n-ary axiom to pairs is (mainly) for serializations where axioms of arity 3 and above cannot be represented, and the annotations are not copied to avoid duplicating the annotations. The javadoc should say that, if there is no need to actually split the axiom, the return value will be equal to the initial axiom.
Returning the same instance in that case is economical, but I don't think it should be mandatory.
