### ISSUE TITLE
OWLNegativeObjectPropertyAssertionAxiom#containsAnonymousIndividuals misleading javadoc

### ISSUE THREAD

**Issue by sszuev** [owlcs/owlapi#885]
and the same for `OWLNegativeDataPropertyAssertionAxiom`.
The javadoc says:

> Determines whether this axiom contains anonymous individuals. Anonymous individuals are not allowed in negative object property assertions.

It seems it is not fully correct: 
- An anonymous individual can belong to the annotation, so even both parts of the axiom are named individuals, it still may contain anonymous individuals in its annotations
- And why it is not allowed? There is nothing about it in spec: https://www.w3.org/TR/owl2-syntax/#Negative_Object_Property_Assertions

**Comment by ignazio1977** [comment]
Not sure what the history of that comment is. It has existed in that form since 2009, but as far as I can tell at no point OWL 2 proposed to reserve those axioms for named individuals. And, obviously, if the axiom cannot have anonymous individuals, the method is pointless.
