### ISSUE TITLE
read and display a local .owl extension file

### ISSUE THREAD

**Issue by gayathri13990** [owlcs/owlapi#886]
I am new to owl-api. I tried to load owl api file using maven project in eclipse and i go t some output running as java application. Now i converted the same maven project to dynamic web application. Now i am trying to display the owl files content in server. But i don't know how to.
The below is the code which i tried by myself. I got the error

> Type Status Report
> Message /home/gayathri/eclipse-workspace/HelloMaven/src/main/java/com/gayathri/HelloMaven/App.java
> Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

`    
     

     <input type="submit" value="Login" />

     <form name="loginForm" method="post" action="App.java">

     @WebServlet("App")

     public class App extends HttpServlet {

     protected void doPost(HttpServletRequest request,
     HttpServletResponse response) throws ServletException, IOException {

    OWLOntologyManager man = OWLManager.createOWLOntologyManager();
    File file = new File("/home/gayathri/eclipse-workspace/steels2.owl");
    //OWLOntology o = null;
    try {
        OWLOntology o = man.loadOntologyFromOntologyDocument(file);
        //System.out.println("username: " + o);
        PrintWriter writer = response.getWriter();
        writer.println(o);
    } catch (OWLOntologyCreationException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    }
    }
    }`

Please help me where i am worng or what else i have to do

**Comment by ignazio1977** [comment]
The error you mention is your application server not wishing to provide information on an error that has happened, for security reasons. From this we cannot tell whether the problem is in the application server configuration, in OWLAPI or in your code snippet.

The code itself looks fine, but you'll have to check any app server logs to find what the actual issue is.

**Comment by gayathri13990** [comment]
My app is not creating the classes folder.The following is my project structure.  I couldn't even able to print a hello  world.
![stru](https://user-images.githubusercontent.com/9986081/66981571-bd85bb80-f0d1-11e9-8f5d-3e5b6d25ef67.png)

**Comment by ignazio1977** [comment]
> java.lang.ClassNotFoundException: com.gayathri.HelloMaven.App

That confirms the problem is not in your use of OWLAPI. It seems your code is not getting compiled and deployed as a servlet at all.

**Comment by gayathri13990** [comment]
Yes now it got compiled properly and now I am getting the following error.

> java.lang.NoClassDefFoundError: org/semanticweb/owlapi/apibinding/OWLManager

Is it missing any jar files?

**Comment by gayathri13990** [comment]
I have created a dynamic web project. So there is no pom.xml file. Should i need add the dependencies manually? If so please tell me what are all the jar files i have to add in my build path.

**Comment by ignazio1977** [comment]
The list is too long. Download a release from https://github.com/owlcs/releases and extract its contents in the lib folder of your project.

**Comment by gayathri13990** [comment]
Should i copy all the folder contents to my lib folder?

**Comment by gayathri13990** [comment]
I just copied all jar and zip files from 3 folders and pasted in my lib folder. Still i am getting the error message 

> java.lang.NoClassDefFoundError: javax/inject/Provider

> /home/gayathri/eclipse-workspace/Newwebapp/WebContent/WEB-INF/lib/javax-inject.jar
> /home/gayathri/eclipse-workspace/Newwebapp/WebContent/WEB-INF/lib/javax-inject-  1.0-201002241208.jar

I have these two jar files for javax.


Is converting maven project to dynamic web app and creating dynamic web project both are same or different?

**Comment by gayathri13990** [comment]
`java.lang.ClassNotFoundException: uk.ac.manchester.cs.owl.owlapi.concurrent.Concurrency`
I have added the required libraries to my class path too. Still what it is searching for?

**Comment by gayathri13990** [comment]
I have added the required library files and the error is gone. Now I am trying to load ontology and its giving the following error. ** I am getting java.io.FileNotFoundException: in which i have specified the full path to the file File file = new File("/home/gayathri/eclipse-workspace/steels2.owl");** 
Complete error

**java.io.FileNotFoundException: steels2.owl (No such file or directory)
    java.io.FileInputStream.open0(Native Method)
    java.io.FileInputStream.open(FileInputStream.java:195)
    java.io.FileInputStream.<init>(FileInputStream.java:138)
    org.semanticweb.owlapi.io.FileDocumentSource.getInputStream(FileDocumentSource.java:87)
    org.semanticweb.owlapi.io.FileDocumentSource.getReader(FileDocumentSource.java:102)
    org.semanticweb.owlapi.io.AbstractOWLParser.getInputSource(AbstractOWLParser.java:257)
    org.coode.owlapi.rdfxml.parser.RDFXMLParser.parse(RDFXMLParser.java:116)
    uk.ac.manchester.cs.owl.owlapi.ParsableOWLOntologyFactory.loadOWLOntology(ParsableOWLOntologyFactory.java:212)
    uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:866)
    uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:805)
    uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:820)
    com.gayathri.App.doPost(App.java:60)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
    org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)**

**Comment by gayathri13990** [comment]
Thanks @ignazio1977  I gave the absolute path to the file and now it works fine. Following is my code. And i am getting output like 

> Hello World!!Ontology(OntologyID(OntologyIRI(<http://www.w3.org/2002/07/SteelOnto>) VersionIRI(<http://www.w3.org/2002/07/SteelOntov0>))) [Axioms: 461 Logical Axioms: 353]

`OWLOntologyManager man = OWLManager.createOWLOntologyManager();
	   File file = new File("/home/gayathri/eclipse-workspace/Newwebapp/src/com/gayathri/steels2.owl");
	  // resp.getWriter().write("Hello World!!!!!!"+file);
	   OWLOntology o;
	   try {
		o=man.loadOntologyFromOntologyDocument(file);
		resp.getWriter().write("Hello World!!"+o);
	} catch (OWLOntologyCreationException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}`

I want the output in webpage. Like how the `.owl` files will display in webpage. Hope u got my question

**Comment by gayathri13990** [comment]
[https://protege.stanford.edu/ontologies/pizza/pizza.owl](url) separately when i open owl file it will open in browser like xml page. But when i open the [http://www.co-ode.org/ontologies/pizza/pizza.owl](url) page it is displaying webpage content. Can we able to display either of the output? Instead of this.

> !Ontology(OntologyID(OntologyIRI(http://www.w3.org/2002/07/SteelOnto) VersionIRI(http://www.w3.org/2002/07/SteelOntov0))) [Axioms: 461 Logical Axioms: 353]

**Comment by gayathri13990** [comment]
sorry my question is wrong. Can you please tell me how to list those axioms?

**Comment by gayathri13990** [comment]
I want to list the **Axioms: 461 Logical Axioms: 353**. Ist it possible to do? If so please tell me how will i list what are all the axioms present.

**Comment by ignazio1977** [comment]
- Number of axioms can be obtained with `o.getAxiomCount()`
- Number of logical axioms can be obtained with `o.getLogicalAxiomCount()`
- All axioms can be obtained via `o.axioms()` as a stream. You can print them with the` .toString()` method, unless you wish for a specific format to be used, in which case you can use (example here is functional syntax):

        StringDocumentTarget target = new StringDocumentTarget();
        o.saveOntology(new FunctionalSyntaxDocumentFormat(), target);
        target.toString() // string representation

**Comment by gayathri13990** [comment]
Will the above syntax list the 461 axioms? I tried with above syntax and its displaying an empty page.

**Comment by gayathri13990** [comment]
I want to display all the 461 axioms and also remove/add.

**Comment by ignazio1977** [comment]
The code just creates a string with the data. Did you add the string to your page?

**Comment by gayathri13990** [comment]
To the `.owl` file i have to create add the string?

**Comment by ignazio1977** [comment]
No, to the page you wish to display.

**Comment by gayathri13990** [comment]
I added the following line to my code and printed the output. `o.getAxioms();` FOllowing is my output

> <http://www.w3.org/2002/07/SteelOnto#BinaryAlloys>
>  <http://www.w3.org/2002/07/SteelOnto#FebasedAlloys>
>  <http://www.w3.org/2002/07/SteelOnto#AlloyClassifications><http://www.w3.org/2002/07/SteelOnto#ElementSymbol>

I couldn't understand where to create add string.

**Comment by gayathri13990** [comment]
Can you please tell me what exactly is an axiom and how it will look like.

**Comment by gayathri13990** [comment]
will it display something like `ClassAssertion(<http://www.w3.org/2002/07/SteelOnto#FebasedAlloys>` followed by `ObjectPropertyAssertion ,Declaration and DataPropertyDomain`.

**Comment by ignazio1977** [comment]
The problem here is not OWLAPI but how to output text in a jsp page.

You have already done so in your code:

    resp.getWriter().write("Hello World!!"+o);

Instead of passing `o` to this method, put here the `target.toString()` from my example.

**Comment by gayathri13990** [comment]
I tried adding the code. Its throwing the following error.

> java.lang.ClassCastException: uk.ac.manchester.cs.owl.owlapi.OWLOntologyImpl cannot be cast to org.semanticweb.owlapi.model.OWLOntologyManager

`StringDocumentTarget target = new StringDocumentTarget();
		
		  try {
			  ((OWLOntologyManager) o).saveOntology((OWLOntology) new FunctionalSyntaxDocumentFormat(), target);
			  } catch (OWLOntologyStorageException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		resp.getWriter().write("Hello World!!"+target.toString());`

**Comment by gayathri13990** [comment]
As the code `  o.saveOntology(new FunctionalSyntaxDocumentFormat(), target);` throws error message, I edited the code `((OWLOntologyManager) o).saveOntology((OWLOntology) new FunctionalSyntaxDocumentFormat(), target);`

**Comment by ignazio1977** [comment]
Why are you casting the ontology to an ontology manager? The ontology manager is already in your code and it's called `man`.

**Comment by gayathri13990** [comment]
So instead of  `o.saveOntology(new FunctionalSyntaxDocumentFormat(), target);` should i give `man.saveOntology(new FunctionalSyntaxDocumentFormat(), target);`?
Still its giving me the following error. 

> The method saveOntology(OWLOntology, IRI) in the type OWLOntologyManager is not applicable for the arguments (FunctionalSyntaxDocumentFormat, StringDocumentTarget)

**Comment by gayathri13990** [comment]
Please explain me what this piece of code is doing `o.saveOntology(new FunctionalSyntaxDocumentFormat(), target);`. Also do i need to do any changes in this line as its throwing the errors.

> java.lang.ClassCastException: uk.ac.manchester.cs.owl.owlapi.OWLOntologyImpl cannot be cast to org.semanticweb.owlapi.model.OWLOntologyManager

> The method saveOntology(OWLOntology, IRI) in the type OWLOntologyManager is not applicable for the arguments (FunctionalSyntaxDocumentFormat, StringDocumentTarget)

**Comment by ignazio1977** [comment]
You're confusing compile time errors and runtime errors.

Go back to my example, there's no manager and no cast involved. The manager is used only to load the ontology.

I assume you're using owlapi 5.

**Comment by gayathri13990** [comment]
Yes I am using owlapi 5. For owlapi 5 do i need to do any modifications?

**Comment by gayathri13990** [comment]
Will the code modified for version5?

**Comment by gayathri13990** [comment]
Can you please tell me what is the changes should i do for owlapi version 5?

**Comment by ignazio1977** [comment]
You're not trying.

My comment earlier:

> The problem here is not OWLAPI but how to output text in a jsp page.

>You have already done so in your code:

> resp.getWriter().write("Hello World!!"+o);
Instead of passing o to this method, put here the target.toString() from my example.


You've not tried this code, because it would have worked.

We cannot do the basic plumbing for you.

**Comment by gayathri13990** [comment]
I tried the code. I am just posting the error file here
![err2](https://user-images.githubusercontent.com/9986081/67468746-abbf8d80-f668-11e9-97e2-0565509b0a4b.png) This is what i am getting

**Comment by gayathri13990** [comment]
As you told earlier that i have put the output text in a jsp page

    resp.getWriter().write("Hello World!!"+target.toString());
I added the above line too. I have posted the image that i have tried your code.

**Comment by gayathri13990** [comment]
I am not doing it in jsp page. Sorry for my wrong question. I have created a new dynamic web project. i want to display the axioms list in the web page.

**Comment by ignazio1977** [comment]
What dies the compilation error say? Not the IDE suggestion - casting has nothing to do here.

**Comment by gayathri13990** [comment]
Pasting the error message for you reference.

> HTTP Status 500 – Internal Server Error

Type Exception Report

Message Servlet execution threw an exception

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

javax.servlet.ServletException: Servlet execution threw an exception
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
Root Cause

java.lang.Error: Unresolved compilation problem: 
	The method saveOntology(FunctionalSyntaxDocumentFormat, StringDocumentTarget) is undefined for the type OWLOntology

	com.gayathri.App.doPost(App.java:45)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
Note The full stack trace of the root cause is available in the server logs.

**Comment by gayathri13990** [comment]
`StringDocumentTarget target = new StringDocumentTarget();
		  o.saveOntology(new FunctionalSyntaxDocumentFormat(), target); //line 45
		 	resp.getWriter().write("Hello World!!"+target.toString());`

**Comment by ignazio1977** [comment]
That code is correct for owlapi 5. Make sure you have only one version of the owlapi jars in your project.

**Comment by gayathri13990** [comment]
The following are the jar present under web app libraries. **owlapi-api-3.5.6.jar, owlapi-api-5.1.5.jar, owlapi-apibinding-3.5.6.jar, owlapi-impl-3.5.6.jar, owlapi-oboformat-3.5.6.jar, owlapi-parsers-3.5.6.jar, owlapi-tools-3.5.6.jar** Should i remove the version 3.5 related jars or shall i remove version 5 from my path?

**Comment by gayathri13990** [comment]
One more from /.m2/repository/net/sourceforge/owlapi/owlapi-apibinding/5.0.0/owlapi-apibinding-5.0.0.jar. The previous comment jar files are present in my lib folder. Which jar should i keep and which one should i delete. Please tell me

**Comment by gayathri13990** [comment]
No zip file in the name owlapi-5.1.12 is there only owlapi-dependencypack-5.1.12.jar is there in the releases which you mentioned earlier

**Comment by gayathri13990** [comment]
Please add the zip file for owlapi-5.1.12.

**Comment by ignazio1977** [comment]
It has been uploaded as a jar file. Jar files are zipped files, all that changes is the extension.

**Comment by gayathri13990** [comment]
Thanks. I have extracted the files from 5.1.12 and copied to my lib folder. I got the following error message.

> HTTP Status 500 – Internal Server Error

Type Exception Report

Message Servlet execution threw an exception

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

javax.servlet.ServletException: Servlet execution threw an exception
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
Root Cause

java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	org.semanticweb.owlapi.utilities.Injector.<clinit>(Injector.java:43)
	org.semanticweb.owlapi.apibinding.OWLManager.<clinit>(OWLManager.java:101)
	com.gayathri.App.doPost(App.java:38)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
Root Cause

java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1360)
	org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1182)
	org.semanticweb.owlapi.utilities.Injector.<clinit>(Injector.java:43)
	org.semanticweb.owlapi.apibinding.OWLManager.<clinit>(OWLManager.java:101)
	com.gayathri.App.doPost(App.java:38)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
Note The full stack trace of the root cause is available in the server logs.

**Comment by gayathri13990** [comment]
I guess i am missing some other jar files. Am i correct?

**Comment by gayathri13990** [comment]
I am not sure. Its just my guess that i am missing slf4j-api jar file. Which version should i take?

**Comment by ignazio1977** [comment]
The purpose of the dependency pack archive is to put all jars required by owlapi in one place.

**Comment by gayathri13990** [comment]
Please suggest me a documentation with syntax for learning the owl.

**Comment by gayathri13990** [comment]
Thanks @ignazio1977 for the help.  I am just getting the raw output of the owl file. I want to show them as triplets and remove the uris. How will i do this?

**Comment by ignazio1977** [comment]
Can you show an example of the desired output? I'm not clear on what you mean by triplets without uris.

**Comment by gayathri13990** [comment]
I am attaching file for your reference. 
[output.txt](https://github.com/owlcs/owlapi/files/3787264/output.txt)

 But, what I want is like this:
 >  [('wine', 'hasColor', 'red'), ...]

**Comment by gayathri13990** [comment]
[http://owlready.8326.n8.nabble.com/Extract-the-triples-from-the-existed-owl-file-td511.html](url)
I want the output like displaying in above url

**Comment by gayathri13990** [comment]
I am getting the output in the following format.
[output.txt](https://github.com/owlcs/owlapi/files/3788334/output.txt)

**Comment by ignazio1977** [comment]
The format mentioned in the link is N-Triples, which is available in the OWLAPI. But it's not a prefixed format, so you might have to do some string work yourself.

    o.saveOntology(new NTriplesDocumentFormat(), target)


NTriples looks something like this:

    <http://www.semanticweb.org/owlapi/test/Ont> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2002/07/owl#Ontology> .
    # http://www.semanticweb.org/owlapi/test#prop
    <http://www.semanticweb.org/owlapi/test#prop> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2002/07/owl#AnnotationProperty> .
    # http://www.semanticweb.org/owlapi/test#prop2
    <http://www.semanticweb.org/owlapi/test#prop2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2002/07/owl#AnnotationProperty> .
    # http://www.semanticweb.org/owlapi/test#A
    <http://www.semanticweb.org/owlapi/test#A> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2002/07/owl#NamedIndividual> .
    # http://www.semanticweb.org/owlapi/test#B
    <http://www.semanticweb.org/owlapi/test#B> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2002/07/owl#NamedIndividual> .
    # http://www.semanticweb.org/owlapi/test#C
<http://www.semanticweb.org/owlapi/test#C> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2002/07/owl#NamedIndividual> .

To strip this down to `(C type NamedIndividual)` and similar triples you'll need some kind of regexp find and replace.

    target.toString().replaceAll("> <[\\w\\.\\:/\\-]+\\#", " ").replaceAll("\R<[\\w\\.\\:/\\-]+\\#", "\R(").replace("> .", ")");

This should sort of do the job, but you'll have to tweak it to your needs.

**Comment by gayathri13990** [comment]
when i try to replace the special characters, nothing the code is doing. I guess it might be because the target is StringDocumentTarget not the String like **String text = "This - word ! has \\ /allot # of % special % characters";
text = text.replaceAll("[^a-zA-Z0-9]", "");
System.out.println(text);** this. So the replace code is not working. Should i convert StringDocumentTarget to string? or both StringDocumentTarget and String are same?

**Comment by ignazio1977** [comment]
I point you at my code again.

    target.toString()

It is already turning the target into a string containing the ntriples format. I thought we had this bit sorted?

**Comment by ignazio1977** [comment]
As I said, the last part requires trying various regular expressions to change the string, after the output has been changed to ntriples. I can't help with that part, owlapi does not support ntriples without IRIs.

Skip the regular expressions and check that the output you get looks like triplets. Then you can work on refining the look to match your criteria.

**Comment by gayathri13990** [comment]
I am getting the output in following format.
[output.txt](https://github.com/owlcs/owlapi/files/3793162/output.txt)

**Comment by gayathri13990** [comment]
Can you please tell me how the triplets will look like from my output.text? Or please show me an example how triplets will look like. I haven't read about this before.

**Comment by gayathri13990** [comment]
Will the triplets look like **alloyAlsoKnownAs type ObjectProperty**?

**Comment by gayathri13990** [comment]
> Skip the regular expressions and check that the output you get looks like triplets. Then you can work on refining the look to match your criteria.


As u mentioned in the comment how the triplets will look. please tell me. I don't have any idea of what is triplets and how it will look like.

**Comment by gayathri13990** [comment]
I am attaching file for your reference. Please let me know whether the extracted out
[triplets.txt](https://github.com/owlcs/owlapi/files/3807415/triplets.txt)
put is triplet.

**Comment by gayathri13990** [comment]
@ignazio1977 Please help me with this. I have loaded the owl file. Now i want to display them as hyperlinks removing uri's. howto do this. Please hepl me.

**Comment by matentzn** [comment]
What you are asking is completely unrelated to the OWL API. I don't want to speak for @ignazio1977 but just from my perspective: Our time as open-source developers is very, very limited. The whole community is dependent on @ignazio1977 and his work; what you are asking in terms of support goes too far. Please get yourself some books on text processing. The issue tracker here is not a helpdesk; it is a tracker for bugs and feature requests.

**Comment by ignazio1977** [comment]
@gayathri13990 
>  I don't have any idea of what is triplets and how it will look like.

Sorry but this means neither you nor I know what you're after.
You've said you want your output to be triplets, plus some additional formatting. I've asked what you mean by triplets - because, in OWL, the closest concept, linguistically, is RDF triples.

Your example was what owlready2 calls N-Triples, however that does not match the N-Triples format OWLAPI supports. Structurally, they're relatively similar - (subject, predicate, object).

I added a small example of what OWLAPI NTriples looks like, but I cannot help further in manipulating the strings because it's not clear, to me or you, what your objective is. You're asking us to tell you what triplets are, but that's what we asked you. We won't get a good answer this way.

**Comment by gayathri13990** [comment]
Thanks for the reply @ignazio1977 . I am very new to this owl api concept that i couldn't understand anything. My expected output will be in the following format. 
`AusteniticStainlessSteels --Class(link) clicking the link displays the following subclass links.
Alloys --subclass(link)---(some properties)
StainlessSteels --subclass(link)---(some properties)
Steels --subclass(link)---(some properties)`

 The above output's code from the owl file is 
`
 
    <owl:Class rdf:about="http://www.semanticweb.org//ontologies/2016/8/untitled-ontology-34#AusteniticStainlessSteels">
        <rdfs:subClassOf rdf:resource="http://www.semanticweb.org//ontologies/2016/8/untitled-ontology-34#Alloys"/>
        <rdfs:subClassOf rdf:resource="http://www.semanticweb.org//ontologies/2016/8/untitled-ontology-34#StainlessSteels"/>
        <rdfs:subClassOf rdf:resource="http://www.semanticweb.org//ontologies/2016/8/untitled-ontology-34#Steels"/>
        <rdfs:subClassOf rdf:resource="http://www.w3.org/2002/07/SteelOnto#AlloyClassifications"/>
    </owl:Class>`

**Comment by gayathri13990** [comment]
The steels2.owl file have some hyperlinks which will display the class link and when clicking class link it goes to the sub class links and the sub class links will contain the properties of the element.
**AusteniticStainlessSteels --Class(link)
Alloys --subclass(link)---(some properties)
StainlessSteels --subclass(link)---(some properties)
Steels --subclass(link)---(some properties)** Hope i am clear

**Comment by gayathri13990** [comment]
I want the same as RDF triples not the owlready2's Ntriplets.

**Comment by gayathri13990** [comment]
I used your previous code 
`StringDocumentTarget target = new StringDocumentTarget();
  o.saveOntology(new FunctionalSyntaxDocumentFormat(), target);`
And removed special characters from the uri's in my owl file. I am getting the output. But each element is getting printed twice.  Even though one is commented its printing twice. What should i do to get them print once.

`

    <Class rdf:about="http://www.w3.org/2002/07/SteelOnto#BinaryAlloys">`

**Comment by gayathri13990** [comment]
I have uploaded the owl file in .txt extension for your reference. Please help me in how to display them as tiplets(RDF triples.). Same like pizza.owl i am trying to extract in my owl file. 
[steels2.txt](https://github.com/owlcs/owlapi/files/3820188/steels2.txt)

**Comment by ignazio1977** [comment]
> But each element is getting printed twice. Even though one is commented its printing twice. What should i do to get them print once.
>
>     
>     <Class rdf:about="http://www.w3.org/2002/07/SteelOnto#BinaryAlloys">


The comments are in the original XML file. The easiest way to strip them all is to load the file as XML, remove all comment nodes and save again, If your ontology won't change you can do this by hand too. This is plain XML manipulation, nothing specific to OWLAPI.

**Comment by gayathri13990** [comment]
Using the following code i somehow managed to print the classes alone.

`File file =new File("/home/gayathri/eclipse-workspace/Newwebapp/src/com/gayathri/steels2.owl");
	   OWLOntology o;
	   
	   try {
		   o = man.createOntology();
		   o=man.loadOntologyFromOntologyDocument(file);
		   StringDocumentTarget target = new StringDocumentTarget();
		   o.saveOntology(new FunctionalSyntaxDocumentFormat(), target);
		  // target.toString(); // string representation
		   //System.out.println(target.toString());
		   Stream<OWLAxiom> axioms = o.axioms();
		   Set<OWLClass> classes = o.getClassesInSignature(); // List classes
		   for (OWLClass cls : classes) {
               System.out.println(cls.getIRI().getShortForm());

               resp.getWriter().write(cls.getIRI().getShortForm()+'\n');
		   }`

But Its getting printed as string. I want it to display in URI. Please help me with this how to display the classes in uri.

**Comment by ignazio1977** [comment]
> I want it to display in URI. Please help me with this how to display the classes in uri.

URI is a special case of IRI. With that in mind, all you need to do is not call `getShortForm()`

    resp.getWriter().write(cls.getIRI()+'\n');


However, please review your code, because it is littered with unnecessary operations. The same effect can be reached with:

	   o = man.loadOntologyFromOntologyDocument(file);
	   Set<OWLClass> classes = o.getClassesInSignature();
	   for (OWLClass cls : classes) {
               resp.getWriter().write(cls.getIRI()+'\n');
	   }

**Comment by gayathri13990** [comment]
I guess i am not explaining properly. I want the IRI's(classes) in short form as link which will point to the IRI's(subclasses)

**Comment by gayathri13990** [comment]
The classes will display something like html link kind off. Is it possible?

**Comment by gayathri13990** [comment]
Please check the link there is a Protege screenshot. Like that i want to display them in web as classes-->subclass-->individuals-->properties like that 

[https://tutorial-academy.com/owlapi-5-read-class-restriction-axiom-visitor/]Protege screenshot

**Comment by ignazio1977** [comment]
> The classes will display something like html link kind off. Is it possible?

Of course it's possible. Let me break this down.

    String uri = cls.getIRI().toString(); // the URI of the class
    String shortForm = cls.getIRI().getshortForm(); // the short form

You can compose them as you wish, but we cannot writhe the HTML for you.

**Comment by gayathri13990** [comment]
I am asking you to write the html for me. But i am asking you to help me in how the syntax will be or how the format will look like. So that using the syntax or something i can able to write my own code. Is there any specific syntax?

**Comment by gayathri13990** [comment]
Like for listing classes as hyperlinks some syntax or code format will be there na.

**Comment by ignazio1977** [comment]
OWLAPI does not have code that creates HTML hyperlinks.

The basic syntax for hyperlinks can be found here https://www.w3schools.com/tags/tag_a.asp

**Comment by gayathri13990** [comment]
One more thing. Is it so that I should add  `<a href="https://www.w3schools.com">Visit W3Schools.com!</a> ` where i am printing classes?

**Comment by ignazio1977** [comment]
Yes. A HTML page is just text, and that's what you're writing on `resp.getWriter()`. I thought that was obvious from the start.

**Comment by gayathri13990** [comment]
Thank you so much. I am very new to the owl api stuff and java. That's why i am taking time to understand. So now i achieved the half of result i want to. Now i want to display the subclass and its general axiom. Also the object and data properties i want to display. So The same way how i list the class i should list the subclass on clicking the class url?
` Set<OWLClass> classes = o.getClassesInSignature();
		   
		   for (OWLClass cls : classes) {
			   String uri = cls.getIRI().toString();
			   String shortForm = cls.getIRI().getShortForm();
			   resp.setContentType("text/html");
			   PrintWriter out = resp.getWriter();
			   out.println("<li><a href="+uri+">"+shortForm+"</a></li>");
		   }`

**Comment by ignazio1977** [comment]
Yes. Read the javadoc and the wiki pages, plenty of examples on how to find axioms.

**Comment by gayathri13990** [comment]
I am not sure whether I am doing in a right way or not. I have included the following code.
`OWLDataFactory df = OWLManager.getOWLDataFactory();
	   OWLReasoner reasoner = new Reasoner.ReasonerFactory().createReasoner(o);
	   NodeSet<OWLClass> subClasses = reasoner.getSubClasses(df.getOWLThing(), true);` Do i need to add any jar files for reasoner? As I am getting error.
