### ISSUE TITLE
Allow gzipped imports

### ISSUE THREAD

**Issue by matentzn** [owlcs/owlapi#887]
Our ontologies are growing and growing, and we are hitting network delays and github filesize limits right left and center. Its amazing the OWLAPI allows reading gzips and zips; but: would it be possible to allow this:

```
Ontology(<http://test.owl>
Import(<http://purl.obolibrary.org/obo/chebi.owl.gz>)
)
```

This would be absolutely amazing, as we could basically deposit all our imports that exceed a certain size as gzips. Thanks!

**Comment by ignazio1977** [comment]
That's already possible with the existing code. If you have a list of IRIs used in imports and their corresponding gzipped version, code like the example below will load the import from the gzipped file.

There's nothing stopping modifying the ontologies to point directly at the zipped versions, but that will require modifying them, so you'd be able to do that to the ones you control but not third party ones,. The IRI mapper works no matter who controls the ontology.

        IRI iriToRedirect = IRI.create("http://test.org/koala.owl");
        IRI redirection = IRI
            .create("file:///Users/ignazio/workspace/owlapi5/contract/src/test/resources/koala.gz");
        m.getIRIMappers().add((OWLOntologyIRIMapper) ontologyIRI -> {
            if (iriToRedirect.equals(ontologyIRI)) {
                return redirection;
            }
            return ontologyIRI;
        });

**Comment by matentzn** [comment]
Maybe I am misunderstanding this. I did not really think about redirecting here; Basically I want this:

o1.owl --imports--> http://test.owl/o2.owl.gz

without any changes to any configuration (this should work in Protege, ROBOT, owltools, everywhere without needing to change their code bases); just that this works by default, regardless of whether there is a local redirect or not. Maybe I am misunderstanding what you are suggesting :P Sorry. One more time slower for the old folks.

**Comment by ignazio1977** [comment]
In that case all you need is the imports IRI to be the address of the gzipped file, no other code required.

**Comment by matentzn** [comment]
Maybe this is a version issue then. This is the ontology:

```
Prefix(:=<http://www.semanticweb.org/matentzn/ontologies/2019/9/untitled-ontology-907#>)
Prefix(owl:=<http://www.w3.org/2002/07/owl#>)
Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>)
Prefix(xml:=<http://www.w3.org/XML/1998/namespace>)
Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>)
Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>)


Ontology(<http://www.semanticweb.org/matentzn/ontologies/2019/9/untitled-ontology-907>
Import(<http://purl.obolibrary.org/obo/chebi.owl.gz>)

)
```

Try open it with Protege 5.5:

```
    INFO  21:24:17  Imported ontology document http://purl.obolibrary.org/obo/chebi.owl.gz was not resolved to any documents defined in the ontology catalog.
   INFO  21:24:17  URL connection input stream is compressed using gzip
   INFO  21:24:17  Failed to load imported ontology at http://purl.obolibrary.org/obo/chebi.owl.gz
   INFO  21:24:17  Finished loading file:/Users/matentzn/data/gzip_test.owl
```

Try opening it with ROBOT:

```
Could not load imported ontology: <http://purl.obolibrary.org/obo/chebi.owl.gz> Cause: Invalid byte 1 of 1-byte UTF-8 sequence.
```

Which OWL API version implements this feature? Is this only very recent?

**Comment by ignazio1977** [comment]
No, my example worked because it's a `file:` url. For remote IRIs, the file extension is harder to use for this purpose.

**Comment by matentzn** [comment]
I see; Any hope this could be realised somehow? :P Or is it very difficult?

**Comment by ignazio1977** [comment]
Should be doable, it's the reliability I'm worried about.

**Comment by matentzn** [comment]
Ok; thanks for considering it, and I won't make a fuss if you dismiss it after consideration! Thanks @ignazio1977

**Comment by ignazio1977** [comment]
Ok, funnily enough the code to do this exists already, but it was not being invoked because github is serving the file over a gzipped stream - which is useful in general, less so when returning a zipped file. But, given the input stream is gzipped, the code in OWLAPI was not bothering to check its content for gz or xs file format.

**Comment by matentzn** [comment]
You are the best man; which owl api versions will have this? 4,5,6? Just 5,6? I have not been paying close attention to new owl api releases recently; I guess this will go live at some point after Christmas?

**Comment by ignazio1977** [comment]
4, 5, 6. I have two or three bugs I want to fix before releasing, should be another week or two.

**Comment by matentzn** [comment]
Thanks a ton.
