### ISSUE TITLE
Serialization order follow up from #702

### ISSUE THREAD

**Issue by ignazio1977** [owlcs/owlapi#888]
Yes, this is from https://github.com/FoodOntology/foodon/, which takes in terms from other ontologies, and adds synonymy etc.  It is in foodon-edit.owl , line 162058 of https://github.com/FoodOntology/foodon/commit/b5de9749996553ed536c79059485938e6431cc71#diff-3ba569ce430a37139d3278d6a229f662 . This file is only adjusted by protege.

>    <rdf:Description rdf:about="http://purl.obolibrary.org/obo/UBERON_0008979">
> `This line`
>`     <oboInOwl:hasExactSynonym xml:lang="en">dead body</oboInOwl:hasExactSynonym>`
    <obo:IAO_0000117 xml:lang="en">Gregory Harhay</obo:IAO_0000117>
> `should be here`
> `   <oboInOwl:hasExactSynonym xml:lang="en">dead body</oboInOwl:hasExactSynonym>`
    <oboInOwl:hasExactSynonym xml:lang="en">cadaver</oboInOwl:hasExactSynonym>
    <oboInOwl:hasExactSynonym xml:lang="en">corpse</oboInOwl:hasExactSynonym>
    </rdf:Description>

_Originally posted by @ddooley in https://github.com/owlcs/owlapi/issues/702#issuecomment-521405037_

**Comment by ignazio1977** [comment]
No longer happening in the latest code

**Comment by ddooley** [comment]
Could you let me know which version of OWLAPI that was resolved in roughly?  The effect is still in protege not surprisingly, but also in robot, so I'll be advocating that they upgrade if possible. Its playing havoc with commit diffs.

**Comment by ignazio1977** [comment]
@ddooley hard to tell, I never managed to reproduce the issue and it's been three years since it was raised.

If you have commits with order based differences, it would be useful if you can point me at them. It's very difficult to tell if there are still bugs to fix without examples of misbehaviour.

**Comment by ddooley** [comment]
I was assuming that it was just apps downstream of OWLAPI that might be using old versions, so coming at it from that angle.  So it is appearing in Protege 5.5 (OWL API 4.5.9) and in Robot v 1.7.0-SNAPSHOT (OWLAPI 4.5.6) , and occurring only in rdf:Description as far as I can tell, with numerous cases where foodon-edit.owl is saved straight from Protege: 

https://github.com/FoodOntology/foodon/commit/3ae64f63132b69feee6ecc840fa18e4c7a654a29
and
https://github.com/FoodOntology/foodon/commit/280529637ac4fca45acef4e6d67df9df84fca3a3
and
https://github.com/FoodOntology/foodon/commit/e6d58aaa04a8f351df78372c41702de8727ee1da
