### ISSUE TITLE
A possibility to merge ONT-API codebase into this repo.

### ISSUE THREAD

**Issue by sszuev** [owlcs/owlapi#889]
[ONT-API](https://github.com/avicomp/ont-api) - is a jena-based OWL-API impl with extended functionality.
It also has a different performance and memory consumption, which in some cases are better than the default implementation offers (see [OWLv5111vsONTv143-SNAPSHOT.14102019-(trunk).txt](https://github.com/owlcs/owlapi/files/3746573/OWLv5111vsONTv143-SNAPSHOT.14102019-.trunk.txt)).

Now the domain 'avicomp' is not quite approachable, so I'd like to move codebase somewhere, to keep the project alive.
And moving ONTAPI as submodule of OWLAPI might be a good idea.
At least OWLAPI clients would appreciate this feature.
In this sense, this issue is a continuation of the issue https://github.com/owlcs/owlapi/issues/340

On the other hand, ONT-API does not fully fit the principles of OWLAPI, since it is designed as independent API.
In the sense of project's maintaining, it would be more convenient to have ONTAPI separately.

This is the question, and I need to choose the better solution.
What do you think about this?

**Comment by ignazio1977** [comment]
One possibility, to keep the separation while also showing the relation between the two, is to have ONTAPI as a project in the OWLCS organisation. The projects currently hosted there are already independently managed by different people, many working in separate organisations, so in that respect ONTAPI would maintain autonomy. If I recall correctly, the creator of a project maintains full authority on which other organization members can merge code or modify project settings.

On top of that, OWLAPI currently has three modules dedicated only to creating releases with slightly different features, as well as benchmark modules. All of these rarely see changes, but it's common to receive requests for a slight tweak to the dependencies or the packaging of the releases. For that reason, I'm planning to split these modules in their own project. this would simplify providing, for example, an OWLAPI distribution with the ONTAPI implementation of the interfaces.

> Now the domain 'avicomp' is not quite approachable

I'm not sure what's entailed by that in terms of releases. Does it mean you won't be making releases under the `ru.avicomp` group?

For the releases project, I plan to keep OWLAPI distribution releases under the `net.sourceforge.owlapi` group - mostly to avoid fragmentation. The group for the modules you'd contribute to the organization remains your choice, there's no constraint on it; the only restriction comes from your account with Sonatype, or with any other public Maven repository you wish to use to publish releases.

Overall, keeping projects alive is best for the developer community, so I'd definitely vote in favor of that, however you wish to do it.

**Comment by ignazio1977** [comment]
As for the possibility of including ONTAPI as a module directly in the OWLAPI repository, I'm undecided as to advantages and disadvantages. I assume we'd still need separate distributions, or extra complexity to let the caller choose which implementations to use (e.g., one manager using default impl and another manager using ONTAPI?).

I'd choose to avoid the extra complexity - the most common question I see asked is still 'what are the jars I need?', and adding more jars and more options, when most applications are built to use only one implementation, feels unnecessary.

On the other hand, there might be synergy I'm unaware of, and we might be losing or duplicating work, so I really can't tell which way is best. I would start with a shared distribution project and figure out later whether there's an advantage to deeper integration.

**Comment by sszuev** [comment]
I like the idea to move the project to OWLCS group.
Moving ONTAPI as a OWLAPI sub-module can be delayed till a deeper understanding of needs arises.

> I'm not sure what's entailed by that in terms of releases. Does it mean you won't be making releases under the ru.avicomp group?

Yes. ONTAPI is not a popular project, so I'm planning to change both maven release group and java-packaging; nobody will suffer. 
Which name can I choose? 
The name `net.sourceforge.ontapi` is good, what do you think?

Under the organization 'avicomp' there are also two more projects: `ont-d2rq` and `ont-map`. 
Although currently I am not planning to maintain these projects, can they be moved into OWLCS too?
I'm not sure it is correct, but at least ont-d2rq is used by someone, and all them are about OWL. 
These projects have no maven releases.

Also, with whom I should contact to create new repo (of repos) in that group?

**Comment by ignazio1977** [comment]
> The name net.sourceforge.ontapi is good, what do you think?

Sounds good to me. When we started making Maven releases for Maven Central and created an account at Sonatype, we were asked whether we were in charge of the owlapi.sourceforge.net domain, but there was no documentation to provide. Not sure if that was just a best practice or an actual rule; you'd have to check yourself whether your account (I'm assuming you're using Sonatype for your releases) needs any changes.

I believe in order for you to be able to move the repository to owlcs the only thing needed is for your user to be added to the organization. I'll do that.

**Comment by ignazio1977** [comment]
> we were asked whether we were in charge of the owlapi.sourceforge.net domain

Having said that, we still have the SourceForge project but the build has no relation to that account at all; so there's a chance you might keep releasing with the old group id even if you no longer are responsible for the domain; or you could create the new group with the github repository. For example, an OWLAPI fork has releases under `com.github.ansell.owlapi`, so that's perfectly doable. Matter of preference, in the end.

**Comment by sszuev** [comment]
Thanks for inviting. 
But the user with the role 'Member' in OWLCS group may only contribute existing repos, 
For creating new repositories there is insufficient permission.

A workaround maybe as follows: a group owner may create a fresh repo without commits, then go to Insights\People tab and make my user as Admin. Ones this is done, I can push the codebases to new git remotes. 

Or need to expand the 'Member' permissions, may be temporarily.

**Comment by ignazio1977** [comment]
I couldn't change settings before you were added to the organization.

**Comment by ignazio1977** [comment]
I couldn't find a good way of changing permissions, so I've forked the projects and added the team as admin, now you should be able to carry out any operation on the three projects.

**Comment by sszuev** [comment]
Thanks, it seems all works.
