### ISSUE TITLE
Python flask and owl

### ISSUE THREAD

**Issue by gayathri13990** [owlcs/owlapi#893]
Hi I am new to python and owl. I have installed python flask for developing web applications. I have created a simple hello world code.I am trying to install owlready2 but its throwing errors. Even I tried manual installation its also throwing error. 
![pyerr](https://user-images.githubusercontent.com/9986081/68277799-f6dc9600-0095-11ea-96c3-209daa242468.png)
![errpy1](https://user-images.githubusercontent.com/9986081/68277800-f6dc9600-0095-11ea-9aa3-c5e16b83aa8a.png)

**Comment by ignazio1977** [comment]
You need to ask this on the owlready2 support channels, it's not owlapi related.
