### ISSUE TITLE
Unexpected getShortForm() behavior on IRIs?

### ISSUE THREAD

**Issue by beckyjackson** [owlcs/owlapi#894]
This might be related to #491 but those IRIs seemed slightly different.

Some IRIs with the same namespace end up with different short forms.

Correct handling:
```
IRI: http://purl.obolibrary.org/obo/chebi#BRAND_NAME
Short Form: BRAND_NAME
Namespace: http://purl.obolibrary.org/obo/chebi#
```

Incorrect handling:
```
IRI: http://purl.obolibrary.org/obo/chebi#1_STAR
Short Form: _STAR
Namespace: http://purl.obolibrary.org/obo/chebi#1
```

I would expect `getShortForm()` to return `1_STAR`, but the number gets cut off. Is this the intended behavior?

**Comment by ignazio1977** [comment]
It is. The fragment of an IRI (the NCName part) cannot start with digits. `getShortForm` tries to get an NCName compatible portion of the IRI.

**Comment by beckyjackson** [comment]
Thanks for the clarification!

**Comment by cweedall** [comment]
@ignazio1977 apologies bumping this years later, but I encountered the same situation and was having difficulty tracking down the specification details for valid NCNames.  Is there a permanent link available to documentation for this?
