### ISSUE TITLE
Question: Canonical way to order set of axioms?

### ISSUE THREAD

**Issue by matentzn** [owlcs/owlapi#908]
Hey @ignazio1977 :) Hope all is great. We were [wondering](https://github.com/geneontology/obographs/issues/47) whether you want to recommend an easy way to produce a canonical order of a set of OWL axioms we can just re-use to generate nicely sorted serialisations. :) Thanks a lot! I guess somewhat related to https://github.com/owlcs/owlapi/issues/273, but I thought to ask separately to be sure.

**Comment by ignazio1977** [comment]
@matentzn do you mean a formalization of the comparison function implemented in OWLAxiom::compareTo?

If not, OWLAxioms implement Comparable, so you can just sort a list of them with the sort() method. But I feel that's too simple an answer.

**Comment by matentzn** [comment]
I left real academia @ignazio1977 which means I also left a good part of my brain behind. Thanks! That was what I needed.

**Comment by julesjacobsen** [comment]
Just to chime in here - using OWLAxiom.compareTo() does not reproducibly produce the same result.

In the case of reading an OWL file into an Ontology and then parsing the OWLAxiom in order there are differences when using compareTo(). _However_ using CollectionFactory.sortOptionally(ontology.getAxioms()) the output order is reproducible.

**Comment by ignazio1977** [comment]
@julesjacobsen Do you have an example of this? `sortOptionally` uses plain sorting, which is based on `OWLAxiom::compareTo`, so I'm puzzled about this difference in behaviour.
Is this with a specific OWLAPI version?

**Comment by julesjacobsen** [comment]
@ignazio1977 Ah, no, my mistake you;'re quite correct - the issue was at my end when using `parallelStream()`

e.g.

```java
    // Works fine, as you say - this is what happens in sortOptionally()
    List<OWLAxiom> sortedAxioms = new ArrayList<>(ontology.getAxioms());
    Collections.sort(sortedAxioms);

    // Also works fine
    List<OWLAxiom> sortedAxioms = ontology.getAxioms()
            .stream()
            .sorted()
            .collect(Collectors.toList());

    // Not ok - order is not preserved! Not sure why I was using that in the first place as it's not like it benefits anything here.
     List<OWLAxiom> sortedAxioms = ontology.getAxioms()
            .parallelStream()
            .sorted()
            .collect(Collectors.toList());
```

Sorry to bother you!
