### ISSUE TITLE
Regarding encoding OWL restrictions as a combination of logical operators

### ISSUE THREAD

**Issue by karanthpallavi** [owlcs/owlapi#914]
Would like to check if its feasible to have OWL restriction for a property having a combination of logical operators as an expression.
For example:
Transition class has object property "hasConditions" which should have a restriction of the form condition1 and condition2 or condition3,
Is there a way to encode such restrictions in OWL API? Thanks

**Comment by ignazio1977** [comment]
Class expressions can be nested, so the domain or range of a property could be a disjunction of condition3 and the intersection of condition1 and condition2. Is this the kind of scenario you have in mind?

**Comment by karanthpallavi** [comment]
Thanks for your response, Yes, exactly

**Comment by karanthpallavi** [comment]
Would like to depict this scenario of transitions in a state diagram:
A transition has a source and a target state with a Guard. Transition, State, Guard, Condition, Signal are all classes in the ontology.
For every transition, there is a Guard that shall have multiple conditions. Conditions are different combinations of signals which can be, for examples:
1. C1 = S1 and S2 and S3 or S4
2. C2 = S1 or S2
and this combination is not known at the time of ontology design,
It can be any combination of logical operations on signals...
May I know how can we encode this in the ontology?
Thanks much
