### ISSUE TITLE
XSD datatypes are erroneously quoted in OBO writer

### ISSUE THREAD

**Issue by cmungall** [owlcs/owlapi#918]
Input:

```
Prefix(:=<http://purl.obolibrary.org/obo/test.owl#>)
Prefix(owl:=<http://www.w3.org/2002/07/owl#>)
Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>)
Prefix(xml:=<http://www.w3.org/XML/1998/namespace>)
Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>)
Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>)

Ontology(<http://purl.obolibrary.org/obo/test.owl>
Declaration(Class(<http://purl.obolibrary.org/obo/X_1>))
AnnotationAssertion(<http://purl.obolibrary.org/obo/rdfs_seeAlso> <http://purl.obolibrary.org/obo/X_1> "xx"^^xsd:string)

)
```

Output (owlapi 4.5.15):

```
format-version: 1.2
ontology: test

[Term]
id: X:1
property_value: rdfs:seeAlso "xx" "xsd:string"
```

this is incorrect and will break consumers of the obo file

Output (owlapi 4.5.6):

```
format-version: 1.2
ontology: test

[Term]
id: X:1
property_value: rdfs:seeAlso "xx" xsd:string
```

this is correct

I am not sure which version of the owlapi introduced this error

@matthewhorridge - can you hold off making a Protege release with newer versions of the owlapi until this is resolved

@jamesaoverton - same for robot

cc @matentzn @balhoff @dosumis

**Comment by cmungall** [comment]
I have confirmed this behavior in both robot and owltools

4.5.9 has the correct behavior. The problem was introduced in 4.5.10 or higher

there may be a reciprocal issue with the parser

**Comment by ignazio1977** [comment]
So, this pull request was wrong - am I reading this correctly?
https://github.com/owlcs/owlapi/pull/833

**Comment by cmungall** [comment]
Yes, my fault, sorry. I will try and look at this later.

**Comment by ignazio1977** [comment]
I think I've got a fix for this.

**Comment by ignazio1977** [comment]
@cmungall I believe this patch resolves the problem, always quoting the value and never quoting the type (if one exists). I believe this was the intention of the original code, but it was being done by inspecting the content of the string rather than the position in the list, which created false positives (and the patch made it worse because it just quoted everything).
