### ISSUE TITLE
HTTP STATUS 500 

### ISSUE THREAD

**Issue by mrajeshrdy** [owlcs/owlapi#919]
Hi Team,
when I am trying to convert Json to owl format throws an error like "The server encountered an internal error that prevented it from fulfilling this request."

Can anyone help how to fix this and conversion Thanks in advance.
![Conv](https://user-images.githubusercontent.com/48939446/77906775-2179f600-72a6-11ea-80da-c29d12f27875.PNG)

**Comment by ignazio1977** [comment]
Not enough information to help. What's the code you're running?

**Comment by mrajeshrdy** [comment]
Hi I was download the ontology from the below link Json file and converting to owl or ttl or format
https://www.kegg.jp/kegg-bin/get_htext#A1

**Comment by ignazio1977** [comment]
I can't find a way to get a JSON file from the link you posted. I only get back a plain HTML page. What code are you running?

**Comment by mrajeshrdy** [comment]
Hi 

I am attaching the Json file which i tried to convert owl or ttl

Hence Json is not supported to upload for that I saved as .txt

[ko00001.txt](https://github.com/owlcs/owlapi/files/4407519/ko00001.txt)

**Comment by ignazio1977** [comment]
What I was after is the information that you are attempting this conversion via http://mowl-power.cs.man.ac.uk:8080/converter/

The service is not maintained by OWLAPI developers. However, the page says:

`The convert accepts ontologies written in RDF/XML, OWL/XML, OWL Functional Syntax, Manchester OWL Syntax and OBO Syntax`

The JSON file you show is not in a supported language, so the converter cannot accept it.

**Comment by mrajeshrdy** [comment]
Hey Thanks for your support, 

Can you suggest any other methods to convert json to json-LD or other owl formats

**Comment by ignazio1977** [comment]
It's not possible to write a general conversion tool from any json content to an owl format - the translation needs to be specific for each different json schema the content is using. I'm not aware of any library that includes translation of json schema patterns, so I'm afraid it needs to be done from scratch.

**Comment by mrajeshrdy** [comment]
Thank you
