### ISSUE TITLE
SAXException() on "http://www.w3.org/2002/07/owl#Ontology"

### ISSUE THREAD

**Issue by palandlom** [owlcs/owlapi#920]
I have SAXexception from `AutoIRIMapper` which is threw by this section:

```
        if (tag.equals("http://www.w3.org/2002/07/owl#Ontology")) {
            throw new SAXException();
        }
```
... owl file (in [http://www.ontologydesignpatterns.org/cp/owl/classification.owl](http://www.ontologydesignpatterns.org/cp/owl/classification.owl) has the namespace - http://www.w3.org/2002/07/owl.

So I'm confused - is that some error here? And if yes how can I avoid of it?

**Comment by ignazio1977** [comment]
That's not an error, it is a shortcut to stop the Sax parser from continuing parsing after the Ontology tag has been found. There's no other way in the Sax interface to halt the processing, and AutoIRIMapper does not need to parse the whole file - only enough of it to find the ontology IRI.

    @Override
    public void startElement(String uri, String localName, String qName, Attributes attributes)
        throws SAXException {
        String tag = uri + localName;
        OntologyRootElementHandler handler = handlerMap.get(tag);
        if (handler != null) {
            IRI ontologyIRI = handler.handle(checkNotNull(attributes));
            if (ontologyIRI != null && currentFile != null) {
                addMapping(ontologyIRI, verifyNotNull(currentFile));

^^^^^^^^^^^^^^^^^^^^^ this is where the mapping is found and stored in the mapper

            }
        }
        if (tag.equals("http://www.w3.org/2002/07/owl#Ontology")) {
            throw new SAXException(ONTOLOGY_ELEMENT_FOUND_PARSING_COMPLETE);
        }
    }

If the AutoIRIMapper isn't getting used in your code, there might be another issue in play. How are you using the mapper?

**Comment by palandlom** [comment]
Yes, I guessed something like this. I add mapper in ontology manager to load ontology with imports. 
Thanks for clarification.
