### ISSUE TITLE
How to get the OWLManager use a HTTP Proxy?

### ISSUE THREAD

**Issue by egonw** [owlcs/owlapi#923]
I am using the OWLAPI in Java code that now runs on a build server behind a proxy server. How can I get OWLAPI to download imported OWL files using the HTTP proxy?

**Comment by ignazio1977** [comment]
OWLAPI doesn't explicitly manage proxies, so the settings for the JVM should work without changes. See https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html

**Comment by egonw** [comment]
No, that did not help. Maybe it is because it's an `ftp://` URL... I need to explore this further. This is the current output:

```
+ java -Dhttp.proxyHost=xxxx.nl -Dhttp.proxyPort=yyyy -cp slimmer-1.0.0-jar-with-dependencies.jar com.github.enanomapper.Slimmer .
Searching configuration files in .
Slimming for aopo.props
Loading OWL file: aopo.owl
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Adding mappings with root: /var/lib/jenkins/jobs/eNanoMapper - AOP/workspace
org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <ftp://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi.owl> Cause: OWLOntologyCreationIOException: java.net.ConnectException: Connection refused (Connection refused)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1713)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.TripleHandlers$TPImportsHandler.handleTriple(TripleHandlers.java:1555)
```

**Comment by ignazio1977** [comment]
I haven't tried FTP URLs myself, but the page I linked above says the parameters are different:

> 2.3) FTP
> Settings for the FTP protocol handler follow the same rules as for http, the only difference is that each property name is now prefixed with 'ftp.' instead of 'http.'
> 
> Therefore the system properties are:
> 
> ftp.proxHost
> ftp.proxyPort
> ftp.nonProxyHosts
> Note that, this time, there is a separate property for the "non proxy hosts" list. Also, as for http, the default port number value is 80. It should be noted that when going through a proxy, the FTP protocol handler will actually use HTTP to issue commands to the proxy server, which explains why this is the same default port number.
> 
> Let's examine a quick example:
> 
> $ java -Dhttp.proxyHost=webcache.example.com
> -Dhttp.proxyPort=8080 -Dftp.proxyHost=webcache.example.com -Dftp.proxyPort=8080 GetURL
> Here, both the HTTP and the FTP protocol handlers will use the same proxy server at webcache.example.com:8080.
