### ISSUE TITLE
classAssertionAxioms with OWLClassExpression fails

### ISSUE THREAD

**Issue by sszuev** [owlcs/owlapi#930]
version 5.1.14

The testcase:

            String ns = "http://xxx#";
            OWLOntologyManager m = OntManagers.createOWL();
            OWLDataFactory df = m.getOWLDataFactory();

            OWLObjectProperty p = df.getOWLObjectProperty(ns + "op");
            OWLNamedIndividual i = df.getOWLNamedIndividual(ns + "I");
            OWLClassExpression c = df.getOWLObjectMaxCardinality(1, p);

            OWLOntology o = m.createOntology();
            o.add(df.getOWLClassAssertionAxiom(c, i));
            o.saveOntology(OntFormat.TURTLE.createOwlFormat(), System.out);

            Assert.assertEquals(1, o.classAssertionAxioms(i).peek(System.out::println).count());
            Assert.assertEquals(1, o.classAssertionAxioms(c).peek(System.out::println).count());

**Comment by ignazio1977** [comment]
Nice catch, it's a nine year old bug. Under bug 3207604 on the old SourceForge website, which seems to no longer exist, the type for `getClassAssertionAxiom` went from OWLClass to OWLClassExpression, but the index still only stores OWLClass objects, so searches by any non named classes don't find matches, although the interface allows them.
