### ISSUE TITLE
Support RDF4J Rio HDT parser

### ISSUE THREAD

**Issue by ansell** [owlcs/owlapi#931]
RDF4J Rio recently added support for HDT parsing (not writing yet). Would be useful to add the mapping classes to allow it to be used as a parsing source here.

**Comment by firmao** [comment]
Could you provide an example of HDT parsing using RDF4J?

**Comment by ignazio1977** [comment]
@firmao use new HDTRDFDocumentFormat() as format argument - that's the only difference between this format and others used in the examples.
