### ISSUE TITLE
SWRL body reordered when structure shared

### ISSUE THREAD

**Issue by martinjoconnor** [owlcs/owlapi#936]
In an ontology with class **A** and object property **op1** the following SWRL round-trips successfully:

A(?a) ^ op1(?x, ?y)  -> 

But this rule does not:

A(?a) ^ op1(?x, ?y)  -> A(?a)

The body atoms get reordered, giving:

op1(?x, ?y) ^ A(?a)   -> A(?a)

Oddly, the presence of at least one head atom seems to cause the issue. With an empty head, no reordering seems to happen.

OWLAPI version is 4.5.9. Serialization format is RDF/XML.

**Comment by ignazio1977** [comment]
I've tried this by modifying SWRLAtomOrderingRoundTripTestCase to have no head and added an object property atom, but I can't replicate the failure. Do you create this via code or via Protege?

**Comment by martinjoconnor** [comment]
The issue manifests itself in Protege using the SWRLAPI. However, I have managed to produce an OWLAPI-based code fragment that illustrates the problem.

Basically, the code below creates a (nonsensical) rule `Person(?x) ^ hasUncle(?x, ?y) -> Person(?x)` and saves the rule in RDF/XML format to a temporary file. If you examine the serialized output you will see that the individual property atom is placed before the class atom in the serialization of the rule body (`hasUncle(?x, ?y) ^ Person(?x)`). However, if the head is empty (which can be performed by commenting out `head.add(classAtom)`) then the body is serialized properly.


```

    String NAMESPACE = "http://swrlapi.org/it#";
    OWLClass PERSON = Class(iri(NAMESPACE + "Person"));
    OWLObjectProperty HAS_UNCLE = ObjectProperty(iri(NAMESPACE + "hasUncle"));
    OWLOntologyManager ontologyManager = OWLManager.createOWLOntologyManager();
    OWLOntology ontology = OWLManager.createOWLOntologyManager().createOntology();
    OWLDataFactory dataFactory = ontology.getOWLOntologyManager().getOWLDataFactory();
    RDFXMLDocumentFormat format = new RDFXMLDocumentFormat();
    SWRLVariable xVariable = dataFactory.getSWRLVariable(iri(NAMESPACE + "x"));
    SWRLVariable yVariable = dataFactory.getSWRLVariable(iri(NAMESPACE + "y"));
    SWRLClassAtom classAtom = dataFactory.getSWRLClassAtom(PERSON, xVariable);
    SWRLObjectPropertyAtom objectPropertyAtom = dataFactory.getSWRLObjectPropertyAtom(HAS_UNCLE, xVariable, yVariable);
    Set<SWRLAtom> body = new LinkedHashSet<>();
    Set<SWRLAtom> head = new LinkedHashSet<>();
    body.add(classAtom);
    body.add(objectPropertyAtom);
    head.add(classAtom);
    SWRLRule swrlRule = dataFactory.getSWRLRule(body, head);

    ontologyManager.addAxiom(ontology, Declaration(PERSON));
    ontologyManager.addAxiom(ontology, Declaration(HAS_UNCLE));
    ontologyManager.addAxiom(ontology, swrlRule);

    File file = File.createTempFile("temp", ".owl");
    ontology.saveOntology(format, org.semanticweb.owlapi.model.IRI.create(file.toURI()));

```

**Comment by ignazio1977** [comment]
Thanks for the example, I didn't realize that the determining feature of your first report is that the same expression appears on both sides of the rule.

This bug is triggered when the same non-entity object is used multiple times (not just an equal expression, but the exact same object). When rendering XML, the shared structure must be replicated, otherwise the RDF would contain only one blank node where two are expected.

That mechanism was using the same code for all collections, which woks fine for collections where the order is based on OWLObject::compareTo. That's not the case for SWRL rules though.

In my test, I was using different values for all parts of the rule; so the bug was not triggered.

**Comment by martinjoconnor** [comment]
Great! Thanks for the quick fix.

**Comment by martinjoconnor** [comment]
Hi Ignazio,

Do you have a timeframe for the next release of the v4-series of the OWLAPI? I'd like to update the SWRLAPI to include the fix to this issue.

Martin

**Comment by ignazio1977** [comment]
@martinjoconnor version 4.5.17 contains the fix.

**Comment by martinjoconnor** [comment]
Great. Thanks.

FYI, I'm  not seeing that release here:

https://github.com/owlcs/owlapi/releases

Though it is clearly on Maven central.
