### ISSUE TITLE
Deprecation of Signature

### ISSUE THREAD

**Issue by gwytherinadelle** [owlcs/owlapi#941]
I have a local modified copy of a public ontology stored in a database. I'm trying to iterate through the classes to make sure they all exist within my local copy and if not, add them. All of the examples I have been able to find make use of the getClassesInSignature, but this has been deprecated. The deprecation notes say to use the stream method, but this note is ambiguous enough that I am having difficulties finding what I'm looking for. Any help would be appreciated.

**Comment by ignazio1977** [comment]
For all the deprecated methods that return a set and start with `get`, the stream version has the same name minus the get prefix. So in this case it's `classesInSignature`.

**Comment by gwytherinadelle** [comment]
Awesome, thank you. Is there a way to flag for including imports?

**Comment by ignazio1977** [comment]
> Is there a way to flag for including imports?

sorry I don't get what you mean here.

**Comment by gwytherinadelle** [comment]
The method getClassesInSignature(boolean includeImportsClosure) does not appear to have a non deprecated method. Is there an function to include everything in the ontology including the imports?

**Comment by ignazio1977** [comment]
Similar pattern, where there was only a boolean for imports mow theres an `Imports` enumeration with INCLUDED/EXCLUDED members.

**Comment by gwytherinadelle** [comment]
Thank you!
