### ISSUE TITLE
Deep Imports

### ISSUE THREAD

**Issue by LittleBunnyFooBar** [owlcs/owlapi#943]
I am storing a local modified copy of an ontology (BAO) within a MySQL database. I am trying to update this copy of the ontology to the most recent version using OWL API via a QUARTZ scheduler within a Tomcat web application. For each class, I need the superclass, the subclass, the label, and the definition. Unfortunately, the labels and definitions are buried in deep imports. By deep imports, I mean they are not defined in the parent owl file, but rather in the import defined in the import defined in the import of the parent owl file. How do I use OWL API to load all of the imports into a singular ontology in the ontology manager?

**Comment by ignazio1977** [comment]
If I get this right, you have

`A imports B imports C imports D`

and some entity declarations (and label annotations) are in D.

You want an ontology `E` that contains all axioms from `A, B, C, D`, but the ontology information itself is not important, only the contained axioms.

You can load `A` and OWLAPI will load the imports closure `A, B, C, D`. Then you can get all the axioms from `A`:

`a.axioms(Imports.INCLUDED)`

This returns a stream of axioms, that will include declarations and annotation axioms that include labels at any level in the imports. You can create an ontology from these axioms, or store the information in other ways if that's more useful to your use case.

**Comment by LittleBunnyFooBar** [comment]
Ah ha! This is exactly what I was looking for. Thank you!
