### ISSUE TITLE
ReferencedIndividualCount value differs between OWL API versions

### ISSUE THREAD

**Issue by jvendetti** [owlcs/owlapi#949]
I'm attempting an upgrade from version 4.5.13 to 4.5.16. One of my unit tests is failing due to a difference in the return value of the getValue() method for ReferencedIndividualCount. The following test case passes in 4.5.13:

```
File file = new File("BRO_v3.2.owl");
IRI iri = IRI.create(file);
OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
OWLOntology ontology = manager.loadOntology(iri);

ReferencedIndividualCount referencedIndividualCount = new ReferencedIndividualCount(ontology);
referencedIndividualCount.setImportsClosureUsed(true);
assertEquals(Integer.valueOf(80), referencedIndividualCount.getValue());
```

... but fails in 4.5.16:

```
java.lang.AssertionError: 
Expected :80
Actual   :124
```

I'm not sure how to account for this difference. Am I using the correct methodology for calculating the number of individuals?

[BRO_v3.2.owl.zip](https://github.com/owlcs/owlapi/files/4887422/BRO_v3.2.owl.zip)

**Comment by ignazio1977** [comment]
No obvious changes in the methods used, but it would depend on which individuals are found. There have been bugs fixed around parsing of some annotation axioms, and if the extra individuals are found in those positions then the code is right but the test expects incorrect behaviour.

(There's a 4.5.17 version out with a number of bug fixes in other areas, if you're updating it might be worth considering updating to that version)

**Comment by jvendetti** [comment]
OK, thank you for the explanation.

With regard to 4.5.17, are you planning to publish in Maven Central? I couldn't find it listed:

https://repo1.maven.org/maven2/net/sourceforge/owlapi/owlapi-distribution/

Attempting to update my pom.xml in IntelliJ gives:

`Could not find artifact net.sourceforge.owlapi:owlapi-distribution:pom:4.5.17 in central (https://repo.maven.apache.org/maven2)`

**Comment by ignazio1977** [comment]
It has been released for maven central. Possibly a sync issue between sonatype and maven central, I'll go check.

**Comment by ignazio1977** [comment]
Something went wrong when I made the release but nothing was reported. I've rerun the release process and now 4.5.17 shows up on Sonatype. Should soon be available on Central.

**Comment by jvendetti** [comment]
Thanks much - I see it now.

**Comment by ignazio1977** [comment]
I've checked the contents of the BRO ontology and looked for individuals that are only found now.

One example below:

    <owl:Class rdf:about="&BRO;Averaging_and_Agglomeration">
    </owl:Class>
    
    <owl:Class rdf:about="&BRO;Averaging_and_Aglomeration">
        <rdfs:subClassOf rdf:resource="&BRO;Deprecated_Resource"/>
        <desc:replacedBy rdf:resource="&BRO;Averaging_and_Agglomeration"/>
    </owl:Class>

The object of `desc:replacedBy` is only found as an individual in the latest OWLAPI not in 4.5.13.

This looks like an accidental bug fix to me - none of the changes that have gone in mentions punned individuals as a problem.

I don't know if the intent of the ontology here was to pun the class and individual IRIs for the use of `desc:replacedBy`, but it's declared as an object property so its range must be an individual. Current behaviour looks correct to me, but it's possible that the intention was for it to be an annotation property.

**Comment by jvendetti** [comment]
Thanks for looking at BRO - I should have thought to include an example individual in the initial issue report. The original author of the ontology isn't on the BioPortal team anymore, so I'm not sure if the intent was to use the punning. Since the OWL API is doing the correct thing here, I've updated our unit tests accordingly. The upgrade to 4.5.17 seems complete on our end - planning to publish to production today.
