### ISSUE TITLE
New in Owl 

### ISSUE THREAD

**Issue by giladrozmarin** [owlcs/owlapi#953]
Hello I'm new in owl world,
and I'm trying to work with owl file in js
Can you help me with Readme file for first example ?

**Comment by ignazio1977** [comment]
OWLAPI is a Java only api, are you going to use some adapter library to access it via JavaScript?

If so, please give us a clue about what you're planning to do first.

**Comment by giladrozmarin** [comment]
Yes I'm looking for adapter library to access it via JavaScript.

I'm develop a KSB of Military exercise  that mean user fill a forms online
and in the server side - there is a "json-rules-engine"(npm package)  that check you fill the form by the rules
(there is a plenty of rules in  Military)
I want pass the rules to "json-rules-engine" from OWL file and make inferences by the owlAPI

**Comment by ignazio1977** [comment]
OK, for the OWLAPI side of things the documentation in the wiki should help.

I can't help with the JavaScript library, I don't know any adapters.
