### ISSUE TITLE
Ontology not loaded in case of multiple HTTP redirects

### ISSUE THREAD

**Issue by ventuc** [owlcs/owlapi#954]
When loading an external ontology, OWL API currently follows only one HTTP redirect.

For example it doesn't work for Dublic Core ontology, because to reach http://purl.org/dc/elements/1.1/ the client must follow 2 http redirects:
1. http://purl.org/dc/elements/1.1/ --> HTTP 302, redirects to https://www.dublincore.org/specifications/dublin-core/dcmi-terms/dublin_core_elements#
2. https://www.dublincore.org/specifications/dublin-core/dcmi-terms/dublin_core_elements# --> HTTP 303, redirects to http://www.dublincore.org/specifications/dublin-core/dcmi-terms/dublin_core_elements.rdf
3. http://www.dublincore.org/specifications/dublin-core/dcmi-terms/dublin_core_elements.rdf is the actual Dublin Core ontology

**Comment by ventuc** [comment]
Hi @ignazio1977 , sorry to bother you, but still no news about the release of the fix?

**Comment by ignazio1977** [comment]
I've finished the first javadoc review, should be able to do the release this evening.

**Comment by ignazio1977** [comment]
5.1.16 released, should be on maven central by tomorrow

**Comment by ventuc** [comment]
> 5.1.16 released, should be on maven central by tomorrow

Thanks!
