### ISSUE TITLE
Annotations instead of Property assertions

### ISSUE THREAD

**Issue by razvansandu** [owlcs/owlapi#961]
Hello,

I have just recently started using OWLAPI, so I apologize in advance for any mistakes.
I am trying to populate an ontology using the OWLAPI, view it in Protege and then run some SQWRL queries on it.

I have been using the examples from [here](https://github.com/owlcs/owlapi/blob/version4/contract/src/test/java/org/semanticweb/owlapi/examples/Examples.java) but I am struggling with OWLDataProperty and OWLObjectProperty. I can create the individuals and the properties successfully, but in Protege I can only see them under Annotations, instead of Property Assertions (as I have seen them before).

![image](https://user-images.githubusercontent.com/11517463/90986232-e09eb880-e589-11ea-8336-22cc320a8f44.png)

The code I am using is below and I am starting with an empty ontology:
```java
        Set<OWLAxiom> domainsAndRanges = new HashSet<OWLAxiom>();

        OWLClass personClass = dataFactory.getOWLClass(IRI.create(ontologyFile + "#Person"));

        OWLDataProperty hasAge = dataFactory.getOWLDataProperty(IRI.create(ontologyFile + "#hasAge"));

        domainsAndRanges.add(dataFactory.getOWLDataPropertyDomainAxiom(hasAge, personClass));
        domainsAndRanges.add(dataFactory.getOWLDataPropertyRangeAxiom(hasAge, dataFactory.getIntegerOWLDatatype()));

        OWLNamedIndividual john = dataFactory.getOWLNamedIndividual(IRI.create(ontologyFile + "#John"));
        OWLNamedIndividual matthew = dataFactory.getOWLNamedIndividual(IRI.create(ontologyFile + "#Matthew"));

        OWLDataPropertyAssertionAxiom matthewDataPropertyAssertion =
                dataFactory.getOWLDataPropertyAssertionAxiom(hasAge, matthew, 43);
        OWLDataPropertyAssertionAxiom dataPropertyAssertion =
                dataFactory.getOWLDataPropertyAssertionAxiom(hasAge, john, 51);
        domainsAndRanges.add(matthewDataPropertyAssertion);
        domainsAndRanges.add(dataPropertyAssertion);

        // make john and matthew instances of person
        domainsAndRanges.add(dataFactory.getOWLClassAssertionAxiom(personClass, john));
        domainsAndRanges.add(dataFactory.getOWLClassAssertionAxiom(personClass, matthew));

        OWLObjectProperty hasFather = dataFactory.getOWLObjectProperty(IRI.create(ontologyFile + "#hasFather"));
        domainsAndRanges.add(dataFactory.getOWLObjectPropertyAssertionAxiom(hasFather, matthew, john));


        ontologyManager.addAxioms(ontology, domainsAndRanges);
        try {
            ontologyManager.saveOntology(ontology);
        } catch (OWLOntologyStorageException e) {
            e.printStackTrace();
        }
```

In terms of SQWRL queries, I am trying a basic one: `Person(?p) ^ hasAge(?p, ?a) -> sqwrl:select(?p, ?a)`. It works as expected if the properties are under "Property assertions", but not when they are in the "Annotations" tab.

Any help is highly appreciated.

**Comment by ignazio1977** [comment]
The declarations for the properties you're using are missing, for some reason. How are you initialising the ontology and its format?

**Comment by razvansandu** [comment]
```java
public final class MyOntologyManager {
    private static MyOntologyManager INSTANCE;
    private final String pathname = "src/main/resources/ontology.owl";

    private final File ontologyFile = new File(pathname);
    private OWLOntologyManager ontologyManager;
    private OWLOntology ontology;
    private OWLDataFactory dataFactory;

    private MyOntologyManager() throws OWLOntologyCreationException {
        this.ontologyManager = OWLManager.createOWLOntologyManager();
        this.ontology = this.ontologyManager.createOntology(IRI.create(ontologyFile));
        this.dataFactory = this.ontologyManager.getOWLDataFactory();
    }

    public static MyOntologyManager getInstance() {
        if (INSTANCE == null) {
            try {
                INSTANCE = new MyOntologyManager();
            } catch (OWLOntologyCreationException e) {
                e.printStackTrace();
            }
        }

        return INSTANCE;
    }

    public void populateOntology() {
        // ... code in initial snippet
    }
```

This is all the code I am using, starting with a brand new file.

**Comment by ignazio1977** [comment]
Running your code I get the following output:

    <?xml version="1.0"?>
    <rdf:RDF xmlns="ur:test:ontology.owl#"
     xml:base="ur:test:ontology.owl"
     xmlns:owl="http://www.w3.org/2002/07/owl#"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:xml="http://www.w3.org/XML/1998/namespace"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
     xmlns:ontology="ur:test:ontology.owl#">
    <owl:Ontology rdf:about="ur:test:ontology.owl"/>
    <owl:ObjectProperty rdf:about="ur:test:ontology.owl#hasFather"/>
    <owl:DatatypeProperty rdf:about="ur:test:ontology.owl#hasAge">
        <rdfs:domain rdf:resource="ur:test:ontology.owl#Person"/>
        <rdfs:range rdf:resource="http://www.w3.org/2001/XMLSchema#integer"/>
    </owl:DatatypeProperty>
    <owl:Class rdf:about="ur:test:ontology.owl#Person"/>
    <owl:NamedIndividual rdf:about="ur:test:ontology.owl#John">
        <rdf:type rdf:resource="ur:test:ontology.owl#Person"/>
        <hasAge rdf:datatype="http://www.w3.org/2001/XMLSchema#integer">51</hasAge>
    </owl:NamedIndividual>
    <owl:NamedIndividual rdf:about="ur:test:ontology.owl#Matthew">
        <rdf:type rdf:resource="ur:test:ontology.owl#Person"/>
        <hasFather rdf:resource="ur:test:ontology.owl#John"/>
        <hasAge rdf:datatype="http://www.w3.org/2001/XMLSchema#integer">43</hasAge>
    </owl:NamedIndividual>
    </rdf:RDF>


When parsed, this gives these declarations:


    Declaration(NamedIndividual(<ur:test:ontology.owl#John>))
    Declaration(Class(<ur:test:ontology.owl#Person>))
    Declaration(DataProperty(<ur:test:ontology.owl#hasAge>))
    Declaration(ObjectProperty(<ur:test:ontology.owl#hasFather>))
    Declaration(NamedIndividual(<ur:test:ontology.owl#Matthew>))

This looks correct and exactly what you're after, and Protege should have no problems interpreting it.

I'm wondering if the problem is an existing file with the same name? Maybe Protege has the previous version of the ontology loaded?
