### ISSUE TITLE
Performance of signature checks during ontology changes

### ISSUE THREAD

**Issue by fanavarro** [owlcs/owlapi#968]
Hi, I would like to populate an ontology with individuals from different datasources. To achieve this, I have created some mappers that iterate over the datasources (normally csv files) and create the corresponding individuals in the ontology.

This process starts very fluently, being able to process ten rows of my input csv in a second, more or less. However, this rate gets worse as new instances are included in the ontology. For example, when the application has dealt with 1780 rows, it take about 7 seconds in order to process a single row. I am not sure about how many individuals have been created at this point, but the conversion from each row implies the creation of a considerable amount of them.

I have analysed my application with visualvm, and the bottle neck seems to be located in the method _containsIndividualInSignature_, from OWLOntology class. In some points of my code, I check if an instance already exists or not in order to do different things. I thought this would have a O(1) complexity, but maybe I was wrong.

Do you have any tip to improve this performance?

Thanks for your work.

**Comment by ignazio1977** [comment]
Which OWLAPI version are you using?

Depending on your code there might be various ways to work around this issue, the simplest I can think of would be to keep a set of individuals you've added in your code, so instead of calling to OWLAPI (which might need to recompute indexes to answer that query) you'd have an O(C) cost.

**Comment by fanavarro** [comment]
Hi @ignazio1977, thanks for your quick reply!

I am using the version 5.1.16 (the latest one I think). Thanks for your advice, I will try to keep that set on my own. I have to learn more about the internals of the owlapi... I did not know that there is an internal index. I also expected a high RAM memory usage but, surprisingly for me, it is stable at the moment, good work!

Thanks again!

**Comment by fanavarro** [comment]
Finally, I've replaced the containsIndividualInSignature method by keeping my own set of included individuals. With this change, my performance changes. With the OWLOntology method, the process took 2 days to be completed; with my own set, it last a couple of minutes.

Not sure if I should close this issue. @ignazio1977, I leave it in your hands.

Greetings!

**Comment by ignazio1977** [comment]
I've done some more investigation on this.

The root issue is that the lookup methods are geared towards being efficient when no changes are happening in the ontology, so they use caches to make searches faster. However, these caches are expensive, and are invalidated when changes are made - so, for that approach, looking for an element that was just added to the ontology is the worst case scenario, where the caches are constantly rebuilt and soon invalidated.

Using `containsIndividualInSignature` with an IRI argument is difficult to optimise - references to entities are indexed by entity, not by IRI, so it's difficult to design the cache out of the process.

There is another method, `containsEntityInSignature`, which takes an OWLEntity, and so would accept the OWLNamedIndividual you created, which ultimately resolves to a map key lookup, so it does not need to build caches.
However, in the current code this method always uses a cache signature, which is efficient, again, only when the ontology is not being modified. This is easier to amend - by only using the cached signature if it has already been created by other uses of the ontology. Making this change, I can reduce the search times by three orders of magnitude, with no impact on other uses of the method. Will be included in the next OWLAPI release.
