### ISSUE TITLE
Error importing common ontologies (pizza.owl) as part of another ontology while reading from file

### ISSUE THREAD

**Issue by dhanishmeht** [owlcs/owlapi#972]
I am using OWLAPI version 5.1.16 and have a test owl file which imports the pizza.owl

[pizza-import.owl.txt](https://github.com/owlcs/owlapi/files/5306859/pizza-import.owl.txt)
Had to add .txt due to Github restrictions.

Pizza owls URI is not resolvable and hence I have a common directory where I place the pizza.owl and use the AutoIRIMapper to map the directory.
Then I proceed with loading the test ontology, which gives parsing errors.
The following is my import code,

`
OWLOntologyLoaderConfiguration loaderConfiguration = new OWLOntologyLoaderConfiguration();
            loaderConfiguration.setMissingImportHandlingStrategy(MissingImportHandlingStrategy.SILENT);

            OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
            manager.clearOntologies();

            IRIDocumentSource documentSource = new IRIDocumentSource(IRI.create(ontFile.toURI()));

            AutoIRIMapper autoIRIMapper = new AutoIRIMapper(new File(getClass().getClassLoader().getResource("common").getFile()), true);
            autoIRIMapper.getOntologyIRIs();
            Set<OWLOntologyIRIMapper> mappers = new HashSet<>();
           mappers.add(autoIRIMapper);
            manager.setIRIMappers(mappers);
            manager.setOntologyLoaderConfiguration(loaderConfiguration);
           OWLOntology ontology = manager.loadOntologyFromOntologyDocument(ontFile);
`

I get parse errors because it is trying to resolve the Pizza URI as a URL and is getting some HTML code.
I have attached the log file 
[log.txt](https://github.com/owlcs/owlapi/files/5306907/log.txt)

**Comment by ignazio1977** [comment]
You're using an iri document source, which will skip the auto iri mapper as well as the file. Use a file document source and give it the ontFile object, which I believe is a File.

**Comment by danny2394** [comment]
I forgot to comment out that part, I was previously using document source, however the ontFile object is of File type

**Comment by dhanishmeht** [comment]
I used the FileDocumentSource and gave it the ontFile object which is of File type, however I get the same error

**Comment by dhanishmeht** [comment]
I debugged more into it, and it does try to use the AutoIRIMapper, however it tries to match using the IRI along with the version, and the mapper does not have a version based map.

Any idea on how to proceed?

**Comment by ignazio1977** [comment]
What ontology IRI is declared in your local copy of pizza.owl? If it doesn't match the URL in the root ontology, AutoIRIMapper won't know how to match the import request and the files on disk.
You could solve this by changing the local file, or you could add an OWLOntologyIRIMapper to map from the ontology IRI you use in your import file to the ontology IRI used in your local copy.

**Comment by dhanishmeht** [comment]
`<owl:Ontology rdf:about="http://www.co-ode.org/ontologies/pizza">
        <owl:versionIRI rdf:resource="http://www.co-ode.org/ontologies/pizza/2.0.0"/>
        <dc:title xml:lang="en">pizza</dc:title>
        <terms:contributor>Nick Drummond</terms:contributor>
        <terms:license rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Creative Commons Attribution 3.0 (CC BY 3.0)</terms:license>
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">pizza</rdfs:label>
        <terms:provenance xml:lang="en">v2.0 Added new annotations to the ontology using standard/well-know annotation properties

v1.5. Removed protege.owl import and references. Made ontology URI date-independent

v1.4. Added Food class (used in domain/range of hasIngredient), Added several hasCountryOfOrigin restrictions on pizzas, Made hasTopping invers functional</terms:provenance>
        <owl:versionInfo rdf:datatype="http://www.w3.org/2001/XMLSchema#string">2.0</owl:versionInfo>
        <terms:contributor>Alan Rector</terms:contributor>
        <dc:description xml:lang="en">An ontology about pizzas and their toppings.

This is an example ontology that contains all constructs required for the various versions of the Pizza Tutorial run by Manchester University (see http://owl.cs.manchester.ac.uk/publications/talks-and-tutorials/protg-owl-tutorial).</dc:description>
        <terms:contributor>Matthew Horridge</terms:contributor>
        <terms:contributor>Chris Wroe</terms:contributor>
        <terms:contributor>Robert Stevens</terms:contributor>
    </owl:Ontology>`

This is a snippet  under the owl tag in the ontology of the local copy. I simply downloaded the file available at
https://protege.stanford.edu/ontologies/pizza/pizza.owl


Before I import the ontology, I used the AutoIRIMapper to scan the directory, and it picked up 
`http://www.co-ode.org/ontologies/pizza`
When I import my test file which has an import of the pizza.owl as generated by Protege, this is the IRI of the import it saved it as,
`http://www.co-ode.org/ontologies/pizza/2.0.0` which has the version information encoded in the end.

I could change the IRI in the saved pizza.owl to include the version,  but then this would become an manual process of keeping the versions updated for all the ontologies in the directory.

**Comment by ignazio1977** [comment]
The problem is that, in order for an ontology to be imported when its version is also specified, the ontology with the desired version must be resolvable - i.e., what explicitly is not the case with the pizza ontology version you want to use.

In this case your only workaround is to specify a mapper from version 2.0.0 to the version AutoIRIMapper can actually find, or to an IRI that points directly to your file:

    SimpleIRIMapper pizza2Mapper = new SimpleIRIMapper(
        IRI.create("http://www.co-ode.org/ontologies/pizza/2.0.0"),
        IRI.create("file:///path/to/your/folder/pizza.owl"));

This mapper has the same effect, locally, as publishing version 2.0.0 of pizza.owl at http://www.co-ode.org/ontologies/pizza/2.0.0.
If you use the IRI that AutoIRIMapper can find instead, then AutoIRIMapper will do the rest of the work.

In either case you end up maintaining some import resolution information in your code or your local files. This cannot be escaped, with the current OWL specs, if the ontology developers have not made the different versions individually resolvable online.

**Comment by dhanishmeht** [comment]
Makes sense, I will do this for now. Shall this be left open?
