### ISSUE TITLE
Java heap space error with large ontologies

### ISSUE THREAD

**Issue by LittleBunnyFooBar** [owlcs/owlapi#974]
For certain public ontologies, when trying to use loadOntologyFromOntologyDocument, I run into java heap space errors. I've tried adjusting my heap space to no avail. 

Ontologies that cannot be loaded: 
http://bioportal.bioontology.org/ontologies/CLO
http://bioportal.bioontology.org/ontologies/GO

**Comment by ignazio1977** [comment]
This might be dependent on OWLAPI version, Java version and format. GO in RDF/XML, with Java 11 and OWLAPI 5.1.16, can be parsed with default heap size.
Can you add the versions you used?

**Comment by LittleBunnyFooBar** [comment]
OWLAPI: 5.1.14
JDK: 1.8.0_251
GO: OBO format, 2020-08-11 release

Is the API more efficient with the RDF/XML format vs the OBO format?

**Comment by ignazio1977** [comment]
OBO conversion to OWL is known to be inefficient, because the OBO document is in memory while the ontology is being built. However, this shouldn't be more than twice the size of the memory required for the ontology. It might be a combination of factors here.

**Comment by ignazio1977** [comment]
I've tried 5.1.16 with Java 8 and OBO input but I can't replicate the issue. 550K axioms in a few seconds and default heap size, on a 2010 macbook.
The changes from 5.1.14 are few and shouldn't affect memory footprint.
