### ISSUE TITLE
how to avoid getting UnloadableImportException

### ISSUE THREAD

**Issue by marwa811** [owlcs/owlapi#977]
Hello,
I am trying to load an ontology named OBOE-SBC.owl, which has some imported ontologies 
  <owl:imports rdf:resource="http://ecoinformatics.org/oboe/oboe.1.0/oboe-chemistry.owl"/>
       <owl:imports rdf:resource="http://ecoinformatics.org/oboe/oboe.1.0/oboe-context.owl"/>
        <owl:imports rdf:resource="http://ecoinformatics.org/oboe/oboe.1.0/oboe-units.owl"/>
        <owl:imports rdf:resource="http://ecoinformatics.org/oboe/oboe.1.0/oboe.owl"/>
that I discovered that two of them are not working  "oboe-context.owl" and "oboe-units.owl" !!

Set<OWLOntology> importedOntologies=o.getOWLOntologyManager().getOntologies(); 
and I get the "Exception in thread "main" org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology"

how to avoid this exception?

**Comment by ignazio1977** [comment]
OWLOntologyLoaderConfiguration allows you to stop throwing exceptions on unreachable imports.

    OWLOntologyManager manager=OWLManager.createOWLOntologyManager();
    OWLOntologyLoaderConfiguration loaderConfig = new OWLOntologyLoaderConfiguration()
        .setMissingImportHandlingStrategy(MissingImportHandlingStrategy.SILENT);
    IRIDocumentSource source=new IRIDocumentSource(IRI.create("ontology IRI"));
    OWLOntology ontology = manager.loadOntologyFromOntologyDocument(source, loaderConfig);

**Comment by marwa811** [comment]
Thanks a lot .. now its working fine
