### ISSUE TITLE
Does OWLapi support Manchester syntax?

### ISSUE THREAD

**Issue by cknoll** [owlcs/owlapi#982]
I guess owlapi does support Manchester syntax, but in the [README.md](https://github.com/owlcs/owlapi/blob/version5/README.md) this feature is not listed explicitly (only mentioned in some releasenotes):

```
The following components are included:

* An API for OWL 2 and an in-memory reference implementation
* RDF/XML parser and writer
* OWL/XML parser and writer
* OWL Functional Syntax parser and writer
* Turtle parser and writer
* KRSS parser
* OBO format parser
* Reasoner interfaces for working with reasoners such as FaCT++, HermiT, Pellet, Racer, JFact and Chainsaw.
```

This is mainly a question, but maybe updating the README would be worth considering.

**Comment by ignazio1977** [comment]
The wiki has more documentation.
https://github.com/owlcs/owlapi/wiki

**Comment by cknoll** [comment]
Yes, I saw this. But that Manchester syntax is supported is not stated explicitly in the linked page. And even if it were: from my perspective as a potential user of this project, I would expect this information among the other bullet points at the top of the README.md. Just a usability suggestion.
