### ISSUE TITLE
Could not parse ontology.  Either a suitable parser could not be found, or parsing failed. 

### ISSUE THREAD

**Issue by jiguangxi** [owlcs/owlapi#983]
Exception in thread "main" org.semanticweb.owlapi.io.UnparsableOntologyException: Problem parsing file:/xxxx
Could not parse ontology.  Either a suitable parser could not be found, or parsing failed.  See parser logs below for explanation.
The following parsers were tried:
1) org.semanticweb.owlapi.rio.RioParserImpl : org.semanticweb.owlapi.formats.RioTurtleDocumentFormatFactory@95fd655c
2) org.semanticweb.owlapi.rio.RioParserImpl : org.semanticweb.owlapi.formats.NQuadsDocumentFormatFactory@6f9c39ad
3) org.semanticweb.owlapi.rio.RioParserImpl : org.semanticweb.owlapi.formats.RDFJsonDocumentFormatFactory@cd748dc3
4) org.semanticweb.owlapi.rio.RioParserImpl : org.semanticweb.owlapi.formats.NTriplesDocumentFormatFactory@937ecd36
5) org.semanticweb.owlapi.rio.RioParserImpl : org.semanticweb.owlapi.formats.TrigDocumentFormatFactory@27e81c
6) org.semanticweb.owlapi.rio.RioParserImpl : org.semanticweb.owlapi.formats.RDFJsonLDDocumentFormatFactory@dcacc47d
7) org.semanticweb.owlapi.rio.RioParserImpl : org.semanticweb.owlapi.formats.RioRDFXMLDocumentFormatFactory@69b9a3bc
8) org.semanticweb.owlapi.rio.RioParserImpl : org.semanticweb.owlapi.formats.N3DocumentFormatFactory@9a5
9) org.semanticweb.owlapi.rio.RioParserImpl : org.semanticweb.owlapi.formats.TrixDocumentFormatFactory@27e82d
10) org.semanticweb.owlapi.rio.RioParserImpl : org.semanticweb.owlapi.formats.BinaryRDFDocumentFormatFactory@3bf24493
11) org.semanticweb.owlapi.rio.RioParserImpl : org.semanticweb.owlapi.formats.RDFaDocumentFormatFactory@264e8d

Detailed logs:
--------------------------------------------------------------------------------
Parser: org.semanticweb.owlapi.rio.RioParserImpl : org.semanticweb.owlapi.formats.RioTurtleDocumentFormatFactory@95fd655c
    Stack trace:
org.eclipse.rdf4j.rio.UnsupportedRDFormatException: Did not recognise RDF format object Turtle (mimeTypes=text/turtle, application/x-turtle; ext=ttl)        org.semanticweb.owlapi.rio.RioParserImpl.parse(RioParserImpl.java:138)
        uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:194)
        uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.load(OWLOntologyManagerImpl.java:1107)
        uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1057)
        uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:1007)
        uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:1020)
        io.DictionaryInput.readTBox(DictionaryInput.java:49)
        sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Did not recognise RDF format object Turtle (mimeTypes=text/turtle, application/x-turtle; ext=ttl)        org.eclipse.rdf4j.rio.Rio.lambda$unsupportedFormat$0(Rio.java:725)
        org.eclipse.rdf4j.rio.Rio$$Lambda$115/752011518.get(Unknown Source)
        java.util.Optional.orElseThrow(Optional.java:290)
        org.eclipse.rdf4j.rio.Rio.createParser(Rio.java:102)
        org.semanticweb.owlapi.rio.RioParserImpl.parseDocumentSource(RioParserImpl.java:164)
        org.semanticweb.owlapi.rio.RioParserImpl.parse(RioParserImpl.java:125)
        uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:194)
        uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.load(OWLOntologyManagerImpl.java:1107)
        uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1057)
        uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:1007)

I am trying to parse the .owl format ontology file based on hadoop and spark using owl-api. This can be done in the local [4] mode, but an error occurs in the yarn-client mode, and the owl ontology file cannot be parsed。
 I'm using OWLAPI 5.1.11.
Any insights would be greatly appreciated.

**Comment by ignazio1977** [comment]
Can you add more details on what yarn-client mode is?

**Comment by jiguangxi** [comment]
> Can you add more details on what yarn-client mode is?

Of course. My hadoop version is 2.7.2 and spark version is 2.4.4. The cluster includes a master node and three slave nodes. executor-memory is 2G, driver-memory is 2G, 3 executors. For safety, I packaged all spark-related jars into the expected project jar package. The specific error codes are as follows:
```
        File testFile = new File(pathTBox);
        OWLOntologyManager m = OWLManager.createOWLOntologyManager();
        OWLOntology univBench = m.loadOntologyFromOntologyDocument(testFile);
```
Here, my ontology file is in .owl format

The following is the contents of the META-INF/services/ directory of my jar package:
```
javax.jdo.JDOEnhancer
javax.script.ScriptEngineFactory
org.apache.hadoop.security.token.TokenIdentifier
org.semanticweb.owlapi.model.OWLStorerFactory
javax.xml.stream.XMLEventFactory
org.openrdf.rio.RDFParserFactory
com.fasterxml.jackson.core.ObjectCodec
org.apache.commons.logging.LogFactory
org.apache.logging.log4j.message.ThreadDumpMessage$ThreadInfoFactory
org.semanticweb.owlapi.model.OWLOntologyManagerFactory
org.apache.hadoop.security.SecurityInfo
javax.annotation.processing.Processor
java.nio.file.spi.FileTypeDetector
org.eclipse.rdf4j.rio.RDFWriterFactory
org.eclipse.rdf4j.rio.LanguageHandler
org.apache.hadoop.hive.ql.io.StorageFormatDescriptor
org.glassfish.jersey.servlet.spi.AsyncContextDelegateProvider
io.fabric8.kubernetes.client.ResourceHandler
org.semanticweb.owlapi.model.OWLOntologyManager
org.apache.hadoop.crypto.key.KeyProviderFactory
javax.jdo.PersistenceManagerFactory
org.glassfish.jersey.internal.spi.ForcedAutoDiscoverable
org.apache.hadoop.io.compress.CompressionCodec
org.w3c.dom.DOMImplementationSourceList
org.apache.spark.status.AppHistoryServerPlugin
org.apache.hadoop.mapreduce.protocol.ClientProtocolProvider
org.eclipse.rdf4j.rio.DatatypeHandler
javax.xml.parsers.DocumentBuilderFactory
org.semanticweb.owlapi.model.OWLDataFactory
java.sql.Driver
org.apache.logging.log4j.util.PropertySource
javax.xml.validation.SchemaFactory
org.semanticweb.owlapi.model.OWLDocumentFormatFactory
org.semanticweb.owlapi.util.mansyntax.ManchesterOWLSyntaxParser
com.fasterxml.jackson.databind.Module
org.apache.orc.DataMask$Provider
org.apache.hadoop.security.token.TokenRenewer
org.apache.hadoop.security.alias.CredentialProviderFactory
org.apache.logging.log4j.spi.Provider
org.glassfish.jersey.internal.spi.AutoDiscoverable
org.apache.spark.ml.util.MLFormatRegister
org.apache.jena.sys.JenaSubsystemLifecycle
org.semanticweb.owlapi.io.OWLParserFactory
org.apache.spark.scheduler.ExternalClusterManager
javax.xml.datatype.DatatypeFactory
org.semanticweb.owlapi.model.OWLOntologyFactory
org.eclipse.rdf4j.rio.RDFParserFactory
javax.servlet.ServletContainerInitializer
org.glassfish.hk2.extension.ServiceLocatorGenerator
com.fasterxml.jackson.core.JsonFactory
javax.xml.parsers.SAXParserFactory
javax.ws.rs.ext.RuntimeDelegate
org.xml.sax.driver
org.eclipse.jetty.http.HttpFieldPreEncoder
io.fabric8.kubernetes.client.ServiceToURLProvider
org.apache.spark.sql.sources.DataSourceRegister
org.apache.hadoop.fs.FileSystem
io.fabric8.kubernetes.client.ExtensionAdapter
org.glassfish.jersey.servlet.spi.FilterUrlMappingsProvider
```

**Comment by ignazio1977** [comment]
We've seen similar troubles in other setups where a uber jar is running rather than the usual owlapi jars + dependencies.
The most common problem is the uber jar construction overwriting one or more files that exist with the same name in different owlapi jars. Can you check the content of these files in your services folder:

    org.semanticweb.owlapi.model.OWLStorerFactory
    org.openrdf.rio.RDFParserFactory
    org.semanticweb.owlapi.model.OWLOntologyManagerFactory
    org.eclipse.rdf4j.rio.RDFWriterFactory
    org.eclipse.rdf4j.rio.LanguageHandler
    org.semanticweb.owlapi.model.OWLOntologyManager
    org.eclipse.rdf4j.rio.DatatypeHandler
    org.semanticweb.owlapi.model.OWLDataFactory
    org.semanticweb.owlapi.model.OWLDocumentFormatFactory
    org.semanticweb.owlapi.util.mansyntax.ManchesterOWLSyntaxParser
    org.semanticweb.owlapi.io.OWLParserFactory
    org.semanticweb.owlapi.model.OWLOntologyFactory
    org.eclipse.rdf4j.rio.RDFParserFactory

They should match the files found in, e.g., owlapi-distribution.jar!/META-INF/services

In particular, the issue might be in 

    org.semanticweb.owlapi.io.OWLParserFactory

This file should contain parsers for all supported formats, but in your stack trace it looks like only RIO formats have been attempted, which makes me think your uber jar contains only the file included in the owlapi-rio jar. If the format is one not supported by RIO (owl/xml, manchester syntax, functional syntax) then no suitable parser will be found.
