### ISSUE TITLE
How to convert a String in Manchester syntax to an OWLAxiom object?

### ISSUE THREAD

**Issue by akaDudy** [owlcs/owlapi#987]
Hi,
I'm working on a plugin for a university project similar to the DLQuery tab, where the input should be converted to an OWL axiom in Manchester syntax. 
The user types a String but in order to execute that string and get the results, I need to check if the string it's written in Manchester syntax first, and then convert it to an OWL axiom so the reasoner can execute it. Could I get an example if it's not too much to ask?

Thanks a lot

**Comment by ignazio1977** [comment]
Calling the Manchester parser to parse an axiom is easy enough - use `ManchesterOWLSyntaxInlineAxiomParser`.
The difficult part of parsing an axiom is resolving the entities - i.e., in an axiom you might have IRIs such as `ex:subclass`, `sample:testProperty` and so on. To be turned into the correct entities for the axiom, it's necessary to configure an `OWLEntityChecker` instance properly. When parsing a whole ontology, the declarations are extracted from the ontology during parsing, but when parsing a string representing just one axiom the necessary infrastructure cannot be built and must be managed manually. This is the most common issue met by developers attempting to implement this functionality.

**Comment by ignazio1977** [comment]
Examples of short form provider setup can be found here:
https://github.com/owlcs/owlapi/wiki/DL-Queries-with-a-real-reasoner

Also, from unit tests:

        OWLDataFactory df = ...
       OWLOntologyManager m = ....
        OWLClass a = ...;
        OWLClass b = ...;
        String in = "A SubClassOf B";
        OWLOntology o = m.createOntology();
        m.addAxiom(o, df.getOWLDeclarationAxiom(a));
        m.addAxiom(o, df.getOWLDeclarationAxiom(b));
        // select a short form provider that uses annotations
        ShortFormProvider sfp =
            new AnnotationValueShortFormProvider(Arrays.asList(df.getRDFSLabel()),
                Collections.<OWLAnnotationProperty, List<String>>emptyMap(), m);
        BidirectionalShortFormProvider shortFormProvider =
            new BidirectionalShortFormProviderAdapter(m.getOntologies(), sfp);
        ManchesterOWLSyntaxParser parser = OWLManager.createManchesterParser();
        parser.setStringToParse(in);
        ShortFormEntityChecker owlEntityChecker = new ShortFormEntityChecker(shortFormProvider);
        parser.setOWLEntityChecker(owlEntityChecker);
        parser.setDefaultOntology(o);
        // when
        // finally parse
        OWLAxiom axiom = parser.parseAxiom();
        // then
        assertEquals(df.getOWLSubClassOfAxiom(a, b), axiom);

**Comment by akaDudy** [comment]
Thank you very much for your answer! I'll try to do what you said. Could I please ask for your help should I need it? You're the first person who's been really able to help me with this.

**Comment by ignazio1977** [comment]
Sure, no worries.

**Comment by Bonnevie** [comment]
I have a very related question, so I'll piggyback on this one here if it's alright.
I am using an entity checker of the form:

```kotlin
ShortFormEntityChecker(
            BidirectionalShortFormProviderAdapter(
                manager, _ontology.importsClosure().toList(),
                ManchesterOWLSyntaxPrefixNameShortFormProvider(format)
            )
        )
```

and it generally works well, correctly identifying short forms!
I furthermore require being able to declare new classes and defining axioms for them, and it seems that adding class declarations effectively add them to the short-form provider, so that's great. 
I tried writing some axioms using full IRIs ("http://..."), and this works too when wrapped in <>, but now the issue arises: this only seems to work for elements that were in the ontology at time of definition, and not the ones asserted via declarations.
In other words calling,
```kotlin
ontology.add(data.getOWLDeclarationAxiom(data.getOWLClass(IRI.create("http://www.ontology.net/onto#OldIri"))))
parser.setStringToParse("<http://www.ontology.net/onto#NewIri> SubClassOf: <http://www.ontology.net/onto#OldIri>")
return parser.parseAxiom()
```
fails with the exception:
```
Exception in thread "main" org.semanticweb.owlapi.manchestersyntax.renderer.ParserException: Encountered <http://www.ontology.net/onto#NewIri> at line 1 column 8. Expected one of:
	Class name
```
But resolves if I use the short form, or try to resolve the full IRI of the OldIri class instead.
(sorry if the code looks a bit off, I'm using Kotlin)

edit: it seems like I can get around the error by rebuilding the entitychecker after the declarations. Is this necessary, or can I somehow get the entity checker to refresh?

**Comment by ignazio1977** [comment]
Hi @Bonnevie 
`BidirectionalShortFormProviderAdapter` is building its internal maps on construction, so changes that happen after the class has been instantiated are not taken into account.

Workaround: instantiate a new ShortFormEntityChecker after you're done making changes, or create a new one and a new parser every time just before parsing a new string. Which one's best depends on how many changes you plan to do and when.

**Comment by Bonnevie** [comment]
Thanks Ignazio! Is there an official definition of what an "inline" axiom looks like? It seems to be slightly different from just a line in a frame?

**Comment by ignazio1977** [comment]
No definition I know of, I think this is very much syntax related. So far, I've only encountered questions about Manchester syntax - possibly because that's the only parser with an interface to pass in a string to parse to one axiom.
