### ISSUE TITLE
possible to fail ontology loading if there are unparsed triples?

### ISSUE THREAD

**Issue by balhoff** [owlcs/owlapi#988]
OWLAPI prints INFO log messages when loading from RDF and some triples have not been consumed. Is there a way to have the loader fail (e.g. throw an exception) in this situation?

This question stems from a discussion in the ROBOT tracker: https://github.com/ontodev/robot/issues/785

**Comment by ignazio1977** [comment]
'Bad idea to drop triples without throwing exceptions'
'I need to use this ontology which has some bad content and OWLAPI won't allow me'

Some fights cannot be won.

Setting parsing to strict mode should throw an exception if unparsed triples remain, to adhere to the OWL parsing specs. I don't believe it currently does that. Main problem is that the leftover triples are not very reliable - often I see info messages of that sort that seem incorrect, so some investigation might be required first.

Cue usual rant about annotations and RDF based formats. Single most complicated feature in all of OWLAPI. Building a reasoner is easier.

**Comment by balhoff** [comment]
> 'I need to use this ontology which has some bad content and OWLAPI won't allow me'
> Some fights cannot be won.

I agree that OWLAPI cannot be expected to reasonably handle any arbitrary RDF. For that reason in some situations it might be appropriate to be able to throw an error.

> Setting parsing to strict mode should throw an exception if unparsed triples remain, to adhere to the OWL parsing specs. I don't believe it currently does that. Main problem is that the leftover triples are not very reliable - often I see info messages of that sort that seem incorrect, so some investigation might be required first.

Okay, yes, an exception in strict mode would be desired. I didn't actually try this yet; we should probably add a 'strict mode' option to ROBOT.

> Cue usual rant about annotations and RDF based formats. Single most complicated feature in all of OWLAPI. Building a reasoner is easier.

I personally stick to OWL functional syntax as much as possible. 😄

**Comment by jamesaoverton** [comment]
@ignazio1977 you're absolutely right that this is a no-win situation. I apologize if my comment in the other thread was uncharitable. I know what it's like to give stuff away and then get back complaints, and to be caught in similar situations, so I should have been more circumspect.

We're building on your hard work. We couldn't do our work without what you've given us. We really appreciate it. I'm sorry that I haven't yet had a chance to thank you in person, and buy you the beverage of your choice. If there's some way we can contribute back (specific patches or tests or anything else), please let us know.

**Comment by ignazio1977** [comment]
> I apologize if my comment in the other thread was uncharitable.

No worries, yours was not the voice that I heard in my head nagging :-)

**Comment by ignazio1977** [comment]
In the meantime, leftover triples can be checked in the OWLDocumentFormat object - they're referenced there after the ontology has been parsed. See the `OWLOntologyLoaderMetaData` instance from `OWLDocumentFormat::getOntologyLoaderMetaData`.

**Comment by jamesaoverton** [comment]
Thanks @ignazio1977. I didn't know about `OWLOntologyLoaderMetaData`. We'll look into making a `--strict` flag for ROBOT that can check the size of `unparsedTriples` (among other things): https://github.com/ontodev/robot/issues/787

**Comment by ignazio1977** [comment]
#1023 revealed one bug that was leaving triples unparsed when they'd actually been parsed. This removes one of the difficulties mentioned in this thread.

**Comment by ignazio1977** [comment]
#1023 revealed one bug that was leaving triples unparsed when they'd actually been parsed. This removes one of the difficulties mentioned in this thread.
