### ISSUE TITLE
How to get every property and its name of a class ?

### ISSUE THREAD

**Issue by LazyKody** [owlcs/owlapi#995]
Hi,

for my application i need all the properties defining a given class of an ontology and their values.

As i understood, 

**1)**
there are 2 types of properties (datatype and object).
With the methods "_ontology.getDataPropertiesInSignature()_" and "_ontology.getObjectPropertiesInSignature()_" i can get them.

**2)**
The 2 sets of properties represent all properties that can be used to describe a class in the same ontology.

**3)**
Object-Properties describe relations between individuals. 
Datatype-Properties relate values to individuals ( strings, numbers, ...)

Please correct me if a am wrong so far.

The code at the end is a piece of an owl file, which represents a class.

At "_<owl:Class rdf:about="http://purl.obolibrary.org/obo/BFO_0000031"> [...] </owl:Class>_" are listed abbreviations of the property-IRIs and the specific values. 
Again, correct me if i am wrong.

Here starts my problem.

Via "_EntitySearcher.getAnnotationObjects(cls, ontology)_" i do get all the informations in "_<owl:Class rdf:about="http://purl.obolibrary.org/obo/BFO_0000031"> [...] </owl:Class>_",
**BUT**
i also need the lables (names) of these properties.
So i tried to look up for the lables in my set of properties ( refer to **1)** ) using the IRIs. But i cannot find any consensus. There are no Properties with these IRIs.
_ontology.getDataPropertiesInSignature()_ does not even deliver any properties, although according to my knowledge there are some datatype properties used by that class in the snippet below.

Questions:
Did i missunderstood something?
What do i miss?
How do i get the names of these Properties?

When i look up for one of the properties in the snipper with their IRI ( for example purl.obolibrary.org/obo/IAO_0000112) it is called "Annotation Property". Are these diffrent to Datype-Properties?

Thank you very much for your time and help.

>    <owl:Class rdf:about="http://purl.obolibrary.org/obo/BFO_0000031">
>         <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/BFO_0000002"/>
>         <obo:IAO_0000112 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">The entries in your database are patterns instantiated as quality instances in your hard drive. The database itself is an aggregate of such patterns. When you create the database you create a particular instance of the generically dependent continuant type database. Each entry in the database is an instance of the generically dependent continuant type IAO: information content entity.</obo:IAO_0000112>
>         <obo:IAO_0000112 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">the pdf file on your laptop, the pdf file that is a copy thereof on my laptop</obo:IAO_0000112>
>         <obo:IAO_0000112 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">the sequence of this protein molecule; the sequence that is a copy thereof in that protein molecule.</obo:IAO_0000112>
>         <obo:IAO_0000115 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">b is a generically dependent continuant = Def. b is a continuant that g-depends_on one or more other entities. (axiom label in BFO2 Reference: [074-001])</obo:IAO_0000115>
>         <obo:IAO_0000602>(iff (GenericallyDependentContinuant a) (and (Continuant a) (exists (b t) (genericallyDependsOnAt a b t)))) // axiom label in BFO2 CLIF: [074-001]</obo:IAO_0000602>
>         <rdfs:isDefinedBy rdf:resource="http://purl.obolibrary.org/obo/bfo.owl"/>
>         <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">generically dependent continuant</rdfs:label>
>     </owl:Class>
>     <owl:Axiom>
>         <owl:annotatedSource rdf:resource="http://purl.obolibrary.org/obo/BFO_0000031"/>
>         <owl:annotatedProperty rdf:resource="http://purl.obolibrary.org/obo/IAO_0000115"/>
>         <owl:annotatedTarget rdf:datatype="http://www.w3.org/2001/XMLSchema#string">b is a generically dependent continuant = Def. b is a continuant that g-depends_on one or more other entities. (axiom label in BFO2 Reference: [074-001])</owl:annotatedTarget>
>         <obo:IAO_0010000 rdf:resource="http://purl.obolibrary.org/obo/bfo/axiom/074-001"/>
>     </owl:Axiom>
>     <owl:Axiom>
>         <owl:annotatedSource rdf:resource="http://purl.obolibrary.org/obo/BFO_0000031"/>
>         <owl:annotatedProperty rdf:resource="http://purl.obolibrary.org/obo/IAO_0000602"/>
>         <owl:annotatedTarget>(iff (GenericallyDependentContinuant a) (and (Continuant a) (exists (b t) (genericallyDependsOnAt a b t)))) // axiom label in BFO2 CLIF: [074-001]</owl:annotatedTarget>
>         <obo:IAO_0010000 rdf:resource="http://purl.obolibrary.org/obo/bfo/axiom/074-001"/>
>     </owl:Axiom>

From ontology " http://purl.bioontology.org/ontology/HOIP "

**Comment by ignazio1977** [comment]
There's an issue here: there's a difference between data and object properties and how they relate to classes, and annotation properties used to annotate a class.

Annotation properties can be attached to most anything: classes, data or object properties, individuals, axioms, other annotations. Data and object properties, on the other hand, cannot - they connect individuals to literals or to other individuals (data for the first case, object for the second). They're not 'properties of a class', but rather ' a class can be defined to be the domain or range, or part of the domain or range, of a property'.

In your case you seem to be looking for annotation properties rather than other properties - as object and data properties wouldn't appear in this snippet of XML.

In the code you're using you should be getting a collection or a stream of `OWLAnnotation` objects, where you'd get access to the `OWLAnnotationProperty` used in the annotation via `OWLAnnotation::getProperty`. Not sure whether you're after the annotation IRI or any `rdfs:label` that the property might have been annotated with; if the first, the `OWLAnnotationProperty` object is enough; if the second, then you'd do something like:

    OWLAnnotation a = ... from the previous call
    OWLAnnotationProperty p = a.getProperty();
    // this will return all annotations that use rdfs:label
    EntitySearcher.getAnnotations(p, ontology, dataFactory.getRDFSLabel());
